### ISSUE TITLE
Question on thread safety

### ISSUE THREAD

**Issue by dlaidlaw** [kubernetes-client/java#100]
Which objects in the API are thread-safe? I assume the ApiClient is thread safe, since it is stored statically in the Configuration. Are the various API objects, such as CoreV1Api also thread-safe?

**Comment by brendandburns** [comment]
As far as I know, everything in the library is stateless, so everything should be thread-safe.

But under the hood the code is generated by swagger-codegen and uses the okhttp library, so we're relying on them, see:

https://github.com/square/okhttp/wiki/Concurrency

And here's the basic ApiClient code:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache

**Comment by davidwcarlson** [comment]
The [sample client docs](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/java/okhttp-gson) for okhttp-gson contains the (possibly boilerplate) message:

> It's recommended to create an instance of `ApiClient` per thread in a multithreaded environment to avoid any potential issues.
