### ISSUE TITLE
Implement base interface for most Kubernetes objects

### ISSUE THREAD

**Issue by dlaidlaw** [kubernetes-client/java#101]
Most of the Kubernetes objects have a set of fields in common:

- kind
- apiVersion
- metadata
- spec

The objects that support this really need to reflect that by implementing an interface and possibly extending a base class.

**Comment by brendandburns** [comment]
This has to happen via Swagger, I added this: 

https://github.com/kubernetes/apiserver/issues/23

To track.

**Comment by vibhupratap** [comment]
Was any work done on this. This will be very useful

**Comment by russgold** [comment]
The Swagger issue keeps getting marked as 'stale'.

**Comment by brendandburns** [comment]
Closing this since we now have this support with `KubernetesObject` and `KubernetesListObject`
