### ISSUE TITLE
createNamespacedControllerRevision question

### ISSUE THREAD

**Issue by chlung** [kubernetes-client/java#102]
Hi,

When I create a DaemonSet with RollingUpdate in UpdateStrategy, does it automatically enable ControllerRevision?  When do I need to make api call for `createNamespacedControllerRevision`?

Thanks.

**Comment by brendandburns** [comment]
You shouldn't need to use this call afaik. It exists, since it is a public API on the k8s apiserver, but I believe that only the DeploymentController needs to create them.

**Comment by chlung** [comment]
@brendandburns  Great.  Thanks.
