### ISSUE TITLE
patchNamespacedConfigMap

### ISSUE THREAD

**Issue by lehy786** [kubernetes-client/java#1043]
Hi, I would like to ask about...
what is the `body` param actually looks like at patchNamespacedConfigMap from release 4.0.0?
should I just put the V1ConfigMap into it?
please!

**Comment by brendandburns** [comment]
Have a look at the PatchExample here:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java
