### ISSUE TITLE
[documentation]  Question on Compatibility matrix and Instructions for Maven/Gradle

### ISSUE THREAD

**Issue by ramanNarasimhan77** [kubernetes-client/java#1049]
Hello,
I have a kubernetes environment with version 1.18.0. 
While running an application that uses kubernetes java client version 6.0.1, I faced some errors due to missing value for metadata.managedFields.fieldsType. I believe this is caused by using incorrect client version.

I am trying to figure out which kubernetes versions are compatible with k8s java client version 6.0.1 and which version to use with kubernetes 1.18.0 so that I can co-ordinate with the application developer and work on either getting the compatibility issue fixed or downgrade the kubernetes version on the cluster.

For this purpose, I tried checking the readme available for recent releases and have not been able to figure this out.
Is there someplace that I can lookup to get the up-to-date dependency matrix and correct maven dependencies?

#### Maven version set as 5.0.0

<img width="869" alt="image" src="https://user-images.githubusercontent.com/52691361/86885759-71712000-c113-11ea-81a1-1ceb7f40235b.png">

#### Compatibility matrix 

<img width="634" alt="image" src="https://user-images.githubusercontent.com/52691361/86885791-7cc44b80-c113-11ea-8865-eff3efabf003.png">

#### Maven dependency is still having version 5.0.0

<img width="875" alt="image" src="https://user-images.githubusercontent.com/52691361/86887740-a7fc6a00-c116-11ea-9d74-2ebece7186a3.png">

#### Compatibility matrix is missing entries for 8.x client versions

<img width="587" alt="image" src="https://user-images.githubusercontent.com/52691361/86887756-ad59b480-c116-11ea-84ad-1c836109e85d.png">

**Comment by brendandburns** [comment]
You can find the matrix here:
https://github.com/kubernetes-client/java#compatibility

8.0.2 corresponds to Kubernetes 1.16

We should probably cut a `9.x.y` soon to provide 1.17 support (and eventually a `10.x.y` after that with 1.18 support, or perhaps )

Regardless the library should work properly with 1.18 for most objects, it would only be alpha/beta objects where there are some problems.

I would definitely recommend the 8.0.2 library though it has a lot of bug fixes in addition to revised client code.

**Comment by brendandburns** [comment]
I'm closing this issue as I believe that the question has been resolved. Please use `/reopen` if you need further assistance on this issue.
