### ISSUE TITLE
change pod from a node to another in runtime

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [kubernetes-client/java#105]
Hi everybody.
I saw in k8 tutorial that we can select the node where we want to deploy a pod. It is using the nodeSelector.
So, I am trying to change this property while my k8 application is running.
My main class has this code to set a new node selector:

`public class Test {

	public static void main(String[] args) throws FileNotFoundException, ApiException {
		final String podName = "etcd-swarm1";

		//final String oldNode = "swarm1";
		final String newNode = "swarm5";
		
		PodAbstraction podAbstraction = new PodAbstraction(podName, newNode);
		RuntimeDealer runtimeDealer = new RuntimeDealer();
		V1Pod pod = runtimeDealer.searchPod(podName);
		
		podAbstraction.updateNodeSelector(pod);	
				
	}

}`

And, my _podAbstraction_ class, has the method _updateNodeSelector()_, which is:

```
public void updateNodeSelector(V1Pod pod) {	
	//System.out.println("the pod is on node : "+"\n"+pod.getSpec().toString());
	pod.getSpec().setNodeSelector(this.nodeSelector);
	pod.getSpec().setNodeName("swarm5");
	System.out.println("and now it is on node: "+pod.getSpec().getNodeName());
}
```

Aparently it is now enough to make a pod leave on node to another (in my case, I am trying to move the pod 
_etcd-swarm1_ from the node _swarm1_ to the node _swarm5_).

Finally, I got this message on my terminal after running this java-client program( I have abstracted some comands here):

```
vinicius@vinicius-VPCEG17FB:~/Documentos$ kubectl  get pods -o wide 
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
etcd-swarm1                             1/1       Running   0          20d       10.66.66.23   swarm1
```
As you can see, it has not been moved.
Does someone has any idea of how I can complete the task of moving a pod from a node to another one?
Thanks

**Comment by lwander** [comment]
I think you'll have to send that updated `V1Pod` back to the Kubernetes master for that change to be reflected. You can send a patch request with `patchNamespacePod(..)` in the `CoreV1Api`.

**Comment by ViniciusDeAndrade** [comment]
this way is good enough?
```
public void updateNodeSelector(V1Pod pod) throws ApiException {		
	pod.getSpec().setNodeSelector(this.nodeSelector);
	pod.getSpec().setNodeName("swarm5");
		
	String podName = pod.getMetadata().getName();
	String podNamespace = pod.getMetadata().getNamespace();		
		
	K8Instance.getInstance().patchNamespacedPod(podName, podNamespace, null, null);
	System.out.println("and now it is on node: "+pod.getSpec().getNodeName());
		
}
```

PS.: I did not understand all the parameters yet.

**Comment by lwander** [comment]
Well I don't know what `K8Instance.getInstance()` is, but you definitely need to pass the diff between the current pod and the desired pod to your `patchNamespacedPod` call. Take a look at what kubectl does when you edit a pod in detail by passing `-v 9` as a flag.

**Comment by ViniciusDeAndrade** [comment]
I have tried to use a example given [here, in this page samples](https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CoreV1Api.md#patchNamespacedPod)
But I still got errors:

```
Exception when calling CoreV1Api#patchNamespacedPod
io.kubernetes.client.ApiException: Missing the required parameter 'body' when calling patchNamespacedPod(Async)
	at io.kubernetes.client.apis.CoreV1Api.patchNamespacedPodValidateBeforeCall(CoreV1Api.java:19194)
	at io.kubernetes.client.apis.CoreV1Api.patchNamespacedPodWithHttpInfo(CoreV1Api.java:19233)
	at io.kubernetes.client.apis.CoreV1Api.patchNamespacedPod(CoreV1Api.java:19218)
	at main.Example.main(Example.java:40)

```

OMG, What is going on?

Here is the code:
```

package main;

import java.io.FileNotFoundException;
import java.io.FileReader;

import io.kubernetes.client.ApiClient;
import io.kubernetes.client.ApiException;
import io.kubernetes.client.Configuration;
import io.kubernetes.client.apis.CoreV1Api;
import io.kubernetes.client.auth.ApiKeyAuth;
import io.kubernetes.client.models.V1Pod;
import io.kubernetes.client.util.Config;
import io.kubernetes.client.util.KubeConfig;

/**
 * patch pod example from 
 * https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CoreV1Api.md#patchNamespacedPod
 * @author vinicius
 *
 */
public class Example {
	public static void main(String[] args) throws FileNotFoundException {
		//setting the environment
		final String pathToGfadsConfigFile = "/home/vinicius/Documentos/gfads-test.config";
		FileReader gfadsConfigFile = new FileReader(pathToGfadsConfigFile);
		KubeConfig kc = KubeConfig.loadKubeConfig(gfadsConfigFile);
		ApiClient client = Config.fromConfig(kc);
		Configuration.setDefaultApiClient(client);


		CoreV1Api apiInstance = new CoreV1Api();

		String name = "name_example"; // String | name of the Pod
		String namespace = "namespace_example"; // String | object name and auth scope, such as for teams and projects
		Object body = null; // Object | 
		String pretty = "pretty_example"; // String | If 'true', then the output is pretty printed.


		try {
			V1Pod result = apiInstance.patchNamespacedPod(name, namespace, body, pretty);
			System.out.println(result);
		} catch (ApiException e) {
			System.err.println("Exception when calling CoreV1Api#patchNamespacedPod");
			e.printStackTrace();
		}

	}
}
```

**Comment by lwander** [comment]
Those example are auto-generated, and might not be great, sorry about that.

Looks like `Object body = null; // Object`, and the error message "Missing the required parameter 'body' when calling patchNamespacedPod(Async)" is pointing us in the right direction. If you want to see what you need to send as the body, you can use `kubectl` to help: `kubectl edit pod <pod name> -v 9` will print all http traffic on STDERR and show you how to format your request.

You can also take a look at how I used the patch methods & generated the body using JsonDiff [here](https://github.com/spinnaker/clouddriver/pull/1868/files#diff-150b8912ec8e0cd49b16cb79345b11e7R98).

**Comment by brendandburns** [comment]
fwiw, I don't think patch is what you want here (it does a `PATCH` which probably isn't what you want) I think you want a `PUT` in which case you want: `replaceNamespacedPod`.

**Comment by ViniciusDeAndrade** [comment]
Mr. Wander, I was trying to copy your **patchDeployment method,** but I got a problem. 
This method calls another one called **determineJsonPatch**, witch deals with a Object that that is not on the default API, the **ObjectMapper**.

Also, there is more one thing. These methods works with a Map[], but what is it? The Map I know is a Map< T , T >;

Since now, I thank you for all your help

**Comment by ViniciusDeAndrade** [comment]
If someone can see what is going on, I have made my code simpler with just 2 classes.
One main, and one with some simple methods, easy to understand/abstract ('cause they work) and two print near the end of the main class, which just the first works before the **patch** method.
[the code is here](https://github.com/ViniciusDeAndrade/k8-runtime/tree/master/k8-runtime/src/main/java) . 

Thank you all.

**Comment by lwander** [comment]
@brendandburns makes a good point, you should be able to get away with calling `replaceNamespacePod` which will take a `V1Pod` as an argument, instead of an arbitrary json path. That list of maps is described here: http://jsonpatch.com/. The `ObjectMapper` just helps serialize the k8s client resources into JSON & `Map<String, Object>` types.

**Comment by brendandburns** [comment]
I'm going to close this as it is a request for help rather than a true issue...

**Comment by brendandburns** [comment]
(feel free to ask for more help and re-open, though, if need be)
