### ISSUE TITLE
Cut a 9.0.0 release?

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1050]
cc @yue9944882 do you think we should cut a 9.0.0 release to enable 1.17 support and then re-gen for 1.18?

**Comment by yue9944882** [comment]
@brendandburns SGTM!

**Comment by samtonyclarke** [comment]
Any idea when a 9.0.0 release might be made?

**Comment by bgruenefeld** [comment]
we are planing to move to k8s v 1.18.
can you give me a date when you are done adjusting the java client so that it works for k8s v 1.18?

**Comment by brendandburns** [comment]
@bgruenefeld once #1100 merges we will regenerate w/ 1.18, After that we will probably nearly immediately do a release 10.0.0 with support for 1.18.

However, this library should work with 1.18 for most scenarios today, it just won't have any API changes that happened in 1.18 (those should be pretty limited)
