### ISSUE TITLE
How to use kubernetes-client/java  implement  the command of kubectl drain

### ISSUE THREAD

**Issue by Fly0905** [kubernetes-client/java#1069]
kubectl drain <node name>

**Comment by yue9944882** [comment]
it's not currently supported. but i pinned it somewhere else to track the discussions/progress.

**Comment by brendandburns** [comment]
Just to add more context:

Kubectl drain is a complicated operation that involves marking a node as unschedulable, and then removing all of the pods.

The code for it is here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/drain/drain.go#L289

**Comment by Fly0905** [comment]
Tanks，I will use a shell script to exec kubectl drain in my project

**Comment by Fly0905** [comment]
Thanks，I will use a shell script to exec kubectl drain in my project
