### ISSUE TITLE
Update PatchExample to not use Deployment from extensions/v1beta1

### ISSUE THREAD

**Issue by php-coder** [kubernetes-client/java#1075]
The `PatchExample` work with Deployment from deprecated `extensions/v1beta1` API group that [was removed in Kubernetes 1.16](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/):

https://github.com/kubernetes-client/java/blob/bd8c85771008c266673e2163e4bebd7f7b29f646/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java#L48-L51

This (and possibly others) example should be updated to use Deployment from `apps/v1` instead.

**Comment by brendandburns** [comment]
Would be happy to take a PR to fix this.

**Comment by sarveshkaushal** [comment]
Do we want to change the `ExtensionV1beta1Deployment` to `V1Deployment` by using `AppsV1Api`?
