### ISSUE TITLE
Forbidden error while trying to run the application

### ISSUE THREAD

**Issue by VenkateshwaraUsirikayala** [kubernetes-client/java#1080]
Hi,

I am trying to get the pods information using the Kubernetes Java APIs, but when I try to get execute the program it throws an error saying 'io.kubernetes.client.openapi.ApiException: Forbidden' whereas if I try to fetch the pods information from the terminal with the same kubeconfig file I can get the pods info. 

Need some help with this.

Regards,
Venky

**Comment by yue9944882** [comment]
are you following the [example](https://github.com/kubernetes-client/java/blob/31fbb3a52c6ca7a6ad6d71cd154b387191705adc/examples/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java#L41-L42) to load the kubeconfig?

**Comment by brendandburns** [comment]
If you are correctly loading the KubeConfig file, it's possible that your authentication method is unsupported. Can you attach your kubeconfig? Obviously please anonymize any secret information (e.g. certificates, tokens, IP addresses) before attaching.

**Comment by VenkateshwaraUsirikayala** [comment]
[kubeconfig.txt](https://github.com/kubernetes-client/java/files/4941957/kubeconfig.txt)

Here is the attached kubeconfig. Please let me know if there is some configuration to be added.

**Comment by VenkateshwaraUsirikayala** [comment]
> are you following the [example](https://github.com/kubernetes-client/java/blob/31fbb3a52c6ca7a6ad6d71cd154b387191705adc/examples/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java#L41-L42) to load the kubeconfig?

Yes, I just have copy-pasted the code and using my kubeconfig

**Comment by sarveshkaushal** [comment]
Can you provide full stack trace?

**Comment by VenkateshwaraUsirikayala** [comment]
Exception in thread "main" io.kubernetes.client.openapi.ApiException: Forbidden
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:979)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:19189)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:19161)

This is the stack trace while running the application.

**Comment by VenkateshwaraUsirikayala** [comment]
closing this issue, as I don't have access to few namespaces but trying to fetch information from them. Figured out the solution by finding the right namespace for which I have access to
