### ISSUE TITLE
Leader Elect Lock has no ownerReference

### ISSUE THREAD

**Issue by samtonyclarke** [kubernetes-client/java#1089]
When the go operator-sdk creates a lock for leader election it adds an [owner reference](https://github.com/operator-framework/operator-lib/blob/main/leader/leader.go#L142) so that it gets cleaned up on deletion. I don't see the same functionality in the Java Kubernetes client. Is there a plan to add support?

**Comment by yue9944882** [comment]
i just skimmed the code and noticed that the crafted owner reference is actually the pod namespace/name in which the application runs --- that additionally requires the application to be running in a cluster. but i suppose it's good to make it an opt-in feature. one reasonable implementation i can think of will be providing another constructor for explicitly setting the owner reference. or as a prompt walkaround we can extend [the resource-lock class](https://github.com/kubernetes-client/java/blob/9dae95dac762cf979c2ace3334feb52f0232a5f8/extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java#L46) to override the `create` method.
