### ISSUE TITLE
Could Copy avoid tar dependency?

### ISSUE THREAD

**Issue by takeshi-yoshimura** [kubernetes-client/java#1091]
I am testing `io.kubernetes.client.Copy`, but it requires `tar` is installed in the target container.
I workaround this by adding it to my image, but it would be nice if we removed that requirement.

**Comment by yue9944882** [comment]
i believe we need an upstream support to remove tar requirement, see https://github.com/kubernetes/kubernetes/issues/58512. in terms of docker runtime, it already supports runtime-level copy for a period of time but sadly it's not supported in the unified container-runtime interface.

**Comment by brendandburns** [comment]
Some utility is required (e.g. it will never work with a `scratch` container without runtime support)

I'm open to alternative implementations (e.g. base64, bzip2, etc) if something seems better but `tar` is pretty universal.

**Comment by yue9944882** [comment]
i suppose `cat $file | base64` can be an alternative, but it can take much longer time than the tar approach..

**Comment by sarveshkaushal** [comment]
We keep `tar` utility but if tar fails then may be try to do `cat'??

**Comment by sarveshkaushal** [comment]
Should we check for both cpio and tar?

**Comment by takeshi-yoshimura** [comment]
I understand we need runtime supports for running Copy on all images. But, fall back to cat seems enough for my tested containers. I finally run it with multiple file copies instead of directory copy.

**Comment by brendandburns** [comment]
I'm ok with coding a fallback to `cat` we can use `which tar` to figure out if `tar` is present.

**Comment by brendandburns** [comment]
I wonder if we could also use ephemeral containers:

**Comment by sarveshkaushal** [comment]
> I'm ok with coding a fallback to `cat` we can use `which tar` to figure out if `tar` is present.

I will take a look at this.

**Comment by brendandburns** [comment]
I'm closing this since #1107 merged.

**Comment by Ilhicas** [comment]
I don't follow, we went from, no tar, let's fallback to having two other binaries? which and cat?
I'm using a distroless image, and people with from scratch and binaries won't have those as well.
Is there any impediment preventing the use of "binaryless" containers to make a cp from those containers such as in docker?
