### ISSUE TITLE
Is it possible to select specific cluster when using ~/.kube/config with multiple clusters defined ?

### ISSUE THREAD

**Issue by rgombash** [kubernetes-client/java#1094]
If multiple clusters are present in config, one that is selected by "kubectl config use-context cluster_name" and written in config under "current-context:" is used by defult. Is it possible to select other defined clusters?

**Comment by yue9944882** [comment]
yes, you can switch the context by explicitly calling `KubeConfig#setContext(<targetContextName>)`, and here is an example for loading kubeconfig from filepath:

https://github.com/kubernetes-client/java/blob/9dae95dac762cf979c2ace3334feb52f0232a5f8/examples/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java#L41-L42

**Comment by brendandburns** [comment]
Closing this since the question is answered.

**Comment by rgombash** [comment]
Thanks a lot!
