### ISSUE TITLE
listNamespacedControllerRevision and readNamespacedControllerRevision questions

### ISSUE THREAD

**Issue by chlung** [kubernetes-client/java#110]
Hi,
I have two questions.

1.     Call `readNamespacedControllerRevision`, but get "Not Found".  If I make the api call listNamespacedControllerRevision, I can get result back.

apiInstance.readNamespacedControllerRevision(name, namespace, null, null, null)

2.    Call listNamespacedControllerRevision and fail to get `item(0).data` from result.  The result only contains `item(0).metadata`.

apiInstance.listNamespacedControllerRevision(namespace, pretty, null, null, null, "app=abc", 10, null, 30, null)

Thanks

**Comment by brendandburns** [comment]
Closing this as it is a request for help and it is pretty old at this point. Please re-open a new issue if there are still issues here.
