### ISSUE TITLE
How to watch k8s

### ISSUE THREAD

**Issue by OIUE** [kubernetes-client/java#1106]

**Comment by brendandburns** [comment]
There are two examples:
InformerExample:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java

WatchExample:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

**Comment by OIUE** [comment]
> There are two examples:
> InformerExample:
> https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java
> 
> WatchExample:
> https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

Thanks

add this code

```
        OkHttpClient httpClient = client.getHttpClient().newBuilder().readTimeout(0, TimeUnit.SECONDS).build();
        client.setHttpClient(httpClient);
```
