### ISSUE TITLE
enqueue_mapped functionality

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [kubernetes-client/java#1108]
The controller runtime has way to register secondary resources and have the reconciler be called via the main resource. See [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/handler/enqueue_mapped.go). Without this ability it looks like you have to implement two separate controllers, one for the primary resource and one for the secondary resource. Is there a plan to support this enqueue mapped functionality?

**Comment by yue9944882** [comment]
IIUC, watching multiple resources (primary & secondary) is already supported. you can call `watch` multiple times to spawn multiple watches for single controller.

https://github.com/kubernetes-client/java/blob/95d25f9c8200d863c4d06687f1ac961c6105d58f/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java#L87

**Comment by tony-clarke-amdocs** [comment]
But this is not the same thing. You can add multiple watches that have the same reconciler but then the problem is that the reconciler cannot know which of the resources it is being called for. What the enqueue_mapped provides is a mapping from the secondary resource to the primary resource so that the reconciler always gets called with the mapped primary resource. The client code looks something like:
```
	err = c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestsFromMapFunc{
		ToRequests: handler.ToRequestsFunc(func(bindingObject handler.MapObject) []reconcile.Request {
			return getAllReconcileRequestList(bindingObject.Meta.GetName(), bindingObject.Meta.GetNamespace())
		}),
	})

        func getAllReconcileRequestList(configmapName string, namespace string) []reconcile.Request {
	requests := []reconcile.Request{}

	prs := model.GetModel().GetPrimaryReferencingConfigMap(configmapName)
	for _, v := range prs {
		requests = append(requests, reconcile.Request{
			NamespacedName: types.NamespacedName{
				Namespace: namespace,
				Name:      v,
			},
		})
	}
	return requests
}

```

Another thing that you can do with the go controller runtime is requested to be notified about secondary resources owned by the primary resource. Again, when the reconciler is called it is called with the primary resource. The client code looks something like:
```
        subresources := []runtime.Object{
		&corev1.ConfigMap{},
	}

	// watch for all instances of these subresources that are owned by the Primary
	for _, subresource := range subresources {
		err = c.Watch(&source.Kind{Type: subresource}, &handler.EnqueueRequestForOwner{
			IsController: true,
			OwnerType:    &drv1beta1.PrimaryType{},
		})
		if err != nil {
			return err
		}
	}
```

**Comment by yue9944882** [comment]
thanks @tony-clarke-amdocs! frankly i wasn't aware of this utility in controller-runtime before, but this is indeed a convincing use-case. i will take a stab on porting the implementation.

**Comment by yue9944882** [comment]
> as for non-spring construction of controllers, you can pass a key-func instance which holds work-queue instance and manually pushes events to the queue by its customized logic. however, for the versions before 9.0.0, you will have to push a dummy controller-request to the queue and handle it explicitly in your reconciler b/c null return value is not supported..

i opened https://github.com/kubernetes-client/java/pull/1118 to provide the extensibility. the good news is that if you're using non-spring construction of controller, you're free to walk-around by the trick i mentioned in the pull..
