### ISSUE TITLE
[Chore]Git pre-commit configuration

### ISSUE THREAD

**Issue by sarveshkaushal** [kubernetes-client/java#1114]
I was thinking of adding a pre-commit hook to the project which will format the code using `mvn spotless` plugin if user has forgot to run formatting before committing.
We will have to add a `pre-commit` executable in `PROJECT_ROOT/.git/hooks` directory. Contents of file are attached.

```
#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "Running Maven clean test for errors"
# retrieving current working directory
CWD=`pwd`
MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# go to main project dir
cd $MAIN_DIR/../../
# Run spotless to format code
mvn spotless:apply
if [ $? -ne 0 ]; then
  "Error while formatting the code"
  # go back to current working dir
  cd $CWD
  exit 1
fi
# go back to current working dir
cd $CWD
```

Do you think this will help prevent build failures when a user missed running formatting?

**Comment by brendandburns** [comment]
Sounds good to me, we do this in the javascript repo and it works well. We should consider running unit tests too.

**Comment by sarveshkaushal** [comment]
But that will increase the time of commit. Our test cases take a few minutes to run. If that's ok.

**Comment by brendandburns** [comment]
Its ok if we just run spotless first. (though it's fairly slow too :)

**Comment by sarveshkaushal** [comment]
Yes I agree. I am facing problem while trying to add this under `.git` folder. Git is not even recognizing this folder.
