### ISSUE TITLE
Cut a 10.0.0 release?

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1120]
We just cut a 9.0.0 release, but it might make sense to also cut a 10.0.0 with 1.18 library support.

On the other hand, 1.18 removes the `v1beta1/Deployment` APIs so it will definitely be a breaking change for some folks.

@yue9944882 wdyt?

**Comment by yue9944882** [comment]
SGTM, would be better if get more progress on Kubectl equivalence before the next release

**Comment by brendandburns** [comment]
Ok, let's finish up the initial kubectl work and then do a 10.0.0.

**Comment by brendandburns** [comment]
@yue9944882 do you think we're ready for a release? Most of the kubectl stuff is in.

**Comment by yue9944882** [comment]
i think we're getting really close, how about we get `kubectl get` (#1251) and `kubectl delete` and `kubectl replace` before we cut a new release?

**Comment by brendandburns** [comment]
ok, works for me. There are a number of bug fixes that we've accumulated so I'd like to get it done soon.

I'll take on delete and replace.

**Comment by yue9944882** [comment]
@brendandburns how you do think about cutting a new release this week?

**Comment by brendandburns** [comment]
I will do it!
