### ISSUE TITLE
How can I copy my files to pod ?

### ISSUE THREAD

**Issue by juyiwang7** [kubernetes-client/java#1127]
I want to copy the files to the pod，and my code is like this:
```
String kubeConfigPath = "config-k8s";
String namespace = "xx";
String podName = "jxxx";
ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();
Configuration.setDefaultApiClient(client);

Copy copy = new Copy();
copy.copyFileToPod(namespace,podName,null, Paths.get("/home/array/ToWord.pdf"),Paths.get("/home/jovyan/"));
```

No error message was reported, but the copy failed！Can someone provide me with a correct copy of the sample code?

**Comment by juyiwang7** [comment]
And how to release resources,for example inputstream.close(),but I cant't how to close client in kubernetes-client/java.As a result,my function  never exits.

**Comment by sarveshkaushal** [comment]
What you are doing here looks correct to me. Not sure why the copy is failing. Do you have `tar` present in target pod?

**Comment by juyiwang7** [comment]
Yes ,I hava tar in the pod. You can visit below url,I use tar in the pod.
```
https://img-blog.csdnimg.cn/20200801080324247.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NDYxNzcyMg==,size_16,color_FFFFFF,t_70
```

**Comment by brendandburns** [comment]
When you say 'failed' what do you mean? Does it throw an exception? Does it just not copy anything?

The Copy code ultimately calls `Exec` with the tar command. If you run the tar command yourself via `Exec.java` you may get more information.

**Comment by juyiwang7** [comment]
It works,but not complete。I tried run the function,64M only copies 20M to zhe pod. But when I debug the function,it can be copied complete. There is no error message while running or debugging.

**Comment by juyiwang7** [comment]
My code:
```
File srcFile = new File(filePath);
        ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();
        Configuration.setDefaultApiClient(client);
        Exec myExec = new Exec(client);
        final Process proc =
                myExec.exec(namespace, podName, new String[] {"sh", "-c", "base64 -d | tar -xmf - -C " + destDir},
                        null,true,false);
        try {
            ArchiveOutputStream archiveOutputStream =
                    new TarArchiveOutputStream(
                            new Base64OutputStream(proc.getOutputStream(), true, 0, null));
            FileInputStream input = new FileInputStream(srcFile);

            ArchiveEntry tarEntry = new TarArchiveEntry(srcFile, srcFile.getName());
            archiveOutputStream.putArchiveEntry(tarEntry);
            // When I debug here,user F8 ,the file can be copy complete. If I use F9 before the function,the copy will be not complete.
            long copy = ByteStreams.copy(input, archiveOutputStream);
            archiveOutputStream.closeArchiveEntry();
            input.close();
        } catch (Exception e){
            e.printStackTrace();
        } finally {
            proc.destroy();
        }
```

**Comment by brendandburns** [comment]
I think you need to call `archiveOutputStream.flush()` before you call `input.close()`

**Comment by juyiwang7** [comment]
No,it doesn't works!I have tried to add this code.

**Comment by netikras** [comment]
Related: https://github.com/kubernetes-client/java/issues/1310 (the reason both your and mine implementations were failing, i.e. not copying all the data to the pod)

**Comment by yuanbaodong** [comment]
Are you solve this  problem ?

**Comment by yuanbaodong** [comment]
Are you solve this?

**Comment by netikras** [comment]
@yuanbaodong yes, I have solved it.
Either wait for the PR to be merged and a new version released, or implement the same mechanism in your own code.

See the code snippet in my issue.

**Comment by yuanbaodong** [comment]
@netikras   thanks ,  I have solved it too

**Comment by yuanbaodong** [comment]
https://github.com/kubernetes-client/java/issues/1311
