### ISSUE TITLE
Utility code to create configmap from multiple files in a directory?

### ISSUE THREAD

**Issue by pravindamodaran** [kubernetes-client/java#1129]
I'm looking to create configmap from a directory (basically add all files in the directory to a single configmap), same as this:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-directories

Is there a way to do it using java api's?

**Comment by brendandburns** [comment]
You will have to do it yourself. Create a `V1ConfigMap` object and then read the files in and add them to the `binaryData` field in the `ConfigMap` resource.

There's no utility to do this currently (though we'd gladly take a PR to add such utility)

**Comment by sarveshkaushal** [comment]
@brendandburns - does this still require work?
