### ISSUE TITLE
Shutdown of SharedProcessor 

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [kubernetes-client/java#1134]
I believe the shutdown of the shared processor is designed to be graceful. It will wait one minute for each informer. This means that for each informer it will wait one minute. These waits are not done in parallel but in sequence. This means that if you have say 10 informers it will wait 10 minutes. It doesn't seem correct? Furthermore, it would be nice if there was a way to say "don't wait, just shutdown now" for testing.

**Comment by yue9944882** [comment]
>  It will wait one minute for each informer. This means that for each informer it will wait one minute.

it doesn't wait for a constant period of time. the `stop()` call of a shared processor returns if its managed thread pool completely terminated and 1 min is the timeout. the following test shows that the workers managed by shared processor is signalled upon `stop()`. can you show us a minimal re'pro code snippet?


https://github.com/kubernetes-client/java/blob/master/util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java#L85-L102

**Comment by dddddai** [comment]
>  it would be nice if there was a way to say "don't wait, just shutdown now" for testing.

You may give the timeout in the constructor.
```java
public SharedProcessor(ExecutorService threadPool, Duration timeout) {
  this.listeners = new ArrayList<>();
  this.syncingListeners = new ArrayList<>();

  this.executorService = threadPool;
  this.timeout = timeout;
}
```
btw,how about setting the timeout in `stop`? Maybe It seems easier to understand than using a constructor.@yue9944882

just like this
```java
public void stop() {
  stop(Duration.ofMinutes(1));
}

public void stop(Duration timeout) {
  ...
}
```

**Comment by tony-clarke-amdocs** [comment]
> @yue9944882 can you show us a minimal re'pro code snippet?

I think an existing [test](https://github.com/kubernetes-client/java/blob/client-java-parent-9.0.0/util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java#L59) demonstrates the issue. 
```
mvn -Dtest=DefaultSharedIndexInformerTest#testNamespacedPodInformerNormalBehavior test
...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 64.522 s - in io.kubernetes.client.informer.impl.DefaultSharedIndexInformerTest

```
This test waits one minute because there is just one informer. If there is another informer it will wait another minute. See [here](https://github.com/kubernetes-client/java/blob/client-java-parent-9.0.0/util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java#L213)

> @dddddai You may give the timeout in the constructor.

But the constructor with the timeout is not accessible from DefaultSharedIndexInformer. See [here](https://github.com/kubernetes-client/java/blob/client-java-parent-9.0.0/util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java#L97).

**Comment by yue9944882** [comment]
> I think an existing test demonstrates the issue.

thanks, after reproducing in my local environment, i find that the crux is that the works managed by `SharedProcessor#executor` are all long-running thread --- they don't exit unless we signal --- so it doesn't make sense to shutdown the thread pool by `shutdown()` which tries draining the pool but doesn't interrupt instead we should use `shutdownNow()`. i opened #1140 and it looks working
