### ISSUE TITLE
GenericKubernetesApi:watch(String namespace...) does not honor the namespace passed in

### ISSUE THREAD

**Issue by zzur** [kubernetes-client/java#1143]
Code inspection on master reveals the wrong method being called (cluster vs namespaced): should have been listNamespacedCustomObjectCall() it seems.

Events from other namespaces are delivered by the watcher...

-----------------------------

public Watchable<ApiType> watch(String namespace, final ListOptions listOptions)
      throws ApiException {
    if (Strings.isNullOrEmpty(namespace)) {
      throw new IllegalArgumentException("invalid namespace");
    }
    Call call =
        customObjectsApi.listClusterCustomObjectCall(
            this.apiGroup,
            this.apiVersion,
            this.resourcePlural,
            null,
            listOptions.getContinue(),
            listOptions.getFieldSelector(),
            listOptions.getLabelSelector(),
            listOptions.getLimit(),
            listOptions.getResourceVersion(),
            listOptions.getTimeoutSeconds(),
            true,
            null);

    return Watch.createWatch(
        customObjectsApi.getApiClient(),
        call,
        TypeToken.getParameterized(Watch.Response.class, apiTypeClass).getType());
  }

**Comment by brendandburns** [comment]
Acknowledged. Fix (and test) is in #1145
