### ISSUE TITLE
okhttp3 issues with openjdk8 > 8u251 and http/2

### ISSUE THREAD

**Issue by fabiokung** [kubernetes-client/java#1149]
Hello, we are seeing the same issues described at fabric8io/kubernetes-client#2212 with the official client (version `8.0.0`) against kube-apiserver `v1.17.3`. #1003 also looks similar.

As a quick remediation, we are pinned to older (`<= 8u251`) JVMs. I haven't tested if the `HTTP2_DISABLE=true` env var suggested at https://github.com/fabric8io/kubernetes-client/issues/2212#issuecomment-628555229 works with the official client yet, as I haven't had a chance to dig if that is being used by `okhttp3` directly, or if it's something that the `fabric8io` java client does.

**Comment by fabiokung** [comment]
Main symptom are `TCP` connections being `RST` by kube-apiserver right after TLS handshakes.

**Comment by yue9944882** [comment]
thank you @fabiokung for reporting this! the walkaround for this issue on okhttp client will be explicitly excluding HTTP2 from the supported protocols --- the good news is that the okhttp client instance under `ApiClient` is accessible by its getter/setter. additionally the fix https://github.com/kubernetes-client/java/pull/960 is already published in 9.0.0. 

>    client.setHttpClient(
        client.getHttpClient().newBuilder().protocols(Arrays.asList(Protocol.HTTP_1_1)).build());

**Comment by fabiokung** [comment]
Fixed in `9.0.0`
