### ISSUE TITLE
Multiple calls to SharedInformerFactory::sharedIndexInformerFor for the same api type class does not work as documented

### ISSUE THREAD

**Issue by avmohan** [kubernetes-client/java#1154]
See https://github.com/kubernetes-client/java/blob/client-java-parent-9.0.1/util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java#L131

The documentation says:
`And the informer cache will be overwritten on multiple call w/ the the same apiTypeClass.`

But actually it creates a new informer and returns it without replacing the one in the informer cache. As a result, the returned informer is not started when `startAllRegisteredInformers` is invoked later.

**Comment by yue9944882** [comment]
thanks for reporting this. it was an oversight in the document, opened #1165 as the fix
