### ISSUE TITLE
createNamespacedDeployment/createNamespacedDeploymentWithHttpInfo  is not creating deployment

### ISSUE THREAD

**Issue by kondapally1989** [kubernetes-client/java#116]
trying to create a hello world deployment (synonymous with command  (kubectl run kubeexample --image=docker.io/jocatalin/kubernetes-bootcamp:v1 --port=8080) command works)

$kubectl version
`### Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCt:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDat017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/am}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCt:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"dirty", BuildDat017-06-22T04:31:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/am}
`

$minikube version
`minikube version: v0.20.0
`

exposed the kube rest api using following command (No authentication)
` kubectl proxy --address="0.0.0.0" --port=9090  --accept-hosts='^*$'  --v=8`

when hitting the rest end point directly ("apis/extensions/v1beta1/namespaces/"+namespace+"/deployments") using curl or java(using apache http commons) it creates the deployment(response is 201 created).
method: POST
body: `{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"kubeexample","creationTimestamp":null,"labels":{"run":"kubeexample"}},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"kubeexample"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"kubeexample"}},"spec":{"containers":[{"name":"kubeexample","image":"docker.io/jocatalin/kubernetes-bootcamp:v1","ports":[{"containerPort":8086}],"resources":{}}]}},"strategy":{}},"status":{}}`

but when i am using the official client it doesn't create any deployment.(using *-1.0.0-beta2-SNAPSHOT.jars)
following is the piece of code i am using to create deployment

```java
	ApiClient client = Config.fromUrl("http://X.X.X.X:9090/");
        String namespace = "default"; 
        ExtensionsV1beta1Deployment body = new ExtensionsV1beta1Deployment(); 
        V1ObjectMeta metadata = new V1ObjectMeta();
        metadata.setName("kubeexample");
        metadata.setNamespace("default");
        HashMap<String, String> labels = new HashMap<String, String>();
        labels.put("run", "kubeexample");
        metadata.setLabels(labels);
        metadata.setGeneration(1L);
		body.setMetadata(metadata);
		ExtensionsV1beta1DeploymentSpec spec = new ExtensionsV1beta1DeploymentSpec();
		spec.setReplicas(1);
		V1LabelSelector selector = new V1LabelSelector();
		Map<String, String> matchLabels = new HashMap<String, String>();
		matchLabels.put("run", "kubeexample");
		selector.setMatchLabels(matchLabels);
		spec.setSelector(selector);
		V1PodTemplateSpec template = new V1PodTemplateSpec();
		V1ObjectMeta metadata2 = new V1ObjectMeta();
		metadata2.setLabels(matchLabels);
		metadata2.setCreationTimestamp(null);
		template.setMetadata(metadata2);
		V1PodSpec spec2 = new V1PodSpec();
		List<V1Container> containers = new ArrayList<V1Container>();
		V1Container e = new V1Container();
		e.setName("kubeexample");
		e.setImage("docker.io/jocatalin/kubernetes-bootcamp:v1");
		List<V1ContainerPort> ports = new ArrayList<V1ContainerPort>();
		V1ContainerPort e2 = new V1ContainerPort();
		e2.setContainerPort(8080);
		ports.add(e2);
		e.setPorts(ports);
		V1ResourceRequirements resources = new V1ResourceRequirements();
		resources.setRequests(new HashMap<String, String>());
		e.setResources(resources);
		containers.add(e);
		spec2.setContainers(containers);
		V1PodSecurityContext securityContext = new V1PodSecurityContext();
		spec2.setSecurityContext(securityContext);
		template.setSpec(spec2);
		spec.setTemplate(template);
		body.setSpec(spec);
		body.setKind("Deployment");
		body.setApiVersion("extensions/v1beta");
        String pretty = "true"; // String | If 'true', then the output is pretty printed.
        try {
        	ExtensionsV1beta1Api apiInstance = new ExtensionsV1beta1Api(client);
			ApiResponse<ExtensionsV1beta1Deployment> result = apiInstance.createNamespacedDeploymentWithHttpInfo(namespace, body, pretty);
            System.out.println(result.getData());
        } catch (ApiException e3) {
            System.err.println("Exception when calling ExtensionsV1beta1Api#createNamespacedDeployment");
            e3.printStackTrace();
        }
``` 

RESPONSE:  status code 200 and getdata() prints  `class ExtensionsV1beta1Deployment {
    apiVersion: extensions/v1beta1
    kind: DeploymentList
    metadata: class V1ObjectMeta {
        annotations: null
        clusterName: null
        creationTimestamp: null
        deletionGracePeriodSeconds: null
        deletionTimestamp: null
        finalizers: null
        generateName: null
        generation: null
        initializers: null
        labels: null
        name: null
        namespace: null
        ownerReferences: null
        resourceVersion: 1009815
        selfLink: /apis/extensions/v1beta1/namespaces/default/deployments
        uid: null
    }
    spec: null
    status: null
}
`
but never creates the deployment.

when i debugged through code (attaching source jar of okhttpclient  and kube) inside i am able to observe that createNamespacedDeployment/createNamespacedDeploymentWithHttpInfo  first calls **post** method and then calls **get** method to fetch list of deployment and internally(in your client) response of post is as:
 
`Response{protocol=http/1.1, code=301, message=Moved Permanently, url=http://x.x.x.x:9090//apis/extensions/v1beta1/namespaces/default/deployments?pretty=true}`

and for lateral get call it fetches list of deployment for which the response code is 200 .

OUTPUT at kubectly proxy server is as follows(when hit from kube-client)

`$kubectl proxy --address="0.0.0.0" --port=9090  --accept-hosts='^*$'  --v=8 
I1114 10:19:38.800081    8655 loader.go:357] Config loaded from file /root/.kube/config
Starting to serve on [::]:9090
I1114 10:19:45.128870    8655 proxy_server.go:98] /apis/extensions/v1beta1/namespaces/default/deployments matched ^.*
I1114 10:19:45.128922    8655 proxy_server.go:98] x.x.x.x matched ^*$
I1114 10:19:45.128928    8655 proxy_server.go:138] Filter accepting GET /apis/extensions/v1beta1/namespaces/default/deployments x.x.x.x
I1114 10:19:45.128940    8655 upgradeaware.go:237] Request was not an upgrade
I1114 10:19:45.129024    8655 round_trippers.go:414] GET https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments?pretty=true
I1114 10:19:45.129031    8655 round_trippers.go:421] Request Headers:
I1114 10:19:45.129036    8655 round_trippers.go:424]     Authorization: Bearer test1Abc
I1114 10:19:45.129041    8655 round_trippers.go:424]     Accept: application/json
I1114 10:19:45.129045    8655 round_trippers.go:424]     User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
I1114 10:19:45.129050    8655 round_trippers.go:424]     X-Forwarded-For: 10.178.143.194
I1114 10:19:45.129054    8655 round_trippers.go:424]     Accept-Encoding: gzip
I1114 10:19:45.174642    8655 round_trippers.go:439] Response Status: 200 OK in 45 milliseconds
I1114 10:19:45.174666    8655 round_trippers.go:442] Response Headers:
I1114 10:19:45.174671    8655 round_trippers.go:445]     Date: Tue, 14 Nov 2017 10:19:46 GMT
I1114 10:19:45.174675    8655 round_trippers.go:445]     Content-Type: application/json
I1114 10:19:45.174679    8655 round_trippers.go:445]     Content-Length: 2591
`

**Comment by brendandburns** [comment]
The problem is you set 'apiVersion' to `extensions/v1beta` when it should be `extensions/v1beta1`

Although, in reality, you don't even need to set the `apiVersion` the generated code will take care of that for you.

I'm not sure why the proxy silently drops the bad request, that seems like it might be a bug in the `kubectl proxy` may be worth filing a bug on the main `kubernetes/kubernetes` project about that behavior.

But when I run your code against the kubernetes API without the proxy in the middle, I get a BadRequest error with a (semi) decent error message.

**Comment by kondapally1989** [comment]
if kubectl proxy would have been the issue, curl/postman or sample java
program (using apache http commons) should not have also worked. but they
do work with kubectl proxy with in between(they create deployment
successfully over proxy)

**Comment by brendandburns** [comment]
The 'apiVersion' field in your current example contains the correct value 'extensions/v1beta1'

You have code has a typo.

When I fix the typo in your Java code it works correctly.

**Comment by brendandburns** [comment]
'current' should be 'curl' in the previous comment. Silly phone...

**Comment by kondapally1989** [comment]
I corrected the typo to ***body.setApiVersion("extensions/v1beta1");*** and tried again, deployment didn't get created.
 
even after commenting 	***body.setApiVersion("extensions/v1beta1");***. nothing happens  much (deployment doesnt get created)i can still observe 301 status code for post method(within the code) and 200 for get method.

**Comment by brendandburns** [comment]
What version of kubernetes are you running? Deployments are v1beta2 in kubernetes 1.8.x I believe....

--brendan

________________________________

**Comment by kondapally1989** [comment]
$kubectl version
```### Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCt:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDat017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/am} 

Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCt:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"dirty", BuildDat017-06-22T04:31:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/am}
```
$minikube version
minikube version: v0.20.0

**Comment by brendandburns** [comment]
I tried this on minikube 1.7.x on my box and it worked.  Upgrade your minikube version?

--brendan



________________________________

**Comment by kondapally1989** [comment]
I have updated both minikube and kubectl
minikube version : v0.23.0 (Latest)
kubectl server version  1.8.0 (Latest)

I have  captured the post requests from both postman(restful requester) and java(official client) program
 using wireshark.

below post request successfully creates deployments (request from postman)

```
E:@@#<&b?B]
5POST /apis/extensions/v1beta1/namespaces/default/deployments?pretty=true HTTP/1.1
Host: 192.168.0.11:9090
Connection: keep-alive
Content-Length: 467
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.89 Chrome/62.0.3202.89 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: be530a8c-de1d-6603-4cad-85c9acbbff62
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8

{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"generation":1,"labels":{"run":"kubeexample"},"name":"kubeexample","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"kubeexample"}},"template":{"metadata":{"labels":{"run":"kubeexample"}},"spec":{"containers":[{"image":"docker.io/jocatalin/kubernetes-bootcamp:v1","name":"kubeexample","ports":[{"containerPort":8080}],"resources":{"requests":{}}}],"securityContext":{}}}}}

```

below is the post request from java(using official client) pgm (doesnt create any deployments)

```
e5E2)@@L#WvUV
M^MQPOST //apis/extensions/v1beta1/namespaces/default/deployments?pretty=true HTTP/1.1
Accept: application/json
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
Content-Type: application/json; charset=utf-8
Content-Length: 467
Host: 192.168.0.11:9090
Connection: Keep-Alive
Accept-Encoding: gzip

{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"generation":1,"labels":{"run":"kubeexample"},"name":"kubeexample","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"kubeexample"}},"template":{"metadata":{"labels":{"run":"kubeexample"}},"spec":{"containers":[{"image":"docker.io/jocatalin/kubernetes-bootcamp:v1","name":"kubeexample","ports":[{"containerPort":8080}],"resources":{"requests":{}}}],"securityContext":{}}}}}

```

both the data except for headers look same to me and making me quiet confused.

**Comment by kondapally1989** [comment]
It seems i figured out what is the wrong happening.
'/' is the culprit in Config.fromUrl("http://X.X.X.X:9090/");
removing the forward slash creates deployment with breeze. this works (Config.fromUrl("http://X.X.X.X:9090");).
