### ISSUE TITLE
[Umbrella Issue] Testing framework for Java SDK

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#1176]
it's valuable to have a reusable testing framework that mocks out kubernetes apiserver behavior for Java SDK. This will not only improve our code quality but also provide reusable testing utilities for the developers.. i can think of two aspect to get start with:

- __Unit test__: we're really close at mocking out kubernetes apiserver by leveraging wiremock [for example](https://github.com/kubernetes-client/java/blob/f6d2e1d594a0bbe1757f0089eb48b606f6b435bb/util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java#L93-L105). i suppose we can take a further step by providing a wrapper JUnit runner upon wiremock to get rid of those hardcoded kubernetes api url-paths from the tests. developers will also benefit from a cleaner code interfaces..

- __Integration/end-to-end test__: unlike a mocking http server, we can spawn a real kubernetes testing cluster using KinD but this will require a docker daemon deployed on the host. ideally we can expect to simply code something like `Testings.newKindCluster().installCRD(..)` to drive a minimal cluster by code.

**Comment by sarveshkaushal** [comment]
@yue9944882 - Can you please add more details on how to proceed on this?

**Comment by yue9944882** [comment]
> Unit test: we're really close at mocking out kubernetes apiserver by leveraging wiremock for example. i suppose we can take a further step by providing a wrapper JUnit runner upon wiremock to get rid of those hardcoded kubernetes api url-paths from the tests. developers will also benefit from a cleaner code interfaces..



@sagarbhavsar4328 sure, in our test codes, we're mostly using wiremock to setup a local http server to mock out kubernetes endpoints e.g. https://github.com/kubernetes-client/java/blob/6c0e2507fac4f89c9b7578213d979975c46907b2/extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java#L64-L67. 

but i don't think starting a local server is necessary for a unit-test if we can properly mock out the server behaviors at client-side. we can probably start by mocking `ApiClient` by leveraging `Mockito` framework w/ a more user-friendly interface.
