### ISSUE TITLE
Question: Is 6.0.1 the latest release or 9.0.2?

### ISSUE THREAD

**Issue by Capstan** [kubernetes-client/java#1183]
Hey, @brendandburns, long time no see. *waves*

Did something change in the model for releasing this client last year so it reverted from [GitHub releases](https://github.com/kubernetes-client/java/releases) and now just relies on [git tagging](https://github.com/kubernetes-client/java/tags)? Right now, there's conflicting information:

* GitHub persists in showing on the RHS of the UI that [6.0.1](https://github.com/kubernetes-client/java/releases/tag/client-java-parent-6.0.1) is the latest release.
* According to [RELEASES.md](https://github.com/kubernetes-client/java/blob/master/RELEASES.md), there should be also be e-mail at `kubernetes-dev@googlegroups.com` with the release notes, but [a search](https://groups.google.com/g/kubernetes-dev/search?q=kubernetes-java-client) reveals the last time that happened was for 3.0.0-beta1.
* According to [README.md](https://github.com/kubernetes-client/java/blob/master/README.md), the [Maven and Gradle installation instructions](https://github.com/kubernetes-client/java/blob/master/README.md#installation) reference 9.0.0, and the [compatibility diagram](https://github.com/kubernetes-client/java/blob/master/README.md#compatibility) also lists it.

If they _are_ the later versions, then is there something categorizing the release notes for them? Is it reasonable to promote them to GitHub releases, or is there some way to make it not be pointing people at stale releases?

**Comment by brendandburns** [comment]
`9.0.2` is the latest version. Personally, I figure that everyone is going to be looking at the maven central page:

**Comment by brendandburns** [comment]
Ahh, I saw the Github "latest release" UX. That didn't use to exist. I've added an official GitHub "release" so that things look right.

**Comment by rjeberhard** [comment]
Similarly, I now see something that looks like a 10.0 release on the same releases page. Is 10.0 out or coming out soon? Thanks for all of the hard work. I really appreciate it.

**Comment by brendandburns** [comment]
Just updated the release page, and an updated `CHANGELOG.md` file has been merged.

`10.0.0` was pushed out to Sonatype yesterday, should be visible in maven central soon (I hope)

Closing this issue, since I believe it has been resolved. (we do need better automation to ensure that this keeps happening going forward)
