### ISSUE TITLE
DefaultControllerBuilder does not allow configuration of the ready timeout

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [kubernetes-client/java#1195]
I have noticed that my controller fails to start because the ready function can take longer than 30 seconds to run. But the controller builder does have a way to express the ready timeout. Can we add a method on the build to support this?

**Comment by Bhashitha123** [comment]
goog

**Comment by tony-clarke-amdocs** [comment]
Forgive me, what does "goog" mean :) ?

**Comment by brendandburns** [comment]
A current work-around is to cast the `Controller` that you get to a `DefaultController` and then you can set the ready timeout.

But I think that a PR to add support for setting this timeout in the builder makes sense. @tony-clarke-amdocs can you send a PR?

If not we'll get to it eventually.

**Comment by tony-clarke-amdocs** [comment]
That's exactly what I am doing now. But prefer it was in the builder. I am working on my employer to work on signing the CNA...will submit PR then. Thanks.
