### ISSUE TITLE
Lower logger levels

### ISSUE THREAD

**Issue by edrevo** [kubernetes-client/java#1200]
Would this project be open to a PR that lowers the log level of several messages? In general, I find that this library logs a lot of messages in the error level for transient issues that are retryable. For example, https://github.com/kubernetes-client/java/blob/31fbb3a52c6ca7a6ad6d71cd154b387191705adc/extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java#L117 could be a warn, since the fact that it failed is already encoded in the return type (so the caller can decide whether that is an error or it is going to be retried down the line).

These error logs make my Ops team's life harder, since they end up as issues in [Sentry](https://sentry.io/), so that's my primary motivator to change the log level for some of the messages.

**Comment by brendandburns** [comment]
We should definitely do a more fine-grained logging.

Some fixes I would suggest for the PR:

1) Don't catch `Throwable` catch specific exceptions.

2) If the exception is `ApiException` with an error code of `409` then this exception is expected. log to debug or info

3) If it's another type of ApiException or IOException then it's unexpected, log to error

We'd gladly take a PR with those fixes (as well as anywhere similar in the code)

Thanks!
