### ISSUE TITLE
IOException when Watching a Resource

### ISSUE THREAD

**Issue by lgnashold** [kubernetes-client/java#1213]
**This is not because I have misconfigured the timeout for the OkHTTP3 client**

I am setting up a Kubernetes watch (on an ingress resource specifically). 
I initialize my OkHTTP3 client as follows: 
```
 OkHttpClient httpClient = client.getHttpClient().newBuilder()
                .readTimeout(0, TimeUnit.SECONDS)
                .build();
```
I run the watch like this: 
```
   try (Watch<NetworkingV1beta1Ingress> watch = Watch.createWatch(
                client,
                apiInstance.listNamespacedIngressCall(my-namespace, "true", false, null, null, null, null, null, null, true, null),
                new TypeToken<Watch.Response<NetworkingV1beta1Ingress>>() {
                }.getType()
        )) {
            watch.forEach(x -> {
               // application specific code
                }
            });
        }
```
After a relatively small amount of time (~5 minutes), I get the following IOException inside Watch.java:184, which eventually is thrown as a RuntimeException. 
```
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
    okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:420
    okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
    okio.RealBufferedSource.exhausted(RealBufferedSource.java:57
    io.kubernetes.client.util.Watch.hasNext(Watch.java:182)
    java.lang.Iterable.forEach(Iterable.java:74) 
```
Upon googling this error, I found a similar issue in OkHTTP (https://github.com/square/okhttp/issues/2204) which recommended disabling HTTP2. 

I tried re-configuring the OkHttpClient to only use HTTP 1.1: 
```
 OkHttpClient httpClient = client.getHttpClient().newBuilder()
                .readTimeout(0, TimeUnit.SECONDS)
                .protocols(Collections.singletonList(Protocol.HTTP_1_1))
                .build();
```
However, this caused a new error. After exactly 5 minutes, the watch would fail with the following exception:
```
java.io.EOFException 
   okio.RealBufferedSource.require(RealBufferedSource.java:61)
   ....
   okio.RealBufferedSource.exhausted(RealBufferedSource.java:57)
   io.kubernetes.client.util.Watch.hasNext(Watch.java:182)
```
Is there any way to have a watch that lasts longer than 5 minutes?

**Comment by lgnashold** [comment]
Actually, if the server does have a maximum timeout after five minutes like implied here (https://github.com/kubernetes/kubernetes/issues/6513), then how do I distinguish between a server timeout, a client timeout, and an actual client error (since they're all surfaced as a RuntimeException)? If I want to have a watch that runs for lets say an hour, how do I take into account this timeout with the Java API?

**Comment by brendandburns** [comment]
@lgnashold you should always assume that watches can break for arbitrary reasons.

For this reason, you are probably better off using the higher level Informer class (https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java) rather than watching directly.

The Informer will handle all of the watch + list re-initiating for you.

Hope that helps!

**Comment by lgnashold** [comment]
Thank you for your help!
