### ISSUE TITLE
Maven artifacts for client-java-contrib submodules.

### ISSUE THREAD

**Issue by hodur** [kubernetes-client/java#1236]
I do realize this is work in progress according to this issue https://github.com/kubernetes-client/java/issues/1132, but I'm hoping to use this library to create ServiceMonitors for Prometheus operator. It seems that both
```
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java-prometheus-operator-models</artifactId>
    <version>0.38.1-SNAPSHOT</version>
</dependency>
``` 
and 
```
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java-cert-manager-models</artifactId>
    <version>0.16.1-SNAPSHOT</version>
</dependency>
```
are not available from a public maven repository yet. Is that intentional while they are still in development? Should I figure out how to deploy ServiceMonitor in a different way?

Pinging @simingweng and @yue9944882 instead of commenting on the other issue.

**Comment by brendandburns** [comment]
We haven't (yet) figured out how we're going to release these packages. For now you will need to build them yourself.

**Comment by hodur** [comment]
Roger, I'll go ahead and do that.
