### ISSUE TITLE
ProtoClient does not process updates (PUT) correctly

### ISSUE THREAD

**Issue by cliveseldon** [kubernetes-client/java#124]
There seem to be various bugs in the ProtoClient

1. A POST request is always created when a body is provided (create, update). It should be put for update.

https://github.com/kubernetes-client/java/blob/57eb4e0fe514a55c3196316c221223e85ced3f4c/util/src/main/java/io/kubernetes/client/ProtoClient.java#L166

2. There is a typo in "Content-type" - the apiClient expects "Content-Type"

https://github.com/kubernetes-client/java/blob/57eb4e0fe514a55c3196316c221223e85ced3f4c/util/src/main/java/io/kubernetes/client/ProtoClient.java#L160

3. PATCH is not catered for

**Comment by cliveseldon** [comment]
Also a delete with DeleteOptions is not available.

**Comment by brendandburns** [comment]
Closing as I believe this was fixed by the merge of commits from #125
