### ISSUE TITLE
We would like to have the doc about the configuration of server, insecure access and specific username accessing

### ISSUE THREAD

**Issue by bugzyz** [kubernetes-client/java#1260]
Hi! Great project!

We are trying to use this java client to read, exec outside of our k8s cluster, from a totally separated VM. 
To avoid those troublesome TLS connection, username authorization, we already grant the role we need in our k8s cluster and test the connection from our separated VM to the k8s cluster by the below curl command. 

```
curl -X GET $APISERVER/api --insecure
```

And already got some response like

```
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "xxxxxxxx",
      "serverAddress": "xxxxxxxx"
    }
  ]
}
```

So now, to simply integrate this java client into our java code, how to do this with the java client. Any recommended doc?

**Comment by brendandburns** [comment]
This client knows how to read configuration data from a standard kubeconfig file:

https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

You can either place that in `$HOME/.config/kubeconfig` for the user that runs the Java program, or you can set the file path in the `$KUBECONFIG` environment variable.

if the `kubectl` command line tool works on the machine, this client library will too.

There are lots of code examples here:
https://github.com/kubernetes-client/java/tree/master/examples/src/main/java/io/kubernetes/client/examples

Hope that helps.

**Comment by bugzyz** [comment]
Great! That's very helpful! Thanks for your suggestion!

**Comment by brendandburns** [comment]
Closing the issue as I believe the question is answered.

**Comment by brendandburns** [comment]
Oops, I realized I said `$HOME/.config/kubeconfig` when I should have said `$HOME/.kube/config` apologies for any confusion. I've corrected the earlier comment.
