### ISSUE TITLE
sdk depends too many jars,  it looks like not good^_^

### ISSUE THREAD

**Issue by johnyannj** [kubernetes-client/java#1261]
Maven: com.google.code.findbugs:jsr305:3.0.2
Maven: com.google.code.gson:gson:2.8.6
Maven: com.google.errorprone:error_prone_annotations:2.3.4
Maven: com.google.guava:failureaccess:1.0.1
Maven: com.google.guava:guava:29.0-jre
Maven: com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
Maven: com.google.j2objc:j2objc-annotations:1.3
Maven: com.google.protobuf:protobuf-java:3.12.2
Maven: com.squareup.okhttp3:logging-interceptor:3.14.3
Maven: com.squareup.okhttp3:okhttp:3.14.3
Maven: com.squareup.okio:okio:1.17.2
Maven: commons-codec:commons-codec:1.14
Maven: io.gsonfire:gson-fire:1.8.4
Maven: io.kubernetes:client-java:9.0.2
Maven: io.kubernetes:client-java-api:9.0.2
Maven: io.kubernetes:client-java-proto:9.0.2
Maven: io.sundr:builder-annotations:0.21.0
Maven: io.sundr:resourcecify-annotations:0.21.0
Maven: io.sundr:sundr-codegen:0.21.0
Maven: io.sundr:sundr-core:0.21.0
Maven: io.swagger:swagger-annotations:1.6.2
Maven: javax.annotation:javax.annotation-api:1.3.2
Maven: joda-time:joda-time:2.10.6
Maven: junit:junit:4.11
Maven: org.apache.commons:commons-collections4:4.4
Maven: org.apache.commons:commons-compress:1.20
Maven: org.apache.commons:commons-lang3:3.11
Maven: org.bitbucket.b_c:jose4j:0.7.2
Maven: org.bouncycastle:bcpkix-jdk15on:1.66
Maven: org.bouncycastle:bcprov-ext-jdk15on:1.66
Maven: org.bouncycastle:bcprov-jdk15on:1.66
Maven: org.checkerframework:checker-qual:2.11.1
Maven: org.hamcrest:hamcrest-core:1.3
Maven: org.joda:joda-convert:2.2.1
Maven: org.slf4j:slf4j-api:1.7.30
Maven: org.yaml:snakeyaml:1.26

**Comment by brendandburns** [comment]
All of the dependencies are necessary for various pieces of the client library. The client itself is a fairly complicated piece of code covering a number of different ways to interact with Kubernetes.

I'm going to close this issue because I don't think we plan on reducing any of these dependencies. Please re-open if there are specific dependencies that you'd like to discuss or you think we can mark as optional.

**Comment by spencergibb** [comment]
@brendanburns the one that has caused problems before is `com.google.guava:guava`. Could that one be re-evaluated?

**Comment by brendandburns** [comment]
what specific issues are you seeing?

**Comment by brendandburns** [comment]
Closing again due to no response, please create a new issue if there are specific issues with `guava`

**Comment by spencergibb** [comment]
Sorry for the delay. Nothing specific, just typical conflict with guava in a user project and there being incompatibility between the versions
