### ISSUE TITLE
How to create dynamic informers

### ISSUE THREAD

**Issue by avmohan** [kubernetes-client/java#1268]
Do we have support for something like this in the java client?
https://firehydrant.io/blog/dynamic-kubernetes-informers/

Instead of explicitly watching for specific resources, need to watch on arbitrary runtime type.

**Comment by brendandburns** [comment]
The existing Informer in the client should work for this. You pass the type in as a generic parameter to the Informer as well as using the GenericAPI to create a `Call`

There's an example here:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java

It uses a built-in type, but there's no reason that you have to do that. Let us know if you run into problems.

**Comment by yue9944882** [comment]
@avmohan recently we extracted a new abstraction [ModelMapper](https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ModelMapper.java) to deal w/ API discovery and the dynamic informer should be working based on that. i can imagine a daemon thread reloading API discovery periodically and add/remove informers from the factory dynamically. 


> The existing Informer in the client should work for this. You pass the type in as a generic parameter to the Informer as well as using the GenericAPI to create a Call

yes i think that will also be working. but given the fact that those arbitrary resources don't have a certain java model class connected, i guess they will be deserialized into free gson object (which will be hard to manipulate?). usually the use-case of dynamic informers only need to access the metadata fields from the object i.e. drop the spec/status, so it's probably valuable to use an equivalence of [PartialObjectMetadata](https://github.com/kubernetes/kubernetes/blob/a9f0db16614ae62563ead2018f1692407bd93d8f/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L1277-L1283) along with the dynamic informers..

**Comment by avmohan** [comment]
Thanks guys.
