### ISSUE TITLE
Is there a possibilty to lock the Config Map before updating it to avoid race conditions

### ISSUE THREAD

**Issue by srinivasev** [kubernetes-client/java#1269]
I have a scenario where multiple threads try to read and update the file contents exist as an entry for one of the key as mentioned below.

apiVersion: v1
kind: ConfigMap
data:
    configFile : yaml file

The YAML file content in this configFile key can be read by any thread and do necessary modifications and patch it back based on requirment. How to avoid the race conditions when multiple parallel threads read the file and append its own content and end up in data loss which is modified by either of the thread.

Is there any way to obtain the locking mechanism on the ConfigMap and can perform read, parse, patch it back and then release the lock for other threads.

**Comment by brendandburns** [comment]
You need to use the 'resourceVersion' field to do this, see the discussion here:

https://github.com/kubernetes/kubernetes/issues/2115#issuecomment-61498890

It's not a traditional Java lock, it's optimistic concurrency on the server.

**Comment by srinivasev** [comment]
Hi @brendanburns  ,
Does it hold good for patching configmap using below API's. Because I can see the patch invocation is working fine when multiple threads try to patch the same configmap key with different values.

How I Tested ?
I created main classes, T1 and T2.
T1 reads the configmap and sleeps for 60s before updating.
T2 reads the configmap same as T1 resourceVersion field and sleeps for 120s before updating.

I am not seeing any 409 Conflict error, the patch is working fine by overriding the T1 updated value during T2 patch.

Client creation : 
V1ConfigMapList configMaps = coreV1ApiClient.listNamespacedConfigMap("srini", null, false, null, null,
                    "app=cpro, component=server", null, null, null, true);

Patching the ConfigMap :
coreV1ApiClient.patchNamespacedConfigMap(configMap.getMetadata().getName(), "srini",
                    new V1Patch(finalContentForPatchWithMap.toString()), null, null, "admin", false);

**Comment by yue9944882** [comment]
@srinivasev 

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency 

IIUC update will be safer than patch if you're looking for literally locking the configmap. the patch is actually doing a "get->apply->update" at the server-side and only conflicts when the patch content cannot be applied to the latest state of the target object.

**Comment by srinivasev** [comment]
Hi @yue9944882 ,

If I see the link shared by you, it clearly states as below - 

When a record is about to be updated, it's version is checked against a pre-saved value, and if it doesn't match, the update fails with a StatusConflict (HTTP status code 409).

So, In my scenario too, this should hold good right? Every PATCH call `(patchNamespacedConfigMap)` should be cross-checking the 'resourceVersion' field before performing the patch/merge over the data. If there is a mismatch, the client should be thrown with 409 error.

**Comment by srinivasev** [comment]
Hi @brendandburns ,

If I need to make use of resourceVersion for conflict control, the only option is to use the `replaceNamespacedConfigMap(...)`.  I think this method needs the complete content of Configmap data to be read (all the key:value pairs) by the client and manipulate whatever required for a particular key and replace the configmap with the latest data.

So, 
Client A reads the ConfigMap
Client B reads the ConfigMap
Client A modifies the content of `keyA` locally
Client B modifies the content of `keyA` locally
Client A invokes the `replaceNamespacedConfigMap(...)` by sending complete ConfigMap data and operation will be success.
Client B invokes the `replaceNamespacedConfigMap(...)` by sending complete ConfigMap data and operation will be a failure with 409.

hope this understanding is correct.

One more question, the content of values in configmap are yaml files. Currently V1Patch supports the format like PATCH_FORMAT_APPLY_YAML. Can we achieve similar mechanism while invoking the `replaceNamespacedConfigMap(...)`

**Comment by brendandburns** [comment]
Your understanding is correct.

You should be able to just replace the `byte[]` in the String -> byte[] map:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1ConfigMap.java#L41

So get a `V1ConfigMap` then update via `V1ConfigMap.putDataItem(key, newByteData)`

Then use `replaceNamespacedConfigMap(...)` to replace the value on the server.

Hope that helps!

**Comment by srinivasev** [comment]
Hi @brendandburns ,

Is the same support of conflict error 409 available at python client? In the case of python, I am modifying binary_data of the ConfigMap for a business use case whenever a request is received. Hope the `replace_namespaced_config_map ` method in the python client serves the same functionality of optimistic concurrency control.

**Comment by brendandburns** [comment]
Yes, the `409` comes from the server, so any client library should work if you use the `replace*` methods.

Just make sure you set the `resourceVersion` in the object that you are sending to `replace*`

**Comment by monoj** [comment]
@brendandburns 

I think i am missing something, but i am unable to get the current `resourceVersion` when i make a below call. The `resourceVersion` is null. What is the correct way to read a secret that also gives me `resourceVersion`, so that i can use it for optimistic concurrency writes ?

`new CoreV1Api().readNamespacedSecret(secretName, namespace, DEFAULT_PRETTY, true,
          true)`

**Comment by brendandburns** [comment]
@monoj the resource version should be in `V1Secret.getMetadata().getResourceVersion()` or similarly for ConfigMaps.

**Comment by monoj** [comment]
@brendandburns thank you. 

I am doing that `V1Secret.getMetadata().getResourceVersion()`. But the `resourceVersion` value is `null` if i get the `V1Secret` object via `CoreV1Api().readNamespacedSecret()` method. Interestingly, when i get the `V1Secret` object via the `CoreV1Api().listNamespacedSecret()` method, i am getting back the correct `resourceVersion`.

**Comment by srinivasev** [comment]
Hi @brendandburns ,
Is there any Kubernetes resource that can be used only for achieving the locking mechanism / Kubernetes provides the locking mechanism similar to DB locking where the user is not required to handle it explicitly?

We have a scenario where multiple threads try to update the same resource/ConfigMap. This is increasing our retries logic.

Scenario : 

- I have 1000 names to be updated into the single config map. 
- This update logic is parallelly taken care of by 8 individual threads.
- As we are relying on the resourceVersion of Configmap for the retries, we are expecting to set higher number for the retry count.
- Because on or the other parallel thread will be holding the lock and leading to conflict errors.(where we are supposed to use the above-discussed locking mechanism).
