### ISSUE TITLE
ExtensionsV1beta1Api.patchNamespacedDeployment throws 500 Internal server error because of wrong content type in header

### ISSUE THREAD

**Issue by kondapally1989** [kubernetes-client/java#127]
reason: content-type in header is being set to **application/json-patch+json** instead of **application/strategic-merge-patch+json**
 this is causing 500 internal server error

 when i test the patch call to  **/apis/extensions/v1beta1/namespaces/default/deployments/kubeexample?pretty=false**  with content type as    **application/json-patch+json** (in postman rest client) , getting following error 

```
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "json: cannot unmarshal object into Go value of type jsonpatch.Patch",
    "code": 500
}
```

I believe content type should be **application/strategic-merge-patch+json** (with it as content type deployment gets updated)

in ExtensionsV1beta1Api.patchNamespacedDeploymentCall

localVarContentTypes is being set to **application/json-patch+json** instead of **application/strategic-merge-patch+json** because of ApiClient.selectHeaderContentType(String [] arr)  always select first element of array({"application/json-patch+json", "application/merge-patch+json", "application/strategic-merge-patch+json"}) as it matches with regex.

**Comment by Rafaesp** [comment]
Same error when calling `new NetworkingV1Api().patchNamespacedNetworkPolicy()`

**Comment by mjschmidt** [comment]
Any word on this issue?

**Comment by kondapally1989** [comment]
@mjschmidt 
with strategic merge patches, it throws internal server error(because of SWAGGER/OPENAPI/codegen related issues). but with Json Patches it will work.
working example  of JsonPatch is here  https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java

**Comment by costimuraru** [comment]
How can we use a JsonPatch to patch a Node?
