### ISSUE TITLE
NullPointerException when getting Hostname from ingress

### ISSUE THREAD

**Issue by habibali95** [kubernetes-client/java#1274]
I'm trying to get the hostname from a newly created ingress, it seems like we have to wait until ingress is ready to be used (until the address from load balancer is affected) but using the java client I didn't a way to check if ingress is ready. this is how we get the hostname : ingress.get().getStatus().getLoadBalancer().getIngress().get(0).getHostname()
the first attempts throw NPE, after waiting more than 30 sec, it works, is there any way to check that all these getters are safe to use? 
This is the created ingress : 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "username-ingress"
  namespace: "org"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: username-ingress
spec:
  rules:
    - http:
        paths: 
          - path: /fake-1-fake(/|$)(.*)
            backend:
              serviceName: "fake-1-fake"
              servicePort: 80
 Cluser version is 1.16, java client version is 8.0.2

**Comment by brendandburns** [comment]
Any of the get methods can return null, so you need to check null for all of the gets (e.g. `getStatus() != null && .getStatus().getLoadBalancer() != null && ...`)
