### ISSUE TITLE
service

### ISSUE THREAD

**Issue by cxz0804** [kubernetes-client/java#1281]
The version I used was 8.0.2, so I need to write a method to change the service and I called the method "replaceNamespacedService",

code:

 public void createServicea() throws ApiException {
        Map<String, String> message = new HashMap<>();
//        String nameStr = ;
        ApiClient client = k8sInit.getConnection();
        CoreV1Api apiInstance = new CoreV1Api(client);

        V1Service body = new V1Service();
        body.setApiVersion("v1");
        body.setKind("Service");

        V1ObjectMeta objectMeta = new V1ObjectMeta();
        objectMeta.setName("test-test");
        objectMeta.setNamespace("test");
        Map<String, String> annotation = new HashMap<>();
        annotation.put("k8s.eip.work/displayName", "test01");
        annotation.put("k8s.eip.work/workload", "test02");
        objectMeta.setAnnotations(annotation);

        Map<String, String> Labels = new HashMap();
        Labels.put("k8s.eip.work/layer", "test03");
        Labels.put("k8s.eip.work/name", "test04");
        objectMeta.setLabels(Labels);

        V1ServiceSpec serviceSpec = new V1ServiceSpec();
        List<V1ServicePort> servicePorts = new ArrayList<>();
        serviceSpec.setType("ClusterIP");
        V1ServicePort servicePort = new V1ServicePort();
        //servicePort.setName(serviceDTO.getSpec_ports_name());
        servicePort.setPort(8082);
//        servicePort.setNodePort(8080);
        servicePort.setProtocol("TCP");
        IntOrString q = new IntOrString(8082);
        servicePort.setTargetPort(q);
        servicePorts.add(servicePort);
        // selector
        Map<String, String> selector = new HashMap<>();
        selector.put("k8s.eip.work/layer", "test03");
        selector.put("k8s.eip.work/name", "test-test");

        serviceSpec.setPorts(servicePorts);
        serviceSpec.setSelector(selector);
        body.setMetadata(objectMeta);
        body.setSpec(serviceSpec);
        V1Service result = apiInstance.replaceNamespacedService("test-test", "test", body, null, null,null);
        System.out.println(result);
    }

**Comment by brendandburns** [comment]
I'm not certain of your question. What do you need help with?

Thanks!

**Comment by cxz0804** [comment]
Now I do not know where my code is wrong, how to debug can not debug

**Comment by cxz0804** [comment]
"replaceNamespacedService"This method call what to pay attention to you, I now how to call it, is not very clear, the way I call the method call "replaceNamespacedDeployment" and "replaceNamespacedService", however, calls the different

**Comment by brendandburns** [comment]
I'm sorry, I still don't fully understand your question, but it seems like you are wondering how to use the library.

There are a number of examples here:
https://github.com/kubernetes-client/java/tree/master/examples/src/main/java/io/kubernetes/client/examples

And there is documentation about the semantics of `replace` here:
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#updating-resources

I hope that helps.

If you can add details about the specific problem you are facing we can help further.

**Comment by brendandburns** [comment]
Closing this issue due to lack of response. Please use `/reopen` if you need to reopen.
