### ISSUE TITLE
Yaml.dump could not recognize hostNetWork fiels

### ISSUE THREAD

**Issue by Rui-Tang** [kubernetes-client/java#1294]
This is my pod with HostNetWork set to true

![image](https://user-images.githubusercontent.com/14860802/94358800-f007a900-00d5-11eb-89e1-be3741cb8720.png)

Yaml.dump() could not recognize hostNetWork field

![image](https://user-images.githubusercontent.com/14860802/94358822-3a892580-00d6-11eb-84e3-737e5bd6379b.png)

**Comment by brendandburns** [comment]
This looks like the same issue as #592
