### ISSUE TITLE
Why the published images are noted as deprecated?

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#1296]
<img width="1065" alt="Screen Shot 2020-09-29 at 8 04 29 PM" src="https://user-images.githubusercontent.com/12049380/94556162-3a805580-028f-11eb-8922-c5481f7be926.png">

@brendandburns it's the images we published to do the CRD model generation. but what does the deprecation mean, or is the github registry shutting downing in the future?

**Comment by brendandburns** [comment]
I think we need to migrate to `ghcr.io`

https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry
