### ISSUE TITLE
What is the error thrown from the java api when the size of ConfigMap crossed its limit

### ISSUE THREAD

**Issue by srinivasev** [kubernetes-client/java#1301]
Hi Team,
I am storing certificate's/.pem files of an end-point in the config map. The contents will be as below in the form of key:value pairs.

Certificate1 of end-point 1 : .pem content as the value
Certificate2 of end-point 2 : .pem content as the value

This list grows as and when there is a new end-point added for our system and surely we reach the 1MB limit as each certificate size(.pem file size) is approximately 10 to 15kb. In this case, what is the error thrown from the API? Currently using java replaceNamespacedConfigMap method of java k8 client for making an entry in the config map.

**Comment by brendandburns** [comment]
The client doesn't enforce any limits, the error would come from the server. I would assume that it is HTTP 400 Bad Request. But it might be HTTP 429.  Either way it will cause the client to throw `ApiException`

**Comment by srinivasev** [comment]
Thanks, Hope this error is thrown during the invocation of patch_namespaced_config_map call too.

**Comment by srinivasev** [comment]
Hi @brendandburns 

I can see below exception when I tried to insert more than allowed limit - 

kubernetes.client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '25d2990b-2f3e-4c03-b966-66d61c8eccea', 'Content-Type': 'application/json', 'Date': 'Tue, 06 Oct 2020 05:11:26 GMT', 'Content-Length': '422'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ConfigMap \"srini-nc0180-cbnd-mistral-certificates-store\" is invalid: []: Too long: must have at most 1048576 bytes","reason":"Invalid","details":{"name":"srini-nc0180-cbnd-mistral-certificates-store","kind":"ConfigMap","causes":[{"reason":"FieldValueTooLong","message":"Too long: must have at most 1048576 bytes","field":"[]"}]},"code":422}
