### ISSUE TITLE
Is there a java/python api client api for knowing the size of configmap data

### ISSUE THREAD

**Issue by srinivasev** [kubernetes-client/java#1306]
Hi Team,

Is there any API which returns the data size in ConfigMap under kubernetes-client/java. I referred the CoreV1Api class, didn't find anything similar.

**Comment by brendandburns** [comment]
There's no specific API to do this. As far as I know, the only way to do this would be to load the ConfigMap object (`V1ConfigMap`) and then compute the size from the Byte arrays that are in that object. (and then pad it a little bit to include the `apiVersion` etc.)

**Comment by brendandburns** [comment]
Closing this since I believe the question is answered. Please use `/reopen` or open a new issue if you need further assistance.
