### ISSUE TITLE
Wrong Iterator interface implementation

### ISSUE THREAD

**Issue by vtaranenko** [kubernetes-client/java#1309]
https://github.com/kubernetes-client/java/blob/31fbb3a52c6ca7a6ad6d71cd154b387191705adc/extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java#L119

Two subsequent calls of `hasNext()`return two different values when no items were found.

First call always returns `true` so foreach loop fails with:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at io.kubernetes.client.extended.pager.Pager$PagerIterator.next(Pager.java:144)
```
Which goes against Iterator's contract:
https://docs.oracle.com/javase/7/docs/api/java/util/Iterator.html#hasNext()

**Comment by brendandburns** [comment]
Yep, we should check to make sure that items is non-empty.

Thanks for reporting, we will fix.
