### ISSUE TITLE
Get Namespace When Running In Pod

### ISSUE THREAD

**Issue by ryanjbaxter** [kubernetes-client/java#1313]
By default there is a file called `namespace` located at `/var/run/secrets/kubernetes.io/serviceaccount` when running in a pod.  Is there a way of reading that files value in the client library?  I poked around but couldnt find anything.

**Comment by brendandburns** [comment]
We have no method, but you can just read the file yourself right?

Can you describe your use-case? Unlike `kubectl` this client doesn't have a notion of a "current" or "default" namespace, so I'm not sure what client experience you're looking for.

**Comment by rohanKanojia** [comment]
@ryanjbaxter: If you use [Fabric8 Kubernetes Client](https://github.com/fabric8io/kubernetes-client), namespace specified should be available in `KubernetesClient`'s configuration:
```java
try (KubernetesClient k8s = new DefaultKubernetesClient()) {
    // This should print namespace loaded in /var/run/secrets/kubernetes.io/serviceaccount/namespace
    k8s.getConfiguration().getNamespace();
}
```

**Comment by ryanjbaxter** [comment]
@brendanburns yes I can read it myself, I was just hoping the library could do it for me ;)

When using the k8s client from within an application running on k8s it would be nice to get the namespace in which the application is running.  Many of the APIs require the namespace name, and since the namespace will be dynamic depending on where the application is deployed, I want to get it from the file.

@rohanKanojia I dont want to use fabric8

**Comment by rohanKanojia** [comment]
@ryanjbaxter :  I replied because I noticed earlier you're already using Fabric8 in [Spring Cloud Kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes). It's the same client which is used by projects like [Apache Spark](https://spark.apache.org/), [Strimzi](https://strimzi.io/), [Dekorate](https://github.com/dekorateio/dekorate) and [Eclipse JKube](https://github.com/eclipse/jkube)

**Comment by ryanjbaxter** [comment]
@rohanKanojia understood but in this case I don't want to use fabric8 😀

**Comment by rohanKanojia** [comment]
ohk, :broken_heart: . Sorry for the noise.

**Comment by brendandburns** [comment]
@ryanjbaxter makes sense, I'll see where it makes sense to add this. It's not a hard thing to add.

Thanks!
