### ISSUE TITLE
deserialize configmap failed when binaryData field is set

### ISSUE THREAD

**Issue by liuming-dev** [kubernetes-client/java#1318]
I got this deserialization exception as the following, and this exception will happen if `binaryData` is set.

![image](https://user-images.githubusercontent.com/11614773/95645091-71a40180-0aee-11eb-9d18-25a83df35fe0.png)
![image](https://user-images.githubusercontent.com/11614773/95645099-7c5e9680-0aee-11eb-9790-7cfe7a6fbdde.png)

https://github.com/kubernetes-client/java/blob/fbf46529894c7f189cc5a604716aae50769d2caf/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1ConfigMap.java#L36

**Comment by brendandburns** [comment]
Are you trying to deserialize your own JSON file? Or is it coming from the Kubernetes API server.

I think your JSON is malformed.

**Comment by yue9944882** [comment]
@liuming-dev i cant reproduce it in the test https://github.com/kubernetes-client/java/pull/1325. the `binaryData` is a string-byte[] map and all the byte[] are required to be base64 encoded to be properly shown in json format. can you send us a sample for reproducing the error?

**Comment by brendandburns** [comment]
Closing this since we can't repro and there was no response from the reporter.

Please use `/reopen` or open a new issue if you need further assistance.
