### ISSUE TITLE
Looking for swagger codegen for use with CR schema

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#132]
We were previously using our own Java client created with swagger codegen, which it looks like you are too.  Now that there is an official Java client we'd like to use this one.  However, we have a custom resource and we generate api and model classes for our swagger json file.  To use this client, we would need to do a similar integration.  I don't see generation of the files in the pom for this project.

Thanks!

**Comment by brendandburns** [comment]
@rjeberhard generation is handled centrally in https://github.com/kubernetes-client/gen
