### ISSUE TITLE
How to execute a script(not a single command) inside pod?

### ISSUE THREAD

**Issue by kumars17** [kubernetes-client/java#1334]
I am trying to execute a script inside the pod from my client. Please note, script exist on my client machine and not inside pod. So I am reading the script content and copying it to the output stream of exec process and then reading the output of the exec process by reading the input stream. Observing hang issue both while reading the output as well as .waitFor() method(if I don't read the output and directly waitFor process to terminate). Below is sample code.. any help appreciated.

 Process pr =
		        exec.exec("testns", "mypod-deployment-768c8b8957-4l5p2", new String[] {"/bin/sh"} , true, false);

File inputScript= new File("c:\\scriptdir\\a.sh");
FileInputStream inpStream = new FileInputStream(inputScript);
  ByteStreams.copy(inpStream,pr.getOutputStream());
 pr.getOutputStream().flush();
inpStream.close();
pr.getOutputStream().close();

 File fout = new File("c:\\scriptdir\\out.sh");
 OutputStream os=new FileOutputStream(fout);

if ( pr.getInputStream()!=null) {
				 ByteStreams.copy(pr.getInputStream(), os);  // It hangs here.
				 os.flush();

 }
		 
			 pr.waitFor();  //If I comment Bytestream.copy.It hangs here.
			 int extValue=pr.exitValue();

**Comment by kumars17** [comment]
Here si the sample script file

a.sh
------------
#!/bin/sh
echo "Script starts"
ls -al /
hostname

**Comment by brendandburns** [comment]
You probably need to send `ctrl-d` after you send the script, because otherwise the remote shell process doesn't know to stop reading from the input stream.

If your script is small it might be easier to use:

`[ "sh", "-c", "echo \"Script Starts\"; ls -al /; hostname"]`

as the command that you are executing, rather than trying to pass it through `stdin`

**Comment by kumars17** [comment]
I was looking for more like ..  
>  cat a.sh | /bin/sh
  where my input script server as input for the /bin/sh via pipe and as input stream is finished shell should treat it as input completed.

**Comment by brendandburns** [comment]
In that case, you need to explicitly send the `ctrl-d` character to indicate to the shell that the stdin has terminated, otherwise the remote process won't terminate.

**Comment by brendandburns** [comment]
Closing this issue because I believe it is answered. Please use `/reopen` if further assistance is required.
