### ISSUE TITLE
Support for app.k8s.io/v1beta1 application

### ISSUE THREAD

**Issue by jerryhu1234** [kubernetes-client/java#1336]
ERROR: ERROR: java.io.IOException: ERROR: YAML file deployment-dev.yaml is invalid, please check it. Details: java.io.IOException: Unknown apiVersionKind: app.k8s.io/v1beta1/Application known kinds are: {v1/ServerAddressByClientCIDRBuilder=class io.kubernetes.client.openapi.models.V1ServerAddressByClientCIDRBuilder, v1/ReplicaSetConditionFluentImpl=class io.kubernetes.client.openapi.models.V1ReplicaSetConditionFluentImpl, v2beta2/ResourceMetricStatus=class io.kubernetes.client.openapi.models.V2beta2ResourceMetricStatus, v1beta1/PodDisruptionBudgetSpec=class io.kubernetes.client.openapi.models.V1beta1PodDisruptionBudgetSpec, v1/PersistentVolumeClaim=class io.kubernetes.client.openapi.models.V1PersistentVolumeClaim, v1/PortworxVolumeSourceFluentImpl=class io.kubernetes.client.openapi.models.V1PortworxVolumeSourceFluentImpl, v1/PersistentVolumeClaimSpecFluent=interface io.kubernetes.client.openapi.models.V1PersistentVolumeClaimSpecFluent, v1/NetworkPolicyEgressRuleFluentImpl=class io.kubernetes.client.openapi.models.V1NetworkPolicyEgressRuleFluentImpl, v1/SecretList=class io.kubernetes.client.openapi.models.V1SecretList, v1/ServiceListFluentImpl=class io.kubernetes.client.openapi.models.V1ServiceListFluentImpl, v1/RoleRefBuilder=class io.kubernetes.client.openapi.models.V1RoleRefBuilder, extensions/v1beta1/IngressTLS=class

**Comment by brendandburns** [comment]
This is a CRD (custom resource definition) you can use the instructions here:
https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

to generate the code for this, and then you will need to register it with the YAML processor.

**Comment by yue9944882** [comment]
@jerryhu1234 are you referring to https://github.com/kubernetes-sigs/application?

**Comment by jerryhu1234** [comment]
> @jerryhu1234 are you referring to https://github.com/kubernetes-sigs/application?
Not yet, l will deal with it.
