### ISSUE TITLE
V1Deployment Bean Deserialization error

### ISSUE THREAD

**Issue by Rick-yi** [kubernetes-client/java#1340]
Not an integer (through reference chain: org.snebpaas.core.tool.api.R["data"]->io.kubernetes.client.openapi.models.V1Deployment["spec"]->io.kubernetes.client.openapi.models.V1DeploymentSpec["strategy"]->io.kubernetes.client.openapi.models.V1DeploymentStrategy["rollingUpdate"]->io.kubernetes.client.openapi.models.V1RollingUpdateDeployment["maxSurge"]->io.kubernetes.client.custom.IntOrString["intValue"]

Solution：The actual value is a string, but a parameter exception was thrown while using the get method

**Comment by brendandburns** [comment]
I'm not sure I understand the issue that you are facing? `maxSurge` can either be an int or a String in the YAML and thus it is represented by an `IntOrString` object in the Deployment. Can you provide more details about the problem you are facing and how to reproduce it?

Thanks!

**Comment by topjung3** [comment]
I guess it relates to https://github.com/kubernetes-client/java/issues/177. Should be used Gson or this (https://stackoverflow.com/questions/35359430/how-to-make-jackson-ignore-properties-if-the-getters-throw-exceptions/35416682)

@brendanburns 
Could be supported ObjectMapper using POJO?

**Comment by Rick-yi** [comment]
> 我想这与[＃177有关](https://github.com/kubernetes-client/java/issues/177)。应该使用Gson或此（https://stackoverflow.com/questions/35359430/how-to-make-jackson-ignore-properties-if-the-getters-throw-exceptions/35416682）
> 
> @brendanburns
> 可以是使用POJO的kubernetes-client / java支持的ObjectMapper吗？

thanks!
