### ISSUE TITLE
Maven Package with Latest

### ISSUE THREAD

**Issue by TWood67** [kubernetes-client/java#136]
Hi all, 

I'm working on a project that has this as a maven dependency. I recently found a bug which was fixed in https://github.com/kubernetes-client/java/commit/ae400e7a45c5988437ac902dcfeb0b97cb2f408c. Do you plan on pushing an updated package soon? It would be greatly appreciated!

Thank you!

**Comment by brendandburns** [comment]
cc @lwander master of all things maven...

**Comment by brendandburns** [comment]
Duplicate of https://github.com/kubernetes-client/java/issues/138
