### ISSUE TITLE
Provide fluent nested builders for model objects.

### ISSUE THREAD

**Issue by iocanel** [kubernetes-client/java#137]
Currently, the generated model has a builder-like structure baked inside the model objects. 
Given the depth of the model, it would really help if the builders supported more advanced features like nesting, visitors and in-lining (similar to what we have in the https://github.com/fabric8io/kubernetes-client). 

**nesting** makes it so much easier to create model objects directly in java. It's faster to write, it's more IDE friendly etc.

**visitors** allow making changes, without having to explicitly traverse the object tree. (e.g. allows doing things like `visit all Pod Specs in the tree and add a sidecar container` without having to care if the spec is under a Deployment, DeploymentConfig, Pod, ReplicaSet etc).

**in-lining** allows to use the builder structure but instead of building the object directly to pass the object to a function. This allows to seamlessly integrate the builder into the client dsl.

Now, if we could get those builders either as part of the kubernetes module, it would open up the room of aligning with the https://github.com/fabric8io/kubernetes-client.

**Comment by brendandburns** [comment]
Feel free to start writing them :) `io.kubernetes.client.fluent` or somesuch...

We could also generate them, I suppose, but someone needs to write the generator...

**Comment by brendandburns** [comment]
(another option is to use protocol buffers and the proto-client which are somewhat more fluent, in some ways)

**Comment by iocanel** [comment]
@brendanburns: I've written a generator myself that we used for the fabric8 kubernetes-client.
So let'me try to integrate it and see how it goes.

**Comment by pires** [comment]
@iocanel did you make any progress?

**Comment by iocanel** [comment]
On 02.16.18, Paulo Pires wrote:
>@iocanel did you make any progress?

Yeah, I do have something working. Will create a pull request
shortly.

**Comment by brendandburns** [comment]
@iocanel cool, would love to see it!

**Comment by saturnism** [comment]
would love to see this merged! i enjoy the fabric8 client a lot :)

**Comment by rhuss** [comment]
@iocanel I know, it has been some time and you are probably still very busy. But is there any chance for this PR still to happen ? 'would be really happy to help out here, too, as I think it would be a super awesome addition. We need something like this for the fabric8-maven-plugin to switch and would love to switch to kubernetes-client.

**Comment by brendandburns** [comment]
This was fixed with #323 and #357 has an example.
