### ISSUE TITLE
Add ability to set OkHttpClient in ApiClient and ClientBuilder

### ISSUE THREAD

**Issue by btleedev** [kubernetes-client/java#1374]
One of our services monitors multiple Kubernetes clusters that can be added and removed by our users. Because of this, we're continuously creating instances of the ApiClient. The problem is that this in turn creates an OkHttpClient with a new connection pool and dispatcher.

As far as I can tell there's no way to avoid creating a new connection pool and dispatcher when we create the OkHttpClient. Using `ApiClient#setHttpClient(OkHttpClient)` doesn't help as it just replaces the default ApiClient created when instantiating OkHttpClient.

We'd like to be able to be able set the OkHttpClient via the ClientBuilder. That way we would be able to only instantiate one connection pool and dispatcher used across all instances of ApiClient.

If this feature makes sense, I can take a look and create a PR for it.

**Comment by yue9944882** [comment]
@btleedev SGTM, plz feel free to send a pull for the purposing change

**Comment by Nikhil1Raina** [comment]
Has this feature been implemented? If so, is there some documentation or example that could you used to illustrate the use of this feature??
I seem to have a very similar issue going on and would like to solve it!
