### ISSUE TITLE
Retrieving secret returns bad malformed data

### ISSUE THREAD

**Issue by tlawrie** [kubernetes-client/java#1377]
When using the listNamespacedSecret() method to retrieve a secret along with the getData() method, the data in the secret is malformed i.e.

```
class V1Secret {
    apiVersion: null
    data: {authenticated-emails-list=[B@85e4898}
    immutable: null
    kind: null
    metadata: class V1ObjectMeta {
        annotations: null
        clusterName: null
        creationTimestamp: 2020-11-13T04:18:02.000+11:00
```

Where as `data: {authenticated-emails-list=[B@85e4898}` should be base64 encoding string.

This is SDK version 10.0.0

**Comment by yue9944882** [comment]
@tlawrie the values under `data` are the base64 decoded byte arrays. you dont need to do the manual encoding.

**Comment by tlawrie** [comment]
Hi @yue9944882 that is correct.

The output above is the toString() of the V1Secret object returned by listNamespacedSecret().

I am trying to do secret.getData().getKey("authenticated-emails-list") and decode the data.

However its returning "Illegal base64 character". and the data returned of `[B@85e4898` does not match what I see when I do kubectl get secret -o yaml.

**Comment by brendandburns** [comment]
`"[B@85e4898"` looks like the Java representation of a byte array, not the byte array itself, I suspect that you are doing the following:

`decodeBase64(secret.getData().getKey(...).toString())`

That's not going to work, since the `byte[]` toString doesn't provide the data in the byte array.

If that is what you are doing, you should pass the raw byte array to `Base64.Decode.decode(...)` instead of using `toString()`

**Comment by yue9944882** [comment]
> I am trying to do secret.getData().getKey("authenticated-emails-list") and decode the data.

no, the other way round. the `byte[]` under key `"authenticated-emails-list"` is already decoded. if it's originally a `String` then just cast to `String` will work. 

> However its returning "Illegal base64 character". and the data returned of [B@85e4898 does not match what I see when I do kubectl get secret -o yaml.

^^^ you're supposed to do base64 encoding instead of decoding to compare the values.

**Comment by brendandburns** [comment]
But just to be super clear: `"[B@85e4898"` is `byte[].toString()` not the content of the byte array. (https://stackoverflow.com/questions/1040868/java-syntax-and-meaning-behind-b1ef9157-binary-address)

**Comment by tlawrie** [comment]
Thank you everyone for your help.

The code that ended up working is below for future people searching.

```
  private String getSecretDataProp(V1Secret secret, String key) {
    String data = null;
    
    try {
      if (secret != null && secret.getData() != null && secret.getData().containsKey(key)) {
        LOGGER.info("Data: \n" + new String(secret.getData().get(key)));
        data = new String(secret.getData().get(key));
      }
    } catch (NullPointerException e) {
      LOGGER.warn("No matching data key found");
    }

    return data;
  }
```

**Comment by rupamroy2006** [comment]
> 

thank you very much for the code snippet. This really helped solve the cryptic problem of reading the data from V1Secret for me.
