### ISSUE TITLE
Propose release 1.0.0-beta2

### ISSUE THREAD

**Issue by westse** [kubernetes-client/java#138]
Would like recent additions, (like [this one](https://github.com/kubernetes-client/java/pull/108)).

**Comment by lwander** [comment]
SGTM, I'm traveling but would like to run the release next week. Any concerns @brendandburns or @mbohlool?

**Comment by brendandburns** [comment]
LGTM.

(@lwander if you train me in how to do a release, I can help too :)

**Comment by Rafaesp** [comment]
It would be useful to have new version released soon

**Comment by markxnelson** [comment]
Hi, is it possible to get an idea of when you are planning to run this release? Thanks

**Comment by brendandburns** [comment]
@lwander any ideas? Do we have the process documented somewhere? If it's documented, (or you just have a rough pointer) I'm happy to do the release myself...

Thanks!

**Comment by kondapally1989** [comment]
Will swagger related issues (like patch<k8_objects> and delete<k8_objects>) be addressed in this release ?

**Comment by markxnelson** [comment]
Hi Brendan,
I saw in another thread that the process is documented here: 
https://github.com/kubernetes-client/java/blob/master/RELEASES.md

Mark Nelson
Architect
http://redstack.wordpress.com
1 (972) 963-9435

**Comment by neuromantik33** [comment]
I desperately need a release soon, as [PR 106](https://github.com/kubernetes-client/java/pull/106) is required otherwise leaking connections and not usable in production...

**Comment by brendandburns** [comment]
Ok, I believe I have sucessfully pushed the release.

Can someone validate?

**Comment by markxnelson** [comment]
Thanks @brendanburns I can see it in oss.sonatype now, but not in central yet, i think there is a delay though.

**Comment by markxnelson** [comment]
We can pull it from maven central now.  Thank you very much for getting this release out!

**Comment by brendandburns** [comment]
Closing this, since the release is done.
