### ISSUE TITLE
Examples can be out of sync with the released library.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1383]
When we re-generate the code, the APIs can change (e.g. the number of parameters) so the checked in examples are compatible with HEAD rather than with the latest release of the library.

We need to figure out a way to both have the examples work at HEAD but also have examples that work with the most recently released library. Perhaps a separate directory?

cc @yue9944882 wdyt?

**Comment by yue9944882** [comment]
> We need to figure out a way to both have the examples work at HEAD but also have examples that work with the most recently released library. Perhaps a separate directory?

@brendandburns i think so. in #1386, i separated examples into two sub-module for release-10 and release-11 (the yet coming release) and meanwhile there's a symlink file named release-last that points at release-10 which is used by the README page. so next time when we start a release-12, we just need to switch release-last to release-11 and remove release-10. wdyt?

**Comment by brendandburns** [comment]
Makes sense to me. I'm going to close this issue since #1386 merged.

We may want to add this symlink stuff as a maven task in the pom.

**Comment by brendandburns** [comment]
Closing this because it has been addressed.
