### ISSUE TITLE
How can I  update ConfigMap

### ISSUE THREAD

**Issue by Sherlock-Harden** [kubernetes-client/java#1390]
~~~
    String kubeConfigPath = System.getenv("HOME") + "/.kube/config";
    ApiClient apiClient = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();
    apiClient.setDebugging(true);
    CoreV1Api coreV1Api = new CoreV1Api(apiClient);
    try {
      coreV1Api.patchNamespacedConfigMap(
          "test",
          "default",
          new V1Patch("{\"data\":{\"k8s-app: 1\"}}"),
          "true",
          null,
          null,
          false);
    } catch (ApiException e) {
      e.printStackTrace();
    }
~~~

Prompt modification unsuccessful, return Error codes 422
Where did I make a mistake?
Please help me to check it. 
thank you.

**Comment by brendandburns** [comment]
422 indicates that your patch is malformed. It looks like you are using JSON patch, so you need to explicitly tell the system that you are doing that. We have utilities to make this easier.

Please have a look at the example here:
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-10/src/main/java/io/kubernetes/client/examples/PatchExample.java

**Comment by Sherlock-Harden** [comment]
Thanks a lot
