### ISSUE TITLE
Access Service-Catalog in k8s

### ISSUE THREAD

**Issue by Logan-Gong** [kubernetes-client/java#1393]
How to use java interface for access service-catalog api just like ''/apis/servicecatalog.k8s.io/v1beta1/serviceinstances" ?

**Comment by brendandburns** [comment]
That API is a custom resource (CRD) there are details about how to generate CRD code here:

https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

**Comment by LoganKung** [comment]
> 该 API 是一个自定义资源 （CRD），下面提供了有关如何生成 CRD 代码的详细信息：
> 
> https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

It will generate "pretty","dryRun","fieldManager" parameters in the url of POST request when I use "createNamespacedCustomObject" function. This is not supposed to be. I found it by tracking the "localVarpath" and other variables related to the request during the debug process. Then  program will throw ”Unprocessable Entity“ Exception. But it will succeed when I call svc-catalog's api directly without these three parameters and the rest of the request is the same as in client.
How can I use these three parameters in the function correctly ? Thank you very much.
