### ISSUE TITLE
UpdateWatchEventFilter and DeleteWatchEventFilter's javadoc are mixed up

### ISSUE THREAD

**Issue by d47853** [kubernetes-client/java#1398]
The Javadoc on the two event filters seems to clash with what is implemented in the KubernetesControllerFactory, specifically in the in the [UpdateFilterAdapter](https://github.com/kubernetes-client/java/blob/e28c5c03af8f1bc5ce9e4c2a48cfb1baea8a10f8/spring/src/main/java/io/kubernetes/client/spring/extended/controller/factory/KubernetesControllerFactory.java#L253) and [DeleteFilterAdapter](https://github.com/kubernetes-client/java/blob/e28c5c03af8f1bc5ce9e4c2a48cfb1baea8a10f8/spring/src/main/java/io/kubernetes/client/spring/extended/controller/factory/KubernetesControllerFactory.java#L268).

UpdateWatchEventFilter:
```java
/** ...
 * <p>A update-event filter must have the signature as {@link
 * java.util.function.BiPredicate<ApiType, Boolean>} where the 1st parameter is the
 * "before-deletion" state of the resource and the 2nd indicates whether the cache entry for the
 * resource is stale.
```

DeleteWatchEventFilter:
```java
/** ...
 * <p>A delete-event filter must have the signature as {@link
 * java.util.function.BiPredicate<ApiType,ApiType>} where the 1st parameter is the old state of the
 * resource and the 2nd is the new state.
```

I believe these should be the other way around.

**Comment by brendandburns** [comment]
Feel free to send a PR with the fix. Thanks!

**Comment by d47853** [comment]
I'll probably get a bit of time next week if that's alright
