### ISSUE TITLE
PatchExample.java: String "applyYamlStr" contains json

### ISSUE THREAD

**Issue by synox** [kubernetes-client/java#1399]
While the variable mentions yaml, the content is JSON. It still seems to work. 

https://github.com/kubernetes-client/java/blob/7f6107250891fd953c47d1a025efa893867cd319/examples/examples-release-11/src/main/java/io/kubernetes/client/examples/PatchExample.java#L50-L51

**Comment by brendandburns** [comment]
As of YAML 1.2, YAML is a super-set of JSON, so all JSON is valid YAML.

**Comment by synox** [comment]
Thanks, great to know 👍🏻
