### ISSUE TITLE
Enh Req: read methods should return null rather than throw ApiException on not found

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#140]
Examples include CoreV1Api.readNamespacedPod.  It would be much more useful if this method could return null on not found rather than throwing an ApiException.

Since there are legitimate exceptions, we're stuck with code like this:

            V1Pod existingPod = null;
            try {
                existingPod = coreApi.readNamespacedPod(name, namespace, "false", false, false);
            } catch (ApiException e) {
                if (e.getMessage().contains("Not Found")) {
                    // we expected this exception - this is ok, nothing to do
                }
            }

**Comment by lwander** [comment]
This is a tricky one - `kubectl` will return `1` when your resource can't be found, and the API returns 404 under the hood. One could argue that throwing an exception is more consistent with the rest of the client/API.

Then again, not finding a resource isn't really "exceptional".

WDYT @brendandburns

**Comment by rjeberhard** [comment]
I'd really prefer the null than the exception, but I could live with an exception if we could get a NotFoundException that I could catch rather than having to catch ApiException and rely on checking the message contents (i.e. fragile).

Would it be possible to have different exceptions for these different return codes?

**Comment by lwander** [comment]
Exceptions based on return code sound like a good idea.

Let me see if swagger supports this

**Comment by lwander** [comment]
Maybe we can define a new response for 404 judging by the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object). @mbohlool knows more about this than I do.

**Comment by mbohlool** [comment]
A new response 404 looks good to me. How does it look in generated client? Will it result in a NotFound exception? There are two places we can add that 404 response. We can add it in main repo (I recommend this, in a file called `api_installer.go`) or as a post-processing step in generator. Let's open an issue for it in gen/ repo.

**Comment by brendandburns** [comment]
The ApiException is introspectable for the return code.

I think throwing an exception is the right thing to do here.  If we wanted to create a more fluent client code (see #137) then returning `null` from that client might be the right thing to do there...

**Comment by rjeberhard** [comment]
We've consistently updated our code to catch the exception and check for 404, so this is no longer an issue.
