### ISSUE TITLE
Why does deleteNamespacedServiceAccount return V1ServiceAccount while other resources delete methods return V1Status?

### ISSUE THREAD

**Issue by liavyona** [kubernetes-client/java#1400]
I have a list of resources which I work generic with (using reflection). I have a list of future tasks to delete them all. All resources delete methods return `V1Status` while `deleteNamespacedServiceAccount` returns `V1ServiceAccount` why is that?

**Comment by liavyona** [comment]
I tried to convert it myself by:
```
        if ("ServiceAccount".equals(kind)) {
            Call call = ((CoreV1Api) api).deleteNamespacedServiceAccountCall(name, namespace, null, null, null, null, null, null, null);
            Type returnType = (new TypeToken<V1Status>() {
            }).getType();
            ApiResponse<V1Status> response = ((CoreV1Api) api).getApiClient().execute(call, returnType);
            return (V1Status) response.getData();
```
It returns successfully but the details and status attributes are null.

**Comment by liavyona** [comment]
I found that [this](https://github.com/kubernetes-client/java/commit/957492b92540aa6378d9045874b58e18507e937a#diff-a9fb373489afead3256afc6495ab90ee20f3a0ae0b44aa1f65342c8016b8bb8c) commit changed the return type of `deleteNamespacedServiceAccount` alongside other kubernetes resources which have been changed too (PersistVolume, Pod etc.). On the other hand, Service, Secret, ConfigMap and others remain the same. Why is that? What benefit do I have from getting the object I just deleted? V1Status can tell me whether the deletion completed successfully.
@brendandburns Why there is no aligned API to whole resources?

**Comment by brendandburns** [comment]
All of this is generated from the Kubernetes OpenAPI specification here:

https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

The truth is that delete can either return a V1Status or the object itself (see #86 for more discussion) but this isn't well represented in the OpenAPI specification.

If we wanted to correct this, we need to update the OpenAPI specification. (and also update the client generator to handle multi-return), that's not a bad thing to do, but it's also not a super high priority.

Hope that helps.
