### ISSUE TITLE
Source jars not generated for snapshots locally

### ISSUE THREAD

**Issue by dsyer** [kubernetes-client/java#1406]
I can see there is some confusion about source jars (#598 #597), but there are no source jars available locally when I build this project from source. I am confused because I see source jars in Maven Central (for releases), but no sign of how they got there. I also don't know if there is a snapshot repository (I see no sign of it in the poms) where I can get them if I don't want to build locally. Can we add the source plugin to the build, maybe?

**Comment by brendandburns** [comment]
How are you building locally? I believe that if you `mvn package` you should get source jars included.

**Comment by brendandburns** [comment]
(there's no snapshot repo, unfortunately, it would be nice to add)

**Comment by dsyer** [comment]
I think you mean `mvn install`. But, no, that isn’t working (no source jars).

**Comment by dsyer** [comment]
> (there's no snapshot repo, unfortunately, it would be nice to add)

You have snapshot deployment distribution configured in the top level pom. Have you tried using it?
