### ISSUE TITLE
Use JDK instead of Guava

### ISSUE THREAD

**Issue by dsyer** [kubernetes-client/java#1412]
Guava is a poor choice of a dependency for a library jar because it changes a lot and binary incompatibilities arise frequently downstream. It isn't used all that much in this project so it should be easy to get rid of. There was a comment in #1261 to this effect, but perhaps not enough focus for anyone to take any action.

Example: `io.kubernetes.client.util.ModelMapper` uses a mixture of utilities from Guava and Apache Commons Lang3. Probably it could at least consolidate to only use the Apache library. Ideally it should be possible to settle on just using the JDK.

**Comment by brendandburns** [comment]
I don't feel strongly about this. I've never had any problems with Guava that you describe, but I don't think we're wedded to it either. If you want to send PRs to go towards other libs, we'd be happy to review, but I don't think it is a high priority.

**Comment by dsyer** [comment]
I think we can get pretty close without too much impact. But there are some harder to fix parts as well, that might indicate other issues (e.g. `ModelMapper` as mentioned above does a classpath scan using Guava's `ClassPath` which won't work in a native image binary, so I would prefer to replace with something else anyway, like a properties file). I'll see what I can do.
