### ISSUE TITLE
Spring PrometheusScrapeEndpoint duplicates features in Spring Boot

### ISSUE THREAD

**Issue by dsyer** [kubernetes-client/java#1421]
The `PrometheusScrapeEndpoint` bears a very close resemblance to the class of the same name in Spring Boot. I don't see any issues discussing why it is there, but maybe there's some background I'm not aware of. In any case I think it would be better to simply use the "standard" Spring Boot endpoint, unless anyone knows better. (N.B. because of https://github.com/spring-projects/spring-boot/issues/24377 it would require an additional `@Bean` of type `CollectorRegistry`, but that seems like a small thing, and can be removed later.)

**Comment by yue9944882** [comment]
@dsyer the prometheus endpoint from this project will not be activated unless `"kubernetes.actuator.prometheus.enabled"` property is set. as for the compatibility w/ spring-boot's standard actuator endpoint, i opened https://github.com/kubernetes-client/java/pull/1429 to allow the existing metrics registering onto a custom registry. 

the gap is that spring-boot uses micrometer as the default SDK instead of prometheus SDK. i used micrometer SDK somewhere else and i agree it will be working perfectly. but meanwhile i noticed a few other metrics specification and SDK e.g. open-telemetry or open-observability, so before making a decision between the specifications, am leaning on staying at prometheus official library :)

**Comment by dsyer** [comment]
#1429 would be a good addition as we could then wire in the `CollectorRegistry` provided by Spring Boot. I also think we should immediately remove the `PrometheusScrapeEndpoint` from this project and replace it with a `@Bean` that exposes the default `CollectorRegistry` - that way the user can see k8s metrics on `/actuator/prometheus` with the "standard" Spring Boot configuration flag (e.g. `management.endpoints.web.exposure.include=prometheus`), and it wouldn't require usage of micrometer.

**Comment by yue9944882** [comment]
> I also think we should immediately remove the PrometheusScrapeEndpoint from this project and replace it with a @Bean that exposes the default CollectorRegistry

added another commit removing the actuator endpoints w/ the same name. plz feel free to review. thanks.

**Comment by dsyer** [comment]
That was what I had in mind. I'm not really sure why we have a `LazySingletonCollectorRegistry`. I was thinking it would just be 

```java
@Bean
  @ConditionalOnMissingBean
  public CollectorRegistry prometheusCollectorRegistry() {
    // Explicitly uses default static registry by default
    return CollectorRegistry.defaultRegistry;
  }
```

I'll add some more review comments to the PR if you like.

**Comment by yue9944882** [comment]
> That was what I had in mind. I'm not really sure why we have a LazySingletonCollectorRegistry. I was thinking it would just be

conventionally, we're supposed to register the metrics as static final fields, right? `LazySingletonCollectorRegistry` accepts collector-registry injection from spring bean context and provides static getter so that the static metrics registration can work. wdyt?

> I'll add some more review comments to the PR if you like.

for sure

**Comment by dsyer** [comment]
I don't know about that convention. It seems inconsistent with the idea that you can inject a `CollectorRegistry` into a constructor (which is most of the point of #1429 if I'm not mistaken). Anyway, that's not the point, the point is to persuade Spring Boot to use the same `CollectorRegistry` and you can do that just by re-using the global `CollectorRegistry.defaultRegistry`. That will lead to problems with global state in integration tests probably, but that's a problem with Prometheus, not with Spring Boot or Kubernetes Client.

**Comment by yue9944882** [comment]
> That will lead to problems with global state in integration tests probably, but that's a problem with Prometheus, not with Spring Boot or Kubernetes Client.

that's one of the reasons why i added `LazySingletonCollectorRegistry`. while we can work-around integration tests failure but passing a CollectorRegistry doesn't work for a few other classes in the Kubernetes Client, e.g. non-singleton classes such as Controller. if we're registering the metrics as a part of the constructor, the registration will abort complaining on the duplicated metrics name. 

> A better solution would be to use a non-static instance of CollectorRegistry everywhere.

as above, i think non-static metrics only works for singleton classes, that's mostly true for spring bean tho. am i missing anything?

**Comment by dsyer** [comment]
> the registration will abort complaining on the duplicated metrics name.

Then we have to stop using global statics, right? Or stick to `CollectorRegistry.defaultRegistry` (which was my first suggestion as it's easier).

**Comment by yue9944882** [comment]
/close

closing solved issue
