### ISSUE TITLE
Dependecy hygiene: sundr-codegen should be optional

### ISSUE THREAD

**Issue by dsyer** [kubernetes-client/java#1422]
As was noted here, the sundr code generation processor pollutes the classpath of downstream projects (including, ironically, the "extended" jar in this project, which is using commons-lang classes from the sundr jar): https://github.com/sundrio/sundrio/issues/153. Sundr really shouldn't be shading 3rd party libraries without repackaging, but it's kind of a nightmare for users of the k8s client jars, and the dependency almost certainly ought to be optional here anyway.

**Comment by brendandburns** [comment]
I'm fine with this being an optional dependency.

**Comment by brendandburns** [comment]
I'm also ok moving to a different builder generation library if there is a better option, but I haven't seen one.
