### ISSUE TITLE
Cutting 11.0.x releases

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#1441]
@brendandburns as a new release of k/k is out last month, let's cut a new major release wdyt?

**Comment by brendandburns** [comment]
Sounds good to me.

**Comment by ryanjbaxter** [comment]
@brendanburns @yue9944882 do you think that we could get a release by December 21st?

**Comment by brendandburns** [comment]
There seems to be something odd going on with pushing a release. I will work on it, but I'm not positive that I can get it done by end of day on the 21st.

**Comment by brendandburns** [comment]
Ok, I figured it out, things are pushed out to sonatype:

https://oss.sonatype.org/service/local/repositories/releases/content/io/kubernetes/client-java/11.0.0/client-java-11.0.0.jar

They should be in Maven Central in ~24hrs

**Comment by ryanjbaxter** [comment]
Thanks I see it there now.

**Comment by brendandburns** [comment]
Closing this since the release is out and the `11.0.0` PR is merged.
