### ISSUE TITLE
Implement FieldIndexer for efficient querying of owned objects

### ISSUE THREAD

**Issue by dsyer** [kubernetes-client/java#1443]
Glolang has a `client.FieldIndexer` (in `sigs.k8s.io/controller-runtime/pkg/client`) that enables (I believe) efficient querying of objects owned by a controller. I don't see anything like that here, so I guess it's a feature request.

**Comment by brendandburns** [comment]
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java#L253

But we don't have an implementation of that interface for Fields afaik. It would be a good addition.

**Comment by yue9944882** [comment]
@dsyer custom indexer is supported, the unit-test shows how to do the customization:

https://github.com/kubernetes-client/java/blob/36184250027a162a038ad9a855faf4a5bf93df49/util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java#L165

**Comment by dsyer** [comment]
/remove-lifecycle rotten

Please
