### ISSUE TITLE
V1ServiceSpec Not Deserialized

### ISSUE THREAD

**Issue by ryanjbaxter** [kubernetes-client/java#1449]
When I retrieve services from K8S it appears the spec data is not deserialized.  I cannot understand why.  Any insights or if there is a way to customize the `Excluder` so that it can be deserialized?

**Comment by brendandburns** [comment]
It should be deserialized.  What version of k8s? and what version of the client?

Can you dump the YAML using kubeclt and attach it to this issue? (anonymize as needed obviously)

**Comment by ryanjbaxter** [comment]
Thanks @brendanburns, it is something specifically about this service

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"servicea-wiremock"},"name":"servicea-wiremock","namespace":"default"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"servicea-wiremock"},"type":"ClusterIP"}}
  creationTimestamp: "2020-12-19T01:28:09Z"
  labels:
    app: servicea-wiremock
  name: servicea-wiremock
  namespace: default
  resourceVersion: "2390"
  selfLink: /api/v1/namespaces/default/services/servicea-wiremock
  uid: 73cc2135-4199-11eb-ab0d-0242ac110003
spec:
  clusterIP: 10.103.180.6
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: servicea-wiremock
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

If I fetch the `kubernetes` service I get the `spec` data.

I don't see a difference between the two.

I am using k8s 1.17 and the client is 10.0.0.

**Comment by ryanjbaxter** [comment]
Here is the YAML I applied to create the service

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicea-wiremock
  name: servicea-wiremock
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: servicea-wiremock
  type: ClusterIP
```

**Comment by ryanjbaxter** [comment]
I figured out the problem.  We had some Gson configuration that was excluding the spec that I was not aware of.  Sorry for the noise.
