### ISSUE TITLE
Use of SecureRandom() in APIClient is non-FIPS compliant

### ISSUE THREAD

**Issue by Ghatage** [kubernetes-client/java#1458]
In the APIClient.java, on [Line 1365](https://github.com/kubernetes-client/java/blob/a3e5a3234e9f96adb3de10c1770191b6831acf8e/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L1365) in the function applySslSettings() we are initializing the `sslContext` object with `new SecureRandom()`
This is incorrect as when we run any application using this API in FIPS mode, the application will fail to comply.
This is because since we are initializing with `SecureRandom()` it'll use the underlying DefaultRNG which most of the times with be from `Sun` which is non FIPS compliant.

cc @yue9944882

**Comment by brendandburns** [comment]
This code is generated. If we want to make this change it needs to be made here:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L1525

I think the right thing to do is to add a `setRandom(...)` method to the ApiClient to allow people to insert their own implementation of `Random` if they want to.

Once that PR is in the generator, we can re-generate the code.

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/blob/eb94f2bbb8671a1f2c81efa353796803b2f7a82a/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L1369

@Ghatage as far as i can see you can work-around by overriding socket-factory after the `ApiClient` instance is created. you can use the custom `Random` by re'newing an socket-factory instance, amiright?
