### ISSUE TITLE
can not watch object

### ISSUE THREAD

**Issue by qiankunli** [kubernetes-client/java#1462]
client-java version: 9.0.1 
Environment：
![image](https://user-images.githubusercontent.com/8024725/103278611-dba1b800-4a06-11eb-9762-fabaef2ba1d3.png)

watcher/informer can not trigger add/update/delete handler logic after ip=2.2 host restart.

watch code
```java
client = Config.fromToken(apiServerUrl, apiToken, false);
client.setConnectTimeout(5_000);
client.setReadTimeout(30 *60 *1000);
client.setWriteTimeout(5_000);
Configuration.setDefaultApiClient(client);
 CoreV1Api coreV1Api = new CoreV1Api();

SharedInformerFactory factory = new SharedInformerFactory();
SharedIndexInformer<V1Pod> podInformer = factory.sharedIndexInformerFor(
        (CallGeneratorParams params) -> {
            try {
                return coreV1Api.listPodForAllNamespacesCall(
                         true,null,
                        null, "deploySource=cmdb",
                        null, null, params.resourceVersion,
                        params.timeoutSeconds, params.watch,
                        null
                );
            } catch (ApiException e) {
                e.printStackTrace();
            }
            return null;
        },
        V1Pod.class,
        V1PodList.class
);
podInformer.addEventHandler(
       new PodEventHandler(...)
);
factory.startAllRegisteredInformers();
```

haproxy config
```
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /var/run/haproxy-admin.sock mode 660 level admin
    stats timeout 1800s
    user haproxy
    group haproxy
    daemon
    nbproc 1

defaults
    log     global
    timeout connect 5000
    timeout client  20m
    timeout server  20m
listen dev-kube-master
    bind 0.0.0.0:9443
    mode tcp
    option tcplog
    option dontlognull
    option dontlog-normal
    balance roundrobin
    server 192.168.2.1 192.168.2.1:6443 check inter 5s fall 2 rise 2 weight 1
    server 192.168.2.2 192.168.2.2:6443 check inter 5s fall 2 rise 2 weight 1
```
I guess that  client-java connect to 3.3 and connect to 2.2, when 2.2 restart, client-java connect to 2.1 , but can not watch event.

**Comment by yue9944882** [comment]
@qiankunli it seems to be connected w/ improper settings on ha-proxy. does ha-proxy do backend connection management? e.g. the ha-proxy instance may keep the long connections to the backend instances even if no request is being served by ha-proxy. the connection management can be conflicting w/ such long-running requests as WATCH.

**Comment by qiankunli** [comment]
> @qiankunli it seems to be connected w/ improper settings on ha-proxy. does ha-proxy do backend connection management? e.g. the ha-proxy instance may keep the long connections to the backend instances even if no request is being served by ha-proxy. the connection management can be conflicting w/ such long-running requests as WATCH.


I set `timeout server 20m`  to prevent connection close when running `kubectl exec xx bash`, is that the problem?
```
defaults
    log     global
    timeout connect 5000
    timeout client  20m
    timeout server  20m
```
