### ISSUE TITLE
Custom authenticator - Forbidden

### ISSUE THREAD

**Issue by hfgbarrigas** [kubernetes-client/java#1482]
Trying to use a gcp service account to make requests. When running within a cluster, although I implemented a custom Authenticator, I'm getting Forbidden.

Here's the authenticator implementation:

```java

    public RefreshableGCPAuthenticator(GoogleCredentials credentials) {
        this.credentials = credentials;
    }

    @Override
    public String getName() {
        return "gcp";
    }

    @Override
    public String getToken(Map<String, Object> config) {
        return this.credentials.getAccessToken().getTokenValue();
    }

    @Override
    public boolean isExpired(Map<String, Object> config) {
        if (this.credentials.getAccessToken() == null || this.credentials.getAccessToken().getExpirationTime() == null) {
            return true;
        }

        Date expirationTime = this.credentials.getAccessToken().getExpirationTime();
        return expirationTime.toInstant().compareTo(Instant.now()) <= 300000L;
    }

    @Override
    public Map<String, Object> refresh(Map<String, Object> config) {
        try {
            this.credentials.refreshIfExpired();
            AccessToken accessToken = this.credentials.getAccessToken();

            config.put(ACCESS_TOKEN, accessToken.getTokenValue());
            config.put(EXPIRY, accessToken.getExpirationTime());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return config;
    }
```

The client is instantiated as follow:

```java
        GoogleCredentials credentials = (GoogleCredentials) credentialsProvider.getCredentials();
        KubeConfig.registerAuthenticator(new RefreshableGCPAuthenticator(credentials));
        ApiClient client = ClientBuilder.standard().build();
        io.kubernetes.client.openapi.Configuration.setDefaultApiClient(client);

       BatchV1Api batchApi = new BatchV1Api(apiClient);
```

Any pointers? I'm sure the service account in question has permissions to create namespaced jobs.

**Comment by brendandburns** [comment]
Are you using a Kubernetes service account? If so, you should just use the standard client, no authenticator is needed.

If you are using a `$KUBECONFIG` file, you need to send us the contents of the file (anonymized of course) so that we can debug further.

In particular, the name needs to match the name of the authenticator in the kubeconfig file.

**Comment by hfgbarrigas** [comment]
The available `GCPAuthenticator` doesn't support refresh as [#290](https://github.com/kubernetes-client/java/issues/290) seems to indicate.

I'm using a specific service account in a pod running within the cluster. Not keen on using the cluster default svc acc and workload identity is not used in that particular cluster.
Given this, I ended up creating that refreshable authenticator with a svc acc mounted as a secret volume.

Looked inside the pod and $KUBECONFIG is not defined and no ~/.kube/config is present.

**Comment by brendandburns** [comment]
I think you'll need to create a synthetic Kubeconfig file with the authProvider set to 'gcp'

What is missing in your current code is the link between the client and your custom authenticator.

Right now without a kubeconfig file your client detects that it's in a Pod and it uses the Kubernetes Service Account.

fwiw, using the Kubernetes Service Account is definitely a more common approach (and probably the more "kubernetes native" approach also) so you should consider just using Kubernetes service accounts, the client supports that out of the box.

**Comment by brendandburns** [comment]
You could also consider implementing the `Authentication` interface and use `ClientBuilder.setAuthentication(...)` instead

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L351

**Comment by hfgbarrigas** [comment]
Ended up using k8s service accounts. Though I'm not 100% pleased managing  permissions in two different places, cloud services through iam and k8s workloads through native service accounts, works for now. 

Pondered on your suggestion, creating a synthetic kubeconfig or providing a custom authentication. However, felt a bit hacky and decided against it. Closing this since no further action is needed.

Thanks for reaching out.
