### ISSUE TITLE
how to make proxy in java client ?

### ISSUE THREAD

**Issue by sunnoy** [kubernetes-client/java#1495]
client -> proxy(client java) ->  kube-api 

proxy can help client authentication to kube-api

is java client give something like clien-go's 

```go
// TransportFor returns an http.RoundTripper that will provide the authentication
// or transport level security defined by the provided Config. Will return the
// default http.DefaultTransport if no special case behavior is needed.
func TransportFor(config *Config) (http.RoundTripper, error) {
	cfg, err := config.TransportConfig()
	if err != nil {
		return nil, err
	}
	return transport.New(cfg)
}
```

**Comment by brendandburns** [comment]
This isn't something that the client does out of the box.

You will need to create an HTTP server and then forward each request using raw requests.

You can look at the code in Watch.java to see how to perform raw requests.

**Comment by sunnoy** [comment]
ok thks
