### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/output_dir/swagger.json.unprocessed' in Docker Desktop for Windows

### ISSUE THREAD

**Issue by niaomingjian** [kubernetes-client/java#1497]
Following the latest document https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md#example-commands-for-local-crd-manifests in Windows10 with **Docker Desktop for Windows** encountered  this IOError.

E:\ws>`docker run -v "/e/ws/tmp/crds/":/tmp/crds/ -v /var/run/docker.sock:/var/run/docker.sock -v "/e/ws/tmp/java":"/output_dir" -ti --network host docker.pkg.github.com/kubernetes-client/java/crd-model-gen:v1.0.3 /generate.sh -u /tmp/crds/crontab-crd.yaml -n com.example.stable -p com.example.stable -o "/tmp/java"`

Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
customresourcedefinition.apiextensions.k8s.io/crontabs.stable.example.com created
Verifying CRD installation..
customresourcedefinition.apiextensions.k8s.io/crontabs.stable.example.com successfully installed
Deleting cluster "kind" ...
KUBERNETES_CRD_GROUP_PREFIX: com.example.stable
OPENAPI_MODEL_LENGTH: 2
PACKAGE_NAME: com.example.stable
CLIENT_VERSION: 5.0-SNAPSHOT
OUTPUT_DIR: /output_dir/gen

rendering settings file to /tmp/settings
reading input openapi specs
--- Building docker image kubernetes-java-client-gen-with-openapi-generator:v1...
Sending build context to Docker daemon  167.4kB
Step 1/9 : FROM ghcr.io/yue9944882/crd-model-gen-base:v1.0.0
 ---> 0d430f452f5a
Step 2/9 : ARG OPENAPI_GENERATOR_COMMIT
 ---> Using cache
 ---> 4ce5737cc485
Step 3/9 : ARG GENERATION_XML_FILE
 ---> Using cache
 ---> 22ac32e6dfaf
Step 4/9 : ARG OPENAPI_GENERATOR_USER_ORG=OpenAPITools
 ---> Using cache
 ---> dc282c320061
Step 5/9 : COPY openapi-generator/generate_client_in_container.sh /generate_client.sh
 ---> Using cache
 ---> 6cb0f92caf40
Step 6/9 : COPY preprocess_spec.py /
 ---> Using cache
 ---> 2281982bd14c
Step 7/9 : COPY custom_objects_spec.json /
 ---> Using cache
 ---> 13a49bdb34f1
Step 8/9 : COPY ${GENERATION_XML_FILE} /generation_params.xml
 ---> Using cache
 ---> 77a99941b56e
Step 9/9 : ENTRYPOINT ["mvn-entrypoint.sh", "/generate_client.sh"]
 ---> Using cache
 ---> 01fc1d2d9760
Successfully built 01fc1d2d9760
Successfully tagged kubernetes-java-client-gen-with-openapi-generator:v1
--- Running generator inside container...
/source/openapi-generator /
/
--- Downloading and pre-processing OpenAPI spec
Traceback (most recent call last):
  File "//preprocess_spec.py", line 475, in <module>
    sys.exit(main())
  File "//preprocess_spec.py", line 451, in main
    with open(unprocessed_spec, 'r') as content:
**IOError: [Errno 2] No such file or directory: '/output_dir/swagger.json.unprocessed'**

`kubernetes-java-client-gen-with-openapi-generator:v1` container couldn't get `swagger.json.unprocessed` file generated in 
"E:\ws\tmp\java\gen\swagger.json.unprocessed" by `docker.pkg.github.com/kubernetes-client/java/crd-model-gen:v1.0.3`.  In Docker Linux, it was able to access this file. How do they share it? But in windows environment, they can't. Copying the file to `/output_dir` in `kubernetes-java-client-gen-with-openapi-generator:v1` container could resume the execution. But it's not good. How to execute that docker run command smoothly in Docker Desktop?

**Comment by brendandburns** [comment]
Right now, only Linux is really tested for this use case. I would use WSL2 if you want to run on Windows.

**Comment by brendandburns** [comment]
Closing this since generating on Windows + Docker is currently out of scope.

**Comment by wenjunma004** [comment]
I met this issue on Ubuntu too.

**Comment by dsyer** [comment]
Me too. @brendandburns can we re-open it please?
