### ISSUE TITLE
feat request : load a yaml for undefiled model type

### ISSUE THREAD

**Issue by Rajpratik71** [kubernetes-client/java#1499]
As far as i am able to find that , client library needs and only support predefined "models" for loading a yaml into that 

e.g.

`Yaml yaml = new Yaml();
ExtensionsV1beta1Deployment body = yaml.loadAs(new FileReader("deployment.yaml"), ExtensionsV1beta1Deployment.class);
ExtensionsV1beta1Api api = new ExtensionsV1beta1Api();
api.createNamespacedDeployment("default", body, "");
`

So , here my question and issue is how to load/apply following yaml using "kubernetes-client" library.

Below providing yaml for " Scheduling Policy" used by [Intel's Telemetry aware scheduler ](https://github.com/intel/telemetry-aware-scheduling) or many other as Kubernetes supports extending of "Kube-scheduler" by addons.

**[DeschedulerPolicy](https://github.com/intel/telemetry-aware-scheduling/blob/master/deploy/health-metric-demo/descheduler-policy.yaml)**

`
apiVersion: "descheduler/v1alpha1" 
kind: "DeschedulerPolicy" 
strategies: 
  "RemovePodsViolatingNodeAffinity": 
    enabled: true 
    params: 
      nodeAffinityType: 
        - "requiredDuringSchedulingIgnoredDuringExecution" 
`

**[TASPolicy](https://github.com/intel/telemetry-aware-scheduling/blob/master/deploy/health-metric-demo/health-policy.yaml)**

`
apiVersion: telemetry.intel.com/v1alpha1
kind: TASPolicy
metadata:
  name: demo-policy
  namespace: default
spec:
  strategies:
    deschedule:
      rules:
      - metricname: health_metric
        operator: Equals
        target: 2
    dontschedule:
      rules:
      - metricname: health_metric
        operator: Equals
        target: 1
      - metricname: health_metric
        operator: Equals
        target: 2
    scheduleonmetric:
      rules:
      - metricname: health_metric
        operator: LessThan
`

@brendandburns

**Comment by brendandburns** [comment]
You need to define your own class to represent the CRD object, then yaml.loadAs should work as expected.

Alternately, you can use the instructions here:
https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

To generate classes for your CRDs.

**Comment by Rajpratik71** [comment]
Hi @brendandburns , I tried this approach , but it failed with following log

customresourcedefinition.apiextensions.k8s.io/taspolicies.telemetry.intel.com created
Verifying CRD installation..
customresourcedefinition.apiextensions.k8s.io/taspolicies.telemetry.intel.com failed publishing openapi schema because it's attached non-structral-schema condition.

**Comment by brendandburns** [comment]
It looks like the intel CRD doesn't have a corresponding Swagger/OpenAPI specification. Without a definition of the API structure, we can't generate the code.

Looks like your only option is to hand-code an equivalent Java object for the intel CRD.

**Comment by Rajpratik71** [comment]
ok. Will try on work arounds.
