### ISSUE TITLE
Rewrite support for k8s loadbalancer in spring module

### ISSUE THREAD

**Issue by dsyer** [kubernetes-client/java#1505]
I don't like any of the annotations in the spring module much (can we review them all at some point?), but `@KubernetesEndpointsLoadBalanced` is by far the most egregious. The fact that it only works with field injection (a notorious antipattern) is the worst part, but I have other questions. Could we maybe re-implement it as a `@Qualifier` or just a plain factory?

**Comment by brendandburns** [comment]
cc @yue9944882 I'm definitely not enough of a Spring expert to comment too deeply. Can you provide more details of what you would change?

**Comment by yue9944882** [comment]
@dsyer the load-balancer support is yet experimental. am always open to the changes, plz feel free to submit pull requests to the codebase
