### ISSUE TITLE
getClassNamesFromPackage prints jarFile to stdout

### ISSUE THREAD

**Issue by SockenSalat** [kubernetes-client/java#1506]
in Version `11.0.0` in the class `io.kubernetes.client.util.ModelMapper` in line 415 the name of the containing jar file is printed to stdout:

`System.out.println(">" + jarFileName);`

That is a bit annoying ;-)

**Comment by brendandburns** [comment]
oops, that's almost certainly some stray debugging code that got left in. Happy to have a PR to remove that and I can push a patch version (or we'll get a PR done sometime soon)
