### ISSUE TITLE
WebSocketsExample: Missing example path and authentication error

### ISSUE THREAD

**Issue by scholzj** [kubernetes-client/java#151]
The WebSocketExample accepts the path as an argument. That is ok. But it would be great if you can include some example path which can be used (for examle as comment or in the README file).

I tried it for example with `/api/v1/pods?watch=true` (but also other adresses). But I always get "403 Forbidden" error although with all other example the authentication worked fine:

```
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Does the WebSocket example need some special authentication? I can see this problem with both master and 1.0.0-beta1. I'm runnng it against Minikube v0.24.1 (Kubernetes 1.8.0).

**Comment by brendandburns** [comment]
I'm not sure if that path is supported.  You want something like:

`/api/v1/namespaces/default/pods?watch=true`

But in reality, if you want to do a Watch, you should look at the [watch example](https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java)

The web socket example is pretty low level.

**Comment by scholzj** [comment]
Even with the path you suggested, I still get the same exception. To be honest I know that I probably wont need this and that as long as the higher level calls work this is irrelevant. But I wanted to try it since it is in the examples.

The port forwarding example which uses web sockets works for me (well, for some ports - see #156 ), so I don't think there is a general issue with the WebSockets client. But it seems strange why some paths such as `/api/v1/namespaces/default/pods?watch=true` return HTTP 403.

**Comment by brendandburns** [comment]
I'll try to verify on my machine and see what's up.

--brendan

________________________________

**Comment by brendandburns** [comment]
Sorry I didn't catch this before. `?watch=true` doesn't use websockets, it's a vanilla GET.

You need something like:
```
/api/v1/pods/namespace/default/pods/<podname>/attach?stdout=true
```

which actually does use web sockets.

**Comment by scholzj** [comment]
Cool, thanks. #157 looks exactly as something what I needed / was looking for. Thanks.
