### ISSUE TITLE
Are two concurrent updates of two keys in a configmap using JSON patch, free from race conditions?

### ISSUE THREAD

**Issue by thamidurm** [kubernetes-client/java#1513]
I'm sorry if this isn't the place to ask this question.  Say, I have a config map with keys, "key1" and "key2". If I have one thread per key and these threads replace the value corresponding to the key using JSON patch, is there a possibility of one update being affected by the other?

**Comment by brendandburns** [comment]
Short answer "maybe" each patch is independent, and the patching itself doesn't involve locking in the api server, so it's definitely possible.

If you want to detect potential conflicts you should include a `resourceVersion` in your patch and you will get a 409 if there is a conflict (which you can then catch the exception and retry)

See discussion of resourceVersions here:
https://stackoverflow.com/questions/52910322/kubernetes-resource-versioning

And an example of testing the behavior here:
https://gitlab.cncf.ci/kubernetes/kubernetes/commit/a503e5301a5cb2bd2a7915c08635484dee5603b6

**Comment by thamidurm** [comment]
@brendanburns Thanks you for taking time to reply. Appreciate it.

**Comment by sinloss** [comment]
> ...
> And an example of testing the behavior here: https://gitlab.cncf.ci/kubernetes/kubernetes/commit/a503e5301a5cb2bd2a7915c08635484dee5603b6

In case someone needs it, tests mentioned above could now be found here
https://github.com/kubernetes/kubernetes/commit/a503e5301a5cb2bd2a7915c08635484dee5603b6
