### ISSUE TITLE
How to set namespace in Kubectl.Apply method from client-java-extended library

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1520]
Hello,

If I do kubectl apply by specifying particular resource type I am able to specify namespace
```
Kubectl.apply(V1Deployment.class).namespace(namespace).fieldManager("kubectl")
        .forceConflict(true).resource((V1Deployment) resource).execute();
```
but if I do generic way as below: I am loading all resources using Yaml.loadAll method and iterating over each to call kubectl apply.
```
Class clazz = resource.getClass();
Kubectl.apply(clazz).fieldManager("kubectl")
        .forceConflict(true).resource((KubernetesObject) resource).execute();
```
I am not able to set namespace. How should we set the namespace in this case?

Thanks,
Swarda

**Comment by brendandburns** [comment]
What does "not able to set namespace" mean? Does it mean that the code doesn't compile? The call doesn't work?

What error are you seeing?

As far as I know that code should compile, though not all resources are namespaced, and so if you try to set a namespace for a non-namespaced resource it will probably throw an error.

**Comment by saparaj** [comment]
I am getting compile error if I try to do it as below:
```
private static void apply(KubeConfig config, String filePath) throws IOException {
        List<Object> resourceList = Yaml.loadAll(new FileReader(filePath));
        for (Object resource: resourceList) {
            String pNamespace = getNamespace(config, "default", (KubernetesObject) resource);
            Class clazz = resource.getClass();
            KubernetesObject appliedObject = Kubectl.apply(clazz).namespace(pNamespace).fieldManager("kubectl").resource((KubernetesObject) resource).execute();
            System.out.println("Resource of kind: "+ appliedObject.getKind() + " and name: " + appliedObject.getMetadata().getName() + " applied");
        }
    }
```
Compilation Error:
Error:(81, 75) java: cannot find symbol
  symbol:   method fieldManager(java.lang.String)
  location: class io.kubernetes.client.extended.kubectl.Kubectl.NamespacedApiClientBuilder

**Comment by saparaj** [comment]
This worked 
```
Class clazz = resource.getClass();
KubectlApply kubectlApply = (KubectlApply) Kubectl.apply(clazz).fieldManager("kubectl")
        .forceConflict(true).resource((KubernetesObject) resource).namespace(namespace);
appliedObject = kubectlApply.execute();
```

**Comment by brendandburns** [comment]
Closing this since I believe the issue was resolved.
