### ISSUE TITLE
Connect to remote cluster with ca-authority-data and other contents of kubeconfig file

### ISSUE THREAD

**Issue by nknkgithub** [kubernetes-client/java#1521]
Hi, I am using https://github.com/kubernetes-client/java and I want to connect to remote kubernetes cluster.

As a input I will be getting server address, client-certificate-data, client-certificate-key, ca-authority-data(base 64 encoded certificate contents) and whether insecure-skip-tls-verify is true or not.

a) I am converting all the certificate contents to bytes and i.e.

```
byte [] caCertValue = Base64.getDecoder().decode(<CA-certificate-data-instrings>.getBytes("UTF-8"));

//Same done for client certificate and key as well and passing verifySsl as true when certificate-authority-data is present
ApiClient client = new ClientBuilder().setBasePath(<https://ip:6443>)
						.setAuthentication(new ClientCertificateAuthentication(clientCertValue, clientCertKey))
						.setVerifyingSsl(verifySsl).setCertificateAuthority(caCertValue).build();
Configuration.setDefaultApiClient(client);
CoreV1Api api = new CoreV1Api();
V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
```

b) I want to have same functionality as kubectl behaves with kubeconfigfile. Is this proper way of configuring? Or any other way I should configure when contents of kubeconfig file is given as input.

c) I would be have to connect to different remote clusters. So every time I get input I should be following same procedure? 

d) And any function available to write kubeconfig file (append as well since we want to connect to remote kubernetes cluster) based on contents of kubeconfig file.

**Comment by nknkgithub** [comment]
Help is required

**Comment by brendandburns** [comment]
This client library loads things in the same way as `kubectl` (at least it should)

Your best bet is to load the `KubeConfig` object from a `java.io.Reader`
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L82

And then build the client from the KubeConfig:
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L274

**Comment by nknkgithub** [comment]
I will not be getting kubeconfig file, instead will be getting some contents of kubeconfig file. i.e. contents of ca-authority-data, contents of client-certificate-data, contents of client-certificate-key and whether insecure skip tls verify is true or not.  So 

`byte [] caCertValue = Base64.getDecoder().decode(<CA-certificate-data-instrings>.getBytes("UTF-8"));

//Same done for client certificate and key as well and passing verifySsl as true when certificate-authority-data is present
ApiClient client = new ClientBuilder().setBasePath(<https://ip:6443>)
						.setAuthentication(new ClientCertificateAuthentication(clientCertValue, clientCertKey))
						.setVerifyingSsl(verifySsl).setCertificateAuthority(caCertValue).build();

Configuration.setDefaultApiClient(client);
CoreV1Api api = new CoreV1Api();
`

wanted to check whether this can be used or any alternative is available.

**Comment by nknkgithub** [comment]
Help required. In case any other api or function available

**Comment by brendandburns** [comment]
It is possible to load everything through the builder, but helping you with the specific code is beyond the scope of this library. If you run into a bug, please file it via the issues queue.
