### ISSUE TITLE
"generate-model-from-third-party-resources.md" fails with Infinispan CRDs

### ISSUE THREAD

**Issue by fabiobrz** [kubernetes-client/java#1523]
Hi all, more a question here than an issue, maybe.
I went through https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md and it worked with the provided example YAML.

Then I switched to some real third party CRDs and I always get the following error:
```
...
error: error parsing ... error converting YAML to JSON: yaml: line 89: mapping values are not allowed in this context
```
No matter what we have at line 89, either a description string, a property or even a comment, it would fail anyway (at least it fails for me).

Here are some commands I've run recently:
```
$ docker run   --rm   -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host   ghcr.io/yue9944882/crd-model-gen:v1.0.3   /generate.sh   -u https://github.com/infinispan/infinispan-operator/blob/master/deploy/crds/infinispan.org_infinispans_crd.yaml  -n org.infinispan   -p org.infinispan   -o "$(pwd)"
```

```
$ docker run   --rm   -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host   ghcr.io/yue9944882/crd-model-gen:v1.0.3   /generate.sh   -u https://github.com/fabiobrz/infinispan-operator/blob/codegen-test/deploy/crds/infinispan.org_infinispans_crd.yaml  -n org.infinispan   -p org.infinispan   -o "$(pwd)"
```

```
$ docker run   --rm   -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host   ghcr.io/yue9944882/crd-model-gen:v1.0.3   /generate.sh   -u https://github.com/fabiobrz/infinispan-operator/blob/codegen-test/deploy/crds/infinispan.org_backups_crd.yaml  -n org.infinispan   -p org.infinispan   -o "$(pwd)"
```

```
$ docker run   --rm   -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host   ghcr.io/yue9944882/crd-model-gen:v1.0.3   /generate.sh   -u https://github.com/keycloak/keycloak-operator/blob/master/deploy/crds/keycloak.org_keycloakbackups_crd.yaml  -n org.infinispan   -p org.infinispan   -o "$(pwd)"
```

Did anybody have the same issue? Or am I missing something?

Thanks in advance.

**Comment by yue9944882** [comment]
> No matter what we have at line 89, either a description string, a property or even a comment, it would fail anyway (at least it fails for me).

it means that your CRD manifests is not a valid yaml document, can you verify if `kubectl apply -f <yaml file>` works against any cluster?

**Comment by fabiobrz** [comment]
HI @yue9944882 and thanks for your reply.
I followed your hint and yes it gets created. And that helped me to understand that the issue is probably due to some unconventional content, which was returned by the URL that I used in the commands above.
As soon as I replaced it with with the `https://raw.githubusercontent.com/...` URL it started working.

Thanks again.

**Comment by fabiobrz** [comment]
BTW @yue9944882 - one more question. Does a codegen Maven plugin exist or is planned at all. I am aware that Docker execution is behind it so could be difficult but I'd like to have your feedback on this.
