### ISSUE TITLE
crd-model-gen 1.0.3 error

### ISSUE THREAD

**Issue by zhangzerui20** [kubernetes-client/java#1526]
when I run 

`
docker run \
  --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":"$(pwd)" \
  -ti \
  --network host \
  talltangrui/crd-model-gen:v1.0.3 \
  /generate.sh \
  -u /Users/trecool/Documents/work_temp/generate_crd/tsf.cloud.tencent.com_buildtasks.yaml \
  -n tsf.cloud.tencent.com \
  -p com.example.stable \
  -o "$(pwd)"
`

I get 
`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.251 s
[INFO] Finished at: 2021-02-05T10:28:58Z
[INFO] ------------------------------------------------------------------------
---Done.
---Done.
cp: can't stat '/Users/trecool/Documents/work_temp/generate_crd/gen/src/main/java/com/example/stable/models': No such file or directory
`

**Comment by yue9944882** [comment]
> /Users/trecool/Documents/work_temp/generate_crd/tsf.cloud.tencent.com_buildtasks.yaml

is it mounted into the code-gen runner container?

**Comment by brendandburns** [comment]
Closing due to lack of response. Please use `/reopen` if further assistance is needed.
