### ISSUE TITLE
VersionApi call not allowed when ClusterRole system:discovery is used in binding to a service account

### ISSUE THREAD

**Issue by TheFrogPad** [kubernetes-client/java#153]
See https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/VersionApi.java

## Issue:

_VersionApi.getCodeCall()_ uses `/version/` when calling _apiClient.buildCall()_ at line 102.

If you bind the ClusterRole _system:discovery_ to a service account when RBAC is enabled the call fails with HTTP 403

## Workaround:

```
kubectl create clusterrole get-versionresources --verb=get --non-resource-url='/version/*'
kubectl create clusterrolebinding get-versionresources-binding --clusterrole=get-versionresources --serviceaccount=mynamespace:myaccount
```

**Comment by brendandburns** [comment]
oops, didn't mean to close this...

**Comment by brendandburns** [comment]
I've sent a PR to upstream Kubernetes to add this permission to the `system:discovery` role.

**Comment by TheFrogPad** [comment]
Great! I had wondered if the `system:discovery` role might need a change but wasn't sure.

So when I did a search on [kubernetes.io](https://kubernetes.io/docs/search/) I did not seem to find information on the non-resource URLs. Can you provide a reference to the spec about non-resource URLs that you have referenced here for the version?

Thanks

**Comment by brendandburns** [comment]
https://github.com/kubernetes/kubernetes/tree/master/API/openapi/swagger.json

(That's from memory, there might be some typos in the URL but if will get you close...)

--brendan

________________________________

**Comment by TheFrogPad** [comment]
Okay, I was just looking around in the repo and the path should be https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

 I noticed when looking in API folder there is also https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/version.json which has no trailing slash.

Thanks again for the help...

**Comment by brendandburns** [comment]
Oh, that inconsistency is super bad.

The OpenAPI is the "new" spec...  the swagger 1.2 will be deprecated soon.

--brendan



________________________________________

**Comment by liggitt** [comment]
I wouldn't expect the openapi spec to have a trailing slash

**Comment by brendandburns** [comment]
@liggitt 

Well, it's there:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json
Sadly the swagger is too huge for me to direct link via github, but search for '/version/'

@mbohlool any idea why the trailing slash is there?

**Comment by brendandburns** [comment]
I'm closing this, since the change is merged into upstream Kubernetes, and there's not much more we can do here unless the openapi spec changes.
