### ISSUE TITLE
Get the response on command execution in container

### ISSUE THREAD

**Issue by libin0811** [kubernetes-client/java#1531]
my code like this 

` int retCode = Kubectl.exec().namespace("default")
                .name("helloworld-7959bf49bb-c8j7c")
                .container("helloworld-container")
                .command(new String[]{"ls"})
                .execute();`

for example: i want to get the reponse by command "ls" ,but the method return a type "int",not the file list ,how can i get the command return, thank you

**Comment by brendandburns** [comment]
Have a look at the Exec example here:
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/ExecExample.java
