### ISSUE TITLE
10.0.1 release is not synced correct.

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [kubernetes-client/java#1534]
@brendandburns I think the same think has happened with the 10.0.1 release that happened with the 9.0.1 release. 

To see this take a look at the definition of LeaderElectionConfig in the jar. It doesn't match the source code.

**Comment by brendandburns** [comment]
Hrmph, I will take a look. I did have some challenges getting the 10.0.1 done :(

**Comment by himanshug** [comment]
I am also waiting for that to get fixed or maybe release 10.0.2 ( see https://github.com/kubernetes-client/java/pull/1463#issuecomment-774596002 )

**Comment by tony-clarke-amdocs** [comment]
/remove-lifecycle stale The 10.0.1 release is still not valid.

**Comment by tony-clarke-amdocs** [comment]
/remove-lifecycle rotten What is the most recent release?
