### ISSUE TITLE
EventLogger produces unacceptable JSON Patches when updating events

### ISSUE THREAD

**Issue by chris-chambers** [kubernetes-client/java#1536]
The event patch creation code (for updating events whose count will be > 1) produces a JSON patch that the API server doesn't accept (returns HTTP 422).

https://github.com/kubernetes-client/java/blob/46607021cf4a0d5dfc6ef3414eb0ce7b3d1c1210/extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java#L44-L49

It looks like this was originally ported from Go client, which has `strategicpatch.CreateTwoWayMergePatch` to handle patch creation.  This version is creating the patch content manually, but has a couple of errors:

- The `\"count\":\"%d\"` section should have its value unquoted: `\"count\":%d`
- The date should, I think, be formatted as an ISO-8601 string value, rather than the behavior of `Configuration.getDefaultApiClient().getJSON().serialize(now)`, which produces a structured JSON representation of the datetime

The result of this error is that logging any event with the same content (so that an existing event should have its count updated, rather than creating a new event) fails silently.

I monkey-patched like this and got it working:

```java
 new V1Patch( 
     String.format( 
         "{\"message\":\"%s\",\"count\":%d,\"lastTimestamp\":\"%s\"}",
         event.getMessage(), 
         event.getCount(), 
         DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(now))); 
```

But, I'm not familiar with this code, so maybe there is a better solution.

**Comment by chris-chambers** [comment]
As an aside, I see that these classes are marked `legacy`.  Are there other classes I should prefer to use for emitting events?

**Comment by brendandburns** [comment]
cc @yue9944882

**Comment by yue9944882** [comment]
@chris-chambers thank you for reporting this, i just opened a fix for this issue.

> As an aside, I see that these classes are marked legacy. Are there other classes I should prefer to use for emitting events?

a newer event API was recently introduced which basically uses `events.k8s.io/events` api instead of `v1/events` (i.e. legacy events api). as far as i can see, even if the older api now goes "legacy" but it will keep working for a long period of time. in a word, we dont have to land on the new api and the legacy should be working fine.
