### ISSUE TITLE
Annotations are object, not simple Map<String, String>

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#154]
V1ObjectMeta supports a Map<String, String> for annotations and this is consistent with the documentation that describes the annotations as a key/value map.  However, the API reference defines the annotations as an object and kubernetes creates values that are a multi-level map, like this:

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"rjeberha","name":"weblogic-operator-2696653343","uid":"57150e30-e1c7-11e7-86db-002128d7c01c","apiVersion":"extensions","resourceVersion":"10157941"}}
  creationTimestamp: 2017-12-15T18:39:53Z

**Comment by brendandburns** [comment]
Annotations are a (string, string) Map. In the example you pasted, that `{ ... }` is a string as denoted by the YAML block quote character `|`

Can you send a pointer to the API reference? I don't think that sounds correct and should probably be fixed.

**Comment by rjeberhard** [comment]
https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#objectmeta-v1-meta

annotations object | Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations

The reference I pasted "looks" like a String -> Multi-level map.  If that is being manually processed then I understand.

**Comment by brendandburns** [comment]
Yeah, many systems do encode objects as JSON strings and then place them in annotations, but it is on the individual systems to know how to do the String -> Object translation, not the main Kubernetes API...




________________________________________
