### ISSUE TITLE
Watch API always gives event type as modified and not added

### ISSUE THREAD

**Issue by arunpmohan** [kubernetes-client/java#1555]
Kubernetes watch API always provides the event type as modified and we never get "added" event type response even though the pod is really added.

we are using listNamespacePodCall Api for a particular label of pods. This used to work in 1.17 and the version we are using is 8.0.0.1

This is happening from k8 1.20 for us. Any pointers..

{"host":"arcsm-centralmanagement-0.mysps","level":"INFO","log":{"classname":"com.alcatel.tpapps.common.server.monitoring.kubernetes.KubernetesContainerRegistryImpl:487","message":"POD CHANGE: Type: **MODIFIED**, pod name: arprov-provisioning-789686b66f-8wcq2, phase: Running, resource type: comsvc","stacktrace":"","threadname":"KubernetesContainerRegistryImpl-Pod-1"},"time":"2021-02-23T05:36:29.959Z","timezone":"UTC","type":"log","system":"bcmt-app","systemid":"5"}

**Comment by yue9944882** [comment]
@arunpmohan the `listNamespacePodCall` wont be intercepting/tweaking any watch responses from the apiserver i believe. 

>>  even though the pod is really added.

is the added pods in the same namespace you're watching?

**Comment by arunpmohan** [comment]
Yes it is in the same namespace.

**Comment by brendandburns** [comment]
Can you update to 11.0.0? 8.0.0 isn't supported with Kubernetes 1.20.x

**Comment by brendandburns** [comment]
Closing this issue due to lack of response, please `/reopen` if further assistance is needed
