### ISSUE TITLE
Is Impersonator supported in Kubernetes client library?

### ISSUE THREAD

**Issue by ichengchang** [kubernetes-client/java#1563]
I have set up an in-cluster impersonator in GKE so that the API can assume the identity of the impersonator after authenticating via GCP. I can't seem to find an example on how I can include the impersonator when making an API request. Could someone tell me how this can be done with the Java client?

**Comment by brendandburns** [comment]
If you have a kubeconfig file that works with `kubectl`, this library should be able to load it. If it doesn't please file a bug.

If you don't have a working kubeconfig file, then I think your question is out of scope for this library.

**Comment by brendandburns** [comment]
Closing this issue due to lack of response. Please use `/reopen` if necessary to re-activate the issue.
