### ISSUE TITLE
Unprocessable Entity is not a helpful error message

### ISSUE THREAD

**Issue by theAkito** [kubernetes-client/java#1566]
As explained [here](https://github.com/kubernetes-client/java/issues/385#issuecomment-428423594) and experienced, for example, [here](https://github.com/jenkinsci/kubernetes-cd-plugin/issues/102) the message one is getting for providing an invalid spec is not helpful, at all.

It would be nice to see the exact location where the config is wrong in what way exactly without needing to turn on any debugging options whatsoever.

**Comment by brendandburns** [comment]
As is mentioned in the previous issue, if you look at the body of the response (available in the ApiException object `ApiException.getBody()`) you should get a more detailed error string.

We just reflect what the server returns, there's not much more that we can do here. Closing this issue. Please use `/reopen` if you need further assistance.
