### ISSUE TITLE
Cutting a 11.0.1 release

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#1571]
majorly for #1570 #1552 

ref: https://github.com/kubernetes-client/java/issues/1533#issuecomment-788041724

cc @brendandburns @ryanjbaxter

**Comment by brendandburns** [comment]
Yep, will do once the cherry-picks are merged.

**Comment by ryanjbaxter** [comment]
@brendanburns When do we expect that to happen?  The Spring Cloud team is planning a release next week and we would like this release

**Comment by brendandburns** [comment]
@ryanjbaxter the merges should go in shortly (~1pm Pacific)

I should have time @ 2pm pacific to try to cut the release.

Assuming that all goes well (which based on previous releases is a pretty big assumption) then it will be in maven central tomorrow, but sadly this is all best effort and our release machinery is creaky at best.

I'll update this issue by 3pm today with the status.

**Comment by brendandburns** [comment]
Quick update: the picks merged:
https://github.com/kubernetes-client/java/pull/1570

**Comment by brendandburns** [comment]
Side-note: if anyone is a maven/release expert, suggestions on improving our flow (it's documented here: https://github.com/kubernetes-client/java/blob/master/RELEASES.md) are very welcome. Frankly it's a pain these days.

**Comment by brendandburns** [comment]
So it turns out the cherry-pick isn't clean and the branch was broken (side note, we need to fix out automation to build on the release branch before merge)

I sent https://github.com/kubernetes-client/java/pull/1572 to fix things, but I'll need @yue9944882 to review the PR before it can merge and then we can try again w/ the release.

So we are delayed for now.

**Comment by brendandburns** [comment]
Update #2, fix is merged. I tried to push a release but it looks like it didn't show up on sonatype. I feel like this happened last time too, though I can't remember what I fixed to make it work. I will try again tomorrow.

**Comment by brendandburns** [comment]
Update 3. Fixed things (https://github.com/kubernetes-client/java/pull/1573) 11.0.1 is staged to sonatype. You should see it in Maven central in ~24 hours.

(definitely still looking for people to help improve our release flow b/c it is _not_ fun)

**Comment by ryanjbaxter** [comment]
Wahoo!  Thanks @brendanburns I see it in maven central now!

**Comment by brendandburns** [comment]
@ryanjbaxter please do validate that you see the expected patches in the release, we've had some problems in the past and I'd like to validate that it's working correctly.

**Comment by ryanjbaxter** [comment]
All of our tests pass using that build
