### ISSUE TITLE
11.0.0 patchNamespacedCustomObject exception “PatchOptions.meta.k8s.io...”

### ISSUE THREAD

**Issue by ZLEternity** [kubernetes-client/java#1575]
client version : 11.0.0
k8s server version : 1.19
customObjectsApi.patchNamespacedCustomObject(group, "v1", "uat-es", "elasticsearches"
          , cluster_name, body, null, null, false);
![image](https://user-images.githubusercontent.com/39403809/109934087-11b13000-7d07-11eb-87b0-9d1b0f7b682a.png)

then , throw exception

 {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"PatchOptions.meta.k8s.io \"\" is invalid: force: Forbidden: may not be specified for non-apply patch","reason":"Invalid","details":{"group":"meta.k8s.io","kind":"PatchOptions","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: may not be specified for non-apply patch","field":"force"}]},"code":422}

i cant understand the reason, search the same error (google), https://github.com/kubernetes-client/java/issues/958

but, found a new exception;
"json: cannot unmarshal object into Go value of type jsonpatch.Patch","reason":"BadRequest","code":400"

so...what can I do ? I hope someone can answer it，thx～～～

**Comment by brendandburns** [comment]
These errors are coming from the server. I would recommend starting with `kubectl patch ...` and get to a patch that works. You should then be able to convert that to a patch that works with this client library.

Given that I don't think this is an error in the library, I'm closing this issue. If you determine that it is a problem with this library, please use the `/reopen` command to reopen the issue and add more information.

**Comment by mehrdadsilver** [comment]
Is this issue fixed? None of `true` or `false` or `null` values for `force` parameter works with this library when calling `patchNamespacedCustomObject` method.

**Comment by ZLEternity** [comment]
> Is this issue fixed? None of `true` or `false` or `null` values for `force` parameter works with this library when calling `patchNamespacedCustomObject` method. For `true` or `false` we get the same error of:
> 
> `[{"reason":"FieldValueForbidden","message":"Forbidden: may not be specified for non-apply patch","field":"force"}]},"code":422`
> 
> and when we set it to null, we get:
> 
> `json: cannot unmarshal object into Go value of type jsonpatch.Patch","reason":"BadRequest","code":400"`



（patchNamespacedCustomObject）method, unable to pass the test,
i view the method implementation, find 'PatchUtils' can solve this problem;

`res = PatchUtils.patch(
          Object.class,
          () -> apiInstance.patchNamespacedCustomObjectCall(
              this.apiGroup, this.apiVersion, this.apiNameSpace, this.apiPlural, name,
              new V1Patch(JSON.toJSONString(body)),
              dryRun, fieldManager, null, null
          ),
          V1Patch.PATCH_FORMAT_JSON_MERGE_PATCH,
          apiInstance.getApiClient()
      );`

**Comment by vsabavat** [comment]
> json: cannot unmarshal object into Go value of type jsonpatch.Patch","reason":"BadRequest","code":400"
I run into this issue even with c-api. If I use null to the force field or true or false  get similar errors. Is this fixed yet? Also, with null field I get the unmarshal object error, how do we fix it?

**Comment by ifofafk** [comment]
> > Is this issue fixed? None of `true` or `false` or `null` values for `force` parameter works with this library when calling `patchNamespacedCustomObject` method. For `true` or `false` we get the same error of:
> > `[{"reason":"FieldValueForbidden","message":"Forbidden: may not be specified for non-apply patch","field":"force"}]},"code":422`
> > and when we set it to null, we get:
> > `json: cannot unmarshal object into Go value of type jsonpatch.Patch","reason":"BadRequest","code":400"`
> 
> （patchNamespacedCustomObject）method, unable to pass the test, i view the method implementation, find 'PatchUtils' can solve this problem;
> 
> `res = PatchUtils.patch( Object.class, () -> apiInstance.patchNamespacedCustomObjectCall( this.apiGroup, this.apiVersion, this.apiNameSpace, this.apiPlural, name, new V1Patch(JSON.toJSONString(body)), dryRun, fieldManager, null, null ), V1Patch.PATCH_FORMAT_JSON_MERGE_PATCH, apiInstance.getApiClient() );`

thank u so much
