### ISSUE TITLE
[QUERY] Features of Official Java Client

### ISSUE THREAD

**Issue by weiqingy** [kubernetes-client/java#1581]
Hi team

Besides the release notes https://github.com/kubernetes-client/java/releases, I'm wondering if there is any other docs/wikis  introducing the details about the fixes and new features added in the past months (since July 2020)?

We are trying to build an operator, and I have some questions on the official Java client, and would like your confirmation & suggestions.
- Is the Spring Framework is a hard dependency? 
- as we will need to write tests for scenarios where we are manipulating Kubernetes APIs and want to verify behavior of their Kubernetes controllers, Im wondering if the client offers any testing framework? 
- For Watching resources, Is the client via plain HTTP calls or WebSockets?
- Do the official Java client have extensions for other libs like Knative, Kudo?  
- Do the client support cluster-connection configuration via System Properties, Environment Variables, ~/.kube/config file and ServiceAccount token and mounted CA certificates? or users need to do all the configuration when using client from a system/ within a Pod?
- To be able to use CustomResources, do users need to add an additional dependency 'client-java-extended' in the code? Do users have to provide POJOs for your Custom Resources? 

Thank you!

**Comment by brendandburns** [comment]
Answers:
1) Spring is not a hard dependency, it's entirely optional.
2) There's no built in framework (e.g. mocks) but it will work with JUnit and WireMock (there are lots of examples of such tests in the repo)
3) It's plain HTTP for now, but it does support HTTP/2
4) There are some extensions generated, and there are [instructions](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md) for how to generate your own for others.
5) The goal is to support every kubeconfig file that `kubectl` works with. We think we have pretty good compatability. If you hit issues, please file an issue.
6) You don't have to use the `extended` library, but you do need to provide either JSON or POJO for your custom objects.

Hope that helps!

**Comment by weiqingy** [comment]
Thanks for the reply, @brendandburns . Its helpful!

**Comment by brendandburns** [comment]
Closing the issue. Please use `/reopen` if there is more info needed.
