### ISSUE TITLE
12.0.0 release?

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1586]
@yue9944882 shall we do a 12.0.0 release? Kubernetes 1.20.x is out in the wild and the 1.21 release is coming soon.

**Comment by yue9944882** [comment]
@brendandburns SGTM!

**Comment by brendandburns** [comment]
Fixed by #1592

**Comment by brendandburns** [comment]
This is pushed to Maven central now.

**Comment by yue9944882** [comment]
@brendandburns the branch `release-12` is not present in the repo, am i missing anything?

**Comment by brendandburns** [comment]
Ah, yes, we need to create a release branch at the relevant commit. I'll see what I can do.

**Comment by brendandburns** [comment]
Ok, I created the `release-12` branch at the same commit as the release.

**Comment by yue9944882** [comment]
how do you think about cleaning up the following branches from the repo? it seems that they're just phantom branches created upon a few release attemption:

```
release-11-take2
release-11-take3
release-11-take4
release
release2
release3
brendandburns-patch-1
brendandburns-patch-2
lwander-patch-1
release-prep
```

**Comment by brendandburns** [comment]
Yep, we can definitely delete those.

The current release mechanism sadly pushes to the upstream instead of my fork. I don't know how to convince it to push to my fork...

**Comment by brendandburns** [comment]
Closing this issue since deleting those branches is unrelated to the `12.0.0` release.
