### ISSUE TITLE
Cannot connect to Amazon EKS

### ISSUE THREAD

**Issue by ThemGo** [kubernetes-client/java#1591]
Hi, 
I am trying to connect to kubernetes service on aws (Amazon EKS). 
My first simple task is to list all pods. On command line this works flawlessly (“kubectl get pods -A”), but unfortunately not with official Java client library for kubernetes v11.0.1.
My code is like example class https://github.com/kubernetes-client/java/blob/master/examples/examples-release-11/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java 

Output is
```
Could not connect to the endpoint URL: "https://sts.eu-central-1.amazonaws.com/"
15:35:28.578 [main] ERROR io.kubernetes.client.util.KubeConfig - aws failed with exit code 255
Exception in thread "main" io.kubernetes.client.openapi.ApiException: Forbidden
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:993)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:905)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:35956)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:35848)
```
What is wrong?

**Comment by brendandburns** [comment]
This looks like a network error, in particular it looks like the client can't talk to your server. Do you have an HTTP proxy in the mix?

**Comment by ThemGo** [comment]
Yes indeed, there is a proxy in the mix.
On command line (where it works) it is set like this: `set https_proxy=proxyserver:8080`

For Java it is set by VM arguments: `-Dhttps.proxyHost=proxyserver -Dhttps.proxyPort=8080`
Without these VM arguments there would be a timeout instead of “forbidden”, this is the output:

```
Could not connect to the endpoint URL: "https://sts.eu-central-1.amazonaws.com/"
09:01:05.683 [main] ERROR io.kubernetes.client.util.KubeConfig - aws failed with exit code 255
Exception in thread "main" io.kubernetes.client.openapi.ApiException: java.net.SocketTimeoutException: connect timed out
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:908)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:35956)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:35848)
```

And, in difference to the first try, there is no "handleResponse" in the stack trace..

**Comment by brendandburns** [comment]
So I think that the issue is that the client is trying to talk to the amazon token server to get an authentication token and that isn't working.

The relevant code is here:
https://github.com/kubernetes-client/java/blob/fbf46529894c7f189cc5a604716aae50769d2caf/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L258

My guess is that this is happening because somehow the HTTP proxy settings aren't being passed through.

Can you send the `exec` section of your KubeConfig file into this issue? Please remember to redact any personal data before sending.

**Comment by ThemGo** [comment]
This is the whole kube config file (without personal data):

[config_blurred.txt](https://github.com/kubernetes-client/java/files/6150341/config_blurred.txt)

**Comment by ThemGo** [comment]
I got it working now! The proxy must be set twice, both on command line and as a vm argument.
Thanks for the support.
