### ISSUE TITLE
missing V1Patch.md for client java

### ISSUE THREAD

**Issue by AudiVehicle** [kubernetes-client/java#1598]
V1Patch.md should be found https://github.com/kubernetes-client/java/tree/master/kubernetes/docs/V1Patch.md, but i do not see anything.

please fix this,3Q.

**Comment by brendandburns** [comment]
Those docs are generated, but V1Patch is a hand-written object. I don't think we will be adding it to the generated docs, but there's a good example of how to use it here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/PatchExample.java
