### ISSUE TITLE
io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by barlass** [kubernetes-client/java#1614]
While connecting from within a pod in the cluster keep getting handshake failure. Upgrading the JDK version is not an option.
Is there a work around ?

Using openjdk version "1.8.0_91" , Kube Client Version 12.0.0 , Kubernetes Version - 1.19.7

**Comment by brendandburns** [comment]
Can you provide more details about the exception and your kube config?

Please fill in all of the information requested in the issue template.

**Comment by barlass** [comment]
Cant share the kubeconfig. So closing issue.
