### ISSUE TITLE
Behavior of ReflectorRunnable changed in version 12.0.0

### ISSUE THREAD

**Issue by domainname** [kubernetes-client/java#1621]
**Describe the bug**

In commit https://github.com/kubernetes-client/java/commit/013a9b74339a883b8c7870385a2d6ba37330ad27, the behavior of ReflectorRunnable changed a little bit. A new catch block was added. See below.

https://github.com/kubernetes-client/java/blob/f58be100d49d8739317d575f393ae28b81a1b361/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L157-L163

Before the commit, all exceptions are caught by this

https://github.com/kubernetes-client/java/blob/f58be100d49d8739317d575f393ae28b81a1b361/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L164-L166

and exception handler will be invoked.

I'm not sure whether this behavior change is intended or not. It seems to me that exception handler should be invoked in the new catch block as well.

@yue9944882 BTW, what's the purpose of the exception handler? I plan to use it to do a pause when networking error (such as UnknownHostException) occurs, in order to avoid too frequent retries. Does this make sense? Well, I know that it is hard to add a custom exception handler for ReflectorRunnable at this point.

** Client Version **
`12.0.0`

** Kubernetes Version **
N/A

** Java Version **
Java 8

**To Reproduce**

**Expected behavior**

Exception handler should be invoked in the new catch block as well probably.

**KubeConfig**
N/A

**Server (please complete the following information):**
 - OS: Linux
 - Environment: local
 - Cloud: Azure

**Additional context**

N/A

**Comment by brendandburns** [comment]
HTTP_GONE indicates that you are trying to watch from a resourceVersion that no longer exists. It means that the watch needs to re-list and start from the current state.

There are some more details here:

**Comment by brendandburns** [comment]
The dropping non-410 responses is a bug, and is fixed in #1617

**Comment by yue9944882** [comment]
@domainname the change is not intended, so i had #1617 to fix it. we will also cherry-picking this to 11.0.x and 12.0.x releases. the point of exception handler is providing extensibility for customizing logic for handling errors based on the exception object. e.g. in some scenarios, we hope to push notifications when the reflector is failing unexpectedly.

**Comment by domainname** [comment]
@yue9944882 @brendandburns Thank you for the fix. Do you have an ETA of 12.0.1 release?

**Comment by tony-clarke-amdocs** [comment]
@brendanburns @domainname any idea when next release might be made, waiting on a release with [this](https://github.com/kubernetes-client/java/pull/1611) PR merged.

**Comment by brendandburns** [comment]
@tony-clarke-amdocs We should definitely cut a 13.0.0 release soon. Thanks for the reminder.
