### ISSUE TITLE
Difficult to extend exception handler

### ISSUE THREAD

**Issue by domainname** [kubernetes-client/java#1629]
@yue9944882 @brendandburns 

It's difficult to extend exception handler in ReflectorRunnable. Controller does not expose a property for developer to inject a customized exception handler. Nor does SharedInformerFactory. One probably has to write his/her own SharedInformerFactory and Controller, in order to inject a customized exception handler.

**Comment by brendandburns** [comment]
Can you give an example of the code you would like to write or the function signature you are looking for?

We can definitely look to improve things.

Thanks!

**Comment by domainname** [comment]
Hi @brendanburns. This is a typical way to write a informer. There is nowhere to inject an exception handler.

```java
        SharedIndexInformer<V1Deployment> deploymentInformer =
            factory.sharedIndexInformerFor(
                (CallGeneratorParams params) -> api.listDeploymentForAllNamespacesCall(
                    null, null, null, null, null,
                    null, params.resourceVersion, null, params.timeoutSeconds, params.watch,
                    null),
                V1Deployment.class, V1DeploymentList.class);
        deploymentInformer.addEventHandler(deploymentEventHandler);
```

The function signature is 

```java
public class SharedInformerFactory {
  ...
  public synchronized <ApiType extends KubernetesObject, ApiListType extends KubernetesListObject>
      SharedIndexInformer<ApiType> sharedIndexInformerFor(
          CallGenerator callGenerator,
          Class<ApiType> apiTypeClass,
          Class<ApiListType> apiListTypeClass);
  ...
}
```

I hope to see a signature like this:

```java
  public synchronized <ApiType extends KubernetesObject, ApiListType extends KubernetesListObject>
      SharedIndexInformer<ApiType> sharedIndexInformerFor(
          CallGenerator callGenerator,
          Class<ApiType> apiTypeClass,
          Class<ApiListType> apiListTypeClass,
          BiConsumer<Class<ApiType>, Throwable> exceptionHandler);
```

**Comment by brendandburns** [comment]
I think I'm still confused. The `DefaultSharedIndexInformer` doesn't have any `catch` blocks in it, the ReflectorRunnable has a parameter where you can pass in the handler.

Are you talking about the `Controller` class, it is true that doesn't make it easy to pass in an exception handler, we could certainly add a parameter there.

Thanks!

**Comment by domainname** [comment]
`SharedInformerFactory ` builds an instance of `DefaultSharedIndexInformer`. And `DefaultSharedIndexInformer` constructs an instance of `Controller`. Finally `Controller` instantiates `ReflectorRunnable` at

https://github.com/kubernetes-client/java/blob/fbf46529894c7f189cc5a604716aae50769d2caf/util/src/main/java/io/kubernetes/client/informer/cache/Controller.java#L116.

There is no way to pass my own exception handler to ReflectorRunnable from `SharedInformerFactory`. I have to write my own `Controller`, `SharedIndexInformer` and `SharedInformerFactory`.

**Comment by brendandburns** [comment]
Ah, yes. That path is twisty :)

We can plumb something in here. Thanks for the patience.

**Comment by domainname** [comment]
@brendandburns Hi Brendan, do you have any plan to do some improvements in custom exception handler?

**Comment by cbuschka** [comment]
Hey @domainname have prototyped injecting an exception handler on https://github.com/cbuschka/kubernetes-client-java/tree/issue1629_extend_exception_handling_from_shared_informer_factory Can you tell me, if this change would solve your problem? If yes, I can see to finalize it with better null handling and test coverage.

**Comment by domainname** [comment]
Hi @cbuschka , this looks awesome to me. Thank you! I would assume that this change will be in 14.0.1. Do you have an ETA of 14.0.1?

**Comment by cbuschka** [comment]
Sorry, I am not involved in the release process. @brendandburns  Can you answer the question?

**Comment by brendandburns** [comment]
@domainname if you prepare a cherry-pick PR we'd be happy to merge that and make sure it gets into the `14.0.1` release.

**Comment by cbuschka** [comment]
@brendandburns The change is already on the master. See 0642e7b8fc1c3bdebd77136c35cacd577c006e62 Do we still need a cherry-pick PR for 14.0.1? What is the target branch for the cherry-pick?

**Comment by brendandburns** [comment]
The target branch would be the `release-14` branch. Once the commit is present there, we can see about cutting a new release.

**Comment by brendandburns** [comment]
Alternately, we will cut a `15.0.0` to support Kubernetes `1.23.x` sometime in the next month or so which will include this fix.
