### ISSUE TITLE
Unauthorized error when creating a job

### ISSUE THREAD

**Issue by OberstHorst** [kubernetes-client/java#163]
Hey,

i want to create Job using the Java Kubernetes API. My tool runs fine when using a minikube cluster, but fails if i try to execute it against a (testing) Kubernetes cluster that was deployed using ubuntu conjure-up. The cluster has been modified to deny anonymous access and uses RBAC and Node authorization and basic auth authentication. i can use kubectl create -f foo.yaml to create a job, when i try to create a job using the Java API it returns:
```
io.kubernetes.client.ApiException: Unauthorized
        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
        at io.kubernetes.client.apis.BatchV1Api.createNamespacedJobWithHttpInfo(BatchV1Api.java:164)
        at io.kubernetes.client.apis.BatchV1Api.createNamespacedJob(BatchV1Api.java:148)
        at de.jlu.bioinfsys.workflowUI.Runner.CommonKubeRunner.startJob(CommonKubeRunner.java:62)
        at de.jlu.bioinfsys.workflowUI.handler.WorkflowUIHandler.startWorkflow(WorkflowUIHandler.java:64)
        at de.jlu.bioinfsys.workflowUI.workflowUIAPI.WorkflowServerAPI$Processor$startWorkflow.getResult(WorkflowServerAPI.java:546)
        at de.jlu.bioinfsys.workflowUI.workflowUIAPI.WorkflowServerAPI$Processor$startWorkflow.getResult(WorkflowServerAPI.java:531)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
I tried this with a custom user and the default admin user with the same result. Both were able to create jobs using kubectl. The config is read correctly when i force parsing by using `KubeConfig.loadDefaultKubeConfig()`. 

This is how a build my client:
```
        ApiClient client = null;
        try {
            client = Config.defaultClient();
        } catch (IOException e) {
            e.printStackTrace();
        }
        Configuration.setDefaultApiClient(client);

        this.batchApiInstance = new BatchV1Api();
```

Cheers and thanks in advance

**Comment by brendandburns** [comment]
Can you print `getResponseBody()` from the `APIException` that gets thrown, and copy the contents into this issue?

The error body should have more details about what is going wrong.

Thanks!

**Comment by OberstHorst** [comment]
Here is the Response body:
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

Cheers

**Comment by brendandburns** [comment]
@OberstHorst Thanks, sadly there's no real information in there after all...

I will try to reproduce this on my local machine and debug from there.

**Comment by OberstHorst** [comment]
@brendandburns I forgot to mention that i am using v1.0.0beta1 from the maven repository. I was able to dig a bot deeper. If you need some debug output, just let me know. I am currently stepping a bit through the call structure, maybe i find something. Cheers and good new year

**Comment by OberstHorst** [comment]
I was able to identify the problem: The BatchV1API class only adds BearerToken authentications to the HTTP header for authentication, but my setup does not allow BearerToken authentication. I fixed it by replacing ```String[] localVarAuthNames = new String[] { "BearerToken" };``` with ```String[] localVarAuthNames = new String[] { "BasicAuth" };```. This is of course not a real fix but only a workaround for me. Maybe this Array should be generated based on what has been found in the config file?

**Comment by brendandburns** [comment]
Thanks for digging into this.

Ultimatley, I think this is because the kubernetes openapi spec doesn't define an `authMethods` section, and thus the auth we get is the defaults.  It's a little weird because basic is present in `ApiClient.java` but not any of the other generated classes. Not really sure why...

@mbohlool should we have a security section in our open api spec?

**Comment by mbohlool** [comment]
At the time that OpenAPI spec generator developed, there were not enough information to add a security section. We can revisit that.

**Comment by l15k4** [comment]
I have the same problem : 
- I created a Role with permissions `container.jobs.*`
- associated that Role with a service account
- used that service-account token this way : 
```
    Config.fromToken(
      "https://104.155.127.136",
      "...",
      false
    )
```
but creating a job returns `401` Unauthorized ... My cluster version is 1.11, kubernetes-client `3.0.0`

**Comment by missourian55** [comment]
403 With this 
```
        ApiClient a3 = new ApiClient();
        a3.setBasePath("https://ablahahahahahahah.sk1.us-west-1.eks.amazonaws.com");
        a3.setSslCaCert(caCert); //read pem file and pass as Inputstream
        a3.setApiKeyPrefix("Bearer "); //one space after 'r' is intentional
        a3.setApiKey(token); //actual token

        Configuration.setDefaultApiClient(a3);


            CoreV1Api api = new CoreV1Api();
            V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
            for (V1Pod item : list.getItems()) {
                System.out.println(item.getMetadata().getName());
            }
```

```
{Audit-Id=[3176b1f8-d3f5-455c-8de6-0ae36fc7b164], Content-Type=[application/json], X-Content-Type-Options=[nosniff], Date=[Wed, 21 Nov 2018 16:02:36 GMT], Content-Length=[222], OkHttp-Sent-Millis=[1542816154273], OkHttp-Received-Millis=[1542816154335]}
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:anonymous\" cannot list pods at the cluster scope","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```
