### ISSUE TITLE
kubernetes-client does not work with IPv6 cluster

### ISSUE THREAD

**Issue by ruvenmil89** [kubernetes-client/java#1636]
Hi all,
I have an IPv6 k8s cluster.
Unfortunately when I tried to run my application I got the error:
{"host":"sps-ig-centralmanagement-0.sps-btel-ig","level":"WARN","log":{"classname":"com.alcatel.tpapps.common.kubernetes.KubernetesAPIUtils:348","message":"Couldn't list statefulsets. Code                                                                                : 0, response body: null","stacktrace":"[io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLPeerUnverifiedException: Hostname "fd01:abcd::1" not verified:

fd01:abcd::1  is short IP of k8s svc 

From google, I found it's an IPv6 issue with okhttp3.x
[https://github.com/kubernetes-client/java/issues/1289](url)

The way to resolve that issue is by updating the okhttp to 4.5 or above.
I tried to find a kubernetes-client version with okhttp 4.5 + but I did not find anything.

Anyone can confirm to me if it's indeed the issue? Does k8s-client support with IPv6 cluster?

Best regards,
Ruven

**Comment by brendandburns** [comment]
We recently updated okhttp to 4.x, when we release the next major version we will include this new dependency.

In the meantime, I believe that you can override the dependency in your pom files.

**Comment by ruvenmil89** [comment]
@brendandburns Thank you, I'm appreciating your answer.
