### ISSUE TITLE
How to get "kubectl descirbe pod" in k8s-client java?

### ISSUE THREAD

**Issue by Bryce1010** [kubernetes-client/java#1650]
How can I get "kubectl descirbe pod" in k8s-client java?
Thanks so much!

**Comment by yue9944882** [comment]
/feature

kubectl describe is not yet supported b/c it's actually made up of a serial of multiple kubernetes api requests, but this is a valid feature request. (we already had similar advanced kubectl commands equalivalence such as `Kubectl#drain()` `Kubectl#rollout()`)
