### ISSUE TITLE
[Query] How to generate configMap with complex/nested data

### ISSUE THREAD

**Issue by weiqingy** [kubernetes-client/java#1651]
One can use `kubectl create configmap foo --from-file=xxx` to generate one configMap with multiple files. How to do this with the K8s Client `V1ConfigMapBuilder `? E.g.
```
        String namespace = "flinknamespace";
	String name = "flinkconfigmap";
	Map<String, String> data = new HashMap<>();
	data.put("key1", "content_Of_ConfigYamlFile1");
	data.put("key2", "content_Of_ConfigYamlFile2");
        data.put("key2", "content_Of_Log4jPropertiesFile");
	V1ConfigMap configMap = (new V1ConfigMapBuilder())
		.withApiVersion("v1")
		.withKind("ConfigMap")
		.withNewMetadata().withName(name).withNamespace(namespace)
		.withOwnerReferences(ownerRef).endMetadata()
		.withData(data)
		.build();
        V1ConfigMap configMap = api.createNamespacedConfigMap(namespace, configMap, null, null, null);
```

We have multiple config Yaml files and Log4j property file. Should we "copy" the file content into a `String`, e.g. `content_Of_ConfigYamlFile1`, `content_Of_ConfigYamlFile2` and `content_Of_Log4jPropertiesFile`? If so, the String will be long and its very easy to make mistake (e.g. indentation matters in yaml file) . Also, the String is kind of static so that we can not modify the value of the fields insides that String later on.
After `configMap` is created, ConfigMap data will be added to a Volume.

Could you please share some hints on this case? Your suggestions'll be helpful. Thank you!

**Comment by yue9944882** [comment]
@weiqingy well if the point is to place those static files somewhere in the java project, i'd recommend having those static files (.yaml, .properties) in the class path, so we can read the content simply by `Files.readAllByte("<classpath-to-file>")`. am i getting the question correctly?

**Comment by weiqingy** [comment]
Thanks for the reply @yue9944882 !

In `content_Of_ConfigYamlFile1` file, it includes some kind of yaml template variables, and we want to fill in some variables dynamically during runtime, e.g. `Name` and `taskSlots` below:
```
  flink-conf.yaml: |+
    jobmanager.rpc.address: {{ Name }}-jobmgr
    taskmanager.numberOfTaskSlots: {{ taskSlots|default(3) }}
```

Yes, we the code below can generate the String via `Files.readAllBytes`:
 new V1ConfigMapBuilder()
        .withMetadata(metaData)
        .addToData(FLINK_CONF_YAML, new String(Files.readAllBytes(Paths.get(ClassLoader.getSystemResource(content_Of_ConfigYamlFile1).toURI()))))
        .addToData(SQL_CLIENT_DEFAULTS_YAML, new String(Files.readAllBytes(Paths.get(ClassLoader.getSystemResource(`content_Of_ConfigYamlFile2`).toURI()))))
        .build();
```
But, still wondering how to overwrite `jobmanager.rpc.address`  and ` taskmanager.numberOfTaskSlots` with the dynamically generated value. Besides String parsing, is there any better way recommended to achieve this?
