### ISSUE TITLE
How to gather metrics from kubelet/cadvisor

### ISSUE THREAD

**Issue by lukonjun** [kubernetes-client/java#1657]
Hi, I am Interested in cadvisor metrics like container_network_receive_bytes_total and container_fs_writes_bytes_total. 

I found out, that these metrics are exposed via the API http://localhost:8001/api/v1/nodes/worker01/proxy/metrics/cadvisor ...
`container_network_receive_bytes_total{container="",id="/kubepods/besteffort/pod6524d65b-7cb7-437f-a977-9b76d4f752e1/3ea7270ec00f68d234c8f89b077c6a73716098ff2ffdfbc0f8adadaaf9abae84",image="docker.io/rancher/pause@sha256:d22591b61e9c2b52aecbf07106d5db313c4f178e404d660b32517b18fcbf0144",interface="eth0",name="3ea7270ec00f68d234c8f89b077c6a73716098ff2ffdfbc0f8adadaaf9abae84",namespace="anomaly-detection-stack",pod="metrics-collector-chart-metrics-collector-6c75d758f9-6ggbd"} 4.081514e+06 1618820014138`
... however I did not find a Java Class like **Nodemetrics** or **Podmetrics** that displays any of the metrics. 

Is there any Class I am not aware of, or is there no way around just parsing the metrics from the endpoint? 
Thanks in advance

**Comment by brendandburns** [comment]
There's no client for that in this library, though those look like Prometheus metrics, so you may investigate the Prometheus Java client to see if there is an API for parsing metrics there.

Closing this since we have no plans to implement this.

**Comment by lukonjun** [comment]
Ok, makes sense, is there a way to achieve something like with the java client @brendandburns ?
`kubectl get --raw /api/v1/nodes/worker01/proxy/metrics/cadvisor`
Im trying to avoid passing token and certificate to a http client, but could not find something like this in the Documentation.
