### ISSUE TITLE
DeleteResourceQuota is returning ResourceQuota instead of V1Status

### ISSUE THREAD

**Issue by vivekjhauipath** [kubernetes-client/java#1663]
**Describe the bug**
Most delete apis including DeleteResourceQuota( till release-9) used to return V1Status Object. Why is this changed to return V1ResourceQuota object in release-10

** Client Version **
e.g. `10.0.0`

** Java Version **
e.g. Java 8

**To Reproduce**
Just check coreV1Api.java class deleteNamespacedResourceQuota method

**Expected behavior**
It should return V1Status

**Comment by yue9944882** [comment]
@vivekjhauipath actually either returning `V1ResourceQuota` or `V1Status` is not accurate. all resource deletion in kubernetes will return the before-deletion state of the deleting resource or a simple status object depending on whether it's a graceful deletion or not (usually we will run into graceful deletion if the deleting resource is attached finalizer). 

besides i think returning `V1ResourceQuota` would be more descriptive. b/c in the happy case, the content of returned `V1Status` is constant and on the other hand in the failing case we're supposed to capture an `ApiException` so no V1Status will be returned. or @vivekjhauipath can you elaborate why you're expecting a `V1Status` in ur use case?

**Comment by vivekjhauipath** [comment]
> @vivekjhauipath actually either returning `V1ResourceQuota` or `V1Status` is not accurate. all resource deletion in kubernetes will return the before-deletion state of the deleting resource or a simple status object depending on whether it's a graceful deletion or not (usually we will run into graceful deletion if the deleting resource is attached finalizer).
> 
> besides i think returning `V1ResourceQuota` would be more descriptive. b/c in the happy case, the content of returned `V1Status` is constant and on the other hand in the failing case we're supposed to capture an `ApiException` so no V1Status will be returned. or @vivekjhauipath can you elaborate why you're expecting a `V1Status` in ur use case?

I wanted it to remain consistent with previous versions. Also, many other APIs return status for deletion, e.g. secret/service/node it helps in making a generic crud layer.
Has something changes in k8s implementation itself which necessitated this change?

**Comment by yue9944882** [comment]
@vivekjhauipath there's already a generic layer. you can either use [GenericKubernetesApi](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/GenericClientExample.java) or [Kubectl Utility](https://github.com/kubernetes-client/java/blob/master/docs/kubectl-equivalence-in-java.md)

**Comment by yue9944882** [comment]
> Has something changes in k8s implementation itself which necessitated this change?

yes, it's the openapi document changed. the api you are using is generated from the spec.

**Comment by vivekjhauipath** [comment]
> @vivekjhauipath there's already a generic layer. you can either use [GenericKubernetesApi](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/GenericClientExample.java) or [Kubectl Utility](https://github.com/kubernetes-client/java/blob/master/docs/kubectl-equivalence-in-java.md)

Thanks, will check if switching to those would be easy for us

**Comment by vivekjhauipath** [comment]
> > Has something changes in k8s implementation itself which necessitated this change?
> 
> yes, it's the openapi document changed. the api you are using is generated from the spec.

If it's a change in k8s side then maybe I should check there for the rationale. Thanks.
You can probably close it.
