### ISSUE TITLE
Authentication without reading config from kubeconfig file 

### ISSUE THREAD

**Issue by inge4pres** [kubernetes-client/java#167]
Hi,

I read along the documentation and in the code and I could not find a way to instantiate an `ApiClient` passing the base64 encoded CA, key and client certificate.
Is it possible? 
Currently using 1.0.0-beta1.
Thank you

**Comment by brendandburns** [comment]
Easiest way is to directly instantiate the APIClient, see:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Config.java#L57

**Comment by brendandburns** [comment]
Opened #168 that captures this, closing this issue in favor of that one.
