### ISSUE TITLE
Create CustomResourceDefinition object loaded from YAML

### ISSUE THREAD

**Issue by duchungvu** [kubernetes-client/java#1670]
I'm trying to create this [sparkApplications from spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml) on my GKE cluster using this client.

Here's what I've been trying so far:
1. [Generate Java class models](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md) and it created about ~100 new classes (`V1beta2SparkApplication`, `V1beta2SparkApplicationList`, `V1beta2SparkApplicationSpec`, `V1beta2SparkApplicationSpecAwsElasticBlockStore`, ...)
2. Create an instance of that CRD using `Yaml.loadAs()` then use `createNamespacedCustomObject` to create the CRD
```java
V1beta2SparkApplication sparkApplication = Yaml.loadAs(
        new File(sparkoperator.k8s.io_sparkapplications.yaml),
        V1beta2SparkApplication.class);
CustomObjectsApi customObjectsApi = new CustomObjectsApi(apiClient);
customObjectsApi.createNamespacedCustomObject(
        group, 
        version, 
        namespace, 
        plural, 
        sparkApplication,
        null, null, null);
```

- I wonder if there are any way other than generating ~100 classes?
- Would `Yaml.loadAs()` auto-populate `V1beta2SparkApplicationList` and `V1beta2SparkApplicationSpec` when I load `V1beta2SparkApplication`
- I know I can just use `helm` to install the chart on my cluster, but I'm trying to run a Spark job (create the cluster -> install spark-operator -> submit Spark job) using this client without dependent on `helm`. Is there a possible way to do this?

Thanks!

**Comment by yue9944882** [comment]
> I wonder if there are any way other than generating ~100 classes?

since 12.0.0, we can use [DynamicKubernetesApi](https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesApi.java) to manipulate the custom resources w/o generating classes.

> Would Yaml.loadAs() auto-populate V1beta2SparkApplicationList and V1beta2SparkApplicationSpec when I load V1beta2SparkApplication

yes if the class `V1beta2SparkApplication` is registered via `ModelMapper#addModelMap` e.g.

```java
ModelMapper.addModelMap("sparkoperator.k8s.io", "v1beta2",  "SparkApplication", "sparkapplications", V1beta2SparkApplication.class);
```

> I know I can just use helm to install the chart on my cluster, but I'm trying to run a Spark job (create the cluster -> install spark-operator -> submit Spark job) using this client without dependent on helm. Is there a possible way to do this?

we had a few equivalence implementation of kubectl commands which can help you to do the similar things as helm does i suppose.

btw, you're free to contribute your generated classes under [client-java-contrib](https://github.com/kubernetes-client/java/tree/master/client-java-contrib) modules. we already have generated classes for prometheus and helm operator

**Comment by duchungvu** [comment]
@yue9944882 Thank you for following up!

Would you mind provide an example how can I create the CRD with YAML using DynamicKubernetesApi? I'm don't quite understand the example how does it work. How does the API get the CRD config from?

**Comment by yue9944882** [comment]
@duchungvu it's a recently added feature. and i added more utilities for loading Yaml content to dynamic object: https://github.com/kubernetes-client/java/pull/1675. basically you will need to convert yaml content to json so that DynamicKubernetesApi can send it to the server. does it help?

**Comment by duchungvu** [comment]
@yue9944882 Thanks for your follow up. However, when I tried `DynamicKubernetesApi`, I got this exception, do you have any idea what caused this?
```
okhttp3.internal.http2.ConnectionShutdownException[io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:793),
io.kubernetes.client.util.generic.GenericKubernetesApi.create(GenericKubernetesApi.java:423),
io.kubernetes.client.util.generic.GenericKubernetesApi.create(GenericKubernetesApi.java:401),
io.kubernetes.client.util.generic.GenericKubernetesApi.create(GenericKubernetesApi.java:202),
```
The code I used was:

```Java
DynamicKubernetesObject dynamicKubernetesObject = Dynamics.newFromJson(json);
dynamicKubernetesApi.create(dynamicKubernetesObject);
```

On the other hand, I also tried to generate a `V1beta2SparkApplication` then used `CustomObjectsApi` to create the CRD, but I got this error, any idea why?
```
Not Found[io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:971),
io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883),
io.kubernetes.client.openapi.apis.CustomObjectsApi.createNamespacedCustomObjectWithHttpInfo(CustomObjectsApi.java:535),
io.kubernetes.client.openapi.apis.CustomObjectsApi.createNamespacedCustomObject(CustomObjectsApi.java:490),
```
What I ran: 
```Java
V1beta2SparkApplication sparkApplication = Yaml.loadAs(yaml, V1beta2SparkApplication.class);
customObjectsApi.createNamespacedCustomObject(
    "sparkoperator.k8s.io",
    "v1beta2",
    "default",
    "sparkapplications",
    sparkApplication,
    null,
    null,
    null);
```

**Comment by SachinHg** [comment]
@duchungvu did whatever you mention in the last comment work for you?
