### ISSUE TITLE
How to get event name for readNamespacedEvent?

### ISSUE THREAD

**Issue by Bryce1010** [kubernetes-client/java#1671]
It's not a bug, but asking for help! 
There is a event name in API readNamespacedEvent,  how can I get event name ?
Thanks!

**Comment by yue9944882** [comment]
@Bryce1010 as far as i know, the name of the events is auto-generated everywhere, so it's more appropriate to use the list api combining w/ field selectors to find your events.

**Comment by brendandburns** [comment]
Closing this issue because I think the question is answered.

**Comment by Bryce1010** [comment]
Thanks! 
I solved it  finally!
Here is my solution:
```java
String fieldSelector = String.format("involvedObject.kind=Pod,involvedObject.name=%s",
                pod.getMetadata().getName());
V1EventList v1EventList = coreV1Api.listNamespacedEvent(namespace, "no_pretty", null, null,
                fieldSelector, null, null, null, null, null);
```
