### ISSUE TITLE
[Query] Periodic monitoring of status of a custom resource after creation via kubernetes operator

### ISSUE THREAD

**Issue by githubUser-k8** [kubernetes-client/java#1679]
I plan to create a kubernetes operator using kubernetes official java client. I want the operator to periodically monitor health of the custom resources after it creates them and take actions if needed (report back status of the custom resource, for example). What's the best way to achieve this?

-  I was planning to handle this in the reconciler. It looks like "reconcile" method of a reconciler gets called only if a custom resource changes (added/deleted/updated). However, in my case I want the operator to keep checking status of custom resources after they are created/updated (i.e. even if there are no changes in the custom resource). So I am not sure if I can configure to have "reconcile" called periodically even without any changes to custom resources and handle checking health there.
- Is returning "requeue = true and requeAfter = duration I want for periodic monitoring" a good idea? That way "reconcile" method will get called periodically and I can monitor status there. 

Thanks for your help!

**Comment by brendandburns** [comment]
The `Cache` class:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/informer/cache/Cache.java#L178

should work for this.

You can just use a for loop to repeatedly iterate at the right interval.

**Comment by githubUser-k8** [comment]
Thanks @brendandburns for the response! Are you suggesting that we don't rely on the automatic "reconcile" invocation via controller and reconciler, but we periodically loop through all the objects in the cache ourselves? Is that a recommended pattern? Also, any downsides of that?

**Comment by brendandburns** [comment]
I would suggest that you do both.

e.g. The reconcile to get low-latency notifications of changes, the cache to do the polling that you want to do.

In general, we would suggest that polling is not necessary, but the specific details of your use-case may require that.
