### ISSUE TITLE
Generate Api and Model classes from CRD results in missing IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2 when run against kind 1.20

### ISSUE THREAD

**Issue by asavov** [kubernetes-client/java#1710]
**Describe the bug**

Using `java-crd-cmd.sh` script to generate **Models** and **Apis** from single CRD results in:

1. referencing two **missing** classes by the `InfraAlexComV1Api`.
```
import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2;
import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1StatusV2;
```
2. using `IoK8sApimachineryPkgApisMetaV1ObjectMetaV2` (which is **missing**) instead of `io.kubernetes.client.openapi.models.V1ObjectMeta`
 
3. **not** `implements KubernetesObject` by root CR (V1CloudAccount) object.
 
Here's the generate script:
```
generate() {
  git clone https://github.com/kubernetes-client/gen ${OPERATOR_PROJECT_TEMP_DIR}/models-generator || true

  cd $OPERATOR_PROJECT_TEMP_DIR/models-generator/openapi

  bash java-crd-cmd.sh \
   -n com.alex.infra \
   -p com.alex.infra \
   -o $OPERATOR_PROJECT_TEMP_DIR/models-generator-output \
   -g true < $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger
}
```

The full log from generation is : [gen-models-output.txt](https://github.com/kubernetes-client/java/files/6472667/gen-models-output.txt)

**Client Version**
12.0

**Kubernetes Version**
kind k8s from image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
**`^^^ That's the problematic part.`**

**Java Version**
java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+16-SA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+16-SA (build 11.0.7+10-LTS, mixed mode)

**To Reproduce**

This script is executed prior above `generate` script.

```
applyCrd() {
  echo "Apply CRDs: START"

  kubectl apply -f $CRD_1

  kubectl get --raw="/openapi/v2" > $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger

  while ! (grep -Fq '"CloudAccount"' $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger); do
    echo "Waiting for CloudAccount CRD to be applied..."
    sleep 1
    kubectl get --raw="/openapi/v2" > $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger
  done

  echo "Apply CRDs: END"
}
```

**Server (please complete the following information):**
 - OS: Mac
 - Environment: Local dev env

**Additional context**

**This SAME script used to work**. And the Api code generated referred:

```
import io.kubernetes.client.openapi.models.V1DeleteOptions;
import io.kubernetes.client.openapi.models.V1Status;
```

Seems that some recent change has introduced/replaced `V1DeleteOptions` and `V1Status` with

```
import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2;
import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1StatusV2;
```

**Comment by asavov** [comment]
Any idea what might be causing this or any workaround to apply?

**Comment by asavov** [comment]
> Any idea what might be causing this or any workaround to apply?

Seems that using `kindest/node:v1.19.7` (as opposite to `kindest/node:v1.20.2`) workaround the issue.

Still the issue is **Why** with 1.20 k8s version it's not working.

Is it possible to be some issue with [def remove_model_prefixes(spec, crd_mode=False): ](https://github.com/kubernetes-client/gen/blob/master/openapi/preprocess_spec.py#L347) and then conflict between DeleteOptions_V2 (which is available on 1.20 kind) and v1.DeleteOptions?

**Comment by brendandburns** [comment]
The Swagger definitions for the APIs are downloaded from the Kubernetes API server. I suspect that the API object definitions changed between 1.19 and 1.20

**Comment by yue9944882** [comment]
@asavov it seems that you're doing the code-generation in a deprecated approach. i'd suggest trying the latest doc according to https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

**Comment by asavov** [comment]
> The Swagger definitions for the APIs are downloaded from the Kubernetes API server. I suspect that the API object definitions changed between 1.19 and 1.20

Yes. with 1.20 it does **not** work. While with 1.19 and 1.18 it do work.

**Comment by asavov** [comment]
> @asavov it seems that you're doing the code-generation in a deprecated approach. i'd suggest trying the latest doc according to https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

I tried with 

```
 docker run \
  --rm \
  -v "$CRD_1":"$CRD_1" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":"$(pwd)" \
  -ti \
  --network host \
  ghcr.io/yue9944882/crd-model-gen:v1.0.3 \
  /generate.sh \
  -u $CRD_1 \
  -n com.alex.infra \
  -p com.alex.infra \
  -o "$(pwd)"
```
and it worked. And this is cause it uses internally `kind 1.18`

```
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2)
```

Still when run with 1.20 it fails.

I will change issue Name/Title.

**Comment by asavov** [comment]
Any feedback on this?

**Comment by wqq578** [comment]
Report error every time

**Comment by wqq578** [comment]
> Report error every time


Existing cluster generation should be used

**Comment by wqq578** [comment]
> **Describe the bug**
> 
> Using `java-crd-cmd.sh` script to generate **Models** and **Apis** from single CRD results in:
> 
> 1. referencing two **missing** classes by the `InfraAlexComV1Api`.
> 
> ```
> import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2;
> import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1StatusV2;
> ```
> 
> 1. using `IoK8sApimachineryPkgApisMetaV1ObjectMetaV2` (which is **missing**) instead of `io.kubernetes.client.openapi.models.V1ObjectMeta`
> 2. **not** `implements KubernetesObject` by root CR (V1CloudAccount) object.
> 
> Here's the generate script:
> 
> ```
> generate() {
>   git clone https://github.com/kubernetes-client/gen ${OPERATOR_PROJECT_TEMP_DIR}/models-generator || true
> 
>   cd $OPERATOR_PROJECT_TEMP_DIR/models-generator/openapi
> 
>   bash java-crd-cmd.sh \
>    -n com.alex.infra \
>    -p com.alex.infra \
>    -o $OPERATOR_PROJECT_TEMP_DIR/models-generator-output \
>    -g true < $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger
> }
> ```
> 
> The full log from generation is : [gen-models-output.txt](https://github.com/kubernetes-client/java/files/6472667/gen-models-output.txt)
> 
> **Client Version**
> 12.0
> 
> **Kubernetes Version**
> kind k8s from image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
> **`^^^ That's the problematic part.`**
> 
> **Java Version**
> java -version
> openjdk version "11.0.7" 2020-04-14 LTS
> OpenJDK Runtime Environment Zulu11.39+16-SA (build 11.0.7+10-LTS)
> OpenJDK 64-Bit Server VM Zulu11.39+16-SA (build 11.0.7+10-LTS, mixed mode)
> 
> **To Reproduce**
> 
> This script is executed prior above `generate` script.
> 
> ```
> applyCrd() {
>   echo "Apply CRDs: START"
> 
>   kubectl apply -f $CRD_1
> 
>   kubectl get --raw="/openapi/v2" > $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger
> 
>   while ! (grep -Fq '"CloudAccount"' $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger); do
>     echo "Waiting for CloudAccount CRD to be applied..."
>     sleep 1
>     kubectl get --raw="/openapi/v2" > $OPERATOR_PROJECT_TEMP_DIR/models-generator-swagger
>   done
> 
>   echo "Apply CRDs: END"
> }
> ```
> 
> **Server (please complete the following information):**
> 
> * OS: Mac
> * Environment: Local dev env
> 
> **Additional context**
> 
> **This SAME script used to work**. And the Api code generated referred:
> 
> ```
> import io.kubernetes.client.openapi.models.V1DeleteOptions;
> import io.kubernetes.client.openapi.models.V1Status;
> ```
> 
> Seems that some recent change has introduced/replaced `V1DeleteOptions` and `V1Status` with
> 
> ```
> import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2;
> import com.alex.infra.models.IoK8sApimachineryPkgApisMetaV1StatusV2;
> ```

This image can't run. The parameters should be wrong. Do you have any details?

**Comment by yue9944882** [comment]
hi @asavov i wasnt able to reproduce this after bumping the built-in kind version to 0.10.0 which provisions 1.20 k8s cluster internally. can you elaborate ur case why u need a newer k8s cluster to do the code-gen. i can publish a new one w/ the kind binary bumped if that works for u.

**Comment by asavov** [comment]
@yue9944882 Excuse my delayed response. Was on vacation.

On a brand new and fresh Mac (configured with latest bins)

```
>kind version
kind v0.10.0 go1.15.7 darwin/amd64
```

```
>kind create cluster (with config.yaml without image in order to use default)
Creating cluster "kind" ...
⢄⡱ Ensuring node image (kindest/node:v1.20.2) 🖼 
```

those 2 are still missing/invalid
```
import com.vmware.ccs.infra.models.IoK8sApimachineryPkgApisMetaV1DeleteOptionsV2;
import com.vmware.ccs.infra.models.IoK8sApimachineryPkgApisMetaV1StatusV2;
```

> can you elaborate ur case why u need a newer k8s cluster to do the code-gen.
Working on a project using latest kind and kindest/node:v1.20.2, and needing k8s-models auto-generation.

How about to set up zoom?

Let me know if I can provide more details.

**Comment by stefanbethke** [comment]
I'm running in to this very issue, on macOS, Docker Desktop:
```
$ kubectl version    
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cheny1994** [comment]
This issue also occurs when using github action "CRD Java Model Generate"
