### ISSUE TITLE
Tag the node and report an error?

### ISSUE THREAD

**Issue by beyondyinjl2** [kubernetes-client/java#1723]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1Node] with root cause

io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1Node
	at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:256) ~[client-java-extended-12.0.0.jar:na]
	at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:297) ~[client-java-extended-12.0.0.jar:na]
	at io.kubernetes.client.extended.kubectl.KubectlLabel.execute(KubectlLabel.java:54) ~[client-java-extended-12.0.0.jar:na]

[error pic](https://github.com/beyondyinjl2/bug-images/blob/main/k8s/1621589374067.jpg)

code:

CoreV1Api coreV1Api = new CoreV1Api();
        V1Node v1Node = coreV1Api.readNode("edge-node-3", null, null, null);
        System.out.println(v1Node.getMetadata().getName());
        Kubectl.label(V1Node.class)
                .apiClient(client)
                .namespace("default")
                .skipDiscovery()
                 .name("edge-node-3")
                .addLabel("k1", "v1")
                .execute();

        return v1Node;

** Kubernetes Version **
e.g. `v1.20.0`

** Java Version **
e.g. Java 8

**Comment by beyondyinjl2** [comment]
ModelMapper.addModelMap("", "v1", "Node", "nodes", false, V1Node.class);
        client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(br)).build();

 Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.kubernetes.client.extended.kubectl.exception.KubectlException: io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: v1
    code: 404
    details: class V1StatusDetails {
        causes: null
        group: null
        kind: null
        name: null
        retryAfterSeconds: null
        uid: null
    }

**Comment by beyondyinjl2** [comment]
kubectl get nodes
NAME           STATUS     ROLES                  AGE    VERSION
edge-node-1    Ready      agent,edge             121d   v1.19.3-kubeedge-v1.5.0
edge-node-2    Ready      agent,edge             119d   v1.19.3-kubeedge-v1.5.0
edge-node-3    Ready      agent,edge             74d    v1.19.3-kubeedge-v1.6.0
edge-node-4    NotReady   agent,edge             11d    v1.19.3-kubeedge-v1.5.0

kubectl api-versions        
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1

**Comment by beyondyinjl2** [comment]
https://192.168.3.100:6443/apis/apps/v1/namespaces/default/nodes/edge-node-3

**Comment by beyondyinjl2** [comment]
https://192.168.3.100:6443/apis/apps/v1/namespaces/default/nodes/edge-node-3

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "nodes.apps \"edge-node-3\" is forbidden: User \"system:anonymous\" cannot get resource \"nodes\" in API group \"apps\" in the namespace \"default\"",
  "reason": "Forbidden",
  "details": {
    "name": "edge-node-3",
    "group": "apps",
    "kind": "nodes"
  },
  "code": 403
}

**Comment by brendandburns** [comment]
Please file descriptive issues following the [issue-template](https://github.com/kubernetes-client/java/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

Pasting stack traces and JSON blobs without context is not an actionable issue. Closing.
