### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [kubernetes-client/java#173]
Hello.
My research group has a cloud where we set a kubernetes cluster and it was working very well.
But now, when I try to request some data using CLI, I am getting erros.

_Unable to connect to the server: net/http: TLS handshake timeout_

Is there a way to walk around it Using CLI ou even a command in this java-client?

**Comment by kondapally1989** [comment]
@ViniciusDeAndrade 
for me this  arrised because the master ran out of memory, i have removed some files in tmp and it worked again
https://github.com/kubernetes/kubernetes/issues/13382#issuecomment-151869047
https://github.com/Azure/AKS/issues/14

this issue is not related to K8 java client

**Comment by ViniciusDeAndrade** [comment]
I got the problem. The server was not able to deal with the app.
