### ISSUE TITLE
crd yaml generate java class

### ISSUE THREAD

**Issue by chenwenjun-github** [kubernetes-client/java#1731]
**Describe the bug**
Describe the bug
I follow https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md to generate katib CRD model: https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/components/crd/experiment.yaml, then I get the following error:
![image](https://user-images.githubusercontent.com/46237364/119502154-34019980-bd9c-11eb-8077-588f17419c4a.png)
so I add .spec.preserveUnknownFields=false in the YAML 
and the i get the following error:
![image](https://user-images.githubusercontent.com/46237364/119502638-b8541c80-bd9c-11eb-8cb8-c65d3bddd128.png)

the reason whether is there have no openAPIV3Schema in my crd.yaml

**Comment by yue9944882** [comment]
@chenwenjun-github it seems that you didnt write any content under the openapi schema? once enabling the pruning, all the fields not defined in the schema will be pruned before persisted.
