### ISSUE TITLE
Document or adopt standard formatting for Java code

### ISSUE THREAD

**Issue by lewisheadden** [kubernetes-client/java#174]
I've noticed a few different styles of formatted code in the repository for non-generated code. Is there a standard formatter file used for Java code within the Kubernetes community?

If there is a default, can we add it to the documentation for this repo? If not, can we use something like [Google Java Format](https://github.com/google/google-java-format)?

**Comment by brendandburns** [comment]
I'm fine with Google Java Format, that's more or less what I write in anyway...
