### ISSUE TITLE
io.kubernetes.client.openapi.ApiException: Logs request failed: 400

### ISSUE THREAD

**Issue by habibali95** [kubernetes-client/java#1750]
**Describe the bug**
Log request failed when trying to use the method podLogs.streamNamespacedPodLog
** Client Version **
`12.0.0`

** Kubernetes Version **
1.19.3`

** Java Version **
Java 8

**To Reproduce**
use podLogs.streamNamespacedPodLog

**Expected behavior**
error 400
**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: linux
 - Environment container
 - Cloud aws

**Additional context**
PS : .getResponseBody is returning null

**Comment by brendandburns** [comment]
Closing due to lack of response. If you need further assistance please use the `/reopen` command or file a new issue.

**Comment by habibali95** [comment]
/repoen 
hello @brendandburns ,
Im sorry for replying late.
We don't use any HTTP proxy, 
This is how we call the API 			
	
inputStream = podLogs.streamNamespacedPodLog(org, v1Pod.getMetadata().getName(), null, sinceSecond,
						tailLine, false);
org is an existing namespace, sinceSecond is mostly= 2 and tailLine is mostly null
