### ISSUE TITLE
Our builds are flaky.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1752]
Numerous builds are failing with this error:

```
Error:  COMPILATION ERROR : 
Error:  cannot access jdk.internal.org.objectweb.asm.MethodVisitor
  class file for jdk.internal.org.objectweb.asm.MethodVisitor not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for jdk.internal.org.objectweb.asm.MethodVisitor not found
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project client-java-api: Compilation failure
Error:  cannot access jdk.internal.org.objectweb.asm.MethodVisitor
Error:    class file for jdk.internal.org.objectweb.asm.MethodVisitor not found
Error:    Consult the following stack trace for details.
Error:    com.sun.tools.javac.code.Symbol$CompletionFailure: class file for jdk.internal.org.objectweb.asm.MethodVisitor not found
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :client-java-api
Error: Process completed with exit code 1.
```

I can't reproduce it locally, and it seems to be flaky (e.g. some builds pass)

I had thought that it was related to maven caching bad/broken configs but I'm less certain now. It's possible that it's some sort of class-loading clash.

There's not much information online for this error and there's not much information in the error itself.

I'm wondering if it is related to the `sundr` code generation phase, we should perhaps break that out into its own phase for clarity.

cc @iocanel if he has any time/thoughts of if `sundr` could be causing this.

**Comment by iocanel** [comment]
@brendanburns: I've recently encountered an issue in `sundrio` which was similar to this one. The offending class was different but was part of `jdk.internal` which eventually leads to add it to the list of packages we ignore when we traverse the object graph in sundrio. 

This means it worths trying to bump to `0.40.1` which is the latest version of sundrio.

**Comment by brendandburns** [comment]
@iocanel thanks for the response! Unfortunately, we're already on `0.40.1` any ideas about what we should look for?

Is it possible that it is caused by the `exclusion` section in our `pom.xml`

```
      <dependency>
        <groupId>io.sundr</groupId>
        <artifactId>builder-annotations</artifactId>
        <version>${sundrio.version}</version>
        <scope>compile</scope>
        <exclusions>
          <exclusion>
            <artifactId>tools</artifactId>
            <groupId>com.sun</groupId>
          </exclusion>
        </exclusions>
      </dependency>
```

**Comment by iocanel** [comment]
> I'm wondering if it is related to the `sundr` code generation phase, we should perhaps break that out into its own phase for clarity.

What we've recently tried in sundrio itself is to generate the code in its own module and optionally check the generated code in scm. This saves us the effort of generating again and again stuff that are not that volatile. It offers the benefit of having a historical view of what changes. Last but not least its easy to control using profiles.

**Comment by brendandburns** [comment]
Ah, I think I will try that approach also, we'll make it part of the code generation part (which we do anyway) rather than the build.

Thanks for the advice!

**Comment by brendandburns** [comment]
This appears to have been fixed by extracting the fluent generation. Closing.
