### ISSUE TITLE
Expected date-time format

### ISSUE THREAD

**Issue by gauravrkulkarni** [kubernetes-client/java#1754]
I have defined a custom resource with a status field "lastTransitionTime". I have defined it in date-time format. Relevant portion from CRD:
```
status:
  lastTransitionTime:
    type: string
    format: date-time
```

I used instructions [here](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md) to generate models. Looks like lastTransitionTime gets converted into joda DateTime. 
I have an operator that updates this field. When the operator tries to update the custom resource after setting this field, I see an error `.lastTransitionTime in body must be of type date-time: \"` 

I looked at the client code, and looks like we are expected to use java OffsetDateTime. I tried to use OffsetDateTime, but it looks like the operator goes in constant reconciliation loop without any errors or exceptions (which doesn't happen if I don't update this field at all. I am able to update other fields in the status and they are not in date-time format).

1.  Is there a way to debug this further? Is there any other format that's expected? 
2. I am right now generating models using instructions [here](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md), which generates joda DateTime. Is there a way to create models that use OffsetDateTime instead (assuming that's the right format)?  I have manually changed to OffsetDateTime for now. 
 
Client Version: 12.0.0
Kubernetes Version: 1.19.11
Java Version:Java 8
Cloud: Azure (AKS) 

Thanks in advance.

**Comment by brendandburns** [comment]
We probably need to regenerate that docker image for building CRDs.

The change that introduced this for the main repo is here:

https://github.com/kubernetes-client/gen/pull/177/files

I think we need an updated pom.xml in that Dockerfile.

You could probably make that change manually yourself by building one more layer on top of the main generator Docker image.

cc @yue9944882

**Comment by yue9944882** [comment]
> We probably need to regenerate that docker image for building CRDs.

@brendandburns yes, i will re-gen an image adopting OffsetDateTime

> When the operator tries to update the custom resource after setting this field, I see an error .lastTransitionTime in body must be of type date-time: \"

@gauravrkulkarni i think the error is caused by server-side rejection, can you elaborate how you're serializing the datetime object? which codec are you currently using? or you can also pasted us the failing request body so that we can help you.

**Comment by karunasagark** [comment]
@yue9944882 checking to see if you have the re-gen the image with OffsetDateTime? If yes, can you please let me know where to find it?

**Comment by yue9944882** [comment]
i just bumped a new version of the crd model generator, plz let us know if it doesn't solve the issue.

> docker.pkg.github.com/kubernetes-client/java/crd-model-gen:v1.0.4
> ghcr.io/yue9944882/crd-model-gen:v1.0.4

**Comment by tony-clarke-amdocs** [comment]
Thanks @yue9944882, that solved it!
