### ISSUE TITLE
create kubernetes java client controller to watch pods

### ISSUE THREAD

**Issue by ssolanki34** [kubernetes-client/java#1756]
I want to use the kubernetes java client to create a controller (using shared informer) to watch for create, update, and delete events for pods in a specific namespace. I've found some examples that watch deployments and list nodes...but cannot find examples for pods. are there any examples for this specific use case that are available?

**Comment by brendandburns** [comment]
I assume you found the informer example here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/InformerExample.java

That should be pretty easy to adapt to watch Pods instead.
