### ISSUE TITLE
java.lang.NoSuchMethodError when using SharedInformerFactory.sharedIndexInformerFor method

### ISSUE THREAD

**Issue by ssolanki34** [kubernetes-client/java#1757]
`SharedInformerFactory informerFactory = new SharedInformerFactory(client);`
`GenericKubernetesApi<V1Pod, V1PodList> genericKubernetesApi = new GenericKubernetesApi<>(V1Pod.class, V1PodList.class, "", "v1", "pods", client);` 
`// Create the index informer`
`SharedInformer<V1Pod> informer = informerFactory.sharedIndexInformerFor(genericKubernetesApi, V1Pod.class, 0, "default");`

i am trying this code above to create a controller that watches pods in a specific namespace, and i'm using these dependencies in my maven file:
        `<dependency>`
`            <groupId>io.kubernetes</groupId>`
            `<artifactId>client-java</artifactId>`
`            <version>11.0.0</version>`
`        </dependency>`
`        <dependency>`
`            <groupId>io.kubernetes</groupId>`
`            <artifactId>client-java-extended</artifactId>`
`            <version>11.0.0</version>`
`        </dependency>`

when i run this in my k8s cluster, i get an exception: 
`Exception in thread "main" java.lang.NoSuchMethodError: io.kubernetes.client.informer.SharedInformerFactory.sharedIndexInformerFor(Lio/kubernetes/client/util/generic/GenericKubernetesApi;Ljava/lang/Class;JLjava/lang/String;)Lio/kubernetes/client/informer/SharedIndexInformer;`

i have to use the version 11.0.0 or above because in 10.0.0, there is no method `sharedIndexInformerFor` that allows me to write the namespace. 

my k8s cluster version:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

how can i fix this ?

**Comment by brendandburns** [comment]
You have some sort of classpath problem. I suspect that you have built your library against one version of the library, but you are running against another, but I'm not sure.

I think this is a basic Java classpath issue, rather than anything in this library. Therefore I'm closing this issue as out of scope.

If you discover a problem with this client please use `/reopen` to reopen this issue, or open a new one.
