### ISSUE TITLE
How to convert CPU and memory units

### ISSUE THREAD

**Issue by beyondyinjl2** [kubernetes-client/java#1759]
The CPU and memory obtained by Metrics api, the unit is: Quantity(number=0.001721699, format=DECIMAL_SI)
Quantity{number=4014080, format=BINARY_SI}
How to convert to for example: CPU: 377m MEMORY: 136Mi, the unit printed by kubectl top nodes

  kubectl top nodes
NAME CPU(cores) CPU% MEMORY(bytes) MEMORY%
adam3600 377m 37% 136Mi 96%
edge-node-1 302m 7% 2094Mi 26%
rabbitmq3 3050m 38% 12263Mi 38%

**Comment by brendandburns** [comment]
CPU is in cores (1.0 == 1 core)
Memory is in bytes (1 = 1 byte)
