### ISSUE TITLE
Is there a way to access the aws eks using this api with iam roles, lambda

### ISSUE THREAD

**Issue by pavankumar1986** [kubernetes-client/java#1760]
I want to have a lambda function on aws which connects to eks cluster using this api and does some modifications to kubernetes object.
Looked at the basic example picking the userhome/.kube/config for kubernetes details.

Is there a way where we can have it take kubernetes authentication via iam and do the required kubernetes object modifications.

**Comment by djnautiyal** [comment]
@pavankumar1986 you found anything useful?
