### ISSUE TITLE
How to wait for deleteCollectionNamespacedPod to complete before deleting namespace?

### ISSUE THREAD

**Issue by ahmedsmhs** [kubernetes-client/java#1770]
For namespace cleanup, I am trying to delete all resources before deleting the namespace in the code. However, the deletion of pods takes time and the NS deletion fails due to active pods in the NS. How may I make this call wait for the deletion to complete / or force delete the existing pods before proceeding with deletion?

I am already using graceperiod as zero.

**Comment by brendandburns** [comment]
I believe that setting `propogationPolicy` in `V1DeleteOptions` to `"Foreground"` should do this correctly.

**Comment by ahmedsmhs** [comment]
Thanks @brendandburns , but I am still facing the same exception .
`Error occurred while getting namespaceCONFLICT occurred while deleting namespace xyz`

**Comment by brendandburns** [comment]
Without seeing your code it is hard to know, but it appears that you are simultaneously GET and DELETE on the same namespace?

If you print `ApiException.getResponseBody()` you should get more details.

**Comment by ahmedsmhs** [comment]
code for pod deletion:

`private CompletableFuture<Void> cleanUpNamespacedPods(CoreV1Api coreV1Api, String namespace, String id1, String id2) {
    return CompletableFuture.runAsync(() -> {
      try {

        final V1DeleteOptions options = new V1DeleteOptions();
        logger.info("Starting clean up of namespaced pods for namespace {}", namespace);
        coreV1Api.deleteCollectionNamespacedPod(namespace,
            PRETTY_OUTPUT,
            null,
            null,
            null,
            0,
            null,
            null,
            null,
                "Foreground",
            null,
            null,
            options
            );
        logger.info("Finished clean up of namespaced pods for namespace {}", namespace);
        ApiException.getResponseBody();
      } catch (ApiException e) {
        handleAPIException(e, KUBE_RESOURCE_PODS, id1, id2);
      }
    });
  }`

code for cleanup of NS:
```
public void cleanUpNamespacedResources(String imsOrgId, Optional<String> sandboxId,
                                         ApiClient apiClient,
                                         String namespace) throws DeploymentException {
    final CoreV1Api coreApi = new CoreV1Api(apiClient);
    final AppsV1Api api = new AppsV1Api(apiClient);
    final RbacAuthorizationV1Api rbacApi = new RbacAuthorizationV1Api(apiClient);
    final NetworkingV1Api networkApi = new NetworkingV1Api(apiClient);
    final CustomObjectsApi customObjectsApi = new CustomObjectsApi(apiClient);
    final String ethosNS = NamespaceUtils.retrieveEthosNS(namespace);
    final String sandbox_id = sandboxId.orElse(null);
    logger.info("Starting clean up of namespaced resources for namespace {} ,id1 {} and id2 {}",
        namespace, id1, id2);
    final List<CompletableFuture<Void>> futureList = new ArrayList<>();
    futureList.add(cleanUpNamespacedCiliumNetworkPolicy(customObjectsApi, NS, id1, id2));
    futureList.add(cleanUpNamespacedIngressRoutes(customObjectsApi, NS, id1, id2));
    futureList.addAll(cleanUpNamespacedServices(coreApi, NS, id1, id2));
    futureList.add(cleanUpNamespacedDeployment(api, NS, id1, id2));
    futureList.add(cleanUpNamespacedPods(coreApi, NS, id1, id2));
    futureList.add(cleanUpNamespacedServiceMonitor(customObjectsApi, NS, id1, id2));
```

NS deletion snippet (calls cleanupnamespacedresources which in turn invokes pod deletion)
`if(namespaceDeployer.getNamespace(id1, id2) != null) {
                    try {
                        deploymentService.cleanUpNamespacedResources(id1, Optional.of(id2), apiClient, namespacePayload.getNamespaceName());
                    } catch (Exception e) {
                        logger.info("Unable to delete namespace objects");
                    }
                    //Thread.sleep(5000);
                    namespaceDeployer.deleteNamespace(id1, id2);
                } else {
                    logger.info("Namespace{} does not exists for id1{} and id2{}", namespacePayload.getNamespaceName(), id1, id2);`

Do note that the comment sleep of 5000 ms results in cleanup to complete before calling for NS deletion and no exception is thrown.

**Comment by brendandburns** [comment]
I'm not sure how this code relates to the error above, since the error above seems to be about namespaces.

btw, I notice that you have `ApiException.getResponseBody()` in your code. I don't think that compiles, but if it does it's not what I meant. I meant that if an ApiException is thrown, you should print to System.out `ex.getResponseBody()`
