### ISSUE TITLE
[QUERY] Webhook support

### ISSUE THREAD

**Issue by weiqingy** [kubernetes-client/java#1772]
Hi team, 

Wondering if Java client support webhook? Seems there is no admissionv1.AdmissionReview. Please let me know if I missed anything.

Thanks!

**Comment by brendandburns** [comment]
Webhooks can be defined e.g. 

https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1MutatingWebhook.java#L111

Can you share the code you are trying to write?

**Comment by weiqingy** [comment]
Thanks for the quick response, @brendandburns !

@wenjun001  Could you pls share the code here?  thanks!

**Comment by wenjun001** [comment]
@brendandburns  can you share with us how to generate AdmissionReview model from the API server?

**Comment by brendandburns** [comment]
Ah, I understand now, you're looking to write a WebHook in Java, not configure one in the API server.

Currently the `AdmissionReview` class isn't defined as part of the Kubernetes OpenAPI spec, there's a long discussion of that here:

https://github.com/kubernetes/kubernetes/issues/84081

There is a community generated OpenAPI spec here:
https://gist.github.com/bergeron/70ca86cf31762e16f18b2be3c549a074

And you can use the instructions here:
https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model

To generate models from that OpenAPI spec.

However, this seems to be a common enough use case that we should probably generate them ourselves and include them in the project. I will try to get that going.

**Comment by brendandburns** [comment]
Update: I went and generated these myself, the pull request w/ them is here:

https://github.com/kubernetes-client/java/pull/1774

**Comment by wenjun001** [comment]
@brendandburns  thank you for your quick response.  We will use this latest one to implement webhook now.

**Comment by brendandburns** [comment]
Closing this as these resources have been added and will be part of the 13.0.0 release.

**Comment by weiqingy** [comment]
Thanks @brendandburns !
