### ISSUE TITLE
1.20 and 1.21 compatability

### ISSUE THREAD

**Issue by codeyq** [kubernetes-client/java#1777]
**Describe the bug**
The version and compatibility page doesn't show the supportability for 1.20 and 1.21 k8s version. Can we update the page with new client and server versions?

** Client Version **
e.g. `11.0.1`

** Kubernetes Version **
e.g. `1.19.3`

** Java Version **
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
Updated.

There was a typo where 1.19 was duplicated for 11.0 and 12.0 (now fixed)
1.21 is only supported by HEAD (and the forth-coming 13.0 release (#1771)

**Comment by karunasagark** [comment]
@brendandburns 13.0 does not support 1.20 i.e. has a 'x' as per https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility. I don't think that is right, is it?
