### ISSUE TITLE
Broken links in GitHub  wiki

### ISSUE THREAD

**Issue by karthikkondapally** [kubernetes-client/java#1787]
Some of the links in GitHub wiki project are broken and not pointing to correct page

- **Contributing.md** link in https://github.com/kubernetes-client/java/wiki/4.-Development-and-Contributing.
- more **examples** link in https://github.com/kubernetes-client/java/wiki/3.-Code-Examples
-  **cert-manager**, **prometheus operator** links in https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model

**Comment by yue9944882** [comment]
@karthikkondapally thank you so much for sorting these out!

**Comment by yue9944882** [comment]
/close

closing b/c the links are fixed now
