### ISSUE TITLE
How to upload MultipartFile into pod's persistent volume?

### ISSUE THREAD

**Issue by Teramaks** [kubernetes-client/java#1794]
I was looking for solution to upload file into pod's volume, but pods().withName().file().upload() supports only the way with path, is there any way to upload using InputStream?

**Comment by brendandburns** [comment]
fwiw, that code looks like it is the fabric8 client, not this client, but regardless, we don't support this either.

The relevant Copy code is here:
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/Copy.java#L394

And it would be easy enough to just implement it yourself (it uses `Exec` under the hood for most of the heavy lifting)

**Comment by Teramaks** [comment]
Thank you very much!
