### ISSUE TITLE
Yaml fails to load/dump CRD contains x-kubernetes-int-or-string in V1JSONSchemaProps

### ISSUE THREAD

**Issue by chingyi-lin** [kubernetes-client/java#1796]
**Describe the bug**

If the CRD yaml contains `x-kubernetes-int-or-string`, then `Yaml` fails to load the manifest as V1CustomResourceDefinition object. Replacing `x-kubernetes-int-or-string` with `xKubernetesIntOrString` will make Yaml be able to load it successfully. Besides, with `Yaml.dump` on V1CustomResourceDefinition object, the returned yaml string gets  `xKubernetesIntOrString` instead. If one uses the string as the patch request body, the api server will reject it as the spec is invalid.

** Client Version **
`11.0.0` (issue persisted in 11.0.2 and 13.0.0)

** Kubernetes Version **
`1.18.16`

** Java Version **
Java 8

**To Reproduce**
1. Copy the `felixconfigurations.crd.projectcalico.org` crd manifest obtained from https://docs.projectcalico.org/archive/v3.19/manifests/tigera-operator.yaml as a string.
2. Use `Yaml.loadAll("the crd manifest string")` or `Yaml.loadAs("the crd manifest string", V1CustomResourceDefinition.class)`to load it.
3. Observe the error
```
Cannot create property=spec for JavaBean=class V1CustomResourceDefinition {
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
...
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'x-kubernetes-int-or-string' on class: io.kubernetes.client.openapi.models.V1JSONSchemaProps
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:159)
```
**Expected behavior**
* The CRD yaml is being loaded successfully.
* Yaml properly dump `V1CustomResourceDefinition` back to string.

**KubeConfig**
N/A

**Server (please complete the following information):**
 - OS: Amazon Linux 2
 - Environment [e.g. container]
 - Cloud: EKS

**Additional context**
N/A

**Comment by brendandburns** [comment]
Thanks for the detail bug descripton, we will investigate this.

**Comment by yue9944882** [comment]
/assign

thank you for the clue!

**Comment by chingyi-lin** [comment]
Glad to see a fix is merged! I'll validate it once it's released. thank you!
