### ISSUE TITLE
Logs request failed: 400 io.kubernetes.client.openapi.ApiException: Logs request failed: 400 at io.kubernetes.client.PodLogs.streamNamespacedPodLog(PodLogs.java:98) ~[client-java-12.0.0.jar

### ISSUE THREAD

**Issue by habibali95** [kubernetes-client/java#1801]
Describe the bug
Log request failed when trying to use the method podLogs.streamNamespacedPodLog
** Client Version **
12.0.0

** Kubernetes Version **
1.19.3`

** Java Version **
Java 8

To Reproduce
use podLogs.streamNamespacedPodLog

Expected behavior
error 400
KubeConfig
If applicable, add a KubeConfig file with secrets redacted.

Server (please complete the following information):

OS: linux
Environment container
Cloud aws
Additional context
.getResponseBody is returning null

We don't use any HTTP proxy,
This is how we call the API

inputStream = podLogs.streamNamespacedPodLog(org, v1Pod.getMetadata().getName(), null, sinceSecond,
tailLine, false);
org is an existing namespace, sinceSecond is mostly= 2 and tailLine is mostly null

**Comment by yue9944882** [comment]
a `400` error code usually means you are requesting the wrong kubernetes API, can you set `ApiClient#setDebugging` to true and share us more logging? @habibali95

**Comment by habibali95** [comment]
Hello @yue9944882, after setting the debug to true we understood the issue, the pod is still in the phase containerCreating.. in this case, the API return 400 with no details.
Thank you very much for your help, I will close the issue since it's not a bug.
