### ISSUE TITLE
Version 13.0 supports Kubernetes 1.20?

### ISSUE THREAD

**Issue by karunasagark** [kubernetes-client/java#1811]
**Describe the bug**
As per the [versioning and compatibility wiki](https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility) client 13.0 does not support 1.20 i.e. has a 'x'. I don't think that is right, is it?

** Client Version **
e.g. `13.0`

** Kubernetes Version **
e.g. `1.20`

** Java Version **
e.g. Java 11

**Comment by yue9944882** [comment]
they are completely compatible. and it's a bug in the doc, sorry!

**Comment by brendandburns** [comment]
This looks like it is fixed in the wiki now. Closing the issue.
