### ISSUE TITLE
Get custom object from namespace

### ISSUE THREAD

**Issue by tmytlovych-perfectial** [kubernetes-client/java#1815]
Hi

Is there a way to get some custom resources from the namespace? 
Please keep in mind that those resources are out of pod.

Original kubectl is like:

`kubectl get CUSTOM_RESOURCE --namespace TARGET_NAMESPACE --kubeconfig kubeconfig.yml`

**Comment by brendandburns** [comment]
You need to use the GenericAPI, there's an example here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/GenericClientExample.java

You will also need to either hand-code or generate objects for your custom resource, there are instructions here:
https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model

**Comment by tmytlovych-perfectial** [comment]
Thanks
