### ISSUE TITLE
CreateServiceBUG

### ISSUE THREAD

**Issue by kay07** [kubernetes-client/java#1816]
**Describe the bug**
Create a service we need a targetPort,for examples:

tips:dto.getPort() is an Interger type.

`IntOrString intOrString=new IntOrString(dto.getPort().toString());

servicePort .setTargetPort(intOrString);`

Then I will get an error,io.kubernetes.client.openapi.ApiException: Unprocessable Entity.

I have to change it to:

`IntOrString intOrString=new IntOrString(dto.getPort());

servicePort .setTargetPort(intOrString);`

** Client Version **
e.g. `11.0.1`

** Kubernetes Version **
e.g. `1.19.3`

** Java Version **
e.g. Java 8

**Expected behavior**

I think the "IntOrString" should use Interger or String,but now it can use Interger only.

**Comment by brendandburns** [comment]
IntOrString is generally used to represent a number or a name, not a stringified number.

Does it work if you use a string in the YAML and submit via `kubectl`? (e.g. `targetPort: "5"`) 

What is the unprocessable entity error message (print `ApiException.getResponseBody()`)
