### ISSUE TITLE
ttlSecondsAfterFinished is not working 

### ISSUE THREAD

**Issue by manju-v** [kubernetes-client/java#1825]
I have created a job using batchv1 kubernetes java client.
V1Job body = new V1Job().kind("Job")
        .metadata(metadata.name(jobName).namespace(JobYamlConfig.NAMESPACE))
        .spec(spec.ttlSecondsAfterFinished(JobYamlConfig.JOB_DELETE_TTL)
            .template(template.spec(podSpec.containers(containers).restartPolicy("OnFailure")
                .nodeSelector(nodeSelector))));
    try {
       api.createNamespacedJob(JobYamlConfig.NAMESPACE, body, null, null, null);
    } catch (Exception e) {
      LOGGER.error("Create Job Exception: {}", api.getApiClient(), e);
    }

The above code creates a job. The issue is job is not getting deleted even after ttl seconds.

** Client Version **
`13.0.0`

** Kubernetes Version **
`1.18.6`

** Java Version **
 Java 8

**Comment by brendandburns** [comment]
When you look at the YAML for the job (`kubectl get jobs ... -o yaml`) is the TTL set correctly?

**Comment by manju-v** [comment]
No. It was not set. This document  https://v1-18.docs.kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/ says that ttl controller is available in v1.12 [alpha]. My kubernetes version is 1.18.6 and alpha features were not enabled. This might be the reason for ttlSecondsAfterFinished not working.

**Comment by brendandburns** [comment]
Closing this since it seems like it is a Kubernetes version issue, not a client library issue. Please use `/reopen` if you need further assistance.
