### ISSUE TITLE
ReflectorRunnable using old resource version fails to redo list-watch in v13.0.0

### ISSUE THREAD

**Issue by haoming-db** [kubernetes-client/java#1829]
**Describe the bug**
This commit might have introduced a bug because it no longer throws `RuntimeException`: https://github.com/kubernetes-client/java/commit/0e596bbf2f6bfb18848e0bb5bd94064269dab483

(At least in k8s 1.18 and 1.19) when the resource version specified in the watch call is too old, API server could return HTTP 200 with an event having status code 410 and message `too old resource version:`.
In this case, the client should redo list from scratch and then start watching. However, this self-recovery was broken in 13.0.0 by https://github.com/kubernetes-client/java/commit/0e596bbf2f6bfb18848e0bb5bd94064269dab48

In client lib 13.0.0,  [the error we observed is logged here](https://github.com/kubernetes-client/java/blob/release-13/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L235), where the client uses a too old resource version to do k8s watch. This “too old resource version“ is a valid case, and the expected client behavior should be automatically restarting the list-then-watch (method `run()`) so it can recover. However, it calls `return` directly, while [before the commit](https://github.com/kubernetes-client/java/commit/0e596bbf2f6bfb18848e0bb5bd94064269dab483) the code was throwing a `RuntimeException`. The removal of `RuntimeException` is the reason of the bug. In 13.0.0, it will never exit the `while(true)` loop in this case - it always uses the old resource version and will never recover.

Client lib 12.0.0 has the correct behavior: When the client got “too old resource version“ event from k8s API server, with http code 200 but event status code 410, [it throws a RuntimeException](https://github.com/kubernetes-client/java/blob/release-12.0.0/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L227). The exception is [caught here](https://github.com/kubernetes-client/java/blob/release-12.0.0/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L126), and then the `run()` function [returns here](https://github.com/kubernetes-client/java/blob/release-12.0.0/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L150). Once return, the `ReflectorRunnable` is [rerun again after 1 second](https://github.com/kubernetes-client/java/blob/release-12.0.0/util/src/main/java/io/kubernetes/client/informer/cache/Controller.java#L119), so it will redo the list-then-watch `run()`. In this way, it recovers.

** Client Version **
13.0.0

** Kubernetes Version **
1.18, 1.19

** Java Version **
Java 8+. In fact Java version doesn't matter.

**To Reproduce**
Use an old resource version for watch.

**Expected behavior**
Se description of correct behavior in 12.0.0.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by haoming-db** [comment]
@yue9944882 Could you take a look on this? Thanks!

**Comment by yue9944882** [comment]
@haoming-db thank you for reporting this, just opened a fix. and we bump a fixed version soon, hopefully this month!

**Comment by haoming-db** [comment]
> @haoming-db thank you for reporting this, just opened a fix. and we bump a fixed version soon, hopefully this month!

Thanks @yue9944882 . Just to clarify, the fix will be in v13.0.x, right?

**Comment by yue9944882** [comment]
yes, the fix will get in master then release-13 branch (where we cut a new patch release)

**Comment by scheler** [comment]
@yue9944882 when are you planning to do the patch release on v13?  This is a show stopper for us. If this is going to take time, we will move back to an older version. let us know.

**Comment by yue9944882** [comment]
@scheler sry for the delay, i will be publishing a release soon this week or next!
