### ISSUE TITLE
IllegalStateException: Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by frey66** [kubernetes-client/java#1846]
kubenetes version : 1.19.3
dependency : 11.0.1
jdk : 1.8

I created a Demo according to the official case, 
but aways get  "com. Google. Gson. JsonSyntaxException: Java lang. An IllegalStateException:  Expected BEGIN_OBJECT but was STRING at line 1 column 4357"  this exception.

**Comment by frey66** [comment]
my code as follow : 

ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader("config"))).build();
        Configuration.setDefaultApiClient(client);
        CoreV1Api api = new CoreV1Api();
        V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
        for (V1Pod item : list.getItems()) {
            System.out.println(item.getMetadata().getName());
        }

**Comment by frey66** [comment]
![1629809598(1)](https://user-images.githubusercontent.com/46990259/130619671-95cd4de4-4a63-4ea7-9cba-7f289a10e521.png)

![1629809656(1)](https://user-images.githubusercontent.com/46990259/130619839-70e380ce-b940-4bf9-bb62-5c0467657a8b.png)

**Comment by brendandburns** [comment]
I strongly suspect that either you have the wrong server/port configured in `config` file for the client or there is a mis-behaving HTTP proxy in the middle.

This code works connected to my cluster.

**Comment by frey66** [comment]
> I strongly suspect that either you have the wrong server/port configured in `config` file for the client or there is a mis-behaving HTTP proxy in the middle.
> 
> This code works connected to my cluster.

It conflicts with the hadoop dependency in the project. exclusion the gson dependency in hadoop will solve the problem. Thank you

**Comment by brendandburns** [comment]
Closing this comment since the problem appears to be resolved.
