### ISSUE TITLE
java.io.IOException: Invalid DER: object is not integer (continued)

### ISSUE THREAD

**Issue by jevin36** [kubernetes-client/java#185]
unfortunately I am unable to reopen the task https://github.com/kubernetes-client/java/issues/135 again, so I am posting this question here again.

Hi,

I am trying to get the client api (0.2) up and running but unfortunately I am getting the following error:

2017-12-05 16:21:10 ERROR {main} io.kubernetes.client.util.Config - Failed to invoke build key managers
java.io.IOException: Invalid DER: object is not integer
	at io.kubernetes.client.util.SSLUtils$Asn1Object.getInteger(SSLUtils.java:229)
	at io.kubernetes.client.util.SSLUtils.next(SSLUtils.java:160)
	at io.kubernetes.client.util.SSLUtils.decodePKCS1(SSLUtils.java:155)
	at io.kubernetes.client.util.SSLUtils.createKeyStore(SSLUtils.java:100)
	at io.kubernetes.client.util.SSLUtils.createKeyStore(SSLUtils.java:78)
	at io.kubernetes.client.util.SSLUtils.keyManagers(SSLUtils.java:63)
	at io.kubernetes.client.util.Config.fromConfig(Config.java:110)

I tried it with the following code (via config yaml as string and via ~/.kube/config file)

ApiClient apiClient = Config
                    .fromConfig(configAsString)
                    //.fromConfig(new FileReader("/Users/me/.kube/config"))
                    .setVerifyingSsl(false);
Configuration.setDefaultApiClient(apiClient);

kubectl on command line works fine with my config

Do you have any suggestions? Is there anybody whom I can send an example kubeconfig with the keys and certificates for testing? I am not allowed to post it here though.

**Comment by brendandburns** [comment]
I'd rather not have a working kubeconfig.  Is there any chance you can re-create a similar kubeconfig with fake (or deleted) certificates?

**Comment by jevin36** [comment]
Hi, why not? It's not a problem working with it cause the certificates are created by an in company CA. The ones I have sent you already expired.

Or do you see another issue?

**Comment by brendandburns** [comment]
I don't want to be in a situation where I have access to someone else's cluster.

If the config is no longer valid, then I'm fine with it.



________________________________________

**Comment by jevin36** [comment]
Yeah, you re fine. The cluster was removed a couple of weeks again - also only available within the local company network

**Comment by brendandburns** [comment]
Ok cool. What email address did you send it to?

--brendan

________________________________

**Comment by jevin36** [comment]
Hi, to bburns@microsoft.com

**Comment by brendandburns** [comment]
Ok, I found the problem. 

We are hard-coding "RSA" here:

https://github.com/kubernetes-client/java/blob/505a812482d0d3a61e47c4188fdab14935ec0f42/util/src/main/java/io/kubernetes/client/util/credentials/ClientCertificateAuthentication.java#L29

And your key is an eliptical curve key.

For now, you need to use an RSA key, or manually edit the library SSHUtils.java code to change 'RSA' to 'EC'

I'll work to add EC support to the library...

**Comment by brendandburns** [comment]
I took a stab at EC support today, it did not end well...  I think the short term fix is to convert to RSA. I'll continue to try to convince Java to load an EC key, but it might take a while...

**Comment by brendandburns** [comment]
Ok, that took longer than it should have, but the fix is now in PR, I'd love it if you could try it out and verify...

**Comment by jevin36** [comment]
Hi,
just had a quick test and I am not sure if I am doin sth wrong now. This is the code I quickly tried:

```
ApiClient client = Config.fromConfig("/Users/minime/Desktop/kubeconfig");
Configuration.setDefaultApiClient(client);

CoreV1Api api = new CoreV1Api();
V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
for (V1Pod item : list.getItems()) {
    System.out.println(item.getMetadata().getName());
}
```

seems like the certificates are empty (see IllegalArgumentException)

_ApiClient.applySslSettings_
```
else if (sslCaCert != null) {
     char[] password = null; // Any password will work.

     CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");

     Collection<? extends Certificate> certificates = certificateFactory.generateCertificates(sslCaCert);
     if (certificates.isEmpty()) {
         throw new IllegalArgumentException("expected non-empty set of trusted certificates");
     }
}
```

**Comment by ceeaspb** [comment]
@jevin36 looks like I may have hit the same thing in #197

**Comment by kondapally1989** [comment]
@jevin36 

initially verifySSL by default was false. but after push https://github.com/kubernetes-client/java/pull/175, verifySSL by default is true. 
Even i got the error:
```Exception in thread "main" java.lang.IllegalArgumentException: expected non-empty set of trusted certificates```
but if you add **insecure-skip-tls-verify: true** in (kubeconfig.yaml in cluster section)
it works then.

we can also skip verify ssl instead of adding above key value pair by 
```java
ApiClient client = ClientBuilder
				   .standard()
				   .kubeconfig(KubeConfig.loadKubeConfig(new FileReader("/home/karthik/.kube/config")))
				   .setVerifyingSsl(false)
				   .build();
```

**Comment by jevin36** [comment]
#198 fixes the problem correctly for me too
