### ISSUE TITLE
SharedIndexInformer doesn't fill apiVersion/kind in objects passed into onAdd/onUpdate/onDelete

### ISSUE THREAD

**Issue by dsonck92** [kubernetes-client/java#1858]
**Describe the bug**
When using the `SharedIndexInformer` and registering a `ResourceEventHandler`, when the `onAdd`/`onUpdate`/`onDelete` is called, the objects `apiVersion` and `kind` are not filled. If these objects are blindly passed into a fluent builder, modified and then passed to replace, the api server complains that the kind is invalid.

I'm not sure if this is the fault of:
- `SharedIndexInformer` since it should fill in the accurate details in the model
- The models themselves, since they are typed to their specific apiVersion/kind
- The replace functions from the apis since they should be compatible with a particular apiVersion/kind to be sent to the apiserver

**Client Version**
`13.0.0`

**Kubernetes Version**
`1.21.3`

**Java Version**
Java 11

**To Reproduce**
- Write an event handler for the `SharedIndexInformer`
- Subscribe to a watch event
- Log/inspect the given objects, they should have `apiVersion`/`kind` set to `null`

**Expected behavior**
The returned objects should have their `apiVersion` and `kind` set to the appropriate values for the given objects.

*Or*

If this is not necessary, passing said object through the builder and subsequently to the replace function should
correct the `apiVersion` and `kind`

**Server (please complete the following information):**
 - OS: Linux
 - Environment container
 - Cloud self hosted

**Comment by yue9944882** [comment]
> When using the SharedIndexInformer and registering a ResourceEventHandler, when the onAdd/onUpdate/onDelete is called, the objects apiVersion and kind are not filled.

@dsonck92 thanks for reporting this, but when i tested it in the golang informer library, i found that the `apiVersion` nor `kind` were filled. note that the field is missing b/c the original server response doesnt contain that information:

```bash
$ kubectl get --raw="/api/v1/namespaces"
{"kind":"NamespaceList","apiVersion":"v1","metadata":{"resourceVersion":"1334009"},"items":[{"metadata":{"name":"default","uid":"77e79aa0-6920-41cf-9d73-143ebdce38a4","resourceVersion":"199","creationTimestamp":"2021-08-03T07:08:20Z","managedFields":[{"manager":"kube-apiserver","operation":"Update","apiVersion":"v1","time":"2021-08-03T07:08:20Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:phase":{}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}},{"metadata":{"name":"kube-node-lease","uid":"ab21b83c-2eab-475a-9d0d-f1b1288460ee","resourceVersion":"65","creationTimestamp":"2021-08-03T07:08:19Z","managedFields":[{"manager":"kube-apiserver","operation":"Update","apiVersion":"v1","time":"2021-08-03T07:08:19Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:phase":{}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}},{"metadata":{"name":"kube-public","uid":"1edba1f8-5e8e-431e-99b5-df83791d66bc","resourceVersion":"46","creationTimestamp":"2021-08-03T07:08:19Z","managedFields":[{"manager":"kube-apiserver","operation":"Update","apiVersion":"v1","time":"2021-08-03T07:08:19Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:phase":{}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}},{"metadata":{"name":"kube-system","uid":"aa7102bb-1031-4fb7-b3a3-b668f9938b2a","resourceVersion":"17","creationTimestamp":"2021-08-03T07:08:19Z","managedFields":[{"manager":"kube-apiserver","operation":"Update","apiVersion":"v1","time":"2021-08-03T07:08:19Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:phase":{}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}},{"metadata":{"name":"local-path-storage","uid":"f5b11189-2f42-45f0-aac5-1792a34bce94","resourceVersion":"293","creationTimestamp":"2021-08-03T07:08:25Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"local-path-storage\"}}\n"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"v1","time":"2021-08-03T07:08:25Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:status":{"f:phase":{}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}]}
```

> If these objects are blindly passed into a fluent builder, modified and then passed to replace, the api server complains that the kind is invalid.

can you elaborate how you're replacing the object? e.g. which specific api are you using?

**Comment by dsonck92** [comment]
So far I don't seem to reproduce the issue. To explain the general flow:

```java
function onUpdate(V1Deployment oldObject, V1Deployment newObject) {
  V1Deployment object = new V1DeploymentBuilder(newObject).<some modifications>.build();
  api.updateNamespacedDeployment(object.getMetadata().getNamespace(), object.getMetadata().getName(), object, ...);
}
```
In reality it's slightly more complex since I built a wrapper around updateNamespacedDeployment() to account for changing objects. Instead of directly calling update, I pass in an updating function and the original object to the wrapper, it calls update and if that fails with `409`. If that fails, it calls readNamespacedDeployment to get the current state, and calls update again. This ensures that the controller always builds on top of existing objects (since its only job is usually altering labels based on other labels, it must not affect anything else).

So I consider it fixed for now, and I'll reopen if I actually hit it.
