### ISSUE TITLE
Add support for new Gateway API

### ISSUE THREAD

**Issue by JamesXNelson** [kubernetes-client/java#1859]
The new Gateway API https://gateway-api.sigs.k8s.io/ is a promsing new implementation that is slated to ultimately replace Ingress.

Even though it is in alpha, and the docs say "don't use in production", the gateway model is vastly superior for my use case (dynamically adding subdomains for each new client), so I'd _really_ like to try using the gateway api, but without a V1alpha1Gateway class and friends, I cannot w/o devolving to command line `kubectl` invocations (yuck! definitely not going there).

If it is not desirable to release these types yet, I would be willing to build my own and add those types. I don't know how to do this, so if a team member in the know can point me in the right direction, I would appreciate it.

**Comment by yue9944882** [comment]
@JamesXNelson generating java models from either local or remote CRD specs is supported via the codegen runner container. e.g. this is how we generate CRD models for `prometheus-operator`:

https://github.com/kubernetes-client/java/blob/07e714ce5cddc2e09da544d8435131df8096d680/client-java-contrib/prometheus-operator/update.sh#L27-L43

i will appreciate it if you can contribute the generated models back as a new module under `client-java-contrib` btw

**Comment by Ironlink** [comment]
According to a recent Kubernetes blog entry (https://kubernetes.io/blog/2023/10/25/introducing-ingress2gateway/), the Gateway API is "just weeks away from graduating to GA".

@yue9944882 Is the instruction to create a contrib module for Gateway still accurate?

I tried running the code-gen script locally, but it fails due to not recognizing CRD Validation Rules. The output suggests that I could disable validation by adding the argument `--validate=false`, but this option is not exposed by `generate.sh`. Please advise.

```bash
docker run \
  --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":"$(pwd)" \
  --network host \
  ${IMAGE_NAME}:${IMAGE_TAG} \
  /generate.sh \
  -u https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.1/standard-install.yaml \
  -n io.k8s.sigs.gateway-api \
  -p io.k8s.sigs.gateway_api \
  -o "$(pwd)"
```

```
error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.controllerName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.versions[1].schema.openAPIV3Schema.properties.spec.properties.controllerName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false
```
