### ISSUE TITLE
Best practices to define CRD and reuse schema

### ISSUE THREAD

**Issue by mynameborat** [kubernetes-client/java#1869]
I am  developing an operator using java client and want to reuse the schema for some of the fields from existing openapi spec  in our `CustomResourceDefinition` e.g., `securityContext` from `PodSpec`.

Is it possible to reuse schemas across CRDs? 

I tried to copy over the schema as is in place. However, CRD Java POJOs generation generates POJOs that are scoped and usable only within my context of CRD and I still need to write explicit converters to convert those fields into the corresponding fields in the native K8s resources.

Any pointers or suggestions is much appreciated. Thanks!

**Comment by brendandburns** [comment]
You can use the `importMappings` field to override the generator, we do this for things like `Quantity`.

See the XML here:
https://github.com/kubernetes-client/gen/blob/master/openapi/java.xml#L33

You may also need to tweak the pre-processing script here:
https://github.com/kubernetes-client/gen/blob/master/openapi/preprocess_spec.py#L139 (and in a few other places)

fwiw, this isn't going to be super straightforward (apologies!) but it is possible.

**Comment by mynameborat** [comment]
@brendanburns Thanks for the response. It is interesting that some of the field's source of truth is coming from Kubernetes master branch. Are there guarantees that these fields evolve in backward compatible manner as the client version used by applications maybe older and the view of these fields may differ between code generated vs the code available in the class path.

Wonder if this is a concern if we were to expand the list of the fields that are being reused from native K8s resources? Although, I noticed you can override the branch that is being used for generation and perhaps aligning that with the client sdk version might help enforce validity and availability of the fields that is generated.

**Comment by brendandburns** [comment]
We do align the versions of the SDK with kubernetes versions. You can see the table here:

https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility

**Comment by mynameborat** [comment]
I was referring to applications that use the crd-model-gen library to generate CRD POJOs. Looks like the onus is on the application developers to ensure they have the appropriate java-client sdk versions to ensure the metadata fields are compatible.

Is that correct?

**Comment by brendandburns** [comment]
Yes, your library would need to depend on a specific major version of the Java SDK.

That said, most of the fields that you referenced are GA'd fields in Kubernetes and change very slowly if at all, so in practical terms I don't think you would hit many problems even with version skew.
