### ISSUE TITLE
How to get KubeApiSever metric with Java Client

### ISSUE THREAD

**Issue by yunzoud** [kubernetes-client/java#1870]
we can call kubectl get --raw /metrics to get list of raw metrics, is there a way that we can get those metrics through java client?

**Comment by brendandburns** [comment]
There's an example of how to get metrics here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/MetricsExample.java

Although perhaps those aren't the metrics you're looking for?

If you want to make a raw call, you can use the `ApiClient.buildCall(...)` function to build the raw call:
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L995

**Comment by brendandburns** [comment]
Closing this issue since I believe the question is answered and no further requests. Use `/reopen` or open a new issue if you need further assistance.
