### ISSUE TITLE
Fail to generate Java codes from CustomResourceDefinition

### ISSUE THREAD

**Issue by ajtomato** [kubernetes-client/java#1882]
I am developing knative serving java client. I am referring the following instructions to generate model, but get a failure:

https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

I put the crd files under `/tmp/crds/` and use the following command:

```shell
docker run \
  --rm \
  -v "$LOCAL_MANIFEST_FILE":"$LOCAL_MANIFEST_FILE" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":"$(pwd)" \
  -ti \
  --network host \
  ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.4 \
  /generate.sh \
  -u $LOCAL_MANIFEST_FILE \
  -n serving.knative.dev \
  -p com.example.stable \
  -o "$(pwd)"
```

No code is generated under `src/main/java/com/example/stable`. The log and crds are attached. Something wrong in the command?

[serving-crds-0.23.2.yaml.txt](https://github.com/kubernetes-client/java/files/7160289/serving-crds-0.23.2.yaml.txt)

[log.txt](https://github.com/kubernetes-client/java/files/7160265/log.txt)

**Comment by brendandburns** [comment]
I believe that you have the value for `-n` flag reversed, the docs say:

`<the target CRD group name, which is in the reverse order of ".spec.group">`

But right now, it appears that it the same order as `spec.group`

cc @yue9944882 since he's the expert in this area.

**Comment by ajtomato** [comment]
That is absolutely right. After change the order of `-n` flag, it works. Thanks a lot.
