### ISSUE TITLE
Release 13.0.1 and regenerate for 14.0.0 / 1.22?

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1892]
@yue9944882 

Kubernetes 1.22 has been out for a while and 1.23 is on the horizon, shall we cut a 13.0.1 release and then regenerate for 14.0.0 / 1.22?

**Comment by saparaj** [comment]
Hi @brendanburns and @yue9944882 : Any time soon are we planning to release this cut 13.0.1?

**Comment by rdesgroppes** [comment]
Works like a charm. Many thanks, @brendandburns!
