### ISSUE TITLE
Is the uninstall of helm release available with this library

### ISSUE THREAD

**Issue by srinivasev** [kubernetes-client/java#1895]
Hi,

Can i uninstall an helm release using any api with this library/jar.

**Comment by brendandburns** [comment]
Assuming you are using Helm 3, Helm uses a custom resource definition.

There is no Java object (POJO) for Helm currently in this library, so you will have to define your own POJO and use the Generic API, which is a little manual. There is an example of how to use this API here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/GenericClientExample.java

If you would rather not define a POJO, you can use the Dynamic client, there's an example here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/DynamicClientExample.java
