### ISSUE TITLE
Are there established reference projects?

### ISSUE THREAD

**Issue by mamachanko** [kubernetes-client/java#1900]
I am looking for battle-tested, Java-based projects implementing the operator pattern that can serve as references. However, I struggle to find any.

There's an abundance of Golang-based operators. It's the go-to language in Kubernetes land. However, learning about patterns sometimes is easier by reading code in your team's primary language, e.g. Java.

There’s a wealth of [examples](https://github.com/kubernetes-client/java/tree/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples) in `kubernetes-client/java`. I thought I was clever by [searching GH for `public Result reconcile(Request request)`](https://github.com/search?l=Java&q=%22public+Result+reconcile%28Request+request%29%22&type=code), but that as well yielded almost nothing beyond examples.

Understandably, it is not common for large open-source projects to play favorites and list user implementations. But maybe someone can point some out?

(I've also [asked in #kubernetes-client](https://kubernetes.slack.com/archives/C76GB48RK/p1632496279067100).)

**Comment by brendandburns** [comment]
We don't really keep track (or even have visibility into) users of this library, but based on questions on the issues queue, it seems that both [Oracle](https://github.com/kubernetes-client/java/issues/1886) and Alibaba.

I'm going to close this issue as I believe the question is as answered as it is going to get :)

**Comment by mamachanko** [comment]
thanks @brendandburns !

**Comment by yue9944882** [comment]
@mamachanko we practiced java-based operator in production for years in alibaba. but most of them are not public projects btw..
