### ISSUE TITLE
Springboot integration with K8S API Demo？

### ISSUE THREAD

**Issue by tina-root** [kubernetes-client/java#1901]
**Describe the bug**

** Client Version **
e.g. `11.0.1`

** Kubernetes Version **
e.g. `1.19.3`

** Java Version **
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
Not sure what the issue is. Please add details of the problems you are seeing.

**Comment by yue9944882** [comment]
@tina-root appreciated if you can rephrase your question in english so that other users can learn from the thread

**Comment by tina-root** [comment]
hello！
Sorry, I just want a Springboot integration K8S API demo. I found the doc document on github's official website and found it difficult to understand.
Thanks for your help!

**Comment by brendandburns** [comment]
Thanks! There are a couple of examples here:
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java

**Comment by tina-root** [comment]
> 谢谢! 这里有几个例子: [https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java ](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java)
> 
> [https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java ](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java)

好的，非常感谢！
Ok, thank you very much!

**Comment by tina-root** [comment]
> 谢谢! 这里有几个例子: [https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java ](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java)
> 
> [https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java ](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java)

再次打扰，为什么代码中都不写注释？
Excuse me again, why are there no comments in the code?

**Comment by brendandburns** [comment]
I believe that the code is simple enough that comments are not required. Please let us know if there are questions about how to use it.

**Comment by tina-root** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
