### ISSUE TITLE
Would love to Contribute to this project 

### ISSUE THREAD

**Issue by Recognizeyourself** [kubernetes-client/java#1910]
I am a beginner in Java and looking for good-first-issues or first-timers contributions like documentation correction. 

Would be fortunate to be a part of this repository as a contributor.

Please point me in the right direction on how I can contribute to this repository. 

Thanks for reading.

**Comment by cbuschka** [comment]
Hey @Recognizeyourself  what's about how to setup the IDE with the correct formatter/ coding style. I am looking for information about how to configure my ide or verify if the code is properly commited before passing it on to @brendandburns .
