### ISSUE TITLE
Not able to generate classes for external snapshotter

### ISSUE THREAD

**Issue by kumars17** [kubernetes-client/java#1913]
I am trying to generate the classes for the kubernetes external snapshotter CRDs and am having hard time. Anyone able to generate it successfully?

When I try the latest master classes at https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd 

It fails with error 

LOCAL_MANIFEST_FILE=/tmp/crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
[root@lrmp113 crds]# docker run   --rm  -v "$LOCAL_MANIFEST_FILE":"$LOCAL_MANIFEST_FILE"  -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host ghcr.io/yue9944882/crd-model-gen:v1.0.4   /generate.sh   -u $LOCAL_MANIFEST_FILE   -n snapshot.storage.k8s.io   -p snapshot.storage.k8s.io    -o "$(pwd)"
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
error: error validating "/tmp/crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[1]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[1]): unknown field "deprecationWarning" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion]; if you choose to ignore these errors, turn validation off with --validate=false

when I try the 4.0 version of crds @ https://github.com/kubernetes-csi/external-snapshotter/tree/release-4.0/client/config/crd . It makes progress but finally fails with error:

docker run   --rm  -v "$LOCAL_MANIFEST_FILE":"$LOCAL_MANIFEST_FILE"  -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host ghcr.io/yue9944882/crd-model-gen:v1.0.4   /generate.sh   -u $LOCAL_MANIFEST_FILE   -n snapshot.storage.k8s.io   -p snapshot.storage.k8s.io    -o "$(pwd)"

cp: can't stat '/tmp/java/gen/src/main/java/snapshot/storage/k8s/io/models': No such file or directory

**Comment by yue9944882** [comment]
> Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
error: error validating "/tmp/crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[1]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[1]): unknown field "deprecationWarning" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion]; if you choose to ignore these errors, turn validation off with --validate=false

it's complaining b/c the kubernetes cluster from KinD is too old (1.18.2), i will be uploading a new generator image based on latest KinD.

**Comment by kumars17** [comment]
Not sure if I am referring to wrong CRDS??  I took it from  https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd

**Comment by kumars17** [comment]
Tried everything.. It still fails with same error...
docker run   --rm    -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host ghcr.io/yue9944882/crd-model-gen:v1.0.6   /generate.sh   -u https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml -u https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml -u https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml   -n   io.k8s.storage.snapshot   -p  io.k8s.storage.snapshot    -o "$(pwd)"

....

[INFO] writing file /output_dir/.gitignore
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ApiException.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/Configuration.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/Pair.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/auth/Authentication.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ApiCallback.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ApiResponse.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/JSON.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ProgressRequestBody.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ProgressResponseBody.java
[INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/GzipRequestInterceptor.java
[INFO] Skipped /output_dir/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[INFO] writing file /output_dir/.openapi-generator/VERSION
[INFO] writing file /output_dir/.openapi-generator/FILES
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.632 s
[INFO] Finished at: 2021-10-08T13:40:35Z
[INFO] ------------------------------------------------------------------------
---Done.
---Done.
cp: can't stat '/tmp/java/gen/src/main/java/io/k8s/storage/snapshot/models': No such file or directory

**Comment by rparke** [comment]
> Tried everything.. It still fails with same error... docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":"$(pwd)" -ti --network host ghcr.io/yue9944882/crd-model-gen:v1.0.6 /generate.sh -u https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml -u https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml -u https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml -n io.k8s.storage.snapshot -p io.k8s.storage.snapshot -o "$(pwd)"
> 
> ....
> 
> [INFO] writing file /output_dir/.gitignore [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ApiException.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/Configuration.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/Pair.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/auth/Authentication.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ApiCallback.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ApiResponse.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/JSON.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ProgressRequestBody.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/ProgressResponseBody.java [INFO] writing file /output_dir/src/main/java/io/kubernetes/client/openapi/GzipRequestInterceptor.java [INFO] Skipped /output_dir/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.) [INFO] writing file /output_dir/.openapi-generator/VERSION [INFO] writing file /output_dir/.openapi-generator/FILES [INFO] ------------------------------------------------------------------------ [INFO] BUILD SUCCESS [INFO] ------------------------------------------------------------------------ [INFO] Total time: 6.632 s [INFO] Finished at: 2021-10-08T13:40:35Z [INFO] ------------------------------------------------------------------------ ---Done. ---Done. cp: can't stat '/tmp/java/gen/src/main/java/io/k8s/storage/snapshot/models': No such file or directory

Have you had any luck with this. I've had the same issue with no solutions.

**Comment by pradeep-hegde** [comment]
I am facing the same issue with no solution. Any solutions to this issue?
