### ISSUE TITLE
`Yaml.load` fails for custom resource definition with `x-kubernetes-preserve-unknown-fields`

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [kubernetes-client/java#1930]
**Describe the bug**
`Yaml.load` of a custom resource definition including the parameter `x-kubernetes-preserve-unknown-fields` (https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/#JSONSchemaProps) fails:

> org.yaml.snakeyaml.error.YAMLException: Unable to find property 'x-kubernetes-preserve-unknown-fields' on class: io.kubernetes.client.openapi.models.V1JSONSchemaProps

It works if you specify it as `xKubernetesPreserveUnknownFields` but then the YAML is incompatible with other Kubernetes clients.

You can reproduce it with these files:
https://gist.github.com/dennis-benzinger-hybris/270b996c1ba2104467a29b373624c817

** Client Version **
Tried with 13.0.0 and 11.0.2

** Kubernetes Version **
1.22.1

** Java Version **
Java 8

**Comment by yue9944882** [comment]
@dennis-benzinger-hybris thank you for reporting this, i think it's already fixed by https://github.com/kubernetes-client/java/pull/1804, the fix is yet on the master branch tho.

**Comment by dennis-benzinger-hybris** [comment]
Thanks for the update. Yes, my issue looks very similar to #1796.
