### ISSUE TITLE
Sending commands to containers response very slowly

### ISSUE THREAD

**Issue by a116555** [kubernetes-client/java#1933]
**Describe the bug**
Sending commands to containers response very slowly

** Client Version **
e.g. `11.0.1`

** Kubernetes Version **
e.g. `1.19.3`

** Java Version **
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by a116555** [comment]
latency on reading
 The delay is more than 500ms

**Comment by brendandburns** [comment]
If you are sending a large amount of code, I suspect that this is because the buffer size in the pipe is 1024 and it is getting full and being read slowly, but I'm not certain.

**Comment by gfvirga** [comment]
@brendandburns I just ran into this issue and I copied the flush() inside the while loop and my API is returning the stream instantly!

Here is what I tried:
```
    fun streamLogs(pod: V1Pod): StreamingResponseBody {
        val `is` = logs.streamNamespacedPodLog(pod)

        return StreamingResponseBody { outputStream ->
            // Streams.copy(`is`, outputStream)
            val buf = ByteArray(1024)
            var length: Int
            while (`is`.read(buf).also { length = it } > 0) {
                log.info("readings")
                outputStream.write(buf, 0, length)
                outputStream.flush()
            }
            outputStream.close()
        }
    }
```
