### ISSUE TITLE
APIs to get cluster metrics.

### ISSUE THREAD

**Issue by blublinsky** [kubernetes-client/java#194]
Unless I am missing something, there are no APIs to get cluster metrics either based on Heapster APIs or Metric APIs. Are there any equivalents to:
kubectl top node and/or kubectl top pod --all-namespaces

**Comment by brendandburns** [comment]
Is there swagger/open api for those APIs somewhere?  If there is Swagger/OpenAPI we can look to generate it...

cc @mbohlool

**Comment by where-tsukada** [comment]
@blublinsky 
Did you find any solutions?

I also like to know how to get metrics equivalent to kubectl top pod.

**Comment by blublinsky** [comment]
Nothing so far.
Still waiting for reply


Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by varsanyid** [comment]
Is there any update regarding this?

**Comment by yue9944882** [comment]
the cluster metrics api's openapi-spec is not included in the kube-apiserver's. we have to retrieve the spec from the metrics server and run the [generator](https://github.com/kubernetes-client/gen) to generate its client.
