### ISSUE TITLE
Watching individual pods

### ISSUE THREAD

**Issue by bmcstdio** [kubernetes-client/java#195]
From what I understand it is currently not possible to [watch](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#watch-64) an individual pod. Are there any plans for supporting this?

**Comment by brendandburns** [comment]
Eventually :)  PRs welcome in the mean time...

**Comment by shrgupta7692** [comment]
Hi,

I think we can use this API - /api/v1/namespaces/{namespace}/pods  to watch an individual pod by passing pod name in fieldSelector like metadata.name=<podname> and in java client - API is CoreV1Api.listNamespacedPodCall.
