### ISSUE TITLE
How to resolve "Timeout: Too large resource version" In Java client ? 

### ISSUE THREAD

**Issue by kkkkun** [kubernetes-client/java#1950]
**Describe the bug**
/kind bug 

How to resolve kubernetes's issue kubernetes/kubernetes#91073 in Java client.

Recently We meet this question, It was fixed in client-go which would retry without resourceversion. Can we do same in Java client. https://github.com/kubernetes/kubernetes/pull/92537

**Comment by vitality411** [comment]
Still relevant @yue9944882
