### ISSUE TITLE
Release 11.0.3

### ISSUE THREAD

**Issue by ryanjbaxter** [kubernetes-client/java#1962]
It would be great to have a new release of the 11.0.x branch with the latest fixes.

**Comment by ryanjbaxter** [comment]
@brendanburns @yue9944882 would appreciate your help here

**Comment by yue9944882** [comment]
@ryanjbaxter do you think about having a new release this week or next? i can do the release next week but this week i'm a bit buried prepping for the upcoming kubecon event here (11.08 is the deadline for submitting the presentation materials)

**Comment by ryanjbaxter** [comment]
Yes next week is fine!

**Comment by brendandburns** [comment]
I pushed 11.0.3 and 12.0.2 to maven central, they are now available.

Please see #1964 and #1965

**Comment by ryanjbaxter** [comment]
Thank you!
