### ISSUE TITLE
How can I use api to operate 'kubectl rollout restart'? 

### ISSUE THREAD

**Issue by lmx-code** [kubernetes-client/java#1967]
**Describe the bug**
@brendandburns How can I use api to operate 'kubectl rollout restart'

** Client Version **
e.g. `13.0.1`

** Kubernetes Version **
e.g. `1.19.3`

** Java Version **
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
`kubectl rollout restart` is not a single API, it is a set of client-side logic programmed into the `kubectl ` executable.

We have re-implemented some of that here:
https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlRollout.java

But afaik, restart is not currently implemented. We would be happy to take a PR to add that support.
