### ISSUE TITLE
How can i use api to operate "kucubctl logs -f "?

### ISSUE THREAD

**Issue by lmx-code** [kubernetes-client/java#1971]
**Describe the bug**
@brendandburns How can i use api to watch log for pod
** Client Version **
e.g. `13.0.0`

** Kubernetes Version **
e.g. `1.19.3`

** Java Version **
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLog.java

**Comment by brendandburns** [comment]
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/LogsExample.java

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/KubectlExample.java
