### ISSUE TITLE
Best way to handle multiple k8s clusters 

### ISSUE THREAD

**Issue by pebf** [kubernetes-client/java#1972]
Hi, 
I'm developing live-ops application with this SDK. 

I tried with DynamiceKubernetesApi, but it's not working well for me. 
Maybe kubectl is better option since kubectl commands work well in my terminal. 
But it allows one k8s client in an application. 
Can I get a hint to handle multiple k8s clusters? It would be very helpful.

**Comment by brendandburns** [comment]
I'm not sure I fully understand your question, but you probably need to create one kubernetes api client object per cluster

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/Example.java#L34

If your clusters are all in the same kubeconfig file, then you can just use the `KubeConfig.setContext(...)` function to select a specific context.

If your clusters are in different kubeconfig files, then you will need to load a separate `KubeConfig` and client for each kubeconfig file.

**Comment by pebf** [comment]
@brendandburns Thanks for reply. Second one is answer for me. Could you give a example about that? 
Like the example you shared, io.kubernetes.client.openapi.Configuration instance only have defaultClient and CoreV1Api comes from global context. How can I create a CoreV1Api (or other Api) instance from different client?

**Comment by brendandburns** [comment]
You'll want to use `ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(pathToConfigFile))`

You will need to create a different instance of the `CoreV1Api` for each cluster you want to talk to.

**Comment by pebf** [comment]
Hi @brendandburns Thanks for your comments. 
Since I can't find example that generate `CoreV1Api` with client argument, I didn't believe it's possible.
It has solved now. 
If possible, can I know purpose of `DynamicKubernetesApi`?

**Comment by aespinosa** [comment]
If you look at https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesApi.java#L22-L25 the javadoc has it written there.

it's purpose is for when there is no Java POJO for let's say a CRD object.  But this can be used with vanilla Kubernetes resources too

**Comment by aespinosa** [comment]
Samples in https://github.com/kubernetes-client/java/wiki/3.-Code-Examples shows passing the `ApiClient` object in various `*Api` constructors.
