### ISSUE TITLE
import io.kubernetes.client.util.Config; not fould

### ISSUE THREAD

**Issue by powerpistn** [kubernetes-client/java#1988]
I use client.java and my steps are as follows
1）installation
`
git clone --recursive https://github.com/kubernetes-client/java

cd java

mvn install

`
2）Configure Pom.xml
`  
 

        <dependency>

            <groupId>io.kubernetes</groupId>

            <artifactId>client-java-api</artifactId>

            <version>14.0.1-SNAPSHOT</version>

        </dependency>

`

When I use the official example
![image](https://user-images.githubusercontent.com/43348528/141788815-47e6012d-c17f-4960-9886-0615e7cafb89.png)

It seems that util does not exist, how I can solve it？

**Comment by brendandburns** [comment]
In general, installing from source shouldn't be necessary (unless you really want to)

You can use:

```xml
    <dependency>
        <groupId>io.kubernetes</groupId>
        <artifactId>client-java-api</artifactId>
        <version>14.0.0</version>
    </dependency>
```

To pull the library from maven central.

If you really do want to build from source, you should look inside your `$HOME/.m2/...` directory to make sure that the package was actually installed there.

**Comment by powerpistn** [comment]
> In general, installing from source shouldn't be necessary (unless you really want to)
> 
> You can use:
> 
> ```
>     <dependency>
>         <groupId>io.kubernetes</groupId>
>         <artifactId>client-java-api</artifactId>
>         <version>14.0.0</version>
>     </dependency>
> ```
> 
> To pull the library from maven central.
> 
> If you really do want to build from source, you should look inside your `$HOME/.m2/...` directory to make sure that the package was actually installed there.

thank you,I change the pom.xml as follews
`
<dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>14.0.0</version>
        </dependency>
`
solve the problem.

**Comment by yue9944882** [comment]
/close

as it's solved
