### ISSUE TITLE
Some components are NOT generated Java codes from CustomResourceDefinition

### ISSUE THREAD

**Issue by ajtomato** [kubernetes-client/java#1990]
**Describe the bug**
I am using the following instructions to generate java codes from CRD. The CRD is attached. The component, RevisionSpec, is a object. No detailed information is generated. I am wondering whether this is normal. How to generate the detailed components.

[generate Java codes from CustomResourceDefinition](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md)

**Client Version**
master

**Kubernetes Version**
1.19

**Java Version**
Java 8

**To Reproduce**
[generate Java codes from CustomResourceDefinition](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md)

**Expected behavior**
The detailed components are generated 

**KubeConfig**
NA

**Server (please complete the following information):**
NA

**Additional context**
NA
[serving-crds-simple.txt](https://github.com/kubernetes-client/java/files/7543137/serving-crds-simple.txt)

**Comment by brendandburns** [comment]
I'm not sure I follow. What command are you running? What is the output of the command (e.g. stdout)?

What is the expected output and what are you not seeing?

In general, the CRD generation works, so we need more details to understand what is going wrong for you.

**Comment by ajtomato** [comment]
I use the following commands. And the generated code is attached. The expected result is that V1RevisionSpec.java is generated.
[V1Revision.zip](https://github.com/kubernetes-client/java/files/7543402/V1Revision.zip)

```shell
mkdir -p /tmp/crds && cd /tmp/crds

# Local generation
LOCAL_MANIFEST_FILE=/tmp/crds/serving-crds.yaml
LOCAL_MANIFEST_FILE=/tmp/crds/serving-crds-simple.yaml
mkdir -p /tmp/java && cd /tmp/java

docker run \
  --rm \
  -v "$LOCAL_MANIFEST_FILE":"$LOCAL_MANIFEST_FILE" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":"$(pwd)" \
  -ti \
  --network host \
  ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.4 \
  /generate.sh \
  -u $LOCAL_MANIFEST_FILE \
  -n dev.knative.serving \
  -p com.abchina.knative.client.openapi \
  -o "$(pwd)"
```

**Comment by yue9944882** [comment]
@ajtomato can you share us the actual status of your crd by command `kubectl get crd revisions.serving.knative.dev -o yaml | less`? i think something's wrong w/ the CRD's installation w/ your local cluster

**Comment by ajtomato** [comment]
> @ajtomato can you share us the actual status of your crd by command `kubectl get crd revisions.serving.knative.dev -o yaml | less`? i think something's wrong w/ the CRD's installation w/ your local cluster



I run the command on the cluster, it seems OK. Do you mean I should run this command on the local cluster on the laptop? If so, what is the command? I try the following commands. It seems not right.

```shell
docker run \
  --rm \
  -v "$LOCAL_MANIFEST_FILE":"$LOCAL_MANIFEST_FILE" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":"$(pwd)" \
  -ti \
  --network host \
  ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.4 \
  kubectl get crd revisions.serving.knative.dev -o yaml | less
```
