### ISSUE TITLE
CronJob as specified for `1.21` is not present in version `13.0.x`

### ISSUE THREAD

**Issue by kolstae** [kubernetes-client/java#1994]
**Describe the bug**
The `io.kubernetes.client.openapi.apis.BatchV1Api` doesn't contain the methods for cronjob-management e.g. `createNamespacedCronJob`

According to the [documentation](https://v1-21.docs.kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) - the `batch/v1` is the `apiVersion` to use. In version `14.0.0` of the client, the `BatchV1Api` contains the new methods.

**Client Version**
`13.0.x`

**Kubernetes Version**
`1.21.x`

**Comment by brendandburns** [comment]
Yes, apologies, we messed up when we released `13.0.x` and it is based on Kubernetes 1.20, not 1.21 as specified in the docs.

I updated the docs to accurately represent this.

You will need to use Kubernetes 14 to get these APIs.

**Comment by kolstae** [comment]
Sorry to reopen, but I felt this question belongs here.
What version should be used for kubernetes `1.21`?

**Comment by kolstae** [comment]
Never mind. My mistake, I thought the `batch/v1beta1`-api disappeared in `1.22` but it will be available through `1.24` it seems
