### ISSUE TITLE
DynamicKubernetesApi create method throws exception  for a resource even that is created on cluster and httpStatus is 200

### ISSUE THREAD

**Issue by thalleslmF** [kubernetes-client/java#1998]
**Describe the bug**
When calling the method create of DynamicKubernetesApi it throws a exception with a message that the resource was not found, but the resource is created on cluster and the httpStatus of the create operation is 200.

**Client Version**
e.g. `14.0.0`

**Kubernetes Version**
e.g. `1.21`

**Java Version**
e.g. Java 11

**To Reproduce**
1.Create a DynamicKubernetesApi object for a service
2. Call the method create
3. See the error

**Expected behavior**
Should not throw a exception 

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Linux
 - Cloud: Kind(Local cluster)

**Additional context**
the source code to reproduce https://github.com/thalleslmF/java-operator/blob/main/src/main/java/sdk/operator/App.java

**Comment by brendandburns** [comment]
What is the body of the response message? Any more details?

Examining the code, I don't see any way that this could happen with a status code of 200 unless there is an IOException (e.g. the server closes the connection before the response is fully returned) but it's possible there's a bug lurking in there that I can't see.

Would it be possible for you to run the code in a debugger and trace through where the problem is occurring?

**Comment by thalleslmF** [comment]
hey @brendandburns, it was my mystake, it's not about the 200 status. I found that the problem is that when i try to create a deployment resource it's not created and return a exception 404 not found. But the manifest is valid, so i tried the following code just to test and returns null even if a deployment exists on the namespace. 
```
 DynamicKubernetesApi dynamicApi = new DynamicKubernetesApi("", "apps/v1", "deployments", apiClient);
        var deploymentsList = dynamicApi.list();
```
I think that the problem is that dynamicapi is not recognizing the deployment resource

**Comment by thalleslmF** [comment]
Another test 
```
ApiClient apiClient = ClientBuilder.standard().build();
        var dynamicKubernetesObject = new DynamicKubernetesObject();
        dynamicKubernetesObject.setApiVersion("apps/v1");
        dynamicKubernetesObject.setKind("Deployment");
        var metadata = new V1ObjectMeta();
        metadata.setName("deployment-test");
        metadata.setNamespace("default");
        dynamicKubernetesObject.setMetadata(metadata);
        DynamicKubernetesApi dynamicApi = new DynamicKubernetesApi("", "apps/v1", "deployments", apiClient);
        var deploymentCreated = dynamicApi.create(dynamicKubernetesObject).throwsApiException().getObject();
        System.out.println(deploymentCreated.getRaw());
```

**Comment by thalleslmF** [comment]
throws this exception
```
Exception in thread "main" io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: v1
    code: 404
    details: class V1StatusDetails {
        causes: null
        group: null
        kind: null
        name: null
        retryAfterSeconds: null
        uid: null
    }
    kind: Status
    message: the server could not find the requested resource
    metadata: class V1ListMeta {
        _continue: null
        remainingItemCount: null
        resourceVersion: null
        selfLink: null
    }
    reason: NotFound
    status: Failure
```

**Comment by dddddai** [comment]
Looks like you misconfigured the api group, it should be:
```java
DynamicKubernetesApi dynamicApi = new DynamicKubernetesApi("apps", "v1", "deployments", apiClient);
```

**Comment by thalleslmF** [comment]
@dddddai i tried this , but i get a 405. Can you post a full example of creating a deployment? Also, the second parameter is named "apiVersion", it should not be only version if i cant put "apps/v1"?

**Comment by thalleslmF** [comment]
@dddddai thanks, it was my mistake
