### ISSUE TITLE
can not find `ExtensionsV1beta1Ingress` class in 14.0.0.

### ISSUE THREAD

**Issue by lin1005q** [kubernetes-client/java#2015]
**Describe the bug**

can not find `io.kubernetes.client.openapi.models.ExtensionsV1beta1Ingress` class in 14.0.0.

**Client Version**
e.g. `14.0.0`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 11

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by lin1005q** [comment]
The v1.22 release will stop serving the following deprecated API versions in favor of newer and more stable API versions:

* Ingress in the extensions/v1beta1 API version will no longer be served
  * Migrate to use the networking.k8s.io/v1beta1 API version, available since v1.14. Existing persisted data can be retrieved/updated via the new version.


> https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by lin1005q** [comment]
@yue9944882

**Comment by brendandburns** [comment]
As the blog states that API was removed in Kubernetes `1.22` The `14.0.0` release targets Kubernetes `1.22` so that API isn't in it.

If you need that API (and you are using an older Kubernetes version) you should use the `13.0.0` release.

**Comment by vaibhavs-uipath** [comment]
@lin1005q  what to use instead of ExtensionsV1beta1Ingress and ExtensionsV1beta1IngressList.
I am upgrading the client from v13 to v16. 
I have to change ExtensionsV1beta1Api, ExtensionsV1beta1Ingress and ExtensionsV1beta1IngressList.

Can you please point to the alternate classes?

**Comment by SheetalAtre** [comment]
Did you find any alternatives, I am searching for alternative classes/implementations for ::
import io.kubernetes.client.openapi.models.ExtensionsV1beta1HTTPIngressPath;
import io.kubernetes.client.openapi.models.ExtensionsV1beta1HTTPIngressRuleValue;
import io.kubernetes.client.openapi.models.ExtensionsV1beta1Ingress;
import io.kubernetes.client.openapi.models.ExtensionsV1beta1IngressBackend;
import io.kubernetes.client.openapi.models.ExtensionsV1beta1IngressRule;
import io.kubernetes.client.openapi.models.NetworkingV1beta1HTTPIngressPath;
import io.kubernetes.client.openapi.models.NetworkingV1beta1HTTPIngressRuleValue;
import io.kubernetes.client.openapi.models.NetworkingV1beta1Ingress;
import io.kubernetes.client.openapi.models.NetworkingV1beta1IngressBackend;
import io.kubernetes.client.openapi.models.NetworkingV1beta1IngressRule;

**Comment by vaibhavs-uipath** [comment]
I migrated as suggested here https://github.com/kubernetes-client/java/issues/2015#issuecomment-983188557
