### ISSUE TITLE
 Kuberentes C# Client, get allocated resources for a node

### ISSUE THREAD

**Issue by remus-corneliu** [kubernetes-client/java#2016]
I'm trying to get the allocated resources for a Node using Kuberenetes C# client but I cannot figure out where or how do I get the information.

I'm debugging a V1Node instance and I see in Status property Capacity and Allocatable (Defaults to Capacity), but I cannot see anything regarding left for use capacity or allocated capacity (CPU and RAM).

Some help would be much appreciated.

**Comment by brendandburns** [comment]
This repository is dedicated to the Java client. (though I work on both). Please file an issue in the [csharp](https://github.com/kubernetes-client/csharp) repository and we can continue the discussion there.

You may be interested in the implementation of Top for Nodes here:
https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTop.java#L98

You can probably implement something similar.

**Comment by remus-corneliu** [comment]
@brendandburns , thanks. I've created [this](https://github.com/kubernetes-client/csharp/issues/749)
