### ISSUE TITLE
Release 11.0.4

### ISSUE THREAD

**Issue by ryanjbaxter** [kubernetes-client/java#2041]
Can we release 11.0.4?

I would like to take advantage of this fix
https://github.com/kubernetes-client/java/pull/1963

**Comment by yue9944882** [comment]
@ryanjbaxter for sure, i'm working moving the release infra to github action from snapshots #2040 so that we can easily publish releases by pushing tags. i will send a 11.0.4 on the new release infra

/assign

btw how do you think about picking the commit to our major branch?

**Comment by ryanjbaxter** [comment]
Great thanks!

> btw how do you think about picking the commit to our major branch?

Sounds good would you like me to do that?

**Comment by yue9944882** [comment]
> Sounds good would you like me to do that?

yea by any chance can you pick it to master branch?

**Comment by ryanjbaxter** [comment]
@yue9944882 Here is the PR

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/runs/4734270953?check_suite_focus=true

@ryanjbaxter 11.0.4 release is published. @brendandburns the sad news is that our release job failed in the last step after the artifact is published. 

> remote: error: GH006: Protected branch update failed for refs/heads/release-11.        
remote: error: Required status check "cla/linuxfoundation" is expected.        
To https://github.com/kubernetes-client/java.git
 ! [remote rejected] release-11 -> release-11 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/kubernetes-client/java.git'

i opened https://github.com/kubernetes-client/java/pull/2069 to catch up with the automated release

**Comment by ryanjbaxter** [comment]
Great thanks!  We will update next week!

**Comment by yue9944882** [comment]
/close

the 11.0.4 is available
