### ISSUE TITLE
copy.copyFileToPod not working in 13.0.1

### ISSUE THREAD

**Issue by TheXs** [kubernetes-client/java#2059]
**Describe the bug**
ApiClient client = Config.defaultClient();
        CoreV1Api api = new CoreV1Api();
        api.setApiClient(client);
V1Pod foo = api.readNamespacedPod("chi-clickhouse-replicated-0-0-0", "database", null, false, false);
        List<V1Container> containers = foo.getSpec().getContainers();
        V1Container v1Container = containers.get(0);
        String ns = "database";
        String name = "chi-clickhouse-replicated-0-0-0";
        String from = "/opt/saas/bin/boot.sh";
        String to = "/home/script/boot.sh";
        Boolean execute = copy()
                .apiClient(client)
                .namespace(ns)
                .name(name)
                .container(v1Container.getName())
                .from(from)
                .toPod(to)
                .execute();
My code is here, when I execute it，it just started with no response, and when I go check the file in destPod, there was nothing. 
All my other Kubernetes-API are working fine execept the copy one.
Best regards!

**Comment by brendandburns** [comment]
Does `kubectl copy ...` work for you in the same environment?

**Comment by TheXs** [comment]
> Does `kubectl copy ...` work for you in the same environment?

Yes, it works.

**Comment by brendandburns** [comment]
Can you try using the `Copy` class directly:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/Copy.java

**Comment by roman-zadvornov** [comment]
I'm facing same problem here. The reason it is not working it creates a Process, but doesn't destroy it. I've copied a two methods from Copy class but have to manually destroy the created process. And it worked for me.

public void copyFileToPod(String namespace, String pod, Path srcPath, Path destPath) throws ApiException, IOException {
        Process process = execCopyToPod(namespace, pod, destPath);
        File srcFile = new File(srcPath.toUri());
        try (ArchiveOutputStream archiveOutputStream = new TarArchiveOutputStream(process.getOutputStream());
             FileInputStream input = new FileInputStream(srcFile)) {
            ArchiveEntry tarEntry = new TarArchiveEntry(srcFile, destPath.getFileName().toString());
            archiveOutputStream.putArchiveEntry(tarEntry);
            Streams.copy(input, archiveOutputStream);
            archiveOutputStream.closeArchiveEntry();
        } finally {
            process.getOutputStream().close();
            process.destroy();
        }
    }

    public Process execCopyToPod(String namespace, String pod, Path destPath) throws ApiException, IOException {
        String parentPath = destPath.getParent() != null ? destPath.getParent().toString() : ".";
        parentPath = parentPath.replace("\\", "/");
        Exec exec = new Exec();
        return exec.exec(namespace, pod, new String[]{"sh", "-c", "tar -xmf - -C " + parentPath}, null, true, false);
    }
