### ISSUE TITLE
Request Kubernetes Java sample code  to deploy yaml manifest file where kind is define Deploy(i.e. "kind: Deployment")  to Kubernetes cluster. 

### ISSUE THREAD

**Issue by baoquach14** [kubernetes-client/java#2085]
Hi All

Can you please help and provide me a sample code using Kubernetes-client Java code to deploy yaml manifest file where it contains kind is define Deployment (i.e. "kind: Deployment")  to Kubernetes cluster. 

I can only find create kind of a Pod and Service function only.
coreApi.createNamespacedPod()
coreApi.createNamespacedService(...)

Thank you for your help and support

Regards, Bao

**Comment by brendandburns** [comment]
The YAML example is here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-14/src/main/java/io/kubernetes/client/examples/YamlExample.java

You should be able to easily adapt that to create Deployment objects instead. There are no plans to extend that example to cover Deployments also.

**Comment by baoquach14** [comment]
Hi Brendan

Thank you very much for your reply

For my Kubernetes manifest of Kind: Deployment

 File inputYamlFile = new File(inputYamlFilePath);
 V1Deployment yamlApp = (V1Deployment) Yaml.load(inputYamlFile);

But I could not which function in CoreV1Api that accept V1Deployment as input parameter.

Thank you for your help

Regards, Bao
