### ISSUE TITLE
Support for GKE  cluster authentication

### ISSUE THREAD

**Issue by vins011** [kubernetes-client/java#2089]
**Describe the bug**

**Client Version**
e.g. `11.0.1`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by vins011** [comment]
Execute kubectl commands after GKE authentication

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/pull/1810 are you looking for the changes from this pull?
