### ISSUE TITLE
io.kubernetes:client-java-prometheus-operator-models:14.0.0 not published to Maven Central

### ISSUE THREAD

**Issue by franck102** [kubernetes-client/java#2090]
**Describe the bug**
client-java-parent is available from https://search.maven.org/artifact/io.kubernetes/client-java-parent/14.0.0/pom, and it references 
client-java-prometheus-operator-models:14.0.0, however that POM is only available at 10.0.2

![image](https://user-images.githubusercontent.com/1033413/149294957-f37b780c-1ea3-4c35-ac9d-a1ced38badd5.png)

**Client Version**
14.0.0

**Kubernetes Version**
n/a

**Java Version**
n/a

**To Reproduce**
Search for "io.kubernetes" on search.maven.org

**Expected behavior**
All modules declared in client-java-parent available from Central at the latest version.

**Comment by brendandburns** [comment]
We have been kind of inconsistent about how we handled those modules. They're not really tied to a specific Kubernetes release and so they really should probably be released separately (but as you can see with `10.0.2` we have occasionally pushed them as part of the release)

Is this causing you a problem right now? I'm trying to gauge the urgency of coming up with a solution.

@yue9944882 what do you think we should do here? It feels like we should pull them out of the top-level `pom.xml` and maybe place them in their own directory with it's own top-level pom (or even a separate project under `github/kubernetes-client`?

**Comment by franck102** [comment]
Nothing urgent, I cloned the 14.0.0 version of the module and I built it locally.

Somehow the documented approach of generating the source from an openapi.Json pulled from K8s fails for me with missing classes.

**Comment by yue9944882** [comment]
generally its not recommended to import the parent model, just importing the specific client-sdk module should work. @brendandburns these contrib modules are merely a few java models generated from third-party CRD. i agree we should move them out of root pom. on the other hand i think it's valuable to maintain more and more pre-generated models from well-known CRDs. 

> maybe place them in their own directory with it's own top-level pom

oddly my IDE wont index the nested dangling pom project.. i wonder if we can declare these modules as "optional" so users wont download them until the generated models are actually referenced.
