### ISSUE TITLE
Propose release: need release with fix for pod exec WebSockets bug

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#210]
@brendandburns,

Any chance we could please get a 1.0.0-beta3 release including the fix for #180?  While we can test with local changes, since we're also an open-source project, I can't commit a modified version of WebSockets.java to our repository.  Thanks in advance.

Any word on what the release roadmap will be?

**Comment by brendandburns** [comment]
Sure, I can cut a new release this weekend...

**Comment by rjeberhard** [comment]
Thanks!  I appreciate it.  Just a heads-up, I had a PR for Exec that would support reading non-zero exit codes and Exec$ExecProcess.waitFor(long, TimeUnit); however, I've temporarily retracted it because the API server always returns 400 bad request when stdin=false.  I need to find someone who understands the server-side validation.

**Comment by greglanthier** [comment]
I _think_ a problem I stumbled on this evening with port-forwarding (see this [comment](https://github.com/kubernetes-client/java/issues/180#issuecomment-374082291)) might be resolved by PR #202.  I'd be keen to try out a new release including PR #202 when its available.

**Comment by brendandburns** [comment]
Ok, this has been staged out to sonatype.  It may take a little while before it is replicated to maven central.
