### ISSUE TITLE
Update wiki - outdated information across wiki

### ISSUE THREAD

**Issue by wideocean** [kubernetes-client/java#2105]
I noticed that the wiki is quite outdated on several sub-pages.

Examples:
- Installation: proposed version to use is still version 10
- Code Examples: all links there lead to 404

Suggestion: Check the wiki and replace outdated information.

**Comment by H1manshu-Soni** [comment]
Hey @wideocean I am a beginner trying to fnid some issues to fix and I think this wil be a good issue to start with, can you point me to the website and the resources required.
-Himanshu

**Comment by wideocean** [comment]
@H1manshu-Soni 
The wiki can be found here: https://github.com/kubernetes-client/java/wiki 

Code examples are already fixed it seems.
Installation sub page is still outdated (minor issue): https://github.com/kubernetes-client/java/wiki/1.-Installation 

If you think you can fix and update the page, go for it.

**Comment by H1manshu-Soni** [comment]
Hey @wideocean I am not sure if I understand you correctly but what exactly do you want to me to fix this might be a dumb question but i just dont know what to do there I am sorry for the trouble.

**Comment by wideocean** [comment]
@H1manshu-Soni 
The installation sub page states version 10 while the latest published release is version 14.

**Comment by H1manshu-Soni** [comment]
How can I edit the wiki page I am really sorry but I am very new to this stuff.

**Comment by H1manshu-Soni** [comment]
Hey @wideocean I have fixed the version problem is there anything else you want me to do?
Thanks at first it felt hard but with your help it made this much easier!

**Comment by harshitasao** [comment]
Hi @yue9944882, As indicated in [comment](https://github.com/kubernetes-client/java/issues/2105#issuecomment-1054596420) I've made the required changes to my forked wiki. If that appears to be correct, please merge it, and if any changes are needed, please let me know. 
Link to my forked wiki - https://github.com/harshitasao/java/wiki/1.-Installation
Thank you.

**Comment by yue9944882** [comment]
thanks for reporting the outdated content in wiki, i just refreshed them. leaving this thread open for a few days in case i missed anything.

**Comment by iamshakkib** [comment]
Hi I too want to contribute in open source using Java, Previously have some intern exp. how can I do it ?

**Comment by brendandburns** [comment]
@iamshakkib apologies for the (very) delayed response, but if you are still looking to contribute, there are several issues labelled `good-first-issue`

https://github.com/kubernetes-client/java/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
