### ISSUE TITLE
Handling of token expiration 

### ISSUE THREAD

**Issue by Dimylo** [kubernetes-client/java#2110]
Hello,
I'm currently checking possible impacts of BoundServiceAccountTokenVolume feature in my application. Regarding the expiration of tokens, is there a handling from the API about the time where there's no connection between the API and the service accounts or should this case be handled by the application?

**Comment by brendandburns** [comment]
Not sure I fully understand the question. This client currently loads the token from disk once into memory, if that token is invalidated, the client needs to be restarted to reload the token. It's possible that there are improvements we could do here (similar to what we do for time-bound tokens provided by an `exec` provider) but currently that's not implemented.
