### ISSUE TITLE
Creating Namespaces with DynamicKubernetesApi

### ISSUE THREAD

**Issue by apex256** [kubernetes-client/java#2114]
Is there any support for creating v1/Namespace objects with a DynamicKubernetesApi? I end up getting a 404 response back and that may be due to how the DynamicKubernetesApi builds the path for an API call in a generic fashion that the v1/Namespace object's API path does not seem to support.

What would be the optimal way of handling v1/Namespace objects with a DynamicKubernetesApi object? The goal for me is to be able to emulate what **"kubectl apply -f"** does with only needing the path to a configuration file, and also being able to support custom objects. Am I missing something here with using the DynamicKubernetesApi, or is the only approach to just try and determine the object is a v1/Namespace beforehand and use a Corev1Api object.

Running on 12.0.0 here if that helps.

Thanks in advance

**Comment by yue9944882** [comment]
let me try reproduce this in my local environment

**Comment by apex256** [comment]
For what it's worth I get the same thing trying to create v1/PersistentVolume objects through the DynamicKubernetesApi, the commonality is that they are both not namespaced objects, is there a way to use a generic API such as the DynamicKubernetesApi to create non namespaced objects? Assuming that's what is causing these 404s.

**Comment by apex256** [comment]
Seems like I've been trying to call the method signature (Namespace, DynamicKubernetesObject, CreateOptions) with a null/empty string namespace thinking that would do the job. That method signature is only for Namespaced objects, using (DynamicKubernetesObject, CreateOptions) did the trick for me.

Closing this, thanks all.
