### ISSUE TITLE
Support setting the terminal size

### ISSUE THREAD

**Issue by thecrazzymouse** [kubernetes-client/java#2122]
**Describe the bug**
The current exec API does not allow to set the size of the terminal or update the size of the terminal at a later time. When Kubectl command line is used it sends a message to update the size of the terminal. The Java API does not have this functionality.

**Client Version**
13.0.0

**Comment by thecrazzymouse** [comment]
It should be possible to access the resize stream through this API

```
  public Future<Integer> exec(
      String namespace,
      String podName,
      Consumer<IOTrio> onOpen,
      BiConsumer<Integer, IOTrio> onClosed,
      BiConsumer<Throwable, IOTrio> onError,
      Long timeoutMs,
      boolean tty,
      String... command)
      throws IOException
```

**Comment by brendandburns** [comment]
We'd be happy to take a PR to add this functionality.

**Comment by ming0804** [comment]
stty cols 190 rows  50  可以先用这个临时解决下
