### ISSUE TITLE
io.kubernetes.client.custom.Quantity isn't serializable/deserializable back and forth

### ISSUE THREAD

**Issue by mg183964** [kubernetes-client/java#2128]
**Describe the bug**
I have a requirement to get Pod in json format from kube api in a kotlin project, and deserialize it into V1Pod object. After doing some processing, V1Pod obj will again be serialized and sent as an update to kube api. But when try to deserialize it second time into V1Pod object, the io.kubernetes.client.custom.Quantity is unable to be decoded.

**Client Version**
`14.0.0`

**Kubernetes Version**
`1.19.3`

**Java Version**
Java 8

**To Reproduce**
1. Use this testPod.json:
`{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "someservice"
    },
    "spec": {
        "containers": [
            {
                "env": [
                    {
                        "name": "SOME_ENV_VAR",
                        "valueFrom": {
                            "resourceFieldRef": {
                                "containerName": "someservice",
                                "divisor": "1Mi",
                                "resource": "requests.memory"
                            }
                        }
                    }
                ],
                "image": "docker.sometestorg.com/sometestrepo/someimage:sometag",
                "name": "someservice",
                "resources": {
                    "limits": {
                        "cpu": "1100m",
                        "memory": "2Gi"
                    },
                    "requests": {
                        "cpu": "100m",
                        "memory": "750Mi"
                    }
                }
            }
        ]
    }
}
`

2. Run this unit test:
`
   @Test
    fun testSerializationDeserializationOfPodObject() {
        var podObj = Json.decodeValue<V1Pod>(readResourceFileAsText("testPod.json"))
        Assertions.assertThat(podObj).isNotNull
        podObj.metadata?.namespace = "some-namespace"
        val podJson = Json.encode(podObj)
        Assertions.assertThat(podJson).isNotEmpty
        podObj = Json.decodeValue(podJson)
        Assertions.assertThat(podObj).isNotNull
    }

   private fun readResourceFileAsText(file: String): String {
            return this::class.java.getResource(file)?.readText()
                ?: throw IllegalStateException("Cannot find file $file")
   }
`
3. The line of code ` podObj = Json.decodeValue(podJson)` throws this error:
`Failed to decode:Cannot construct instance of `io.kubernetes.client.custom.Quantity` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"apiVersion":"v1","kind":"Pod","metadata":{"name":"someservice","namespace":"some-namespace"},"spec":{"containers":[{"env":[{"name":"SOME_ENV_VAR","valueFrom":{"resourceFieldRef":{"containerName":"someservice","divisor":{"number":1048576,"format":"BINARY_SI"},"resource":"requests.memory"}}}],"image":"docker.sometestorg.com/sometestrepo/someimage:sometag","name":"someservice","resources":{"limits":{"cpu":{"number":1.100,"format":"DECIMAL_SI"},"memory":{"number":2147483648,"format":"BINARY_SI"}},"[truncated 113 chars]; line: 1, column: 223] (through reference chain: io.kubernetes.client.openapi.models.V1Pod["spec"]->io.kubernetes.client.openapi.models.V1PodSpec["containers"]->java.util.ArrayList[0]->io.kubernetes.client.openapi.models.V1Container["env"]->java.util.ArrayList[0]->io.kubernetes.client.openapi.models.V1EnvVar["valueFrom"]->io.kubernetes.client.openapi.models.V1EnvVarSource["resourceFieldRef"]->io.kubernetes.client.openapi.models.V1ResourceFieldSelector["divisor"])`

**Expected behavior**
The Pod object should be able to serialize/deserialize without any issue.

**KubeConfig**
N/A

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by mg183964** [comment]
It works with Gson mapper but not with jackson

**Comment by yue9944882** [comment]
yea the round-tripping of the models in this repo only works for gson serializer, am not sure if there's a way to convert gson custom codec to jackson's.

**Comment by brendandburns** [comment]
I'm going to close this as out of scope/will not fix. If someone wants to add a deserialization handler for Jackson + Quantity, we'd take the PR, but it's not currently a requirement for this library. If you want to deserialize correctly for now you need to use Gson.

The quantity formatter for Gson is here:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/QuantityFormatter.java
