### ISSUE TITLE
Cannot write Pod logs to String

### ISSUE THREAD

**Issue by p01K** [kubernetes-client/java#2137]
**Describe the bug**
Hello,

When I tried the following code
~~~~
        ApiClient client = ClientBuilder.cluster().build();
        Configuration.setDefaultApiClient(client);
        CoreV1Api api = new CoreV1Api();
        PodLogs logs = new PodLogs();

        V1Pod pod = api.readNamespacedPod("podId", "default", "false");
        var is = logs.streamNamespacedPodLog(pod);
        Streams.copy(is, System.out, true);
~~~~

The pod logs are printed correctly in stdout,
however when I try to user another OutputStream to
write the logs stream to a string, like 
~~~~
            ByteArrayOutputStream targetStream = new ByteArrayOutputStream();
            Streams.copy(is, targetStream, false);
~~~~
the program blocks.

Any ideas ?

**Client Version**
`14.0.0`

**Kubernetes Version**
`v1.22.6`

**Java Version**
`Java 17`

**Server (please complete the following information):**
 - OS: Linux

**Comment by gfvirga** [comment]
I ran into the same error. I believe there is a bug in `Streams.copy()` that hangs the connection when the buffer isn't full.
I fixed it by copying the function and adding `out.flush()` inside the while loop.

PS: this is in kotlin
```
return StreamingResponseBody { outputStream ->
            // Streams.copy(`is`, outputStream)
            val buf = ByteArray(1024)
            var length: Int
            while (`is`.read(buf).also { length = it } > 0) {
                outputStream.write(buf, 0, length)
                outputStream.flush()
            }
            outputStream.flush()
            outputStream.close()
        }
```

**Comment by p01K** [comment]
I tried the following
~~~~
        byte[] data = new byte[16384];
        int nRead;
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        while((nRead=is.read(data))>=0){
            buffer.write(data, 0, nRead);
            buffer.flush();
        }
~~~~

and after it reads some bytes (they seemed to be all the pod logs up to that time), the final read just blocks

**Comment by gfvirga** [comment]
Is it blocking the final log lines of a running pod?

Did you try `buffer.flush()` after the while loop too? I don't know why, but that way worked for me.
This is where I copycat the code from.
https://github.com/kubernetes-client/java/blob/9360c35afa65a4cc79624eaac7dc1d6f540ff235/util/src/main/java/io/kubernetes/client/util/Streams.java#L24

**Comment by brendandburns** [comment]
I'm going to close this issue, because I don't believe this is a problem with this client.

In my experience you do need to flush many streams (especially buffered streams) to ensure all bytes get written to disk/file.
