### ISSUE TITLE
exec java seems not work.

### ISSUE THREAD

**Issue by augustshen** [kubernetes-client/java#2143]
when I start a pod, I want to start some web service in it. so I wirte a function
	private void kunExec(String ns, String podname, String[] cmd) {
		try {
			Exec exec = new Exec();
			Process proc = exec.exec(ns, podname, cmd, null, false, false);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			System.out.println(e.getMessage());
			e.printStackTrace();
		} catch (ApiException e) {
			// TODO Auto-generated catch block
			System.out.println(e.getMessage());
			e.printStackTrace();
		} catch (UnsupportedOperationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

it works well when start redis-server
	private void startRedis(String ns, String podname) {
		String[] args = new String[] { "nohup", "redis-server"};
		kunExec(ns, podname, args);
	}

but when I want to start some java service, it seems not work.
	private void startBlockchainapi(String ns, String podname) {
		String[] args;
		args = new String[] { "/cochain/blockchainapi/start.sh" };
		kunExec(ns, podname, args);
		args = new String[] { "nohup", "java", "-Xms256m", "-Xmx512m", "-Djava.compiler=NONE",
				"-Dloader.path=/cochain/blockchainapi/lib", "-jar", "/cochain/blockchainapi/blockchainapi.jar"};
		kunExec(ns, podname, args);
	}
start the java in shell script or just write in code , both not work.
but if in shell cmd
kubectl exec -n namespace podname -- /cochain/blockchainapi/start.sh  will work.
kubectl exec -n namespace podname -- nohup java .................................. also will work.

so why?  I am using the 10.0.1 version, I have tried 12.0.0, but can't compile, seems the inface has some change, so I back to 10.0.1, any suggestion?

**Comment by brendandburns** [comment]
My guess is that using a shell is setting up a bunch of things like `$PATH` variables and the like, but I'm not certain.

I'm going to close this issue because I believe the client is working as expected, since several other commands work. I believe there's an issue inside your container.

Please use the `/reopen` command if you determine that there is a problem with the client.
