### ISSUE TITLE
Error decode for generated OffsetDateTime filed in CRD

### ISSUE THREAD

**Issue by wangcanfengxs** [kubernetes-client/java#2152]
**Describe the bug**
When I generate a CRD model and use a `timestamp` filed like `.metadata.creationTimestamp`. But the `timestamp` filed type is `OffSetDateTime`, it cause error when I use k8s api to get an object. 

**Client Version**
`10.0.1`

**Kubernetes Version**
`1.18.19`

**Java Version**
e.g. Java 8

**To Reproduce**
1. Definition a CustomResourceDefinitioin
2. Generate a model
3. Use this model to get an object from k8s.
4. Error when gson fromJson

The reason for this problem is no Adapter for OffsetDateTime?

**Comment by brendandburns** [comment]
How are you instantiating the Gson object? If you use the one in the client library, I believe it should work. What is the exception trace you are seeing?
