### ISSUE TITLE
Implement support to client certificate auth using a exec command in KubeConfig

### ISSUE THREAD

**Issue by pgalache** [kubernetes-client/java#2157]
Currently the library does not support authentication using client certificate when that certificate is the output of an exec command. The exec command always expects a token.

There is a comment in [code](https://github.com/kubernetes-client/java/blob/f9f02728a2b72a1ac7eb014ecb45b6d2a44f4d48/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L284) indicating that KubeconfigAuthentication is not prepared for dynamic certs.

**Client Version**
e.g. `14.0.0`

** Kubernetes Version **
1.22.5

** Java Version **
Java 16

** To Reproduce **
Try to authenticate with a KubeConfig that has an exec command that returns client certificates.

** Expected behavior **
Auth works OK.

** Server (please complete the following information): **

OS: Linux
Cloud AWS

**Comment by brendandburns** [comment]
We would gladly take PRs for this, but currently no plans to implement it.

**Comment by pgalache** [comment]
Close as it's implemented in #2170
