### ISSUE TITLE
Is there any API for creating yaml in batches？

### ISSUE THREAD

**Issue by nuclearwu** [kubernetes-client/java#2164]
Is there any API for creating yaml in batches (similar to kunectl create -f xxxx.yaml), without considering splitting a yaml (including one or more ConfigMap, Service, Deployment) containing different types and multiple resources into a single resource create? Does java-client-extended have such a function? Are there any relevant examples?

**Describe the bug**

**Client Version**
e.g. `11.0.1`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
Look at `Yaml.loadAll(...)` https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Yaml.java#L159

That should do what you want.

**Comment by brendandburns** [comment]
I realized that you might have been asking about creating, not just loading. And the answer to that is 'no' you will need to iterate across the list created by `loadAll(...)` and create each object individually.

fwiw, this is what `kubectl` does under the hood also.

**Comment by nuclearwu** [comment]
I got it, thanks
