### ISSUE TITLE
Informer health monitoring and error callback

### ISSUE THREAD

**Issue by mamachanko** [kubernetes-client/java#2166]
When creating and starting informers with the `SharedIndexInformerFactory` I would like to get insight on the health of the informers. As far as I can tell, once started, it's a black box.

Ideally, I would be able to register code to act on error conditions.

**Comment by brendandburns** [comment]
One of the constructors for SharedIndexInformerFactory takes an exception handler

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java#L155

That should enable you to handle errors.

**Comment by mamachanko** [comment]
I missed that. Thanks @brendandburns 🙇🏻
