### ISSUE TITLE
What's the resync behaviour of a `SharedIndexInformer` with a 0 ms resync period?

### ISSUE THREAD

**Issue by mamachanko** [kubernetes-client/java#2167]
The `SharedIndexInformerFactory.sharedIndexInformer(callGen, apiType, apiListType)` defaults to a _0 ms_ resync period.

https://github.com/kubernetes-client/java/blob/5cd447eac861de53b902cd85b2fcd8dc3fa83789/util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java#L104

Does that mean it never resyncs or does it assume the _default_ resync period? If it's the latter, I struggle to determine its value.

**Comment by dddddai** [comment]
It means the former

**Comment by yue9944882** [comment]
yes 0 means never resync, which is aligning to the client-go informer's behavoir

**Comment by mamachanko** [comment]
Thank you @dddddai @yue9944882 !
