### ISSUE TITLE
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to service-name:80 [service-name/10.96.116.239] failed: connect timed out

### ISSUE THREAD

**Issue by I-want-to-knowledge** [kubernetes-client/java#2169]
# **Describe the bug**
Service discovery error

# **Client Version**
e.g. `13.0.2`

# **Kubernetes Version**
e.g. `1.20.+`

# **Java Version**
e.g. Java 11.0.5

# **To Reproduce**
## 1---------------
spring-boot-starter-parent:2.6.4
spring-cloud-dependencies:2021.0.1
    spring-boot-starter-web
    spring-cloud-starter-openfeign
    spring-boot-starter-actuator
    feign-httpclient (io.github.openfeign)
    spring-cloud-starter-kubernetes-client-all
## 2------------------
--Dockerfile--
...
java -Djdk.tls.client.protocols=TLSv1.2 -jar  /*.jar
...

## 3------------------
![image](https://user-images.githubusercontent.com/27717836/158505161-d7c53c61-ab6c-4b1f-bbe0-6ea44f759d91.png)
![image](https://user-images.githubusercontent.com/27717836/158505244-7bc2db90-04fa-4534-91cf-8e9a9f730c17.png)
![image](https://user-images.githubusercontent.com/27717836/158505374-1c37ab09-f08a-4ac8-9a1b-19f44398f338.png)

# **Expected behavior**
Can request 'caas-core-svc', @ feignclient when no URL is configured！
Automatic service discovery！

# **KubeConfig**
ordinary system

# **Server (please complete the following information):**
 - OS: [centos7+]
 - Environment [cluster k8s]
 - Cloud [e.g. Azure]

# **Additional context**
Or provide the implementation principle document of service discovery

**Comment by I-want-to-knowledge** [comment]
e.g. Java 11.0.11 is normal

**Comment by I-want-to-knowledge** [comment]
使用discoveryClient.getInstances("caas-core-svc")得到如下结果；
-------------------------------------------------
[KubernetesServiceInstance{instanceId='9f120881-4176-48b4-bcfc-678ae8f4a64d', serviceId='caas-core-svc', host='100.64.196.216', port=8080, uri=http://100.64.196.216:8080, secure=false, namespace=caas-system, cluster=null, metadata={null=8080, adp.aliyuncs.com/component-version=1.5.3-0, adp.aliyuncs.com/component-app-version=1.5.3, adp.aliyuncs.com/application-name=quota-test, adp.aliyuncs.com/component-name=aecp, adp.aliyuncs.com/component-type=aecp, adp.aliyuncs.com/application-namespace=default, adp.aliyuncs.com/component-namespace=acs-system, adp.aliyuncs.com/component-provider=}}]
---------------------------------------------------
![image](https://user-images.githubusercontent.com/27717836/158529442-bad6cc76-db28-437a-8e2f-b0bc7a345450.png)
其中key是null，Jackson解析是会报错，是不是这个原因导致的？？

**Comment by brendandburns** [comment]
I don't think this is a client error. But more importantly this looks like it is running in a unit test?

We need much more detail on the environment and the stacktraces to see if there is a problem here in the client, but I suspect that there's a problem with your server.
