### ISSUE TITLE
java api for kubernetes 1.23

### ISSUE THREAD

**Issue by gladhiola** [kubernetes-client/java#2179]
Hi Team,
I couldn't find any related information about kubernetes-client for kubernetes 1.23 (https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/)
Could you give some information related to this topic? Will there be a java client for 1.23 and when will it be available?
Thanks,
BR,
Melinda

**Comment by yue9944882** [comment]
@gladhiola we will schedule a new release for 1.23 soon, hopefully this week or next, thanks

**Comment by brendandburns** [comment]
@yue9944882 do you want me to cut the release?

**Comment by yue9944882** [comment]
@brendandburns i just cut the release this time b/c this is the first time we bump a major release via the action. note that we will need to manual checkout and push a release branch upon every major release, plz TAL at https://github.com/kubernetes-client/java/pull/2185

**Comment by yue9944882** [comment]
15.0.0 is out

/close
