### ISSUE TITLE
Avoid using internal `gson` packages for better modularity

### ISSUE THREAD

**Issue by rotty3000** [kubernetes-client/java#2186]
**Describe the bug**
Kubernetes Java client is trying to be a OSGi bundle which I admire and wish to assist with. However, there are several small issues to resolve. The first couple issues are breaking the concept of isolation between implementations.

In this specific case the client uses internal `gson` package to handle ISO 8601 dates.

**Client Version**
14.0.1 (and earlier)

**Kubernetes Version**
N/A

**Java Version**
N/A

**To Reproduce**
Try to resolve kubernetes java client in OSGi.

**Expected behavior**
kubernetes java client resolves in OSGi.

**KubeConfig**
N/A

**Server (please complete the following information):**
 - OS: any
 - Environment: OSGi
 - Cloud: N/A

**Additional context**
I am preparing a PR to solve the issue.

**Comment by brendandburns** [comment]
We're open to this, but please be aware that much of this library is generated code (most of the contents of `kubernetes`) so if you plan on making changes there, they need to be made in the code generator, not the checked-in source code.

**Comment by brendandburns** [comment]
Thanks, the generated code starts here:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/JSON.mustache

**Comment by rotty3000** [comment]
Given the PR is merged I'm assuming this can be closed.

But before that happens I wanted to close the loop on the issue of `JSON` being ignored from being generated. In order to go back to being generated we need to retroactively discover all the changes that were made since it was ignored.

If someone can explain where ignore is set I might be able to figure out which commit added it and any changes that occurred since then and see how much we need to port up to the generator. Not promising anything but that's how I would proceed.

**Comment by rotty3000** [comment]
.. found it `kubernetes/.openapi-generator-ignore` thx. closing now.
