### ISSUE TITLE
Question: API health endpoints?

### ISSUE THREAD

**Issue by johnflavin-fw** [kubernetes-client/java#2189]
I am implementing a java application to connect to a kubernetes cluster using this client library. Among other endpoints, I would like to connect to the [Kubernetes API health endpoints](https://kubernetes.io/docs/reference/using-api/health-checks/). But I cannot see how to connect to these endpoints using this client.

Can anyone show me an example of how to do this?

**Comment by brendandburns** [comment]
These endpoints are not formally part of the API definition that most of this client is generated from. You will have to write custom code to do this.

You're going to need to use the `ApiClient.execute(...)` method similar to what the generic client does here:
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L797

If you do end up implementing this, we'd be happy to take a PR to add support.
