### ISSUE TITLE
V1PodReadinessGate().conditionType only accepts preset enums in v15.0.0

### ISSUE THREAD

**Issue by abelsromero** [kubernetes-client/java#2192]
**Describe the bug**
`conditionType` has been changed to enum `V1PodReadinessGate.ConditionTypeEnum` in v15.0.0 which prevents from using custom checks.
In previous versions it was a String which allowed to set the name of the check directly, without it anyone using a custom readiness check is forced to stay on v14.x.

**Client Version**
v15.0.0

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
Java 11

**To Reproduce**
This is no longer valid.
```
new V1PodReadinessGate()
.conditionType("MyGate")
```

**Expected behavior**
An alternative to be able custom gates should be provided, maybe using something different than an enum or having another setter method.

**KubeConfig**
n/a

**Server (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by yue9944882** [comment]
https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.23/api/openapi-spec/swagger.json

it seems that the openapi-spec on 1.23 release branch is broken, in the past it's just a plain string type, but since 1.23 it became an enum. will send a fix to that branch. thanks for reporting this.

**Comment by yue9944882** [comment]
UPDATE: see the bug report at https://github.com/kubernetes/kubernetes/pull/105057#issuecomment-1083448820, the fix is https://github.com/kubernetes/kubernetes/pull/105057#issuecomment-1083450656

**Comment by yue9944882** [comment]
this will be fixed by https://github.com/kubernetes-client/java/pull/2212

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/pull/2217

published 15.0.1, the new release should be available in the central registry w/i 48 hrs.

/close
