### ISSUE TITLE
Error while creating Kubernetes Job

### ISSUE THREAD

**Issue by mmmaks** [kubernetes-client/java#221]
When creating Kubernetes Job, with yaml : 
    `  kind: Job`
    `apiVersion: batch/v1`
Error : 
> java.io.IOException: Unknown apiVersionKind: batch/v1/Job known kinds are:

and then a list of known kinds.
But [here](https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#job-v1-batch) shows `apiVersion: batch/v1` for job.

Also, when I try to create Job with yaml : 
`  kind: Job`
   `apiVersion: v1`

Error : 
`io.kubernetes.client.ApiException: Bad Request
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.BatchV1Api.createNamespacedJobWithHttpInfo(BatchV1Api.java:160)
	at io.kubernetes.client.apis.BatchV1Api.createNamespacedJob(BatchV1Api.java:144)`

**Comment by brendandburns** [comment]
Yeah, somehow we're losing the API group here...

@mbohlool do you know how we are doing the API group in the swagger?

Why does `Apps` and `Extensions` get generated into the object name but not `Batch`?

**Comment by brendandburns** [comment]
I think the tl;dr; is that we may need to do more work on API discovery here.  Probably need to download the swagger spec from the server.  *sigh*

For now you will want to call:

```java
Yaml.addModelMap("batch/v1", V1Job.class)
```

Somewhere in your code before you try to load that object from YAML that should manually specify the mapping we should have discovered auto-magically.

**Comment by mmmaks** [comment]
ok, Thanks

**Comment by iming0319** [comment]
@brendandburns 
What I meet is "Unknown apiVersionKind: apps/v1beta1/Deployment known kinds are:...."
And I got a know kind "apps/v1/beta1Deployment".

so, I think this issue is related to the method initModelMap(), in Yaml.java
We shoud edit it 
form:
if (name.startsWith("AppsV1")) {
      return "apps/v1";
}
if (name.startsWith("AppsV1beta1")) {
    return "apps/v1beta1";
}
to:
if (name.startsWith("AppsV1beta1")) {
    return "apps/v1beta1";
}
if (name.startsWith("AppsV1")) {
    return "apps/v1";
}

**Comment by brendandburns** [comment]
I believe this was fixed by #246 please re-open if it is still a problem.

Thanks!
