### ISSUE TITLE
Outdated user agent string

### ISSUE THREAD

**Issue by johnflavin-fw** [kubernetes-client/java#2213]
**Describe the bug**
On initialization the `io.kubernetes.client.openapi.ApiClient` sets a user agent string hard-coded with an old snapshot version.

```java
setUserAgent("Kubernetes Java Client/13.0.1-SNAPSHOT");
```

See https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L106

**Client Version**
`14.01`

**Java Version**
Java 7

**Expected behavior**
If the user agent is to include the client version, the string should be automatically kept up-to-date as the version changes.

**Comment by yue9944882** [comment]
/kind bug

i think we need to figure out a way to automatically refresh the version in the user-agent

**Comment by brendandburns** [comment]
@yue9944882 we should probably lift the hold on re-generating this file with each release...
