### ISSUE TITLE
How to use client create VerticalPodAutoscaler resource?

### ISSUE THREAD

**Issue by qhh0205** [kubernetes-client/java#2226]
hi, guys, does anyone know how to use this client create VerticalPodAutoscaler resource? At present, the client doesn't seem to support it, but that support HPA creation. Do you have any suggestions on the creation of VPA? thx!

**Comment by brendandburns** [comment]
Vertical Pod Autoscaling is an extension to the Kubernetes API, you will need to generate the client objects yourself using the instructions here:

https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model
