### ISSUE TITLE
Error in Json Mapping for delete service reasponse body.

### ISSUE THREAD

**Issue by fuzails** [kubernetes-client/java#2231]
Kubectl versions:
`
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
`

Jaca client version 15.0.0

When calling the API io.kubernetes.client.openapi.apis.CoreV1Api#deleteNamespacedService the response that is returned from the api specifies status as a string as per below

`
{
	"kind": "Status",
	"apiVersion": "v1",
	"metadata": {},
	"status": "Success",
	"details": {
		"name": "harness-service-11",
		"kind": "services",
		"uid": "7c263c2f-e43c-4b69-8933-916427790b5d"
	}
}
`

The returnType passed into the API io.kubernetes.client.openapi.ApiClient#deserialize is specified as io.kubernetes.client.openapi.models.V1Service. This results in the response body not being serialized and an ApiException being thrown with the following message:

**Expected BEGIN_OBJECT but was STRING**

I believ the reason being that as per the json response body above status is returned as a string wheras io.kubernetes.client.openapi.models.V1Service is expecting a io.kubernetes.client.openapi.models.V1ServiceStatus type.

**Comment by brendandburns** [comment]
I think that this is an error in the generated OpenAPI specification for the Kubernetes API (or in the code generator)

**Comment by fuzails** [comment]
Yep apologies, just saw it under known issues, somehow I missed the known issues when I was looking to see if this has already been reported.

Thanks
