### ISSUE TITLE
Support Matrix Document Update

### ISSUE THREAD

**Issue by DanielYWoo** [kubernetes-client/java#2233]
**Describe the bug**
The compatibility matrix does not have the latest version 15.0.x.
https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility

**Client Version**
`15.0.1`

**Kubernetes Version**
`N/A`

**Java Version**
N/A

**To Reproduce**
N/A

**Expected behavior**
The matrix needs to be updated.

**KubeConfig**
N/A

**Server (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by brendandburns** [comment]
This appears to now be fixed.

![image](https://user-images.githubusercontent.com/5751682/165800453-7a934b95-0e42-4986-8cd9-ea04d773b3f2.png)

**Comment by DanielYWoo** [comment]
lightening speed, thanks
