### ISSUE TITLE
Possible deserialization issue

### ISSUE THREAD

**Issue by oldshaghat** [kubernetes-client/java#2244]
Invoking `CoreV1Api`'s `listPodForAllNamespaces` method with all null arguments results in an illegal state exception : 	
	 * Not a string (through reference chain: io.kubernetes.client.openapi.models.V1PodList["items"]->java.util.ArrayList[3]
		 * ->io.kubernetes.client.openapi.models.V1Pod["spec"]
		 * ->io.kubernetes.client.openapi.models.V1PodSpec["containers"]
		 * ->java.util.ArrayList[0]
		 * ->io.kubernetes.client.openapi.models.V1Container["livenessProbe"]
		 * ->io.kubernetes.client.openapi.models.V1Probe["httpGet"]
		 * ->io.kubernetes.client.openapi.models.V1HTTPGetAction["port"]
		 * ->io.kubernetes.client.custom.IntOrString["strValue"])

When underlying API response has an integer port 
 "livenessProbe": {
              "httpGet": {
                "path": "/healthz",
                "port": 10259,
                "host": "127.0.0.1",
                "scheme": "HTTPS"
              },

**Client Version**
`15.0.1`

**Kubernetes Version**
`1.23.0`

**Java Version**
Java jdk 17.0.2.8-hotspot / adoptium

**To Reproduce**
With a running single node Kubeadm cluster request pods in all namespaces via client library

**Expected behavior**
A list of V1Pod objects to be used 

**Server (please complete the following information):**
 - OS: Ubuntu 
 - Environment: Docker, mirantis docker shim, flannel

**Comment by brendandburns** [comment]
`JSON` is not currently supported, only `GSON`.

The reason you're seeing the problem is that the field is an `IntOrString` object and it requires a custom deserializer:
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java#L23

Which is only registered with GSON. You could probably adapt that to work with the JSON parser (and if you do and want to send a PR we'd probably mege it)

Hope that helps.

**Comment by oldshaghat** [comment]
JSON is the name of the class in the code gen that wraps the GSON instance, I believe 

But yeah I think now I see what's going on -- the API call and the API (GSON) deserialization is working but when I idiotically pass that result back out my 'normal' server stack is trying to re-serialize the V1Pod with Jackson and that's where the failure is. I have a test now working that is showing that - this is not a bug / closing the issue.
