### ISSUE TITLE
Generate JAR for extended kubernetes client

### ISSUE THREAD

**Issue by ilias-115** [kubernetes-client/java#2248]
**How can I generate JAR for the extended client ?**
We can generate the JAR for the client by executing:

`
git clone --recursive https://github.com/kubernetes-client/java
cd java/kubernetes
mvn package
`

But what about the **extended** client ? I need the JAR files in order to use it. 

**Client Version**
e.g. `15.0.1`

**Kubernetes Version**
e.g. `20.11`

**Java Version**
Java 8

**Comment by brendandburns** [comment]
Just run `mvn package` in the `java` directory, it will build all of the packages.
