### ISSUE TITLE
Cronjob

### ISSUE THREAD

**Issue by GitHub-del-cloud1** [kubernetes-client/java#2249]
Can I trigger a cron job manually from Java code?
If yes,Could you please let me know how?

**Comment by brendandburns** [comment]
Manually triggering a cron job is equivalent to creating a `Job` resource from the template within the `ChronJob` object.

This is definitely possible with this client, you need to:

Read the `CronJob` from the client
Examine the PodTemplate in CronJob->Spec->Template
Create a `Job` from that template using the client.
