### ISSUE TITLE
Timeout of triggering the reconcile loop

### ISSUE THREAD

**Issue by weiqingy** [kubernetes-client/java#2273]
Hi team,

Is there a way to tune the timeout at which point the K8s triggers the reconcile loop? Is it this parameter [REFLECTOR_WATCH_CLIENTSIDE_TIMEOUT](https://github.com/kubernetes-client/java/blob/0642e7b8fc1c3bdebd77136c35cacd577c006e62/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L41)? The default value is 5 mins. How did you come up with the defaults value? How to configure it? 

Thanks!
Weiqing

**Comment by yue9944882** [comment]
@weiqingy can you elaborate the purpose of configuring that property? a 5-min watch timeout is designed, the informer should be restarting a new watch connection after the previous one has expired. the same property is not customize'able in the native golang informer as far as i know

**Comment by weiqingy** [comment]
Thanks for the reply @yue9944882 . You've answered my question. I'll update here if I have more questions.
