### ISSUE TITLE
ttlSecondsAfterFinished is not working

### ISSUE THREAD

**Issue by shangzhilong** [kubernetes-client/java#2279]
kubernetes-client-java version:   15.0.1

ttlSecondsAfterFinished is not working:
            BatchV1Api api = new BatchV1Api();
            V1Job v1Job =
                    new V1JobBuilder()
                            .withNewMetadata()
                            .withName(createNamespacedJobReq.getJobName())
                            .withLabels(createNamespacedJobReq.getLabels())
                            .endMetadata()
                            .withNewSpec()
                            .withNewTemplate()
                            .withNewMetadata()
                            .withLabels(req.getLabels())
                            .endMetadata()
                            .withSpec(v1PodSpec)
                            .endTemplate()
                            .withTtlSecondsAfterFinished(60*10)
                            .endSpec()
                            .build();
            V1Job createResult = api.createNamespacedJob(namespace, v1Job, null, null, null, null);

but inside k8s master node, 'kubectl apply -f job-ttl-test.yaml' has no problem:
job-ttl-test.yaml:
     apiVersion: batch/v1
      kind: Job
      metadata:
        name: pi-with-ttl
        namespace: nmap-idc-stg
      spec:
        ttlSecondsAfterFinished: 100
        template:
          spec:
            containers:
            - name: pi
              image: perl
              command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            restartPolicy: Never

**Comment by yue9944882** [comment]
@shangzhilong wasnt able to reproduce that. i created a job using your code snippet, and it worked:

```
  spec:
    ...
    ttlSecondsAfterFinished: 600
  status:
    active: 1
    ready: 0
    startTime: "2022-06-15T06:42:47Z"
```
