### ISSUE TITLE
Dynamics is not thread-safe

### ISSUE THREAD

**Issue by honnix** [kubernetes-client/java#2284]
**Describe the bug**
`io.kubernetes.client.util.generic.dynamic.Dynamics` is not thread-safe when handling yaml. This is because  `org.yaml.snakeyaml.Yaml` is not thread-safe as documented: `Public YAML interface. This class is not thread-safe.`.

More specifically, methods in `Dynamics` using `internalYamlCodec` are not thread-safe.

**Client Version**
`15.0.1`

**Kubernetes Version**
`1.24.0`

**Java Version**
Java 17

**To Reproduce**
Invoke `Dynamics.newFromYaml` from multiple threads.

**Expected behavior**
The utility class is either thread-safe or documented.

**KubeConfig**
NA

**Server (please complete the following information):**
NA

**Additional context**
NA

**Comment by colinhusanmao** [comment]
seems internalYamlCodec isn't used by the library,  as the server return application/json type content usually, we need to be carefully if we use it.

**Comment by dmcwhorter-ddl** [comment]
fwiw -- we've seen a bug on an internal project that traced back to this issue
