### ISSUE TITLE
Propose a release of 0.16.0 for Kubernetes 1.24

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#2286]
I propose that we cut a release. @yue9944882 if that works, I will run the GitHub action to perform the release.

**Comment by yue9944882** [comment]
@brendandburns +1, it's a new major release so we need to push a new `release-16` branch and then run the release job on that branch. https://github.com/kubernetes-client/java/blob/master/RELEASES.md#make-sure-the-release-job-runs-on-the-release-branch.

**Comment by rjeberhard** [comment]
I'm curious about the status of #2218. I see that the `OpenAPIEnums` is graduating to beta in 1.24.

**Comment by rjeberhard** [comment]
Sounds good, thanks for responding @yue9944882. I don't need this feature, but I did the work updating our code to use 15.0.0 and so hadn't been able to move to 15.0.1 without reverting that work. I was curious to see if I would need to do that work (to revert) to use 16.0.0 and the timeframe of when those enum types might return.

**Comment by yue9944882** [comment]
@rjeberhard we can see the progress in this thread https://github.com/kubernetes/kubernetes/issues/109177 btw

**Comment by brendandburns** [comment]
This is now published:

https://search.maven.org/artifact/io.kubernetes/client-java/16.0.0/bundle
