### ISSUE TITLE
Updating pod image with PATCH returns HTTP code 422

### ISSUE THREAD

**Issue by Dimylo** [kubernetes-client/java#2287]
Hello,
After the upgrade, from 14.0.1 to 15.0.1, V1Pod patchNamespacedPod method cannot handle our Patch request, returning a 422 HTTPError. Our body format is:
`body = "[{\"op\":\"replace\", \"path\":\"/spec/containers/0/image\", \"value\":\"{new-image}\"}];
V1Patch patch = new V1Patch(body);`
and our method call looks like:
`this.api.patchNamespacedPod(podName, namespace, patch, pretty, null, null, null, false);`

Are there any changes regarding this procedure where we need to take into account?
Isn't the default action to handle it as json-format?

Best regards, 
Dimitris

**Comment by brendandburns** [comment]
I believe that the default content type for the patch operation changed. It's recommended that you use `PatchUtils.patch(...)` as shown in the patch example:

https://github.com/kubernetes-client/java/blob/automated-release-15.0.1/examples/examples-release-15/src/main/java/io/kubernetes/client/examples/PatchExample.java#L68

**Comment by colinhusanmao** [comment]
solved by setting force to null.
