### ISSUE TITLE
Missing support for client.authentication.k8s.io/v1

### ISSUE THREAD

**Issue by oazmon** [kubernetes-client/java#2290]
**Describe the bug**
No version including HEAD supports client.authentication.k8s.io/v1

**Client Version**
All Versions including HEAD

**Kubernetes Version**
e.g. `1.21+` 

**Java Version**
Any

**To Reproduce**
Attempt to login to a cluster using client.authentication.k8s.io/v1

**Expected behavior**
A login successful. Instead getting unknown apiVersion

**Additional context**
The problem is here: 
https://github.com/kubernetes-client/java/blob/bfd8217bb95138087bdd5dd928ea061a6fa3def9/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L275

**Comment by brendandburns** [comment]
Yeah, I think that's a bug. Feel free to send a PR, or we will get to it eventually.
