### ISSUE TITLE
Propose release 1.0.0-beta4

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#231]
This is going to be the final (I hope) release candidate before cutting a 1.0.0.

Changes:
   * Add default true to stdout and stderr on Exec. (#227), fixes #225 
   * Add single argument constructor in Quantity (#223), fixes #229 

cc: @lwander @lewisheadden @rjeberhard

**Comment by lwander** [comment]
SGTM

**Comment by brendandburns** [comment]
This has been pushed out to sonatype, it will take a little while to propogate out to maven central.

I'm going to wait ~2 weeks (on vacation next week :) and if there are no bugs I'll promote to 1.0.0

**Comment by brendandburns** [comment]
Closing this as the release is published.
