### ISSUE TITLE
Unexpected unknown resource type exception while Kubectl.apply

### ISSUE THREAD

**Issue by fbi007130** [kubernetes-client/java#2318]
**Describe the bug**
I am trying to apply a yaml file with Kubectl according to https://github.com/kubernetes-client/java/blob/b0c91798c63203f20dc8f2674197e772b2c187ee/docs/kubectl-equivalence-in-java.md#kubectl-apply .But there is a exception as below.The yaml file can be execute successfully via kubectl command in ssh.
Exception:
`io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.util.generic.dynamic.DynamicKubernetesObject
	at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:268)
	at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:309)
	at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:73)
	at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:67)
	at com.ChaoBladeStepdefs.deletePod(ChaoBladeStepdefs.java:47)
	at ✽.Delete pod(file:///C:/Users//Test.feature:4)`

Yaml file:

`apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: delete-pod-by-labels
spec:
  experiments:
  - scope: pod
    target: pod
    action: delete
    desc: "delete pod by labels"
    matchers:
    - name: labels
      value:
      - "app.kubernetes.io/instance=valuevalue"
    - name: namespace
      value:
      - "idm"
    - name: evict-percent
      value:
      - "100"
`

Java code:
`String yamlStr=new String(Files.readAllBytes(Paths.get("/tmp/deletepod.yaml")));
DynamicKubernetesObject dynamicK8sObject=Dynamics.newFromYaml(yamlStr);
Kubectl.apply(DynamicKubernetesObject.class).resource(dynamicK8sObject).execute();
`

**Client Version**
`16.0.0`

**Kubernetes Version**
 `1.23.3`

**Java Version**
Java 8

**To Reproduce**

**Expected behavior**
delete-pod-by-labels should be create.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
This is happening because your custom resource definition is unknown to the `ModelMapper` class:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java#L267

Please look at the instructions here:
https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

For generating types for CRD.

Alternately, you can hand-code an object for your CRD and then call `ModelMapper.addModelMap(...);`

**Comment by brendandburns** [comment]
Looking at the code some more, it may be possible for us to do the right thing here for DynamicKubernetesObject + GenericApi, but it's going to require some careful coding.

**Comment by fbi007130** [comment]
Thank.It is better that we should apply a yaml without a CRD created because I think it is too heavy to create a CRD in my test project.
