### ISSUE TITLE
'void org.yaml.snakeyaml.LoaderOptions.setEnumCaseSensitive(boolean)' while using k8s java client v16.0.0

### ISSUE THREAD

**Issue by namantalaycha10** [kubernetes-client/java#2333]
getting this error while using k8s java client v16.0.0 with snakeyaml v1.126
are these both version compatible with each other , if not then what version of snake yaml is compatible ?

```
         'void org.yaml.snakeyaml.LoaderOptions.setEnumCaseSensitive(boolean)'
	at io.kubernetes.client.util.Yaml.getSnakeYaml(Yaml.java:417)
	at io.kubernetes.client.util.Yaml.getSnakeYaml(Yaml.java:395)
	at io.kubernetes.client.util.Yaml.loadAs(Yaml.java:106)
```

**Comment by brendandburns** [comment]
We use snakeyaml `v1.30` https://github.com/kubernetes-client/java/blob/automated-release-16.0.0/pom.xml#L45

That is the supported version. We don't test anything else.
