### ISSUE TITLE
`Taints.Effect.NO_EXECUTE.toString()` returns "NoExcute" instead of "NoExecute"

### ISSUE THREAD

**Issue by sky-bro** [kubernetes-client/java#2340]
**Describe the bug**

the enum value `Taints.Effect.NO_EXECUTE`'s toString() method returns "NoExcute" instead of "NoExecute".

source code: https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/taints/Taints.java#L35

**Client Version**
`16.0.0`

**Kubernetes Version**
`1.24.3`

**Java Version**
`Java 8`

**To Reproduce**
add a taint to a node with:
```java
import io.kubernetes.client.extended.kubectl.Kubectl;
import io.kubernetes.client.extended.kubectl.exception.KubectlException;
import io.kubernetes.client.openapi.Configuration;
import io.kubernetes.client.util.Config;

import java.io.IOException;

class Main{
    public static void main(String[] args) throws KubectlException, IOException {
        Configuration.setDefaultApiClient(Config.defaultClient());
        String nodeName = "myk8s-4nodes-worker";
        // neither "NoExecute" or "NoExcute" will work
        Kubectl.taint().name(nodeName).addTaint("key", "value", "NoExecute").execute();
    }
}
```

**Expected behavior**
taint (with Effect "NoExecute") should be added correctly

**Comment by brendandburns** [comment]
Yeah, that's a bug. We'd happily take a PR with the fix or we'll get to it eventually.

**Comment by priyal13m** [comment]
Before: 
![image](https://user-images.githubusercontent.com/19232080/184832671-1164962d-445e-47f3-a5e8-8152aca273de.png)
After:
![image](https://user-images.githubusercontent.com/19232080/184832704-d6b542cb-6f95-4c84-8b7a-ea2fbe1c4524.png)

**Comment by yue9944882** [comment]
good catch!
