### ISSUE TITLE
AWS EKS Authentication using KubeConfig

### ISSUE THREAD

**Issue by mayankkthr** [kubernetes-client/java#2348]
I am trying to connect to AWS EKS Cluster using Kubernetes Java Client.
I am trying to use AWS EKS Config file to perform this operation.

AWS EKS config file uses certificate based authentication with exec command. But I get the following error:

java.io.IOException: Cannot run program "aws": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at io.kubernetes.client.util.KubeConfig.runExec(KubeConfig.java:326)
        at io.kubernetes.client.util.KubeConfig.tokenViaExecCredential(KubeConfig.java:269)
        at io.kubernetes.client.util.KubeConfig.getAccessToken(KubeConfig.java:231)

It seems that **aws** command is not being recognized. 

The command getting executed is something like - **aws --region** region-name **eks get-token --cluster-name** cluster-name

**Comment by brendandburns** [comment]
You need the `aws` command line tool installed in your environment.

**Comment by mayankkthr** [comment]
I tried doing exec into my pod and installed aws-cli. But that did not help.
Let me try to rebuild my docker image with aws-cli installation and then retry the authentication.

**Comment by mayankkthr** [comment]
Installing aws-cli in docker image worked. Thanks!
