### ISSUE TITLE
patchNode  object

### ISSUE THREAD

**Issue by berlinsaint** [kubernetes-client/java#235]
i use python library to  patchNode Ok, but wrong with the java;
my patch body is  patch = {"metadata":{"labels":{"test":"11dd"}}}
i use :  
![image](https://user-images.githubusercontent.com/10629930/38673331-966d3e9e-3e83-11e8-9a01-13fe2b90b333.png)
but not use ,it return HTTP 500 .

**Comment by berlinsaint** [comment]
Solved.

`String jsonStr =  "{\"op\":\"add\",\"path\":\"/metadata/labels/testd\",\"value\":\"hhhee\"}";
    Object obj = (new Gson()).fromJson(jsonStr, JsonElement.class);
   // Gson a = new Gson();
    ArrayList<JsonObject> arr = new ArrayList<>();
    arr.add(((JsonElement) obj).getAsJsonObject());
    api.patchNode("ixxx",arr,"true");`

**Comment by LeoDemon** [comment]
it works for me , tks.

**Comment by yue9944882** [comment]
for future travelers, please refer to the PatchExample under https://github.com/kubernetes-client/java#example to find out how to patch resources in different patch formats.
