### ISSUE TITLE
EXEC: Upgrade request required error when executing api.connectPostNamespacedPodExec()

### ISSUE THREAD

**Issue by jevin36** [kubernetes-client/java#236]
Hi, when I am executing api.connectPostNamespacedPodExec() I am getting a BAD REQUEST. Maybe I am just doing sth wrong invoking the method or initializing the client?

```
...
    ApiClient client = Config.fromConfig("/Users/kevin/.kube/config");
    Configuration.setDefaultApiClient(client);

    CoreV1Api api = new CoreV1Api();

    try {
      String aDefault1 = api.connectPostNamespacedPodExec("hello-node-9f5f775d6-qsgj2", "default", "/bin/ls", null, null, null, null, true);
    }catch (ApiException e){
      System.out.println(e.getResponseBody());
      e.printStackTrace();
    }
...
```

Result:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}

io.kubernetes.client.ApiException: Bad Request
```

**Comment by brendandburns** [comment]
Does the example here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java

Work for you?

The kubernetes api server doesn't like your request and it's returning 400 which blocks the web socket from connecting. 

Can you see if `e.getCause()` is populated? that might give you more information.

If not, perhaps the ExecExample above can help you figure out what is different about your request...

**Comment by jevin36** [comment]
Hi,
the cause is null. I am testing against the latest minikube on a mac. The ExecExample works fine, I checked that before.

I read sth. about exec  is using SPDY somewhere on a webpage but I am not sure if the implementation  for Exec and new CoreV1Api().connectGetNamespacedPodExec(...) varies.

**Comment by brendandburns** [comment]
Oh, wait, I just noticed that  you're trying to use the `connectGetNamespacedPodExec()` directly.

I don't think that is going to work, that call expects the caller to be able to upgrade to a web-sockets connection and the Swagger client knows nothing about WebSockets.

You need to use the `Exec` class as is done in the example.

Sorry I didn't notice that sooner.  Closing this issue.

**Comment by davecramer** [comment]
Should it be made private then ?
