### ISSUE TITLE
Manual or Sample Code to create core create objects like Pods, Services etc

### ISSUE THREAD

**Issue by muthiyalu** [kubernetes-client/java#237]
Hi All,
I am trying to use the Java api create java components which can abstract a developer from having to understand the mechanics of Kubernetes . In that context I didn't find any set documentation or sample on how to create and deploy objects like Pods , Services etc via the Api. Can this added the sample?

**Comment by brendandburns** [comment]
There are a number of Java examples here:

https://github.com/kubernetes-client/java/tree/master/examples/src/main/java/io/kubernetes/client/examples
