### ISSUE TITLE
Port exec-based client auth provider to Java client

### ISSUE THREAD

**Issue by dbenhur** [kubernetes-client/java#238]
With 1.10, this exec-based client auth credential provider alpha feature was introduced  [kubernetes/features#541](https://github.com/kubernetes/features/issues/541) for client-go.  Exec-based auth plugin should be supported by this java client in addition to client-go. Umbrella issue: [kubernetes#62185](https://github.com/kubernetes/kubernetes/issues/62185)

/kind feature
/sig api-machinery

**Comment by aniruddh-a** [comment]
Is anyone working on this issue ?

**Comment by brendandburns** [comment]
@aniruddh-a sorry for the delay in responding. No one is working on this. If you're inetersted we'd love a PR.

Thanks

**Comment by mustafaakin** [comment]
Is help still needed? We implemented it in a hacky-way but would love to contribute it in a cleaner way, it is simple enough to do so.

**Comment by vkahawala** [comment]
Hi @mustafaakin I would verymuch like to know how you solved this issue. I saw your post under [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/168). I was able to get that piece of code working. But I'm having trouble using that token with kubernetes java client.

Thanks

**Comment by jglick** [comment]
Seems to be `KubeConfig.getAccessToken` which needs patching. I did so for another client: https://github.com/fabric8io/kubernetes-client/pull/1224

**Comment by jglick** [comment]
Since this is implemented at least in a basic form, I think this issue could be closed and follow-ups filed as needed for the items I noted in #512 or anything else that comes up.
