### ISSUE TITLE
Return JSON format for CRD API

### ISSUE THREAD

**Issue by 025nju** [kubernetes-client/java#2412]
Like getting pod list, creating pod, is there method to return json response with http status included? Can't find any. 
Currently it's converted to V1PodList or V1Pod, from ApiResponse.
Sometimes we need this client work in the middle, so all data in ApiResponse will be necessary for relaying to the real requester.
Thanks in advance.

**Comment by brendandburns** [comment]
This is possible, but not particularly easy, there's an example here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/PodLogs.java#L74

That may help point the way.

**Comment by aespinosa** [comment]
You may be interested in https://square.github.io/okhttp/4.x/okhttp/okhttp3/-call/ to figure out how the `Call` object works behind the scenes with the `*Call()` methods 

I wonder if the openapi-generator maintainers of the okhttp-gson java templates can add documentation on the generated API methods on when & where to use which.  

At least in here, we've done a good job of indicating when to use the synchronous and async methods, maybe we add a more explicit example of using the `*Call` method?

**Comment by 025nju** [comment]
@brendandburns , @aespinosa thanks a lot for your guidance.
