### ISSUE TITLE
Generating CRD action, no such file or directory error

### ISSUE THREAD

**Issue by Mert18** [kubernetes-client/java#2415]
**Describe the bug**
I am trying to generate Java classes from the CRD below, it keeps giving "no such file or directory error". I am giving package name as the reversed order of group name in the crd as mentioned in the documentation.

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: "2022-10-03T20:18:24Z"
  generation: 1
  name: virtualclusters.tenancy.x-k8s.io
  resourceVersion: "2436"
  uid: 927f3779-fe5a-44e7-8188-94dd6f34d5dc
spec:
  conversion:
    strategy: None
  group: tenancy.x-k8s.io
  names:
    kind: VirtualCluster
    listKind: VirtualClusterList
    plural: virtualclusters
    shortNames:
    - vc
    singular: virtualcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .spec.clusterVersionName
      name: ClusterVersion
      type: string
    - jsonPath: .status.clusterNamespace
      name: ClusterNamespace
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterDomain:
                type: string
              clusterVersionName:
                type: string
              opaqueMetaPrefixes:
                items:
                  type: string
                type: array
              pkiExpireDays:
                format: int64
                type: integer
              serviceCidr:
                type: string
              transparentMetaPrefixes:
                items:
                  type: string
                type: array
            required:
            - clusterVersionName
            type: object
          status:
            properties:
              clusterNamespace:
                type: string
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                  required:
                  - status
                  type: object
                type: array
              message:
                type: string
              phase:
                type: string
              reason:
                type: string
            required:
            - phase
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: VirtualCluster
    listKind: VirtualClusterList
    plural: virtualclusters
    shortNames:
    - vc
    singular: virtualcluster
  conditions:
  - lastTransitionTime: "2022-10-03T20:18:24Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-10-03T20:18:24Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
```
[Here ](https://github.com/Mert18/java/actions/runs/3248326095/jobs/5329400832) is the error logs. From the erroneous action.

**Client Version**
`15.0.1`

**Kubernetes Version**
`1.24.3`

**Java Version**
Java 8

**To Reproduce**
Go to actions tab on your cloned repository.
Run an action with the CRD I have specified above.

**Expected behavior**
Expecting to get generated Java classes from the CRD.

**Additional context**
I was able to generate some classes from different CRDs, from different CRD files. So I am not sure If there is an error with this 
CRD template.

Thanks in advance.

**Comment by sakryt** [comment]
Same question when generating [this crd]([https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml]), have you found solutions?

**Comment by Mert18** [comment]
Unfortunately I have not, but I ended up writing my custom classes implementing `io.kubernetes.client.common.KubernetesObject` and `io.kubernetes.client.common.KubernetesListObject` as described [here](https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model).

**Comment by sakryt** [comment]
Finally, I found that when the crd's `spec.gourp` and `metadata.name` ends with `k8s.io`, the generator work failed with this error.

**Comment by sakryt** [comment]
Finally, I found that when the crd's `spec.gourp` and `metadata.name` ends with `k8s.io`, the generator work failed with this error.
So, the solution is change the `spec.gourp` and `metadata.name` value and it works.

**Comment by aespinosa** [comment]
```
cp: can't stat '/home/runner/work/java/java/crd-gen/gen/src/main/java/io/x-k8s/tenancy/models': No such file or directory
```

the generator created the `x_k8s` directory instead.  java doesn't allow dashes.  try removing the dash in your group's name

**Comment by Mert18** [comment]
> ```
> [INFO] Skipped /output_dir/docs/V1alpha1VirtualClusterSpec.md (Skipped by modelDocs options supplied by user.)
> [INFO] writing file /output_dir/src/main/java/io/x_k8s/tenancy/models/V1alpha1VirtualClusterStatus.java
> [INFO] Skipped /output_dir/docs/V1alpha1VirtualClusterStatus.md (Skipped by modelDocs options supplied by user.)
> 
> .... 
> cp: can't stat '/home/runner/work/java/java/crd-gen/gen/src/main/java/io/x-k8s/tenancy/models': No such file or directory
> ```
> 
> the generator created the `x_k8s` directory instead. java doesn't allow dashes. try removing the dash in your group's name

Can confirm that removing "-" from the group name resolves the problem but I'm not sure whether this breaks other things or not. This can be considered as a "workaround" and I'm closing this issue. If you have any other way to resolve the problem, please comment on this issue.
