### ISSUE TITLE
Kubectl delete label support

### ISSUE THREAD

**Issue by Mert18** [kubernetes-client/java#2422]
**Describe the bug**
Kubectl.label() does not have a delete option as far as I have seen. Normally in k8s, a label can be deleted via CLI by putting "-" at the end of the label.

Ex:
```kubectl label node <nodename> <labelname>=labelvalue``` adds the label, and
```kubectl label node <nodename> <labelname>-``` deletes the label

But in Kubectl.label() function cannot have "-" at the end of the label name due to some restrictions. Can it be achieved? 

By the way, I found a getaround with the jsonpatches and created a patch to the resource in order to achieve this functionality:

```
String patchString = "[{ \"op\": \"remove\", \"path\": \"/labelpath\" }]";
                V1Patch patch = new V1Patch(patchString);
                Kubectl.patch(V1Node.class).apiClient(apiClient).name(nodeName).patchContent(patch).execute();
```

**Comment by LUEDDEA** [comment]
setting the value for the label to null removes the label

**Comment by LUEDDEA** [comment]
@shubhbapna 
that is more or less, what I already do with the existing code:
`
label(V1Node.class).apiClient(client).name(nodeName).addLabel(key, **null**).execute();`

**Comment by shubhbapna** [comment]
Yeah, maybe for the sake of clarity since we are using `addLabel` to well delete a label, we can add this simple `deleteLabel` method?
