### ISSUE TITLE
KubectlDrain.java is not working properly

### ISSUE THREAD

**Issue by LUEDDEA** [kubernetes-client/java#2425]
**Describe the bug**
When I run
`kubectl drain node1 --ignore-daemonsets`
I get a warning `ignoring DaemonSet-managed Pods: .......`
and all pods (except those listed in the warning) running on node1 will be immediately get into state "terminating", the message "evicting pod.....", followed by the message "pod/..... evicted" is displayed.

When I use
`drain().ignoreDaemonSets().apiClient(client).name(nodeName).execute();`
one of the DaemonSet-managed pods is terminated and immediately restarted, then the next pod is going into state "terminating". After the default gracePeriod of 30 seconds I get an exception:
`Timed out waiting for Pod delete.`

I think there are two issues in the Java API:
First, every pod deleted, no matter if it is a DaemonSet-managed pod or not. In KubectlDrain.java line 78 is a check with `validatePods()` with a check for DaemonSet but then `deletePod()` does not exclude the DaemonSet-managed pods.

Second, the method `deletePod` first calls `api.deleteNamespacedPod()` and provides the gracePeriod/timeout set for KubectlDrain (The duration in seconds before the object should be deleted.).
In the next line there is a `waitForPodDelete` with exactly the same timeout. That means, the API does not delete before the timeout is over and the wait does not wait any longer thant the timeout.

**Java Client Library Version**
`16.0.0`

**Kubernetes Version**
`1.24.1`

**Java Version**
`openjdk version "17.0.3" 2022-04-19`
`IBM Semeru Runtime Open Edition 17.0.3.0 (build 17.0.3+7)`

**To Reproduce**
see description above

**Expected behavior**
Same behaviour of the Java client, as in kubectl cmd.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Linux
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by mmacedoaraujo** [comment]
If this is still open for someone to get this issue, I'll really want to give it a try. This will be my first contribution here, if there's no problem I'll be really glad to contribute.

**Comment by LUEDDEA** [comment]
@mmacedoaraujo Are you working on this? Otherwise I would try to provide a fix in the next days.

**Comment by mmacedoaraujo** [comment]
@LUEDDEA you can go on, I'm not working on it anymore
