### ISSUE TITLE
Propose Release 1.0.0

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#243]
Official 1.0.0 Kubernetes Java release!

Changes:
   * Fix an issue with YAML parsing IntString values (#242)
   * Fix an issue with HTML-escaped byte arrays (#240) 

@lwander @lewisheadden @mbohlool 

Once this release is done, I'll move forward to support the 1.10 API with a 2.0.0 series (or possibly a 1.1.0 series)

**Comment by lwander** [comment]
SGTM!

**Comment by brendandburns** [comment]
This has been released out to Sonatype.
