### ISSUE TITLE
Java Client doesn't refresh client auth exec-based credentials

### ISSUE THREAD

**Issue by micahhausler** [kubernetes-client/java#2438]
**Describe the bug**

Kubernetes supports [executing an external process](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration) to get API server credentials, and the Java K8s client does too. 

For processes that run longer than a credential's lifetime, client-go [consumes the `.Status.ExpirationTimestamp`](https://github.com/kubernetes/kubernetes/blob/6824cd3addbb214e88e00f451babb8a44eb738d1/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L472), caches the credential and will refresh when the credential expires. 

Today, the [Java client ignores the `.Status.ExpirationTimestamp`](https://github.com/kubernetes-client/java/blob/v16.0.1/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L310) and only gets the exec-based credential once at process start, and will not refresh.  

Amazon EKS's tokens (using [kubernetes-sigs/aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator)) use this exec-based format, and return an expiration timestamp [15 minuets in the future](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/6da4c44ca4aa1c83dbc0820c5413312606dc09f3/pkg/token/token.go#L361) (same for the [AWS CLI implementation](https://github.com/aws/aws-cli/blob/2.8.8/awscli/customizations/eks/get_token.py#L140)). This causes  long-running Java clients (such as a Spark job) to fail authentication after 15 minuets. 

**Client Version**

All versions

**Kubernetes Version**

All versions

**Java Version**
N/A

**To Reproduce**
N/A

**Expected behavior**

The Java client should cache the returned exec-based credential, and refresh automatically

**KubeConfig**
N/A

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**
N/A

**Comment by brendandburns** [comment]
We'd be happy to take a PR to implement this, you will need to implement the `Authenticator` interface and register it for `exec` providers.

See:
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/authenticators/AzureActiveDirectoryAuthenticator.java

For an example.

**Comment by brendandburns** [comment]
I looked into this more closely and it is more complicated, you can look at the comment here:

https://github.com/kubernetes-client/java/blob/bbd7b10e5b50e691d7d1b95c70da15bba17ec6b8/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L318

For more details.

**Comment by brendandburns** [comment]
We will need a significant refactor to support this. Not impossible, but definitely not trivial.

**Comment by raykrueger** [comment]
I may have a solution for this to review this week if we're still interested. It will be possible to support a refresh internal on any Authentication instance created in the ClientBuilder.
