### ISSUE TITLE
Fail to generate crd models for chaos-mesh(error: mapping values are not allowed in this context)

### ISSUE THREAD

**Issue by colinhusanmao** [kubernetes-client/java#2444]
**Describe the bug**
I want to generate crd models for chaos-mesh, cause i want to create cr based on those models. but when i do it according to the wiki [Generate Java CRD Model](https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model), it failed with the message: "error converting YAML to JSON: yaml: line 28: mapping values are not allowed in this context"，i don't know the reason, the content in line 28 is below:
````
27        properties:
28          apiVersion:
29            description: 'APIVersion defines the versioned schema of this representation
30              of an object. Servers should convert recognized schemas to the latest
31              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
32            type: string
````

**Client Version**i
11.0.2

**Kubernetes Version**
1.19.10

**Java Version**
null

**To Reproduce**
run geneate crd action with the yaml : https://github.com/chaos-mesh/chaos-mesh/blob/v2.1.5/config/crd/bases/chaos-mesh.org_httpchaos.yaml

**Expected behavior**
generate crd models successfully

**KubeConfig**
null

**Server (please complete the following information):**
null

**Additional context**
null

**Comment by aespinosa** [comment]
i'm guessing that's coming from the apiserver? `apiVersion`  , etc. does not need to be in the CRD definition.  

the apiserver will inject them in the end when the linked script downloads the swagger 2 definition

**Comment by brendandburns** [comment]
My guess is that it is not liking that multi-line string for the `description` field. I would try that whole string on a single line. I don't think a multi-line string in single quotes is valid YAML.

**Comment by colinhusanmao** [comment]
> My guess is that it is not liking that multi-line string for the `description` field. I would try that whole string on a single line. I don't think a multi-line string in single quotes is valid YAML.

i have found some crd yaml contains multi-line string in single quote, and the yaml can be parsed currectly in some website,like: https://onlineyamltools.com/convert-yaml-to-json

**Comment by allenhaozi** [comment]
@colinhusanmao How did this work out ? I have the same error
