### ISSUE TITLE
Kubectl.cordon() Exception when runing in k8s， However, idea IDE is running ok

### ISSUE THREAD

**Issue by FlonFl** [kubernetes-client/java#2448]
**Describe the bug**

Kubectl.cordon() Exception when runing in k8s， However, idea IDE is running ok；The Windows 10 operating system.

**Dev java version:**
C:\Users\Administrator>java -version
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

**java version in docker:**
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**springboot version:**
v2.5.5

**maven dependence:**
 ```
<!-- kubernetes client -->
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>16.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-extended</artifactId>
            <version>16.0.1</version>
        </dependency>
```
**dockerfile:**
```
FROM openjdk:8-jdk-alpine
ENV TZ=Asia/Shanghai
ARG JAR_FILE=xxx-1.0.0.jar
COPY ${JAR_FILE} /home/xxx.jar
WORKDIR /home
RUN apk add dumb-init
ENTRYPOINT ["dumb-init","java","-jar","xxx.jar","--spring.profiles.active=k8s"]
```

**My code:**

```
        Configuration.setDefaultApiClient(apiClient);
        try {
            if ("cordon".equalsIgnoreCase(status)) {
                V1Node v1Node = Kubectl.cordon().apiClient(apiClient).name(nodeName).execute();
                log.info("执行节点{} cordon成功：{}",nodeName, v1Node);
                return true;
            } else if("uncordon".equalsIgnoreCase(status)) {
                Kubectl.uncordon().apiClient(apiClient).name(nodeName).execute();
                return true;
            }
        } catch (KubectlException e) {
            log.error("执行节点调度失败：",e);
        }
```

**Exception :**

```
io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1Node
        at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:268) ~[client-java-extended-16.0.1.jar!/:?]
        at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:309) ~[client-java-extended-16.0.1.jar!/:?]
        at io.kubernetes.client.extended.kubectl.KubectlCordon.performCordon(KubectlCordon.java:44) ~[client-java-extended-16.0.1.jar!/:?]
        at io.kubernetes.client.extended.kubectl.KubectlCordon.execute(KubectlCordon.java:38) ~[client-java-extended-16.0.1.jar!/:?]

```

**Client Version**
 `16.0.1`

**Kubernetes Version**
 `v1.19.8`
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
`

**Java Version**
Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
SpringBoot does weird things with the classloader that prevent some of our magic registration stuff from working.

You probably need to add `ModelMapper.refresh(discovery)` into your code.

**Comment by FlonFl** [comment]
> SpringBoot does weird things with the classloader that prevent some of our magic registration stuff from working.
> 
> You probably need to add `ModelMapper.refresh(discovery)` into your code.

Thanks brendandburns,  I use the `CoreV1Api.Patch` to replace the `Kubectl. Cordon ()`, can run normally. 

```
String CORDON_PATCH_STR = "[{\"op\":\"replace\",\"path\":\"/spec/unschedulable\",\"value\":true}]";
CoreV1Api api = new CoreV1Api(apiClient);
V1Node v1Node = api.patchNode(nodeName, new V1Patch(CORDON_PATCH_STR), null, null, null,null,null);
```
