### ISSUE TITLE
Custom object json-patch

### ISSUE THREAD

**Issue by luochenzc** [kubernetes-client/java#2449]
I noticed that most patch calls support all 3 patch types (json-patch, merge-patch, strategic-merge-patch), but the patch calls for custom objects (including for status and scale sub-resources) only support merge-patch.
But patchClusterCustomObject(group, version, plural, name, body, dryRun, fieldManager, force)  The API uses json-patch , cause response 400 ?

**Comment by colinhusanmao** [comment]
patchClusterCustomObject use json-patch default and we can't change it, i think it should be marked as @deprecated, people should use PatchUtils instead. @yue9944882

**Comment by luochenzc** [comment]
> patchClusterCustomObject use json-patch default and we can't change it, i think it should be marked as @deprecated, people should use PatchUtils instead. @yue9944882

Can you provide an example? I haven't contacted PatchUtils. Thank you very much

**Comment by brendandburns** [comment]
It's hard to mark those methods as @deprecated because they come out of the code generator. We'd need some annotation in the swagger/open api or somesuch.

I'm closing this issue since @luochenzc seems to have solved their issue.
