### ISSUE TITLE
CustomObjectsApi needs enhancement

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#245]
Presently, we generate our own "Api" class for the type described by our CRD; however, I'd prefer to use the built-in CustomObjectsApi class.

Unfortunately, there is no way to pass in the our Type (and list Type) when constructing or using this class.  Also, the list methods are missing parameters like fieldSelector and _continue.

I'm happy to assist with performing the enhancement but would like to know if there is a way to adjust how this class is generated so that we get the enhancements described.

@brendandburns

**Comment by brendandburns** [comment]
This is tricky...  I'm going to have to think about it a little bit...

**Comment by rjeberhard** [comment]
Hi, @brendandburns.  Any update on this one?  If you look at the conversation in Issue #515 you'll see the gymnastics that are presently necessary to use your own type.

In the meantime, we basically copied methods from CoreV1Api, but used the paths from CustomObjectsApi, and then updated to use our custom type.

**Comment by yue9944882** [comment]
> @rjeberhard , you may be interested in kubernetes-client/gen#59 (comment)

just regenerating the client is fine i believe..

**Comment by yue9944882** [comment]
/remove-lifecycle rotten

ref: #609, working on structured CRD client generation
