### ISSUE TITLE
Unable to import Builder classes while upgrading to higher version

### ISSUE THREAD

**Issue by apoorvamk** [kubernetes-client/java#2461]
**Describe the bug**
Trying to upgrade the java client from 12.0.1 to 16.0.2 but unable to import/use the builder classes as it is not found (for ex: V1ConfigMapBuilder) which was available in lower versions. I see the class [https://github.com/kubernetes-client/java/blob/v16.0.2/fluent/src/main/java/io/kubernetes/client/openapi/models/V1ConfigMapBuilder.java](https://github.com/kubernetes-client/java/blob/v16.0.2/fluent/src/main/java/io/kubernetes/client/openapi/models/V1ConfigMapBuilder.java) in the version release but it's absent here: [https://javadoc.io/static/io.kubernetes/client-java-api/16.0.2/allclasses-noframe.html](https://javadoc.io/static/io.kubernetes/client-java-api/16.0.2/allclasses-noframe.html)

**Client Version**
e.g. `16.0.2`

**Kubernetes Version**
e.g. `1.22`

**Java Version**
e.g. Java 8

**Comment by brendandburns** [comment]
@apoorvamk thanks for reporting this, I will take a look and try to figure out what happened. If they are missing, it's not intentional.

Can you try `16.0.1` or `16.0.0`?

Thanks!

**Comment by eformat** [comment]
The *Builder classes seem to have disappeared in latest versions 16.* e.g V1DeploymentBuilder not there.
Still there in 12.0.2, gone since 13.0.0 ?

https://javadoc.io/doc/io.kubernetes/client-java-api/12.0.2/index.html
https://javadoc.io/doc/io.kubernetes/client-java-api/13.0.0/index.html

**Comment by brendandburns** [comment]
Ah, thanks.

We repackaged those classes around that transition, you need the `client-java-api-fluent` package:

https://javadoc.io/doc/io.kubernetes/client-java-api-fluent/latest/index.html

**Comment by brendandburns** [comment]
Closing this issue as I believe the question is answered. Please use the `/reopen` command if further assistance is needed.
