### ISSUE TITLE
Getting the context name

### ISSUE THREAD

**Issue by Antirecord** [kubernetes-client/java#2463]
Good afternoon! Can you please tell me how can I get the context-name when using the configuration incluster(Service Account)?

**Comment by brendandburns** [comment]
In the case of an in-cluster configuration, there is no kubeconfig file, and therefore no context. You can see the details of how the in cluster configuration is created here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L242

**Comment by Antirecord** [comment]
> In the case of an in-cluster configuration, there is no kubeconfig file, and therefore no context. You can see the details of how the in cluster configuration is created here:Now it is clear. Sorry for the stupid question.
> 
> https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L242
