### ISSUE TITLE
Please remove the @ignore annotation and fix the testcase : testAutowiredFieldsOfReconcilerBeansAreSet

### ISSUE THREAD

**Issue by colinhusanmao** [kubernetes-client/java#2469]
**Describe the bug**
can we fix the @ignore testcase, or just remove it?

**Client Version**
`11.0.2`

**Kubernetes Version**
`1.19`

**Java Version**
Java 8

**To Reproduce**
remove the @ignore annotation, run the test case KubernetesReconcilerProcessorTest#testAutowiredFieldsOfReconcilerBeansAreSet
it throws:
````
NoSuchBeanDefinitionException: No qualifying bean of type 'io.kubernetes.client.extended.controller.Controller' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=testReconciler1Controller)}
````

**Expected behavior**
test case run success

**KubeConfig**
none

**Server (please complete the following information):**
windows

**Additional context**
can we fix the testcase by removing the controller injection like below:
````
//  @Autowired
//  @Qualifier("testReconciler1Controller")
//  private Controller controller1CreatedByReconcilerProcessor;
//
//  @Autowired
//  @Qualifier("testReconciler2Controller")
//  private Controller controller2CreatedByReconcilerProcessor;

  @Autowired
  @Qualifier("testReconciler1")
  private TestReconciler testReconciler1ToBeInjected;
````
 or remove this testcase?

**Comment by brendandburns** [comment]
I don't see the `@ignore` annotation at HEAD. If it is present in `11.0.2` it's not really worth fixing as that branch is very old and unmaintained at this point.

https://github.com/search?q=repo%3Akubernetes-client%2Fjava+ignore+NOT+language%3AMarkdown+NOT+language%3AJSON+NOT+path%3Aopenapi+NOT+path%3Acontrib&type=code

Thanks
