### ISSUE TITLE
no release note for version 11.0.2  found

### ISSUE THREAD

**Issue by colinhusanmao** [kubernetes-client/java#2475]
**Describe the bug**
i want to know the changelog for version 11.0.2, but i can't find it under : https://github.com/kubernetes-client/java/releases

**Client Version**
11.0.2

**Kubernetes Version**
1.19.16

**Java Version**
Java 8

**To Reproduce**
no release note or changelog found for version 11.0.2

**Expected behavior**

**KubeConfig**

**Server (please complete the following information):**

**Additional context**

**Comment by brendandburns** [comment]
Release note management is painful and needs to be improved, see #2308 

For 11.0.2 consulting the branch PR history:
https://github.com/kubernetes-client/java/pulls?q=is%3Apr+base%3Arelease-11+is%3Aclosed

Can show you what was committed between 11.0.1 and 11.0.2
