### ISSUE TITLE
Forbidden returned from job running in pod on GKE cluster

### ISSUE THREAD

**Issue by RobMaskell** [kubernetes-client/java#248]
I'm trying to use the kubernetes-client to create a secret on a newly created GKE k8s cluster but that's not working so I tried just listing pods and that doesn't work either. I'm trying to use the cert and token on the pod that I've confirmed do exist.

```
        CoreV1Api api = new CoreV1Api(Config.fromCluster());
        V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
        for (V1Pod item : list.getItems()) {
            System.out.println(item.getMetadata().getName());
        }
````
The exception I'm getting is
```
io.kubernetes.client.ApiException: Forbidden
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18462)
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18440)

```
I tried increasing the logging level but I didn't get any additional info and now I have no idea what to try next. Do I need to pass some environment vars to the job in the YAML file? or am I missing something else.

**Comment by brendandburns** [comment]
Can you print out ApiException.getResponseBody() that likely has more details.

**Comment by RobMaskell** [comment]
For the benefit of anyone else reading this it looks like an RBAC issue on GKE. I ran the following
```
kubectl create clusterrolebinding myapp-view-binding --clusterrole=admin --serviceaccount=default:default
```
Which I don't advise in production as it gives too much privilege to the user but it did make the code work.
Thanks @brendanburns  for the help

**Comment by kondapally1989** [comment]
try adding   serviceAccountName: admin to pod spec 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Comment by RobMaskell** [comment]
Thanks @kondapally1989  that's exactly the kind of page I failed to find, very helpful.
