### ISSUE TITLE
Can we supprt chaos-mesh models in this project?

### ISSUE THREAD

**Issue by colinhusanmao** [kubernetes-client/java#2486]
**Describe the bug**
can we supprt chaos-mesh models in this project? https://github.com/chaos-mesh/chaos-mesh/tree/master/config/crd/bases
just like prometheus-operator and cert-manager in client-java-contrib

**Client Version**
11.0.2

**Kubernetes Version**
1.19.3

**Java Version**
Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
**Server (please complete the following information):**

**Additional context**

**Comment by brendandburns** [comment]
We'd take a PR to add the classes if you want. The trick is going to be who shows up to support/regenerate whenever the API changes.

It might make sense to manage it as a separate package...

**Comment by colinhusanmao** [comment]
> We'd take a PR to add the classes if you want. The trick is going to be who shows up to support/regenerate whenever the API changes.
> 
> It might make sense to manage it as a separate package...
 
Thanks! 
    if the api changes, which i think will be compatible with old versions, we can fetch their yamls and regenerate code when we release a new version.  The API will genereate huge amount of codes, which i think maybe is not a good idea.
