### ISSUE TITLE
Base64 encoded string escaping still broken on secret post and patch in 1.0.0

### ISSUE THREAD

**Issue by Bas83** [kubernetes-client/java#249]
The issue is that Base64 padding characters, meaning the = sign, are replaced by \u003d 
This happens for both create and update. And I have made a test class that fully reproduces the issue just using the client with version 1.0.0. Previously there was another similar issue to this that was supposedly fixed but apparently the cases weren't identical.

Note that the problem only occurs when the base64 encoded string is PADDED with = or ==. This means that it does work for many possible values. The example values in my test class are of course failing.

The problem occurs in 2 places in this test: 

**For the 'auth' object in create, even when using the easier stringData way of passing the config of the secret.**

The request being made:

{"apiVersion":"v1","kind":"Secret","metadata":{"name":"myregistrysecret1543901145"},"stringData":{".dockerconfigjson":"{\"auths\":{\"docker.io\":{\"username\":\"1x\",\"password\":\"1x\",\"auth\":\"MXg6MXg\u003d\"}}}"},"type":"kubernetes.io/dockerconfigjson"}

Note the \u003d in the request. Also note this actually silently fails. Even pulling an image will still work as kubernetes doesn't seem to look at the auth object but rather the username and password field.

**For the whole dockerconfigjson object when trying to patch the secret.**

The request being made:

[{"op":"replace","path":"/data","value":{".dockerconfigjson":"eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJYMiIsInBhc3N3b3JkIjoiWDJ4IiwiYXV0aCI6IldESTZXREo0In19fQ\u003d\u003d"}}]

Note the \u003d in the request.

The error:

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"v1.Secret: ObjectMeta: v1.ObjectMeta: TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 102, parsing 163 ...03d\\u003d\"... at {\"apiVersion\":\"v1\",\"data\":{\".dockerconfigjson\":\"eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJYMiIsInBhc3N3b3JkIjoiWDJ4IiwiYXV0aCI6IldESTZXREo0In19fQ\\u003d\\u003d\"},\"kind\":\"Secret\",\"metadata\":{\"name\":\"myregistrysecret1543901145\",\"namespace\":\"default\",\"uid\":\"b7140c25-42d7-11e8-85fb-00155d380106\",\"resourceVersion\":\"186505\",\"creationTimestamp\":\"2018-04-18T07:11:29Z\"},\"type\":\"kubernetes.io/dockerconfigjson\"}","code":500}

Here is my code:

[TestApp.zip](https://github.com/kubernetes-client/java/files/1936964/TestApp.zip)

And as text:

```
import com.google.gson.JsonObject;
import io.kubernetes.client.ApiClient;
import io.kubernetes.client.Configuration;
import io.kubernetes.client.apis.CoreV1Api;
import io.kubernetes.client.models.V1ObjectMeta;
import io.kubernetes.client.models.V1Secret;
import io.kubernetes.client.util.Config;

import java.util.*;

public class TestApp {

    private final static String KUBE_CONFIG_LOCATION = "C:\\\\Users\\\\Sebastiaan\\\\.kube\\\\config";
    private final static String SECRET_NAME = "myregistrysecret" + new Random().nextInt();;

    public static void main(String[] args) throws Exception {
        ApiClient client = Config.fromConfig(KUBE_CONFIG_LOCATION);
        client.setDebugging(true);
        Configuration.setDefaultApiClient(client);
        String username = "1x";
        String password = "1x";
        createSecret(username, password);
        username = "X2";
        password = "X2x";
        updateSecret(username, password);
    }

    private static void createSecret(String username, String password) throws Exception {
        CoreV1Api api = new CoreV1Api();
        V1Secret secret = new V1Secret();
        secret.setApiVersion("v1");
        secret.setKind("Secret");
        secret.setType("kubernetes.io/dockerconfigjson");
        V1ObjectMeta secretMeta = new V1ObjectMeta();
        secretMeta.setName(SECRET_NAME);
        secret.setMetadata(secretMeta);

        String dockerConfigJson = getDockerConfigJson(username, password).toString();

        Map<String, String> data = new HashMap<>();
        data.put(".dockerconfigjson", dockerConfigJson);
        secret.setStringData(data);
        System.out.println("docker config json on create:" + dockerConfigJson);
        api.createNamespacedSecret("default", secret, "false");
    }

    private static void updateSecret(String username, String password) throws  Exception {
        CoreV1Api api = new CoreV1Api();
        ArrayList<JsonObject> patchObjects = new ArrayList<>();
        JsonObject patchObject = new JsonObject();
        JsonObject dataObject = new JsonObject();
        String nonEncodedConfig = getDockerConfigJson(username, password).toString();
        String encodedConfig = Base64.getEncoder().encodeToString(nonEncodedConfig.getBytes());
        System.out.println("docker config json in patch not encoded:" + nonEncodedConfig);
        System.out.println("docker config json in patch:" + encodedConfig);
        dataObject.addProperty(".dockerconfigjson", encodedConfig);
        patchObject.addProperty("op", "replace");
        patchObject.addProperty("path", "/data");
        patchObject.add("value", dataObject);
        patchObjects.add(patchObject);
        System.out.println("patch objects tostring: " + patchObjects.toString());
        api.patchNamespacedSecret(SECRET_NAME, "default", patchObjects, "false");
    }

    private static JsonObject getDockerConfigJson(String username, String password) {
        String host = "docker.io";

        JsonObject authObject = new JsonObject();
        authObject.addProperty("username", username);
        authObject.addProperty("password", password);
        String auth = username + ":" + password;
        String authEncoded = Base64.getEncoder().encodeToString(auth.getBytes());
        System.out.println("auth encoded: " + authEncoded);
        authObject.addProperty("auth", authEncoded);
        JsonObject registryObject = new JsonObject();
        registryObject.add(host, authObject);
        JsonObject configJsonObject = new JsonObject();
        configJsonObject.add("auths", registryObject);
        return configJsonObject;
    }
}

```

**Comment by Bas83** [comment]
Btw, I think the fix may be to call disableHtmlEscaping on the GsonBuilder. See https://google.github.io/gson/apidocs/com/google/gson/GsonBuilder.html#disableHtmlEscaping--

**Comment by Bas83** [comment]
A workaround has been provided for me in https://github.com/kubernetes-client/java/issues/239 so as far as I'm concerned, this can be closed.

However, I agree with the comment in there that escaping these characters is a responsibility of the kubernetes server, not the client, so I'm wondering why this is done at this level.

**Comment by brendandburns** [comment]
@Bas83 thanks, I agree the server should be better here. I'll try to repro and file some k8s bugs...

thx

**Comment by RobMaskell** [comment]
I had this issue and v1.0.0 sorted it for me, was able to write my secret

**Comment by brendandburns** [comment]
Closing this issue as resolved.

**Comment by brendandburns** [comment]
really closing this one :)
