### ISSUE TITLE
Creating ApiClient with bearer tokens - oidc

### ISSUE THREAD

**Issue by Mert18** [kubernetes-client/java#2495]
**Describe the bug**
I have a Keycloak server that provides me bearer token (oidc) and I want to create an api client with this token (so the requests will be authorized). My api-server have --oidc-issuer-url and a few other things configured(role and rolebindings) to make it happen. But I could not see any method to create ApiClients with bearer token in this library. Is it possible yet? Thanks in advance.

**Client Version**
15.0.1

**Kubernetes Version**
1.24.3

**Java Version**
Java 11

**Expected behavior**
I want to find a way to create client that supports OAuth tokens to authenticate

**Comment by brendandburns** [comment]
This client should be able to load any `kubeconfig` file if you want to pass that as either a file or a stream.

Alternately, the code here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L242

Gives an example of how to build a client w/o a kubeconfig file. You probably can adapt that to match your needs.

**Comment by Mert18** [comment]
It worked. Thank you so much :)
