### ISSUE TITLE
Controllers and LeaderElector uses non-daemon threads by default

### ISSUE THREAD

**Issue by Prototik** [kubernetes-client/java#2509]
**Describe the bug**
I noticed my app won't stop after `main` is exited, thread dump says there are live threads: `leader-elector-*`.
I searched this problem via issues and it surprised me as it got fixed long time ago: #873
But was broken in 3f542d9c50c2864f7581dde847e44ec150eff3b8.
I don't know what @dsyer means with comment `Daemon status inherited from default`, but docs for [`Executors.defaultThreadFactory`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#defaultThreadFactory()) explicitly says it creates non-daemon threads by default:
`Each new thread is created as a non-daemon thread...`

**Client Version**
`17.0.0`

**Java Version**
Java 17

**Comment by brendandburns** [comment]
Seems like we should provide the ability for a user to inject their own thread factory if they want to so that you can chose what kind of threads you want.

We'd be happy to take a PR to add this customizability to the `Threads` class

**Comment by nervoussidd** [comment]
Hey can you assign me this issue? i would love to contribute.

**Comment by Sajiyah-Salat** [comment]
Can someone explain me this pr. I would love to work on  that?

**Comment by swastik959** [comment]
hi i am new to open source and want to contribute to this issue can you guide me through it

**Comment by swastik959** [comment]
@brendandburns hi I have submitted a pr please review it

**Comment by Aman254** [comment]
Hey Can anyone please invite me to the kubernetes slack work space 

My  Email:  utsav.kumar.3639@gmail.com

**Comment by mahehsblogs** [comment]
Hey, I am new to Open Source. Is this issue still open?
