### ISSUE TITLE
Get list of Node Pool for a cluster 

### ISSUE THREAD

**Issue by pawank0411** [kubernetes-client/java#2514]
How can we get the list of Node Pool using kubernetes-client library ?

**Comment by brendandburns** [comment]
You want the `listNode` call, here's an example:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTop.java#L101

**Comment by pawank0411** [comment]
@brendandburns This only gives me the list Nodes.

But as per my requirement I need list of Node groups/pools with some details like max node count, min node count etc
