### ISSUE TITLE
Mentoring request: Using PartialObjectMetadata (uses custom Accept header, return type)

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#2516]
**Use case**
From the discussion in this Slack thread on #sig-api-machinery: https://kubernetes.slack.com/archives/C0EG7JC6T/p1673376066590699

"We have several applications (operators, etc.) where it is critical that the application responds promptly to changed resources, so naturally we make heavy use of watches. However, we've observed that watch notifications are not guaranteed, which makes sense especially in some of our customer's heavily loaded environments. Therefore, we are presently backing up the use of watches by periodically listing the resource. This obviously works but is surprisingly expensive, e.g. 60% of the CPU/memory consumption of an operator could be in these lists. Is there a different pattern that we could use, e.g. force a watch to generate a BOOKMARK or a variant of a read or list that is more like a HEAD request in that it only returns the metadata or resourceVersion?"

After some back-and-forth, the response was that there is an undocumented feature where a client can perform a LIST operation that only returns metadata (spec, status suppressed). 

The request that the feature be documented is here: https://github.com/kubernetes/website/issues/37448
It is somewhat unclear to me, but either client-go informer already uses this feature or there is a separate informer specifically for these partial object metadata requests: https://github.com/kubernetes/client-go/blob/master/metadata/metadatainformer/informer.go

Note: Our main application (an operator) is not presently using the Informer or Controller patterns from this project primarily because the application was written in 2017 and the mentioned classes had not yet matured. I'm open to using those classes if we can figure out how to resolve some of the QoS requirements and operational details such as this issue. Maybe this is an area where my team could contribute back?

**Client Version**
`17.0.0`

**Kubernetes Version**
`1.24.0`

**Java Version**
Java 19

**Ask**
Based on the description of the PartialObjectMetadata feature, a client uses this by specifying a custom Accept header and then expecting a PartialObjectMetadataList type back instead of the resource-specific type. How could I do this with the Java client? We are presently using methods like CoreV1Api.listNamespacedPodAsync. The only mechanism I see that might be able to adjust or configure the Accept header would be an Interceptor on the ApiClient.OkHttpClient.

I see that there is a PartialObjectMetadata(List) set of classes, but these are presently part of the proto module, which I believe doesn't support custom resources, and I'm not sure how I would use it with the existing API's anyway.

Thanks, in advance.

**Comment by brendandburns** [comment]
cc @yue9944882 

I think this should be feasible, see the discussion here:
https://github.com/kubernetes-client/java/issues/1268

I'm not sure if PartialObjectMetadata is in the swagger definitions anywhere. If it is, we're not grabbing it right now, but it wouldn't be hard to hand-write a PartialObjectMetadata class and use that as the generic parameter to Watch, Informer, etc.

You'll want to use the `GenericAPI` which enables you to grab arbitrary types.

Hopefully that's enough to get you started, let us know how you proceed or if there are questions and we can help you address them. And we would welcome contributions back.

fwiw, the proto definitions are _very_ old and probably should be removed or updated as I'm not sure they even work anymore.

That said, for a truly high-performance informer/etc. using proto may become necessary as lots of the CPU time is spent in decoding JSON.

**Comment by yue9944882** [comment]
@rjeberhard @brendandburns my apologies for visiting this thread late, i was out for lunar new year for a while. years ago when we applied this informer to production, we encountered and solved this issue by customizing gson serializer. in gson library, there is extensibility to short-circuit and omit some fields upon deserialization, that will save a lot of java object from instantiation. let me check if i can find some example code snippet of that.

**Comment by yue9944882** [comment]
the following is an example of skipping deserializing pod's status in the apiClient, so the cached objects in the informers will cost lower memory space.
```
        Gson gson = new GsonBuilder()
            .addDeserializationExclusionStrategy(new ExclusionStrategy() {
                @Override
                public boolean shouldSkipField(FieldAttributes fieldAttributes) {
                    return false;
                }

                @Override
                public boolean shouldSkipClass(Class<?> aClass) {
                    if (V1PodStatus.class.equals(aClass)) {
                        return true;
                    }
                    return false;
                }
            })
            .registerTypeAdapter(Date.class, new JSON.DateTypeAdapter())
            .registerTypeAdapter(java.sql.Date.class, new JSON.SqlDateTypeAdapter())
            .registerTypeAdapter(DateTime.class, new JSON.DateTimeTypeAdapter())
            .create();
```
