### ISSUE TITLE
Kubectl equivalent API call 

### ISSUE THREAD

**Issue by pawank0411** [kubernetes-client/java#2519]
Can you please let me know the equivalent method call for the below command.

`kubectl get node -o=custom-columns='node_name:metadata.name, node_group:metadata.labels.cloud\.google\.com/gke-nodepool'`

I can think of `Kubectl.get(V1Node.class).execute();`
But how can I pass the appropriate args like `-o=custom-columns` etc.

**Comment by brendandburns** [comment]
Those flags are specific to how the objects are printed to stdout. You will need to implement that custom printing yourself using the `V1Node` class.

Closing since this is out of scope for the library. If you want to send a PR to add a more configurable printer please feel free.

**Comment by pawank0411** [comment]
@brendandburns - I am getting `Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1Node` when `Kubectl.get(V1Node.class).namespace("namespace ").execute()` is called.
