### ISSUE TITLE
V1Node is not working with kubectl

### ISSUE THREAD

**Issue by pawank0411** [kubernetes-client/java#2521]
I am getting `Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1Node` when `Kubectl.get(V1Node.class).execute()` is called.

**Comment by pawank0411** [comment]
By checking some previous closed issues - I tired to adding
`ModelMapper.addModelMap("", "v1", "node", "nodes", false, V1Node.class);`

Don't know why I started getting 
`io.kubernetes.client.openapi.apis. CustomObjectsApi.listClusterCustomObjectCall(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljav
at io.kubernetes.client.util.generic.GenerickmernetesApi.lambda$list $2 (GenericKubernetesApi.java:341)
at io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:787)
at io.kubernetes.client.util.generic.GenerickubernetesApi.list (GenericKubernetesApi.java:337)
at io.kubernetes.client.extended.kubectl.KubectlGet.execute(KubectlGet.java:72)`

Let me add some more context.
Client Library version : 15.0.0

**Comment by pawank0411** [comment]
I upgraded the client version to the latest one 17.0.0 but still the issues persists.

**Comment by pawank0411** [comment]
@brendandburns Please help me out.

**Comment by pawank0411** [comment]
I have even tried adding
`ModelMapper.refresh(new Discovery(client))` to the code base.

But still I am getting `Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1Node`

**Comment by brendandburns** [comment]
We rely on static initialization magic to register those classes:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ModelMapper.java#L74

There's something about the way that SpringBoot has multiple class loaders that messes around with that loading.

Manually registering it with `addModelMap(...)` is the right last-resort way to fix it.

I'm surprised that `ModelMapper.refresh(...)` isn't working though. If you have a simple reproduction of this (e.g. code and pom) we can try to figure out what is going on, but for now manually calling `addModelMap(..)` is the right fix/workaround.

**Comment by pawank0411** [comment]
> By checking some previous closed issues - I tired to adding `ModelMapper.addModelMap("", "v1", "node", "nodes", false, V1Node.class);`
> 
> Don't know why I started getting `java.lang.NoSuchMethodError: io.kubernetes.client.openapi.apis. CustomObjectsApi.listClusterCustomObjectCall(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljav at io.kubernetes.client.util.generic.GenerickmernetesApi.lambda$list $2 (GenericKubernetesApi.java:341) at io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:787) at io.kubernetes.client.util.generic.GenerickubernetesApi.list (GenericKubernetesApi.java:337) at io.kubernetes.client.extended.kubectl.KubectlGet.execute(KubectlGet.java:72)`
> 
> Let me add some more context. Client Library version : 15.0.0 Tomcat server version : 9.0.68 Spring Boot Application

I tried even adding model map manually that @brendandburns

**Comment by pawank0411** [comment]
> We rely on static initialization magic to register those classes:
> 
> https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ModelMapper.java#L74
> 
> There's something about the way that SpringBoot has multiple class loaders that messes around with that loading.
> 
> Manually registering it with `addModelMap(...)` is the right last-resort way to fix it.
> 
> I'm surprised that `ModelMapper.refresh(...)` isn't working though. If you have a simple reproduction of this (e.g. code and pom) we can try to figure out what is going on, but for now manually calling `addModelMap(..)` is the right fix/workaround.

```
public List<V1Node> ListNodepoolsKubectl() {
try {
Logger.info("Inside try block of ListNodepoolsKubectl() "); ApiClient client = Config.defaultClient(); Configuration.setDefaultApiClient(client); client.setDebugging (true);

ModelMapper.refresh(new Discovery(client)); 
List<V1Node> nodes = Kubectl.get(V1Node.class).execute(); Logger.info("Exit try block of listNodepoolsKubectl() "); 
return nodes;
} catch (KubectlException | IOException e) {Logger.info("exception at listNodepoolsKubectl() {}", e.getStackTrace()); Logger.info("exception at listNodepoolsKubectl() {}", e.getMessage());
} catch (ApiException e) {
Logger.info("exception at listNodepoolsKubectl() {}", e.getStackTrace());
Logger.info("exception at listNodepoolsKubectl())", e.getResponseBody()); Logger.info("exception at listNodepoolsKubectl())", e.getResponseHeaders());
Logger.info("exception at listNodepoolsKubectl() {}", e.getMessage());
} return Collections.emptyList();
}
```

pom.xml
```
<dependency>
<groupId>io.kubernetes</groupId>
<artifactId>client-java-extended</artifactId>
<version>17.0.0</version>
<exclusions>
<exclusion>
<groupId>com.github.ben-manes.caffeine</groupId> <artifactId>caffeine</artifactId>
</exclusion>
</exclusions>
</dependency> 
```

**Comment by pawank0411** [comment]
@brendandburns Please help me out. I have already tried adding modelMap as well

**Comment by pawank0411** [comment]
@brendandburns let me know any solution
