### ISSUE TITLE
Is there API to list pods in a given namespace ?

### ISSUE THREAD

**Issue by inspire99** [kubernetes-client/java#2527]
Is there API to list pods in a given namespace ?

I want to filter out pods from a given namespace and then access files from that particular pod.

**Comment by brendandburns** [comment]
Here's a good example:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/ExpandedExample.java#L159

**Comment by brendandburns** [comment]
This will probably help you with accessing the files:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCopy.java
