### ISSUE TITLE
copyFileFromPod uses cat command to be run on container - sometimes user (ExecCredential - AWS EKS) could be forbidden

### ISSUE THREAD

**Issue by inspire99** [kubernetes-client/java#2528]
**Describe the bug**
During file copy from pod to local machine, copyFileFromPod internally tries to execute cat command and then build the inputStream.
But, sometimes the user allowed to interact with k8s apiServer may not have permission.
The alternative kubectl command still works.

**Client Version**
e.g. `11.0.1`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
Hrm, can you provide more details? Specifically do you mean that the alternative `Kubectl` class in this client works? Or the `kubectl` client on the command line works?

The auth to the api server should be the same whether it is kubectl or this client so I'd want to investigate in more detail if that was the case.

**Comment by inspire99** [comment]
It was kubectl client, which I could run from the commandline
