### ISSUE TITLE
Calling getNodeMetrics() giving 404

### ISSUE THREAD

**Issue by gdagur** [kubernetes-client/java#2530]
I am trying to run this example on my machine - https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/MetricsExample.java

At [line 40](https://github.com/kubernetes-client/java/blob/c905116f736e2a0264b08644ea26606af8a46254/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/MetricsExample.java#L40), when it tries to call getNodeMetrics() it throws following error -
```
Exception in thread "main" io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: null
    code: 404
    details: null
    kind: null
    message: 404 page not found
    
    metadata: null
    reason: null
    status: null
}


I have checked `kubectl get nodes` and `kubectl get pods` were  working when I tried to run the example.

```

**Client Version**
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Kubernetes Version**
e.g. `1.25.0`

**Java Version**
`Java 8`

**To Reproduce**
1) install docker desktop and kubernetes on macOs
2) Deploy any pods to kubernetes
3) check `kubectl get pods` is working
4) Try to the Metrics example

**Expected behavior**
I was expecting to see the resources used by each container.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: MacOS
 - Environment: docker-desktop

**Comment by brendandburns** [comment]
Is there a metrics server running in your cluster? Can you try `kubectl top pods` If that works, then something weird is going on. If that doesn't work, it's because you don't have a metrics server in your cluster.

**Comment by gdagur** [comment]
Thanks @brendandburns you are right, I checked I didn't have metric server running locally that. 

However I tried after changing context to point to remote EKS cluster. After that I checked `kubctl get pods` , `kubectl top pods` all work and I can see the workloads, their cpu cores and memory bytes etc through command line, but when I tried to execute above java example, it fails with 403.  I thought as long as kubectl command works, the java client would also work for remote eks server, as it uses the same kube config.

Do you have any inputs regarding this. Is there anything additional that needs to be done to make it it work with remote server like eks?
