### ISSUE TITLE
Not support to load multi yaml documents from a single file.

### ISSUE THREAD

**Issue by ihac** [kubernetes-client/java#254]
Seems [PR 209(Add support for easier YAML loading.)](https://github.com/kubernetes-client/java/pull/207) does not support multiple resources in one yaml file (separated by `---`), which is quite common in daily use.

I guess using `snakeyaml.Yaml.loadAll()` would be a quick fix, but it conflicts with your current api. So do you get any plan for this?

Thanks.

**Comment by brendandburns** [comment]
I'd be ok if someone wanted to add:

`List<Object> loadAll(Reader input)`

method to the `Yaml` class.

**Comment by brendandburns** [comment]
This was fixed by #256
