### ISSUE TITLE
io.kubernetes.client.informer.cache.Cache#indexKeys may cause NPE

### ISSUE THREAD

**Issue by Yuanxiangz** [kubernetes-client/java#2548]
**Describe the bug**

io.kubernetes.client.informer.cache.Cache#indexKeys
![image](https://user-images.githubusercontent.com/11549125/215770539-b8ca1683-592b-492a-8712-7ff98b39aec4.png)

the "set" maybe null. that will cause NPE. we should check null before use

just like byIndex
![image](https://user-images.githubusercontent.com/11549125/215774679-f1101832-f5f5-40d4-ba7e-b91dd2b41e50.png)

**Client Version**
all

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by yue9944882** [comment]
thank you for reporting this, just opened a pull for the fix.
