### ISSUE TITLE
IOException when Watching pod

### ISSUE THREAD

**Issue by lishengming6** [kubernetes-client/java#2555]
**Describe the bug**
When the watch pod changes, the IO exception is reported at intervals. I want to know why

**Client Version**
 `9.0.2`

**Kubernetes Version**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**Java Version**
Java 8

**log**

![image](https://user-images.githubusercontent.com/18570881/217773599-b87c9c28-101a-4bf8-8753-bc6fa2cccb21.png)
![image](https://user-images.githubusercontent.com/18570881/217773678-083d8945-5171-49fd-ac75-e6273fb0f8d3.png)
![image](https://user-images.githubusercontent.com/18570881/217773710-432ff507-c01b-4152-84e3-18b77d6b2068.png)

**Comment by brendandburns** [comment]
You'll probably want to print the IOException to know for sure, but in general, a watch is a TCP stream, and TCP can break in the network for various reasons (e.g. timeouts, etc)

You'll want to use the `Informer` classes in this client for a more complete solution for watching and responding to resource changes.

**Comment by lishengming6** [comment]
Yes, when io happens, I will create a new watch again, which may miss or get repeated pod changes

**Comment by brendandburns** [comment]
The correct pattern is to do:
```java
// pseudo-code
while (true) {
    pods = ListPods()
    watchPods()
}
```

That way you don't miss any pods. If you use the `Informer` class in this client it handles that pattern for you.

**Comment by lishengming6** [comment]
ok，I get it，thanks.
