### ISSUE TITLE
coreV1Api.deleteNamespacedPersistentVolumeClaim got an error

### ISSUE THREAD

**Issue by liubiao1024** [kubernetes-client/java#2559]
**Describe the bug**

V1PersistentVolumeClaim v1PersistentVolumeClaim = coreV1Api.deleteNamespacedPersistentVolumeClaim(name, namespace, pretty, null, 0, null, null, v1DeleteOptions);

I want to delete pvc, but got an error 

E0213 13:14:17.777898       1 status.go:71] apiserver received an error that is not an metav1.Status: &runtime.notRegisteredErr{schemeName:"k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/register.go:27", gvk:schema.GroupVersionKind{Group:"", Version:"v1", Kind:"PersistentVolumeClaim"}, target:runtime.GroupVersioner(nil), t:reflect.Type(nil)}: no kind "PersistentVolumeClaim" is registered for version "v1" in scheme "k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/register.go:27"

**Client Version**
10.0.0

**Kubernetes Version**
1.21.3

**Java Version**
Java 8

**Comment by brendandburns** [comment]
You are using a pretty old version of the library and I believe that this has been fixed in later versions. Can you try upgrading?
