### ISSUE TITLE
IllegalStateException: Not an integer

### ISSUE THREAD

**Issue by youngledo** [kubernetes-client/java#2566]
**Describe the bug**
I have a **V1Deployment** and try to parse it using jackson-dataformats-text(https://github.com/FasterXML/jackson-dataformats-text/tree/master/yaml), but an exception occurs.

Thanks.

**Client Version**
16.0.0

**Java Version**
Java 11

**To Reproduce**

1. A V1Deployment：
<img width="602" alt="企业微信截图_978f61e2-03e3-48cd-9d29-445a16b52c4c" src="https://user-images.githubusercontent.com/68590897/219313801-51a1c292-8f01-4ea0-8ad2-7c6114689bc0.png">

2. Use this method：com.fasterxml.jackson.databind.ObjectMapper#writeValueAsString
<img width="963" alt="企业微信截图_58686c34-ce79-4513-9593-6d79acd3ed66" src="https://user-images.githubusercontent.com/68590897/219313822-547d6e7e-30d4-46a7-ad76-8ae26c1fd5ef.png">

**Comment by brendandburns** [comment]
IntOrString is a custom type that is either an int or a string. To parse it correctly you need to set up a custom encoder/decoder like we do here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Yaml.java#L249

I don't know the exact details of how to do that for the FasterJackson library. That's beyond the scope of this client, so I'm closing this issue as I believe the question is answered. Please use `/reopen` if you need further assistance.

**Comment by youngledo** [comment]
> Can it return null instead of throw an exception "Not a string" or "Not an integer" ? It's ok when using Gson, but not all of the project want to dependency Gson when jackson is the default serialize tool.
> 
> ```
>   public String getStrValue() {
>     return isInt ? null : strValue;
>   }
> 
>   public Integer getIntValue() {
>     return isInt ? intValue : null;
>   }
> ```
It seems that Jackson does not support this kind of customization, need to provide a PR to Jackson

**Comment by wkclz** [comment]
我在 IntOrString 上指定序列化逻辑了，在 #3113 上。Jackson 不会帮干这种事的，标准的做法就是 getter setter.
