### ISSUE TITLE
[Query] Timespan between when the request is taken from cache/queue first time and when the request is fetched from the cache/queue the second time after it got re-queued

### ISSUE THREAD

**Issue by weiqingy** [kubernetes-client/java#2571]
Hi Team,

We built a Flink K8s operator using the Kubernetes-client in Java. Based on our testing, if a request got re-queued, and it will take another 10+ mins to be fetched from the queue for reconciling again even when these weren't many requests in the queue and the operator was not busy at all. I wonder if this is expected? I think if there is only one request in the cache/queue, that request should be fetched by the operator immediately if the operator is not busy on other things, is that correct? If there is any configuration to decide the time span how long a request need to be buffered in the cache/queue if it has been reconciled several times and got re-queued?

**Client Version**
e.g. `14.0.0`

**Kubernetes Version**
e.g. `1.19.16`

**Java Version**
e.g. Java 8

Looking forward to your reply. Thanks!

**Comment by brendandburns** [comment]
Can we get more details on your code? Are you using the `Informer` class?

It's hard to help without additional details.

Thanks!

**Comment by yue9944882** [comment]
> Based on our testing, if a request got re-queued, and it will take another 10+ mins to be fetched from the queue for reconciling again even when these weren't many requests in the queue and the operator was not busy at all.

10+ mins wait time in queue is an indication that the reconcile loop in your controller is constantly failing for some reason. the default rate-limiting policy is a retry-count-based exponential limiter which functions with `delay = max (1000sec, 5milliSec*2^(retryCount-1))`. note that the limit punishment is calculated based on a per-request basis, and once that request finished failing the retry delaying time should be resetted.

**Comment by weiqingy** [comment]
Thanks for helping out here @brendandburns and @yue9944882 . 

1. ` Are you using the Informer class?`
Yes, we are using `informer.SharedIndexInformer` and `informer.SharedInformerFactory`. In our case, before updating the customer resource (`FlinkCluster` in our case) to the desired state (e.g. Ready/Running, aka, the Flink cluster creation is done), the operator needs to validate whether all the child resources of the `FlinkCluster` become in desired state, and the operator watches all the child resources. Whenever there is a state change on child resources, the operator will perform the validation. If the validation doesn't passed (aka. throw out some exception), then the operator will re-queue the request for another round of reconciliation for the`FlinkCluster` creation. Thus, in some cases in which the Flink cluster has many child-resources, re-queueing the request could happen more than average.  Does the implementation make sense to you?

2. ` the default rate-limiting policy is a retry-count-based exponential limiter which functions with delay = max (1000sec, 5milliSec*2^(retryCount-1))`
We didn't set up any rate-limiting policy. For `1000sec`, does it mean that if a request got re-queued, it would take at least ~16 mins to go to another round of reconciliation? Is the rate-limiting policy or the retry-count-based exponential limiter configurable? Could you please share the configuration wiki or code example about how to set up the policy? 

Thanks again,
Weiqing

**Comment by weiqingy** [comment]
Hey @brendandburns @yue9944882 Could you please help take a look at the questions above? Thanks!
