### ISSUE TITLE
The Unit problem of limits value in V1ResourceRequirements

### ISSUE THREAD

**Issue by xiaokuncom** [kubernetes-client/java#2573]
Limits in V1ResourceRequirements is a Map type, but there is no document indicating what is the unit of value in the Map collection of limits in the data obtained by Java after calling api to query the information of pod. This may affect the subsequent calculation of utilization. Can anyone answer it for me? thank you.

**Comment by yue9944882** [comment]
by "unit", do you mean those suffixes e.g. `10m`, `100Mi`? these human readable forms are actually a trick done by golang yaml/json serializer, (the kubernetes upstream has a custom serializing function for easier human interpretation) but they're all done by the client-side. this project can help you correctly talking w/ the kubernetes server and dump/load payload to correct object type, however for now it doesn't have the equivalent helper functions yet. please following the original type documentation of [Quantity](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L31-L92) to comprehend the meaning of underlying fields beneath the map.

**Comment by xiaokuncom** [comment]
> by "unit", do you mean those suffixes e.g. `10m`, `100Mi`? these human readable forms are actually a trick done by golang yaml/json serializer, (the kubernetes upstream has a custom serializing function for easier human interpretation) but they're all done by the client-side. this project can help you correctly talking w/ the kubernetes server and dump/load payload to correct object type, however for now it doesn't have the equivalent helper functions yet. please following the original type documentation of [Quantity](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L31-L92) to comprehend the meaning of underlying fields beneath the map.

I see. Thank you
