### ISSUE TITLE
Create CRD model fail

### ISSUE THREAD

**Issue by LinzeSu** [kubernetes-client/java#2575]
**Describe the bug**
Followed steps here: https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md. Have run both using Github Action and locally and failed with the same message (except for the directory part as they run in different place):
```
cp: can't stat '/home/runner/work/java/java/crd-gen/gen/src/main/java/com/hirain/adminapp/crd/models': No such file or directory
```

**To Reproduce**
Run workflow with https://raw.githubusercontent.com/GoogleCloudPlatform/spark-on-k8s-operator/master/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml. And this error occurs.

**Additional context**
I've been looking through similar issues and solutions but sadly none of them works. Including setting ```.spec.preserveUnknownFields``` to false(https://github.com/kubernetes-client/java/issues/1254) and change the ```.spec.group``` to another name(https://github.com/kubernetes-client/java/issues/1496).

**Comment by liangyuanpeng** [comment]
Same problem with me. i'm generate crd model for gateway api https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml

Just change the url of `https://gist.githubusercontent.com/yue9944882/266fee8e95c2f15a93778263633e72ed/raw/be12c13379eeed13d2532cb65da61fffb19ee3e7/crontab-crd.yaml` to gatewayapi crd url of `https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml`

And it's not working.

**Comment by liangyuanpeng** [comment]
Also not working with github action: https://github.com/liangyuanpeng/kubernetes-client-java/actions/runs/5503815146/jobs/10029387317

crd url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
package: io.github.demo

**Comment by liangyuanpeng** [comment]
I'm building image of myself with https://github.com/kubernetes-client/java/blob/master/client-java-contrib/publish-gen-image.sh , and the image seems like is not working. 

Got the broken image. Run with:

** v1.0.6 ** Change to ** test **
```
docker run   --rm   -v /var/run/docker.sock:/var/run/docker.sock   -v "$(pwd)":"$(pwd)"   -ti   --network host   ghcr.io/kubernetes-client/java/crd-model-gen:test   /generate.sh   -u https://gist.githubusercontent.com/yue9944882/266fee8e95c2f15a93778263633e72ed/raw/be12c13379eeed13d2532cb65da61fffb19ee3e7/crontab-crd.yaml   -n com.example.stable   -p com.example.stable   -o "$(pwd)"
```

```shell
Successfully tagged kubernetes-java-client-gen-with-openapi-generator:v1
--- Running generator inside container...
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "mvn-entrypoint.sh": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 
```

Any doc for build generate crd model gen image? Remind me if i misses something,Thanks.

cc @yue9944882 @brendanburns

**Comment by KaitaoQiu** [comment]
same here, an error occurred when I wanna generate models for 
https://github.com/kubevela/kubevela/blob/master/charts/vela-core/crds/core.oam.dev_applications.yaml

**Comment by KaitaoQiu** [comment]
I have fixed my problem, I need to use the reverse order for group name
