### ISSUE TITLE
Request 18.0.0 or 17.0.2 with backport of recent changes

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#2583]
Hey @brendandburns,

What is the time frame for an 18.0.0 release? Or, alternatively, if it's not soon, may I backport recent changes (GenericKubernetesApi and PartialObjectMetadata) and the SnakeYAML dependency to a 17.0.x maintenance branch and request a 17.0.2 release?

Thanks in advance.

**Comment by brendandburns** [comment]
Yeah, we should probably cut an 18.0.0, I'll do it tomorrow.

If you want to send a backport into 17.0.x I'll cut a 17.0.2 at the same time.

**Comment by brendandburns** [comment]
For anyone tracking this, 18.0.0 pushed out to sonatype today, should be in Maven Central by tomorrow sometime.
