### ISSUE TITLE
Kubernetes Resource Serialization

### ISSUE THREAD

**Issue by lwander** [kubernetes-client/java#26]
Hi team,

Assuming I have the JSON representation of some Kubernetes resource retrieved from the Kubernetes API server - would I be able to deserialize this into the corresponding resource in this client library? For example, would something like this work?

```java
V1Pod v1pod = new ObjectMapper().convertValue(jsonPayload, V1Pod.class)
```

Poking through the generated code I don't see why not, but just wanted to make sure that this is the intended behavior.

Thanks

**Comment by brendandburns** [comment]
I have not tested this, but this should work:

```sh
 Gson gson = new Gson() ;
 V1Pod pod = gson.fromJson(jsonFile, V1Pod.class) ;
```

Now if you want us to do the API detection for you and then parse out the right version, that'd be trickier...

**Comment by brendandburns** [comment]
Closing this because I believe the question is answered, please re-open if it doesn't work...
