### ISSUE TITLE
Bind works with Replication Controller. I want to do that with Deployment

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [kubernetes-client/java#260]
Hello.
I do not know why I do not Watch a deployment object. Can someone help me?

`package scheduler;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

import com.google.common.reflect.TypeToken;

import br.ufpe.cin.gfads.cluster.Update;
import br.ufpe.cin.gfads.kuber.KubernetesController;
import io.kubernetes.client.ApiClient;
import io.kubernetes.client.ApiException;
import io.kubernetes.client.apis.AppsV1beta1Api;
import io.kubernetes.client.apis.CoreV1Api;
import io.kubernetes.client.models.AppsV1beta1Deployment;
import io.kubernetes.client.models.V1Binding;
import io.kubernetes.client.models.V1Node;
import io.kubernetes.client.models.V1NodeCondition;
import io.kubernetes.client.models.V1ObjectMeta;
import io.kubernetes.client.models.V1ObjectReference;
import io.kubernetes.client.models.V1Pod;
import io.kubernetes.client.models.V1PodList;
import io.kubernetes.client.util.Watch;

public class Schedule {
	private ApiClient client;
	private CoreV1Api core;

	public Schedule(ApiClient client) {
		this.client = client;
		this.core = new CoreV1Api(client);

	}

	public boolean watchAndSchedule(String namespace, String serviceName, String chosenNode) throws Exception   {
		String schedulerName = KubernetesController.verifyScheduler(core, serviceName);

		// Retrieving Pods events
		Watch<V1Pod> w = Watch.createWatch(client, 
				core.listNamespacedPodCall(namespace, null, null, null, null, null, 
						null, 
						null, null, true, null, null), 
				new TypeToken<Watch.Response<V1Pod>>() {}.getType());
		
	
		// For all pods events
		for( Watch.Response<V1Pod> event : w ) {
			// check if the pod is "pending" and its scheduller name is the same of ours
			// the follwing code is inspired in this example:
			// https://github.com/kubernetes-client/java/blob/997c088f88fffba5d9195ce91fad89dddb57cff4/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java
			if(schedulerName.equals(event.object.getSpec().getSchedulerName()))
				if( "Pending".equals(event.object.getStatus().getPhase())) {

					System.out.println("Scheduling " + event.object.getMetadata().getName());
					// apply the binding and attach the pod to a node
					//V1Binding res = scheduler(core, event.object.getMetadata().getName(), getNodesAvailable(v1));
					V1Binding res = this.schedule(core, serviceName, chosenNode, namespace);
					if(res != null)
						return true;

				}

		}
		return false;
	}

	/**
	 * this method attach one microservice to one node
	 * @param core
	 * @param serviceName
	 * @param chosenNode
	 * @return
	 * @throws ApiException 
	 */
	private static V1Binding schedule(CoreV1Api core, String serviceName, String chosenNode, String namespace)
			throws ApiException {
		// instantiate a binding object
		V1Binding body = new V1Binding();

		// setting the binding target
		V1ObjectReference target = new V1ObjectReference();
		target.kind("Node");
		target.apiVersion("v1");
		target.name(chosenNode);

		// setting the pod to be attached to selected node
		V1ObjectMeta meta = new V1ObjectMeta();
		meta.name(serviceName);

		// fill the binding object
		body.target(target);
		body.metadata(meta);

		// apply the binding in the cluster
		return core.createNamespacedBinding(namespace, body, null);

	}

}
`

**Comment by brendandburns** [comment]
I'm not sure I understand your question, but I will try to respond.

Watching a `Deployment` will show changes to that `Deployment` but if you want to see changes to `Pods` from a Deployment creating Pods, you need to watch the list of Pods.

You might want to pull the `selector` label query and only watch pods related to that Deployment...

Anyway, please let us know if we can help further.

**Comment by ViniciusDeAndrade** [comment]
Actually I already did what I wanted. And I needed to watch the pods, as you told.
My problem was about updating the cluster with the new deployment configuration. I was working
with replication controller...
I fixed it somehow, and the POM API version needed to be changed... It was a mess! xD

Now I want to know why the **watch**  ends with a throwing error. I need it to act like a listener,
waiting to trigger

**Comment by brendandburns** [comment]
At the bottom of it all, Watch is a TCP connection, and eventually most TCP connections time-out due to inactivity (or load balancers in between), so you should expect (and catch) exceptions and re-initiate the Watch.

I suppose we could wrap that up somehow, but it would be tricky to do it in a way that wouldn't mask real errors from users.

I'm going to close this issue since it seems to be mostly resolved. Please re-open (or create another) if you run into more trouble.

Thanks!
