### ISSUE TITLE
Add exceptionHandler for SharedInformerFactory.sharedIndexInformerFor?

### ISSUE THREAD

**Issue by css521** [kubernetes-client/java#2603]
**Describe the bug**
When I use GenericKubernetesApi as the sharedIndexInformerFor method parameter in the SharedInformerFactory class, there are always many exceptions printed on the console.  Just like the example.
```
 SharedIndexInformer<V1Pod> informer =
                    sharedInformerFactory.sharedIndexInformerFor(
                            new GenericKubernetesApi<>(
                                    V1Pod.class, V1PodList.class, "", "v1", "pods", apiClient),
                            V1Pod.class,
                            1000 * 60 * 15L,
                            namespace);
```
But when I use ListerWatcher as the parameter for the sharedIndexInformerFor method in the SharedInformerFactory class, I can add an exceptionHandler to handle my exceptions, and this is very effective. Just like the example.
```
SharedIndexInformer<V1Pod> informer =
                    sharedInformerFactory.sharedIndexInformerFor(
                            listWatcher,
                            V1Pod.class,
                            1000 * 60 * 15L,
                            this::exceptionHandler);
```
![image](https://user-images.githubusercontent.com/42376488/226795102-1a4370ec-021f-4cce-a933-7f4241dee845.png)

![image](https://user-images.githubusercontent.com/42376488/226795650-f758636c-83c8-421e-a8ec-952b5a1b08ef.png)

So, can we add exceptionHandler to the constructors of SharedInformerFactory class except for ListerWatcher, and I am happy to do this.
**Client Version**
17.0.1

**Kubernetes Version**
1.19.3

**Java Version**
Java 11

**To Reproduce**

**Expected behavior**
**KubeConfig**

**Server (please complete the following information):**

**Additional context**

**Comment by brendandburns** [comment]
Yes, I think that would be fine. We'd be happy to take a PR for this.

Thanks!
