### ISSUE TITLE
Parsing response failed when calling deleteNamespacedPod

### ISSUE THREAD

**Issue by ohadmuch** [kubernetes-client/java#262]
Using version 1.0.0

When calling **deleteNamespacedPod** the inner method **deleteNamespacedPodWithHttpInfo** tries to parse the execute response with type of **V1Status** but the response return actually **V1Pod** so the parsing is failed and an exception is thrown although the delete action is actually performed 

![image](https://user-images.githubusercontent.com/5943778/39865547-ea00fc8e-5455-11e8-8ec4-51d9bcf17407.png)

**Comment by kondapally1989** [comment]
Known issue https://github.com/kubernetes-client/java/issues/86
see https://github.com/kubernetes-client/java/issues/86#issuecomment-334981383
This error may arise for all delete K8 objects.

**Comment by brendandburns** [comment]
Closing as duplicate.
