### ISSUE TITLE
Error when trying to call patchNode

### ISSUE THREAD

**Issue by ohadmuch** [kubernetes-client/java#263]
Using version 1.0.0

When calling **CoreV1Api** **patchNode** method the call fails because the inner methods set the wrong content type, the content type should be : **"application/merge-patch+json"**

when setting it manually the call succeed

**Comment by kondapally1989** [comment]
know issue https://github.com/kubernetes-client/java/issues/127

will arise for all patch calls

use JSON PATCH, which will not throw any error: 
example:  https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java

**Comment by brendandburns** [comment]
closing as duplicate.

**Comment by costimuraru** [comment]
The `PatchExample` shows how to patch a Deployment.
```
 ExtensionsV1beta1Deployment deploy =
api.patchNamespacedDeployment(deployName, namespace, body, pretty);
```

But there is no `api.patchNode` there.

Ideas?

**Comment by Baaamm** [comment]
Same problem here. I want to make this call with the api: kubectl taint nodes <node-name> testKey=value:NoExecute

is it possible? I got: 

Internal Server Error, Response Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"json: cannot unmarshal object into Go value of type jsonpatch.Patch","code":500}
