### ISSUE TITLE
Unknown apiVersionKind secrets-store.csi.x-k8s.io/v1/SecretProviderClass is it registered?   - K8S java client 

### ISSUE THREAD

**Issue by payalgodhanioracle** [kubernetes-client/java#2655]
**Describe the bug**
Unknown apiVersionKind secrets-store.csi.x-k8s.io/v1/SecretProviderClass is it registered?   

Error Stack

Failed to load resources:
java.io.IOException: Unknown apiVersionKind secrets-store.csi.x-k8s.io/v1/SecretProviderClass is it registered?
	at io.kubernetes.client.util.Yaml.modelMapper(Yaml.java:554)
	at io.kubernetes.client.util.Yaml.loadAll(Yaml.java:179)
	at io.kubernetes.client.util.Yaml.loadAll(Yaml.java:145)

**Client Version**
e.g. `17.0.2 and 18.0.0`

**Kubernetes Version**
e.g. `1.23.4`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**
Should be able to create the resource - secrets-store.csi.x-k8s.io
This resource can be created with kubectl and helm manually but not with Java K8S client. We see that the fix is already in the master branch. This is the pull request which was merged but there was no java client release post this.

https://github.com/kubernetes-client/java/pull/2620

Could we create a new release from the master branch or have an ETA for the next release ?

**Comment by brendandburns** [comment]
I don't think that this is the issue that you referenced.

This library only has the built-in resources by default. That resource is a custom resource (CRD) that is dynamically loaded into the cluster. You need to either register your own implementation of that resource using the `ModelMapper` class or you need to use the `generic` client as shown here:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-15/src/main/java/io/kubernetes/client/examples/GenericClientExample.java

There are also instructions here:
https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model

If you want to generate the client models from an OpenAPI specification.

**Comment by payalgodhanioracle** [comment]
The SecretProviderClass is registered with the cluster, and we still see the above error and we see that it works fine with kubectl
