### ISSUE TITLE
When watch stops...

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [kubernetes-client/java#266]
Hello.
I want to know why the watch stops throwing an exception.
I did my own scheduler and I need to watch if the pod status is "pending".
When the watch finds it, it schedules. But after it, when do not have pod pending anymore, 
an exception is thrown.
Why?

`public static void main( String[] args ) throws Exception {
		// This configuration doesn't use the Config file
		// You should change it if necessary
		ApiClient client = ClusterConnection.SetEnv();
		client.setConnectTimeout(3600);
		Configuration.setDefaultApiClient(client);

		CoreV1Api v1 = new CoreV1Api(client);

		// This name refers to the scheduler set in the deployment file
		String schedulerName = "gfads";
		String namespace = "teste";

		// Retrieving Pods events
		Watch<V1Pod> w = Watch.createWatch(client, 
				v1.listNamespacedPodCall(namespace, null, null, null, null, null, 
						null, 
						null, null, true, null, null), 
				new TypeToken<Watch.Response<V1Pod>>() {}.getType());

		// For all pods events
		for( Watch.Response<V1Pod> event : w ) {
			System.out.println(event.object);
			// check if the pod is "pending" and its scheduller name is the same of ours
			// the follwing code is inspired in this example:
			// https://github.com/kubernetes-client/java/blob/997c088f88fffba5d9195ce91fad89dddb57cff4/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java
			if( "Pending".equals(event.object.getStatus().getPhase()) &&
					schedulerName.contains(event.object.getSpec().getSchedulerName()) ) {
					//schedulerName.equals(event.object.getSpec().getSchedulerName()) ) {

				System.out.println("Scheduling " + event.object.getMetadata().getName());
				// apply the binding and attach the pod to a node
				V1Binding res = scheduler(v1, event.object.getMetadata().getName(), getNodesAvailable(v1));

			}

		}

		// This code are trowing an exception "io.kubernetes.client.ApiException: Conflict"
		// I don't know why, but the code is working fine even with this exception
	}
}
`

**Comment by brendandburns** [comment]
Watches will timeout once in a while, you should wrap any Watch in a `while (true) { ... }` loop.
