### ISSUE TITLE
sundrio heads up and downstream project check

### ISSUE THREAD

**Issue by iocanel** [kubernetes-client/java#2673]
In sundrio we are exploring the possiblity of merging `Fluent` and `FluentImpl` classes in order to reduce the amount of generated code.
The pull request can be found here: https://github.com/sundrio/sundrio/pull/368.

It would be great to know before hand how this change is going to affect you.

That being said we've added a new github action so that we check how each pull request affects downstream projects and it might be a good idea to include the official java client for kubernetes too (see https://github.com/sundrio/sundrio/issues/377).

**Comment by brendandburns** [comment]
I don't think we really mind that much. We generally only re-create the builders across Kubernetes minor versions where there are potentially API changes anyway. Especially if the generated Builder classes stay mostly the same, I don't think there will be impact.

**Comment by iocanel** [comment]
The generated class will be mostly the same. The only thing that changes are internals (Fluent and FluentImpl). Unless you explicitly extend or implement those by hand, you should be fine.
