### ISSUE TITLE
Getting IllegalThreadStateException 

### ISSUE THREAD

**Issue by irfanjs** [kubernetes-client/java#2674]
**Describe the bug**
We are using EKS and trying to fetch the kubernetes objects using java client . Followed the step as per doc and example given. However, it is giving exception after fetching few PODs 

**Client Version**
15

**Kubernetes Version**
AWS EKS : 1.23 

**Java Version**
17

**To Reproduce**
Follow the steps mention in doc 
Getting below error : 

```
[WARNING] thread Thread[OkHttp xxx.com,5,com.oe.kubernetesapi.ListNodes] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[OkHttp xxx.com,5,com.oe.kubernetesapi.ListNodes] will linger despite being asked to die via interruption
[WARNING] thread Thread[OkHttp TaskRunner,5,com.oe.kubernetesapi.ListNodes] will linger despite being asked to die via interruption
[WARNING] thread Thread[OkHttp TaskRunner,5,com.oe.kubernetesapi.ListNodes] will linger despite being asked to die via interruption
[WARNING] thread Thread[OkHttp TaskRunner,5,com.oe.kubernetesapi.ListNodes] will linger despite being asked to die via interruption
[WARNING] NOTE: 4 thread(s) did not finish despite being asked to via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.oe.kubernetesapi.ListNodes,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:803)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:319)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)

```
**Expected behavior**
JAVA client should run and fetch the PODs / list of nodes without any exception and warnings  

**KubeConfig**
Not attached. will attach later if required. very big config file 

**Server (please complete the following information):**
 - OS: [ UBUNTU : 22.04 LTS]
 - Environment [ local ]
 - Cloud [ AWS]

**Additional context**
Java client is fetching pods and giving up after few seconds with above exception . I have increased the time out as well to 3 min. , still the same issue . Not sure what is the issue . Please suggest

**Comment by brendandburns** [comment]
That exception stack trace does not appear to be coming out of the kubernetes client code. We need more details to determine if this is a client issue or if it is a problem with your code.
