### ISSUE TITLE
Wrong Status in Pod Conditions

### ISSUE THREAD

**Issue by manishkrishan** [kubernetes-client/java#2691]
**Describe the bug**

`io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPod(String, String, Boolean, String, String, String, Integer, String, String, Integer, Boolean)` returns wrong status through `io.kubernetes.client.openapi.models.V1PodCondition.getStatus()` after POD restarts (although POD is in healthy state). Problem is with only when there is single POD. Works fine if there are multiple pods with same selector. Works fine after restarting the JAVA application with same POD (no change in state).

**Sample code**
~~~
List<V1Pod> getPods(String appName) {
   try {
      List<V1Pod> pods = new ArrayList<V1Pod>();
      Configuration.setDefaultApiClient(Config.defaultClient());
      CoreV1Api api = new CoreV1Api();
      V1PodList list = api.listNamespacedPod(<ns>, null, null, null, null, "app="+appName, null, null, null, null, false);

      if (list != null) {
         for (V1Pod pod : list.getItems()) {
            List<V1PodCondition> podConditions = pod.getStatus().getConditions();
            for (V1PodCondition item : podConditions) {
               logMessage("type = " + item.getType() + ", status = " + item.getStatus());
               if ((item.getType().compareTo("Ready") == 0) && (item.getStatus().compareTo("True") == 0)) {
                  pods.add(pod);
               }
            }
         }
      }
      return pods;
   } catch (Exception ex) {
      // . . . 
   }
   return null;
}
~~~

We have a job which keep polling the active pods. When it works fine with single POD, it print below logs:

~~~
type = Initialized, status = True
type = Ready, status = True
type = ContainersReady, status = True
type = PodScheduled, status = True
~~~

After pod restarts, it print below:
~~~
type = Initialized, status = True
type = Ready, status = False
type = ContainersReady, status = False
type = PodScheduled, status = True
~~~

But if I restart my java app (JVM), same app returns the correct status for same pod (no state change).

Direct kubectl cmd returns following:
~~~
kubectl get pods -n oac <my pod name> -o jsonpath="{.status.conditions}"
[{"lastProbeTime":null,"lastTransitionTime":"2023-05-31T09:31:28Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2023-06-01T10:01:24Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2023-06-01T10:01:24Z","status":"True","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2023-05-31T09:31:28Z","status":"True","type":"PodScheduled"}]
~~~

**Client Version**
`17.0`

**Kubernetes Version**
minikube version: v1.29.0

**Java Version**
Java 1.8.0.361

**Expected behavior**
Status should be same as getting after restarting the java application.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server:**
 - OS: Linux 7.8

**Comment by tamilselvan1102** [comment]
May be you have executed the Sample code before the pod get ready

**Comment by tamilselvan1102** [comment]
It may be because of [ReadinessProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes)

**Comment by manishkrishan** [comment]
I have updated the output direct from `kubectl` cmd which is correct but sample returns it incorrectly even after I get correct output from `kubectl` until I restart java app using sample. It looks like something is cached in `kubernetes-client`.

**Comment by tamilselvan1102** [comment]
Are you calling your java app function as a thread to check the pod status in a certain time interval ?

> List<V1Pod> getPods(String appName) {

**Comment by manishkrishan** [comment]
> to check the pod status in a certain time interval ?

yes, every 30 seconds

**Comment by brendandburns** [comment]
You may want to filter/print the state of the Pod. It's possible that you are getting some pods that are in the `Terminated` state.

I do not think that this is an issue with this client, since the client basically just parses the raw JSON that it is getting from the server in situations like this.

**Comment by brendandburns** [comment]
It's also the case that minikube v1.29.0 uses kubernetes 1.26 where the 18.0.0 Java client library is the right one to use. It's possible that there is a mis-match between the 17.0.0 library and Kubernetes 1.26, since 17.0.x was generated for kubernetes 1.25.x.

**Comment by manishkrishan** [comment]
Thankyou [brendandburns](https://github.com/brendandburns) for response.
1. There is no other `Terminated` pod, as mentioned there is only single pod which is restarted.
2. I don't think, this is due to some version mismatch because same env, same pod state, all works fine with restart of my java app.

**Comment by manishkrishan** [comment]
Also I tried Java client library 18.0.0 and see the same issue i.e. once single pod is restarted, K8S Java client lib is unable to fetch the pod condition correctly. Is there anyway to reset the internal caches or state ?

**Comment by brendandburns** [comment]
There are no internal caches or state in the client. It makes an HTTP call each time. Can you check the access logs on your server and make sure that it's actually making the call?

Also when you say 'restart' what do you mean, do you mean a new Pod (e.g. the Pod is recreated) or do you just mean the application inside the Pod crashes and is restarted by Kubernetes.

Because for a brief moment while the application is being restarted, the status _is_ expected to change because the application is being restarted.

**Comment by manishkrishan** [comment]
I am not sure how to check access logs on api server, as mention this is in minikube hence tried following

`minikube ssh 'docker logs $(docker ps -a -f name=k8s_kube-api --format={{.ID}})' | grep Get`

and I don't see any relevant logs in any case (working and non working)

'restart' means, restarting the java process which is calling `listNamespacedPod()` method in a background thread on every 30 second. There are 2 different pods running few containers, Pod1 is watching to Pod2 using `listNamespacedPod()` method. When pod2 restarts (due to any reason OOM Kill or something else) originally described problem happens. If I restart the Pod1 as well, all works fine. When Pod1 `podConditions` are reporting wrong Pod2 status at same time,  `kubectl get pods -n oac <my pod name> -o jsonpath="{.status.conditions}"` returning correct status.

**Comment by brendandburns** [comment]
As above, I don't believe that this is caused by a bug in this client, though anything is possible. At this point if you want to investigate further, I think you will need to rebuild the client yourself and add some debugging code to figure out where something is going wrong. There's not enough information here to determine what the problem is.

If you figure out what the problem is and it actually is a problem in this client, please feel free to update this issue with more details on the root cause.

**Comment by manishkrishan** [comment]
Thankyou [brendandburns](https://github.com/brendandburns) ,  I will try by enabling debug logs.
