### ISSUE TITLE
Unable to select context programatically

### ISSUE THREAD

**Issue by henrik242** [kubernetes-client/java#2701]
I create a `CoreV1Api` like this, which uses the default context:
```
val apiClient = ClientBuilder.standard().build()
val api = CoreV1Api(apiClient)
```
During this process I have no access to the `KubeConfig` object, so I am unable to programatically set the current context (like in `kubectl config use-context ...`).

Is there a way to achieve this?

**Comment by brendandburns** [comment]
Closing this issue as I believe the question is answered. Please use `/reopen` if you need further assistance.

**Comment by henrik242** [comment]
Thanks!
