### ISSUE TITLE
V1JobBuilder not found

### ISSUE THREAD

**Issue by mcraj017** [kubernetes-client/java#2706]
**Describe the bug**
I have updated the client from 11.0.1 to 18.0.0 and I am not getting V1JobBuilder not found error

**Client Version**
`18.0.0`

**Java Version**
`Java 17`

**To Reproduce**
1. Try to create V1Job with V1JobBuilder

**Expected behavior**
V1JobBuilder should be detected by Inteliij

**Server (please complete the following information):**
 - OS: Mac
 - Environment : intellij

**Comment by brendandburns** [comment]
It's still there:

https://github.com/kubernetes-client/java/blob/master/fluent/src/main/java/io/kubernetes/client/openapi/models/V1JobBuilder.java#L5

But we re-packaged it as a separate dependency:
https://mvnrepository.com/artifact/io.kubernetes/client-java-api-fluent

I believe if you add that dependency to your project it should work correctly, if it doesn't please let us know.

**Comment by mcraj017** [comment]
it solves the issue thanks a lot
