### ISSUE TITLE
The wiki Code Examples chapter contains some broken hyper-links

### ISSUE THREAD

**Issue by aim-for-better** [kubernetes-client/java#2721]
**Describe the bug**
The wiki Code Examples chapter contains some broken hyper-links.

![image](https://github.com/kubernetes-client/java/assets/12733681/2a8daeb9-1656-49ee-8715-cf3ac86b62bd)

One example

![image](https://github.com/kubernetes-client/java/assets/12733681/7ccb927a-8aef-43d0-af70-53a4d2164bad)

And I have one forked repo to fix this https://github.com/aim-for-better/kubernetes-client-java-wiki
**Client Version**
e.g. `11.0.1`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by aim-for-better** [comment]
ping on this

**Comment by yue9944882** [comment]
wiki fixed, thanks for reporting this!
