### ISSUE TITLE
Requesting 18.0.x with backport of recent changes

### ISSUE THREAD

**Issue by mindgamer** [kubernetes-client/java#2722]
Hi @brendandburns,

I recently cherry picked a [fix](https://github.com/kubernetes-client/java/pull/2712#event-9596968867) to branch - 18.0.0. Would it be possible to cut a 18.0.x release to include my fix?

Thank you so much in advance!!

**Comment by mindgamer** [comment]
@brendandburns

**Comment by brendandburns** [comment]
I'm on vacation this week (through 7/12) but I will get to it sometime next week. If it's not done by 7/14 please feel free to ping this issue again.

Thanks

**Comment by mindgamer** [comment]
Thank you @brendandburns

**Comment by brendandburns** [comment]
18.0.1 was pushed to sonatype recently:

https://github.com/kubernetes-client/java/actions/runs/5511257377

It should be visible in maven central in ~24 hours.

Please let me know if you don't see it after EoD tomorrow.

**Comment by brendandburns** [comment]
I see this in maven central:
https://repo1.maven.org/maven2/io/kubernetes/client-java-api/18.0.1/

Closing this issue.

**Comment by mindgamer** [comment]
Thank you @brendandburns
