### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by nikhil4931** [kubernetes-client/java#2730]
**Describe the bug**
Getting SocketTimeoutException Read timed out error when trying to Access K8s Secrets and ConfigMaps.

**Client Version**
Not sure where to get this informatoon

**Kubernetes Version**
`13.0.2`

**Java Version**
     Java 17

**To Reproduce**
1. Use Java K8s library API's to fetch the configMaps and secrets
2. Completed role and role binding to the applications service account
3. After deploying the application, It's failing to get the secrets and throwing SocketTimeoutException

**Expected behavior**
Expected behavior is to get configMaps and secrets successfully

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Docker container
 - OCI

**Additional context**
1. I was able to SSH into pod via kubectl and I can confirm I can see all the required details in /var/run/secrets/kubernetes.io/serviceaccount/token
2. I executed this curl and it's working fine
**token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)**
**curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $token" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/{namespace}/configmaps/{name}**
removed actual namespace details
3. I am not sure why a curl is working and code is not able to fetch it.

**Comment by brendandburns** [comment]
Your curl is connecting to a configmap, and your example code is connecting to a Secret. Does your example code work if you try to get a ConfigMap?

**Comment by nikhil4931** [comment]
HI @brendandburns sorry for the confusion, My example code is not working for any of the resource but when I try the same things via CURL I am getting the response. To add one more point, Applications ServiceAccount has GET role for both ConfigMaps and Secrets

**Comment by brendandburns** [comment]
When you say "I executed this curl" did you do that inside the Pod? Or from your machine?

Your code looks correct to me, I suspect that there is some problem with your Pod.

**Comment by nikhil4931** [comment]
Yes I SSHd into pod and ran inside the Pod.

Same code is working in different namespace (different cluster) but failing in a particular namespace. I couldn't able to figure out whats the difference.

**Comment by nikhil4931** [comment]
Hi @brendandburns, could you please suggest how to debug this? I am certain that the code has no issues since it works in other K8s clusters. However, it is failing only in one particular cluster, and I am not able to figure out what the difference is.
