### ISSUE TITLE
Migrate to Jakarta EE to support spring boot 3.0

### ISSUE THREAD

**Issue by jiec-msft** [kubernetes-client/java#2751]
Hey team,

By reading the [Spring Boot 3.0 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee), in spring boot 3.0, `javax.annotation` should be upgraded to `jakarta.annotation`.  Such as in the code: https://github.com/kubernetes-client/java/blob/229d876feec4b93221912b32ec8cae48f64ca1d4/util/src/main/java/io/kubernetes/client/util/Strings.java#L15

But, looks like this project still depends on `javax.annotation:javax.annotation-api:1.3.2`. So will this project compatible with Spring Boot 3.0? Or can we update this dependency with Jakarta EE?

**Comment by brendandburns** [comment]
There's a duplicate discussion here:
https://github.com/kubernetes-client/java/issues/2606

I'm going to close this issue in favor of that one.

The tl;dr; is that we're open to migrating, but it requires work in the upstream code generator that someone needs to do.

Regarding Spring Boot 3.0 as far as I know it also requires an update to JDK 17 and at this time we have no plans to require JDK 17. This is discussed in this issue:

https://github.com/kubernetes-client/java/issues/2452

I'm happy to have further discussions or proposals in those issues.
