### ISSUE TITLE
New issue 

### ISSUE THREAD

**Issue by sandy99405** [kubernetes-client/java#2758]
**Describe the bug**

**Client Version**
e.g. `11.0.1`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by sandy99405** [comment]
Thanks

**Comment by brendandburns** [comment]
Please don't send spam issues.
