### ISSUE TITLE
Example code to list all pods results in Java error in IntelliJ

### ISSUE THREAD

**Issue by Simpson99091** [kubernetes-client/java#2761]
**Describe the bug**
Example code to list all pods results in Java error in IntelliJ.

**Client Version**
15.0.1

**Kubernetes Version**
n/a

**Java Version**
Java 11

**To Reproduce**
1. Start a new maven project in IntelliJ.  Include dependency in POM:
```
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java</artifactId>
    <version>15.0.1</version>
</dependency>
```

2. Copy the example code from https://github.com/kubernetes-client/java/wiki/3.-Code-Examples "list all pods:" into a new Java class.

**Expected behavior**
I expected to be able to compile the example code from https://github.com/kubernetes-client/java/wiki/3.-Code-Examples to list all pods and run it.  However, the IDE reports this as an error.

```
listPodForAllNamespaces(java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, ...)' in 'io.kubernetes.client.openapi.apis.CoreV1Api' cannot be applied to '(null, null, null, null, null, null, null, null, null)
```

Note: I was able to get it to work by adding an extra "null" to the parameter list!  But I'm not able to edit the Wiki.

**Comment by Mert18** [comment]
Yes, one null parameter is absent in the example code, this may confuse the starters. Is it really hard to change the wiki?
