### ISSUE TITLE
Unresolved dependency: 'io.kubernetes:client-java-proto:jar:18.0.0'

### ISSUE THREAD

**Issue by luochenzc** [kubernetes-client/java#2764]
**Describe the bug**

**Client Version**
e.g. `11.0.1`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
I'm not sure what the problem you are describing is. Can you fill in more details about the issue that you are facing?
