### ISSUE TITLE
Can CustomObjectsApi support all kind of kubernetesObject?

### ISSUE THREAD

**Issue by simsnow** [kubernetes-client/java#2765]
We have many project use k8s-sdk controll the cluster,
I am writing a self-sdk for our projects,
I want to use CustomObjectsApi to process all kind of kubernetesObject,
I found it hard code "/**apis**/{group}/{version}/", some "/**api**/{group}/{version}" not suitable for use,

I will hack it by "if group is empty use **api**, else use **apis**"

is that right, any other point that may happen?

**Comment by simsnow** [comment]
Here is the link to CustomObjectsApi. Maybe i can give a patch to make it more compatible...

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/apis/CustomObjectsApi.java#L80

**Comment by yue9944882** [comment]
> "/api/{group}/{version}"

the "/api" prefix only applies to those oldest legacy API such as pod, node. custom resources will be automatically registered under "/apis". you can also use "DynamicKuberentesClient" to build a path agnostic client

**Comment by simsnow** [comment]
@yue9944882 Thank you for help. I can't found a method like "listClusterCustomObjectCall" in DynamicKubernetesApi.

My basic business is "render a yaml, load the yaml, create some kubeObjects, watch the status, delete the kubeObjects"

Here is my code using **informer** to watch status

```
        CustomObjectsApi customObjectsApi = new CustomObjectsApi(client);
        GroupVersionResource groupVersionResource = ModelMapper.getGroupVersionResourceByClass(getApiType());
        SharedIndexInformer<T> informer = factory.sharedIndexInformerFor((CallGeneratorParams params) -> {
            return customObjectsApi.listClusterCustomObjectCall(groupVersionResource.getGroup(), groupVersionResource.getVersion(),
                    groupVersionResource.getResource(), null, null, null, null, null, null, params.resourceVersion, null, params.timeoutSeconds,
                    params.watch, null);
        }, getApiType(), getListType());

        informer.addEventHandler(new ResourceEventHandler<T>() {...});
```

**Comment by brendandburns** [comment]
`DynamicKubernetesApi` features a private call that does what you want:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L627

@yue9944882 we should consider making that public so that people can watch dynamic objects?

**Comment by InfiniteZh** [comment]
hey, I am use `customObject` too.
And I found that `patchNamespacedCustomObject` is only support json.
```java
public okhttp3.Call patchNamespacedCustomObjectCall {
...
final String[] localVarContentTypes = {
      "application/json-patch+json", "application/merge-patch+json"
    };
    final String localVarContentType =
        localVarApiClient.selectHeaderContentType(localVarContentTypes);
    localVarHeaderParams.put("Content-Type", localVarContentType);
...
}
```
``` java
public String selectHeaderContentType(String[] contentTypes) {
    if (contentTypes.length == 0 || contentTypes[0].equals("*/*")) {
      return "application/json";
    }
    for (String contentType : contentTypes) {
      if (isJsonMime(contentType)) {
        return contentType;
      }
    }
    return contentTypes[0];
  }
```
selectHeaderContentType will return directly at the first parmeter. 
right?
