### ISSUE TITLE
Umbrella Issue: Java8 incompatible dependencies

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#2774]
The following dependencies failed to be upgraded due to Java8 incompatibility:

- https://github.com/kubernetes-client/java/pull/2773
- https://github.com/kubernetes-client/java/pull/2771

**Comment by brendandburns** [comment]
Or do you want to jump straight to Java17?

**Comment by yue9944882** [comment]
> Alternately we could have a minor version for Java8 and a minor version for Java11 (e.g. 19.1.x == java8, 19.0.x == java11)

@brendandburns i'm not sure bumping major is easy to users to understand. maybe just adding a `.java8` suffix will be more intuitive? 🤔

regarding the spring 17 support, i think we can skip compiling for those java8 incompatible modules in our test job if we want to bump those dependencies to java11, so java8 users can still use the java8-compatible modules anyway. See this commit in https://github.com/kubernetes-client/java/pull/2773: https://github.com/kubernetes-client/java/pull/2773/commits/14f8bc6c1659c7c509e3afc5808631b3763be193, this will only require java17 for those who wants to opt-in to spring support.

as for mockito, i don't see the necessity to bump that at this point? since that it's just a test-dependency. probably we can figure out how to support java8 in long-term when there's a more convincing dependency needs us to upgrade in the future?

**Comment by brendandburns** [comment]
Ok, sounds good to me. I figured out how to handle the logback dependency that seemed to have a similar problem, so that's another one off the list.

We can defer this until we're really stuck.

**Comment by brendandburns** [comment]
Another Java11+ dependency:

https://github.com/kubernetes-client/java/pull/2782
