### ISSUE TITLE
Quantity not equal after serialization and deserialization.

### ISSUE THREAD

**Issue by doom15** [kubernetes-client/java#2783]
**Describe the bug**
Quantity with value "0.5Gi" not equal after serialization and deserialization.

**Client Version**
any

**Kubernetes Version**
any

**Java Version**
Java 8

**To Reproduce**
The whole process we are trying to do:
1. Assemble a deployment A and serialize it, save in mysql
2. Assemble another deployment B. deserialize deployment A.  
3. use equal method to compare A and B(we'd like to know if there was any roll-out upgrade)
 
But when we use the memory flavor 0.5Gi, the equals method will always return false even there isn't any change between A and B.
After some dig, I made a simplified demo below
```
public class Main {
    public static void main(String[] args) {
            compareQuantity("0.5Gi");
            compareQuantity("0.5G");
            compareQuantity("1Gi");
            compareQuantity("1G");
            compareQuantity("500Mi");
            compareQuantity("500M");
            compareQuantity("500m");
            compareQuantity("0.5");
            compareQuantity("1");
    }

    private static void compareQuantity(String value) {
        Quantity quantity = Quantity.fromString(value);
        // simulate the serialize-method
        String suffixedString = quantity.toSuffixedString();
        // simulate the deserialize-method, see io.kubernetes.client.custom.Quantity.QuantityAdapter
        Quantity deSerial = Quantity.fromString(suffixedString);
        boolean equals = Objects.equals(quantity, deSerial);

        PrintStream out = equals ? System.out : System.err;
        out.println("original value: " + value);
        out.println("quantity string: " + quantity.toSuffixedString() + "; format: " + quantity.getFormat());
        out.println("deSerial string: " + deSerial.toSuffixedString() + "; format: " + deSerial.getFormat());
        if (!equals) {
            out.println("NOT EQUAL");
        }
        out.println();
    }
}
```
 the 0.5Gi-Quantity is not equal.

**Dig more**

When we construc Quantity of 0.5Gi in method  QuantityFormatter::parse 
https://github.com/kubernetes-client/java/blob/cd7ce7db9b6018370ca1dfc437c6ef03490c13cd/kubernetes/src/main/java/io/kubernetes/client/custom/QuantityFormatter.java#L23-L36

we got a number which's scale is 1 (for the value 0.5) and binary format (for the prefix i) .
When we are going to serialize it in method QuantityFormatter::format
https://github.com/kubernetes-client/java/blob/cd7ce7db9b6018370ca1dfc437c6ef03490c13cd/kubernetes/src/main/java/io/kubernetes/client/custom/QuantityFormatter.java#L46-L60
we will fall into the case BINARY_SI, and will use the toBase10String method because the number's scaler > 0 and then isFractional will  be true.
So, we got an "DECIAMAL"  format when serialization. When we trying to deserialize it back. we got an diffrent format "DECIAMAL" instead of "BINARY" which cause the equals return false.

https://github.com/kubernetes-client/java/blob/cd7ce7db9b6018370ca1dfc437c6ef03490c13cd/kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java#L79-L91
It compare number and format.

**Suggestion**
I think we don't need the "format" in Quantity::equals method, which is just for serialization.  The "number" is ony we need for compare, which have been normalized with the unit of empty. 

any good idea ?

**Comment by brendandburns** [comment]
Thanks, we'd be happy to review a PR (please add unit tests also using the demo code above)

**Comment by doom15** [comment]
OK, will do it tomorrow
