### ISSUE TITLE
Example code is out of date.

### ISSUE THREAD

**Issue by Ananya2001-an** [kubernetes-client/java#2786]
**Describe the bug**
I tried running the example for `listPodForAllNamespaces` in my local maven project but it's giving me compilation error. The null values being passed as arguments to the method seems to be the problem. I am not sure if the example provided is wrong or something else seems to the issue here? The same thing happened with other methods as well...

```java
package com.example;

import io.kubernetes.client.openapi.ApiClient;
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.Configuration;
import io.kubernetes.client.openapi.apis.CoreV1Api;
import io.kubernetes.client.openapi.models.V1Pod;
import io.kubernetes.client.openapi.models.V1PodList;
import io.kubernetes.client.util.Config;
import java.io.IOException;

/**
 * A simple example of how to use the Java API
 *
 * <p>Easiest way to run this: mvn exec:java
 * -Dexec.mainClass="io.kubernetes.client.examples.Example"
 *
 * <p>From inside $REPO_DIR/examples
 */
public class KubernetesClientDemo {
  public static void main(String[] args) throws IOException, ApiException {
    ApiClient client = Config.defaultClient();
    Configuration.setDefaultApiClient(client);

    CoreV1Api api = new CoreV1Api();
    V1PodList list =
        api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null, null, null);
    for (V1Pod item : list.getItems()) {
      System.out.println(item.getMetadata().getName());
    }
  }
}
```

![Screenshot 2023-09-08 175233](https://github.com/kubernetes-client/java/assets/55504616/a4dea10c-5375-45e1-b234-7df1dc40df56)

**Client Version**
e.g. `18.0.1`

**Kubernetes Version**
minikube

**Java Version**
e.g. Java 11

**Expected behavior**
Should have listed all the pods.

**Server (please complete the following information):**
 - OS: [e.g. WSL]

**Comment by brendandburns** [comment]
Please re-read the error message. You are passing the wrong number of parameters. Passing nulls (at least for nullable types) is fine.

Closing this issue as it is not a problem with this client.

**Comment by brendandburns** [comment]
I realized that we haven't brought the examples forward for recent releases (e.g. 18.0.1) so the older examples are not correct. Reopening this issue to cover updating the examples.

**Comment by rohan-kapse** [comment]
is it still active?
