### ISSUE TITLE
Publishing proto files

### ISSUE THREAD

**Issue by Sleepy-GH** [kubernetes-client/java#2798]
More of a feature request then a bug report.

Is there any way the proto files could be shared either in the `client-java-proto` library or as a separate library?
This way people can reference these proto files from their own proto files.

Thank you!

**Comment by brendandburns** [comment]
These are already hosted elsewhere, e.g.

https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/generated.proto

There is a script here:
https://github.com/kubernetes-client/gen/blob/master/proto/dependencies.sh

That downloads a lot of them.

That script is probably out of date, fwiw, so if you make improvements please send a PR to the kubernetes-client/gen repo.

Thanks!

**Comment by Sleepy-GH** [comment]
It would be nice if they get hosted on maven central along the generated closed tho.

I can see if I can take a stab at it next week

**Comment by brendandburns** [comment]
I'm happy to review a PR if you get one together.

fwiw, I don't think those generated classes for proto have been rebuilt in a _long_ time (like multiple years :) so a first step might be to regenerate them for a modern Kubernetes release.
