### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/java#28]
This issue is to track the release process of the client (on maven?).

- [x] Figure out the owner email to be used in POM file (following up on #44)
- [x] Get the "io.kubernetes" namespace in maven central. I've run this past kubernetes-dev and kubernetes-sig-api-machinery without complaint. We just need the domain owner within google to file a JIRA ticket against sonatype.
- [x] Generate a GPG key for the client. We'll need someone in the kubernetes org to do this - Figure out where to store private key (odds are the private key will be stored by Google.)
- [x] Publish an initial release to maven central (and optionally make it public).

(Edited, adding and edited action items from lwander's comment bellow)

**Comment by mbohlool** [comment]
@brendandburns fyi. lwander is working on a maven release.

**Comment by lwander** [comment]
Quick update: 

- [ ] Get the "io.kubernetes" namespace in maven central. I've run this past kubernetes-dev and kubernetes-sig-api-machinery without complaint. We just need the domain owner within google to file a JIRA ticket against sonatype.
- [ ] Generate a GPG key for the client. We'll need someone in the kubernetes org to do this - odds are the private key will be stored by Google.
- [ ] Publish an initial release to maven central (and optionally make it public).
- [ ] Codify a CI release process that doesn't require us to store sonatype credentials on some hosted service.

**Comment by brendandburns** [comment]
Why does someone on Google need to request it?

Kubernetes is not a Google project.

I'm happy to do the request on behalf of the Kubernetes project, send me the link to the jira..

--brendan

________________________________

**Comment by lwander** [comment]
I believe the kubernetes.io domain name owner needs to request it, and it seems that google owns the domain. If you own the domain that would make things a lot easier :) Here is the guide for requesting our namespace: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by brendandburns** [comment]
I can get access to the DNS.. I'll see what I can do.

--brendan

________________________________

**Comment by lwander** [comment]
Awesome, thanks Brendan

**Comment by mbohlool** [comment]
@lwander I've added action items to the first comment. It is has some of your action items (I didn't add CI release process as we discussed, we maybe ok with manual release for now. We can automate it if we see it a big burden later).

**Comment by lwander** [comment]
Sounds good to me, thanks

**Comment by lwander** [comment]
As an alternative to using one kubernetes-wide GPG key, what do you think about each of us signing the release with our own key? This means the signature of the artifacts will differ depending on who ran the release.

**Comment by mbohlool** [comment]
I am not sure what is the norm, but as a user, I don't care who is doing
the release and just want to check signature. Having more than one key make
more confusion than any benefit to the user.

**Comment by lwander** [comment]
Agreed - I figured this was a reasonable alternative if we don't come up with a good way to share an org-wide key.

**Comment by lwander** [comment]
@mbohlool we have the group id, we just need to publish a signed artifact to make it official.

**Comment by mbohlool** [comment]
Nice. We just need to decide on GPG key. @brendandburns do you have any suggestion on where to put GPG key so we have have access to it?

**Comment by brendandburns** [comment]
Probably the correct place is some shared CNCF infrastructure.  But the story for shared infrastructure like that is pretty imperfect.


I'll send mail to the bootstrap committee to discuss...


--brendan



________________________________

**Comment by lwander** [comment]
I think we can safely close this, WDYT @mbohlool/@brendandburns

**Comment by mbohlool** [comment]
Sure. btw, do you think we are ready for a beta release? we can start another issue and list anything we need to do to release a beta version.

**Comment by lwander** [comment]
Yeah I'd be happy to run another release (0.2.0)? Is there something else special about it? I've had good luck running the client library listing, updating, & creating various resources so far for Spinnaker.

**Comment by mbohlool** [comment]
if alpha is resonably stable, we first need to see if we met all requirements of beta from [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/csi-new-client-library-procedure.md#client-support-level) (that I think we do), then we can release a beta. I suggest 1.0.0-beta.1.

**Comment by lwander** [comment]
Requirements I am not sure about: 

 * Works from within the cluster environment.
 * X509 Client certificate (inline and referenced by file)
 * Reasonably stable releases 

^ we've only done one release

Maybe I'll try a 0.2.0 release this week and if that goes off cleanly we'll promote to 1.0.0-beta.1?

**Comment by mbohlool** [comment]
Sure. we need to have a changelog too.

**Comment by lwander** [comment]
For 0.2.0 or the promotion to beta? I'll put one together.

**Comment by mbohlool** [comment]
I don't think there is any requirements for alpha. We should have it for beta though.

**Comment by lwander** [comment]
Ok sounds good. I'll work on this late this week at the earliest - I'm out at a conference

**Comment by rvowles** [comment]
I would recommend adding the Nexus maven plugin to the artifacts you release (i'm not sure if you release your reactor). If you put it in your 'release-sign-artifact' profile, it will automatically close & release it without having to use the UI in oss.sonatype.org

It looks like this:

`                        <plugin>
                                <groupId>org.sonatype.plugins</groupId>
                                <artifactId>nexus-staging-maven-plugin</artifactId>
                                <version>1.6.7</version>
                                <extensions>true</extensions>
                                <configuration>
                                        <serverId>sonatype-nexus-staging</serverId>
                                        <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                                        <autoReleaseAfterClose>true</autoReleaseAfterClose>
                                </configuration>
                        </plugin>` 

You would just need in your ~/.m2/settings.xml your credentials for sonatype-nexus-staging (which i see is at issue above).

**Comment by lwander** [comment]
Oh neat, thanks @rvowles

**Comment by lwander** [comment]
I think we can safely close as we've done two releases.
