### ISSUE TITLE
BatchV1Api createNamespacedJob io.kubernetes.client.openapi.ApiException: Unprocessable Entity

### ISSUE THREAD

**Issue by juefeiouran** [kubernetes-client/java#2822]
**Describe the bug**
use BatchV1Api.createNamespacedJob  but throws Exception
![image](https://github.com/kubernetes-client/java/assets/34408774/7d4c7faa-ce20-41a1-b20c-5c72cb4df865)

![image](https://github.com/kubernetes-client/java/assets/34408774/b2bb942f-85b6-4498-aefe-863af7342e6b)

param v1Job ：
![image](https://github.com/kubernetes-client/java/assets/34408774/4995c8cc-a299-40ea-880a-b2b9d615999d)

**Client Version**
![image](https://github.com/kubernetes-client/java/assets/34408774/f46cd417-6cd9-4b11-8d6b-539b4462f4f8)

**Java Version**
Java 8

**Comment by brendandburns** [comment]
Unprocessable Entity (422) indicates that your request is malformed. If you print `ApiException.getResponseBody()` you should get an error message that indicates why it is being rejected.

This is unlikely to be an error in the client, but rather a problem with your Job object, but if it does look like an error in this client, please update this issue with more details.
