### ISSUE TITLE
Unable to Load Custom Object as YAML

### ISSUE THREAD

**Issue by sdmichelini** [kubernetes-client/java#2823]
**Describe the bug**
Using the `Yaml.loadAll(..)` I cannot load a file with a non-registered CRD. Is there a way to use the Dynamic client to apply YAML from
YAML load? 

A use case I have is we have a CRD (AzureIdentity) and we want to be able to apply it from YAML without having to generate the CRDs and such.

**Client Version**
`17.0.2`

**Kubernetes Version**
 `1.26.6`

**Java Version**
 Java 17

**To Reproduce**

**Expected behavior**

**Server (please complete the following information):**
 - OS: Linux
 - Environment: container
 - Cloud: Azure

**Additional context**

**Comment by brendandburns** [comment]
Loading YAML requires a Java object to load the YAML into. However that Java object doesn't have to be generated, you can hand code a plain Java object that implements `KubernetesObject` if that is easier.

Once you have that hand coded object, you can use `ModelMapper` to register the group/version/kind to Java Object relationship and then the YAML loading should work correctly.

Hope that helps, let me know if you need further details.

**Comment by brendandburns** [comment]
It would also be possible to update the YAML loader so that it loaded into DynamicKubernetesObjects if it couldn't find a mapping. That's not it's behavior today, but it would be a useful PR if you wanted to send it.
