### ISSUE TITLE
BatchV1Api.createNamespacedJob Content-Type error

### ISSUE THREAD

**Issue by juefeiouran** [kubernetes-client/java#2825]
**Describe the bug**
The Content-Type of this method is incorrect, application/yaml is required, but application/json is provided by default

**Client Version**
18.0.1

**Kubernetes Version**
v1.27.2

**Java Version**
e.g. Java 8

![image](https://github.com/kubernetes-client/java/assets/34408774/3e0f4567-1526-4be0-b5ec-b94a7ed0fa55)

![image](https://github.com/kubernetes-client/java/assets/34408774/33e23747-ef19-4723-afc5-f9191f250e2b)
![image](https://github.com/kubernetes-client/java/assets/34408774/c5daf1ee-2ce2-4d9c-8b59-12e8578461c5)

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
That is not correct. Kubernetes accepts JSON as well as YAML (indeed it accepted JSON exclusively for a long time)

Closing this issue.
