### ISSUE TITLE
19.0.0 Release version not tagged

### ISSUE THREAD

**Issue by santhosh-vikraman** [kubernetes-client/java#2844]
**Describe the bug**
Recent release version ( 19.0.0) is not tagged and release details not updated. This is making confusion since there are breaking changes in the deployment like signature change in methods.

**Client Version**
N/A

**Kubernetes Version**
N/A

**Java Version**
N/A

**To Reproduce**
Applications using latest.release will be affected with signature changes and when they look for release changes its missing in the tags or releases

**Expected behavior**
Release version need to be tagged

**Additional context**

**Comment by brendandburns** [comment]
This is supposed to be done by the github action. Not sure why it didn't happen, I will investigate.

Note that maintaining the changelog is painfully manual. We'd be happy to take a PR to add automation for the changelog, but without that, it may not get updated regularly.

**Comment by rohan-kapse** [comment]
can i work on it?

**Comment by brendandburns** [comment]
@rohan-kapse If you want to work to add automation for the changelog, go for it.

**Comment by yue9944882** [comment]
the release workflow is here: https://github.com/kubernetes-client/java/actions/runs/6386007569 which is on commit `aded3583bfc27d698f91bcb341f615ccd6f562a4`. @brendandburns i think we can manually tag in the repo.

**Comment by brendandburns** [comment]
@yue9944882 yes, we can manually tag. The automation I was suggesting was for generating the changelog from the PRs that have merged...

**Comment by skdidwania** [comment]
Hi @brendandburns ,
I was wondering if you guys were able to tag the 19.0.0 release as I am still not able to view the release 19.0.0 on github.

Thanks
