### ISSUE TITLE
Using the jdk version lower than 1.8, throws an error Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by dreamcatcher-cx** [kubernetes-client/java#286]
hello:
my project is based on the jdk version of 1.7. because Java 1.7 default TLS protocol is v1.0, i receiveed the error.
the most direct way is to upgrade the jdk version，but my project environment does not currently allow this...
what should i do?

**Comment by brendandburns** [comment]
TLS 1.0 is insecure and generally unsupported by Kubernetes API servers. You should be able to change the protocol on the `HttpClient` 

An example of how to do this is here:

https://github.com/square/okhttp/issues/2372#issue-136531955
