### ISSUE TITLE
Duplicate classes shipped in client-java-api and client-java-api-fluent

### ISSUE THREAD

**Issue by stevenschlansker** [kubernetes-client/java#2874]
**Describe the bug**
We have an existing project that uses `client-java-api` jar. We add a new feature that uses `Kubectl` from `client-java-extended`. Extended has a transitive dependency on `client-java-api-fluent`. The Fluent jar ships many of the same class files as the api jar, leading to build errors like:

```
[ERROR] Found duplicate (but equal) classes in [io.kubernetes:client-java-api-fluent:19.0.0, io.kubernetes:client-java-api:19.0.0]:
[ERROR]   io.kubernetes.client.openapi.models.AdmissionregistrationV1ServiceReference
[ERROR]   io.kubernetes.client.openapi.models.AdmissionregistrationV1WebhookClientConfig
[ERROR]   io.kubernetes.client.openapi.models.ApiextensionsV1ServiceReference
[ERROR]   io.kubernetes.client.openapi.models.ApiextensionsV1WebhookClientConfig
[ERROR]   io.kubernetes.client.openapi.models.ApiregistrationV1ServiceReference
[ERROR]   io.kubernetes.client.openapi.models.AuthenticationV1TokenRequest
...
```

**Client Version**
19.0.0

**To Reproduce**
Have a build plugin that ensures no two JARs have the same class files.
Depend on `client-java-api-fluent` and `client-java-api` in the same build.

**Expected behavior**
Each class should exist in exactly one JAR file, instead of being duplicated between `client-java-api` and `client-java-api-fluent`

**Comment by brendandburns** [comment]
We'll take a look at this. Much of this is auto-magically generated so it's probably going to take some sleuthing to figure out what went wrong.

**Comment by stevenschlansker** [comment]
Well that sucks. Seems pretty pointless to bother diagnosing and reporting issues with k8s if they just close.

**Comment by svagner** [comment]
Especially because issue actual and for version 18...
