### ISSUE TITLE
Impossible to pass the Kubectl `--ignore-not-found=true` flag in the Java API

### ISSUE THREAD

**Issue by Bas83** [kubernetes-client/java#2876]
**Issue**

Impossible to pass the Kubectl `--ignore-not-found=true` flag in the Java API. This is causing us to have to catch exceptions and look pretty deeply into the returned object to figure out it's not an actual error.

**Client Version**

`19.0.0`

**Kubernetes Version**

Not relevant

**Java Version**

Java 17

**To Reproduce**

Delete an object that doesn't exist (anymore).
Get exception:

```
io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: v1
    code: 404
    details: class V1StatusDetails {
        causes: null
        group: batch
        kind: jobs
        name: training-job-748e6807-e980-467c-82d4-a7e94bc5cbc1-v2
        retryAfterSeconds: null
        uid: null
    }
    kind: Status
    message: jobs.batch "training-job-748e6807-e980-467c-82d4-a7e94bc5cbc1-v2" not found
    metadata: class V1ListMeta {
        _continue: null
        remainingItemCount: null
        resourceVersion: null
        selfLink: null
    }
    reason: NotFound
    status: Failure
}
	at io.kubernetes.client.util.generic.KubernetesApiResponse.lambda$throwsApiException$0(KubernetesApiResponse.java:64)
	at io.kubernetes.client.util.generic.KubernetesApiResponse.onFailure(KubernetesApiResponse.java:78)
	at io.kubernetes.client.util.generic.KubernetesApiResponse.throwsApiException(KubernetesApiResponse.java:62)
	at io.kubernetes.client.extended.kubectl.KubectlDelete.execute(KubectlDelete.java:36)
	... 206 common frames omitted
```
 

**Expected behavior**

Be able to set flag and not worry about deleting jobs that may or may not exist anymore.

**Server (please complete the following information):**
 - OS: Linux and Windows
 - Environmen: container and standalone cluster
 - Cloud: AWS

**Comment by brendandburns** [comment]
We would gladly take a PR to `KubectlDelete` to add this functionality.
