### ISSUE TITLE
connect the link between Deployment to its replica Set and follow to Pods ? 

### ISSUE THREAD

**Issue by mkarthiatgithub** [kubernetes-client/java#288]
** I do not know where to shoot this question, hence trying here

I use Kubernetes JAva API https://github.com/kubernetes-client/java 1.0.0

Here, how do one connect the link between Deployment to its replica Set and follow it Pods ? 

I see an api for listing all deployments for a given namespace.  It returns list of ExtensionsV1beta1Deployment ,which does not have ReplicaSet its producing. 
Hence , tracing a deployment to its replicaSet and then its pod seems challenging. Or is it just me don't know . Any help or direction will be useful

**Comment by brendandburns** [comment]
Have a look here:

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

You can work backward from `metadata.ownerReferences`

This is a Kubernetes API question, not a Java question, so I'm closing this issue.
