### ISSUE TITLE
coreApi.readNode() method exception has no details

### ISSUE THREAD

**Issue by guruguha** [kubernetes-client/java#2880]
**Describe the bug**
When using the Java client API to fetch node details, the API throws a runtime exception and doesn't provide any details as to why the exception happened. i.e., return value from `ex.getMessage()` is empty.

The only stack trace print is:

```
io.kubernetes.client.openapi.ApiException:
at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:973) ~[blob_p-3cd72cadcfba546d41cd13cdb234a4f19801cc6c-384eac9721a9464143f65d3b9a7c59fa:2.1.2]
at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885) ~[blob_p-3cd72cadcfba546d41cd13cdb234a4f19801cc6c-384eac9721a9464143f65d3b9a7c59fa:2.1.2]
at io.kubernetes.client.openapi.apis.CoreV1Api.readNodeWithHttpInfo(CoreV1Api.java:53351) ~[blob_p-3cd72cadcfba546d41cd13cdb234a4f19801cc6c-384eac9721a9464143f65d3b9a7c59fa:2.1.2]
at io.kubernetes.client.openapi.apis.CoreV1Api.readNode(CoreV1Api.java:53329) ~[blob_p-3cd72cadcfba546d41cd13cdb234a4f19801cc6c-384eac9721a9464143f65d3b9a7c59fa:2.1.2] 
```

**Client Version**
`18.0.1`

**Kubernetes Version**
`1.23`

**Java Version**
Java 8

**To Reproduce**
Try to fetch the AZ details of a specific node using the K8S API given the namespace and pod name:
```
ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);
String podName = System.getenv("POD_NAME");
String namespace = System.getenv("POD_NAMESPACE");
CoreV1Api coreApi = new CoreV1Api();
V1Pod pod = coreApi.readNamespacedPod(podName, namespace, null);
String nodeName = pod.getSpec().getNodeName();
V1Node node = coreApi.readNode(nodeName, null);
V1ObjectMeta metadata = node.getMetadata();
Map<String, String> labels = metadata.getLabels();
```

**Expected behavior**
It should clearly show what the error is.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Linux
 - Environment : EKS
 - Cloud : AWS 

**Additional context**

**Comment by Ananya2001-an** [comment]
Hey @guruguha the code seems to be running fine on my side...are your env vars set correctly? I am able to retrieve the labels at the end...

**Comment by guruguha** [comment]
@Ananya2001-an thanks for checking. I am running this on my Flink cluster. 
Current behavior is that it works and fetches the node labels correctly for Flink running with Spotify operator. It fails to fetch the node labels when running Flink with Apache operator. The cluster definition is the same and there is no difference in how I'm setting up the cluster.

**Comment by guruguha** [comment]
Also, the issue is that there is no exception message which makes this very cryptic and not at all helpful for debugging.

**Comment by brendandburns** [comment]
Have a look at the discussion here:
https://github.com/kubernetes-client/java/issues/2066

There are several ways to get additional information from the ApiException.

Ultimately someone needs to make a fix in the upstream code generator.
