### ISSUE TITLE
CustomObjectsApi : createClusterCustomObject example

### ISSUE THREAD

**Issue by anitad** [kubernetes-client/java#289]
Current example for createClusterCustomObject(group, version, plural, body, pretty) api , has the "body" parameter set to null. After setting it as a JSON object (CustomResource JSON) , api throws 500 internal server error , with no specific error message.

Eg. body = {
  "apiVersion": "<value>",
  "kind": "<value>",
  "metadata": {
   "name": "<value>"
  },
  "spec": {
    "deploymentName": "<value>",
    "replicas": 1
  }

Error message from the k8s apiserver - 
kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Object 'Kind' is missing in 'object has no kind field '\",\"code\":500}\n"

**Comment by brendandburns** [comment]
This is because the "kind" field in your body is emptystring.

You need to specify "kind" (although this should probably be a 422 code not a 500 code)
