### ISSUE TITLE
use overloading for required params

### ISSUE THREAD

**Issue by Ananya2001-an** [kubernetes-client/java#2890]
I feel that we should use method overloading to make it easier for users to call methods with just the required params...since passing all nulls is kind of a hustle... IMHO most of the times users are just passing these params as values to the methods and thus keeping in mind all the optional fields seems kind of less efficient... 

It sucks that we can't set default values for the params but at least this is better than what we are doing now... creating this option for the users would be nice :)  

can use **coreApi.createNamespacedPod(namespace, pod);** instead of this **coreApi.createNamespacedPod(namespace, pod, null, null, null, null);**

```java
createNamespacedPod(String namespace, V1Pod body){
     createNamespacedPod(namespace, body, null, null, null, null);
}

createNamespacedPod(namespace, body, {optional params}) { ... }
```

**Comment by brendandburns** [comment]
All of this code comes from a code generator (https://github.com/OpenAPITools/openapi-generator).

Using a code generator is the only way to sustainably keep up with the breadth of the Kubernetes API, but unfortunately, as you note, it leads to some less than ergonomic code.

There are two ways to move forward on this.
1) We could introduce some hand-crafted classes for commonly used methods (e.g. Pods, Namespaces, Deployments, etc) which provide this style of more friendly overloaded methods.

2) We could add options to the code generator, though it is somewhat challenging to figure out the right way to automatically generate all the different overloads.

If people are interested in #1, I think we would be happy to entertain PRs, but it's not something that the core maintainers are likely to implement in the near term.

**Comment by Ananya2001-an** [comment]
Yeah that sounds right... I guess 1) would be an easier option. I would like to look into it.

**Comment by Ananya2001-an** [comment]
Should we create these classes inside the extended folder?

**Comment by brendandburns** [comment]
extended is intended for truly optional stuff. I think it is fine to put this in `util`
