### ISSUE TITLE
Order-dependent flakiness in KubernetesInformerCreatorTest.testInformerInjection

### ISSUE THREAD

**Issue by yijut2** [kubernetes-client/java#2896]
**Describe the bug**
The order dependent flakiness was detected when KubernetesReconcilerCreatorTest.java was run before the KubernetesInformerCreatorTest. The error appeared at line 157 in KubernetesInformerCreatorTest. It was suppose to get 1 result the calling `getRequestedFor()`for specific `urlPattern`, however, the actual result was 2.

**Client Version**
Any

**Kubernetes Version**
Any

**Java Version**
Java 17

**To Reproduce**
`mvn install -pl spring -am -DskipTests`
(must setup iDFlakies on a Maven project - https://github.com/UT-SE-Research/iDFlakies)
`mvn -pl spring idflakies:detect -Ddetector.detector_type=random-class-method -Ddt.randomize.rounds=10 -Ddt.detector.original_order.all_must_pass=false`

**Expected behavior**
When calling the getRequestedFor() method in KubernetesInformerCreatorTest, we should get the return value as 1 since we only generated the object with specific QueryParam once in this test file.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Linux
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
Thanks for reporting. That tool looks interesting, we'll have to give it a try.

There are definitely flaky tests in this repostory. We've been gradually trying to fix all of them in order of occurence, and we'd be happy to take a PR to fix this flake.

**Comment by brendandburns** [comment]
Closed by #2897

**Comment by yijut2** [comment]
Thank you!
