### ISSUE TITLE
Can't see the source code in IntelliJ IDEA（Client-java-api-15.0.1.jar）

### ISSUE THREAD

**Issue by keepgoong** [kubernetes-client/java#2933]
IntelliJ IDEA：2022.3.1
JDK 11.0
MAVEN 3.8.7：

    <dependency>
      <groupId>io.kubernetes</groupId>
      <artifactId>client-java</artifactId>
      <version>15.0.1</version>
    </dependency>
------
I can't see the source code in client-java-api-15.0.1.jar.But I can see the source code in client-java-15.0.1.jar.
For example:
![watch](https://github.com/kubernetes-client/java/assets/141293047/0bd48693-ab4e-40d1-9a01-b998a1346acb)
![corev1api](https://github.com/kubernetes-client/java/assets/141293047/ddeda554-6a20-42c4-b7cf-07c61c5f526c)

Here's what I've tried:
- 1.Change the source
    before:client-java-api-15.0.1.jar   change after:client-java-api-15.0.1-sources.jar 
    but this change didn't work,it changes back automatically,still use Client-java-api-15.0.1.jar.
![image](https://github.com/kubernetes-client/java/assets/141293047/1c677a13-bb11-4bc3-a96a-ee2d16806294)
- 2.Change Maven setting.
      I chose the following options
   ![屏幕截图 2023-12-06 232817](https://github.com/kubernetes-client/java/assets/141293047/a9caa8d0-624a-4409-aa77-4811d2ee771c)
     It will download source.jar and javadoc.jar,but it did't solve the problem.

How can I solve this problem? 
Maybe I should choose JDK 8?But part of my dependency requires JDK11...

**Comment by brendandburns** [comment]
I don't know how source code viewing in Intellij is supposed to work, so not sure if this is a problem with our library or with Intellij.

Given that this is pretty low-priority, I don't think we'll be fixing this anytime soon, but if you figure it out and send a PR we'd be happy to review it.

**Comment by piotom** [comment]
I had the same issue today and solved it by increasing the file size limit to 4MB in the Custom Properties in Intellij as follows:
>idea.max.intellisense.filesize=4000

It looks like the default value of 3MB is not for some of those files, i.e., CoreV1Api.java

See https://www.jetbrains.com/help/objc/configuring-file-size-limit.html

**Comment by keepgoong** [comment]
@piotom Thank you very much! This solves the problem perfectly!
![image](https://github.com/kubernetes-client/java/assets/141293047/ed29112a-ebef-4ec8-a1ba-9e02c1e8b299)
