### ISSUE TITLE
OkHttp3.Call doesn't have timeout by default

### ISSUE THREAD

**Issue by bacek** [kubernetes-client/java#2935]
**Describe the bug**
Java Client is using OkHttp3.Call for most (all?) of processing. Default OkHttp3.Call doesn't have timeout configured.

Which leads to problems like `apiClient` hanging in case of network bleeps.

**Client Version**
`19.0.0`

**Kubernetes Version**
`1.26`

**Java Version**
Java 11

**To Reproduce**

**Expected behavior**
apiClient calls not to hang forever.

**Additional context**
We have tightly locked k8s cluster with Istio. We submit a lot (1000+) jobs to k8s using `batch/job`.

When load burst happens, istio-proxy can have some hiccup, with errors like this:
```
WARNING: A connection to https://172.20.0.1/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

When this happen call 
```
batchApi.createNamespacedJob(this.namespace, job, null, null, "k8sBatchService", FIELD_VALIDATION);
```

just hangs forever.

**Comment by brendandburns** [comment]
Ok. This would require an upstream change in the code generator here:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache

If someone sends a PR there, we can then incorporate it into this library.

If you don't want to do that, you can also manually create the HTTP client yourself and pass it in to ApiClient:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L152
