### ISSUE TITLE
Which method returns the List of ingress in Core API 

### ISSUE THREAD

**Issue by irfanjs** [kubernetes-client/java#2937]
Hi,
using below code , we can list the PODs in all namespaces 

```
 ApiClient client = Config.defaultClient();
	        Configuration.setDefaultApiClient(client);

	        CoreV1Api api = new CoreV1Api();
	        V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null, null, null);
	        for (V1Pod item : list.getItems()) {
	            System.out.println(item.getMetadata().getName());
	        }
```

in the same way m how can we list the number of ingress in namespaces 
i got below code , but which method should be used to get the list of ingresses in core API  

  
    ```
	 ApiClient client = Config.defaultClient();
	        Configuration.setDefaultApiClient(client);
	        
                CoreV1Api api1 = new CoreV1Api();
	        V1IngressList list1 = null;
	        for (V1Ingress item : list1.getItems()) {
	            System.out.println(item.getMetadata().getName());
	        }

please suggest

**Comment by brendandburns** [comment]
There is an equivalent method `listIngressForAllNamespaces(...)` in the `NetworkingV1Api` object, you can instantiate it just like the `CoreV1Api`

**Comment by irfanjs** [comment]
@brendandburns 
Thanks. Do we have any method to just get the hostnames in given Ingress ??
Please suggest ..

**Comment by irfanjs** [comment]
@brendandburns . please suggest if any. 
Blocker for us
