### ISSUE TITLE
How to list Hosts associated with Ingress 

### ISSUE THREAD

**Issue by irfanjs** [kubernetes-client/java#2942]
Have below code to list the ingresses . do we have method to get the list of HOSTS associated with ingress ? Thanks 

           ```
     NetworkingV1Api netapi = new NetworkingV1Api();
	        V1IngressList list1 = netapi.listIngressForAllNamespaces(null, null, null, null, null, null, null, null, null, null, null);
	        
	        for (V1Ingress item : list1.getItems()) {
	            System.out.println("ingress list" + item.getMetadata().getName());
	        }
```

**Comment by irfanjs** [comment]
Please help / suggest

**Comment by brendandburns** [comment]
Sorry we can't provide help in how to program against the details of the Kubernetes API. There's lots of information on https://kubernetes.io 

If you find specific problems with the client please file new issues.

**Comment by irfanjs** [comment]
@brendandburns 
Im not asking help in programs but to know from where I can get help on documentation 
I did not find any such method in class definition so asking . 
if you have handy information , please help . Thanks
