### ISSUE TITLE
Exec.exec(namespace, podName, command, true, false)  java.net.SocketException: Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by ChenAdminChen** [kubernetes-client/java#2944]
maven version
 <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>18.0.0</version>
        </dependency>

Kubernetes Version: 1.26.1

Java Version: Java 8

code:
![image](https://github.com/kubernetes-client/java/assets/32416945/4ea71909-f7af-4363-993c-d1b79fe44b48)

![34EB9E27-80BB-43be-AB59-D5B3035FD468](https://github.com/kubernetes-client/java/assets/32416945/a3678080-97b3-44b1-b0d4-6fc15712d149)

I can read the data I want, why would this problem still occur？？？？

**Comment by brendandburns** [comment]
I think there is a race between your async reading and the socket being closed by a server requesting a close. I think this is expected.

Basically your code is hanging on `read()` waiting for more data to come over the socket, but then a request comes to close the socket, so the socket gets closed, your async `read()` needs to be aborted and it will get this exception.

I think that in this case it is fine to just swallow the exception. It's possible that we need to do more in the `Exec` class to handle this more seamlessly. PRs to improve that are welcome.
