### ISSUE TITLE
How to list all namespaces in cluster 

### ISSUE THREAD

**Issue by irfanjs** [kubernetes-client/java#2969]
Have written following code to get list of all namespaces in cluster

```
public static void main(String[] args) throws ApiException, IOException {
		// TODO Auto-generated method stub
		
		ApiClient client = Config.defaultClient();
		Configuration.setDefaultApiClient(client);

                 V1NamespaceList li = new V1NamespaceList();
                li.getItems().forEach(x -> System.out.println(x.getMetadata().getName()));

}
```
but it is not returning list of namespaces .... Im not getting what is wrong. 
please suggest

**Comment by irfanjs** [comment]
I wrote another code , still not getting.  please suggest 

```
	ApiClient client = Config.defaultClient();
		Configuration.setDefaultApiClient(client);

		NetworkingV1Api netapi = new NetworkingV1Api();

		CoreV1Api api = new CoreV1Api();

		V1NamespaceList list2 = api.listNamespace(null, null, null, null, null, null, null, null, null, null);

		for (V1Namespace item : list2.getItems()) {
			String namespace = item.getMetadata().getNamespace();
			System.out.println(namespace);
		}
```

**Comment by brendandburns** [comment]
This issue queue is for bugs with the client, not general help programming against the Kubernetes API.

Please see the examples for places to learn:
https://github.com/kubernetes-client/java/tree/master/examples/examples-release-19

**Comment by irfanjs** [comment]
Thanks @brendandburns 
I tried searching / learning the examples , but did not get much about namespaces apart from the code which I have written 
Please suggest if possible

**Comment by irfanjs** [comment]
@brendandburns : 
I got the code to list the namespaces in given cluster. However, getting exception 

           ```
     CoreV1Api api = new CoreV1Api();
		ApiClient client = Config.defaultClient();
		Configuration.setDefaultApiClient(client);
		NetworkingV1Api netapi = new NetworkingV1Api();
		V1NamespaceList listOfns = api.listNamespace(null, null, null, null, null, null, null, null, null, null);
		V1IngressList list1 = netapi.listIngressForAllNamespaces(null, null, null, null, null, null, null, null, null,
				null);

               	for (V1Ingress item : list1.getItems()) {
			List<String> hosts = item.getSpec().getRules().stream().map(V1IngressRule::getHost).toList();

			for (int i = 0; i < hosts.size(); i++) {
				listOfTenants.add(hosts.get(i));
			}
		}

		System.out.println(listOfTenants);

```
         
ingress list is getting printed properly . However namespace list is not . not sure why ? below exception 

> 
> 19:11:32.777 [main] DEBUG io.kubernetes.client.util.KubeConfig - Obtained a token from aws
> Exception in thread "main" io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:80
> 	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:888)
> 	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespaceWithHttpInfo(CoreV1Api.java:29271)
> 	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespace(CoreV1Api.java:29164)
> 	at oe.kubeapi.cloudcontroller.swagger.swaggerui.TestName.main(TestName.java:47)
> Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:80
> 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
>  

to print the namespace list , it is not referring , default client which is set I guess . Please suggest

**Comment by irfanjs** [comment]
@brendandburns 
can you please suggest ?
