### ISSUE TITLE
Get Pod and Get Pods are not returning the status

### ISSUE THREAD

**Issue by gmorales-vertex** [kubernetes-client/java#2977]
Describe the bug
I'm trying to get pods details using the following APIs:
    Kubectl.get(V1Pod.class).namespace(NAMESPACE).name(podName).execute();

    coreV1Api
        .listNamespacedPod(
            namespace, null, null, null, null, null, null, null, null, null, null, null)
        .getItems()
 
Both of them of them are returning the Pod(s) but the reason is always null instead of showing "ImagePullBackOff" or the actual reasons/status of the pods.

kubectl get pods output:
edge-deployment-5789c5b759-r9fbq   0/1     ImagePullBackOff   0          22h

Client Version: 15.0.1

Kubernetes Version: 1.28.4

Java Version: 17

I think this is issue is also related to this issue [https://github.com/kubernetes-client/java/issues/2142](https://github.com/kubernetes-client/java/issues/2142)

"kubectl get pods -o yaml" command response: The status:reason is showing "ImagePullBackOff" but both of the APIs listed above are showing null/empty.

Also, the events ("kubectl get events") are not showing for this error. This issue can be easily replicated by specifying wrong image name in the deployment.

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-06T18:52:13Z"
    generateName: edge-deployment-5789c5b759-
    labels:
      app: edge
      clusterId: cfff8e30-298e-4608-8636-00890a8adf03
      clusterName: glenn-k3s-edge
      imageName: glenn-SR-15-image
      mduVersion: 234f
      pod-template-hash: 5789c5b759
    name: edge-deployment-5789c5b759-svb96
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: edge-deployment-5789c5b759
      uid: 1cd8c921-0315-4325-8818-fc4abfbd0cde
    resourceVersion: "296262"
    uid: f09c3902-c1db-41f8-912c-e0c1c3588d62
  spec:
    containers:
    - env:
      - name: ite_metrics_enabled
        value: "true"
      - name: ite_metrics_schedule
        value: "30000"
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      image: glennmorales/testsr15:gcm-SR-15-4887
      imagePullPolicy: Always
      name: edge
      ports:
      - containerPort: 8585
        name: edge-port
        protocol: TCP
      - containerPort: 9001
        name: prometheus-port
        protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 5124Mi
        requests:
          cpu: "1"
          memory: 4024Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-7zrvm
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    imagePullSecrets:
    - name: gcm-k3s-secret
    nodeName: lima-rancher-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-7zrvm
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-06T18:52:13Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-06T18:52:13Z"
      message: 'containers with unready status: [edge]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-06T18:52:13Z"
      message: 'containers with unready status: [edge]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-06T18:52:13Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - image: glennmorales/testsr15:gcm-SR-15-4887
      imageID: ""
      lastState: {}
      name: edge
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: Back-off pulling image "glennmorales/testsr15:gcm-SR-15-4887"
          reason: ImagePullBackOff
    hostIP: 192.168.5.15
    phase: Pending
    podIP: 10.42.0.27
    podIPs:
    - ip: 10.42.0.27
    qosClass: Burstable
    startTime: "2024-01-06T18:52:13Z"
kind: List
metadata:
  resourceVersion: ""
```

**Comment by brendandburns** [comment]
You will want to run `kubectl get pods -o yaml` which will dump the YAML object returned. That object is what is parsed into the `V1Pod` object. Looking at the YAML will enable you to figure out which fields you have available.

I believe that the ImagePullBackOff actually comes from the events associated with the pod, in which case you will need to make a call to get events, not just get pods.

`kubectl` is a fairly complex piece of client-side code. It is not 1-1 with this client library.

If you can find a field in `kubectl get pods -o yaml` which is not present in the Java client, then that is a bug, please update this issue with that information, including the YAML output.

**Comment by gmorales-vertex** [comment]
updated the ticket.. please see changes.

**Comment by brendandburns** [comment]
Thanks for the YAML.

Just for complete clarity, when you look at `pods.getItems()[0].status.containerStatuses[0].state.waiting.reason` via this client the value is null?

Please make sure that you are looking in the `containerStatuses` array and not elsewhere, there is a pod status also, but it is not usually filled in.

Container Statuses:
https://github.com/kubernetes-client/java/blob/f8f6ca6bdb1ffa265b29e05ff483d16a40ea5d31/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1PodStatus.java#L136

Pod Status (generally not filled in)
https://github.com/kubernetes-client/java/blob/f8f6ca6bdb1ffa265b29e05ff483d16a40ea5d31/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1PodStatus.java#L88

**Comment by gmorales-vertex** [comment]
<img width="1614" alt="Screenshot 2024-01-08 at 11 26 26 AM" src="https://github.com/kubernetes-client/java/assets/123597311/60265e44-cd00-4929-a7fc-0b60586a55ab">

I can see the status now in `pods.getItems()[0].status.containerStatuses[0].state.waiting.reason`

I think this will work us now.

Yeah POD - pods.getItems()[0].status.reason is always null

Thank you for helping us on how to retrieve the actual pod status. 
You may close this ticket now.
