### ISSUE TITLE
Recent release version ( 19.0.0) is not tagged and release details not updated.

### ISSUE THREAD

**Issue by skdidwania** [kubernetes-client/java#2980]
**Describe the bug**
Recent release version ( 19.0.0) is not tagged and release details not updated. This is making confusion since there are breaking changes in the deployment like signature change in methods

**Client Version**
e.g. N/A

**Kubernetes Version**
e.g. N/A

**Java Version**
e.g. N/A

**To Reproduce**
Applications using latest.release will be affected with signature changes and when they look for release changes its missing in the tags or releases

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
Thanks for reporting this, something must have gone wrong in the automation, we'll look into it.

In the meantime the branch is here:
https://github.com/kubernetes-client/java/tree/automated-release-19.0.0

Given that it is a major version change, and we track Kubernetes releases, method signature changes are expected.
