### ISSUE TITLE
kubernetes-client is not ready for kubernetes version 1.28

### ISSUE THREAD

**Issue by gladhiola** [kubernetes-client/java#2998]
**Describe the bug**
java kubernetes-client is missing from https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility for kubernetes version 1.28

**Client Version**
?

**Kubernetes Version**
1.28

Could you please give some information when will it be available?
Thanks!

**Comment by brendandburns** [comment]
We do need to regenerate the code for 1.28, but this client should mostly work. Any new APIs added in 1.28 (or APIs that changed) won't be available, but the core APIs should work correctly.

We are in the process of some major refactors to modernize this library for Java11+, so it's going to be a few weeks before we get a 20.0.0 release ready.

But as I said, the 19.0.0 client should mostly work with Kubernetes 1.28

**Comment by gladhiola** [comment]
Thanks for the information, then we will go with 19.0.0!
