### ISSUE TITLE
Websocket POST vs GET

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/java#30]
Created this issue to continue the discussion in #19 

TODO(mehdy): add a summary of discussion here.

I've digged a little more and found the issue that resulted in adding POST: https://github.com/kubernetes/kubernetes/issues/10366

I've also looked at kubernetes code, and GET and POST serving paths look the same (as far as I can tell).

The argument in kubernetes/kubernetes#10366 could be applied to SPDY or http/2 but not websocket. I think we should be fine with websocket GET only as the serving path is the same and there is no plan to remove GET from exec/attach/portforward serving stack in kubernetes.

Another solution for java client is to support SPDY/HTTP2 instead of websocket (we supported websocket for python client because there were no good SPDY client for python). This way we are not bounded by websocket limitation of GET.

cc: @brendandburns

**Comment by brendandburns** [comment]
Closing this, because we've conclusively gone with WebSockets and GET.
