### ISSUE TITLE
Yaml.loadAll fails, (guava version update resolves)

### ISSUE THREAD

**Issue by peterdnight** [kubernetes-client/java#300]
kubernetes java pom.xml guava version  is  `22.0`, but I ran into issues when running Yaml.loadAll under java 9 because the Yaml.classes member variable is not initialized (Yaml.initModelMap line 104). 

I was able to use the new api by adding the latest guava to my project pom (overriding the version specified by io.kubernetes.client-java:
```
		<dependency>
		  <groupId>com.google.guava</groupId>
		  <artifactId>guava</artifactId>
		  <version>25.1-jre</version>
		</dependency>
```

**Comment by brendandburns** [comment]
Thanks for the report, filed a PR to update dependencies.
