### ISSUE TITLE
Bad request for replaceNamespacedDeploymentScale

### ISSUE THREAD

**Issue by aboudzakaria** [kubernetes-client/java#303]
I'm trying to scale a deployment with the following code:

```
        V1beta2Deployment deployment = listDeployments.getItems().get(0);        

        ExtensionsV1beta1Scale body = new ExtensionsV1beta1Scale();
        body.setSpec(new ExtensionsV1beta1ScaleSpec());
        body.getSpec().setReplicas(2);
        
        ExtensionsV1beta1Scale scale = extensionsapi.replaceNamespacedDeploymentScale(deployment.getMetadata().getName(),
                deployment.getMetadata().getNamespace(), body, null);
```
However, I'm getting `io.kubernetes.client.ApiException: Bad Request` Exception
I'm not sure is it the correct way to do this?
The documentation is not clear about it or maybe I couldn't find the correct way to do this.
Thanks for your help.

**Comment by kondapally1989** [comment]
@aboudzakaria 
look at this https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AppsV1beta1Api.md#replaceNamespacedDeploymentScale

replaceNamespacedDeploymentScale expects AppsV1beta1Scale as body not Deployment. hence bad request.

if you are looking for deployment replace:-
https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AppsV1beta1Api.md#replaceNamespacedDeployment

**Comment by aboudzakaria** [comment]
oh I have messed up. it works now thanks! 
closing,
