### ISSUE TITLE
Can't debug Watch

### ISSUE THREAD

**Issue by gyorokpeter** [kubernetes-client/java#3101]
I'm getting an error:
```
java.lang.IllegalArgumentException: Expected the field `containers` to be an array in the JSON string but got `null`
```
However there seems to be no way to debug this because `Watch.next()` handles all of reading the response, parsing the JSON and converting to the target type all by itself with no way to print the results in between.

**Comment by yue9944882** [comment]
@gyorokpeter which client version are you using? is it `20.0.0`?

**Comment by yue9944882** [comment]
i think it's failing because the new client is not able to properly deserialize watch bookmark event from kube-apiserver. thanks for reporting the issue. i will try reproduce that locally
