### ISSUE TITLE
crd-model-gen generates models with javax annotations

### ISSUE THREAD

**Issue by kozjan** [kubernetes-client/java#3117]
**Describe the bug**
I am using `ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.6` to generate some models based on CRDs.
The generated code uses `@javax.annotation.Nullable` and `@javax.annotation.Generated` annotations.
Is it possible to generate code with Jakarta annotations?

I found this issue https://github.com/kubernetes-client/gen/issues/246 which supposedly allows use of `useJakartaEe` and I saw that this option is set to true here: https://github.com/kubernetes-client/gen/blob/master/openapi/java.xml#L105.
But last version of crd-model-gen was published 2 years ago and still has the older version.
I'm not sure, but maybe releasing new version would solve this problem?

**Client Version**
`1.19`

**Kubernetes Version**
`1.24`

**Java Version**
Java 8

**To Reproduce**
- generate models using `CRD Java Model Generate` workflow

**Expected behavior**
Generated code has jakarta annotations instead of javax.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Linux
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by kozjan** [comment]
I think it would also require updating commit here: https://github.com/kubernetes-client/java/blob/master/client-java-contrib/Dockerfile#L11
I will try to build this image with updated commit and see if it works

**Comment by brendandburns** [comment]
Great, thanks, if it works for you feel free to send a PR and we will rebuild the container image.

**Comment by kozjan** [comment]
hey @brendandburns, can you publish new container image?
