### ISSUE TITLE
Migrate from spock to normal junit (eventually jupiter)

### ISSUE THREAD

**Issue by codefromthecrypt** [kubernetes-client/java#3135]
Right now, E2E tests are using a different programming language, groovy, and a less used framework, spock. This complicates both the act of adding new tests as well dealing with dependencies.

At the time, it may have made sense to try something like Spock. However, if you look closely at the E2E tests, they are simple and neither need to use BDD style, nor need to use a different programming language.

Basic junit is easier for new maintainers and the code, and I believe this should be reverted to normal java. I'm happy to prove this in a PR if maintainers agree.

**Comment by brendandburns** [comment]
I'm fine with this normalization.

**Comment by codefromthecrypt** [comment]
> I'm fine with this normalization.

great. I'll raise a PR as it will make other infra migrations (like junit -> Jupiter) much easier and comprehensive as they'll also apply to E2E.
