### ISSUE TITLE
How to update Deployment with Volume (ConfigMap type) and VolumeMount

### ISSUE THREAD

**Issue by CathySha** [kubernetes-client/java#319]
I use ConfigMap as Volume in the deployment.
I'm trying to update a deployment with different Volume  (ConfigMap type) and VolumeMount.(see example below)
How to update the deployment?
Thank you!

Example:
The old Deployment is like this: (I only show the main part)

kind: Deployment
metadata:
name: d2
namespace: n1
spec:
replicas: 1
strategy:
rollingUpdate:
maxSurge: 0
maxUnavailable: 1
type: RollingUpdate
template:
metadata:
creationTimestamp: null
spec:
containers:
- image: x.x.x.x
imagePullPolicy: IfNotPresent
name: c2
resources:
limits:
cpu: "1"
memory: "4294967296"
requests:
cpu: 300m
memory: "536870912"
volumeMounts:
- mountPath: /var
name: configmapvolume1
- mountPath: /var/a
name: configmapvolume2
volumes:
- configMap:
defaultMode: 420
items:
- key: a.yml
path: a.yml
name: a
name: configmapvolume1
- configMap:
defaultMode: 420
items:
- key: c.yml
path: c.yml
name: a
name: configmapvolume2

The new Deployment is like this:(I only show the main part)

kind: Deployment
metadata:
name: d2
namespace: n1
spec:
replicas: 1
strategy:
rollingUpdate:
maxSurge: 0
maxUnavailable: 1
type: RollingUpdate
template:
metadata:
creationTimestamp: null
spec:
containers:
- image: x.x.x.x
imagePullPolicy: IfNotPresent
resources:
limits:
cpu: "1"
memory: "4294967296"
requests:
cpu: 300m
memory: "536870912"
volumeMounts:
- mountPath: /var/b
name: configmapvolume1
volumes:
- configMap:
defaultMode: 420
items:
- key: b.yml
path: b.yml
name: b
name: configmapvolume1

**Comment by brendandburns** [comment]
You can use replaceNamespacedDeployment:

https://github.com/kubernetes-client/java/blob/5f4b99a0720387a3e729f1312246943196c678ed/kubernetes/docs/AppsV1Api.md#replaceNamespacedDeployment

**Comment by CathySha** [comment]
@brendandburns 
Thank you for your answer.
I tried this function, and when it came to:
apiInstance.replaceNamespaceDeployment(deploymentName, namespaceName, body, pretty);

This error happens:
io.kubernetes.client ApiException: Unauthorized
Is this because the ApiKey I set into BearerToken was wrong?
Which key should I use? And how to get it?
Thank you very much!
