### ISSUE TITLE
Add independent lock

### ISSUE THREAD

**Issue by liran2000** [kubernetes-client/java#3247]
## Description

Add a lock class, not depends on leader election.

Usage high level guideline:
```
try {
  lock.lock(timeout); // blocking
  doSomeAction();
} finally {
  lock.unlock();
}
```

## Use cases

Actions which require distributed lock.

### implementation details - high level

- lock:
  - try to creates a lease.
  - if already exists, wait and try again until created, or timeout reached.
- unlock:
  - delete the lease.

Note that I have this implementation ready, so if confirmed, I can try opening a PR for it at _extended_ module.
Would appreciate feedback on proceeding with it.

**Comment by brendandburns** [comment]
What is the purpose of this class? We have several implementations of Lock already:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java

**Comment by liran2000** [comment]
Actions which require a distributed lock. How can lock/unlock usage be achieved with existing lock ?
Keep in mind this functionality commonly needed without leader election.

```
try {
  lock.lock(timeout); // blocking
  doSomeAction();
} finally {
  lock.unlock();
}
```

**Comment by brendandburns** [comment]
Is it that you want to be able to `unlock()`? If that is the case, I'd prefer that you added that to the existing leader election implementation vs adding a completely new implementation of locking/leader election.

There's not much difference between locking and leader election (except perhaps the unlock part) so I'd prefer to extend the existing implementations.

**Comment by liran2000** [comment]
Existing _LeaseLock_ implements [io.kubernetes.client.extended.leaderelection.Lock](https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/leaderelection/Lock.java), which is "[strictly for use by the leaderelection code](https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/leaderelection/Lock.java#L20)". Adding to it can feel like abuse.
I am thinking of implementing [java.util.concurrent.locks.Lock](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/locks/Lock.html), as encountered a need for it, for common usage.
What do you think ?

```
Lock lock = ...;
 if (lock.tryLock()) {
   try {
     // manipulate protected state
   } finally {
     lock.unlock();
   }
 } else {
   // perform alternative actions
 }
```

**Comment by brendandburns** [comment]
I think it's definitely fine to implement `java.util.concurrent.locks.Lock` but I believe that you can implement that using the `LeaderElector` class, you don't have to implement the lock acquire/retain/release code yourself.

That code is tricky to get right and we're better off focusing on a single implementation.
