### ISSUE TITLE
 V1.ConfigMapVolumeSource.newBuilder().setField()

### ISSUE THREAD

**Issue by dengyun19900722** [kubernetes-client/java#326]
when i use V1.ConfigMapVolumeSource.newBuilder().setField() to build  a ConfigMapVolumeSource, i don't know how to put the params.

**Comment by brendandburns** [comment]
There's a similar example here:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/test/java/io/kubernetes/client/models/V1PodBuilderTest.java

Does that help?

**Comment by brendandburns** [comment]
Closing this due to lack of response. Please re-open if you have more information to provide.

Thanks!
