### ISSUE TITLE
ReflectorRunnable restarting approximately every one minute.

### ISSUE THREAD

**Issue by xiaoyu1095** [kubernetes-client/java#3284]
**Describe the bug**

ReflectorRunnable.run().watchHandler(newWatch); when run "watch.hasNext()" throw a RuntimeException with "IO Exception during hasNext"

          if ((t instanceof RuntimeException)
              && t.getMessage() != null
              && t.getMessage().contains("IO Exception during hasNext")) {
            log.info("{}#Read timeout retry list and watch", this.apiTypeClass);
            // IO timeout should be taken as a normal case
            return;
          }

How can I avoid this issue?"

**Client Version**
`20.0.1`

**Kubernetes Version**
`1.23.6`

**Java Version**
Java 8

**Comment by brendandburns** [comment]
It's highly likely that the network connection to the your API server is closing for some reason. I would check your network.

**Comment by xiaoyu1095** [comment]
Thanks. By the way, can I use a generic client to submit all Kubernetes resources with the KubernetesObject type?
