### ISSUE TITLE
how to use batch/v1beta1 for v19.0.0 ?

### ISSUE THREAD

**Issue by robini** [kubernetes-client/java#3303]
i see since v17.0.0, there is no Class for batch/v1beta1. How to get batch/v1beta1 cronjob in v17.0.0+ version? 

**Client Version**
e.g. `19.0.0`

**Java Version**
e.g. Java 8

**Comment by brendandburns** [comment]
The v1beta1 API for CronJob was deprecated a long time ago. You need to migrate to the v1 version of the API, which is present in this library.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
