### ISSUE TITLE
Issues with in-cluster auto-configuration

### ISSUE THREAD

**Issue by pluttrell** [kubernetes-client/java#335]
I'm am experiencing Forbidden errors when running within a container within a cluster. I've tried this with version `2.0.0` and `3.0.0-beta1`.

Use case: We are packing all of our regression tests into containers and executing them as Kubernetes jobs. One of these regression test containers needs to take some action only after a cron job is run. So I'm using the java client to (1) copy the cronjob's configuration and (2) create a new (one-time) job and (3) watch that job, waiting for it's completion (or timeout).

The following code works locally as the auto-configuration is utilizing kubeconfig for the API server and authentication on my local box. But when I package the code up into the docker container and run it inside of a Kubernetes job/pod, I get the error listed below.

```java
    ApiClient client = Config.defaultClient();
    Configuration.setDefaultApiClient(client);
    V1beta1CronJob cronJob = new BatchV1beta1Api(client)
        .readNamespacedCronJob(cronJobName, namespace, null, null, null);
```

Error:
```bash
io.kubernetes.client.ApiException: Forbidden
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882) ~[client-java-3.0.0-beta1.jar!/:na]
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798) ~[client-java-3.0.0-beta1.jar!/:na]
	at io.kubernetes.client.apis.BatchV1beta1Api.readNamespacedCronJobWithHttpInfo(BatchV1beta1Api.java:1441) ~[client-java-api-3.0.0-beta1.jar!/:na]
	at io.kubernetes.client.apis.BatchV1beta1Api.readNamespacedCronJob(BatchV1beta1Api.java:1423) ~[client-java-api-3.0.0-beta1.jar!/:na]
```

When running within the cluster, it appears that the code is getting the proper API Server because I see that the value of `client.getBasePath())` is `https://x.x.x.x:443` where `x.x.x.x` is the IP assigned to the service named `kubernetes`.

Am I doing something wrong? Or not doing something that I need too? Thanks in advance.

**Comment by kondapally1989** [comment]
@pluttrell 
may be its rbac issue. ask your admin regarding serviceaccounts to be given for pod.

if its a local setup on which you are trying, may be for testing purpose give full access to all pods for api  authentication 
```
kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts
```

for more on rbac: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
before going for jar, you can also check with curl if  your pod has  access to kube API.
```
#kubectl exec <pod-name> -it bash
#KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
#curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/pods/$HOSTNAME
```

**Comment by pluttrell** [comment]
Confirmed, my issues was due to RBAC permissions. Many thanks for your help @kondapally1989!
