### ISSUE TITLE
Inner classes on io.kubernetes.client.JSON should be `static`

### ISSUE THREAD

**Issue by johnrengelman** [kubernetes-client/java#338]
There are a number of inner classes defined on the `io.kubernetes.client.JSON` classes and they are a mix of `static` and `non-static` inner classes. None of them are using instances variables from the wrapping `JSON` instance, so they should all be `static`.

Specifically https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/JSON.java#L198 and https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/JSON.java#L125

The current implementation causes issue when trying to initialize the GSON bindings are your own.

**Comment by brendandburns** [comment]
As @lwander says, this seems reasonable, but this code is generated. You need to make modifications here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/JSON.mustache

**Comment by arcturusInk** [comment]
I am interested in looking into this issue.

**Comment by saurav-malani** [comment]
Hello @lwander @brendandburns! I am new to kubernetes java-client. I would like to work on this issue. But, can you please explain the complete scenario and explain to me what exactly am I supposed to do?
