### ISSUE TITLE
list listPodForAllNamespaces error

### ISSUE THREAD

**Issue by luca-ma** [kubernetes-client/java#3390]
**Describe the bug**
Hi,
I'm using your example
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-18/src/main/java/io/kubernetes/client/examples/Example.java
to get all Pod in a K8s cluster.

CoreV1Api.listPodForAllNamespaces return a 401 response.

Could you suggest how to configure the client to correctly access the cluster?
thanks in advance
luca

**Client Version**
13.0.0

**Kubernetes Version**
1.29

**Java Version**
java 11

**Comment by brendandburns** [comment]
401 indicates that you are not authorized. That's probably not an error in this client, depending on where you are running the code you may need to add permissions for a pod service account or ensure that you have a kubeconfig file in the right location.

**Comment by brendandburns** [comment]
Also, client version 0.13.0 is_very_ old, please update to the latest client.

**Comment by luca-ma** [comment]
OK thank you
I'll switch to the latest version (20.0.1)
regards
luca

Il giorno mer 8 mag 2024 alle ore 18:31 Brendan Burns <
***@***.***> ha scritto:

**Comment by brendandburns** [comment]
That FAQ entry is for Pods running inside the cluster, but it sounds like you are accessing from outside the cluster.

In that case you need some way to authenticate and authorize your client. The easiest way to do that is to supply a Kubeconfig file, alternately you can set up the client programatically with a certificate/token for doing authentication, but that is definitely harder.
