### ISSUE TITLE
The CustomResourceDefinition "rayjobs.ray.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by xiaoyu1095** [kubernetes-client/java#3393]
FILE="rayjobs.yaml"
GROUP_NAME="io.ray"
PACKAGE="io.ray"

docker run \
  --rm \
  -v `pwd`/src/main/resources/crd/${FILE}:`pwd`/src/main/resources/crd/${FILE} \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/output:/tmp/output \
  -v "$(pwd)":"$(pwd)" \
  -ti \
  --network host \
  ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.6 \
  /generate.sh \
  -u `pwd`/src/main/resources/crd/${FILE} \
  -n ${GROUP_NAME} \
  -p ${PACKAGE} \
  -o "$(pwd)"

The CustomResourceDefinition "rayjobs.ray.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

**Comment by brendandburns** [comment]
I don't think that this issue is related to this repository. Closing. Please use `/reopen` if it is related to this repository and clarify the issue.

**Comment by free6om** [comment]
@xiaoyu1095 check [this](https://github.com/kubernetes-client/java/issues/2619#issuecomment-2232483076)
