### ISSUE TITLE
import io.kubernetes.client.util.Config; package not available in client-java-api-3.0.0-beta2-SNAPSHOT

### ISSUE THREAD

**Issue by devamtech** [kubernetes-client/java#341]
Hi,

I am trying to write below code,
ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);

but config is coming from util. In APi.3.0.0, there is no util package, Can you please tell me, where can I get util package

**Comment by maria** [comment]
I think they made a separate package https://github.com/kubernetes-client/java/tree/release-3.0/util

**Comment by brendandburns** [comment]
You need to run `mvn install` that should put all the right things in the right places...

**Comment by devamtech** [comment]
I did mvn install only but still util package is missing

**Comment by maria** [comment]
For me it worked if after I ran `mvn package` and `mvn install` in the root directory, I added to my pom file

```java
    <dependency>
      <groupId>io.kubernetes</groupId>
      <artifactId>client-java</artifactId>
      <version>3.0.0-beta2-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.kubernetes</groupId>
      <artifactId>client-java-api</artifactId>
      <version>3.0.0-beta2-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by maria** [comment]
`mvn install` does run `mvn package`, I was just playing it safe, I also did `mvn install` with all options for client-java-api and util packages. Another thing that I did was to ensure I create a jar with all dependencies. I am redoing this process and see how the docs should be updated, if needed.

**Comment by brendandburns** [comment]
I pushed `3.0.0-beta2-SNAPSHOT` and I think this is all fixed. I'm closing this for now, can someone re-open if there is a problem?

Thanks!
