### ISSUE TITLE
Invalid targetPort "cannot unmarshal object into Go value of type int32"

### ISSUE THREAD

**Issue by covolution** [kubernetes-client/java#345]
For Service creation the Java client api seems to be sending:
```
{
	"apiVersion": "v1",
	"kind": "Service",
	"metadata": {
		"name": "test-service"
	},
	"spec": {
		"ports": [{
			"name": "8180-tcp",
			"port": 8180,
			"protocol": "TCP",
			"targetPort": {
				"isInt": true,
				"intValue": 8180
			}
		}],
		"selector": {
			"app": "testpod"
		}
	}
}
```

This is resulting in a 
```
"message": "Service in version \"v1\" cannot be handled as a Service: v1.Service: Spec: v1.ServiceSpec: Selector: Ports: []v1.ServicePort: v1.ServicePort: TargetPort: unmarshalerDecoder: json: cannot unmarshal object into Go value of type int32, error found in #10 byte of ...|lue\":8180}}],\"select|..., bigger context ...|:\"TCP\",\"targetPort\":{\"isInt\":true,\"intValue\":8180}}],\"selector\":{\"app\":\"testpod\"}}}|...",

```
I tried with client `2.0.0` and `2.0.0-beta2`.  Any ideas?

**Comment by brendandburns** [comment]
This looks to me like you don't have the IntOrString Marshal/Demarshaller registered with your GSON.

How did you create the client?

Somehow this adapter here:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java#L12

Isn't getting registered with the the GSON encoder.

I will try to repro this locally...

**Comment by covolution** [comment]
The client is pulled in as a maven dependency.
```
    <dependency>
      <groupId>io.kubernetes</groupId>
      <artifactId>client-java</artifactId>
      <version>2.0.0-beta2</version>
    </dependency>
```
I checked the dependency tree and GSON 2.2.2 was being pulled in (via another transitive dependency).  I explicitly added GSON 2.6.2 and it works.
Thanks.
