### ISSUE TITLE
Bearer Token | Not able to get one

### ISSUE THREAD

**Issue by vaibhavswarnkar** [kubernetes-client/java#349]
I am trying to use **connectGetNamespacedPodExec** API which is asking for a TOKEN. I am running minikube and will be using GKE. As of now I am accessing other APIs through kubectl proxy. How to get the API TOKEN on minikube and also on GKE.

I am stuck here from a long time, any help is appreciated.

**Comment by brendandburns** [comment]
See here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Config.java#L92

**Comment by vaibhavswarnkar** [comment]
Thanks, got it working.
