### ISSUE TITLE
Get a Shell access to a pod

### ISSUE THREAD

**Issue by vaibhavswarnkar** [kubernetes-client/java#350]
Is there any REST API to open a shell like we do by command `kubectl exec -it {pod-name} -- /bin/bash` this opens a shell in the terminal and commands can be run inside the container.

I tried using exec API from the example and commands are executing also but there is an issue in it, for example: 
If I want to check the current path by typing the command `pwd`, I get a response like `/apps`. If I type command `cd ../` to go back and check the directory again, I get the same directory as `/apps`.

I need a shell-like access to a specific container in the pod, is there any way to do it?

**Comment by kondapally1989** [comment]
you can combine commands with ';' , '&&', '||' 
example:      **ls;pwd**

**Comment by vaibhavswarnkar** [comment]
@kondapally1989 I don't think this is a solution. I have to type a hundred commands, I am not going to use the said solution. I am simply trying to say, the Exec example is persisting the command result as in if I have traversed back in the directory structure, it should stay like that for the Exec session.

**Comment by vaibhavswarnkar** [comment]
I think Attach example is the one I am looking for (not sure, if someone can help me) 

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/AttachExample.java

I have tried using the attach API but I didn't get what it does, as I have tried giving input from my console and nothing has happened

**Comment by vaibhavswarnkar** [comment]
Any help?

**Comment by kondapally1989** [comment]
i think java exec implementation  does not support shell access similar to kubectl exec -it {pod-name} -- /bin/bash.  and attach may not serve the pupose https://github.com/kubernetes/kubernetes/issues/23335..

**Comment by swvaibhav** [comment]
@kondapally1989 I am trying to go through the codes of the minikube dashboard as it has Exec option which opens a shell in the dashboard and acts similar to `kubectl exec -it ---`. As the document says, everything in kubernetes is accessible via APIs then there must be an API for the same.

Another solution I am thinking of is to bring the Exec API underlying code on my own Java class, so that the below code is not executed everytime.

I went through the code, and the below code, opens a new websocket session eachtime it is executed.

`final Process proc =
	        exec.exec(
	            namespace,
	            name,
	            new String[] {"sh", "-c", "service nginx restart"},
	            true,
	            tty);` 

If the websocket session can be maintained and the commands to executed are executed on the same session each time, I think then it should emulate the Shell like access.

Any suggestion and comment?

**Comment by vaibhavswarnkar** [comment]
@kondapally1989 I am trying to go through the codes of the minikube dashboard as it has Exec option which opens a shell in the dashboard and acts similar to `kubectl exec -it ---`. As the document says, everything in kubernetes is accessible via APIs then there must be an API for the same.

Another solution I am thinking of is to bring the Exec API underlying code on my own Java class so that the below code is not executed every time.

I went through the code, and the below code opens a new WebSocket session each time it is executed.

`final Process proc = exec.exec( namespace, name, new String[] {"sh", "-c", "service nginx restart"}, true, tty);
`
If the WebSocket session can be maintained and the commands to execute are executed in the same session each time, I think then it should emulate the Shell like access.

Any suggestions and comments?

**Comment by brendandburns** [comment]
you just want to exec `sh` by itself. Probably want to set `tty` to `true` the `Process` object will have streams, you can then use those streams to execute new commands just like you would with a regular shell.

You can send `echo 'foo'\n` or whatever on the `InputStream` and the command will be executed by the shell.

This client library should be able to do everything that `kubectl exec ...` does.  (if not it's a bug)

**Comment by vaibhavswarnkar** [comment]
@kondapally1989 Thanks, but it keeps giving `java.net.SocketTimeoutException: Read timed out` error. I tried changing the `client.getHttpClient().setReadTimeout(0, TimeUnit.MILLISECONDS);` but it is still giving me the error.

**Comment by kondapally1989** [comment]
@vaibhavswarnkar  may be  sh -c in your program is causing shell to behave differently 
```
-c string
If the -c option is present, then commands are read from string. If there are arguments after the string, they are assigned to the positional parameters, starting with $0.  
```
following pgm worked if only sh is passed
```java
package io.kubernetes.client.examples;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

import com.google.common.io.ByteStreams;

import io.kubernetes.client.ApiClient;
import io.kubernetes.client.ApiException;
import io.kubernetes.client.Configuration;
import io.kubernetes.client.Exec;
import io.kubernetes.client.util.Config;

public class ExecEx {
public static void main(String[] args) throws ApiException, IOException, InterruptedException {
	ApiClient client = Config.defaultClient();
	client.getHttpClient().setReadTimeout(0l, TimeUnit.MILLISECONDS);

	Configuration.setDefaultApiClient(client);
	String name = "hello-world-58f9949f8-cxp7n"; // String | name of the Pod
	String namespace = "default"; // String | object name and auth scope, such as for teams and projects
	Boolean tty = true; // Boolean | TTY if true indicates that a tty will be allocated for the attach call. This is passed through the container runtime so the tty is allocated on the worker node by the container runtime. Defaults to false.
	
	Exec exec = new Exec();
    
    // final Process proc = exec.exec("default", "nginx-4217019353-k5sn9", new String[]
    //   {"sh", "-c", "echo foo"}, true, tty);
    final Process proc =
        exec.exec(
            namespace,
            name,
            new String[] {"sh"},
            true,
            tty);

    Thread in =
        new Thread(
            new Runnable() {
              public void run() {
                try {
                  ByteStreams.copy(System.in, proc.getOutputStream());
                } catch (IOException ex) {
                  ex.printStackTrace();
                }
              }
            });
    in.start();

    Thread out =
        new Thread(
            new Runnable() {
              public void run() {
                try {
                  ByteStreams.copy(proc.getInputStream(), System.out);
                } catch (IOException ex) {
                  ex.printStackTrace();
                }
              }
            });
    out.start();

    proc.waitFor();
    
    // wait for any last output; no need to wait for input thread
    out.join();
}
}

```

**Comment by vaibhavswarnkar** [comment]
@kondapally1989 I am not issuing `-c` command in the commands array. I have used the code given by you in your previous comment.

**Comment by kondapally1989** [comment]
for me pgm worked as expected. i have attached the screenshot of output. 
may be i am missing some thing. will look into this again.

![screenshot from 2018-08-28 10-48-03](https://user-images.githubusercontent.com/8391050/44702285-56add900-aab0-11e8-866e-d4845a525232.png)

**Comment by vaibhavswarnkar** [comment]
@kondapally1989 So I can get the like shell access, but after sometime the program is throwing the ` java.net.SocketTimeoutException: timeout` Error

**Comment by brendandburns** [comment]
You likely need to adjust your socket timeout on the client (and set if very large)

```java
ApiClient client = ...;
client.getHttpClient().setConnectTimeout(value, TimeUnit.SECONDS);
client.getHttpClient().setReadTimeout(value, TimeUnit.SECONDS);
client.getHttpClient().setWriteTimeout(value, TimeUnit.SECONDS);
```

--brendan

**Comment by brendandburns** [comment]
please re-open if you're still having problems.

Thanks

**Comment by vaibhavswarnkar** [comment]
What if I want to pass and get value from other than STDIN and STDOUT??

**Comment by brendanburns** [comment]
How do you want to pass things? Your options are stdout, stderr (output),
stdin, cmd line args (input)

**Comment by vaibhavswarnkar** [comment]
Well, I will be calling the Exec programme from another application by creating a WebSocket connection and then sending commands via WebSockets...

**Comment by ica10888** [comment]
There is an example for the exec program via webSocket. Include backend Springboot and frontend Xterm. Maybe help you.

https://github.com/ica10888/k8s-web-terminal

![avatar](https://github.com/ica10888/k8s-web-terminal/blob/master/doc/example.png?raw=true)

``` java

package com.kube.dto;

import io.kubernetes.client.ApiException;
import io.kubernetes.client.Exec;
import org.apache.log4j.Logger;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.io.*;
import java.util.Arrays;
import java.util.List;
import java.util.Map;


public class WsConnection extends  Thread {

    private InputStream inputStream ;
    private OutputStream outputStream;
    private Exec exec;
    private WebSocketSession session;
    private Pod pod;
    private ConsoleSize consoleSize;
    private Process proc;

    private static Logger logger = Logger.getLogger(WsConnection.class);

    public WsConnection(Map<String, String> stringStringMap, WebSocketSession session) {
        this.setSession(session);
        this.setExec( new Exec());
        this.setPod(new Pod(stringStringMap.get("name"),stringStringMap.get("namespace"),stringStringMap.get("container")));
        this.setConsoleSize(new ConsoleSize(stringStringMap.get("cols"),stringStringMap.get("rows")));
    }

    @Override
    public void run() {
        List<String> cmds = Arrays.asList( new String[] {"/bin/bash","/bin/sh"});
        cmds.forEach((s) -> startProcess(s));

    }

    private void startProcess(String shellPath){
        String namespace = this.getPod().getNamespace();
        String name = this.getPod().getName();
        String container = this.getPod().getContainer();
        Boolean tty = true;
        Boolean initValid = true;
        try {
            proc = exec.exec(namespace,name,new String[]{shellPath},container,true,tty);
            outputStream = proc.getOutputStream();
            inputStream = proc.getInputStream();
            try {
                while (true){
                    byte data[] = new byte[1024];
                    if (inputStream.read(data) != -1) {
                        TextMessage textMessage = new TextMessage(data);
                        if (initValid && isValidBash(textMessage,shellPath)){
                            break;
                        } else {
                            initValid = false;
                        }
                        session.sendMessage(textMessage);
                    }
                }
            } catch ( IOException e) {
                logger.warn("Pipe closed");
            } finally {
                proc.destroy();
                logger.info("session closed... exit thread");
            }


        } catch (ApiException | IOException e) {
            e.printStackTrace();
            try {
                logger.info("ApiException or IOException... close session");
                session.close();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
        }


    }

    private boolean isValidBash(TextMessage textMessage,String shellPath){
        String failMessage = "OCI runtime exec failed";
        if (textMessage.getPayload().trim().indexOf(failMessage) != -1){
            logger.warn("OCI runtime exec failed: " + shellPath);
            return true;
        }else {
            return  false;
        }
    }

    protected void finalize() {
        try {
            outputStream.close();
            inputStream.close();
            outputStream = null;
            inputStream = null;
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void exit() {
        proc.destroyForcibly();
        try {
            outputStream.close();
            inputStream.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }


    public InputStream getInputStream() {
        return inputStream;
    }

    public void setInputStream(InputStream inputStream) {
        this.inputStream = inputStream;
    }

    public OutputStream getOutputStream() {
        return outputStream;
    }

    public void setOutputStream(OutputStream outputStream) {
        this.outputStream = outputStream;
    }

    public Exec getExec() {
        return exec;
    }

    public void setExec(Exec exec) {
        this.exec = exec;
    }

    public WebSocketSession getSession() {
        return session;
    }

    public void setSession(WebSocketSession session) {
        this.session = session;
    }


    public Pod getPod() {
        return pod;
    }

    public void setPod(Pod pod) {
        this.pod = pod;
    }

    public ConsoleSize getConsoleSize() {
        return consoleSize;
    }

    public void setConsoleSize(ConsoleSize consoleSize) {
        this.consoleSize = consoleSize;
    }



}


```
