### ISSUE TITLE
comment in example code snippet is inconsistent

### ISSUE THREAD

**Issue by kennhhhhh** [kubernetes-client/java#3506]
https://github.com/kubernetes-client/java/blob/ff42d73ef230038d406afcb80acaa0821e84f9fe/examples/examples-release-18/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java#L45

this is outside-cluster rather than inside-cluster

**Comment by brendandburns** [comment]
We'd be happy to take a PR to fix this comment.
