### ISSUE TITLE
LogsApi, how does it works ?

### ISSUE THREAD

**Issue by tlnd-laurent** [kubernetes-client/java#351]
Hi,

I'm a little confused by the LogsApi, i was expecting it to take as parameter the namespace and the jobname but it's asking for a path to log.

I'm trying to get the logs from a job, the kuberntes REST API is:
https://localhost:6445/apis/batch/v1/namespaces/{namespace}/jobs/{jobName}

Is this possible with the current API ?

**Comment by brendandburns** [comment]
Jobs are objects that create `Pods`. The logs are associated with the `Pod` object not the `Job` object.

You need to find the `Pod` that is associated with the `Job` and then the example here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/LogsExample.java

Will show you want to do.

**Comment by brendandburns** [comment]
please re-open if you still have questions.

**Comment by tlnd-laurent** [comment]
Thanks for your answer, I will try this.

Still the kubernetes REST API allow you to get logs from a job. They already handle the link to the pod.
So why the java API is not proposing this ?

**Comment by tlnd-laurent** [comment]
One more thing, to get my pods do I have to list of pods and filter with the job name? there is no other way ?

And I don't seems to be able to re open the issue
