### ISSUE TITLE
Transferring files to pod

### ISSUE THREAD

**Issue by BenjaminITS** [kubernetes-client/java#353]
Hello,
I tried to send files to a pod with the lib using the Exec object. It works, but it can't ensure the integrity of the file.
Here is an example of how I do it : 

```
public class ExecExample {
    public static void main(String[] args) throws IOException, ApiException {
        String podName = "nginx-4217019353-k5sn9";
        String namespace = "default";

        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);

        Exec exec = new Exec();
        final Process proc =
                exec.exec(
                        namespace,
                        podName,
                        new String[]{"tee" ,"/tmp/test"},
                        true,
                        false);

        try {
            FileInputStream file = new FileInputStream("C:/test");
            OutputStream pod = proc.getOutputStream();
            IOUtils.copy(file, pod);
            pod.flush();
            IOUtils.closeQuietly(file);
            IOUtils.closeQuietly(pod);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        proc.destroy();

        System.exit(proc.exitValue());
    }
}
```

The problem is that there are missing bytes in my pod file. Not always the same amount and it's depending of the original file size. 
For example : 
- Sent 1024 bytes -> always received 1024 bytes = OK
- Sent 2048 bytes -> always received 2047 bytes = KO
- Sent 4096 bytes -> always received 4095 bytes = KO
- Sent 8192 bytes -> always received 8190 bytes = KO

I tested with the command `tar xf - -C /tmp` and sending a tar file, and I also tested the commands with kubectl. No problems in the both cases.
It's maybe a buffer problem, but I don't know when. IOUtils.copy() return the right amount of bytes.

Development environment : Windows
Kubernetes Java library version : 2.0.0
Kubernetes version : 1.8.2

**Comment by brendandburns** [comment]
I would read the entire file into memory first, and then try writing it to the stream and make sure that it is correctly understood.

Of course, I would also be careful about special characters in the binary file.  You probably want to use something like a base64 encoding to be certain that you are only sending alpha numeric characters.

**Comment by kondapally1989** [comment]
@brendandburns 
does having something like KubeCopy.java(similar to kubectl cp) which copies files to and from containers of pod in project be helpful?

**Comment by brendandburns** [comment]
@kondapally1989 sure, if you wanted to add something like that in `util` somewhere, that's probably useful...

Thanks!

**Comment by brendandburns** [comment]
@kondapally1989 I went ahead and wrote this up in pull #375 a review would be awesome!

**Comment by Slayug** [comment]
> Hello,
> I tried to send files to a pod with the lib using the Exec object. It works, but it can't ensure the integrity of the file.
> Here is an example of how I do it :
> 
> ```
> public class ExecExample {
>     public static void main(String[] args) throws IOException, ApiException {
>         String podName = "nginx-4217019353-k5sn9";
>         String namespace = "default";
> 
>         ApiClient client = Config.defaultClient();
>         Configuration.setDefaultApiClient(client);
> 
>         Exec exec = new Exec();
>         final Process proc =
>                 exec.exec(
>                         namespace,
>                         podName,
>                         new String[]{"tee" ,"/tmp/test"},
>                         true,
>                         false);
> 
>         try {
>             FileInputStream file = new FileInputStream("C:/test");
>             OutputStream pod = proc.getOutputStream();
>             IOUtils.copy(file, pod);
>             pod.flush();
>             IOUtils.closeQuietly(file);
>             IOUtils.closeQuietly(pod);
>         } catch (IOException ex) {
>             ex.printStackTrace();
>         }
> 
>         proc.destroy();
> 
>         System.exit(proc.exitValue());
>     }
> }
> ```
> 
> The problem is that there are missing bytes in my pod file. Not always the same amount and it's depending of the original file size.
> For example :
> 
>     * Sent 1024 bytes -> always received 1024 bytes = OK
> 
>     * Sent 2048 bytes -> always received 2047 bytes = KO
> 
>     * Sent 4096 bytes -> always received 4095 bytes = KO
> 
>     * Sent 8192 bytes -> always received 8190 bytes = KO
> 
> 
> I tested with the command `tar xf - -C /tmp` and sending a tar file, and I also tested the commands with kubectl. No problems in the both cases.
> It's maybe a buffer problem, but I don't know when. IOUtils.copy() return the right amount of bytes.
> 
> Development environment : Windows
> Kubernetes Java library version : 2.0.0
> Kubernetes version : 1.8.2

Hello,
First i'm sorry to reply in a closed issue but, the question was "transferring files to pods" and the Util class only provides method to copy from pod. 
I tried to copy directory through the tar cmd as you said, but i'm not enable to make it works.
I also tried to use the following example https://github.com/fabric8io/kubernetes-client/issues/868#issuecomment-365216344 from the fabric8io, and to adapt it, but without any success..


```
String namespace = response.object.getMetadata().getNamespace();
   String podName = response.object.getMetadata().getName();

   Exec exec = new Exec();
   FileInputStream inputStream = null;
   try {
       inputStream = new FileInputStream(new File("/tmp/src"));
   } catch (FileNotFoundException e) {
       e.printStackTrace();
   }
   TarArchiveEntry entry = new TarArchiveEntry("/src");
   List<String> commands = Arrays.asList("tar", "xf", "-", "-C", "/");
   final Process proc;
   try {
       proc = exec.exec(
               namespace,
               podName,
               commands.isEmpty()
                       ? new String[] {"sh"}
                       : commands.toArray(new String[commands.size()]),
               true,
               false);

       try (TarArchiveOutputStream tarOut = new TarArchiveOutputStream(proc.getOutputStream());
            ByteArrayOutputStream byteOut = new ByteArrayOutputStream();) {

           byte[] bytes = new byte[4096];
           int count;
           while ((count = inputStream.read(bytes)) > 0) {
               byteOut.write(bytes, 0, count);
           }

           entry.setSize(byteOut.size());
           tarOut.putArchiveEntry(entry);
           byteOut.writeTo(tarOut);
           tarOut.closeArchiveEntry();
           tarOut.finish();
       } catch (IOException e) {
           e.printStackTrace();
       }

   } catch (ApiException e) {
       e.printStackTrace();
   } catch (IOException e) {
       e.printStackTrace();
```



So I got this:

> java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by anuprout** [comment]
Hi @brendandburns , Is there any utility to copy files to PODs. The Copy.java has only copy from PODs methods. 

I am also having the same issue in copying files to the PODs. Any help would be highly appreciated. Thanks

**Comment by Slayug** [comment]
@anuprout I end up to create a configMap before my pod start and link to it.

It might be an alternative for you ?

**Comment by anuprout** [comment]
Hi @Slayug , sure.. any pointer would help. Could you please the sample config map you created ?

**Comment by Slayug** [comment]
You first need to create a ConfigMap instance :
```java
String configMapName = "something";

files = new HashMap<String, String>();
files.put("fileName", "content");

configMap = new ConfigMapBuilder()
    .withNewMetadata()
        .withName()
        .addToLabels(...your labels)
    .endMetadata()
    .addToData(files)
    .build();
```
You have to upload it to your cluster:
```java
kubernetesClient
    .configMaps()
    .inNamespace(yourNamespace)
    .create(configMap);
```

then you have to bind it to your pod with a ConfigMapVolumeSource:

```java
PodSpecBuilder podSpecBuilder = new PodSpecBuilder()
    .withRestartPolicy(restartPolicy)
    .withContainers(containers)
    .withVolumes(new VolumeBuilder()
        .withName(configMap.getMetadata().getName())
        .withConfigMap(new ConfigMapVolumeSourceBuilder()
            .withName(configMapName)  // it's important to keep the same name through the snippets.
       .build())
    .build();
```
And for each of your container into your pod:
```java
new ContainerBuilder()
    .withName(containerName)
    .withImage(image)
    .withVolumeMounts(Collections.singletonList(new VolumeMountBuilder()
         .withName(configMapName) // it's important to keep the same name through the snippets.
         .withMountPath(yourPath)
    .build())));
```

And you can put your pod within a job, deployment anything else then push it.
I think if you need more help for the previous snippets it would be better with a new issue.
