### ISSUE TITLE
ignoreDaemonSets is not working 

### ISSUE THREAD

**Issue by Duranna66** [kubernetes-client/java#3530]
**Describe the bug**

**Client Version**
e.g. `19.0.0`

**Kubernetes Version**
e.g. `1.19.3`

**Java Version**
e.g. Java 17

**To Reproduce**
Kubectl.drain()
                    .ignoreDaemonSets()
                    .force()
                    .name("nodeExample")
                    .execute();

**Expected behavior**
while drain daemonSets pods starts delete .

**KubeConfig**
exmaple:
      clusters:
        - cluster:
            certificate-authority-data: example
            server: "exmaple"
          name: exmaple
      contexts:
        - context:
            cluster: exmaple
            namespace: aclever-users
            user: users.tech-user-test
          name: exmaple-tech-user-test
      current-context: exmaple
      kind: Config
      preferences: { }
      users:
        - name: users.tech-user-test
          user:
            privateKey:
            token: "shifr".

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]

**Additional context**

**Comment by brendandburns** [comment]
Can you provide more details about what you expect and what you are seeing?

**Comment by Duranna66** [comment]
I expect that pods who controlled by DaemonSet will be not delete when I do drain, but it is not.  
Example:  "kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"calico-node-pbzsr\" is forbidden: User \"system:serviceaccount:aclever-users:users.tech-user-test\" cannot delete resource \"pods\" in API group \"\" in the namespace \"calico-system\"","reason":"Forbidden","details":{"name":"calico-node-pbzsr","kind":"pods"},"code":403}
<img width="1386" alt="image" src="https://github.com/kubernetes-client/java/assets/119310710/448f0eac-ee8e-4888-aa81-f039e9d7bf94">

**Comment by Duranna66** [comment]
why k8s client tries to delete this ?
thx for fb

**Comment by Duranna66** [comment]
> Can you provide more details about what you expect and what you are seeing?

I expect that pods who controlled by DaemonSet will be not delete when I do drain, but it is not.
Example: "kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods "calico-node-pbzsr" is forbidden: User "system:serviceaccount:aclever-users:users.tech-user-test" cannot delete resource "pods" in API group "" in the namespace "calico-system"","reason":"Forbidden","details":{"name":"calico-node-pbzsr","kind":"pods"},"code":403}
<img width="1365" alt="image" src="https://github.com/kubernetes-client/java/assets/119310710/ac1fa32f-6485-4289-8403-c526ad73df25">


why k8s client tries to delete this ?
thx for fb

**Comment by brendandburns** [comment]
This is how we check for membership in the DaemonSet:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java#L76

Specifically looking for an owner reference with kind `DaemonSet`.

Can you share the YAML for that calico pod (`kubectl get pod -o yaml ...`) so that we can see what the reference is set to?

**Comment by Duranna66** [comment]
> This is how we check for membership in the DaemonSet:
> 
> https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java#L76
> 
> Specifically looking for an owner reference with kind `DaemonSet`.
> 
> Can you share the YAML for that calico pod (`kubectl get pod -o yaml ...`) so that we can see what the reference is set to?

ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: calico-node

**Comment by Duranna66** [comment]
I noticed that the library code we use in the project is not the same as yours.
<img width="1327" alt="image" src="https://github.com/kubernetes-client/java/assets/119310710/5cd9f9e9-1625-47c4-8f31-30f63dcfe7b5">

**Comment by Duranna66** [comment]
we don't have continue...

**Comment by Duranna66** [comment]
I have this dependencies k8s    : [
                    'io.kubernetes:client-java-extended:21.0.0',
                    'io.kubernetes:client-java:21.0.0',

**Comment by Duranna66** [comment]
Okey, let's check this code

for (V1Pod pod : allPods.getItems()) {
      // at this point we know, that we have to ignore daemon set pods
      if (pod.getMetadata().getOwnerReferences() != null) {
        for (V1OwnerReference ref : pod.getMetadata().getOwnerReferences()) {
          if (ref.getKind().equals("DaemonSet")) { 
            continue;    
          }
        }
      }
      deletePod(api, pod.getMetadata().getName(), pod.getMetadata().getNamespace());
    }
    return node;
    
    
    
     If we had DaemonSet we anyway delete this pod because continue works on second for

**Comment by Duranna66** [comment]
maybe try this one 

boolean isDaemonSetPod;
    for (V1Pod pod : allPods.getItems()) {
      // at this point we know, that we have to ignore daemon set pods
       isDaemonSetPod = false;
      if (pod.getMetadata().getOwnerReferences() != null) {
        for (V1OwnerReference ref : pod.getMetadata().getOwnerReferences()) {
          if (ref.getKind().equals("DaemonSet")) {
            isDaemonSetPod = true;
            break;
          }
        }
      }
      if (!isDaemonSetPod) {
        deletePod(api, pod.getMetadata().getName(), pod.getMetadata().getNamespace());
      }

**Comment by brendandburns** [comment]
Oh, I see you sent #3537 thank you! I will review it.
