### ISSUE TITLE
Distributed Locking with Kubernetes Lease Resource

### ISSUE THREAD

**Issue by rahulroshan96** [kubernetes-client/java#3538]
Hello Team,

I am attempting to use the Lease resource for distributed locking to synchronize tasks among Java application instances running in multiple pod replicas. My goal is to implement the following workflow:

1. Acquire the lock (competing with other application instances running in multiple pods)
2. Perform a task within the critical section
3. Release the lock

To achieve this, I am using the **replaceNamespacedLease** method to **acquire the lease**, update the **renewTime**, and set the **holderIdentity**. My understanding is that if thread1 updates the **holderIdentity**, **renewTime**, and **acquires the lease** first, any subsequent attempt by thread2 to update the same lease with a different **holderIdentity** using **replaceNamespacedLease** before the **renewTime** should fail.

However, during my local tests, I am seeing that thread2 is able to replace the lease specifications even when thread1 has already acquired the lease. Is my understanding of how lease acquire should work incorrect? Am I missing something here? Is there a dedicated solution available for achieving this distributed locking workflow using Kubernetes Lease ?

Sample Run:
// Assume lease is already created with leaseDurationSeconds: 300
UpdateLease("thread1"); 
Thread.sleep(30);
UpdateLease("thread2"); // this call should fail ? since thread2 is trying to acquire lease before the renewTime ?

```
import io.kubernetes.client.openapi.models.V1Lease;

public V1Lease UpdateLease(String holderIdentity) throws ApiException {
    V1Lease lease = coordinationApi.readNamespacedLease(leaseName, namespace).execute();
    OffsetDateTime currentRenewTime = lease.getSpec().getRenewTime();
    OffsetDateTime newRenewTime = currentRenewTime.plusSeconds(120);
    Objects.requireNonNull(lease.getSpec()).setHolderIdentity(holderIdentity);
    lease.getSpec().setRenewTime(newRenewTime);
    lease.getSpec().setAcquireTime(OffsetDateTime.now());
    V1Lease result = coordinationApi.replaceNamespacedLease(leaseName, namespace, lease).fieldManager(holderIdentity).execute();
    return lease;
  }
```

  
  **OS:**
  Windows
  
  **Version:** 
  io.kubernetes client-java 21.0.0

**Comment by brendandburns** [comment]
Leases by themselves don't actually block anything. You need to use a local lock implemented on top of leases, for example:

https://github.com/kubernetes-client/java/blob/b14c36d7c3ff5b30a3c6a6456c3156e92c5fbbe6/extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java#L34
