### ISSUE TITLE
Versioning and compatibility Wiki page missing 21.0.x and K8s versions newer than 1.28

### ISSUE THREAD

**Issue by SanjayVas** [kubernetes-client/java#3564]
**Describe the bug**
This page is out of date: https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility

Additionally, the CHANGELOG link on that page is a dead link.

**Comment by brendandburns** [comment]
Fixed the table. Changelog is woefully out of date. We need an automated way to generate release notes.
