### ISSUE TITLE
Latest (v21.0.0) release client-java-extended Maven artifact has non-existant dependencies

### ISSUE THREAD

**Issue by SanjayVas** [kubernetes-client/java#3599]
**Describe the bug**
The released `client-java-extended` Maven artifact references `bucket4j` from the old group (`com.github.vladimir-bukhtoyarov`), which no longer exists. Attempts to depend on the latest release fail. See #3534

**Client Version**
N/A

**Kubernetes Version**
N/A

**Java Version**
N/A

**To Reproduce**
Attempt to depend on `client-java-extended` Maven artifact.

**Expected behavior**
Maven build succeeds.

**Comment by daniel-b2c2** [comment]
I have already pushed a commit to master for this, I have asked for a release to be cut

**Comment by danielburrell** [comment]
@SanjayVas try `21.0.1`

**Comment by brendandburns** [comment]
Closing this issue via #3594 please use the `/reopen` command if you are still having problems.
