### ISSUE TITLE
Dependence issue on client-java package @version "3.0.0-beta1"

### ISSUE THREAD

**Issue by BSWANG** [kubernetes-client/java#360]
The `client-java` package of version `3.0.0-beta1` depends `client-java-api` and `client-java-proto` which version is `3.0.0-SNAPSHOT`. The dependencies version should be `3.0.0-beta1`.

Ref the mvn repo: https://mvnrepository.com/artifact/io.kubernetes/client-java/3.0.0-beta1

![image](https://user-images.githubusercontent.com/3598874/45205064-aa3fd400-b2b3-11e8-9cb6-213a5f72634a.png)

**Comment by brendandburns** [comment]
I'll try to cut a fixed 3.0.0-beta2 later today...

**Comment by BSWANG** [comment]
@brendandburns Hi, any update for this issue?   the [3.0.0-beta1](https://mvnrepository.com/artifact/io.kubernetes/client-java/3.0.0-beta1`) 's dependencies are still at `3.0.0-SNAPSHOT`.
