### ISSUE TITLE
java.io.IOException: Timed out waiting for web-socket to flush?

### ISSUE THREAD

**Issue by swzaaaaaaa** [kubernetes-client/java#3626]
**Describe the bug**
When uploading files to pod, when the file size is 100M, an error will appear.This problem does not occur when the file is relatively small
error：
java.io.IOException: Timed out waiting for web-socket to flush
  at io.kubernets.client.util.WebSocketStreamHandler@WebSocketOutputStream.flush
  at java.util.zip.DeflaterOuputStream.flush
  at. io.kubernetes.client.util.Streams.copy

**Client Version**
e.g. `20.0.0`

**Kubernetes Version**
e.g. `1.21`

**Java Version**
e.g. Java 8

**To Reproduce**
  public Future<Integer> copyFileToPodAsync(
      String namespace, String pod, String container, Path srcPath, Path destPath)
      throws ApiException, IOException {
    // Run decoding and extracting processes
    final Process proc = execCopyToPod(namespace, pod, container, destPath);

    // Send encoded archive output stream
    File srcFile = new File(srcPath.toUri());
     ZipInputStream zis = new ZipInputStream(fis)) 

            ZipEntry zipEntry;
            while ((zipEntry = zis.getNextEntry()) != null) {
                System.out.println("解压文件: " + zipEntry.getName());
               int len = 0;
               ByteArrayOutputStream byteStream = new ByteArrayOutPutStream();
               byte[] bytes = new byte[1024];
                while ((len = zis.read(bytes)) ! = -1}{
                 byteStream.write(bytes,0,len);  
              }

                zis.closeEntry();  // 关闭当前 ZIP 条目
                 Streams.copy(new ByteArrayInputStream(byteStream.tobyteArray()), zipOutPutStream);   ///_////this #_##################################
                
           }

      return new ProcessFuture(proc);
    }

**Comment by brendandburns** [comment]
I would guess that this is related to your network conditions rather than anything in the client. Does it work if you use `kubectl`?

**Comment by swzaaaaaaa** [comment]
![image](https://github.com/user-attachments/assets/205074ba-5e4f-469c-8a9d-3a0cb47a0800)

Is there a timeout set? I haven't tried it on kubectl, and there are some problems with the environment configuration.

**Comment by swzaaaaaaa** [comment]
Hello, you can see that the file size keeps getting larger during the upload time. It doesn't seem to be a network problem.

> I would guess that this is related to your network conditions rather than anything in the client. Does it work if you use `kubectl`?

Hello, i can see that the file size keeps getting larger during the upload time. It doesn't seem to be a network problem.

**Comment by swzaaaaaaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/43643616/357653723-205074ba-5e4f-469c-8a9d-3a0cb47a0800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDQ3MzQsIm5iZiI6MTcyMzYwNDQzNCwicGF0aCI6Ii80MzY0MzYxNi8zNTc2NTM3MjMtMjA1MDc0YmEtNWU0Zi00NjljLThhOWQtM2EwY2I0N2EwODAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAzMDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzA2NTZiZDRkOWQyNDdkYzM5Mjg5YmUzZGZjYmNiM2Q5MjRhZDE5YjhjMzczNTU5NDljY2IxOGU5OWQ4NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tz5ZNQiT4VtzjX8YIF8--sB_NjSFnqv4JWCEGKNwXxM)
> 
> Is there a timeout set? I haven't tried it on kubectl, and there are some problems with the environment configuration.

I think changing this i++ to a larger size should solve the problem. Please tell me how to rewrite this flush method.
