### ISSUE TITLE
How to set the terminal stty cols and rows through exec API ?

### ISSUE THREAD

**Issue by gohonsen** [kubernetes-client/java#3641]
**Describe the bug**
Hey, I want to enter the k8s pod container to run shell commands through web terminal, but I found that after the web terminal page size changed, I cann't synchronize set terminal size through exec API, and the page display is disordered.
 Is there any way to set the terminal stty cols and rows ? Thanks a lot

**Client Version**
`18.0.1`

**Kubernetes Version**
`v1.28.0`

**Java Version**
Java 8

**Comment by brendandburns** [comment]
This isn't currently supported. You can read resize messages from the stream via `Exec.getResizeStream()` but you can't write to that stream currently.

We need something like the following in the Javascript client:

https://github.com/kubernetes-client/javascript/blob/70f651ca7e5c8d3647c071ab4f6aeb89f4ccae14/src/exec.ts#L66

We'd be happy to take a PR for this support.

**Comment by brendandburns** [comment]
Alternately, you could use `ExecProcess.getInputStream(4).write("{ width: foo, height: bar}")` that should work.

https://github.com/kubernetes-client/java/blob/0e94811dbf8e3a0bfebb0c8a8cc9bf61a28e5e83/util/src/main/java/io/kubernetes/client/Exec.java#L610

**Comment by gohonsen** [comment]
@brendandburns I got it, My code like this:

> execProcess = (Exec.ExecProcess) executionBuilder.execute();
            resizeOutStream = execProcess.getResizeStream();
            outputStream = execProcess.getOutputStream();
            inputStream = execProcess.getInputStream();
            String resize = "{\"Width\":" + cols + ",\"Height\":" + rows + "}";
            resizeOutStream.write(resize.getBytes());
>
and it works,  thanks.

**Comment by brendandburns** [comment]
Glad it's working. Making this a little easier could be a good first issue, so I'll leave this open in case someone wants to take it on.

**Comment by sriganeshres** [comment]
@brendandburns i want to work on this issue. But the problem i cant setup the code properly can you send me the steps to setup the code.

**Comment by sriganeshres** [comment]
![image](https://github.com/user-attachments/assets/f8eedab7-5bd5-4066-8988-5ffcfdec595a)
i have done this till now.

thanks

**Comment by sriganeshres** [comment]
then i did this
![image](https://github.com/user-attachments/assets/a1029ef6-d1f2-4932-b54d-e1bb6c5a7988)
next how should i proceed to do the required changes and test and contribute. It is some what tricky to a begginer to this code base. can you kindly please help me.

**Comment by brendandburns** [comment]
@sriganeshres the second command is to regenerate the code, you don't need to do that.

What you need to do is edit this file:

https://github.com/kubernetes-client/java/blob/65ade9471b18126e768475e510c288338f3d3d18/util/src/main/java/io/kubernetes/client/Exec.java#L4

To add a function like `setTerminalSize(int widthColumns, int heightColumns)` and which does code similar to https://github.com/kubernetes-client/java/issues/3641#issuecomment-2301637328.

If you need help with git or making a PR, please see instructions here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?tool=cli

**Comment by sriganeshres** [comment]
thank you @brendandburns

**Comment by sriganeshres** [comment]
@brendandburns  I have added a PR #3657 for this. Thanks for the help and understanding.

**Comment by brendandburns** [comment]
@sriganeshres thank you. In the future, you can just push new commits to the same branch and this PR will update, you don't need to create a new PR. I will close this PR given the new one.
