### ISSUE TITLE
Any plan to release 21.0.1-legacy

### ISSUE THREAD

**Issue by sonnyhcl** [kubernetes-client/java#3654]
21.0.1 has been released for 3weeks. Is there still any plan to release legacy version with regular version together?

![image](https://github.com/user-attachments/assets/5b2d018d-63f7-456c-bf80-80637d8869f3)

**Comment by brendandburns** [comment]
Patch versions for these two versions don't necessarily move in synchronization. In particular, the change which prompted the release was only recently back-ported to 21.0.1-legacy (https://github.com/kubernetes-client/java/pull/3627) I'll kick off the release now. Thanks for the reminder.
