### ISSUE TITLE
vulnerability issue : com.google.protobuf » protobuf-java1 vulnerability

### ISSUE THREAD

**Issue by liuyan0822-ly** [kubernetes-client/java#3720]
**Describe the bug**
vulnerability issue : com.google.protobuf » protobuf-java1 vulnerability

**Kubernetes Version**
20.0.1

I am using latest version. which has a  vulnerability issue : com.google.protobuf » protobuf-java1 vulnerability. I saw it is fixed in master. Any plan to release it? Thanks

**Comment by brendandburns** [comment]
If you cherry-pick it into the `release-20` branch, we can cut a release, otherwise it will wait until the next full version release (1-2 months).

Note that unless you use the proto buf client (which most people don't) that library isn't used.

**Comment by brendandburns** [comment]
@fepeti yes, protocol buffers are only used if you use that client or any of the classes in the `io.kubernetes.client.proto.*` package.

We should probably separate out the protocol buffer client into its own dependency/library, since most people don't use it.

**Comment by liuyan0822-ly** [comment]
@brendandburns , Thanks for your reply. I prefer to wait for your release.

**Comment by brendandburns** [comment]
https://mvnrepository.com/artifact/io.kubernetes/client-java/21.0.2 has been released with this vulnerability addressed.

Closing this issue.
