### ISSUE TITLE
How to connect remote kubernetes apiserver with java api

### ISSUE THREAD

**Issue by kaizhaokover** [kubernetes-client/java#374]
I wanna use java api to manage remote kubernetes cluster resource.But i can't find any instrunction for how to do this .

**Comment by kondapally1989** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

you can load config yaml of kubernets and hit it  or you can get  service token  

with help of ClientBuilder.java you can build APIClient . 
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
`

**Comment by brendandburns** [comment]
There are lots of complete examples here:

https://github.com/kubernetes-client/java/tree/master/examples/src/main/java/io/kubernetes/client/examples
