### ISSUE TITLE
How to resize a PVC ?

### ISSUE THREAD

**Issue by Chuckame** [kubernetes-client/java#3762]
Using kubectl, I'm able to patch the `.spec.resources.requests.storage` of a `PersistentVolumeClaim` (previously created by a `StatefulSet`).

How to do it using the java client ? I've seen `V1PersistentVolumeClaim` and `V1PersistentVolumeClaimSpec` classes, but it's only present for ephemeral volume templates, and in statefulsets.

**Comment by brendandburns** [comment]
If you want to see what `kubectl` is doing, add `--v=10` and it will print all of the request/response data from the server, that should help you implement this.
