### ISSUE TITLE
Can't connect to kubernetes using IBM Java

### ISSUE THREAD

**Issue by jfortunka** [kubernetes-client/java#377]
Running project which uses this client on IBM Java is not possible due to this problem:
https://github.com/square/okhttp/issues/3173

As you can see, this has been fixed in version `3.7.1` of OkHttp.

Kubernetes client currently uses OkHttp in version `2.7.5` - as far as i know (after reading this: https://github.com/kubernetes-client/java/pull/270) to achieve this effect, `swagger-codegen` should be updated to produce code that depends on newer version of OkHttp.

Since there already is such issue in swagger repository (https://github.com/swagger-api/swagger-codegen/issues/6413), I guess I just want to make sure about what steps I should take to resolve this problem:
1. Fix issue: https://github.com/swagger-api/swagger-codegen/issues/6413
2. Update https://github.com/kubernetes-client/gen to use new swagger

Is this correct? Or maybe there is easier way to achieve solution for this problem?

(For now I simply recompiled `2.7.5` version of OkHttp with fix for this particular issue, and I'm "overriding" dependency on OkHttp with my own jar file)

**Comment by brendandburns** [comment]
Yeah, you need to update:

**Comment by brendandburns** [comment]
Closing this since no response and not much more we can do in this repo...

**Comment by jfortunka** [comment]
Sure, we are currently internally debating/thinking about how is the best way for us to handle this problem - when/if we will decide to fix this issue, it wouldn't be a problem if we will open new issue with pull request containing updated dependency, right? :)

**Comment by ejacobson2000** [comment]
Is there any plan to fix this? I ran into this same issue today with the IBM JDK and had to manually change the kubernetes-client code to work around it.
