### ISSUE TITLE
Custom Object Status/Scale Methods Missing for 1.11 API

### ISSUE THREAD

**Issue by cliveseldon** [kubernetes-client/java#378]
I don't see CRUD methods for Status/Scale handling for Custom Objects in:
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/CustomObjectsApi.java
I thought this was part of the v1.11 API, for example here is an auto-update commit for the python client:
https://github.com/kubernetes-client/python/commit/17db994abc5bc2a40b0d0ea108c4cc3c0db8c3a9#diff-343e382f5d0f69190bf247217a71f38a

**Comment by brendandburns** [comment]
This was fixed in the generator here:

https://github.com/kubernetes-client/gen/pull/72

Sadly when we generated for 1.11, was before that fix:

https://github.com/kubernetes-client/java/pull/311

I'll take a backlog item to regenerate...

Thanks for the report.

**Comment by cliveseldon** [comment]
Great. Thanks.

**Comment by brendandburns** [comment]
@cliveseldon if you get a chance to review the PR that fixes this, that would be awesome.

Thanks!
