### ISSUE TITLE
Advice for testing code that's using the client library APIs

### ISSUE THREAD

**Issue by sha1n** [kubernetes-client/java#380]
I started using this library and I find it a hard to test the code that's around the client APIs. I tried looking in the API test code for examples and noticed that they are all ignored at the moment. 

Any advice would be much appreciated!

**Comment by brendandburns** [comment]
Have you looked at Mockito? It's probably a good tool for mocking the client libraries.

**Comment by brendandburns** [comment]
@sha1n I added a quick short example here:

**Comment by sha1n** [comment]
@brendandburns that's great! I wasn't familiar with WireMock - looks pretty cool! I will consider trying it sometime! I ended up using Mockito for unit-testing and a mock http server for some end-to-end tests. 

Thanks a lot for the attention! I guess you may close this one.
