### ISSUE TITLE
Propose release 3.0.0

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#382]
Things seem mostly stable and I want to move on to 4.0.0-beta1 to regenerate for kubernetes 1.12

@lwander

**Comment by brendandburns** [comment]
cc @itowlson (an light/easy intro to Java :)

**Comment by brendandburns** [comment]
cc @kondapally1989 in case you want to lgtm a 3.0.0 release so we can move on to 4.0.0-beta1 and k8s API 1.12 

Thanks!

**Comment by itowlson** [comment]
@brendandburns I'm not in a position to do this right now I'm afraid.  I had a look at what was involved in the previous releases and it didn't look too hard, but I'm not set up to build and test the Java client yet.  Sorry.

**Comment by brendandburns** [comment]
@kondapally1989 yeah, we definitely need better testing, I'll see what I can do.

**Comment by cliveseldon** [comment]
I would be happy to help where I can as we at Seldon use the Java client and are looking for the new release to use the added API features for CRDs (status,scale) that were missing.

**Comment by brendandburns** [comment]
@cliveseldon thanks for the offer of help. For starters, I'd love reviews on the three open PRs :)

And then following the example in the `ExampleTest.java` (https://github.com/kubernetes-client/java/pull/393) it would be great to start adding some test coverage via `wiremock`

In the meantime, I will cut the official 3.0.0 release today after I run some ad-hoc tests, we can improve testing going forward.

Thanks for the help!

**Comment by cliveseldon** [comment]
I've done the reviews.

Regards testing how do these tests fit with the automated Test stubs which are created in the api package? Is there some way to flesh these out automatically? I'm not sure I understand how they are created.

**Comment by brendandburns** [comment]
Thanks for the reviews. I responded and I added a PR with some unit tests.

I didn't actually cut the release, real life (well Hashiconf keynote) got in the way...

But I've now cut the 3.0.0 and pushed it to Sonatype.

It will take a while for it to mirror out to maven central, but you should be able to start using it tomorrow is.

**Comment by brendandburns** [comment]
This is released.
