### ISSUE TITLE
Custom watch resource mechanism

### ISSUE THREAD

**Issue by cviktorov** [kubernetes-client/java#3828]
Hi Colleagues,

Is it possible to implement Java Operator, which watches resources from other platform using custom REST APIs or WEB Sockets?

The idea is to deploy the Java Operator on K8s Cluster, and to have some custom logic for watch resources.

Best regards,
Tsvetislav

**Comment by brendandburns** [comment]
Yes, that is definitely possible. Have a look at the InformerExample:

https://github.com/kubernetes-client/java/blob/master/examples/examples-release-latest/src/main/java/io/kubernetes/client/examples/InformerExample.java

For a place to start.
