### ISSUE TITLE
How to watch for  Service related details deployed ?

### ISSUE THREAD

**Issue by sharmmoh1983** [kubernetes-client/java#383]
I am trying to get the service details deployed on Kubernetes using listEventForAllNamespacesCall
But I am not getting details like service name, ip port

Please let me know how to watch for service related details using watch functionality

**Comment by brendandburns** [comment]
You need to watch the service object itself, not the event stream.

There's an example here for Namespaces:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

Which would be easy to adapt to Services

**Comment by sharmmoh1983** [comment]
Hi @brendandburns 
I did use listServiceForAllNamespacesCall to get the details related to Services. I was wondering if there is any way doing multiple watch calls in async manner in java ,the way asyncio is doing in python client
