### ISSUE TITLE
how can I convert used value to number when use readNamespacedResourceQuota ?

### ISSUE THREAD

**Issue by tingweiwu** [kubernetes-client/java#384]
I noticed that the `used` in  `V1ResourceQuotaStatus` class is  ` Map<String, String>`

so how can I convert string to number value?
as `memory` may be `40Gi` or other value .....
and `cpu` may be `500m` or `1k` ....

```
class V1ResourceQuotaSpec {
    hard: {limits.cpu=Quantity{number=30, format=DECIMAL_SI}, limits.memory=Quantity{number=42949672960, format=BINARY_SI}, requests.cpu=Quantity{number=30, format=DECIMAL_SI}, requests.memory=Quantity{number=42949672960, format=BINARY_SI}, requests.nvidia.com/gpu=Quantity{number=10, format=DECIMAL_SI}}
    scopes: null
}

class V1ResourceQuotaStatus {
    hard: {limits.cpu=30, limits.memory=40Gi, requests.cpu=30, requests.memory=40Gi, requests.nvidia.com/gpu=10}
    used: {limits.cpu=3, limits.memory=30Gi, requests.cpu=3, requests.memory=30Gi, requests.nvidia.com/gpu=3}
}


```

**Comment by brendandburns** [comment]
That's very odd, for some reason the swagger isn't generating a `Quantity` there properly.

If you want to compile from code, you can manually change it to `Map<String, Quantity>` and recompile and it should work.

Obviously that's not a good long-term fix, we need to figure out why the swagger isn't generating the right object there....

Thanks!

**Comment by tingweiwu** [comment]
@brendandburns 
I took a look at https://raw.githubusercontent.com/kubernetes-client/java/master/kubernetes/swagger.json and found that
both the hard in  `V1ResourceQuotaStatus `  and `V1ResourceQuotaSpec`  class refs to  `resource.Quantity`
and I feel confused that the type of resource.Quantity in swagger is `string`?

![image](https://user-images.githubusercontent.com/29671725/46808695-7a4a8b80-cd9f-11e8-9837-06e0436d2721.png)

![image](https://user-images.githubusercontent.com/29671725/46808741-95b59680-cd9f-11e8-80a8-61cb4d56add1.png)


![image](https://user-images.githubusercontent.com/29671725/46808936-0ceb2a80-cda0-11e8-90f1-1305d629eac6.png)

**Comment by brendandburns** [comment]
`resource.Quantity` is intercepted and replaced with a custom type via the logic here:

https://github.com/kubernetes-client/gen/blob/master/openapi/java.xml#L48

What I don't understand is why that logic is kicking in for one object and not for the other...

They seem totally identical and thus I'm very confused...
