### ISSUE TITLE
helm output?

### ISSUE THREAD

**Issue by magick93** [kubernetes-client/java#389]
Hello

Just wondering if its possible to produce a helm chart using this project?

Currently, as helm charts are written in yaml, developing a chart lacks the compile time checking / type safety that comes with the likes of Java.

**Comment by brendandburns** [comment]
No, there's currently no way to produce a Helm chart from this project, I think that might be out of scope for this project as it is focused on Kubernetes APIs...

But I believe that Helm will be migrating to CRD (custom resource definitions) with Helm v3, so at that point you will be able to use this library to create Helm charts.
