### ISSUE TITLE
Test Cases : Mock Watch.createWatch

### ISSUE THREAD

**Issue by sharmmoh1983** [kubernetes-client/java#391]
I am trying to write test cases for Watcher Example  but not able to mock watch object with required data and hence it is getting null pointer exception at  for each loop

```
try {
      for (Watch.Response<V1Namespace> item : watch) {
        System.out.printf("%s : %s%n", item.type, item.object.getMetadata().getName());
}
```

Also I am not able to understand how this for loop is executing and waiting  for  responses  and  program is not running to completion  when there is nothing to iterate

Can some one throw some light on the same?

**Comment by brendandburns** [comment]
`Watch` implements `Iterable`

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Watch.java#L36

If you want to mock it, you're going to need to mock the `next()` method so that it actually returns something.

**Comment by sharmmoh1983** [comment]
Thanks for the reply, Can you please throw some light on how for loop is executed and waiting  for the response when there is nothing to iterate in case of all the responses are consumed or there is nothing to read  on socket?
