### ISSUE TITLE
Duplicate classes in client-java and client-java-api

### ISSUE THREAD

**Issue by bdshadow** [kubernetes-client/java#398]
in my android application i do the following dependency:
```
dependencies {
    implementation('io.kubernetes:client-java:2.0.0')
...
}
```
As a result i have 2 jars in the classpath: io.kubernetes:client-java:2.0.0 and io.kubernetes:client-java-api:2.0.0. The first one contains `util` package and classes, like `JSON`, `ApiClient`, `Attach` and so on. The second one doesn't have the `util` package (it has `apis`, `auth`, `custom`, and `models` packages) + the same classes `JSON`, `ApiClient` and so on (however doesn't contain `Attach` for example). In result i can't build my project because some of the classes are in both jars. 
I tried to exclude client-java-api dependency from client-java, but it doesn't work for me, as it contains util package which i need. Why are these jars so strangely packaged or what am i doing wrong?
![screenshot from 2018-10-22 12-18-13](https://user-images.githubusercontent.com/5796973/47288102-e9707d00-d5f4-11e8-827b-62b77c2d49b6.png)

**Comment by bdshadow** [comment]
tried to do make the same dependency in a simple java project - and it works. Smth is with how android project resolves the dependencies

**Comment by bdshadow** [comment]
the exact error is:
```
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
Program type already present: io.kubernetes.client.JSON$ByteArrayAdapter
```

**Comment by bdshadow** [comment]
The reason of this is maven-bundle-plugin in util module. It exports all its own packages, for example io.kubernetes.client`, but such a package is in both modules: util and kubernetes. And kubernetes is a dependency in util, so it also exports classes which are in kubernetes module in the package with the same name

**Comment by bdshadow** [comment]
So from the very beginning packages in `util` module should have been named somehow like  `io.kubernetes.client.util`. Also logically `kubernetes` module should depend on `util`. They're even built in this order. However, in contrary  `util`has dependency on `kubernetes`, but `kubernetes` on `util` doesn't.

**Comment by VoltBit** [comment]
The issue persists, it is also discussed here:
https://github.com/sundrio/sundrio/issues/153

Right now I can't use the libraries inside an Android project.

**Comment by navidei** [comment]
@bdshadow Could you find any workaround for this problem?
