### ISSUE TITLE
Docs out-of-date

### ISSUE THREAD

**Issue by PI-Victor** [kubernetes-client/java#400]
the [README.md](https://github.com/kubernetes-client/java/blob/master/kubernetes/README.md#getting-started) in the kubernetes directory is not up to date. Specifically the example uses imports from the old 1.0 release, i believe.

I think it should be something along the lines of 

```
import io.kubernetes.client.ApiClient;
import io.kubernetes.client.ApiException;
import io.kubernetes.client.Configuration;
import io.kubernetes.client.auth.*;
import io.kubernetes.client.apis.ApisApi;
import io.kubernetes.client.models.*;
```

**Comment by brendandburns** [comment]
Thanks for the report, we'll improve this (and maybe try to add some CI/CD for this)

**Comment by brendandburns** [comment]
Turns out those docs are auto-generated by the swagger code generator. They're not going to be correct, so I'm just deleting them to remove confusion.

**Comment by PI-Victor** [comment]
awesome, thanks!

i actually just wanted to fix that myself, however i didn't figure out how to generate them from this repo.

There are a few more issues with imports in some examples too.
e.g.: https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AppsV1beta1Api.md#example-14 
the `AppsV1beta1DeploymentList` model is never imported and the imports are commented out (maybe that's intended ?).

I'll rummage around the swagger-gen maybe figure out what's wrong and submit a PR myself.
