### ISSUE TITLE
Support using builders for method parameters?

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes-client/java#409]
Fully specifying all of the nulls for optional parameters can be difficult (especially without an IDE) to read and error-prone when adjacent arguments are of the same type.

Would you be opposed to using the builder pattern for constructing method arguments?

**Comment by PaulFurtado** [comment]
/remove-lifecycle rotten

Still think this client is fairly unusable by humans without this feature

**Comment by yue9944882** [comment]
we need to annotate the parameters for the generated client methods so that a builder can call them via reflection. but that need a change in the upstream template...
