### ISSUE TITLE
It's too hard to manually build a Kubeconfig without a file.

### ISSUE THREAD

**Issue by syonchao** [kubernetes-client/java#410]
kubernetes-client/java
how to use the three file， apiserver-key.pem，apiserver.pem，ca.pem to request https port 6443?

**Comment by dennis-benzinger-hybris** [comment]
If you don't really need a `Kubeconfig` object but just an `ApiClient` you can use to communicate with your cluster then use standard Java to load the content of your files and then use something like this:
```
new ClientBuilder()
    .setBasePath("https://<APISERVER>:6443")
    .setCertificateAuthority(<CA.PEM>)
      .setAuthentication(new ClientCertificateAuthentication(
              <APISERVER.PEM>,
              <APISERVER-KEY.PEM>)).build()
```

**Comment by asarkar** [comment]
I think https://github.com/kubernetes-client/java/issues/429 is relevant too.
