### ISSUE TITLE
Add a merge() method in ProtoClient to directly support PATCH request

### ISSUE THREAD

**Issue by TwinProduction** [kubernetes-client/java#413]
`ProtoClient.update(...)` uses PUT, but really, it replaces the existing resource with the given name by the resource passed as parameter `obj`. It shouldn't have been named `update`, but instead, it should have been named `replace` for clarity. 

[reference](https://kubernetes.io/docs/reference/federation/v1/operations/#_replace_the_specified_service)

Regardless, I don't think that changing it right now wouldn't be a good idea, because it would be a breaking change. Instead, a new method should be added, e.g. `merge(...)`, which would use `PATCH`.

While it is possible to use the `request(...)` method, I think it would be better to avoid using the `request(...)` method as much as possible for clarity. 

An example of this is the fact that `ProtoClient.update(...)`, `ProtoClient.get(...)`, `ProtoClient.delete(...)` and `ProtoClient.create(...)` all call `ProtoClient.request(...)`.

**Comment by brendandburns** [comment]
Closed by #412
