### ISSUE TITLE
Informer equivalent?

### ISSUE THREAD

**Issue by KevinWang15** [kubernetes-client/java#423]
Are there plans for something equivalent to an Informer in the go client? 
How can we reliably do list, watch and resync in Java?

**Comment by brendandburns** [comment]
There are plans, yes :)

In fact I have a rough draft of something like that for Java, but it's not quite ready for user consumption.

So yes, definitely plans, but nothing concrete right now.  If you are interested in collaborating on building it, I can share what I have...

**Comment by kennethredler** [comment]
@brendanburns ... I'd be interested to see what you have so far. Hoping to get to a point where I could collab on it.

**Comment by qzyse2017** [comment]
@brendandburns  I'm also interested in collaborating on building it. Hoping to learn your draft.
@kennethredler You used the wrong github user ID to inform the owner, it is `brendandburns`, not `brendanburns` 😂

**Comment by yue9944882** [comment]
/assign

coming soon, am working on that

**Comment by brendandburns** [comment]
Closing since #461 has merged.
