### ISSUE TITLE
replaceNamespacedReplicationControllerScale should create metadata if null

### ISSUE THREAD

**Issue by asarkar** [kubernetes-client/java#424]
```
api.replaceNamespacedReplicationControllerScale(
        name,
       namespace,
        new V1Scale()
                .metadata(
                        new V1ObjectMeta()
                                .name(name)
                                .namespace(namespace)
                )
                .spec(
                        new V1ScaleSpec()
                                .replicas(replicas)
                ),
        null
)
```
**Actual Behavior:**
The method validates that the `name` and `namespace` arguments are not null. However, the same are repeated for creating `V1ObjectMeta`, without which K8S returns a 400 Bad Request.

**Expected Behavior:**
`replaceNamespacedReplicationControllerScale` should create `V1ObjectMeta` as shown if it's `null` without requiring the user to write redundant code.

**Comment by brendandburns** [comment]
This code is generated, so that kind of intelligent defaulting isn't really possible.

(and it's also not really how HTTP `PUT` works)

If you really want that kind of behavior, you probably want to use `PATCH` instead:

`patchNamespacedReplicationControllerScale(...)`

**Comment by asarkar** [comment]
@brendandburns What's the `body` passed to `patchNamespacedReplicationControllerScale`? I'm not sure how do you expect people to use the API: I can understand if there is not enough documentation, but there are not even enough tests to look at. The [only test](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/test/java/io/kubernetes/client/apis/CoreV1ApiTest.java#L2931) that exists is completely useless.

**Comment by bgst** [comment]
For other readers: Your (partial) friend for this poor doc state is to enable debugging on the ApiClient, i.e.  `apiClient.setDebugging(true);`
