### ISSUE TITLE
CoreV1Api - Support Request Body in Proxy Methods

### ISSUE THREAD

**Issue by james-r-smith** [kubernetes-client/java#427]
Currently, [connectPostNamespacedPodProxy](https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CoreV1Api.md#connectPostNamespacedPodProxy) and the associated POST proxy methods do not support passing in a request body, while Kubernetes in fact supports this. I can see in the source code that `localVarPostBody` is defined as null before sending, so it seems that there just needs to be an option to allow passing in the request body.

I have an application that requires this, and currently our only option is to do the request outside of the library. I'm hoping for a fix if possible. Thanks!

**Comment by brendandburns** [comment]
@james-r-smith 

you have no idea the rabbit hole you just walked into :)

But I will attempt to be your guide...

The code in question is generated by this file here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache

Which in turn uses the Kubernetes swagger spec:

https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

If you find the relevant part of that schema (search for "proxy") the POST method needs a `parameters` field that looks something like this:
```json
...
     "parameters": [
      {
       "name": "body",
       "in": "body",
       "required": true,
       "schema": {
         "type": "object"
       }
      },
]
```

Once that is merged, we can regenerate the code and that _should_ add a body parameter to that call...

Sorry it's so complicated but the only reasonable way to keep up with the APIs is via code generation...

**Comment by james-r-smith** [comment]
@brendanburns, yikes! 😵 Is there a PR for this schema addition? I would like to be able to follow something for updates. I don't even think [FabricIO's client](https://github.com/fabric8io/kubernetes-client) supports this. 😞

**Comment by brendandburns** [comment]
@james-r-smith even better you can just use:

```java
connectPostNamespacedPodProxyCall(...)
```

to get the okhttp `Call` object and then add a body and then execute that `Call` yourself.

**Comment by james-r-smith** [comment]
@brendandburns, while that sounds fantastic, it doesn't seem OkHttp's `Call` object has a modifiable request object. If you know otherwise, I'd appreciate any tips. 😅

**Comment by brendandburns** [comment]
haha, well played.  You are correct. Sorry for the bad advice...

I'll try to get an update to the swagger done.
