### ISSUE TITLE
KubeConfig should look for certs in the same directory where config file is

### ISSUE THREAD

**Issue by asarkar** [kubernetes-client/java#429]
**Actual behavior:**
I've a `config` YAML file that refers to cert files by name, all of which are under `~/.kube`. When I hand the `config` file to [KubeConfig](https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/KubeConfig.java), it fails to find the cert files because it looks for them by name, ignoring the path of the `config` file.
**Expected behavior:**
Unless the file paths are already absolute, relativize them with respect to the `config`. It should work when the `config` is loaded as a file, as well as a URL.

**Comment by brendandburns** [comment]
What is the behavior of `kubectl` in this case? Does it work correctly?

If so, we should adopt the same behavior...

**Comment by asarkar** [comment]
`kubectl` works

**Comment by asarkar** [comment]
@brendandburns WDYT?

**Comment by asarkar** [comment]
The best way to solve a problem; do nothing, and let it get closed by inactivity bot.

**Comment by yue9944882** [comment]
/reopen
/assign

sry, the issue doesn't stand out in the flooding notifications.. i will TAL later

**Comment by asarkar** [comment]
@yue9944882 can you please reopen?

**Comment by yue9944882** [comment]
> I've a config YAML file that refers to cert files by name, all of which are under ~/.kube

i didn't know about this usage before. mostly we embed base-64 encoded key-pairs into `kubeconfig`. will TAL at the implementation at go library..
