### ISSUE TITLE
Upgrade to okhttp3 or better yet, use a HTTP client facade like Feign

### ISSUE THREAD

**Issue by asarkar** [kubernetes-client/java#430]
I see that a `4.0.0.-beta-1` branch is in development. This will be a good time to upgrade the OkHttp client to the latest. The migration is relatively painless. The `2.7.5` version been used is almost 2.5 years old, and of course, has been abandoned in favor of [okhttp3](https://search.maven.org/search?q=g:com.squareup.okhttp3).

Another option, albeit more ambitious, would be to use a Facade like [Feign](https://github.com/OpenFeign/feign) that lets the users plugin in their own HTTP clients. That would be extremely useful in many projects where people heavily customize HTTP clients for timeouts, SSL settings and what not.

**Comment by brendandburns** [comment]
This code is all auto-generated by swagger-codegen:

https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/Java/libraries

I see that there is a feign generator, you could try re-generating with that generator...

Alternately you could upgrade the okhttp-gson client to use okhttp3:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache

**Comment by asarkar** [comment]
@brendandburns I'm not clear on what you're suggesting. I'm not compiling the code myself, I'm picking up the `3.0.0` from Maven Central. I also checked the 4.0.0.-beta-1 [pom.xml](https://github.com/kubernetes-client/java/blob/client-java-parent-4.0.0-beta1/kubernetes/pom.xml#L204), and the version is clearly 2.7.5.

**Comment by brendandburns** [comment]
@asarkar I don't think that the 2.7 and 3.0 APIs are the same, thus I don't think we can just upgrade the pom file. 

either way, we can't make changes to the generated code (or pom) in this repository, it needs to be done in the swagger-codegen repository.

**Comment by asarkar** [comment]
@brendandburns It's unlikely that swagger will agree to simply upgrading a client version; perhaps a new module could be created for okhttp3?
As for the API, from what i've seen, the difference is mostly in the package names, and addition of some fluent builders. It is true that the migration is not simply a POM change, but it is also true that it's very straightforward.

What do you think?

**Comment by brendandburns** [comment]
Maybe we should just try generating with the `feign` module instead?

I think either path would be fine. Let me know if you need pointers to the code to get started.

**Comment by alannakelly** [comment]
Since 20 August 2019 JFrog X-Ray is reporting a High Severity security issue with OkHttp 2.70-2.75:

"OkHttp Cached HTTP / HTTP/2 Headers Non-ASCII Character Handling Remote DoS"

This is getting flagged in a scan on a project using Java Kubernetes Client 5.0.0 as OkHttp 2.75 is a dependency.

**Comment by brendanburns** [comment]
We want to get to openapi-generator but there are currently build errors
with their generated code, Min was looking into it a while ago...

**Comment by brendandburns** [comment]
Update, we just merged the switch to openapi generator and okhttp3.

We will cut a 7.0.0 release soon.

**Comment by brendandburns** [comment]
Closing this as we have switched to okhttp3 in the latest clients.
