### ISSUE TITLE
when create crd， occour Internal Server Error

### ISSUE THREAD

**Issue by li1191863273** [kubernetes-client/java#432]
this is issue https://github.com/kubernetes-client/java/issues/428
sorr, I don't know how to reopen this issue

I show error in the k8s-api-server pod by use this command

    PODNAME=$(kubectl -n kube-system get pod -l component=kube-apiserver -o 
    jsonpath='{.items[0].metadata.name}')
kubectl logs $PODNAME -f --tail 500 -n kube-system

the error is

    E1110 08:39:55.796181       1 status.go:64] apiserver received an error that is not an metav1.Status: Object 'Kind' is missing in 'object has no kind field '

so, It look like k8s api-server not receive this body
in this link https://github.com/kubernetes/kubernetes/issues/44182
It occour this error, but it has body

BTW: I user this String as body

      {
      "apiVersion": "networking.istio.io/v1alpha3",
      "kind": "Gateway",
      "metadata": {
        "name": "bookinfo-gateway",
        "namespace": "istio"
      },
      "spec": {
        "selector": {
          "istio": "ingressgateway"
        },
        "servers": [
          {
            "hosts": [
              "*"
            ],
            "port": {
              "name": "http",
              "number": 80,
              "protocol": "HTTP"
            }
          }
        ]
      }
    }

**Comment by brendandburns** [comment]
thanks for the update.
