### ISSUE TITLE
how to watch unscheduled pod event 

### ISSUE THREAD

**Issue by q6413260** [kubernetes-client/java#434]
I want to Customized a kube-scheduler in java instead of default go version。
I meet some trouble on how to find Pods which is waiting for schedule。
the code below

Watch<V1Namespace> watch = Watch.createWatch(
                client,
                api.listNamespacedPodCall("squirrel", null, null, null, null, null, null, null, null, Boolean.TRUE, new ProgressResponseBody.ProgressListener() {
                    @Override
                    public void update(long l, long l1, boolean b) {
                        System.out.println("update");
                    }
                }, new ProgressRequestBody.ProgressRequestListener() {
                    @Override
                    public void onRequestProgress(long l, long l1, boolean b) {
                        System.out.println("onRequestProgress");
                    }
                }),
                new TypeToken<Watch.Response<V1Namespace>>(){}.getType());

when I create a pod by calling api，the method update will be invoked，it is ok。
But the code above will timeout after some time。

so  do i have to wrap the Watch in a loop that retries to solve timeout problems ?

**Comment by brendandburns** [comment]
You can lengthen the timeout to a very long value, see the example here:

https://github.com/kubernetes-client/java/issues/150#issuecomment-352514928

But yes, in general you should wrap a loop around a watch. Indeed, the recommended practice is (in pseudo-code:

```java
while (watching) {
   List podList = client.listPods(...);
   client.watchPods(...);
}
```

That way if the watch breaks, you always refresh with the full state of the world and don't accidentally miss updates.

**Comment by brendandburns** [comment]
Closing this issue since I think the question is answered. Please re-open if you need more info.
