### ISSUE TITLE
Deploy helm charts

### ISSUE THREAD

**Issue by gavinfish** [kubernetes-client/java#435]
I want to deploy helm charts to my kubernetes cluster. Is there plan for this plugin to support that?

**Comment by brendandburns** [comment]
For Helm 2, probably not. It's a totally separate gRPC based API.

For Helm 3, Helm is moving to CRD (Custom Resource Definitions) at which point this library should work (and we could consider adding more full-fledged Helm support as well)

**Comment by brendandburns** [comment]
Closing the issue as the question is answered, please re-open if more info is needed.
