### ISSUE TITLE
How to check whether a namespace exists

### ISSUE THREAD

**Issue by gavinfish** [kubernetes-client/java#440]
I want to check whether a namespace exists by this sdk. But I cannot find any suitable interface here. `new CoreV1Api().readNamespace(spaceName,"false",false,false)` just throw an ApiException when the namespace does not exist.

**Comment by brendandburns** [comment]
There are two options:

1) You can listNamespace(...) and search for the namespace you're interested in.

2) You can catch ApiException and grab the HTTP status code from that exception, if it is `404` then the namespace doesn't exist.

**Comment by gavinfish** [comment]
All right. Both of them should work though I prefer an interface like `hasNamespace`. Thanks!
