### ISSUE TITLE
KubeConfig example would help

### ISSUE THREAD

**Issue by alan-parry** [kubernetes-client/java#446]
I'm using a managed K8s service, Oracle Cloud if that helps. I'm currently managing the cluster via a kubectl and a kubeconfig file.

I've tried the simple example provided to list pods and deployed it in to the cluster but its failing, I believe due to RBAC configuration. Rather than learn RBAC which is more involved than I want to take on right now, does anyone have an example of how I can use a kubeconfig to authenticate against the API. It looks like this is possible with KubeConfig but the docs aren't very clear or I havent found the right one yet!

Thanks,

**Comment by brendandburns** [comment]
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/Example.java#L34

That will load a kubeconfig from $HOME/.kube/config or a $KUBECONFIG environment variable if it exists...

**Comment by brendandburns** [comment]
Closing this as I think that this is answered.

**Comment by hmeerlo** [comment]
Ok, might be me but I don't understand why this is closed. The question was about usage of KubeConfig (the Java class). But the answer was about Config.defaultClient() which uses the default kube config. So 2 completely different things. I'm actually also looking for an example on KubeConfig usage.
