### ISSUE TITLE
Getting "io.kubernetes.client.ApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 0 null"

### ISSUE THREAD

**Issue by devamtech** [kubernetes-client/java#447]
Hi All,

I am getting below error, when I am trying to create pod using kubernates java client.
Error
====================================
io.kubernetes.client.ApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
0
null 
=======================================
my Code
===================================
	String credentials= new String(Base64.getEncoder().encode("username:password".getBytes()));
		ApiClient  defaultClient = Configuration.getDefaultApiClient();
		defaultClient.setBasePath("https://MasterIP/wcp/login");
		ApiKeyAuth fakeBearerToken = (ApiKeyAuth) defaultClient.getAuthentication("BearerToken");
		fakeBearerToken.setApiKey(credentials);
		fakeBearerToken.setApiKeyPrefix("Basic");
		
		Configuration.setDefaultApiClient(defaultClient);
		

		CoreV1Api api = new CoreV1Api(defaultClient);

		try
		{
		V1Pod pod = new V1PodBuilder().withNewMetadata().withName("apod").endMetadata().withNewSpec().addNewContainer()
				.withName("www").withImage("nginx").endContainer().endSpec().build();

		api.createNamespacedPod("deva ", pod, null);
		}catch (ApiException e) {
		      System.out.println(e);
		      System.out.println(e.getCode());
		      System.out.println(e.getResponseBody());

I have completely blocked,

Can you please help on this issue.

many thanks in advance.

**Comment by brendandburns** [comment]
Hard to know exactly, but I suspect that your cluster uses a self-signed certificate and the CA Root isn't in your Kubeconfig file.

If `kubectl` works correctly, please just use the example code:

```java
Config.defaultClient();
```

as in here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/Example.java#L34

And it should work correctly.

If it doesn't, please provide your kubeconfig file (remove the secret certificates first please)

**Comment by brendandburns** [comment]
Note that you really don't want to set validateSSL to false unless you know what you are doing. That makes you vulnerable to man in the middle attacks.

**Comment by gkarthiks** [comment]
@devamtech  as @brendandburns said bypassing the ssl verification is not recommended.  if you still want to do so, here’s the sample code for that. 
https://github.com/gkarthiks/k8s-api-client-examples/blob/e661a30fbf7297d75ec5a640d47c7f56c9a73f42/k8s-access-via-java/src/com/gkarthiks/k8s/ListPod.java#L13 

The last Boolean value determines whether to verify or not.
