### ISSUE TITLE
listServiceForAllNamespacesCall : Client Connection lost after 5 minutes

### ISSUE THREAD

**Issue by sharmmoh1983** [kubernetes-client/java#448]
I have implemented watcher on listServiceForAllNamespacesCall  which is supposed to listen for  changes all the time in the cluster and it is working fine but for some reason on my dev environment connection is getting lost after 5 minutes 

There is no issue happening when it is running locally on minikube

I am not able to comprehend the issue happening

Can anyone throw some light on the issue?

```
Watch.createWatch(***, api.listServiceForAllNamespacesCall(null, null, null,
                    null, 5, null, null, 4800, Boolean.TRUE, null, null), new TypeToken<Watch.Response<V1Service>>() {
                    }.getType());
```

**Comment by brendandburns** [comment]
Watches should be expected to drop.

There are various reasons for this, generally due to socket idle timeouts in the OS or loadbalancers between you and the service.

You should wrap the watch in a loop like this:

```
while(true) {
    currentList := listServices(...)
    watchServices(eventHandler, ...)
}
```

**Comment by sharmmoh1983** [comment]
@brendandburns 
Can you please elaborate more on the watchServices(eventHandler, ...) part ?

I am calling listofServices call within Watch method and when connection is getting dropped , i am again calling Watch createWatch method
