### ISSUE TITLE
AzureActiveDirectoryAuthenticator: invalid token after refresh

### ISSUE THREAD

**Issue by briansolo1985** [kubernetes-client/java#458]
Hello,

I'm a bit stuck with AzureActiveDirectoryAuthenticator. After the current access token expires, AzureActiveDirectoryAuthenticator manages to request a new token, which seems to be invalid apparently.

I can see the following with debug turned on:
`2018-12-06 14:10:17 INFO  AuthenticationAuthority:149 - [Correlation ID: ec162ffd-1a9f-43b8-b1b4-8f0e416fe4d6] Instance discovery was successful
2018-12-06 14:10:19 DEBUG AuthenticationContext:91 - [Correlation ID: ec162ffd-1a9f-43b8-b1b4-8f0e416fe4d6] Access Token and Refresh Token were returned
--> GET https://{ip}:6443/api/v1/namespaces/{nd}/pods/{pod}/exec?stdin=true&stdout=true&stderr=true&tty=true&container=server&command=ls&command=-alh&command=%2Ftmp HTTP/1.1
authorization: Bearer {new_token_returned_by_azure_authenticator}
Sec-WebSocket-Protocol: v4.channel.k8s.io
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: havfMC/uy3lc2dMDFKB+Ng==
Sec-WebSocket-Version: 13
--> END GET
<-- HTTP/1.1 401 Unauthorized (1108ms)
Content-Type: application/json
Date: Thu, 06 Dec 2018 13:10:20 GMT
Content-Length: 129
OkHttp-Sent-Millis: 1544101820479
OkHttp-Received-Millis: 1544101820832`

My .kube/config seems to be okay, because if I run the same command with kubectl
`kubectl exec --v=10 -it --namespace={ns} {pod} -- bash -c "ls -alh"`
it is able to send the request, and return a valid auth token. Until that token expires, the Java application is able to connect as well.

(sensitive data is replaced with placeholders on purpose)

Do you maybe what can be the problem, or at least could you point me toward the right direction?

Many thanks!

**Comment by brendandburns** [comment]
Weird, let me try to repro this. I swear when I tested it, it worked correctly, but something may have regressed.

**Comment by brendandburns** [comment]
The relevant code is here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L195

I'm wondering if it's because authConfig isn't stored back into the map in that code...

There aren't enough unit tests for this code, I will try to add some.
