### ISSUE TITLE
the problem of updating kubernetes-client from 3.2.0 to 4.0.0 

### ISSUE THREAD

**Issue by wangbin3685** [kubernetes-client/java#462]
when  updating kubernetes-client from 3.2.0 to 4.0.0 ,  does it not support io.fabric8.kubernetes.api.model.extensions.Deployment ?

**Comment by wangbin3685** [comment]
what is the difference between io.fabric8.kubernetes.api.model.apps.Deployment and io.fabric8.kubernetes.api.model.extensions.Deployment ?

**Comment by brendandburns** [comment]
This client has never been the fabric8 client. The fabric8 client is a separate effort that uses a hand-coded generator, not the official open api client libraries.
