### ISSUE TITLE
Listing resources based on Labels and Selectors

### ISSUE THREAD

**Issue by mnoumanshahzad** [kubernetes-client/java#463]
Hi

I am using the K8s Java Client API (v. 3.0.0) at the moment.

My workflow is as follows:
1. Create a K8s Deployment (using AppsV1Api)
2. Create a K8s Service on top of it (using CoreV1Api)
3. I then want to execute some bash commands on the respective Pods that are being created by the Deployment in step 1.

Deployment appends random string to the Pod name, which does make sense to uniquely identify different replicas.
However, I cannot find a way to track back the dynamic names of the Pods being deployed.

To my understanding, K8s uses Labels and Selectors to identify dynamic objects (e.g. pods). But there is no API call that can list resources using Labels and Selectors.

Kindly share what is the best practice to achieve such a functionality.

Thank you

**Comment by mnoumanshahzad** [comment]
It was a mistake on my part.
I did not read the complete documentation.

I was able to list Pods based on Selectors and Labels using the `listNamespacedPod` method from `CoreV1Api`

**Comment by brendandburns** [comment]
Closing this as I believe that the question is resolved. Please re-open if there are continued questions.
