### ISSUE TITLE
Question about operation apis

### ISSUE THREAD

**Issue by chlung** [kubernetes-client/java#48]
Hi,

I try to update/replace the statefulset image version.  Can you suggestion where I can find the supported api?

I also posted my question to slack "sig-apis-machinary".  Please advise where is the best place to have my questions answered.

Thanks.

**Comment by lwander** [comment]
@mbohlool can you confirm that you would supply the patched statefulset to this method? https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/AppsV1beta1Api.java#L2368

**Comment by mbohlool** [comment]
I think that patch method is correct. I would try my command with `kubectl -v9 ...` and see what URL it hits and then confirm the url here. We also experienced in python client that content type was wrong for patch method calls and needed to be fixed. That could be the issue here too.

**Comment by chlung** [comment]
From kubernetes example from https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update,

kubectl patch statefulset web --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"gcr.io/google_containers/nginx-slim:0.7"}]'
"web" patched

I will send json object like **[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"gcr.io/google_containers/nginx-slim:0.7"}]**  should be enough for me to update the image version?

Thanks.

**Comment by chlung** [comment]
@mbohlool  I also see another api - https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/AppsV1beta1Api.java#L3857

What are the differences between these two apis?

Thanks.

**Comment by lwander** [comment]
Replace should delete & create a new statefulset with the given spec, rather than update (keep running) an existing one.

**Comment by chlung** [comment]
Hi @mbohlool Can you confirm that you are getting the same error like me?
I create V1betaStatefulset object and make the following api call
apps.patchNamespacedDeploymentCall(statefulSetName, namespace, stateful, null, null, null)

I got exception like
io.kubernetes.client.ApiException: Content type "application/json-patch+json" is not supported

Thanks

**Comment by mbohlool** [comment]
These are related issues in python client:
https://github.com/kubernetes-incubator/client-python/issues/187
https://github.com/kubernetes-incubator/client-python/issues/93

Probably the fix here is involve some changes in ApiClient as well. Let me know if any of those helps.

**Comment by chlung** [comment]
@mbohlool If the fix is in java ApiClient, are you planning to fix java ApiClient?  thanks.

**Comment by mbohlool** [comment]
I don't have a short term plan to work on this. But added the label so anybody with free time pick it up. That could be me after I cleared up my calendar a bit in future.

**Comment by chlung** [comment]
@mbohlool Thanks for your update.  I also see some similar problem in replaceNamespacedStatefulSet
Here is error - io.kubernetes.client.ApiException: Content type "*/*" is not supported

**Comment by lwander** [comment]
I can look into this - it seems we always pick `"application/json-patch+json"` (see [here](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/AppsV1beta1Api.java#L2391), but never managed to get kubectl to supply a patch that's not in the form `"application/strategic-merge-patch+json"`. We could either override how [`selectHeaderFunctionality`](https://github.com/swagger-api/swagger-codegen/blob/53bd931f5c57eeb805ef38e47a880d73e3dbdc5d/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L780) works in a custom `ApiClient`, or patch the mustache template to take as an argument what type of  JSON patch is being applied, or look into other solutions.

**Comment by lwander** [comment]
Or we could just require each patch to be `"application/strategic-merge-patch+json"`, and always make that the content-type.

**Comment by mbohlool** [comment]
I think patching ApiClient is acceptable as we are diverging from templates. Any change to templates should be ported back to swagger-codegen and hence should be generic enough.

In term of what should be the right patch header, I never spend enough time on this to have strong opinion, but at least from what I saw in discussions of python client, there is no ONE right choice and we may need to decide on the header based on what user provided as body parameter.

**Comment by chlung** [comment]
In order for me to move forward, I try to comment out these lines. https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/AppsV1beta1Api.java#L1937-L1941.  Now, I am getting error `io.kubernetes.client.ApiException: Not Found`

==>Statefulset can be found with read/get api
apiInstance.readNamespacedStatefulSet(statefulSetName, namespace, null, true, true);

==>Statefulset cannot be found with patch api.
apiInstance.patchNamespacedDeployment(statefulSetName, namespace, body, null);

**Comment by lwander** [comment]
If you comment those out you won't have a content type on the patch operation. I raised an issue about this here: https://github.com/swagger-api/swagger-codegen/issues/6053

**Comment by chlung** [comment]
@lwander ok.  thanks.

**Comment by chlung** [comment]
The header issue also can be reproduced with AppsV1beta1Api.createNamespacedStatefulSet call.  The error is about Content-Type "*/*"

**Comment by chlung** [comment]
To reproduce "not found" error.  Use the get to retrieve the statefulset and patch with that statefulset

V1beta1StatefulSet result = apiInstance.readNamespacedStatefulSet(name, namespace, null, true, true);
AppsV1beta1Deployment resultx = apiInstance.patchNamespacedDeployment(name, namespace, result, null)

**Comment by chlung** [comment]
@mbohlool Lars fixed header issue in swagger-codegen project(https://github.com/kubernetes-client/java/issues/58).  Code have been merged.  Do you know how k8s client java api can pick up his changes?  thanks.

**Comment by mbohlool** [comment]
@chlung look at https://github.com/kubernetes-client/java/pull/61

**Comment by chlung** [comment]
Hi, I am testing k8s java client api 0.1.  Per the latest k8s document(https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/#alternative-kubectl-apply--kubectl-edit--kubectl-patch), I notice the patch payload is different from before.  Any recommendations?  Any background about this change?  

Before,
'[{"op": "replace", "path": "spec/replicas", "value":<new-replicas>}]'

Now,
'{"spec":{"replicas":<new-replicas>}}'

Thanks.

**Comment by mbohlool** [comment]
Did you try `kubectl -v9 ...` to see what is the exact payload that client sends to server? note that kubectl can modify payload provided by user to make it easier in command line however these generated clients are the exact replica of API server's entry points and may be different that what kubectl accepts but should be the same as what kubectl sends to server.

**Comment by chlung** [comment]
@mbohlool Thanks.  I will give it a try.

**Comment by chlung** [comment]
With v0.1, I cannot access "V1beta1StatefulSetSpec.updateStrategy" field.
From 1.7 api document, I should be able to access it https://kubernetes.io/docs/resources-reference/v1.7/#statefulset-v1beta1-apps 

Does v0.1 only support 1.6 k8s api? 

Thanks.

**Comment by lwander** [comment]
If it was added in 1.6, it won't be supported in the client yet: https://github.com/kubernetes-client/java#compatability

**Comment by chlung** [comment]
Thanks.

**Comment by lwander** [comment]
@chlung patch operations work just fine as long as you supply a "json patch" style body. Until v3 of the openapi spec, there is really no clean way to pick the [right header type](https://github.com/swagger-api/swagger-codegen/issues/6053). 

See an example using the json patch body [here](https://github.com/spinnaker/clouddriver/pull/1868/files#diff-150b8912ec8e0cd49b16cb79345b11e7R98).

As long as we document how to use the patch operations, I think we can safely close this for now @mbohlool, WDYT?

**Comment by chlung** [comment]
My testing steps:
1, create an json like '[{"op": "replace", "path": "spec/replicas", "value": 3}]' object because api accepts an object.
2. call patch api

I did not include any headters.  It works for me so far for resizing operation.

**Comment by lwander** [comment]
The headers get included for you -- did it work?

**Comment by chlung** [comment]
@lwander After you patched headers issues, all my api calls are working fine.  I don't need to include any extra header or fix client api code.  I can close this issue, but I really would like to see more thoroughly examples for each type of HTTP call.  thanks.

**Comment by lwander** [comment]
That's great :)

As far as examples go: how about from now we file a new issue each time you're unsure of how to invoke a certain operation (e.g. "how do I list pods by selector"). I can supply an example, and this will keep the issue tracker easy to search & available as a form of documentation.

**Comment by chlung** [comment]
The client for POST/PUT/DELETE/PATCH api call header issue can be closed.  Thanks @lwander for providing a patch.

**Comment by HarsimranAvaya** [comment]
static String jsonPatchStr = "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"xxx-container\",\"image\":\"xx/xxxx-app:3.0.1.45\"}]}}}}";
//static String jsonPatchStr = "{ \"op\": \"replace\", \"path\":\"/spec/template/spec/containers/1/image\", \"value\":\"xx/xxxx-app:3.0.1.45\" }";

Why structure one never works when using patchNamespacedDeployment method of Java client of kubernetes.My requirement is to update on the basis of Container name and image version.
