### ISSUE TITLE
can I use " kubectl rollout pause deployment <deployment> " with java API ?

### ISSUE THREAD

**Issue by zhangrc** [kubernetes-client/java#480]
the commond " kubectl rollout pause deployment <deployment> "  can I use API to operate it?

**Comment by brendandburns** [comment]
That command modifies the `Deployment` object, so you'll want to use either the Patch or Put API on Deployments:

See for example: 

https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AppsV1Api.md#patchNamespacedDeployment
