### ISSUE TITLE
Not able to delete job using ttlSecondsAfterFinished

### ISSUE THREAD

**Issue by krishnag9** [kubernetes-client/java#485]
This is my spec that I have used to create the job

V1JobSpec jobspec = new V1JobSpec();
jobspec.setTemplate(template);
jobspec.setTtlSecondsAfterFinished(360);

apiInstance.createNamespacedJob(namespace, job, null, null, null);

The above has to create a job and a pod which is happening correctly. So when the job completes it has to delete the job and pod after 360 seconds which is not happening.

**Comment by brendandburns** [comment]
TTL delete is an Alpha feature in the 1.12 API. Are you sure that it is active in your cluster?

There's nothing in this client library that would affect this behavior one way or the other, unless when you re-read the created `Job` the field isn't set.

If you do `kubectl get jobs <job-name>` and the field isn't set correctly, please re-open this issue and include the complete repo.

Thanks!

**Comment by krishnag9** [comment]
It is taking ttlSecondsAfterFinished as null

class V1Job {
    apiVersion: batch/v1
    kind: Job
    metadata: class V1ObjectMeta {
        annotations: null
        clusterName: null
        creationTimestamp: 2019-01-23T07:35:40.000-06:00
        deletionGracePeriodSeconds: null
        deletionTimestamp: null
        finalizers: null
        generateName: null
        generation: null
        initializers: null
        labels: {controller-uid=c6573490-1f13-11e9-832e-525400184c7c, job-name=job-5c4735314b1f1200016f8385-1548250539467}
        name: job-5c4735314b1f1200016f8385-1548250539467
        namespace: msgbus
        ownerReferences: null
        resourceVersion: 4271694
        selfLink: /apis/batch/v1/namespaces/msgbus/jobs/job-5c4735314b1f1200016f8385-1548250539467/status
        uid: c6573490-1f13-11e9-832e-525400184c7c
    }
    spec: class V1JobSpec {
        activeDeadlineSeconds: null
        backoffLimit: 6
        completions: 1
        manualSelector: null
        parallelism: 1
        selector: class V1LabelSelector {
            matchExpressions: null
            matchLabels: {controller-uid=c6573490-1f13-11e9-832e-525400184c7c}
        }
        template: class V1PodTemplateSpec {
            metadata: class V1ObjectMeta {
                annotations: null
                clusterName: null
                creationTimestamp: null
                deletionGracePeriodSeconds: null
                deletionTimestamp: null
                finalizers: null
                generateName: null
                generation: null
                initializers: null
                labels: {controller-uid=c6573490-1f13-11e9-832e-525400184c7c, job-name=job-5c4735314b1f1200016f8385-1548250539467}
                name: null
                namespace: null
                ownerReferences: null
                resourceVersion: null
                selfLink: null
                uid: null
            }
            spec: class V1PodSpec {
                activeDeadlineSeconds: null
                affinity: null
                automountServiceAccountToken: null
                containers: [class V1Container {
                    args: [python3 -u startJob.py abc def]
                    command: [/bin/bash, -c]
                    env: null
                    envFrom: null
                    image: fnc-docker-reg:3000/script_execution
                    imagePullPolicy: Always
                    lifecycle: null
                    livenessProbe: null
                    name: job-container-5c4735314b1f1200016f8385-1548250539467
                    ports: null
                    readinessProbe: null
                    resources: class V1ResourceRequirements {
                        limits: null
                        requests: null
                    }
                    securityContext: null
                    stdin: null
                    stdinOnce: null
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    tty: null
                    volumeDevices: null
                    volumeMounts: null
                    workingDir: null
                }]
                dnsConfig: null
                dnsPolicy: ClusterFirst
                hostAliases: null
                hostIPC: null
                hostNetwork: null
                hostPID: null
                hostname: null
                imagePullSecrets: null
                initContainers: null
                nodeName: null
                nodeSelector: null
                priority: null
                priorityClassName: null
                readinessGates: null
                restartPolicy: Never
                runtimeClassName: null
                schedulerName: default-scheduler
                securityContext: class V1PodSecurityContext {
                    fsGroup: null
                    runAsGroup: null
                    runAsNonRoot: null
                    runAsUser: null
                    seLinuxOptions: null
                    supplementalGroups: null
                    sysctls: null
                }
                serviceAccount: null
                serviceAccountName: null
                shareProcessNamespace: null
                subdomain: null
                terminationGracePeriodSeconds: 30
                tolerations: null
                volumes: null
            }
        }
        ttlSecondsAfterFinished: null
    }
    status: class V1JobStatus {
        active: null
        completionTime: 2019-01-23T07:37:52.000-06:00
        conditions: [class V1JobCondition {
            lastProbeTime: 2019-01-23T07:37:52.000-06:00
            lastTransitionTime: 2019-01-23T07:37:52.000-06:00
            message: null
            reason: null
            status: True
            type: Complete
        }]
        failed: null
        startTime: 2019-01-23T07:35:40.000-06:00
        succeeded: 1
    }
}
