### ISSUE TITLE
Which API can be used to create custom resource object instance?

### ISSUE THREAD

**Issue by JoeyLuffa** [kubernetes-client/java#487]
Let's assume that I already have the CRD: `sparkApplication`. Now, I would like to talk to this API and create an instance of the spark application. 

By default, we use `kubectl apply -f spark-pi.yaml'  The spark-pi.yaml is [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml). So how can I use the kubectl Java client to achieve this? Thanks.

**Comment by brendandburns** [comment]
The docs here:

https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CustomObjectsApi.md

Should get you headed in the right direction. Let me know if you need more info.

Thanks

**Comment by JoeyLuffa** [comment]
Hi @brendanburns  I used this to initialize the Java client:

```
val client = Config.defaultClient
Configuration.setDefaultApiClient(client)
```

And this works for the `CoreV1Api`'s `listPodForAllNamespaces` method:

```
val api = new CoreV1Api
val list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null)
import scala.collection.JavaConversions._
```

However, when it comes to the `CustomObjectsApi`:

```
val apiInstance = new CustomObjectsApi
...// setting up some arguments
val result = apiInstance.createNamespacedCustomObject(group, version, namespace, plural, body, pretty)
```

I got:
```
Exception when calling CustomObjectsApi#createNamespacedCustomObject
io.kubernetes.client.ApiException: Internal Server Error
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CustomObjectsApi.createNamespacedCustomObjectWithHttpInfo(CustomObjectsApi.java:349)
	at io.kubernetes.client.apis.CustomObjectsApi.createNamespacedCustomObject(CustomObjectsApi.java:330)
```

Can I know what went wrong here? Thanks.

**Comment by brendanburns** [comment]
Yeah I'm pretty sure that's an http 500 coming from the k8s API server.

You could print the response body to be certain.

**Comment by brendandburns** [comment]
I'm going to close this, since it's resolved (I think) feel free to open an additional issue if you need further assistance.

**Comment by nishantsh77** [comment]
> I figured out the issue. The `body` format was not correct. I fixed it and now it works.
> 
> However, the client returns `Internal Server Error` which is misleading. Is it coming from Kubenetes?

@JoeyLuffa Can you please share "format" of body. I tried JSON format but getting "io.kubernetes.client.ApiException: Bad Request". As per https://github.com/kubernetes-client/java/issues/428, is it Map<String, Object> ?
I am trying to invoke createNamespacedCustomObject(..) for sparkoperator.k8s.io and converted YAML to JSON. But its not working.

**Comment by nishantsh77** [comment]
@JoeyLuffa Please ignore my query. I resolved it.
The answer is to convert JSON into Map<String,Object>

**Comment by talgos1** [comment]
@nishantsh77 could you please share your code?

**Comment by mkubit-pl** [comment]
Working example in case anybody needs it (tested with K8s Java SDK 10.0.0):

```java
import io.kubernetes.client.openapi.ApiClient;
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.apis.CustomObjectsApi;
import io.kubernetes.client.util.Config;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Map;

class KubernetesApplyCrdTest {

        /* 
        
        My CRD's (called Tenant) instance I'd like to apply on my cluster:
        
        apiVersion: example/v1alpha1
        kind: Tenant
        metadata:
          name: foodco
        spec:
          name: foodco
          id: foodco
          my_custom_config:
            FOO: "BAR"

     */

    @Test
    void applyCrd() throws IOException, ApiException {
        Map<String, Object> cfg = Map.of(
                "apiVersion", "example/v1alpha1",
                "kind", "Tenant",
                "metadata", Map.of("name", "foodco"),
                "spec", Map.of(
                        "name", "foodco",
                        "id", "foodco",
                        "my_custom_config", Map.of(
                                "FOO", "BAR"
                        )
                )
        );

        ApiClient client = Config.defaultClient(); // it will try to discover the k8s connection from known places such as ~/.kube/config 
        var objectsApi = new CustomObjectsApi(client);
        objectsApi.createNamespacedCustomObject(
                "example",
                "v1alpha1",
                "default",
                "tenants",
                cfg,
                null,
                null,
                null
        );
    }
}
```

then in the cluster I can see:
```
❯ k get tenant          
NAME     AGE
foodco   10m
```
