### ISSUE TITLE
Consider making swagger-annotations a "provided" dependency

### ISSUE THREAD

**Issue by nresare** [kubernetes-client/java#488]
kubernetes-java-api has a runtime dependency on swagger-annotations. This adds to the transitive dependency complexity of kubernetes-client and is not needed to use the client.

The only case where the dependency is even remotely useful is when a user would traverse the byte code using reflection and extract the documentation annotation. In such very rare cases I don't think that it is too much to ask to add this dependency to the processing code explicitly.

**Comment by brendandburns** [comment]
@nresare thanks for the report. Unfortunately this comes in via code-generation so it's not quite trivial to unwind it, but we'll see what we can do.

**Comment by markusheiden** [comment]
Even more this dependency is dangerous!
See https://github.com/kubernetes-client/java/issues/570
Please re-consider removing it.

/remove-lifecycle stale
