### ISSUE TITLE
how to use kubectl apply in kubernetes-client

### ISSUE THREAD

**Issue by fewstrong87** [kubernetes-client/java#489]
how to run it `kubectl apply -f stuff.yaml` in kubernetes-client

**Comment by brendandburns** [comment]
You can not currently use 'apply' since it is implemented in `kubectl` itself. There is a plan to move it to the server in Kubernetes, then it will work properly from this client.  See:

https://github.com/kubernetes/enhancements/issues/555

**Comment by anton-johansson** [comment]
Does anyone know any good workaround or replacement for this? I want to update deployments using the same (but tweaked) YAML. I could of course delete the deployment and re-create it, but then I wouldn't get rolling updates.
