### ISSUE TITLE
How to calculate available free resources in a kubernetes node

### ISSUE THREAD

**Issue by pankajsaha** [kubernetes-client/java#490]
I am using official kubernetes java api for controlling a local kubernetes cluster. what is the best way to calculate the available resources for each node in the cluster. Is there any api method for V1Node which can do that for me? If not, then any suggestion to do this with java code will be really helpful.

**Comment by pankajsaha** [comment]
node.getStatus().getAllocatable().get("cpu").getNumber()
    node.getStatus().getCapacity().get("cpu").getNumber()
these two methods provide allocatable and total capacity of each node. However, it not sure how to find the available free resources. For me, even though pods are running in my local cluster, the value of "allocatable" and "capacity" comes the same.

**Comment by brendandburns** [comment]
Do your pods have resource requests/limits set? By default they usually do not.

The Node API is described in detail here:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#node-v1-core

You should be able to access all of those fields from the Java client library.
