### ISSUE TITLE
kubectl describe pvc response query

### ISSUE THREAD

**Issue by vivekpatani** [kubernetes-client/java#491]
**Command:**
```$ kubectl describe pvc xxxx```

**Response:**
```
Name: xxxx
Namespace: xxxx
StorageClass:  xxxxx
Status: xxxx
Volume: xxxxx
Labels: xxxxx
Annotations: xxxx
Finalizers: xxxxx
Capacity: xxxxx
Access Modes: xxxx
Events: xxxxx
Mounted By: xxxxxx
```

On entering the above command I get the expected response. After adding `-v=9` I track the requests and couldn't find from where the `Mounted By: xxxxxx` came from? I'm looking for an equivalent function to this command if it exists in the client. Any help would be appreciated. Thanks.

This is not a contribution.

**Comment by brendandburns** [comment]
Relevant code is here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe/versioned/describe.go#L1461

Looks like they go and scrape Pods for the volume reference. You could do similar things with this library, but there's not a one function that will do it for you.

Hope that helps. Closing as answered.

**Comment by 329888410** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe/versioned/describe.go#L1461

This page was 404.
