### ISSUE TITLE
Feature Request: Watch with Callback

### ISSUE THREAD

**Issue by runzexia** [kubernetes-client/java#494]
Now my watch method only allows me to use iterators to get information. I currently want to implement a controller in java. I need a lot of time to implement the watch callback method. If possible, I hope to implement this part of the logic in the official client.

**Comment by brendandburns** [comment]
Yep, definitely on the list of things to do...

**Comment by jglick** [comment]
Does #461 do this?

**Comment by runzexia** [comment]
@jglick  yes

**Comment by brendandburns** [comment]
Closing since #461 has merged.
