### ISSUE TITLE
CoreV1Api.patchNamespacedService throws 500 Internal server error when trying to update the label selector with statefulset.kubernetes.io/pod-name label

### ISSUE THREAD

**Issue by radhe-sravan** [kubernetes-client/java#495]
I am trying to update the statefulset.kubernetes.io/pod-name label selector in a service  with a new pod name. This is the patch request I am using : {\"op\":\"replace\",\"path\":\"/spec/selector/statefulset.kubernetes.io/pod-name\",\"value\": \"pod-name\"}.
Following a few of the earlier issues I have taken this as an example : https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java and was deserializing the string as an object and passing it in. But this results in an Internal Server Error. However when I use the same patch request with a simple label without any / in it it works fine. For instance : 
{\"op\":\"replace\",\"path\":\"/spec/selector/abc\",\"value\": \"pod-name\"}.

**Comment by brendandburns** [comment]
Please look at the response body (`ApiException.getResponseBody()`} Hopefully there is more detail there.

(though in general the API server shouldn't throw a 500, you might want to look at your API server logs)

If you can send a complete repro I can try to see what is going wrong.

**Comment by radhe-sravan** [comment]
Hi Brendan,

This is the response body for the exception :

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jsonpatch replace operation does not apply: doc is missing path: /spec/selector/statefulset.kubernetes.io/pod-name","code":500}

**Comment by kondapally1989** [comment]
if key contains '/' in it.

you can have path like this 
/spec/selector/statefulset.kubernetes.io~1pod-name

you can generate valid json patches  via some online tools https://json-patch-builder-online.github.io/
to see how a patch can look.

**Comment by radhe-sravan** [comment]
Thanks @kondapally1989 . That worked.
