### ISSUE TITLE
Protos are missing v2beta2 HorizontalPodAutoscalerSpec

### ISSUE THREAD

**Issue by cliveseldon** [kubernetes-client/java#496]
This is because the generate script https://github.com/kubernetes-client/gen/blob/master/proto/generate.sh is missing this proto. I have added an issue in the gen project.

https://github.com/kubernetes-client/gen/issues/99

**Comment by brendandburns** [comment]
Yeah, plus we haven't run generation in a while. I'll try to get on that...

**Comment by cliveseldon** [comment]
Should be fixed by https://github.com/kubernetes-client/gen/pull/100 and then a generation run.

**Comment by brendandburns** [comment]
@cliveseldon I sent #498 to fix this, please take a look when you get a chance.

**Comment by cliveseldon** [comment]
I added lgtm. Thanks.
