### ISSUE TITLE
How to config k8s client so that it can talk to k8s CRDs from a k8s cluster pod?

### ISSUE THREAD

**Issue by JoeyLuffa** [kubernetes-client/java#503]
The examples in the k8s java client all use default client:

```
ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);
```

How I can config k8s client so that it can talk to k8s CRDs (say, sparkoperator) from a k8s cluster pod? How should I config this client? (basePath, authentications?) And what is the basePath I should use within a pod in the same k8s cluster?

**Comment by brendandburns** [comment]
You shouldn't need any of that, the `defaultClient()` code should take care of that for you, specifically:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L99

You can also use `ClientBuilder.cluster().build()` if you prefer.
