### ISSUE TITLE
Strange API versions in Yaml class? 

### ISSUE THREAD

**Issue by johnlabarge** [kubernetes-client/java#507]
Possibly dumb question.  But the manifests use lowercase versions such as [v1](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/), not capitalized "V1".  Should these be capitalized?  I'm trying to use this to parse a manifest and obviously having some trouble.  

In addition I recognize that this may be foolhardy in general as I end up with a "Object" in return that I then need to cast somehow - nonetheless I was trying to poke at the class and see what it does and how I might use it. 

https://github.com/kubernetes-client/java/blob/004cc202e205f7edf5ab3a28897c0b4f5594b92e/util/src/main/java/io/kubernetes/client/util/Yaml.java#L83

**Comment by brendandburns** [comment]
This is to do auto-introspection and has to do with how the generated Java classes are named (where the 'v' is capitalized)

There's a YAML example here:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/YamlExample.java

Which you ought to be able to start from...

Closing, please re-open if there are further questions (or file new issues :)

**Comment by johnlabarge** [comment]
Right I notice that that example only deals with creating manifests, not loading them.  I was trying to load a yaml manifest file.  It appears that that functionality is not supported by the Yaml.load() method for the reason I mention.  I'll open a new issue explaining further.
