### ISSUE TITLE
How to create a StatefulSet using kubernetes-client?

### ISSUE THREAD

**Issue by Gsssyp** [kubernetes-client/java#508]
How to create a StatefulSet using kubernetes-client? xoxo

**Comment by brendandburns** [comment]
There are lots of examples here:

https://github.com/kubernetes-client/java/tree/master/examples/src/main/java/io/kubernetes/client/examples

That should be sufficient to get you started.

**Comment by Gsssyp** [comment]
Thank you very much for your reply. 

Maybe I'm rather dumb. I can't find any examples about safe fulsets. Can you give me an example? 

Thank you dear.

**Comment by Gsssyp** [comment]
HaHa, This problem has been solved. 
 I would like to ask you if there are any documents and so on, which can not be easily consulted when used.
