### ISSUE TITLE
Catch FailedScheduling events in Java Client API

### ISSUE THREAD

**Issue by IvanMijailovic** [kubernetes-client/java#513]
Hi All,
Is there a way to catch/obtain FailedScheduling events with PodExceedsFreeCPU or PodExceedsFreeMemory reasons in Java Client API code?
On the other hand, make Java Client code aware of these failed events.

Thanks in advance

**Comment by brendandburns** [comment]
Yes, you can use the `List*Events` functions to get events

https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/EventsV1beta1Api.md#listEventForAllNamespaces
