### ISSUE TITLE
getting connection error from pod java client

### ISSUE THREAD

**Issue by gangakrishh** [kubernetes-client/java#514]
I'm getting connection error from pod (app uses java client)

```io.kubernetes.client.ApiException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:443```

what could be problem ?

I looked at basic example https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/Example.java

**Comment by gangakrishh** [comment]
never mind it is working..

**Comment by jewelcai** [comment]
How did u resolve it?
