### ISSUE TITLE
How to convert response from CustomObjectsApi.createNamespacedCustomObject to the custom class

### ISSUE THREAD

**Issue by yiyijin** [kubernetes-client/java#515]

**Comment by yiyijin** [comment]
Hi, I have a class called V1MyCrd, and I use following api to create an instance my CRD: 

```java
V1MyCrd crd = new V1MyCrd();
Object res = psmartApi.createNamespacedCustomObject("my.group", "v1", "test", "mycrds", crd, "true");
```
my question is how can I convert Object res to V1MyCrd?

if I do  type casting directly, I got exception as: 
exception is: com.google.gson.internal.LinkedTreeMap cannot be cast to com.test.V1MyCrd

below are the fields from V1MyCrd:
```java
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private V1ObjectMeta metadata = null;

  @SerializedName("spec")
  private V1MyCrdSpec spec = null;
```

and V1MyCrdSpec looks like:

```java
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("replicas")
  private Integer replicas = null;
```

Thanks a lot!

**Comment by yiyijin** [comment]
Figured out

**Comment by rjeberhard** [comment]
@yiyijin, what was the answer to your question?

**Comment by yiyijin** [comment]
Hi @rjeberhard 
lets say my CRD is called V1MyCRD

for a get call:
```java
private CustomObjectsApi crdApi;
Object o = crdApi.getNamespacedCustomObject(group, "v1", "test", "mycrds", "crd-name");
```

then convert from object to V1MyCRD:

```java
private V1MyCRD convertObjectToPsmart(Object o) {
    if (o == null) return null;
    Gson gson = new JSON().getGson();
    JsonElement jsonElement = gson.toJsonTree(o);
    V1MyCRD crd = gson.fromJson(jsonElement, V1MyCRD.class);
    return crd;
  }
```
and `new JSON()...` comes from `io.kubernetes.client.JSON`

**Comment by ZP-AlwaysWin** [comment]
hi @yiyijin @rjeberhard:

Do you have any discussions on this issue? I have the same problem.

**Comment by ZP-AlwaysWin** [comment]
> Hi @rjeberhard
> lets say my CRD is called V1MyCRD
> 
> for a get call:
> 
> ```java
> private CustomObjectsApi crdApi;
> Object o = crdApi.getNamespacedCustomObject(group, "v1", "test", "mycrds", "crd-name");
> ```
> 
> then convert from object to V1MyCRD:
> 
> ```java
> private V1MyCRD convertObjectToPsmart(Object o) {
>     if (o == null) return null;
>     Gson gson = new JSON().getGson();
>     JsonElement jsonElement = gson.toJsonTree(o);
>     V1MyCRD crd = gson.fromJson(jsonElement, V1MyCRD.class);
>     return crd;
>   }
> ```
> 
> and `new JSON()...` comes from `io.kubernetes.client.JSON`

nice I can use this parse.

**Comment by satyy** [comment]
@yiyijin Thanks a lot.  
This solution is working and solved my problem.  👍
