### ISSUE TITLE
Patch node with taints using add is overriding already added taints

### ISSUE THREAD

**Issue by AlexGoo** [kubernetes-client/java#517]
Hello,

I have a problem with patch node method. Basically I am able to patch a node, in my case updating taints, but the problem is that using add operator it adds the new taints but deletes the old ones.

Basically is not merging is overriding.

This is the patch 
"{\"op\":\"add\",\"path\":\"/spec/taints\",\"value\":[{\"effect\":\"NoExecute\",\"key\":\"node.kubernetes.io/unreachable\"}]}"

**Comment by brendandburns** [comment]
This is one of the challenges of JSON-Patch.

See here:

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md
