### ISSUE TITLE
Not sufficient exception information 

### ISSUE THREAD

**Issue by chlung** [kubernetes-client/java#52]
Hi,

I am using `createNamespacedStatefulSet(...)` api to create a new statefulset.  The statefulset is created, but I am getting the following error which did not have sufficient information to tell me where is the error for me to fix.  Also, what is the api for `kubernetes apply`?

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'class V1beta1StatefulSet {
    apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata: class V1ObjectMeta {
 ...
}' with class 'io.kubernetes.client.models.V1beta1StatefulSet' to class 'io.kubernetes.client.models.AppsV1beta1Deployment'

Thanks.

**Comment by lwander** [comment]
Can you show me the code you're trying to run? It looks like you might be passing a statefulset to an operation that requires a deployment.

**Comment by chlung** [comment]
@lwander I am following this example https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AppsV1beta1Api.md#createNamespacedStatefulSet.  I also comment out the header(Content-Type) like the other issue.  So, I am able to create the statefulset.  Thanks.

**Comment by lwander** [comment]
So the only change you made to the example was to comment out the content type header?

**Comment by chlung** [comment]
Yes.  I am getting the other exception after statefulset created.  I try to find out what is the problem about that exception, but the exception does not tell me much.

**Comment by lwander** [comment]
Can you paste your code? I don't see how changing the header would cause a class cast exception.

**Comment by lwander** [comment]
Or link to the branch where you have made these changes

**Comment by chlung** [comment]
Master branch with commending out - https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/AppsV1beta1Api.java#L388-L392

I believe the call goes through and create the statefulset.  Then, the call returns with cast exception.

**Comment by chlung** [comment]
OK.  I see my issue.  Thanks.

**Comment by chlung** [comment]
@lwander I will close this issue.  Header issue will be tracked with https://github.com/kubernetes-client/java/issues/48.  Thanks.
