### ISSUE TITLE
V1SecurityContext privileged not dumped to YAML

### ISSUE THREAD

**Issue by mihirnimbalkar** [kubernetes-client/java#531]
`public String getSecurityContextYaml() {
    return new Yaml().dump(new V1Pod()
        .apiVersion("v1")
        .kind("Pod")
        .spec(new V1PodSpec().addContainersItem(
            new V1Container()
                .image("gcr.io/test/image")
                .securityContext(new V1SecurityContext().privileged(true)))));
  }

@Test
  public void securityContextTest() {
    String yaml = creator.get().getSecurityContextYaml();
    assertThat(yaml).contains("privileged");
  }`

Output:
`expected to contain:
    privileged
but was:
    !!io.kubernetes.client.models.V1Pod
    apiVersion: v1
    kind: Pod
    metadata: null
    spec:
      activeDeadlineSeconds: null
      affinity: null
      containers:
      - args: null
        command: null
        env: null
        envFrom: null
        image: gcr.io/test/image
        imagePullPolicy: null
        lifecycle: null
        livenessProbe: null
        name: null
        ports: null
        readinessProbe: null
        resources: null
        securityContext: {capabilities: null, runAsGroup: null, runAsUser: null, seLinuxOptions: null}
        terminationMessagePath: null
        terminationMessagePolicy: null
        volumeDevices: null
        volumeMounts: null
        workingDir: null
      dnsConfig: null
      dnsPolicy: null
      hostAliases: null
      hostname: null
      imagePullSecrets: null
      initContainers: null
      nodeName: null
      nodeSelector: null
      priority: null
      priorityClassName: null
      restartPolicy: null
      schedulerName: null
      securityContext: null
      serviceAccount: null
      serviceAccountName: null
      subdomain: null
      terminationGracePeriodSeconds: null
      tolerations: null
      volumes: null
    status: null`

SecurityContext#privileged property doesn't get converted to YAML. I've tried using both import org.yaml.snakeyaml.Yaml and io.kubernetes.client.util.Yaml.

**Comment by brendandburns** [comment]
This code:
```java
new V1Pod()
.apiVersion("v1")
.kind("Pod")
.spec(new V1PodSpec().addContainersItem(
new V1Container()
.image("gcr.io/test/image")
.securityContext(new V1SecurityContext().privileged(true))
```
Is a builder, so it creates a `V1Pod` object, not a `V1SecurityContext` so this is working as intended.
If you want to dump the context you need to do:

```java
V1Pod pod = new V1Pod().....
V1SecurityContext ctx = pod.getSecurityContext()
...
```

**Comment by mihirnimbalkar** [comment]
Thanks for the reply!

The bug here is, when you convert a V1Pod object with a V1SecurityContext to YAML, the converted YAML contains rest of the SecurityContext fields, but the privileged field goes on missing:
`securityContext: {capabilities: null, runAsGroup: null, runAsUser: null, seLinuxOptions: null}`. And

`return new Yaml().dump(new V1Pod()
.apiVersion("v1")
.kind("Pod")
.spec(new V1PodSpec().addContainersItem(
new V1Container()
.image("gcr.io/test/image")
.securityContext(new V1SecurityContext().runAsUser(1001L)))));`

works fine:

`securityContext: {capabilities: null, runAsGroup: null, runAsUser: 1001, seLinuxOptions: null}`

To give a background: in our current system, we run a standalone kubelet which reads pod definition YAML file from a local dir. We currently have a custom logic to generate such YAML file. We've plans to gradually move to Google Kubernetes based system in which pods will be pushed using Kubernetes Java API. This is an intermediate step in the migration, in which, we're replacing custom YAML generation logic with kubernetes API objects i.e., V1Pod.

**Comment by mihirnimbalkar** [comment]
Ah I suspect it's related to https://github.com/kubernetes-client/java/issues/340
