### ISSUE TITLE
createNamespacedReplicaSet question

### ISSUE THREAD

**Issue by chlung** [kubernetes-client/java#54]
Hi,

I notice that both AppV1beta1Api (https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AppsV1beta1Api.md#createnamespacedstatefulset) and ExtensionV1beta1Api (https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/ExtensionsV1beta1Api.md#createnamespacedreplicaset) classes can access createNamespacedReplicaSet method.  What are the differences and any suggestions?

Thanks.

**Comment by brendandburns** [comment]
One is for `ReplicaSet` and one is for `StatefulSet`.

ReplicaSet is best suited for stateless applications whereas StatefulSet is best suited for statefull applications.

Hope that helps.

**Comment by chlung** [comment]
OK.  Thanks.  I must read it wrong.  I thought that both are for statefulset.
