### ISSUE TITLE
Help on readNamespacedPodLog reading less than the size requested.

### ISSUE THREAD

**Issue by rsreeni** [kubernetes-client/java#541]
I am trying to ascertain if there are log files for pods with sizes > 10Mb and reporting on them. When I do readNamespacedPodLog with a limitBytes of 10MB, I get size way less than that sometimes as much as half of that. I understand that the readNamespacedPodLog may return a little < or > the specified limitBytes, but can it be that much of a difference ?

I am using kubernetes-client jar 3.0.0.. I also tried switching to 4.0.0.

I am calling as below:

```
apiInstance.readNamespacedPodLog(podName,namespace,null,
    false,10485760,"false",null,null,false)
```
For example, on a pod that I know has a log file > 11 Mb I consistently get about 6MB being returned.

If I switch to 5Mb, then it exactly returns 5Mb when the file has > 5Mb.

Is this how it should behave? Should I limit to 5 and do a continuous couple of 5 Mb reads to ascertain if the file has 10 Mb?

**Comment by brendandburns** [comment]
Do you get the full 11 Mb if you use `kubectl logs ...`?

--brendan

**Comment by rsreeni** [comment]
After you mentioned it , I tried. Yes. Even kubectl logs on this Pod is giving me only 6 MB. Is there an internal size limit for the retrieval ?
Thanks,

-Sreeni

**Comment by rsreeni** [comment]
Brendan,

There are other pod logs in the same namespace, which my code is reading 10MB fine and reports with no issues. Will there be something with that Pod ? Do I have to look with that context ?

Thanks,

-Sreeni

**Comment by brendandburns** [comment]
It's possible... kubelet relies on CRI to pull logs. There may be some problem/bug somewhere in there.

I'd log onto the machine where the kubelet is running and look at kubelet logs.

I'm going to close this issue since it seems to be a Kubernetes issue rather than a java client issue.

**Comment by rsreeni** [comment]
Im going to restart that single pod manually and see if it happens due to something with that app. 

Thanks a lot for your help, Brendan!!

-Sreeni
