### ISSUE TITLE
Deserialization of custom resources fails due to timestamps in metadata when calling listNamespacedCustomObject

### ISSUE THREAD

**Issue by nutthaus** [kubernetes-client/java#553]
Hello, I'm trying to deserialize a list of custom resources using the listNamespacedCustomObject API. But GSON is throwing an error when trying to parse the creationTimestamp in the metadata. I believe this is because it is defined as a Joda DateTime Object in the V1ObjectMeta API, but in the JSON response from the list call it's a plain old string.

This is using the 4.0.0 Java client and GSON 2.3.

The JSON response:

{\"apiVersion\":\"k8s.test.com/v1\",\"items\":[{\"apiVersion\":\"k8s.test.com/v1\",\"kind\":\"TestObject\",\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"k8s.test.com/v1\\\",\\\"kind\\\":\\\"T\
estObject\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"test1\\\",\\\"namespace\\\":\\\"default\\\"},\\\"spec\\\":{\\\"name\\\":\\\"test1\\\"}}\\n\"},\"creationTimestamp\":\"2019-04-11T15:11:17Z\",\"generation\":1,\"name\":\"test1\",\"namespace\":\
\"default\",\"resourceVersion\":\"54201\",\"selfLink\":\"/apis/k8s.test.com/v1/namespaces/default/testobjects/test1\",\"uid\":\"0e38f92e-5c6c-11e9-bfba-0800273d8128\"},\"spec\":{\"name\":\"test1\"}}],\"kind\":\"TestObjectList\",\"metadata\":{\"continue\":\"\",\"r\
esourceVersion\":\"54210\",\"selfLink\":\"/apis/k8s.test.com/v1/namespaces/default/testobjects\"}}

The error from GSON:

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 367 path $.items[0].metadata.creationTimestamp

Any advice? Thanks in advance!

**Comment by brendandburns** [comment]
What is the definition of the object that you are deserializing into?  We had a bug like this elsewhere:

https://github.com/kubernetes-client/java/pull/500/files

But it's fixed in 4.0.0

**Comment by nutthaus** [comment]
In this case I was trying to deserialize into the following object, using the V1ObjectMeta from the library:

public class TestObjectResource {

    private String apiVersion = "k8s.test.com/v1";
    private String kind = "TestObject";
    private V1ObjectMeta metadata;

    private TestObject spec;
    private TestObject status;

    public TestObjectResource() {}

    public String getApiVersion() {
        return apiVersion;
    }

    public void setApiVersion(String _apiVersion) {
        this.apiVersion = _apiVersion;
    }

    public V1ObjectMeta getMetadata() {
        return metadata;
    }

    public void setMetadata(V1ObjectMeta _metadata) {
        this.metadata = _metadata;
    }

    public String getKind() {
        return kind;
    }

    public void setKind(String _kind) {
        this.kind = _kind;
    }

    public String getPlural() {
        return "testobjects";
    }

    public TestObject getSpec() {
        return spec;
    }

    public void setSpec(TestObject _spec) {
        this.spec = _spec;
    }

    public TestObject getStatus() {
        return status;
    }

    public void setStatus(TestObject _status) {
        this.status = _status;
    }
}

**Comment by brendandburns** [comment]
Where are you getting the GSON object from? Are you creating it yourself?

**Comment by brendandburns** [comment]
Closing this due to no response. Please re-open if you need further assistance.

**Comment by vharsh** [comment]
I'm now facing the same bug thing right now and I'm on `Gson 2.8`, will share how I fixed this. I'll probably be using [gson-fire](https://github.com/julman99/gson-fire) :roll_eyes:
