### ISSUE TITLE
Kubernetes Exec PSQL Query Not Working

### ISSUE THREAD

**Issue by AniketBhadane** [kubernetes-client/java#557]
I'm using io.Kubernetes library in Java. I want to execute a psql command on a container with postgres.

Following does not work:

```
String command2 = "psql --dbname=postgresql://postgres:password@127.0.0.1:1234/db123 -c 'ALTER TABLE audit ALTER COLUMN event TYPE character varying(3000);'";

String command[]  = new String[] { "bash", "-c", command2 };
Exec exec = new Exec();
Process exec2 = exec.exec(namespace, podName, command, dbContainerName, stdIn, stdOut);
Thread.sleep(10000);
exec2.destroy();
```

In the inputstream, I'm getting following error:

> bash: -c: line 0: unexpected EOF while looking for matching `''

Whereas a Select query works:

`String command2 = "psql --dbname=postgresql://postgres:password@127.0.0.1:1234/db123 -c 'SELECT * FROM audit'";`

When I use the same sql query with kubernetes command line, it works:
`
kubectl exec -it pod -c container -- bash -c "psql --dbname=postgresql://postgres:password@127.0.0.1:1234/db123 -c 'ALTER TABLE audit ALTER COLUMN event TYPE character varying(3000);'"
`

Then why is the Exec through java library not working?

**Comment by brendandburns** [comment]
I don't think you need the extra quote marks around `command2`

**Comment by AniketBhadane** [comment]
> I don't think you need the extra quote marks around `command2`

When I remove the single quotes around Alter queries, I get following in the inputstream:

```
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `psql --postgresql://postgres:password@127.0.0.1:1234/db123 -c ALTER TABLE audit ALTER COLUMN event TYPE character varying(3000)'
```

**Comment by brendandburns** [comment]
I don't know this looks like more of a SQL query issue rather than Java Kubernetes client issue. It seems that exec is working properly, but you need to figure out how to properly escape the command for bash.

I'm going to close this since I don't think there's much the client library can do here.
