### ISSUE TITLE
Regular Proxy support 

### ISSUE THREAD

**Issue by karanb192** [kubernetes-client/java#561]
I want to support K8s api support via a http(s) proxy. Currently it's missing from the project. 

For example a user can set up a squid proxy server running on port 3128. Now he/she should be able to specify that proxy and use this sdk to access the K8s APIs.

**Comment by karanb192** [comment]
What say @brendandburns ?

**Comment by yue9944882** [comment]
hi @karanb192, i see okhttp3 library already has [support for https(s) proxy](https://square.github.io/okhttp/2.x/okhttp/com/squareup/okhttp/OkHttpClient.html#setProxy-java.net.Proxy-). you can override the httpClient object by calling `setHttpClient`.

**Comment by brendandburns** [comment]
Closing this since there's an ability to do this via overriding the HTTP client.

**Comment by anders-swanson** [comment]
Note that while you can supply your own http client with proxy, doing so overrides the kubernetes java http client's truststore, which includes the CA certificate for your kubernetes cluster. So if you are overriding the proxy, make sure you also recreate the truststore for your cluster's CA.

This would be great for the client to support out of the box, without having to bundle the cluster truststore code when setting up a proxy endpoint.
