### ISSUE TITLE
patchNamespacedDeploymentScaleAsync failed with 400 Bad Request

### ISSUE THREAD

**Issue by yiyijin** [kubernetes-client/java#566]
I am trying to patch the deployment scale, and my code looks like:

```java
V1Scale scale = new V1ScaleBuilder()
      .withSpec(new V1ScaleSpec().replicas(replicas))
      .build();

    appsV1Api.patchNamespacedDeploymentScaleAsync(
      deploymentName,
      namespace,
      scale,
      null,
      null,
      callback
    );
```

and in the callback I got:
```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"json: cannot unmarshal object into Go value of type jsonpatch.Patch","reason":"BadRequest","code":400}
```

**Comment by yue9944882** [comment]
plz use `replaceNamespacedDeploymentScaleAsync` instead. we don't pass resource object to patch calls.

**Comment by yiyijin** [comment]
@yue9944882 
Thanks for the reply, so just wonder in what circumstances should patch call be used?

**Comment by yiyijin** [comment]
@yue9944882 
Besides, what do you mean by: we don't pass resource object to patch calls, I did see in ApiClient.java buildRequest method, it is passing the body for patch calls.

Can you please explain more details please?

**Comment by yiyijin** [comment]
@yue9944882  thanks, I think I understand your point, this is going to be a json patch, which takes an array of patches. After changing the body to that, it works fine with patch now.
