### ISSUE TITLE
Propose release 0.1.0

### ISSUE THREAD

**Issue by lwander** [kubernetes-client/java#57]
@mbohlool @brendandburns 

I'm thinking not jumping to 1.0.0 directly gives us more leeway in applying early fixes.

**Comment by mbohlool** [comment]
In Python we started with 1.0.0a1. According to semver there is no difference between 0.1.0 and 1.0.0a1. But I am fine either way.

**Comment by brendandburns** [comment]
0.1.0 is fine by me.

**Comment by lwander** [comment]
I'll push this through once we've closed https://github.com/kubernetes-client/java/issues/58 - @brendandburns given that the fix was merged into swagger-codegen is there a way to regenerate the clients using the codegen from HEAD? I don't think the change has been released yet (it's targeting 2.3.0).

**Comment by brendandburns** [comment]
If you checkout and build swagger codegen yourself then you can regenerate the client (or I can do it if you rather) it is semi involved :)

--brendan

________________________________

**Comment by lwander** [comment]
Thanks, I figured it out. There was a change in the client here: https://github.com/swagger-api/swagger-codegen/pull/5955/files that breaks compilation that was introduced before my fix was merged. I'll have to get that resolved before creating a new client.
