### ISSUE TITLE
io.sundr:sundr-codegen conflicts with commons-lang3 and more

### ISSUE THREAD

**Issue by markusheiden** [kubernetes-client/java#570]
`io.sundr:sundr-codegen:jar:0.9.2` contains a copy of `commons-lang` etc. in the original package `org.apache.commons.*`. This hides my more recent dependency of `commons-lang` with some new methods which I cannot access now.

Anyway it is no good idea to include foreign packages. Maybe the package translation is broken? Maybe the io.sundr:builder-annotations simply needs to be updated?

Dependency tree: io.kubernetes:client-java-api:jar:4.0.0 has as dependency io.sundr:builder-annotations:jar:0.9.2 which depends on io.sundr:sundr-codegen:jar:0.9.2.

**Comment by brendandburns** [comment]
cc @iocanel can you take a look at this?

**Comment by iocanel** [comment]
This shouldn't be in issue with recent versions of sundrio as the dependency is shaded. 

The project now uses Sundrio 0.18.0 so I think we can close this one.

**Comment by brendandburns** [comment]
closing per comment from iocanel. We'll cut a 5.0.0 with this new dependency really soon.

**Comment by frrivero** [comment]
Hi, adding io.kubernetes:java-client:10.0.0 dependency is including sundr-cogeden:commons-lang:2.4 and is overwriting my StringUtils class, which is causing some methods to disappear, I have a direct dependency on commons-lang:2.6 and still gets overwritten.
kube-client:10.0.0
