### ISSUE TITLE
How PodLogs.streamNamespacedPodLog works

### ISSUE THREAD

**Issue by JasonCL2015** [kubernetes-client/java#571]
Hi Brendan,
    I want to collect podlogs, my code like below
```
V1Pod pod = api.readNamespacedPod("xxx-6d7758ddb7-qnrh4", "oo", null, null, null);
InputStream is = logs.streamNamespacedPodLog(pod);
ByteStreams.copy(is, System.out);
```
 but my console can't print any logs, please tell me how can i get it, thank u.

--> GET https://xxxxxx:8443/api/v1/namespaces/oo/pods/xxx-6d7758ddb7-qnrh4/log?container=kia&follow=true&pretty=false&previous=false&timestamps=false HTTP/1.1
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLWI2aDV2Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmZWVmYjQ1Mi02OTg3LTExZTktYTJmMS1mYTczOTRlZmZmMDAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YWRtaW4tdXNlciJ9.MiNuKg3sWrjZPLvPqa9Q3gQkkXiRXgLELELbc1PAE4nvTuoankBz5ptmSzO7Iy0o5NDp8-DcSbylmqOxMhXxt_h0YtqMn0xw7kpk_l52h2jjMrfDUgcHNrhWS22B4yeK9Tpc2GvcSPpLJ4Ai41mQ2iFtBaG03UGgecgvoujiWNpWPGMewgct5Zzh5I54dyneSBtH7o_2L0vIK6NbpaUTr98_z8f4kY_IAMV2IYT6-Jb75h_TV4WkAkFvFWSYqOXyukZMWFguZdI6-Qc92yGYQoqg-MVgns6w7yH3ZnnPLOf6B21sIm5y6mfv72W5P7s5_oVR933vVAP96cII7jYY6g
Accept: application/json
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
--> END GET
<-- HTTP/1.1 200 OK (23ms)
Content-Type: text/plain
Date: Thu, 23 May 2019 09:16:16 GMT
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1558602976683
OkHttp-Received-Millis: 1558602976707
@brendandburns

**Comment by JasonCL2015** [comment]
client-java version:4.0.0
kubernets version:1.13

**Comment by JasonCL2015** [comment]
i set follow as ture in method readNamespacedPodLog, so i hope i could get podlogs as io stream that i can push sokcet message to front-end web.
is my idea right?

**Comment by JasonCL2015** [comment]
hello?

**Comment by brendandburns** [comment]
I don't think your pods are logging anything. Does `kubectl logs <pod-name>` print anything?

**Comment by JasonCL2015** [comment]
> I don't think your pods are logging anything. Does `kubectl logs <pod-name>` print anything?

kubectl logs <pod-name> -n <namespace> can print logs,  does  [LogsExample](https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/LogsExample.java) work fine? when i use it,it can't print anything.

**Comment by brendandburns** [comment]
It worked the last time I tested it.... I will try to validate it again.

**Comment by dj13may91** [comment]
Hi @JasonCL2015  @brendanburns 
Can you post a code which works ? i am trying the same thing. Setting follow= true  returns string which still is not a stream.

I am trying below approach but its just a hack to get last 1 second logs and push them to my web socket

`while (flag) {
        try {
          logLine = client.getApi().readNamespacedPodLog(pod.getPodName(), pod.getNamespace(), null, null,null, null, null, 1, null, true);  // 1 = sinceSeconds parameter
        } catch (ApiException e) {
          e.printStackTrace();
        }
        if (StringUtils.isNotBlank(logLine)) {
          this.template.convertAndSend(topic, logLine);
        }
        try {
          Thread.sleep(950);
        } catch (InterruptedException e) {
          e.printStackTrace();
        }`

But this does not give correct logs with 100 %  accuracy

**Comment by dj13may91** [comment]
> Hi @JasonCL2015 @brendanburns
> Can you post a code which works ? i am trying the same thing. Setting follow= true returns string which still is not a stream.
> 
> I am trying below approach but its just a hack to get last 1 second logs and push them to my web socket
> 
> `while (flag) { try { logLine = client.getApi().readNamespacedPodLog(pod.getPodName(), pod.getNamespace(), null, null,null, null, null, 1, null, true); // 1 = sinceSeconds parameter } catch (ApiException e) { e.printStackTrace(); } if (StringUtils.isNotBlank(logLine)) { this.template.convertAndSend(topic, logLine); } try { Thread.sleep(950); } catch (InterruptedException e) { e.printStackTrace(); }`
> 
> But this does not give correct logs with 100 % accuracy



> It worked the last time I tested it.... I will try to validate it again.

@brendandburns can you please help me out over the same ?

**Comment by mattshma** [comment]
I meet the same problem, the code likes this:
```
PodLogs logs = new PodLogs();
InputStream in = null;
try {
    in = logs.streamNamespacedPodLog(pod);
    ByteStreams.copy(in, System.out);
} catch (Exception e) {
    log.info("get stream log error: {}", e.getMessage());
    e.printStackTrace();
} finally {
    if (in != null) {
        in.close();
    }
}
```
I get the result as follows:
```
--> GET https://api_server/api/v1/namespaces/pro-gps/pods/test-h2q2m/log?container=test-job&follow=true&pretty=false&previous=false&timestamps=false HTTP/1.1
Accept: application/json
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
--> END GET
<-- HTTP/1.1 200 OK (19ms)
Audit-Id: d493144d-ede4-404e-93b6-d241763aaaee
Content-Type: text/plain
Date: Tue, 25 Feb 2020 09:25:28 GMT
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1582622728048
OkHttp-Received-Millis: 1582622728067
```
It's print nothing, but if I run the command `curl -X GET "https://api_server/api/v1/namespaces/pro-gps/pods/test-h2q2m/log?container=test-job&follow=true&pretty=false&previous=false&timestamps=false " --header "BEAR TOKEN" --seucre` I could get the output.

Kubernetes version: 1.13
Kubernetes-client version: 5.0.0

**Comment by A-Zee029** [comment]
> I meet the same problem, the code likes this:
> 
> ```
> PodLogs logs = new PodLogs();
> InputStream in = null;
> try {
>     in = logs.streamNamespacedPodLog(pod);
>     ByteStreams.copy(in, System.out);
> } catch (Exception e) {
>     log.info("get stream log error: {}", e.getMessage());
>     e.printStackTrace();
> } finally {
>     if (in != null) {
>         in.close();
>     }
> }
> ```
> 
> I get the result as follows:
> 
> ```
> --> GET https://api_server/api/v1/namespaces/pro-gps/pods/test-h2q2m/log?container=test-job&follow=true&pretty=false&previous=false&timestamps=false HTTP/1.1
> Accept: application/json
> User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
> --> END GET
> <-- HTTP/1.1 200 OK (19ms)
> Audit-Id: d493144d-ede4-404e-93b6-d241763aaaee
> Content-Type: text/plain
> Date: Tue, 25 Feb 2020 09:25:28 GMT
> Transfer-Encoding: chunked
> OkHttp-Sent-Millis: 1582622728048
> OkHttp-Received-Millis: 1582622728067
> ```
> 
> It's print nothing, but if I run the command `curl -X GET "https://api_server/api/v1/namespaces/pro-gps/pods/test-h2q2m/log?container=test-job&follow=true&pretty=false&previous=false&timestamps=false " --header "BEAR TOKEN" --seucre` I could get the output.
> 
> Kubernetes version: 1.13
> Kubernetes-client version: 5.0.0

Hi,do you solve the problem? I get the same problem and have no idea why it happen

**Comment by betonetotbo** [comment]
I was facing a similar problem...

After "exploring" the client sources I found the source of the problem: 
- https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/util/src/main/java/io/kubernetes/client/PodLogs.java#L87

This class `PodLogs` is passing the argument `follow=true`, so while the pod still running the resulting `InputStream` will never reach the end.

So, I using this code to get the logs without the `follow` argument:

```java
String namespace = pod.getMetadata().getNamespace();
String name = pod.getMetadata().getName();
String container = pod.getSpec().getContainers().get(0).getName();
Call call = coreApi.readNamespacedPodLogCall(name, namespace, container, false, null, null, "false", false, null, null, null, null);
Response response = call.execute();

try (InputStream in = response.body().byteStream()) {
    Streams.copy(in, System.out);
}
response.close();
```
