### ISSUE TITLE
run example failed and build client-java failed 

### ISSUE THREAD

**Issue by y-koyamatsu** [kubernetes-client/java#579]
I would like to execute 'example but  it failed "'mvn package install'
i use docker desktop for windows!
・

This is log when I execute "mvn package install"! 
> \.m2\repository\java\examples>mvn package install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building client-java-examples 5.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.sundr:sundr-codegen:jar:0.18.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for io.sundr:sundr-codegen:jar:0.9.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for io.kubernetes:client-java-extended:jar:5.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.844 s
[INFO] Finished at: 2019-05-31T16:50:05+09:00
[INFO] Final Memory: 14M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project client-java-examples: Could not resolve dependencies for project io.kubernetes:client-java-examples:bundle:5.0.0: Failure to find io.kubernetes:client-java-extended:jar:5.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

This is pom.xml under example directory
><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>io.kubernetes</groupId>
	<artifactId>client-java-examples</artifactId>
	<packaging>bundle</packaging>
	<name>client-java-examples</name>
	<url>https://github.com/kubernetes-client/java</url>
	<parent>
		<groupId>io.kubernetes</groupId>
		<artifactId>client-java-parent</artifactId>
		<version>5.0.0</version>
	</parent>
	<dependencies>
		<dependency>
			<groupId>io.kubernetes</groupId>
			<artifactId>client-java-api</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.kubernetes</groupId>
			<artifactId>client-java</artifactId>
			<version>4.0.0</version>
		</dependency>
		<dependency>
			<groupId>io.kubernetes</groupId>
			<artifactId>client-java-extended</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.kubernetes</groupId>
			<artifactId>client-java-proto</artifactId>
			<version>${project.version}</version>
		</dependency>
                <dependency>
                        <groupId>io.sundr</groupId>
                        <artifactId>sundr-maven-plugin</artifactId>
                        <version>0.18.0</version>
                </dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>25.1-jre</version>
		</dependency>
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.github.tomakehurst</groupId>
			<artifactId>wiremock</artifactId>
			<version>2.19.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.8.2</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<archive>
								<manifest>
									<mainClass>io.kubernetes.client.examples.Example</mainClass>
								</manifest>
							</archive>
							<descriptorRefs>
								<descriptorRef>jar-with-dependencies</descriptorRef>
							</descriptorRefs>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.coveo</groupId>
				<artifactId>fmt-maven-plugin</artifactId>
				<version>2.2.0</version>
				<executions>
					<execution>
						<phase>test</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<properties>
		<java.version>1.8</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<swagger-core-version>1.5.12</swagger-core-version>
		<okhttp-version>2.7.5</okhttp-version>
		<gson-version>2.6.2</gson-version>
		<jodatime-version>2.9.3</jodatime-version>
		<maven-plugin-version>1.0.0</maven-plugin-version>
		<junit-version>4.12</junit-version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
</project>

By the way, there are some Error when I execute "mvn install" on  "java" directory!
("java" directory store this project. Some test's result were Error. 
 So build of "client-java" was failed .... I added dependency "client-java" to root pom.xml )
Is that related this issue????

Please help me !!!!

I noticed  that "expected:<http[://localhost:8080]> but was:<http[s://localhost:6445]>" was often occurred!!!!

Here are maven and jdk information.
>mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T04:39:06+09:00)
Maven home: C:\apache-maven-3.5.0\bin\..
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_141\jre
Default locale: ja_JP, platform encoding: MS932
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by brendandburns** [comment]
You need to run `mvn package install` in the root directory of the repository to install the dependencies before you build the examples.

**Comment by y-koyamatsu** [comment]
>You need to run mvn package install in the root directory of the repository to install the dependencies before you build the examples.

I got it!

But I failed test when I  run `mvn package install` in the root directory to run example!!!
