### ISSUE TITLE
What is the body arg in patchNamespacedHorizontalPodAutoscaler?

### ISSUE THREAD

**Issue by ChrisMullard** [kubernetes-client/java#585]
The documentation+example code appears to have an omission:

https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AutoscalingV1Api.md#patchNamespacedHorizontalPodAutoscaler

null is passed in the example for the body arg.

Omitting it isn't possible as the following exception is returned:

> io.kubernetes.client.ApiException: Missing the required parameter 'body' when calling patchNamespacedHorizontalPodAutoscaler(Async)

Thanks

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java

the patch example is here. but i think the example is indeed problematic, the patch body shouldn't be simply a `java.lang.Object`, which is misleading.

**Comment by brendandburns** [comment]
That documentation is auto-generated from Swagger, so it's rough suggestions at best.

Following the example in the PatchExample is a better approach.

I'm closing this since I think there's not much more we can do here. Please re-open if you need additional assistance.

**Comment by ChrisMullard** [comment]
Using the AutoscalingV1Api and patchNamespacedHorizontalPodAutoscaler() with patch string
"{\"op\":\"replace\",\"path\":\"/spec/minReplicas\",\"value\":0}"
I get 
io.kubernetes.client.ApiException: Unprocessable Entity
...what am I doing wrong pls?
