### ISSUE TITLE
I can't run YamlExample.java!

### ISSUE THREAD

**Issue by y-koyamatsu** [kubernetes-client/java#588]
When I run  YamlExample.java , I failed it!
Exception in thread "main" java.lang.Error: Unresolved compilation problems V1PodBuilder and V1ServiceBuilder:
Do I need to implement them by own?

And......
When I run  AttachExample.java , I failed it too!
"java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'" occur!!!
Please advise me to resolve some problems....

In fact, I run mvn package install in the root directory of the repository to install the dependencies before I build the examples.

**Comment by brendandburns** [comment]
I'll try to reproduce the first error.

I think that the second error is because you need to change the name of the pod in the example to a pod that is actually running in your cluster.

**Comment by seongwon-kang** [comment]
I don't know why, `mvn package; mvn fmt:format; mvn package` will solve that.
In my case it was occured when I imported project with improper way on eclipse.
