### ISSUE TITLE
Most Deployment values are null once there are no replicas

### ISSUE THREAD

**Issue by ChrisMullard** [kubernetes-client/java#589]
Once I patch a Deployment replica value to 0 and the available replica count goes to 0 (from kubectl), a call to readNamespacedDeployment returns null for most fields (see attached file).

Is this by design? Surely the fields should have a value (such as availableReplicas, replicas both = 0)
kubectl returns values:

H:\>kubectl get deployments --namespace xxx
NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
backoffice   0         0         0            0           31d
batchproc    0         0         0            0           31d
vanilla      0         0         0            0           31d

[patchedDeployment.log](https://github.com/kubernetes-client/java/files/3264313/patchedDeployment.log)

**Comment by brendandburns** [comment]
What did you use to perform the patch? Did you issue a `PATCH` or was it a `PUT`, because if you called `replace` with a patch-like `Deployment` object, the output above is about what I would expect.

**Comment by ChrisMullard** [comment]
It was a patch using "{\"op\":\"replace\",\"path\":\"/spec/replicas\",\"value\":0}";

...why would that leave fields null when the are subsequently retrieved?

**Comment by yue9944882** [comment]
the `replicas` fields are tagged as `omitempty` which makes them omitted on serialization if they're zero-valued.. (i'm not sure it's by-design or not.. 🤔)

**Comment by ChrisMullard** [comment]
Ok thanks

**Comment by yue9944882** [comment]
@ChrisMullard what's your kubernetes cluster version?

**Comment by ChrisMullard** [comment]
1.12 in AWS under EKS
