### ISSUE TITLE
Some files are missing from maven-deployed sources

### ISSUE THREAD

**Issue by victornoel** [kubernetes-client/java#596]
Hi,

There seems to some missing files in the deployed sources to maven.

For example `io.kubernetes.client.ApiException` is provided by `client-java-5.0.0.jar` but is missing from `client-java-5.0.0-sources.jar`.

I don't know if there are others.

**Comment by yue9944882** [comment]
@victornoel `ApiException` lives in `client-java-api` instead of `client-java`

**Comment by victornoel** [comment]
@yue9944882 then there is a problem with the deployed maven artifacts: `io.kubernetes.client.ApiException` is present in `client-java-5.0.0.jar` also, so in Eclipse, m2e tries to look for its source in `client-java-5.0.0-sources.jar`.

```
➜  ~ unzip -l ~/.m2/repository/io/kubernetes/client-java/5.0.0/client-java-5.0.0.jar | grep ApiException
     3182  2019-05-31 04:49   io/kubernetes/client/ApiException.class
➜  ~ unzip -l ~/.m2/repository/io/kubernetes/client-java-api/5.0.0/client-java-api-5.0.0.jar | grep ApiException 
     3182  2019-05-31 04:49   io/kubernetes/client/ApiException.class

```

**Comment by yue9944882** [comment]
i suppose it's caused by maven bundle packaging plugins.. i'm not really familiar w/ how OSGi packaging works but i sent #597 to strip the duplicated class. it's working fine locally.

**Comment by victornoel** [comment]
@yue9944882 nice, thx!
