### ISSUE TITLE
Launch a defined CronJob?

### ISSUE THREAD

**Issue by seanleblanc** [kubernetes-client/java#598]
I'm just curious if it would be possible to use this client API to launch a command similar to the one described here. Basically, start with a CronJob and launch it right now.

https://stackoverflow.com/questions/40401795/how-can-i-trigger-a-kubernetes-scheduled-job-manually

kubectl create job --from=cronjob/<cronjob-name> <job-name>

**Comment by brendandburns** [comment]
Yes, you can definitely use this API to achieve that.

Here's an example that parses an object from JSON:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ParseExample.java

You just need to then call into the right API to create the CronJob object.

**Comment by seanleblanc** [comment]
So, does that copy an existing, predefined CronJob that would be in the cluster, and then create a one-time Job based on that CronJob spec? That example seems to take a json file as input as well as the target type of spec and then create the correct job for use. 

I'm assuming I might combine this idea with additional steps, such as getting the json for the CronJob from the cluster, putting in an object, and then manipulating it into a one-time job, then calling an api with that object to run the one-time job?

**Comment by The-Kruegz** [comment]
Here because I am also looking to create a job from a cronjob. 
@brendandburns I don't see how your example given applies our question.

**Comment by The-Kruegz** [comment]
@seanleblanc I figured this out if you are interested. This method replicates the functionality of:
kubectl delete job --ignore-not-found =true 
&& kubectle create job --from=conjob/

`public void triggerJobFromCronJob (String env, String namespace, String jobName)
      throws ApiException {
    V1DeleteOptions options = new V1DeleteOptions();
    try {
      V1Status deleteResult = batchV1Api.deleteNamespacedJob(jobName + "-triggered-job", namespace, options, null, 0, null, null);
    }
    catch (ApiException e) {
      if (!e.getMessage().equals("Not Found")) {
        throw e;
      }
    }
    V1beta1CronJob cronJob = batchV1beta1Api.readNamespacedCronJob(jobName + "-cronjob", namespace, null, null, null);

    V1Job triggeredJob = new V1Job();
    triggeredJob.setKind("Job");
    triggeredJob.setApiVersion("batch/v1");

    // fill metadata
    V1ObjectMeta jobMetadata = new V1ObjectMeta();
    jobMetadata.setName(jobName + "-triggered-job");
    LinkedTreeMap<String, String> labels = new LinkedTreeMap<String, String>();
    labels.put("name", jobName + "-triggered-job");
    jobMetadata.setLabels(labels);
    jobMetadata.setNamespace(namespace);

    // copy cronjob's job spec to new triggered job
    V1JobSpec jobSpec = new V1JobSpec();
    jobSpec.setTemplate(cronJob.getSpec().getJobTemplate().getSpec().getTemplate());
    triggeredJob.setSpec(jobSpec);

    batchV1Api.createNamespacedJob(namespace, triggeredJob, null);

  }`
