### ISSUE TITLE
can I use " kubectl rollout history deployment <deployment> " with java API ?

### ISSUE THREAD

**Issue by wushuaiwangyin** [kubernetes-client/java#599]
the commond " kubectl rollout history deployment " can I use API to operate it?

**Comment by yue9944882** [comment]
[https://github.com/kubernetes-client/java/blob/dc82549dde1eeea7593203dec788af0fe33685a7/kubernetes/src/main/java/io/kubernetes/client/models/AppsV1beta1DeploymentSpec.java#L51-L52](https://github.com/kubernetes-client/java/blob/dc82549dde1eeea7593203dec788af0fe33685a7/kubernetes/src/main/java/io/kubernetes/client/models/AppsV1beta1DeploymentSpec.java#L51-L52)

just performing an update the deployment's will work

**Comment by brendandburns** [comment]
fwiw, that's a relatively new API, a lot of the information that command uses is stored in annotations in earlier kubernetes versions...

**Comment by zhamdoctor** [comment]
> https://github.com/kubernetes-client/java/blob/dc82549dde1eeea7593203dec788af0fe33685a7/kubernetes/src/main/java/io/kubernetes/client/models/AppsV1beta1DeploymentSpec.java#L51-L52
> 
> just performing an update the deployment's will work

this is like `kubectl rollout undo`,what about querying history revision like `kubectl rollout history,kubectl rollout status` and some  keywords like `revision`,not update,just query history for revision
