### ISSUE TITLE
io.kubernetes.client.util package question

### ISSUE THREAD

**Issue by chlung** [kubernetes-client/java#60]
Hi,

I try to find out if kubernetes-client java api plans to include the `io.kubernetes.client.util` package in the released jar file.  We would like to use some of java code.

Thanks.

**Comment by lwander** [comment]
Yes, that was the purpose of this change: https://github.com/kubernetes-client/java/commit/fc5347267280f3587932a0b2debf84cfc715e4a4

**Comment by chlung** [comment]
@lwander thanks.
