### ISSUE TITLE
Examples don't contain strategic merge patch and JSON merge patch

### ISSUE THREAD

**Issue by mpashka** [kubernetes-client/java#600]
Kubernetes java client has API to apply patch for some object. But that implies using json patch (Content-Type: application/json-patch+json).
There is no example of using other types. Can you please add support for other patch types and add appropriate examples.

As a workaround I used the following code to apply merge patch for node in java client:
```
            List<Pair> queryParams = new ArrayList<>();
            List<Pair> collectionQueryParams = new ArrayList<>();
            Map<String, String> headerParams = new HashMap<>();
            Map<String, Object> formParams = new HashMap<>();
            headerParams.put("Accept", "application/json");
            headerParams.put("Content-Type", "application/merge-patch+json");
            String[] authNames = new String[]{"BearerToken"};

            String patch = "{\"metadata\": {\"annotations\": {\"" + annotation + "\": \"" + value + "\"}}}";
            Call patchNodeCall = client.buildCall("/api/v1/nodes/" + nodeName, "PATCH", queryParams,
                    collectionQueryParams, patch.getBytes(), headerParams, formParams, authNames, null);
            ResponseBody body = patchNodeCall.execute().body();
            response = body.string();
            JSON json = new JSON();
            V1Node node = json.deserialize(response, new TypeToken<V1Node>() {}.getType());
            body.close();
```

**Comment by yue9944882** [comment]
now patch supports other formats, but the example is on master, haven't released yet 

https://github.com/kubernetes-client/java/blob/dc82549dde1eeea7593203dec788af0fe33685a7/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java#L64-L89

**Comment by theAkito** [comment]
That's an extremely tiny and not very helpful example. Is there documentation on how to properly use strategic merge patches? The documentation on this operation is almost non-existent. Trying to figure out how to make this work as intended, for hours.
