### ISSUE TITLE
CustomObjectsApi misses getAPIResources

### ISSUE THREAD

**Issue by rtwruck** [kubernetes-client/java#604]
CustomObjectsApi can list custom objects if you know their plural name but does not expose a method to get the possible names, i.e. GET /apis/{group}/{version}/.

**Comment by brendandburns** [comment]
It's here:

https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/ApiregistrationV1Api.md#getAPIResources

**Comment by rtwruck** [comment]
No, it's not.
That one does GET /apis/apiregistration.k8s.io/v1/ and the response usually contains two entries: apiservices and apiservices/status.

**Comment by JacobHenner** [comment]
I've opened a PR that would address this omission upon OpenAPI client regeneration: https://github.com/kubernetes-client/gen/pull/232
