### ISSUE TITLE
Consider making library smaller and more modular

### ISSUE THREAD

**Issue by remmeier** [kubernetes-client/java#605]
we intended to make use of the library in a set of micro services. I general it works great. But unfortuntately, the foot print of the library is a bit problematic. 

On the one side it has many dependencies:

```
 +--- io.kubernetes:client-java:3.0.0
|    |    +--- io.kubernetes:client-java-api:3.0.0
|    |    |    +--- io.sundr:builder-annotations:0.9.2
|    |    |    |    +--- io.sundr:sundr-core:0.9.2
|    |    |    |    +--- io.sundr:sundr-codegen:0.9.2
|    |    |    |    +--- io.sundr:resourcecify-annotations:0.9.2
|    |    |    |    \--- javax.validation:validation-api:1.1.0.Final -> 2.0.1.Final
|    |    |    +--- io.swagger:swagger-annotations:1.5.12
|    |    |    +--- com.squareup.okhttp:okhttp:2.7.5
|    |    |    |    \--- com.squareup.okio:okio:1.6.0
|    |    |    |         \--- org.codehaus.mojo:animal-sniffer-annotations:1.10 -> 1.17
|    |    |    +--- com.squareup.okhttp:logging-interceptor:2.7.5
|    |    |    |    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    |    |    +--- com.google.code.gson:gson:2.6.2 -> 2.8.5
|    |    |    +--- joda-time:joda-time:2.9.3 -> 2.10.1 (*)
|    |    |    +--- org.joda:joda-convert:1.2
|    |    |    \--- org.apache.commons:commons-lang3:3.7 -> 3.8.1
|    |    +--- io.kubernetes:client-java-proto:3.0.0
|    |    |    \--- com.google.protobuf:protobuf-java:3.4.0
|    |    +--- org.yaml:snakeyaml:1.19 -> 1.23
|    |    +--- commons-codec:commons-codec:1.11
|    |    +--- org.apache.commons:commons-compress:1.18
|    |    +--- org.apache.commons:commons-lang3:3.7 -> 3.8.1
|    |    +--- com.squareup.okhttp:okhttp-ws:2.7.5
|    |    |    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    |    +--- com.google.guava:guava:25.1-jre -> 27.0-jre (*)
|    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.bouncycastle:bcprov-ext-jdk15on:1.59
|    |    +--- org.bouncycastle:bcpkix-jdk15on:1.59 -> 1.60 (*)
|    |    +--- com.google.protobuf:protobuf-java:3.4.0
|    |    \--- com.microsoft.azure:adal4j:1.6.0
|    |         +--- com.nimbusds:oauth2-oidc-sdk:5.24.1
|    |         |    +--- javax.mail:mail:1.4.7 (*)
|    |         |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|    |         |    +--- org.apache.commons:commons-lang3:3.5 -> 3.8.1
|    |         |    +--- org.apache.commons:commons-collections4:4.1
|    |         |    +--- net.minidev:json-smart:1.3.1
|    |         |    +--- com.nimbusds:lang-tag:[1.4.3,) -> 1.4.4
|    |         |    +--- com.nimbusds:nimbus-jose-jwt:[4.29,) -> 7.3
|    |         |    |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|    |         |    |    +--- net.minidev:json-smart:[1.3.1,2.3] -> 1.3.1
|    |         |    |    +--- org.bouncycastle:bcprov-jdk15on:[1.52,) -> 1.60
|    |         |    |    \--- org.bouncycastle:bcpkix-jdk15on:[1.52,) -> 1.60 (*)
|    |         |    \--- org.slf4j:slf4j-api:[1.7.13,2.0.0) -> 1.7.25
|    |         +--- com.google.code.gson:gson:2.8.0 -> 2.8.5
|    |         +--- org.slf4j:slf4j-api:1.7.21 -> 1.7.25
|    |         \--- commons-codec:commons-codec:1.10 -> 1.11
```

On the other side the project itselfs has JARs up to 9 MB in size. All in all it is around 35 to 40 MB.

Maybe it would be worthwhile to split it up into multiple pieces. By fetching `io.kubernetes:client-java` one would still get the entire thing. But would also have the possiblity to get the parts required for a particular use case. e.g. the Azure Directory services for sure will only affect a subset of the user base.

**Comment by brendandburns** [comment]
I think you can use dependency exclusions:

http://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

To achieve this.

It's possible that if you exclude the Azure library that this libray will crash with `ClassNotFound` in that case, I'm happy to take a PR to add exception catches in the right places...

**Comment by remmeier** [comment]
one can yes. I guess. I wondering if there is any interest to slim down the library in general without "hacking" dependencies. In our case we only need access to secrets, configMaps, pods and deployments from within the cluster, which I suspect is a frequent use case. For such a use case I was hoping more for the 500 KB rather than 40 MB dependency. Or maybe in the lower MB range.

**Comment by brendandburns** [comment]
I don't think there are any plans to slim down the library by reducing the API coverage (e.g. just secrets, pods, etc)

I think we could consider publishing a smaller "http client" style library that handles all of the auth, but doesn't contain all of the object models, then you could do raw JSON or write your own object model if you really wanted to.

Likewise, separating out the individual cloud auth libraries into separate libraries makes sense.

That said, at some level, the point of open source is that if you care enough, you can always hack up the library yourself and reduce it's size to a point that appeals to you. We're going to focus on the 80% use case, not the absolute minimal size use case.  (esp. given that if you're writing Java there's already a 100Mb (at least) JVM involved)

**Comment by remmeier** [comment]
>  given that if you're writing Java there's already a 100Mb (at least)

nowadays with the modularity and stuff that got better as well...

>  open source is that if you care enough, you can always hack up the library
> yourself and reduce it's size to a point that appeals to you.

well not that much to attempt to fork something. And this library is great in any other way. But sufficient enough to attempt/help make it smaller if there is any desire for it :-)

> I think we could consider publishing a smaller "http client" style library that handles all of the auth

could also make sense from a modularity perspective. 

is there any chance of splitting up the proto and api JARs? Because both are now around 9 MB in size. Kubernetes grows and grows. New versions emerge. Version 4 for example grew quite considerably. The next guy may have to open a ticket for 80 MB of dependencies :-) I guess there could be two dimensions two partition the JARs:

- versions (alpha, beta, major ones, etc.)
- seperate core, apps, batch, etc. 

then one can either fetch everything or pick the pieces he actually needs. In our case it is primarly the Core services.
