### ISSUE TITLE
 How to simply create k8s resources by Yaml.loadAs(file)

### ISSUE THREAD

**Issue by chentging** [kubernetes-client/java#611]
@brendandburns @kondapally1989 
I readed issues #254 and #170 .
But I want to create k8s resources via the brower upload yaml file. I actually don't know that the user write which kind and apiVsersion into yaml file, if so, how to create k8s resources via `io.kubernetes.client.util.Yaml.loadAs(file)`
does it support in this library?
Thanks 🙏

**Comment by chentging** [comment]
For example:kubectl create -f xxx.yaml,`kubectl` command actually don't know what resources in yaml file, but it works.

**Comment by yue9944882** [comment]
the go library has a dynamic [de]serializer so it doesn't require the concrete types. and that implementation is some sort of debatable for a period of time.. as a walkaround, consider deserializing w/ a `CustomObject` which basically fits into any types.

**Comment by brendandburns** [comment]
You can do this, the call is:

`Yaml.load(file)` or `Yaml.load(String content)`

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Yaml.java#L171

It returns a generic `Object` that has the right type (assuming it's known)

**Comment by brendandburns** [comment]
Closing this since I think the question is answered.
