### ISSUE TITLE
create namespace  What is the legal value of the parameter in “dryRun”

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#612]
Create namespaces by：
api.createNamespace(v2Namespace,null,"true","-");

throw Exceptions:
io.kubernetes.client.ApiException: Unprocessable Entity

I want to know What is the legal value of the parameter in “dryRun”

**Comment by yue9944882** [comment]
a null will work

/triage support

**Comment by ZP-AlwaysWin** [comment]
Thank you for your reply：
@yue9944882 
I want to other the legal value “dryRun” without "null"
beacause I want to test the parameter "dryRun"

**Comment by yue9944882** [comment]
here's doc for dry-run feature, if that's what you looking for: https://kubernetes.io/docs/reference/using-api/api-concepts/#dry-run

**Comment by ZP-AlwaysWin** [comment]
@yue9944882 
Thank you vey much;
I will carefully read the doc。

**Comment by ZP-AlwaysWin** [comment]
@yue9944882
hi @yue9944882:

I have a question for you。
K8S java client can create resources with same name  multiple times，such as Idempotency，Reentrant。

I test to create a namespace with same name mulitiple times;
throws Exception:

io.kubernetes.client.ApiException: Conflict

**Comment by yue9944882** [comment]
> K8S java client can create resources with same name multiple times

false predicate. a name must be unique for any resource in the kubernetes world.
