### ISSUE TITLE
report bug create deployment

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#615]
I create deployment by kubernetes-client/java

```
......
IntOrString intOrString = new IntOrString(25);
        v1RollingUpdateDeployment.setMaxSurge(intOrString);
        v1RollingUpdateDeployment.setMaxUnavailable(intOrString);
        v1DeploymentStrategy.setRollingUpdate(v1RollingUpdateDeployment);
        v1DeploymentStrategy.setType("RollingUpdate");
        v1DeploymentSpec.setStrategy(v1DeploymentStrategy);
......
```

throw Exception

[org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Not a string; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Not a string (through reference chain: io.kubernetes.client.models.V1Deployment["spec"]->io.kubernetes.client.models.V1DeploymentSpec["strategy"]->io.kubernetes.client.models.V1DeploymentStrategy["rollingUpdate"]->io.kubernetes.client.models.V1RollingUpdateDeployment["maxSurge"]->io.kubernetes.client.custom.IntOrString["strValue"])]

**Comment by yue9944882** [comment]
are you using the provided gson to do the serialization?

**Comment by brendandburns** [comment]
`IntOrString` is registered with `GSON` as a serialization provider. If you supply your own serializer, you'll need to make sure it gets registered with that one too.

See the code here:
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java#L12

Closing this, re-open if you need more info.

**Comment by Sairav** [comment]
@brendandburns Could you please help me understand how to "register" it.

I have used IntOrString while building a NetworkPolicy, runs fine in actual run , network policy is created successfully , but when running a test causes following exception ->

`com.fasterxml.jackson.databind.JsonMappingException: Not a string (through reference chain: io.kubernetes.client.openapi.models.V1NetworkPolicy["spec"]->io.kubernetes.client.openapi.models.V1NetworkPolicySpec["egress"]->java.util.ArrayList[0]->io.kubernetes.client.openapi.models.V1NetworkPolicyEgressRule["ports"]->java.util.ArrayList[0]->io.kubernetes.client.openapi.models.V1NetworkPolicyPort["port"]->io.kubernetes.client.custom.IntOrString["strValue"])`

Above error comes with policy built like ->

```
return new V1NetworkPolicy()
            .apiVersion("networking.k8s.io/v1")
            .metadata(new V1ObjectMeta().name("cp-job-egress-to-dns"))
            .spec(new V1NetworkPolicySpec().addPolicyTypesItem("Egress")
                        .podSelector(new V1LabelSelector().matchLabels(ImmutableMap.of("job-name",jobName)))
                    .addEgressItem(new V1NetworkPolicyEgressRule()
                    .addToItem(new V1NetworkPolicyPeer().ipBlock(new V1IPBlock().cidr(K8S_POD_CIDR_RANGE)))
                    .addPortsItem(new V1NetworkPolicyPort().protocol("TCP").port(new IntOrString(53)))
                    .addPortsItem(new V1NetworkPolicyPort().protocol("UDP").port(new IntOrString(53))))
                );
```

When I provide String value in the port ("53"), it complains with error , not an integer 😅

**Comment by fazai-yeah** [comment]
I have  the same problem, @brendandburns Could you please help me understand how to "register" it.

**Comment by Rapter1990** [comment]
I have a the same issue shown below

`com.fasterxml.jackson.databind.JsonMappingException: Not a string (through reference chain: io.kubernetes.client.openapi.models.V1NetworkPolicy["spec"]->io.kubernetes.client.openapi.models.V1NetworkPolicySpec["egress"]->java.util.ArrayList[0]->io.kubernetes.client.openapi.models.V1NetworkPolicyEgressRule["ports"]->java.util.ArrayList[0]->io.kubernetes.client.openapi.models.V1NetworkPolicyPort["port"]->io.kubernetes.client.custom.IntOrString["strValue"])`

I have to keep the value as `V1DeploymentList` to list all deployments.

How can I implement custom serializer or deserializer for IntOrString and integrate with my ApiClient ?

```
@Configuration
public class KubernetesConfig {

    @Bean
    public ApiClient apiClient() throws Exception {
        return Config.defaultClient();
    }

    @Bean
    public CoreV1Api coreV1Api(ApiClient apiClient) {
        return new CoreV1Api(apiClient);
    }

    @Bean
    public AppsV1Api appsV1Api(ApiClient apiClient) {
        return new AppsV1Api(apiClient);
    }
```
