### ISSUE TITLE
How to create a deployment from a YAML file

### ISSUE THREAD

**Issue by smaillns** [kubernetes-client/java#620]
May you give some examples of can we create Kubernetes objects from YAML files using this API, Thanks.

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/YamlExample.java

load the object from your yaml at first, then fire the request to the apiserver using the client

**Comment by brendandburns** [comment]
Closing this as the question is answered. Please re-open if there are further questions.

**Comment by smaillns** [comment]
> load the object from your yaml at first, then fire the request to the apiserver using the client
Excuse me, but how to load the YAML file ?

**Comment by yue9944882** [comment]
using `Yaml#load` i suppose. see https://github.com/kubernetes-client/java/issues/611#issuecomment-511265984

**Comment by smaillns** [comment]
There are some problems occured while trying to execute the code from a docker container !!

**Comment by smaillns** [comment]
#634
