### ISSUE TITLE
java-client how to Implement this command “kubectl get deployment nginx-deployment -o json”

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#625]
java-client how to Implement this command “kubectl get deployment nginx-deployment -o json”

beasuse ，I want to get the deployment json file

**Comment by yue9944882** [comment]
call `readNamespacedDeployment` and dump it using gson will achieve that

**Comment by ZP-AlwaysWin** [comment]
Thank your help:
V1Deployment v1Deployment = appsV1Api.readNamespacedDeployment("nginx-deployment","default",null,null,null);

how to dump it using gson?
I don't Realization

**Comment by ZP-AlwaysWin** [comment]
CoreV1Api api = new CoreV1Api();
        com.squareup.okhttp.Call call = api.readNamespacedConfigMapCall("xxx","default",null,null,null,null,null);

        Response response = call.execute();

        if(!response.isSuccessful()) {
            return;
        }

        String body = response.body().string();

        JSONObject jsonObject = new JSONObject(body);

        System.out.println(jsonObject);

----
output
```
{
    "metadata":{
        "uid":"1111111",
        "resourceVersion":"1154820",
        "name":"xx",
        "namespace":"default",
        "creationTimestamp":"2019-07-15T02:02:02Z",
        "selfLink":"/api/v1/namespaces/default/configmaps/xx"
    },
    "apiVersion":"v1",
    "kind":"ConfigMap"
}
```

The output style don't standard,It should "apiVersion" is At the top

**Comment by brendandburns** [comment]
order of fields in JSON doesn't matter.

If you want to format it in a specific way, you will need to write the formatter yourself.  Closing this issue since the original question is answered and anything further is outside of the scope of this library.
