### ISSUE TITLE
Get YAML for deployed Kubernetes deployment?

### ISSUE THREAD

**Issue by zhangzerui20** [kubernetes-client/java#630]
Can I get the YAML file of a deployed deployment through the java client? Or is there an HTTP API to do this? I only found out doing this through kubectl.

`kubectl get deploy deploymentname -o yaml --export`

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/YamlExample.java

consider dumping the object in yaml format after getting the deployment using the client

/triage support

**Comment by brendandburns** [comment]
If all you want is the YAML, this library is probably overkill. But the example cited above is the right place if you really do want/need the YAML.

Closing this issue as the question is answered.

**Comment by zhangzerui20** [comment]
> If all you want is the YAML, this library is probably overkill. But the example cited above is the right place if you really do want/need the YAML.
> 
> Closing this issue as the question is answered.


We want to provide users with a web page that allows users to view the deployed YAML of Deployment and Service on the web page. Is there any better way to do this?
