### ISSUE TITLE
Issue when  i create deployment 

### ISSUE THREAD

**Issue by MasterYiLeng** [kubernetes-client/java#632]
When I use the Deployment object of the 4.3.0 client to create a deployment, when I specify cpu and memory for the pod container in the deployment, the api that calls k8s reports a 400 error. Please help me to see it. My code is as follows:
![1563882737(1)](https://user-images.githubusercontent.com/35093485/61710131-719dd180-ad83-11e9-8c12-4af7f11793b9.jpg)
The error message is as follows:
![image](https://user-images.githubusercontent.com/35093485/61710244-bc1f4e00-ad83-11e9-8d0b-506a5dc112d0.png)

**Comment by yue9944882** [comment]
> When I use the Deployment object of the 4.3.0 client to create a deployment, 

what is 4.3.0 client? we don't seem to have that version released?

**Comment by brendandburns** [comment]
The error message in the exception is pretty clear, your quantities don't match the regular expression for quantities as printed in the error message.

Closing this as this is not a problem with the client library.
