### ISSUE TITLE
Listing jobs and remove completed jobs

### ISSUE THREAD

**Issue by jjkoehorst** [kubernetes-client/java#633]
Within the rancher api I can list all the collections (with/without pods) using the following url:

https://somewhere.com/v3/project/c-xzfjm:p-cd9r7/pods/

Which will return the list below. I am trying to figure out which java command to use to obtain the 35 items, check if they are finished according  to their status and clean them up.

```
        V1PodList v1PodList = new V1PodList();
        System.err.println(v1PodList.getItems().size());
```

Returns 0 and the following codes returns 0 as well:

```
        BatchV1Api batchV1Api = new BatchV1Api();
        V1JobList v1JobList = batchV1Api.listNamespacedJob("default", null, null, null, null, null, null, null, null, null);
        System.err.println(v1JobList.getItems().size());
```

```
        v1JobList = batchV1Api.listJobForAllNamespaces(null, null, null, null, null, null, null, null, null);
        System.err.println(v1JobList.getItems().size());
```

I will try to find other ways but so far I am unable to list all the "workloads" as rancher calls it.

```
{
"type": "collection",
"links": {
"self": "…/v3/project/c-xzfjm:p-cd9r7/pods/"
},
"createTypes": {
"pod": "…/v3/project/c-xzfjm:p-cd9r7/pods"
},
"actions": { },
"pagination": {
"limit": 1000,
"total": 35
},
"sort": { … },
"filters": { … },
"resourceType": "pod",
"data": [ 35 items
{
"annotations": {
"cattle.io/timestamp": "2019-07-16T11:24:10Z",
"cni.projectcalico.org/podIP": "10.42.1.30/32"
},
"baseType": "pod",
"containers": [
{
"allowPrivilegeEscalation": false,
"command": [ 13 items
...
```

**Comment by jjkoehorst** [comment]
Ok I noticed that setting the `specs.setTtlSecondsAfterFinished(0);` does not end up in the yaml / api overview of rancher while the `specs.setBackoffLimit(5);` is present. Is this a finished feature as I cannot find anything about `tlSecondsAfterFinished` in the git repository?

**Comment by yue9944882** [comment]
not familiar w/ the rancher api. what version of kubernetes are you using? note that `ttlSecondsAfterFinished` is only supported in a 1.12+ cluster

**Comment by jjkoehorst** [comment]
Need to check that, I am using rancher at the moment as that was the first one that was easy to setup but perhaps there are better solutions... The current versions are, but need to check what the underlying version of kubernetes is.


Component | Version
-- | --
Rancher | v2.2.1
User Interface | v2.2.19
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1

**Comment by adohe** [comment]
have u ever tried to use kubectl to call rancher api? and what is the result?

**Comment by jjkoehorst** [comment]
Have masked a few variables but this is what I get:

`kubectl get jobs myrunner-49lrt -o yaml`

```
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: 2019-07-24T06:52:11Z
  generateName: myrunner-
  labels:
    controller-uid: 8fcb26be-addf-11e9-85af-60a44c4e3841
    job-name: myrunner-49lrt
  name: myrunner-49lrt
  namespace: default
  resourceVersion: "19088568"
  selfLink: /apis/batch/v1/namespaces/default/jobs/myrunner-49lrt
  uid: 8fcb26be-addf-11e9-85af-60a44c4e3841
spec:
  backoffLimit: 5
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 8fcb26be-addf-11e9-85af-60a44c4e3841
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 8fcb26be-addf-11e9-85af-60a44c4e3841
        job-name: myrunner-49lrt
    spec:
      containers:
      - args:
        - ... <args> ...
        image: my/image
        imagePullPolicy: Always
        name: cwl-ngtaxworkflowcwl
        resources:
          limits:
            cpu: "3"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  active: 1
  startTime: 2019-07-24T06:52:11Z
```

**Comment by jjkoehorst** [comment]
And some additional node information

Architecture | amd64
Docker Version | 18.9.4
Kernel Version | 4.15.0-50-generic
Kubelet Version | v1.13.5
Kube Proxy Version | v1.13.5
Operating System Image | Ubuntu 18.04.2 LTS
Operating System | linux

**Comment by brendandburns** [comment]
`listNamespacedJob` is what you want. I don't remember when the `v1` API came into Kubernetes. you might want to try using `BatchV1Beta1Api` instead of `BatchV1` API

What does `kubectl version` show?

**Comment by brendandburns** [comment]
fwiw, the equivalent of your `kubectl` call is:

`readNamespacedJob(....)`

**Comment by brendandburns** [comment]
I would also start with a vanilla Kubernetes (e.g. Minikube) to see if it is Rancher that is causing the problems.
