### ISSUE TITLE
Using the Kubernetes Client API with Kubeadm

### ISSUE THREAD

**Issue by smaillns** [kubernetes-client/java#634]
Some errors occurred while using the API by a Master node with kubeadm

**Comment by smaillns** [comment]
In fact the error due to using Docker container !!

**Comment by brendandburns** [comment]
Looks like this is resolved. If it's not, it's some sort of configuration error unrelated to this client.

Closing this issue.

**Comment by smaillns** [comment]
How can I configure the docker container inorder to be able to use the API ? thanks

**Comment by smaillns** [comment]
How can we solve the problem in case of Pod that carry a container which use the k8s Client API ?
