### ISSUE TITLE
How to get allocated gpus for node in kubernetes[with kubernetes-client java api]

### ISSUE THREAD

**Issue by jefby** [kubernetes-client/java#638]
I want to get available gpus[nvidia.com/gpu] in kubernetes cluster, and i now get total gpu from NodeAPI, but how to get allocated gpus from client api?? like `kubectl describe node` result:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                350m (8%)  0 (0%)
  memory             70Mi (0%)  170Mi (1%)
  ephemeral-storage  0 (0%)     0 (0%)
  nvidia.com/gpu     1          1
```

**Comment by yue9944882** [comment]
currently, a walk-around will be using `CustomObject` to deal w/ the third-party api. but we're working on a java model generator basing on CRD https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2. it will be coming out really soon. does the gpus crd definition provide structural schema?

**Comment by jefby** [comment]
> currently, a walk-around will be using `CustomObject` to deal w/ the third-party api. but we're working on a java model generator basing on CRD https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2. it will be coming out really soon. does the gpus crd definition provide structural schema?

@yue9944882 I use nvidia-gpu cards. and its crd definition is referenced from here. https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml

**Comment by brendandburns** [comment]
I believe that object goes into the `resources` field on the node object.  Regardless, dump the YAML for the object `kubectl get -o yaml ...` and look through that, that will show you where to look in the Java object.

I'm closing this as this should work correctly, please re-open if you try and it doesn't work.
