### ISSUE TITLE
How can I configure the docker container inorder to be able to use the API ? 

### ISSUE THREAD

**Issue by smaillns** [kubernetes-client/java#640]
How can we solve the problem in case of Pod that carry a container which use the k8s Client API ?

java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143) ~[okhttp-2.7.5.jar!/:na]

**Comment by yue9944882** [comment]
the error is suggesting that you didn't set configuration for the client object so it's by default connecting 127.0.0.1:8080. consider refer to the `Configuration` section of the [example list](https://github.com/kubernetes-client/java#example).

**Comment by brendandburns** [comment]
closing this as question is answered.

**Comment by smaillns** [comment]
@

> closing this as question is answered.

@brendandburns  Whay did you close the issue ?! I know that is a configuration issue, but I still don't find a solution for Docker containers
