### ISSUE TITLE
Unable to exec into a pod : '403 Forbidden'

### ISSUE THREAD

**Issue by anonymous19890806** [kubernetes-client/java#641]
Facing the below error while trying to exec into a pod :

        exec.exec(
                        "default",
                        "pod-name,
                        new String[] {"sh", "pg_dump -U postgres db-name> backup-file.sql"},
                        true,
                        true);

_java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'                                                                                                                   at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)                                                                                                          at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)                                                                                                                at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)                                                                                                              at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)                                                                                                                             at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)                                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                       at java.lang.Thread.run(Thread.java:748)
--_

Any help would be much appreciated!!

**Comment by yue9944882** [comment]
have you checked your RBAC configuration? `403 Forbidden` always suggests that

**Comment by anonymous19890806** [comment]
Using kubectl api-versions from the command line, I can see .rbac.authorization.k8s.io/v1 and 
rbac.authorization.k8s.io/v1beta1. 

Also, the below command when executed from the command line does work :
kubectl exec pod-name -- bash -c "pg_dump -U postgres db-name" > backup-file.sql

Could you please let me know if I am missing something?

**Comment by brendandburns** [comment]
I suspect that you aren't loading the kubeconfig file correctly. How are you constructing your the client (there is code that would come before your snippet that is missing)

This is definitely an auth problem.

**Comment by anonymous19890806** [comment]
Hi!

Thank you for the update.
Please find the entire function below. I have added the call for listing the pods as another use case.

public static void function-name() throws io.kubernetes.client.ApiException, IOException, InterruptedException {
        
	ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);
        Exec exec = new Exec();
        boolean tty = System.console() != null;

        // podlist
        CoreV1Api api = new CoreV1Api();
        V1PodList list =
                api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
        for (V1Pod item : list.getItems()) {
            System.out.println(item.getMetadata().getName());
        }

        // command execution
        exec.exec(
                        "default",
                        "pod-name",
                        new String[] {"sh", "pg_dump -U postgres db-name > backup-file.sql"},
                        true,
                        tty);

    }

Could you please let me know if I am still missing something here?

**Comment by brendandburns** [comment]
Does kubectl in the same environment work correctly ?

If so can you post your kubeconfig? Please redact secrets first, obviously

**Comment by rajashreetutgirl** [comment]
I'm facing the same problem. Could you please tell me how to configure RBAC.
Everytime Jupyter hub spins new pod and I need to write a file inside the pod once it is up. How I can achieve this.

I tried below code and it is giving me 403:
stream(kube_api.connect_get_namespaced_pod_exec, pod_name, 'jhub-starter',
stderr=True, stdin=True,
stdout=True, tty=False,
_preload_content=False)
LOG.info("preload content")

Thanks in Advance!!!

**Comment by yue9944882** [comment]
you're have to grant sufficient RBAC permissions before you establishes exec connection. i remember it should be `get` and `post` verbs upon `pods/exec`

**Comment by rajashreetutgirl** [comment]
@yue9944882 Is that permission specific to the particular pod or it is common to all the pods?
and also these permissions should be given via Yaml or it can be acheived via kubernetes python client?

**Comment by yue9944882** [comment]
> Is that permission specific to the particular pod or it is common to all the pods?

normally we grant the permission to a service-accoount and the pod mounts it as it starts running. 

> also these permissions should be given via Yaml or it can be acheived via kubernetes python client?

i suppose it's out of the scope of client SDK library, system administrators should have set up the permission beforehand..

**Comment by rajashreetutgirl** [comment]
@yue9944882 

Same Issue for pvc delete also. I have to delete the pvc in another namespace I have given clusterrole and clusterrolebinding.(attached below)

Error:
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"persistentvolumeclaims "claim-admin-end-2dde-2dgrandfinale" is forbidden: User "system:serviceaccount:edisonai-brahmos:default" cannot delete resource "persistentvolumeclaims" in API group "" in the namespace "jhubtest2"","reason":"Forbidden","details":{"name":"claim-admin-end-2dde-2dgrandfinale","kind":"persistentvolumeclaims"},"code":403}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
#namespace: edisonai-brahmos
name: pod-writer
rules:

apiGroups: [""] # "" indicates the core API group
resources: ["pvc"]
verbs: ["get", "post", "create", "delete", "update", "watch", "list", "put", "patch"]
=======================================================
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
name: pod-writer
roleRef:
kind: ClusterRole
apiGroup: rbac.authorization.k8s.io
name: pod-writer
subjects:
kind: ServiceAccount
name: default
namespace: edisonai-brahmos
=================================
Thanks in Advance !

**Comment by rjeberhard** [comment]
@brendandburns, it's probably worth a doc. note on this issue. I discovered that `kubectl exec` and the Java client have a difference in behavior in that kubectl uses a POST and this client uses a GET when making the initial call to the api-server to negotiate the web socket. This means that the necessary role for "pods/exec" is "create" when using kubectl and "get" when using the Java client.

**Comment by dzhi-lyft** [comment]
@rjeberhard Your comment above explained why kubectl exec works but not Java client. Thanks!

**Comment by justinmchase** [comment]
@rjeberhard Thank you for this comment, it saved my butt. I had the same experience, using a client library its using the http verb `GET` and thus needed the `- get` verb in the role.

It was not clear to me that `POST` was corresponding to the rbac verb `create` until just now, thank you for leaving that comment!

**Comment by rjeberhard** [comment]
You're welcome, @justinmchase.

**Comment by ethnchao** [comment]
Python Client is the same question.

**Comment by eduarhit** [comment]
> Python Client has same question.

I have the same problem in python client, what is the answer? where can we put those get and post verbs for the default user and default namespace? is there a yaml that can be modified? thanks
