### ISSUE TITLE
release-6.0 publish time

### ISSUE THREAD

**Issue by WywTed** [kubernetes-client/java#642]
There are some 'patch' problems fixed in latest version, so  when will it publish to release version 6.0?

**Comment by yue9944882** [comment]
in favor of having a release after #635 gets in and probably hold for 1-2 weeks to verify that. @brendandburns wdyt?

**Comment by brendandburns** [comment]
sure, works for me.

**Comment by markbooch** [comment]
Any updates on the v6.0 release time?

**Comment by yue9944882** [comment]
hopefully this friday? @brendandburns wdyt?

**Comment by markbooch** [comment]
Great! Looking forward to it.

**Comment by brendandburns** [comment]
works for me, I'll cut the release.

**Comment by yue9944882** [comment]
now you can check out version 6.0.1
