### ISSUE TITLE
Does exception contain sensitive information

### ISSUE THREAD

**Issue by msinton** [kubernetes-client/java#644]
I appreciate this might not be the right place for this, but do you know or can you help answer the question - Can the ApiException contain sensitive information?

**Comment by yue9944882** [comment]
@msinton that depends on how to define "sensitive"? do you mean whether the api-exception contains the requesting objects' information e.g. pod.spec.image?

**Comment by brendandburns** [comment]
The exception contains the body of the response from kubernetes. If that contains sensitive info, then it could be in the exception. In general, I don't think there has been any effort to scrub info from errors, so its definitely possible, eg the error might contain a Secret object that fails some sort of validation.

The Java code itself doesn't contribute any secret info in addition to the body

Hope that helps

Closing as the question is answered.
