### ISSUE TITLE
Kubernetes Client-Java API to get all deployments and describe deployments 

### ISSUE THREAD

**Issue by Nancy-Chauhan** [kubernetes-client/java#646]
What would be the API for having the similar results as we have by following commands on CLI :
```
kubectl get deployments
kubectl describe deployments 
```

**Comment by yue9944882** [comment]
> kubectl get deployments
kubectl describe deployments 

@Nancy-Chauhan actually both `get` and `describe` command are working in a complex way. `kubectl` has a number of built-in client-side printers to print out those human-readable formats.. this library is aiming to provide connecting interface in java to access kubernetes cluster, it doesn't actually offer advanced utilities in printing.

**Comment by Nancy-Chauhan** [comment]
@yue9944882 Thanks. That means currently there is no way. I wanted to use this library to fetch the config of all the namespaces i.e. in which services they are running and which branch they are using

**Comment by yue9944882** [comment]
> That means currently there is no way. I wanted to use this library to fetch the config of all the namespaces i.e. in which services they are running and which branch they are using

if you mean get all services under all namespaces, you can invoke `CoreV1Api#listServiceForAllNamespaces` to fetch all the existing services from cluster. what i mean is that there's no out-of-box printer implementations in this library, it will just empower you operate(get, list, create, update, delete...) resources.

**Comment by Nancy-Chauhan** [comment]
Thank you @yue9944882

**Comment by Nancy-Chauhan** [comment]
> > That means currently there is no way. I wanted to use this library to fetch the config of all the namespaces i.e. in which services they are running and which branch they are using
> 
> if you mean get all services under all namespaces, you can invoke `CoreV1Api#listServiceForAllNamespaces` to fetch all the existing services from cluster. what i mean is that there's no out-of-box printer implementations in this library, it will just empower you operate(get, list, create, update, delete...) resources. please check out the example list [kubernetes-client/java#example](https://github.com/kubernetes-client/java#example)

Hi @yue9944882 I have referred the exact question with function used in Issue #650 . Can you kindly please help me with this
