### ISSUE TITLE
Get Annotations : kubectl describe deployments/$SERVICE -n $Namespace

### ISSUE THREAD

**Issue by Nancy-Chauhan** [kubernetes-client/java#650]
I want to get annotations information using kubernetes client for the following command on CLI. When I use the following command on CLI, it generated specific information which contains annotations also : 
```
kubectl describe deployments/$SERVICE -n $Namespace
```

 I use the following function to get the deployment list . But I only want the information related to annotations.
```
AppsV1Api api1 = new AppsV1Api();
V1DeploymentList response = api1.listDeploymentForAllNamespaces(null, null, null, null, null, null,null,null,null);
System.out.println(response);
```

Is there any way to  generate this via kubernetes client - java ?

**Comment by yue9944882** [comment]
> kubectl describe deployments/$SERVICE -n $Namespace

`AppsV1Api#readNamespacedDeployment` is exactly what you're looking for

**Comment by Nancy-Chauhan** [comment]
Thank you so much @yue9944882 for great help 
```
class V1ObjectMeta {
    annotations: {deployment.kubernetes.io/revision=2, kubernetes.io/change-cause=Branch=master-27e600f Message=ON-1796 Re-write the cart GET for edit cart (#1256) Author=Gautam Prajapati Timestamp=2019-07-29T08:57:00.076650}
    clusterName: null
    creationTimestamp: null
    deletionGracePeriodSeconds: null
    deletionTimestamp: null
    finalizers: null
    generateName: null
    generation: 1
    initializers: null
    labels: {app=cart}
    name: cart
    namespace: mft-adoring-nancy
    ownerReferences: null
    resourceVersion: null
    selfLink: /apis/apps/v1beta1/namespaces/mft-adoring-nancy/deployments/cart
    uid: null
}
``` 
I am able to generate this . But do we have any other way to just generate annotations ? I am looking to only get the information of which branch and which commit number it is using i.e 
```
Branch=master-27e600f
```
in line 
```
annotations: {deployment.kubernetes.io/revision=2, kubernetes.io/change-cause=Branch=master-27e600f Message=ON-1796 Re-write the cart GET for edit cart (#1256) Author=Gautam Prajapati Timestamp=2019-07-29T08:57:00.076650}
```

**Comment by Nancy-Chauhan** [comment]
```
System.out.println(result.getMetadata().getAnnotations()); 
```
This works out . Thank you again @yue9944882 . I am closing this issue :)
