### ISSUE TITLE
client should periodically reload InClusterConfig token

### ISSUE THREAD

**Issue by mikedanese** [kubernetes-client/java#652]
See https://github.com/kubernetes/kubernetes/issues/70679

**Comment by yue9944882** [comment]
what's the recommended period of reloading for client? or, is there any way to know the expiration time of the current token? considering leader-election client tolerates at most second-ish period of failure, a longer period like minute-ish won't be fine i suppose..

**Comment by mikedanese** [comment]
client-go re-reads the token every 1 minute:

https://github.com/kubernetes/kubernetes/blob/663796e62441d4f1f871838d567ccee847555cff/staging/src/k8s.io/client-go/transport/token_source.go#L53-L57

> considering leader-election client tolerates at most second-ish period of failure, a longer period like minute-ish won't be fine i suppose..

Kubelet will refresh the token proactively before it expires. The minimum TTL for tokens is 10 minutes, and kubelet starts refreshing at 80% so you have about 2 minutes to reload with the lowest configurable token TTL.

**Comment by cizezsy** [comment]
Any progress in this? If no one is working on this issue, I think I can provide some help to implement it.

**Comment by yue9944882** [comment]
sure, let me know if you need any help

**Comment by cizezsy** [comment]
Hi, I am working on this and plan to add a new Authentication to [ApiClient](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L85 ) to support periodically token refreshing. 

I have a question about this class. The comment in [here](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L10) says this file should not be modified, but I have seen many manually changes in the commit history. Can this class be changed manually? Thanks!

**Comment by yue9944882** [comment]
it was manually edited in the past, but by picking all the manual changes to the upstream generator, this ApiClient class honors the original code template now.. what's the point of modifying this?

**Comment by zshihang** [comment]
java client generator needs this https://github.com/OpenAPITools/openapi-generator/issues/6023 because it lacks the functionality to do monkey patching.
