### ISSUE TITLE
deploy a pod from a Yaml file in kubeadm cluster

### ISSUE THREAD

**Issue by smaillns** [kubernetes-client/java#653]
I get this error while trying to deploy a pod from yaml file using k8s client api 

> java.io.IOException: Unknown apiVersionKind: v1/Pod known kinds are: {}
	at io.kubernetes.client.util.Yaml.modelMapper(Yaml.java:490) ~[client-java-4.0.0.jar!/:na]
	at io.kubernetes.client.util.Yaml.load(Yaml.java:184) ~[client-java-4.0.0.jar!/:na]
	at io.kubernetes.client.util.Yaml.load(Yaml.java:172) ~[client-java-4.0.0.jar!/:na]

The problem occured while using kubeadm, but in minikube it works well !
```
public void deployPodFromFile(@PathVariable String name) throws IOException, ApiException{


        File file = new File("/~ path"+ name);


        //connect to the API Server
        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);


        V1Pod pod = (V1Pod) Yaml.load(file);
        System.out.println(pod.toString());


        CoreV1Api api = new CoreV1Api();
        api.createNamespacedPod("default",pod,null, null, null);

```

**Comment by brendandburns** [comment]
Your cluster is broken in some way (not sure what it is) or your not actually talking to the cluster.

Does `kubectl` work with the `kubeadm` cluster?
