### ISSUE TITLE
how to use xxxAsync function?

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#654]
the java client have four create namespace method

Async
```
public com.squareup.okhttp.Call createNamespaceAsync(.....)
```

the async method how to use？
If there are any examples, look at this method separately and don't know how to use it.

Best Wishes

**Comment by brendandburns** [comment]
You probably don't need to use this call. But if you do want to use it, it executes a raw HTTP request and hands you back the `Call` object for you to stream data from, etc. if you want to.
