### ISSUE TITLE
Create client from client-certificate-data and client-key-data?

### ISSUE THREAD

**Issue by zhangzerui20** [kubernetes-client/java#658]
How can I create client from client-certificate-data and client-key-data. Are there any examples?

**Comment by zhangzerui20** [comment]
When I use fabric, I can do this :

      final io.fabric8.kubernetes.client.Config kubeConfig = new ConfigBuilder()
          .withMasterUrl("https://" + cluster.getEndpoint())
          .withCaCertData(cluster.getMasterAuth().getClusterCaCertificate())
          .withClientCertData(cluster.getMasterAuth().getClientCertificate())
          .withClientKeyData(cluster.getMasterAuth().getClientKey())
          .withNamespace(config.getString(GKE_CLUSTER_NAMESPACE))
          .build();

**Comment by yue9944882** [comment]
i will, for example, load the certs by client-builder. hope that help.

```java
            ClientBuilder clientBuilder = new ClientBuilder().setBasepath(...);
            Authentication authentication = new ClientCertificateAuthentication(
                    clientContext.getClientCert(), clientContext.getClientKey()
            );
            clientBuilder.setAuthentication(authentication);
```

**Comment by brendandburns** [comment]
Closing this because I think the question is answered. Please re-open specific issues if the ClientBuilder doesn't support what you need.
