### ISSUE TITLE
Unable to get pod output using attach

### ISSUE THREAD

**Issue by gondyk** [kubernetes-client/java#660]
I'm trying to get std output from pod using this example: https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/AttachExample.java

Using GO client I can get pod's stdout, but Java client isn't working to get pod's stdout.
My pod prints text to stdout, but result.getStandardOutputStream() is still empty

Java client: 5.0.0
Kubernetes: v1.15.2

**Comment by glarwood** [comment]
@gondyk, I am experiencing this exact problem. I can write to my pod's stdin using AttachResult#getStandardInputStream, however, AttachResult#getStandardOutputStream is always empty. 

My workaround is to use PodLogs#streamNamespacedPodLog, which works fine, but I'd rather just use AttachResult for everything. Were you able to figure it out?
