### ISSUE TITLE
What is the proper way to watch the change of a ConfigMap

### ISSUE THREAD

**Issue by MalcolmSanders** [kubernetes-client/java#664]
Hi, all,
Previously I'm trying to watch a ConfigMap using CoreV1Api. I found that using api.listNamespacedConfigMapAsync() might not work as I expected. I'm using the master branch of kubernetes-client/java. Here is my test case:

`public class V1ConfigMapWatcherTester {
	private static final Logger logger = LoggerFactory.getLogger(V1ConfigMapWatcherTester.class);

	public static void main(String[] args) throws IOException, ApiException {
		ApiClient client = Config.defaultClient();
		client.getHttpClient().setReadTimeout(0, TimeUnit.SECONDS); // infinite timeout
		Configuration.setDefaultApiClient(client);

		CoreV1Api api = new CoreV1Api();

		Watch<V1ConfigMapList> watch =
			Watch.createWatch(
				client,
				api.listNamespacedConfigMapAsync(
					"my_namespace",
					null,
					"_continue_example",
					"metadata.name=my-example-configmap",
					null,
					100,
					null,
					null,
					Boolean.TRUE,
					new ApiCallback<V1ConfigMapList>() {
						@Override
						public void onFailure(ApiException e, int statusCode, Map<String, List<String>> responseHeaders) {
							logger.info("onFailure");
						}

						@Override
						public void onSuccess(V1ConfigMapList result, int statusCode, Map<String, List<String>> responseHeaders) {
							logger.info("onSuccess");
						}

						@Override
						public void onUploadProgress(long bytesWritten, long contentLength, boolean done) {
							logger.info("onUploadProgress");
						}

						@Override
						public void onDownloadProgress(long bytesRead, long contentLength, boolean done) {
							logger.info("onDownloadingProgress, bytesRead: " + bytesRead + ", contentLength: "
								+ contentLength + ", done: " + done);
						}}),
				new TypeToken<Watch.Response<V1ConfigMapList>>() {}.getType());

		try {
			while (true) {
				for (Watch.Response<V1ConfigMapList> item : watch) {
					System.out.printf("%s : %s%n", item.type, item.object.getKind());
				}
			}
		} finally {
			watch.close();
		}
	}
}`

A error is thrown out as follows, and as a result, no watcher is constructed.
`Exception in thread "main" java.lang.IllegalStateException: Already Executed
	at com.squareup.okhttp.Call.execute(Call.java:75)
	at io.kubernetes.client.util.Watch.createWatch(Watch.java:92)
	at common.V1ConfigMapWatcherTester.main(V1ConfigMapWatcherTester.java:31)`

After looking into the client code, I found that if I remove the following line in the implementation of CoreV1Api.listNamespacedConfigMapAsync(), the test case could work as I expected.
`        apiClient.executeAsync(call, localVarReturnType, callback);`

Here is the logs of my expected result. Notice that I modified the ConfigMap during its watch so "MODIFIED" event is received.
`[INFO ] 2019-08-21 17:35:48.963 [main] V1ConfigMapWatcherTester - onDownloadingProgress, bytesRead: 2353, contentLength: -1, done: false
[INFO ] 2019-08-21 17:35:48.969 [main] V1ConfigMapWatcherTester - onDownloadingProgress, bytesRead: 2620, contentLength: -1, done: false
ADDED : ConfigMap
[INFO ] 2019-08-21 17:36:20.228 [main] V1ConfigMapWatcherTester - onDownloadingProgress, bytesRead: 5270, contentLength: -1, done: false
MODIFIED : ConfigMap`

So my question is (1) is this a bug or (2) what's the recommended way to watch a ConfigMap ?

**Comment by yue9944882** [comment]
pass `listNamespacedConfigMapCall` instead of  `listNamespacedConfigMapAsync`, plz refer to the watch example:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

**Comment by MalcolmSanders** [comment]
> pass `listNamespacedConfigMapCall` instead of `listNamespacedConfigMapAsync`, plz refer to the watch example:
> 
> https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

Thanks.  I found another problem, `item.object.getItems().size()` always gets zero which means there is no ConfigMap object in V1ConfigMap got from watch, while I can get the data of ConfigMap through `readNamespacedConfigMap`.

`                       for (Watch.Response<V1ConfigMapList> item : watch) {
				System.out.printf("%s : %s : %d \n", item.type, item.object.getKind(), item.object.getItems().size());
			}`

Is it by design that Watch will only notify events without the data of ConfigMap ?

**Comment by yue9944882** [comment]
it should be `Watch<V1ConfigMap> watch`, the type template is api-type instead of api-list-type

**Comment by MalcolmSanders** [comment]
> it should be `Watch<V1ConfigMap> watch`, the type template is api-type instead of api-list-type

Got it. Thank you very much 👍
