### ISSUE TITLE
import io.kubernetes.client.util cannot be resolved in client-java-api-6.0.0-beta1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by StimpsonH** [kubernetes-client/java#670]
Hi all,

I've tried running both `mvn install` and `mvn package` to generate the jars and have manually installed them, but now I'm getting error `import io.kubernetes.client.util not resolved`. I've noticed in `target/classes` that the `io.kubernetes.client.util` package does not exist, so was it not generated during `mvn install/package`? How can I resolve this if possible?

**Comment by yue9944882** [comment]
now you can check out version `6.0.1`
