### ISSUE TITLE
V1Job.getStatus is missing information about active/failed/suceeded pods

### ISSUE THREAD

**Issue by victornoel** [kubernetes-client/java#673]
When retrieving jobs using `BatchV1Api.listNamespacedJob`, the `V1Job` objects are missing informations, in particular the object returned by `getStatus`.

Here is an example of calling `toString()` on such an object:
```
    class V1JobStatus {
            active: null
            completionTime: 2019-08-23T07:37:20.000Z
            conditions: [class V1JobCondition {
                lastProbeTime: 2019-08-23T07:37:20.000Z
                lastTransitionTime: 2019-08-23T07:37:20.000Z
                message: null
                reason: null
                status: True
                type: Complete
            }]
            failed: null
            startTime: 2019-08-23T07:37:02.000Z
            succeeded: 1
        }
```

As you can see, `active` and `failed` are `null`. I would have expected those field to be set to 0.

**Comment by yue9944882** [comment]
what output do you get running `kubectl get job xxx -o json`?

**Comment by victornoel** [comment]
@yue9944882 good point, the json for status is:
```json
    "status": {
        "completionTime": "2019-08-22T14:34:58Z",
        "conditions": [
            {
                "lastProbeTime": "2019-08-22T14:34:58Z",
                "lastTransitionTime": "2019-08-22T14:34:58Z",
                "status": "True",
                "type": "Complete"
            }
        ],
        "startTime": "2019-08-22T14:33:55Z",
        "succeeded": 1
    }
```

**Comment by yue9944882** [comment]
i think it's in consistence w/ kubectl's behavior. the java client is doing the deserialization as intended

**Comment by victornoel** [comment]
@yue9944882 I understand, so this means this is out of the scope of this java client, and if I wanted things to be different, I would have to ask the kubernetes api project basically?

**Comment by yue9944882** [comment]
> I wanted things to be different, I would have to ask the kubernetes api project basically?

exactly, kubernetes/kubernetes
