### ISSUE TITLE
No error is thrown when create a ConfigMap with the reference of an inexistent owner

### ISSUE THREAD

**Issue by MalcolmSanders** [kubernetes-client/java#679]
Hi,

I find that there is no exception when I create a ConfigMap with an OwnerReference while the owner is actually inexistent.

The code is as follows. 

`              // non-existent owner
                V1OwnerReference ownerReference = new V1OwnerReference()
			.apiVersion("v1").kind("ConfigMap").controller(Boolean.FALSE)
			.name("my-owner").uid("7b2c01ef-cad5-11e9-ac55-98039bb2cdff").blockOwnerDeletion(Boolean.TRUE);

		String namespace = "my-namespace";
		String name = "my-example-configmap";
		Map<String, String> data = new HashMap<>();
		data.put("key1", "value4");
		data.put("key2", "value4");
		V1ConfigMap configMap = (new V1ConfigMapBuilder())
			.withApiVersion("v1")
			.withKind("ConfigMap")
			.withNewMetadata().withName(name).withNamespace(namespace)
			.withOwnerReferences(ownerReference).endMetadata()
			.withData(data)
			.build();
                 V1ConfigMap response = api.createNamespacedConfigMap(namespace, configMap, null, null, null);`

Does that mean we should always double check whether the ConfigMap is successfully created (e.g. by listNamespacedConfigMap()) after calling createNamespacedConfigMap() ? Or any necessary configurations needed ?

**Comment by yue9944882** [comment]
owner-reference is not checked on your create/update operations.. and that's by-design because of limitted transactional operation support from etcd backends.

**Comment by MalcolmSanders** [comment]
> owner-reference is not checked on your create/update operations.. and that's by-design because of limitted transactional operation support from etcd backends.

Got it, Thanks. So I think it's needed to doule check the existence of newly created object.

**Comment by brendandburns** [comment]
Yes, and in general as @yue9944882 mentions the Kubernetes API doesn't provide referential integrity.

Closing as questions are answered.
