### ISSUE TITLE
Propose release 0.2.0

### ISSUE THREAD

**Issue by lwander** [kubernetes-client/java#68]
@mbohlool @brendandburns

This will give us a chance to test the release process again now that I've run it once. We'll likely promote this to 1.0.0-beta.1 if everything goes smoothly. I'll link to release notes & an updated version matrix here.

**Comment by lwander** [comment]
Let's also block on https://github.com/kubernetes-client/java/issues/64

**Comment by brendandburns** [comment]
@lwander sorry for the delay here. This sounds like a good thing to do, what do you need from me?

**Comment by lwander** [comment]
No worries - this has been stagnant due to my traveling for work + vacation. Will work on getting this released today.

**Comment by lwander** [comment]
https://github.com/kubernetes-client/java/pull/77

**Comment by lwander** [comment]
Closing as the release starts...
