### ISSUE TITLE
how to use V1Preconditions in V1DeleteOptions when delete an object ?

### ISSUE THREAD

**Issue by MalcolmSanders** [kubernetes-client/java#680]
Hi,

I'd like to check the ResourceVersion of an object before deleting this object to ensure that this deletion is performed as expected. Is it possible to use V1Preconditions in V1DeleteOptions when deleting a object ?

My sample code is as follows:
`                        V1Status status = api.deleteNamespacedConfigMap(name, namespace, null,
				new V1DeleteOptionsBuilder().withApiVersion("v1").withKind("ConfigMap").withGracePeriodSeconds(0L)
					.withPreconditions(
						new V1PreconditionsBuilder()
                                                           .withResourceVersion("31875779")
							.withUid("32019252-cd5c-11e9-ac55-98039bb2c90e")
							.build()).build(),
				null, 0,
				Boolean.FALSE, null);`

But "Internal Server Error" occurs, while the error logs of kube-apiserver is as follows:
`apiserver received an error that is not an metav1.Status: &runtime.notRegisteredErr{schemeName:"k8s.io/apimachinery/pkg/apis/meta/internalversion/register.go:31", gvk:schema.GroupVersionKind{Group:"", Version:"v1", Kind:"ConfigMap"}, target:runtime.GroupVersioner(nil), t:reflect.Type(nil)}`

**Comment by MalcolmSanders** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#deleteoptions-v1-meta
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#preconditions-v1-meta

From the docs, it seems that precondition only support uid field. But still I get the same error when I build V1Preconditions only with uid.

**Comment by brendandburns** [comment]
When you create the DeleteOptions object, it's `kind` and `apiGroup` etc should be for the DeleteOptions resource type, not a ConfigMap resource type.

**Comment by MalcolmSanders** [comment]
> When you create the DeleteOptions object, it's `kind` and `apiGroup` etc should be for the DeleteOptions resource type, not a ConfigMap resource type.

Got it, haven't noticed that DeletionOptions is also a type of `kind`.
Thanks very much.
