### ISSUE TITLE
copyFileFromPod drops container name

### ISSUE THREAD

**Issue by ceeaspb** [kubernetes-client/java#681]
One of the copyFileFromPod methods drops the container name, leading to possible error.

https://github.com/kubernetes-client/java/blob/632d6c5a17e9bc2d3c69d5d05cb36ee42044d072/util/src/main/java/io/kubernetes/client/Copy.java#L79

**Comment by brendandburns** [comment]
Definitely a bug!

If you want to, a PR with a fix (and a test) would be great, otherwise we'll get to this soon.

Thanks for reporting!

**Comment by ceeaspb** [comment]
Thanks, I have a few more non-happy path issues to report also.
