### ISSUE TITLE
copy directory fails with multi container pod and null container name

### ISSUE THREAD

**Issue by ceeaspb** [kubernetes-client/java#688]
Copying large files or directories fails silently.
There have been many reports of this failing at the level of `docker` in other projects.

Some report AWS ICMP config issues, one reports out of memory in the container when cat'ing the files.

In the test case `tar` and `cat` existed in the container.

So it might not be possible to resolve here, but the error should be reported back to calling code so it can be handled.

**Comment by yue9944882** [comment]
i doubt if it's the underlying read/write timeout in the okhttp client interrupting the streaming.. the default value is 10-second-ish i remember, consider set them to `0` to unlease from the timeout

**Comment by ceeaspb** [comment]
Having turned on client debug the issue is that running copy against a pod with multiple containers fails with http rc 400 bad request.
Adding a specific container name works.

`kubectl` provides some hints when a container is not specified:
```Defaulting container name to first-container.
Use 'kubectl describe pod/test-pod -n test-ns' to see all of the containers in this pod.```

This happened because I followed the example which has null for the container name:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/CopyExample.java#L45

The null is not resolved to the first container name,
also the error is not passed back to the calling code so it can be handled (see #686 ).

**Comment by brendandburns** [comment]
Yeah, it looks like `kubectl` does a get and substitutes in the first container.
