### ISSUE TITLE
Is it possible to list/watch a group of objects according to the prefix

### ISSUE THREAD

**Issue by MalcolmSanders** [kubernetes-client/java#689]
Hi, 
There is a scenario in my case which I need to watch a group of objects in k8s (e.g. ConfigMaps) with the same prefix. But I didn't find the ways using k8s java api.

There are several facts that I know:
(1) We can list/watch all the objects of the same type in a namespace.
(2) We can list/watch an object specified by field selector, while field selector only support "equals" ("=" or "==") and "not equal" ("!=") operator, not enough to specify the prefix.
(3) etcd api support list/watch with prefix or range.

**Comment by yue9944882** [comment]
> (1) We can list/watch all the objects of the same type in a namespace.
> (2) We can list/watch an object specified by field selector, while field selector only support "equals" 


these are all supported in the java client. please refer to the provided example from README page. you can override the parameters in https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java#L38

**Comment by brendandburns** [comment]
Closing since the question is answered.

**Comment by MalcolmSanders** [comment]
Sorry for not being clear.

I know current APIs can list/watch (1) all the objects in a namespace or (2) objects specified by field selector. But is it possible to only list/watch the objects with the same prefix so that lesser objects will be returned as the result, just like [etcd with prefix api](https://godoc.org/github.com/coreos/etcd/clientv3#example-Watcher--WatchWithPrefix).

For example, if all the configmaps in a namespace is as follows:
foo1
foo2
foo3
bar1
bar2

If there is with-prefix option "foo" when list the namespace, I will only get "foo1", "foo2" and "foo3" instead of all the objects in the namespace. And field selector only support "==" and "!=" thus not enough for this case.

**Comment by yue9944882** [comment]
no, prefix-based list-watch isn't supported in the kube-apiserver level.

**Comment by MalcolmSanders** [comment]
> no, prefix-based list-watch isn't supported in the kube-apiserver level.

Got it, thanks.
