### ISSUE TITLE
Why are the Lists initialized with null and not a new ArrayList?

### ISSUE THREAD

**Issue by derkd** [kubernetes-client/java#690]
https://github.com/kubernetes-client/java/blob/a7acacd907eab78bdd36ef1a889c4911fa950943/kubernetes/src/main/java/io/kubernetes/client/models/V1EndpointSubset.java#L37

**Comment by brendandburns** [comment]
This code is automatically generated by the swagger-api-codegen. That's a question for the code generator project.

My guess is that there is a distinction in JSON between `undefined | null` and `[]` and by default things are undefined/null in a JSON object.

Closing since question is answered.
