### ISSUE TITLE
How to efficiently implement "get and watch"

### ISSUE THREAD

**Issue by shakeelrao** [kubernetes-client/java#693]
I'm relatively new to developing with the K8s API and am looking for some guidance on how to approach the following problem.

**The problem:** I want to develop a module that allows clients to fetch the current state of some resource in K8s (i.e. get all Pods in namespace X) and then have the ability to watch for changes in that resource and respond to it. The key here is that I would like to support "get and watch" dynamically (i.e. clients tell us what resources they want, so we won't know what resources to watch ahead of time). As an example, another client could request "get all Pods in namespace Y".

At first glance, it seems like I could use the `Watch` class for each client request, but this solution would have a background thread blocking in a loop for each resource (which seems quite inefficient).

Are there any higher level primitives I can leverage to implement this type of functionality?

Thanks!

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java

you can either use informer to list-and-watch or use the controller-builder to setup your runtime..

**Comment by shakeelrao** [comment]
Thanks @yue9944882. Are there docs explaining how `Controllers` work internally?

**Comment by yue9944882** [comment]
https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html

you can start by reading basic concepts from the kubebuilder docs, the java controller-builder is basically porting from the golang project.

**Comment by brendandburns** [comment]
Closing since the question is answered.

**Comment by shakeelrao** [comment]
In `InformerExample`, the code won't compile due to `Unhandled exception: io.kubernetes.client.ApiException` in the `CallGenerator` lambda. Any ideas on how to fix this?

**Comment by yue9944882** [comment]
> io.kubernetes.client.ApiException

can you print out the body for more information? (using ApiException#getResponseBody)

**Comment by shakeelrao** [comment]
There is no exception being generated because I can't compile the code. The compiler message is:
`java: unreported exception io.kubernetes.client.ApiException; must be caught or declared to be thrown` due to the `listNamedspacedPodCall` in the lambda.

**Comment by yue9944882** [comment]
```java
(CallGeneratorParams params) -> {
    return api.listNamespacedPodCall(
       "default", // default namespace for testing with minikube
       null,
       null,
       null,
       null,
       null,
       null,
       params.resourceVersion,
       params.timeoutSeconds,
       params.watch,
       null,
       null);
}
```

strip the try-catch block, and it will fly

**Comment by shakeelrao** [comment]
@yue9944882 @brendandburns Hi! I've been taking a look at the `Informer` and `Controller` examples and I'm not entirely sure how to adapt them to my use-case. Basically what I want do to is have a service that maintains an up-to-date list of pods (via watching) for a given namespace and label. 

For example, let's call our service `A`. When `A` starts up for the first time, it has nothing cached. Let's say `A` receives the following request from a client: `getPods("default", "app=nginx")` where the first arg is the namespace and the second is a label selector. 

When `A` receives this request, it will do a plain `GET` for all the pods in the `default` namespace with the label `app: nginx`, cache it, and return that to client. It will also start a watch on these pods and update the cache on updates. Thus, whenever a new client asks for `getPods("default", "app=nginx")`, it will receive an up-to-date list of the pods.
