### ISSUE TITLE
listNamespacedStatefulSet question

### ISSUE THREAD

**Issue by chlung** [kubernetes-client/java#70]
Hi,
When we call apiInstance.listNamespacedStatefulSet, the result only contains the apiVersion and kind under list level not each item level.  Is this an expected behavior?  Thanks.

class V1beta1StatefulSetList {
    apiVersion: apps/v1beta1
    items: [class V1beta1StatefulSet {
        apiVersion: null
        kind: null
....
}]
    kind: StatefulSetList
    metadata: class V1ListMeta {
        resourceVersion: 1078833
        selfLink: /apis/apps/v1beta1/namespaces/default/statefulsets
    }
}

**Comment by brendandburns** [comment]
I believe that this is expected, though I'm not 100% positive...

Try `kubectl get statefulset -o json` and see if it's present there...

**Comment by lwander** [comment]
Weird thing is `kubectl get <kind> -o json` has the kind for the top-level object as `List`, and each item correctly annotated with `<kind>`. But when run with `-v 9` the response from the API has the top-level kind as `<kind>List`, and no kind for any of the items in the list. The API response is consistent with that of the client library, but not with `kubectl -o json`.

**Comment by brendandburns** [comment]
-o json takes it into in memory object and then back, so I bet that transformation is what is adding the extra types.

For us, I think we should stick to what's on the wire.

________________________________

**Comment by lwander** [comment]
SGTM
