### ISSUE TITLE
Generated docs include examples with commented out imports

### ISSUE THREAD

**Issue by ganchurin** [kubernetes-client/java#702]
Generated docs include examples with commented out imports. For example, [CoreV1Api](https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CoreV1Api.md) has the following lines in the first example:
```
// Import classes:
//import io.kubernetes.client.ApiClient;
//import io.kubernetes.client.ApiException;
//import io.kubernetes.client.Configuration;
//import io.kubernetes.client.auth.*;
//import io.kubernetes.client.apis.CoreV1Api;

ApiClient defaultClient = Configuration.getDefaultApiClient();
```

**Comment by yue9944882** [comment]
these are generated by swagger-codegen.. it will be fixed after we migrating to openapi-codegen by #595  

https://github.com/OpenAPITools/openapi-generator/blob/4538db92a21b68f5ae134b5ed7434278ceba696c/modules/openapi-generator/src/main/resources/Java/api_doc.mustache#L26-L32

**Comment by ganchurin** [comment]
@yue9944882 Thanks for the response! Should I close the issue?
