### ISSUE TITLE
Support setting owner reference and labels when creating EndpointsLock or ConfigMapLock for LeaderElection

### ISSUE THREAD

**Issue by MalcolmSanders** [kubernetes-client/java#704]
Hi,

Currently I'm testing LeaderElection APIs event though it's only in the latest beta version. It works well for me, and now I'm considering about a graceful way to recycle the objects created for leader election.

I thought if EndpointsLock/ConfigMapLock support (1) owner reference and (2) labels, it could be more convenient to do recycling. What do you think ? @wu8685

**Comment by wu8685** [comment]
@MalcolmSanders I don't get your point. What is the owner/label supposed to be?

**Comment by yue9944882** [comment]
> @MalcolmSanders I don't get your point. What is the owner/label supposed to be?

IIUC, what @MalcolmSanders 's proposing is to group the locks from a same controller in some way so that we can clean the old locks when it's detected as "unused" any more.. it's a good idea i believe.. but curiously can you expand more use-cases for recycling the old locks? i didnt personally see a strong use-case tho so far..

**Comment by MalcolmSanders** [comment]
Some kind of our applications can be terminable just like k8s jobs. Also such applications could be stopped for any reason. We want to make sure all the resources created by such applications could be safely deleted at any circumstances. So it seems that setting deployment's owner reference to all the resources created by the application is a good way. Furthermore, we set labels to all the resources so that we can delete all the resources in one operations and don't have to keep track of them.

I think an easy way to achieve my request could be add a new constructor of EndpointsLock/ConfigMapLock to enable setting labels and OwnerReferences. Then set `labels` and `OwnerReferences` to `V1ObjectMeta` .

public EndpointsLock(String namespace, String name, String identity, ApiClient apiClient, List<V1OwnerReference> ownerReferences, Map<String, String> lables)

**Comment by wu8685** [comment]
How about using `namespace` and `name`, which are provided through current constructor, to locate the lock your application creates?

By the way, I think the usage of ownerReference in your case is not appropriate. labels may be better. But as I said, using `namespace` and `name` is enough.

**Comment by MalcolmSanders** [comment]
> How about using namespace and name, which are provided through current constructor, to locate the lock your application creates?

I think OwnerReference is necessary in my case because we can not make sure that delete operation can always be executed since any error might occur. It's worthwhile to mention that our application is not long running service with the same name but terminable jobs with unique names. Thus any error of an application might result in some objects left un-recycled. What's worse, it could harm the performance or stability of k8s system if such application errors are not delt with in time. While with the help of OwnerReference, we can always say there won't be any object left once the application been stopped.

As to labels, you are right. `name` and `namespace` is enough yet not very graceful in my point of view.

**Comment by wu8685** [comment]
I still prefer to keep the constructor as simple as possible. V1ObjectMeta is not necessary for the lock. A label for leader election lock may be necessary, but I'm afraid it will bring in another problem, because this behavior is not consistent with go client.

How about using admission webhook to attach more information like labels to the lock when it is created in your case?

**Comment by MalcolmSanders** [comment]
Admission webhook is a solution, but it seems too heavy in my case. Based on current APIs, all the objects except EndpointsLock and ConfigMapLock could allow users to specify OwnerReference and labels. Besides, if no more information could be attached to EndpointsLock/ConfigMapLock during creation, admission web server doesn't know how to modify for each lock since each lock actually belongs to an unique application (k8s deployment).

On the other hand, I understand your concern. I think I might just migrate the implementation of EndpointsLock/ConfigMapLock to my own code and do some modification, that is, to implement a new io.kubernetes.client.extended.leaderelection.Lock in my project.
