### ISSUE TITLE
"renewDeadline" support for leader election

### ISSUE THREAD

**Issue by moeyui1** [kubernetes-client/java#706]
https://github.com/kubernetes-client/java/blob/5ae91646b465774c194a1b9299274005c185d5d6/extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionConfig.java#L11

The "renewDeadline" field in `LeaderElectionConfig` seems to be useless currently, is there a plan to support renew deadline duration in the future?
Probably related to this https://github.com/kubernetes-client/java/pull/538#discussion_r274320762

**Comment by wu8685** [comment]
It seems a mistake. I create a PR, Please take a look.
