### ISSUE TITLE
Unbounded network interceptor chain in CustomObjectsApi class

### ISSUE THREAD

**Issue by tbak** [kubernetes-client/java#707]
On each invocation of `io.kubernetes.client.apis.CustomObjectsApi#replaceNamespacedCustomObjectCall(...)`, a new `com.squareup.okhttp.Interceptor`
instance is appended, which results in every growing interceptor list, which eventually leads to `StackOverflowError`.
This problem exists in all methods in `CustomObjectsApi` class which include the following code snippet:
```java
        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }
        
```

**Comment by tbak** [comment]
I have missed that this issue was already reported here: https://github.com/kubernetes-client/java/issues/482. Any chance it will be fixed soon?

**Comment by yue9944882** [comment]
we're getting this by #595 (probably this month or next), but the pull will break backward-compatibility in some way, we have to evaluate carefully..

**Comment by tbak** [comment]
@yue9944882 If I can help in any way, please let me know.
