### ISSUE TITLE
github's releases page does not show latest releases

### ISSUE THREAD

**Issue by Hendrik-H** [kubernetes-client/java#713]
The [releases page](https://github.com/kubernetes-client/java/releases) on github does not show the latest releases. The last listed is `4.0.0`. This has the side effect that there are no notifications about new releases. Was the release process changed and is the list  not updated anymore?

**Comment by brendandburns** [comment]
Unfortunately that page has to be manually updated (afaik) so it's not part of the release process (and thus got forgotten.... :( )

I've gone and added the two additional releases, and we'll try to remember better in the future :)

Thanks!
