### ISSUE TITLE
Leader Elector Cannot re-elect after renew failed

### ISSUE THREAD

**Issue by markbooch** [kubernetes-client/java#714]
Using leader elector which introduced in recent release, I have three pods on election, at the time, I found there are no one is working, all of them have experience the acquire->renew->stop workflow. After that, the pod will not acquire anymore,  I see such implementation in your code, which should be a problem.

Do we need to add loop in our application code? I see there are no such code in your example.
@wu8685

**Comment by moeyui1** [comment]
Currently the election will not retry when lost leadership, it's just the same as [kubernetes client-go](https://github.com/kubernetes/client-go). Perhaps you can use a loop to retry election, something like:
```java
// change stopped to true if you really want it stop the election
while (!stopped) {
    logger.info("let the election begin...");
    elector.run(() -> {
        // start working
    },
    () -> {
        // stop working
    });
}
```

**Comment by markbooch** [comment]
Thanks for the explaination.
