### ISSUE TITLE
CRD resource conversion error problem

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#715]
I have a custom resource 

```
CustomObjectsApi apiInstance = new CustomObjectsApi(apiClient);

Object result = apiInstance.getNamespacedCustomObject(group, version, namespace, plural, name);

System.out.println(result);
```
**Output**

```
{apiVersion=xx.xxx.com/v1, kind=LoadBalancer, ....}
```
How can I convert this Object into a custom V1LoadBalancer class

```
public class V1LoadBalancer {

    @SerializedName("apiVersion")
    private String apiVersion ;

    @SerializedName("kind")
    private String kind ;

    @SerializedName("metadata")
    private Object metadata ;

    @SerializedName("spec")
    private Object spec ;

    @SerializedName("status")
    private Object status ;
}
```
Now I report the following errors directly when I convert

```
V1LoadBalancer result = (V1LoadBalancer)apiInstance.getNamespacedCustomObject(group, version, namespace, plural, name);

System.out.println(result);

Exception in thread "main" java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.example.springdemo.blb.V1LoadBalancer
	at com.example.springdemo.blb.TestLocalK8s.main(TestLocalK8s.java:75)
```

**Comment by ZP-AlwaysWin** [comment]
/assign hi @brendandburns @yue9944882 
Excuse me
Is there any good solution to this problem now?

**Comment by brendandburns** [comment]
You're going to want to use `getNamespacedCustomObjectCall(...)`

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/CustomObjectsApi.java#L1252

That will give you an `okhttp` `Call` object which is the object for the HTTP call before it is executed.

Once you execute that `Call` you will be able to get the raw JSON from the response, and then you will be able to do `gson.fromJson(V1LoadBalancer.class)` which should do the right thing.

Look at the code here:

```
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
```

But you'll substitute in a different `Type` and I think it should work.

**Comment by ZP-AlwaysWin** [comment]
> You're going to want to use `getNamespacedCustomObjectCall(...)`
> 
> https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/apis/CustomObjectsApi.java#L1252
> 
> That will give you an `okhttp` `Call` object which is the object for the HTTP call before it is executed.
> 
> Once you execute that `Call` you will be able to get the raw JSON from the response, and then you will be able to do `gson.fromJson(V1LoadBalancer.class)` which should do the right thing.
> 
> Look at the code here:
> 
> ```
>         Type localVarReturnType = new TypeToken<Object>(){}.getType();
>         return apiClient.execute(call, localVarReturnType);
> ```
> 
> But you'll substitute in a different `Type` and I think it should work.

Yes,you are right,it works. Thank you very much

```
com.squareup.okhttp.Call call = apiInstance.getNamespacedCustomObjectCall(group, version, namespace,plural, name,null,null);

Response response = call.execute();

if (response.isSuccessful()) {
    Gson gson = new JSON().getGson();
    V1LoadBalancer loadBalancerCrdDetails = gson.fromJson(response.body().string(),V1LoadBalancer.class);
    System.out.println(loadBalancerCrdDetails);
 }
```
