### ISSUE TITLE
What's the difference? readNamespacedDeployment and readNamespacedDeploymentStatus 

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#720]
What's the difference? readNamespacedDeployment and readNamespacedDeploymentStatus 

```
public V1Deployment readNamespacedDeploymentStatus(String name, String namespace, String pretty) throws ApiException {
        ApiResponse<V1Deployment> resp = readNamespacedDeploymentStatusWithHttpInfo(name, namespace, pretty);
        return resp.getData();
    }
```
and

```
public V1Deployment readNamespacedDeployment(String name, String namespace, String pretty, Boolean exact, Boolean export) throws ApiException {
        ApiResponse<V1Deployment> resp = readNamespacedDeploymentWithHttpInfo(name, namespace, pretty, exact, export);
        return resp.getData();
    }
```

What's the difference between two functions of this type? They are the same return value.

What I understand is that this `readNamespacedDeploymentStatus` function should not return this definition `V1DeploymentStatus`?

**Comment by ZP-AlwaysWin** [comment]
/assign @brendandburns 
Can you solve my doubts?
Best Wishes

**Comment by brendandburns** [comment]
You'd have to look through the swagger (or how the code generator handles sub resources)

Status is a sub-resource for Deployment.

**Comment by ZP-AlwaysWin** [comment]
hi @brendandburns 
I know status is a sub-resource for Deployment.

But what I don't understand is that these two methods clearly return to the same class. Why do we need to use two methods? I don't see any difference in the use of these two methods.

According to the naming rules of this readNamespacedDeploymentStatus  function, shouldn't it return this V1DeploymentStatus  class for difficulty?
