### ISSUE TITLE
Generating Client from Config Home Does Not Work

### ISSUE THREAD

**Issue by nprabala** [kubernetes-client/java#722]
I'm running the code from the https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/BatchV1Api.md for creating a namespaced job. When I do that, I get an error: io.kubernetes.client.ApiException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:443

For reference, the code from y'all's doc is below:

```
ApiClient defaultClient = Configuration.getDefaultApiClient();

// Configure API key authorization: BearerToken
ApiKeyAuth BearerToken = (ApiKeyAuth) defaultClient.getAuthentication("BearerToken");
BearerToken.setApiKey("YOUR API KEY");
// Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
//BearerToken.setApiKeyPrefix("Token");

BatchV1Api apiInstance = new BatchV1Api();
String namespace = "namespace_example"; // String | object name and auth scope, such as for teams and projects
V1Job body = new V1Job(); // V1Job | 
String pretty = "pretty_example"; // String | If 'true', then the output is pretty printed.
String dryRun = "dryRun_example"; // String | When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
String fieldManager = "fieldManager_example"; // String | fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
try {
    V1Job result = apiInstance.createNamespacedJob(namespace, body, pretty, dryRun, fieldManager);
    System.out.println(result);
} catch (ApiException e) {
    System.err.println("Exception when calling BatchV1Api#createNamespacedJob");
    e.printStackTrace();
}
```

I suspect this has something to do with the cluster config file, since the client is supposed to track that down automatically, starting by looking at KUBECONFIG, then HOME/.kube/config

I don't have KUBECONFIG, but there is a file at HOME/.kube/config with a valid server ip entry. I'm running a Minikube cluster that I'm trying to talk to, and it's up. Kubectl commands also work as expected.

Any thoughts? Not sure what the issue could be. Wondering if it's related to #668

**Comment by brendandburns** [comment]
You need to setup the default client first, look at the sample code here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/Example.java#L34

That should pick up your kubeconfig file.

**Comment by nprabala** [comment]
Ah, thank you. Added the lines there, then wrapped it all in a try catch, and that fixed the problem. Thank you!
