### ISSUE TITLE
Recommended values for resync period?

### ISSUE THREAD

**Issue by shakeelrao** [kubernetes-client/java#725]
I am building an Informer to watch Pods across all namespaces and was wondering if there are recommended values for the Informer resync period. From my basic understanding, the resync period essentially tells the Informer to re-list and cache the state of the objects in the cluster, right? 

In addition, is there a difference between the Informer resync period and the ResourceEventHandler resync period?

**Comment by yue9944882** [comment]
hey @shakeelrao, that's a good question. for the record, the informer in this library works exactly the same as the one in the official go library, so basically all the Q&A around client-go's informer also applies here. (vice versa)

> From my basic understanding, the resync period essentially tells the Informer to re-list and cache the state of the objects in the cluster, right?

no, the `resyncPeriod` you pass in to build either informer or informer-factory doesn't make you do any re-list/watching (the re-list/watching is actually triggered by a server-side timeout from kube-apiserver on a 30~60 mins basis). inside the informer, we push all the receiving watch events from list/watching to a queue (called DeltaFIFO), and the so-called "resync" works by locking the queue until it gets empty to avoid unbounded growth of queue length. __[1]__ the queue will be "resync"ing every `resyncPeriod` iff any of the registered event-handlers is ready for that. the re-list/watching, which you say, is costy for larger clusters, so we are supposed to the keep the watch connection as long as we can. anyway, the default `resyncPeriod` is basically working for most cases.

> In addition, is there a difference between the Informer resync period and the ResourceEventHandler resync period?

yes, they're different but connected. this resync period only applies to a single event-handler. an event handler gets ready every resync period. plz refer to __[1]__.

**Comment by shakeelrao** [comment]
Thank-you for the detailed explanation @yue9944882! I noticed the `DefaultSharedIndexInformer#addIndexer` is unimplemented. As a work around, I'm using one of the public constructors of `DefaultSharedIndexInformer` to pass in a `cache` that has the appropriate index function I need. Is it possible to leverage create a `Controller` given a `DefaultSharedIndexInformer`? 

`ControllerBuilder` seems to rely on `SharedInformerFactory` to create a preconfigured `DefaultSharedIndexInformer`, so I can't inject my own (unless `addIndexers` is implemented, of course).

**Comment by yue9944882** [comment]
>  so I can't inject my own (unless addIndexers is implemented, of course).

makes sense, will send a pull to implement that. thanks for reporting.

**Comment by shakeelrao** [comment]
Thanks! Do you know where I can find the logic that detects the timeout, re-lists objects and starts a new watch? 

It would be a good idea to have some documentation somewhere for this, so that users of `Watch` class can implement similar functionality.
