### ISSUE TITLE
AppsV1Api.listNamespacedDeployment()   io.kubernetes.client.ApiException: Forbidden

### ISSUE THREAD

**Issue by feiainan** [kubernetes-client/java#726]
`AppsV1Api appApi = new AppsV1Api();
		V1DeploymentList listNamespacedDeployment = appApi.listNamespacedDeployment("default", "true", null, null, null, null, null, null, null);`

this code runs with an error: io.kubernetes.client.ApiException: Forbidden
but using CoreV1Api is fine
Everything about AppsV1Api is problematic

**Comment by brendandburns** [comment]
If you print `ApiException.getResponseBody()` you may get some details that help...

**Comment by feiainan** [comment]
> If you print `ApiException.getResponseBody()` you may get some details that help...

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "deployments.apps is forbidden: User \"system:node:10.54.252.60\" cannot list resource \"deployments\" in API group \"apps\" in the namespace \"default\"",
  "reason": "Forbidden",
  "details": {
    "group": "apps",
    "kind": "deployments"
  },
  "code": 403
}

Emmm
I am this user does not have permission?

**Comment by yue9944882** [comment]
`system:nodes` cluster-role is special, kube-apiserver doesn't reload that on update. it's recommended to use service-account to access the cluster otherwise instead of mounting kubelet's kubeconfig into the container.

**Comment by brendandburns** [comment]
I'm going to close this, because the question is answered. Please include the command `/reopen` in your comment if you want to reopen this issue.
