### ISSUE TITLE
listPodForAllNamespaces() argument list differs in KubeConfigFileClientExample.java

### ISSUE THREAD

**Issue by seongwon-kang** [kubernetes-client/java#734]
```
V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null);
```
it takes 8 nulls in original file, but actually takes 9 nulls.

**Comment by seongwon-kang** [comment]
Maven Dependency:
```
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java</artifactId>
    <version>5.0.0</version>
    <scope>compile</scope>
</dependency>
```
in `README.md`, there are 9 nulls, too. but CI fails?

**Comment by brendandburns** [comment]
This changed in `6.0.1` We should consider versioning our examples, but for now you can look at the `5.0.0` tag:

https://github.com/kubernetes-client/java/tree/client-java-parent-5.0.0

Closing, since there isn't anything to do here.
