### ISSUE TITLE
More user-friendly client SDK interface 

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#736]
the generated client sources `*Api.java` has a long list of parameters hence hard for users to use. we can provide a more user-friendly generic client interface into the extended module. 

/assign

**Comment by yue9944882** [comment]
1. group looong list of parameters into {Get,List,Create,Delete,Patch,Update}Options
2. seperate a watch api method from list
3. factor out {Get,List,Create,Delete,Patch,Update}Response to fix the remaining issues from generated class: #86(Delete exception)

**Comment by brendandburns** [comment]
This is all generated, how do you propose doing this with respect to generated code?

**Comment by yue9944882** [comment]
i just send #738 to reflect my initial designs, PTAL
