### ISSUE TITLE
Problems w/ automatic client inside a cluster...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#74]
Reported by a user:

Hey everyone! I am having an issue running the new java-client inside a cluster. I am using
```java
ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);
```
to acquire a client, which works locally, but I get this when the code is executed inside a cluster:
```java
java.lang.RuntimeException: No OAuth2 authentication configured!
```

**Comment by frankreno** [comment]
I am having this same issue.  Is there a workaround/fix?

**Comment by brendandburns** [comment]
The workaround/fix would be to land a kubeconfig in the Pod and use that directly...

But I should be able to get this fixed this evening...

--brendan



________________________________

**Comment by brendandburns** [comment]
@frankreno fix is here:

https://github.com/kubernetes-client/java/pull/75
