### ISSUE TITLE
module(client-java) and module(client-java-extended) can merge to one module??

### ISSUE THREAD

**Issue by rjbhewei** [kubernetes-client/java#747]
rt

**Comment by brendandburns** [comment]
I don't think we want to do this, because if someone just wants the simple client (`client-java`) they shouldn't be required to take the advanced client `client-java-extended`

Closing this issue, feel free to use `/reopen` to reopen if there's additional feedback. Thanks

**Comment by rjbhewei** [comment]
https://github.com/kubernetes-client/java/issues/628

"informer  support pagination"  I need page from  client-java-extended module and informer form client-java module，

how can i do?   create new module ?

**Comment by brendandburns** [comment]
@rjbhewei can't you just import both modules? Is this related to #744
