### ISSUE TITLE
Is there any api corresponding to top command?

### ISSUE THREAD

**Issue by udit0612** [kubernetes-client/java#756]
I wants to run a top command

kubectl top nodes

My output should be like this
```

NAME           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
k8s-master     74m          3%     2666Mi          65%
worker-node1   924m         92%    1266Mi          27%
```
How can i achieve these i didn't see any option of top command in the api

**Comment by yue9944882** [comment]
it's a dup of https://github.com/kubernetes-client/java/issues/675

**Comment by brendandburns** [comment]
Closing as duplicate. tl; dr; is "no, `top` is a combination of a bunch of API calls" there are more details in #675
