### ISSUE TITLE
KubeConfigFileClientExample failed to run if user forgets to change the file path to the actual KubeConfig path

### ISSUE THREAD

**Issue by gangchen03** [kubernetes-client/java#759]
When testing the `KubeConfigFileClientExample` example as-is:
```
mvn exec:java -Dexec.mainClass="io.kubernetes.client.examples.KubeConfigFileClientExample"
```
The execution failed with error:
```
java.io.FileNotFoundException: ~/.kube/config (No such file or directory)
```
Java runtime can't interpret the userhome directory `~` properly, suggest change the default code 
https://github.com/kubernetes-client/java/blob/004a28ab2031c15f2d67e3cc2dd96a352aca9195/examples/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java#L39
as:
```
String kubeConfigPath = System.getProperty("user.home") + "/.kube/config";
```

**Comment by yue9944882** [comment]
/kind bug
/assign

thanks for reporting this

**Comment by kshpak** [comment]
The proposed solution looks better than it is now
