### ISSUE TITLE
How to use patch to add multiple data

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#760]
I refer to this example and write the code to add labels.
https://github.com/kubernetes-client/java#example

```
static String jsonPatchDeploymentStr =
            "[{\"op\":\"add\",\"path\":\"/metadata/labels/name\",\"value\":\"moons\"}]";

appsV1Api.patchNamespacedStatefulSet("test-sts","default",new V1Patch(jsonPatchDeploymentStr),null,null);
```
**Before modification**
![image](https://user-images.githubusercontent.com/23489782/67634237-294afe00-f8f4-11e9-8018-dd93846cf181.png)

**After modification**
![image](https://user-images.githubusercontent.com/23489782/67634257-6d3e0300-f8f4-11e9-8dae-5c265e219d9b.png)

Now, I have a question: can I add this multiple labels  through patch?

**Comment by ZP-AlwaysWin** [comment]
/assign @yue9944882 
hi @yue9944882  excuse me。
Because of your code example, do you have any good suggestions?

Thanks

**Comment by yue9944882** [comment]
>  "[{\"op\":\"add\",\"path\":\"/metadata/labels/name\",\"value\":\"moons\"}]";

as you see the patch content is an array, you are free to add another "add"-op entry to make that work

**Comment by ZP-AlwaysWin** [comment]
> > "[{"op":"add","path":"/metadata/labels/name","value":"moons"}]";
> 
> as you see the patch content is an array, you are free to add another "add"-op entry to make that work

Thank you for your reply，I will use this method。At first, I thought there would be some simple way。

There is also a question: do custom resources CRD not support this way of patch?

```
public static final String PATCH_FORMAT_STRATEGIC_MERGE_PATCH = "application/strategic-merge-patch+json";

```

I use the `PATCH_FORMAT_STRATEGIC_MERGE_PATCH` to patch ，get a error.

```
{
    "kind":"Status",
    "apiVersion":"v1",
    "metadata":{

    },
    "status":"Failure",
    "message":"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json",
    "reason":"UnsupportedMediaType",
    "code":415
}
```

**Comment by cizezsy** [comment]
I think you can use some library like [zjsonpatch](https://github.com/flipkart-incubator/zjsonpatch) to generate JSON-Patch format patches at runtime...

**Comment by yue9944882** [comment]
> public static final String PATCH_FORMAT_STRATEGIC_MERGE_PATCH = "application/strategic-merge-patch+json";

yes, the library cant craft patch content for you :) the format you pasted above is json-patch, while you're setting strategic-merge-patch format as the content-type.

**Comment by ZP-AlwaysWin** [comment]
> > public static final String PATCH_FORMAT_STRATEGIC_MERGE_PATCH = "application/strategic-merge-patch+json";
> 
> yes, the library cant craft patch content for you :) the format you pasted above is json-patch, while you're setting strategic-merge-patch format as the content-type.

No,When I use this format, 
```
public static final String PATCH_FORMAT_STRATEGIC_MERGE_PATCH = "application/strategic-merge-patch+json";

```
my patch content is like this

```
static String jsonPatchLbCrdStr1 = "{\n"
            + "    \"spec\": {\n"
            + "             \"backends\": [\n"
            + "                    {\n"
            + "                        \"name\": \"sts-0\",\n"
            + "                        \"weight\": 200\n"
            + "                    }\n"
            + "                ]\n"
            + "    }\n"
            + "}";
```
but I still get a error
```
{
    "kind":"Status",
    "apiVersion":"v1",
    "metadata":{

    },
    "status":"Failure",
    "message":"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json",
    "reason":"UnsupportedMediaType",
    "code":415
}
```

so， I want to know CRD if don't support the type of patch

```
    public static final String PATCH_FORMAT_STRATEGIC_MERGE_PATCH = "application/strategic-merge-patch+json";

```

**Comment by yue9944882** [comment]
CRD doesn't support strategic-merge-patch (SMP), others should work for you https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility

**Comment by ZP-AlwaysWin** [comment]
> CRD doesn't support strategic-merge-patch (SMP), others should work for you https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility

Thanks your help。
