### ISSUE TITLE
Using microk8s - Can't find how to enable extensions

### ISSUE THREAD

**Issue by giorgos-apo** [kubernetes-client/java#763]
I am using the kubernetes client api to access my kubernetes cluster. 

I 've been trying to find out how to execute commands like:
`microk8s.enable dashboard`.

The problem seems to be that I can't enable a service that already exists and I can only create one from scratch.

 I mean, the dashboard extension belongs the 'kube-system' namespace. So, I have tried to create a namespace called "kube-system" and then a namespaced service called "dashboard". However, this is not proper, since what I want to do actually is to enable an existing service.

To conclude, as mentioned in the micok8s docs, there are some [addons](https://microk8s.io/docs/addons) that need to be enabled.

Is there a way to do so?

**Comment by yue9944882** [comment]
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dashboard

not really familiar w/ microk8s. but there's a manifest of required resources to set up dashboard provided by upstream kubernetes. you're free to load and create those resources into the cluster w/ this SDK project.

>  I have tried to create a namespace called "kube-system" and

that's odd, `kube-system` namespace is supposed to be created when the cluster is initialized. you dont need to set it up manually

**Comment by giorgos-apo** [comment]
Thanks for the answer!

> that's odd, kube-system namespace is supposed to be created when the cluster is initialized. you dont need to set it up manually

Actually you 're right. It was a wrong move.

The idea I 've just come up with, is to find the yaml file of the dashboard deployment and use it to create deployment, puting the yaml file as the "body" parameter here:

`createNamespacedDeployment(namespace, body, pretty, dryRun, fieldManager)`

**Comment by yue9944882** [comment]
> createNamespacedDeployment(namespace, body, pretty, dryRun, fieldManager)

i think that's one way to do it but not the best, i would recommend using server-side apply https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply to do the work, the create api call is not idempotent 

idempotent

**Comment by giorgos-apo** [comment]
Thank you, I will check it out! It looks like the approach I was describing above though

**Comment by brendandburns** [comment]
I believe this issue is resolved, thus I'm closing it. If there is more info needed please use `/reopen` to reopen the issue.

Thanks!
