### ISSUE TITLE
Clean up outside collaborators

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-client/java#764]
Hey there @kubernetes-client/java-admins ,

One of the github-admins here. -- We have a [longstanding issue] on cleaning up outside collaborators, and are now actively planning on removing them on December 1st.

At this point, people that are actively contributing to the Kubernetes project should be promoted to [org members][mem], and any repo specific permissions should be managed through their associated configuration in [kubernetes/org].

With that in mind, the following people are listed as outside collaborators:

- @cliveseldon 
- @iocanel 
- @kondapally1989 

Of those, @cliveseldon and @kondapally1989  have been active and I'd encourage [applying for membership to the kubernetes-client org][mem]. 😄 

@iocanel has been inactive (<5 [devstats] recorded contributions in the past year across all Kubernetes orgs), and I'd opt for removal from direct repo permissions. 

Just a general reminder, not having direct permissions **does not stop** folk from contributing. It just means they'd have less permissions (would need  `/ok-to-test` on PRs etc).

If you have any questions or comments, please don't hesitate to ask in here or feel free to poke me in slack 👍 

Thanks!

assigning java-admins:
/assign @brendandburns @mbohlool 

/sig contributor-experience
/priority important-soon

[longstanding issue]: https://github.com/kubernetes/community/issues/3178
[mem]: https://github.com/kubernetes/community/blob/master/community-membership.md#member
[kubernetes/org]: https://github.com/kubernetes/org
[devstats]: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All

**Comment by brendandburns** [comment]
@mrbobbytables

What is the specific request here? It's unclear if you're planning on removing people yourself and this is an fyi, or if there is an action for the admins requested.

fwiw, while we're at it, @mbbohool has largely retired from involvement with this repo.

**Comment by mrbobbytables** [comment]
@brendandburns If no action is taken, we'll remove on December 1st.

For the active folk, they should apply for org membership in kubernetes-client.

Ideally this is a great time to update the [various groups](https://github.com/kubernetes/org/blob/master/config/kubernetes-client/org.yaml) and manage them through peribolos instead of through the individual repo collaborator settings, but the bigger priority is to ensure everyone that has repo permissions is a member of the associated org.

**Comment by brendandburns** [comment]
thanks, we'll make sure the relevant folks join through the org repo prior to 12/1.

**Comment by mrbobbytables** [comment]
Permissions have been cleaned up. 

@cliveseldon @kondapally1989 -- If you need access --  Please go ahead and file for [org membership to the kubernetes-client org](https://github.com/kubernetes/community/blob/master/community-membership.md#member) and we can pursue adding you the appropriate groups for repo permissions 👍

If you have any questions, please don't hesitate to reopen or ping me on slack.

Thanks!
/close
