### ISSUE TITLE
Gradle plugin 6.0.1

### ISSUE THREAD

**Issue by nprabala** [kubernetes-client/java#765]
import io.kubernetes.client.extended.controller.reconciler.Request;
Cannot resolve symbol 'extended'

UPDATE: Realized the issue is that I was using 5.0.0 in my dependencies, and extended requires release 6.0.0+. I switched to 6.0.1 in my dependencies, but I'm running into the same error. Does the plugin support the extended module in the 6.0.1 release? And if not, is there a way for it to do so?

**Comment by brendandburns** [comment]
It should? But honestly I don't have any experience w/ Gradle, we've only used Maven in this project.

**Comment by nprabala** [comment]
The README says to use 5.0.0 for gradle but 6.0.1 also exists? Which version is currently supported? Who is supporting the kubernetes gradle plugin?

**Comment by yue9944882** [comment]
you're required to add extended dependency to your pom:

```xml
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java-extended</artifactId>
    <version>6.0.1</version>
</dependency>
```

**Comment by nprabala** [comment]
Applying the dependency above in gradle: 

compile 'io.kubernetes:client-java-extended:6.0.1'
classpath('io.kubernetes:client-java-extended:6.0.1')


That worked for me. Thank you!
