### ISSUE TITLE
CustomObjectsApi Using yaml creation error, can give an example?

### ISSUE THREAD

**Issue by cosolar** [kubernetes-client/java#766]
```
 CustomObjectsApi apiInstance = new CustomObjectsApi();
Object result = apiInstance.createNamespacedCustomObject("monitoring.coreos.com", "v1", "monitoring", "prometheusrules", "ops-prometheus-rules", jsonObject.toString());
System.out.println(result);
```

**Comment by yue9944882** [comment]
will the `YamlExample` under `Basics` section help? https://github.com/kubernetes-client/java#example

**Comment by cosolar** [comment]
`java.io.IOException: Unknown apiVersionKind: monitoring.coreos.com/v1/PrometheusRule known kinds are: {v1/Ser-----
at io.kubernetes.client.util.Yaml.modelMapper(Yaml.java:490)
	at io.kubernetes.client.util.Yaml.load(Yaml.java:184)
	at io.kubernetes.client.util.Yaml.load(Yaml.java:172)

`

**Comment by cosolar** [comment]
yue9944882/java-model-gen Download very slow
`error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/07/07c8579cc40a5c7f09add907e55870bfdbaebd6c4cdca204fd1892f7e4f72cd8/data?verify=1572450917-CpD3jJH0srTAUC7df8tEEuTAbUQ%3D: read tcp 172.17.8.17:50370->104.18.124.25:443: read: connection reset by peer
`
[reference](https://github.com/kubernetes-client/java/blob/0e36e8a88ed733713822dddbb2e629c69e994a0e/docs/generate-model-from-third-party-resources.md#best-practice-to-manipulate-java-models)

**Comment by cosolar** [comment]
```shell
[root@k8s-master ~]# docker pull yue9944882/java-model-gen
Using default tag: latest
latest: Pulling from yue9944882/java-model-gen
f17d81b4b692: Pulling fs layer 
93c48fea9208: Pulling fs layer 
f17d81b4b692: Retrying in 1 second 
f17d81b4b692: Retrying in 1 second 
``` @yue9944882

**Comment by cosolar** [comment]
```
[root@k8s-master ~]# docker pull yue9944882/java-model-gen
Using default tag: latest
latest: Pulling from yue9944882/java-model-gen
f17d81b4b692: Pulling fs layer 
93c48fea9208: Pulling fs layer 
f17d81b4b692: Retrying in 1 second 
f17d81b4b692: Retrying in 1 second 

```
@yue9944882

**Comment by yue9944882** [comment]
> f17d81b4b692: Retrying in 1 second 

am afraid we cant really help you w/ local networking issue 🙂

**Comment by brendandburns** [comment]
The YAML loading code doesn't know how to load custom objects. You would need to manually update the relevant mapping yourself using the function here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Yaml.java#L149

I'm going to close this as I don't think there is much more we can do. Please feel free to re-open with the `/reopen` command if you have more info or need more help.
