### ISSUE TITLE
how to force delete pod?

### ISSUE THREAD

**Issue by zhangzerui20** [kubernetes-client/java#770]
Use kubectl to force the removal of the pod:
kubectl delete pod xxx  --force --grace-period=0

Can we do this with kubernetes-client?

**Comment by yue9944882** [comment]
set a zero `gracePeriodSeconds` on the delete call will do the work

https://github.com/kubernetes-client/java/blob/2e95de4b83da764884b648bf085d9edf469c65e0/kubernetes/src/main/java/io/kubernetes/client/models/V1DeleteOptions.java#L41-L42

**Comment by brendandburns** [comment]
Closing this as the question is answered. Please use the `/reopen` command if you want to reopen.
