### ISSUE TITLE
 Expected HTTP 101 response but was '404 Not Found'

### ISSUE THREAD

**Issue by ghost** [kubernetes-client/java#774]
i have run the example of execExample and i got this error

**Comment by NehalAbdelmegeed** [comment]
Me too i have run the same example and get this error too

**Comment by brendandburns** [comment]
Chance are that the pod doesn't exist in your cluster. You may need to change the code to use the name of a pod that exists in your cluster.

See the flag here:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java#L49

**Comment by brendandburns** [comment]
Closing this as I believe the question is answered. Please use `/reopen` comment command if anything more is needed.
