### ISSUE TITLE
deleteCollectionNamespacedDeployment() can not delete pods

### ISSUE THREAD

**Issue by ylvmw** [kubernetes-client/java#779]
I tried to delete a deployment with the API, the deployment could be deleted but the associated pods could not be deleted. Please see my code below:

```
        ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader("kubeconfig-path"))).build();
        AppsV1beta1Api appApi = new AppsV1beta1Api(client);
        V1Status status = appApi.deleteCollectionNamespacedDeployment("default", null, null, "metadata.name=" + name, null, null, null, null, null);
        System.out.println(status);
```

Could you please let me know if anything I was wrong with or if it it a bug?

**Comment by sarveshkaushal** [comment]
This is reproducing for me too. Tried with both v1beta1 and v1.

**Comment by sarveshkaushal** [comment]
I was able to repro this using cURL too. The following curl in my local just deletes the deployment and doesn't terminate pods:
`curl -k -X DELETE -H 'Accept: application/json' 'http://127.0.0.1:8001/apis/apps/v1beta1/namespaces/default/deployments?pretty=true&fieldSelector=metadata.name%3DdeploymentName'`

However following cURL works fine. It deletes the deployment and terminates the pods as well:
`curl -k -X DELETE -H 'Accept: application/json' 'http://127.0.0.1:8001/apis/apps/v1/namespaces/default/deployments?pretty=true&fieldSelector=metadata.name%3DdeploymentName`

Only difference is version v1 and v1beta1

**Comment by ylvmw** [comment]
Found a workaround, we need to delete the pods before deleting the deployment:
```
String kubeConfigPath = System.getProperty("user.home") + "/.kube/config";
ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();
AppsV1Api appApi = new AppsV1Api(client);
String namespace = "default";
String name = "apache";
V1Patch patch = new V1Patch("[{\"op\": \"replace\", \"path\": \"/spec/replicas\", \"value\": 0}]");
appApi.patchNamespacedDeploymentScale(name, namespace, patch, null, null, null, null);
V1Status status = appApi.deleteCollectionNamespacedDeployment(namespace, null, null, "metadata.name=" + name, null, null, null, null, null);
```

**Comment by sarveshkaushal** [comment]
Please take a look at https://github.com/kubernetes/kubernetes/issues/85310
