### ISSUE TITLE
Possible to Filter "List Events" in Event Handler?

### ISSUE THREAD

**Issue by shakeelrao** [kubernetes-client/java#780]
I'm using a `DefaultSharedIndexInformer` and `ResourceEventHandler` to process events. Is it possible to filter events that come from the "list" stage of the "list and watch"? 

Specifically, the only events I care about are watch events (i.e. everything after the initial list). From looking at the code, it seems like every event is processed by the event handler. Just wondering if there's a way to do this natively or if I can set-up some filtering logic in my event handler somehow...

**Comment by brendandburns** [comment]
I believe #757 is adding filtering, please take a look and see if that resolves your issue.

**Comment by yue9944882** [comment]
@bsherman yes, that's by-design in the informer, it broadcasts initial events on the first round of "list"ing. you can hold your event-handler until the cache is fully synced. you might probably feel like take a look at how https://github.com/kubernetes-client/java/blob/cbc1d385dfa02da38e07e4b22498971b7b464680/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java#L91-L93 works.

**Comment by shakeelrao** [comment]
@yue9944882 Thanks for the advice! I ended up not having to filter the "list" stage after all.
