### ISSUE TITLE
streamNamespacedPodLog SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by marvel-007** [kubernetes-client/java#781]
I have read some logs and printed them to the console, but when there is no latest log output, there will be a timeout exception. How can I prevent the timeout? When there is new log data to continue reading and output, the version I use is client. -java-5.0.0 k8s: 1.15.5

**Comment by yue9944882** [comment]
is that a network-level or library-level timeout? the latter can be solve by overriding timeouts to zero in okhttp client:

https://github.com/kubernetes-client/java/blob/9fb6a312085f0fefeea232f0ae5cca3399ae2566/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java#L31

**Comment by brendandburns** [comment]
Though it's generally the case that your network will timeout somewhere in the absence of data (e.g router, etc) so it's worth handling and reconnecting if the logs connection drops.

**Comment by marvel-007** [comment]
Thank you very much, solved my problem after set  .setReadTimeout(0, TimeUnit.SECONDS);
