### ISSUE TITLE
How to create pull secrets?

### ISSUE THREAD

**Issue by zhangzerui20** [kubernetes-client/java#782]
Hey there,

is it possible to create k8s pull secrets using this api equivalent to this command line?

kubectl create secret docker-registry --dry-run=true test --docker-server=null --docker-username=test --docker-password=lol -o yaml > docker-secret.yaml

Thanks for each contribution!

**Comment by brendandburns** [comment]
Yes, you need the `createNamespacedSecret(...)` method call in the v1 API.

That command is a little specialized. You'll probably need to look at the implementation in the kubectl code base.

**Comment by brendandburns** [comment]
If you need to reopen please use the `/reopen` command
