### ISSUE TITLE
" io.kubernetes.client.ApiException: Unauthorized" with KubeConfig in Non-Cluster

### ISSUE THREAD

**Issue by jayaise** [kubernetes-client/java#783]
Tried below code but getting Unauthorized exception:
    String kubeConfigPath = "C://Users//admin//.kube//config";
    ApiClient client =      ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();

    Configuration.setDefaultApiClient(client);
    CoreV1Api api = new CoreV1Api(client);
    V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
    for (V1Pod item : list.getItems()) {
      System.out.println(item.getMetadata().getName());
    }

Getting exception from for api call listPodForAllNamespaces as shown below,
Exception in thread "main" io.kubernetes.client.ApiException: Unauthorized
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:886)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:802)
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18720)
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18698)
	at Kubectl.main(Kubectl.java:51)

**Comment by brendandburns** [comment]
If you print `ApiException.getResponseBody()` you should get more details about why authorization is failing.

**Comment by yue9944882** [comment]
can you verify if your kubeconfig is valid?

**Comment by jayaise** [comment]
Hi,
My Kubeconfig is like below format, let me know if this correct:

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
	<<certificate-authority encoded base64 data string>>
    server: https://kaas-admin.com
  name: kaas-admin
contexts:
- context:
    cluster: kaas-admin
    user: admin1
  name: kaas-admin
current-context: kaas-admin
kind: Config
preferences: {}
users:
- name: admin1
  user:
    client-certificate-data: 
	<<client-certificate encoded base64 data string>>
    client-key-data: 
	<<client-key-data encoded base64 data string>>

**Comment by jayaise** [comment]
I generated client.pem(This contains client-certificate-data base64 decoded string) and key.pem(This contains client-key-data base64 decoded string) and tried with curl command by passing these 2 certificate files it works,
curl --request GET https://... --cert client.pem --key key.pem --insecure
This works fine

**Comment by jayaise** [comment]
Any update on this

**Comment by falken** [comment]
I have a similar problem, Except I get an exception of 

"i.k.c.e.leaderelection.LeaderElector - Error retrieving resource lock kube-system/leader-election as javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed" 

Unless I use setVerifyingSsl(false). Then I just get the Authorization error. 

I use the same config file with kubectl and it seems to work fine.

Config.fromConfig(KubeConfig.loadKubeConfig(new FileReader(fileName)))

**Comment by yue9944882** [comment]
the error seems complaining the CA cert is not properly loaded. does your kubeconfig have a valid `certificate-authority-data` property? or it's skipped by setting `insecure-skip-tls-verify: true`?

**Comment by yue9944882** [comment]
@jayaise is your kubeconfig working w/ kubectl?

**Comment by brendandburns** [comment]
Closing this due to no response. Please use the `/reopen` command as necessary.
