### ISSUE TITLE
Content type "text/html; charset=utf-8" is not supported for type: class io.kubernetes.client.models.V1NamespaceList

### ISSUE THREAD

**Issue by riemann77** [kubernetes-client/java#784]
i am getting this error only when i am using token based authentication , it is working fine when i am reading the config file locally from my computer.

**Comment by brendandburns** [comment]
I don't think that you're actually talking to a kubernetes server. It doesn't ever serve html content.

**Comment by yue9944882** [comment]
>  It doesn't ever serve html content.

+1 correct

**Comment by riemann77** [comment]
my bad it is a spring-boot issue

**Comment by brendandburns** [comment]
I'm closing this issue, since I don't believe it is a client problem and it has been 1 week without a response. Please use the `/reopen` comment command if you need to reopen the issue for any reason.
