### ISSUE TITLE
Can't connect to cluster from pod in version 7.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by goodidea-kp** [kubernetes-client/java#788]
error: io.kubernetes.client.ApiException: Forbidden

Based on your example InClusterClientExample.java it works well with minikube, but the code can't connect in prod.

Please advise how to fix it.
Also, doc never says the difference in configuration between minikube and ".kube" approach vs InCluster approach

**Comment by brendandburns** [comment]
This is very likely a problem with the Pod Service Account and RBAC.

See:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account

For more details.

Closing, since the question is answered, please use the `/reopen` command if more assistance is required.
