### ISSUE TITLE
Support Watch operations

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#8]

**Comment by brendandburns** [comment]
Have you figured out what to do for WebSockets? I've started writing a utility library, let me know if we're conflicting in our efforts...

**Comment by mbohlool** [comment]
I had some thoughts, I need to modify code generation templates to support watch. Also need to modify preprocessing script to add required flags for the new templates. Will send a PR when it is ready.

**Comment by mbohlool** [comment]
btw, Watch should not need WebSockets. That is needed for other advance operations such as attach, exec, etc.

**Comment by brendandburns** [comment]
Ah, yes, you are correct, not needed for watch...
