### ISSUE TITLE
statefulset rolling update issue

### ISSUE THREAD

**Issue by db-vmw** [kubernetes-client/java#80]
Hi,
'm following the document: " https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets " for updating my statefulset to use new image version (rolling update).
1. On issuing the command: 
kubectl patch statefulset my_statefulset_name -p '{"spec":{"updateStrategy":{"type":"RollingUpdate"}}}'
Output: my_statefulset_name patched.

2. On issuing the command: 
kubectl patch statefulset my_statefulset_name --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"my_image"}]'
Output: my_statefulset_name patched

But, nothing happens, I don't see any pods recreating with the new image mentioned. What's happening here? Where to find the logs on what's going wrong here? kubectl describe pod was not helpful.

Note: If I manually delete the pods, the new pods comes up with new image specified as part of patch command. Is this the expected behavior?

Yaml file refers to apiVersion: apps/v1beta1

**Comment by lwander** [comment]
Hey @db-vmw - if I'm understanding correctly you're trying to get this behavior using only `kubectl patch`, right? If that's the case this question might be better suited for the [kubernetes repo](github.com/kubernetes/kubernetes), since this repo here deals with just the java client for the kubernetes API. 

But let's see if we can figure this out. Does the stateful set reflect both edits you made after you issued those two commands? Also, does the actual value for the image change? e.g. what was the value for the image before you changed it to `my_image`?

**Comment by db-vmw** [comment]
Hi @lwander, thanks for pointing me to right repo. 
House would I know if my edits are reflected? I tried, kubectl edit statefulset my_statefulset_name and I don't see the newly updated image name. 
But, I do see the pods updating to new image (my_image) if I delete them (since these are replicas).

**Comment by db-vmw** [comment]
Please excuse my typo error

**Comment by lwander** [comment]
Does `kubectl get statefulset my_statefulset_name` show the updated image?

**Comment by db-vmw** [comment]
yeah, after running the command,
 `kubectl patch statefulset my_statefulset_name --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"my_image"}]`'  , I do see the stateful set my_statefulset_name updating with the new image ID 
(i.e. `kubectl describe statefulset my_statefulset_name` shows the "`my_image`" (new image specified). But, the pods doesn't update themselfs to the new image mentioned (my_image)

**Comment by lwander** [comment]
Sounds like it might be a bug - I think it's best to file this against the kubernetes repo.

**Comment by db-vmw** [comment]
Sure. Thank you @Iwander
