### ISSUE TITLE
Unable to find property 'JSONPath'

### ISSUE THREAD

**Issue by pattyphonemany691** [kubernetes-client/java#806]
We're currently creating a Custom Resource Definition in java from a yaml file. 
```
Yaml yaml = new Yaml();
V1beta1CustomResourceDefinition body = yaml.loadAs(new FileReader("crd.yaml"), V1beta1CustomResourceDefinition.class);
```
The yaml file contains a multiple `JSONPath fields`.
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mycrd
spec:
  additionalPrinterColumns:
  - JSONPath: value
    name: value
```
When loading the yaml file, the following snakeyaml exception is thrown:
```
Caused by: Cannot create property=JSONPath for JavaBean=class V1beta1CustomResourceColumnDefinition {
    jsONPath: null
    description: null
    format: null
    name: null
    priority: null
    type: null
}
 in 'reader', line 15, column 5:
```
```
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'JSONPath' on class: io.kubernetes.client.models.V1beta1CustomResourceColumnDefinition
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:189)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:178)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:285)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:209)
	... 23 more
```

We have found that if we change the `JSONPath` field to match the variable name defined in [V1beta1CustomResourceColumnDefinition](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1beta1CustomResourceColumnDefinition.java)
no errors are thrown and the CRD can be created by calling `apiExtensionsV1beta1Api().createCustomResourceDefinition(body, null, null, null);`
If the crd is manually created by running `kubectl apply -f crd.yaml` the file is successfully applied.

We have looked into modifying the `Yaml` constructor but have been unable to find any options that allows us to parse the `JSONPath` field. Is there a way to load the yaml file with the current casing for `JSONPath`?

**Comment by brendandburns** [comment]
Quick clarification quesiton:

Are you saying that if you change `JSONPath` to `jsONPath` it loads correctly?

Thanks

**Comment by pattyphonemany691** [comment]
If we update the yaml file to use `jsONPath` instead of `JSONPath` it successfully loads.

**Comment by pattyphonemany691** [comment]
The CRD that's created in the cluster does use the correct casing though when we update the crd.yaml file to use `jsONPath`. We see this when we reun `kubectl get crd mycrd -oyaml | less` and it shows `JSONPath`

**Comment by kyuoh125** [comment]
```
  public static final String SERIALIZED_NAME_JS_O_N_PATH = "JSONPath";
  @SerializedName(SERIALIZED_NAME_JS_O_N_PATH)
  private String JSONPath;

 @ApiModelProperty(required = true, value = "JSONPath is a simple JSON path, i.e. with array notation.")

  public String getJSONPath() {
    return JSONPath;
  }


  public void setJSONPath(String JSONPath) {
    this.JSONPath = JSONPath;
  }
  
```
We tried renaming the variable from `jsONPath` -> `JSONPath` in `V1beta1CustomResourceColumnDefinition.java` as shown above, this allowed Yaml to properly load our CRD file.

**Comment by yue9944882** [comment]
`jsONPath` looks odd anyway, will file a fix at the code-generator to correct the naming

**Comment by WywTed** [comment]
so, which version will resolve this problem, i have the same error with version 5.0. change 'JSONPath' to 'jsONPath' works.

**Comment by lin1005q** [comment]
Cannot create property=JSONPath for JavaBean=class V1beta1CustomResourceColumnDefinition

me too

**Comment by lin1005q** [comment]
@brendandburns
