### ISSUE TITLE
Can calling API generate history record?

### ISSUE THREAD

**Issue by wangyushuai** [kubernetes-client/java#821]
When updating patches through the API, no history is generated (reversion), how can I generate history?

**Comment by yue9944882** [comment]
guess what you're looking for is api auditing? that's where we records the history modifcation upon api resources. 

https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by wangyushuai** [comment]
> guess what you're looking for is api auditing? that's where we records the history modifcation upon api resources.
> 
> https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
非常感谢您的回复， 我的意思是 为什么我调用 API 进行Patch 更新，为什么有的时候会产生一个 revision, 有的时候却没有生成新的revision , 这让我很疑惑。

比如：Patch apis/apps/v1/namespaces/default/deployments/nginx-deployment, [{"op":"replace","path":"/spec/replicas","value":1}],    来调整 POD 数，有的时候产生了 revision ,有的时候又没有新的 revision;

又比如： Patch apis/apps/v1/namespaces/default/deployments/nginx-deployment/scale 好像不会产生 revision；

**Comment by wangyushuai** [comment]
@yue9944882

**Comment by brendandburns** [comment]
Assuming you mean the history done by `kubectl apply` then that is done in the client side `kubectl` code.

Starting w/ 1.16 there will be server-side apply which (I believe) should add the history on the server side.

Once that is supported in this library, I think it will work.

**Comment by wangyushuai** [comment]
> Assuming you mean the history done by `kubectl apply` then that is done in the client side `kubectl` code.
> 
> Starting w/ 1.16 there will be server-side apply which (I believe) should add the history on the server side.
> 
> Once that is supported in this library, I think it will work.

I mean that how I can get revision when I create a deployment  or update a deployment~? 
Thank you very much ! @brendandburns

**Comment by yue9944882** [comment]
i read that as, you are expecting "everytime you write/patch a deployment, there should be a revision bumping on its status". i think it's definitely a true statement if you:

T1: save the older revision R1
T2: patch/scale the deployment
T3: observe a revision bump R2 greater than R1

do you have a stable re-pro? btw, the issue should be transferred to `kubernetes/kubernetes` as it's out-of-scope of java SDK i suppose..

**Comment by wangyushuai** [comment]
> i read that as, you are expecting "everytime you write/patch a deployment, there should be a revision bumping on its status". i think it's definitely a true statement if you:
> 
> T1: save the older revision R1
> T2: patch/scale the deployment
> T3: observe a revision bump R2 greater than R1
> 
> do you have a stable re-pro? btw, the issue should be transferred to `kubernetes/kubernetes` as it's out-of-scope of java SDK i suppose..
Yes that's the meaning！

Here is what I am doing:

I want to record thr revision when I "everytime you write/patch a deployment", then I can rollback by revision,  but I can't found revision in result that interface returns,   or  the revison is not the latest in interface's result.

So, I want to know how you do these things ~

Thanks!!

**Comment by yue9944882** [comment]
it will take a span of time (depends on the load) for the controller-manager to finish processing your patch writes b/c the controller is running everything asynchronously. you can retry a few times until the revision is bumped at client-side if it doesnt refresh  i suppose..
