### ISSUE TITLE
Exception in thread "main" io.kubernetes.client.ApiException: Forbidden

### ISSUE THREAD

**Issue by icehehehe** [kubernetes-client/java#824]
I am using io.kubernetes --> client-java --> version --> 6.0.1
I can list pod information by using method listNamespacedPod 
but i cannot use createNamespacedPod.
Here is my code :
        ApiClient client = Config.fromConfig(ResourceUtils.getFile("classpath:")+"\\kubelet.conf");	    
        Configuration.setDefaultApiClient(client); 
        V1PodList list;	    
	    CoreV1Api api = new CoreV1Api();
	    V1Pod pod2 =
	        new V1Pod()
	            .metadata(new V1ObjectMeta().name("anotherpod"))
	            .spec(
	                new V1PodSpec()
	                    .containers(Arrays.asList(new V1Container().name("www").image("nginx"))));
//	    api.createNamespacedPod("default", pod2, null, null, null);
	    list =
	        api.listNamespacedPod("default", null, null, null, null, null, null, null, null);
	    for (V1Pod item : list.getItems()) {
	      System.out.println(item.getMetadata().getName());
	    }

And here is Error:
Exception in thread "main" io.kubernetes.client.ApiException: Forbidden
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPodWithHttpInfo(CoreV1Api.java:8318)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPod(CoreV1Api.java:8300)

The k8s version is 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Still facing the same problem

**Comment by brendandburns** [comment]
The kubeconfig file you're using doesn't have the right permissions. I suspect it's b/c it's the kubelet's config file.

See the docs here:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

For more info on RBAC.

Closing this issue since it isn't a problem with this library. Please use `/reopen` in a new comment if you want to reopen this issue for any reason.
