### ISSUE TITLE
How to get the exact occurrence time of watch event?

### ISSUE THREAD

**Issue by jhz1103** [kubernetes-client/java#825]
For example, i got a response from apiServer at 9:00 am of pod-modify, is that the exact time of happening? I found create-time and delete-time in the metadata, but nothing about the update-time, it there any way to get that information?

**Comment by yue9944882** [comment]
kubernetes doesnt explicitly track the update timestamp for you, while you can either find out the accurate happening time of the update requests by tailing the API audit log, or leverage those third-party tracing platform to achieve that https://github.com/kubernetes/enhancements/pull/650

**Comment by jhz1103** [comment]
Thanks
