### ISSUE TITLE
Twice  start informers in ControllerExample

### ISSUE THREAD

**Issue by andyyin** [kubernetes-client/java#828]
The first time

https://github.com/kubernetes-client/java/blob/744825e70e8b46037e305ff61839c208c60f4ccc/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java#L55

The second time

https://github.com/kubernetes-client/java/blob/744825e70e8b46037e305ff61839c208c60f4ccc/extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java#L46

**Comment by yue9944882** [comment]
yea that's a valid bug in the example.. is that resulting in other unexpected behavior?

**Comment by shakeelrao** [comment]
@andyyin calling `startAllRegisteredInformers` multiple times has no side effect, other than being redundant (see: https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java#L169).

**Comment by shakeelrao** [comment]
@andyyin calling `startAllRegisteredInformers` multiple times has no side effects:

https://github.com/kubernetes-client/java/blob/e96d8f6d33c15075b63802bf7bbaed4b0b4d47e2/util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java#L173-L176

While redundant, there should be no issues.
