### ISSUE TITLE
Exception when creating job

### ISSUE THREAD

**Issue by FANLIYANG-OPS** [kubernetes-client/java#829]
![image](https://user-images.githubusercontent.com/20119253/70620841-3da04b80-1c53-11ea-8f14-c504bf7e55ed.png)
 it's code : 
![image](https://user-images.githubusercontent.com/20119253/70620895-57419300-1c53-11ea-91b5-c9b9140093d6.png)
error message : 
![image](https://user-images.githubusercontent.com/20119253/70620948-6c1e2680-1c53-11ea-824a-e1ff77a6e842.png)
java-client need to Quantity , but K8S need string !

**Comment by yue9944882** [comment]
are you serializig w/ GSON? there's custom serializers registered for quantity types..

**Comment by brendandburns** [comment]
Closing due to no response. Please use `/reopen` to reopen if necessary.
