### ISSUE TITLE
In-cluster config builder does not work properly in an ipv6 cluster

### ISSUE THREAD

**Issue by liggitt** [kubernetes-client/java#839]
https://github.com/kubernetes-client/java/blob/cbc1d385dfa02da38e07e4b22498971b7b464680/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L206-L208

assumes a DNS name or ipv4 address... it does not work correctly with an ipv6 address (the ipv6 host must be wrapped in brackets)

**Comment by liggitt** [comment]
cc @thockin

**Comment by brendandburns** [comment]
Thanks for reporting, will send a PR.
