### ISSUE TITLE
Attach standardOutputStream not working

### ISSUE THREAD

**Issue by rawler** [kubernetes-client/java#847]
Several issues have been opened about this, to later be auto-closed.

I investigated this, and found the culprit to be "stdout=true" needs to be added to URL to activate stdout streaming. I suspect it was once the default, server-side, but now needs to be explicit.

For me, I fixed it temporarily by copying Attach.java to local file and applying this;

```
--- Attach.java.old	2020-01-07 14:19:53.819452472 +0100
+++ Attach.java	2020-01-07 14:20:28.055836186 +0100
@@ -59,6 +59,7 @@
 
   private String makePath(
       String namespace, String name, String container, boolean stdin, boolean tty) {
+    boolean stdout = true;
     return "/api/v1/namespaces/"
         + namespace
         + "/pods/"
@@ -66,6 +67,8 @@
         + "/attach?"
         + "stdin="
         + stdin
+	+ "&stdout="
+	+ stdout
         + "&tty="
         + tty
         + (container != null ? "&container=" + container : "");

```

In general I think maybe with the selection of three booleans for different streams, setting up Attach deserves a builder. If there is interest and agreement, I can make a PR.

**Comment by brendandburns** [comment]
A builder for Attach would be great! We'd welcome a PR (and for Exec too if you feel like it :)

Many thanks!
