### ISSUE TITLE
ControllerManager should wait for all informers synced before starting controllers

### ISSUE THREAD

**Issue by cizezsy** [kubernetes-client/java#850]
Currently, controller manager will start controllers immediately after starting informers. This might cause problems.

1. If we want to get multiple types of resources in reconciler from the local cache, we need to manually add `informer.hasSynced` to controller's `ReadyFuncs` to ensure informers of these type are synced. 
2. If those informers are not synced due to the network problem, we got this controller failed and have no way to know it except to look at the logs. 
3. The default `readyTimeout` is 30s, there is no interface exposed to configure it except cast `Controller` to `DefaultController`.(I am not sure if it is a good practice)

So, what do you think to wait for informers synced then starting controller? Thanks!

**Comment by yue9944882** [comment]
> 1. If we want to get multiple types of resources in reconciler from the local cache, we need to manually add informer.hasSynced to controller's ReadyFuncs to ensure informers of these type are synced.


we can add the `hasSynced` functions from multiple resources when building the controller. the function `withReadyFunc` doesnt "put" instead it "add". is that addressing you?

https://github.com/kubernetes-client/java/blob/a4384e8375ebf0c622a9882b7f71a9c9ed3eb462/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java#L91-L93

> 2. If those informers are not synced due to the network problem, we got this controller failed and have no way to know it except to look at the logs.

can you elaborate about "network problem"? practically, if a controller fails pre-flight check (which includes informer sync-up) the controller will be return will an error log. i read you as "the controller-manager needs a way to handle the failure from the managed controllers, or detect the liveness of the controllers". is it?

> The default readyTimeout is 30s, there is no interface exposed to configure it except cast Controller to DefaultController.(I am not sure if it is a good practice)

customizing timeout sounds reasonable. will send a pull for the fix.
