### ISSUE TITLE
How to Get Multiple Resource  ，For exemple  kubectl get svc  a  b

### ISSUE THREAD

**Issue by Fly0905** [kubernetes-client/java#852]

**Comment by brendandburns** [comment]
You need to make multiple calls, one for each resource. There is no client call to get multiple resources at once, except the *List calls which get all resources.


e.g.

```java
client.readNamespacedService(...);
client.readNamespacedService(...);
```

Closing this as the question is answered, please use the `/reopen` command if you need to reopen.
