### ISSUE TITLE
k8s 1.16 support

### ISSUE THREAD

**Issue by JulianKahnert** [kubernetes-client/java#857]
Hi, are there any plans on creating a new [client version](https://mvnrepository.com/artifact/io.kubernetes/client-java) with #826 included that supports k8s 1.16?

**Comment by brendandburns** [comment]
The support is there in the repo. We need to build and push an `8.0.0-beta1` release, I'll look into doing that sometime tomorrow.

**Comment by rjeberhard** [comment]
Thanks, @brendandburns, for all of the hard work on this project.  I'm also interested in 1.16/1.17 support, so I'd be willing to try out the beta release.

**Comment by brendandburns** [comment]
@rjeberhard the 1.16 support is pushed out in the 8.0.0-alpha1 release.

We'll see about cutting a formal 8.0.0 official release sometime soon-ish and then we can move on to regenerating for 1.17

**Comment by rjeberhard** [comment]
@brendandburns, thanks for pushing 8.0.0-alpha1.  I was able to update our operator project to use CRD v1 and successfully run all of our tests against a 1.16 cluster.
