### ISSUE TITLE
Pod CPU usage in %

### ISSUE THREAD

**Issue by bhargaviaaa** [kubernetes-client/java#860]
How to get Pod CPU usage in %. Also which api and method to be used for kubectl top pods?

**Comment by brendandburns** [comment]
This is a duplicate of #717 please take a look at the solution there.

tl; dr; `kubectl top ...` is not a single API call, but rather code in the `kubectl` binary. You will need to duplicate the code in this library. We'd be happy to take a PR to add this functionality if you write it.
