### ISSUE TITLE
Not able to Patch custom resource as per RFC 6902

### ISSUE THREAD

**Issue by balajikrb** [kubernetes-client/java#862]
Hi,

I am trying to perform a patch on Kubernetes CRD. I use json-patch library(com.github.java-json-tools:json-patch:1.12) to generate patchItem and I see the patch document it is generating seems to be fine.

But, while triggering from application (Java code) I get the following error.

"status": 500,
"error": "Internal Server Error",
"message": "Bad Request",

The patch document it generates is as below (As per RFC 6902),

[{"op":"remove","path":"/metadata/generation"},{"op":"replace","path":"/spec/srv/value1","value":4000}]

While checking the traces, the same is converted into something like below.,

{
	"operations": [{
		"op": "remove",
		"path": {
			"missing": {},
			"tokenResolvers": [{
				"token": {
					"cooked": "metadata",
					"raw": "metadata"
				}
			}, {
				"token": {
					"cooked": "generation",
					"raw": "generation"
				}
			}]
		}
	}, {
		"value": {
			"_value": 4000
		},
		"op": "replace",
		"path": {
			"missing": {},
			"tokenResolvers": [{
				"token": {
					"cooked": "spec",
					"raw": "spec"
				}
			}, {
				"token": {
					"cooked": "srv",
					"raw": "srv"
				}
			}, {
				"token": {
					"cooked": "value1",
					"raw": "value1"
				}
			}]
		}
	}]
}

Due to this, Kubernetes is not able to patch CRD and it is reporting Bad request.,

More details:
=============
Client Java library : v7.0.0
Kubernetes version: 1.13

JsonNode source, target;
ObjectMapper om = new ObjectMapper();

source = om.convertValue(oldProfile, JsonNode.class);
target = om.convertValue(newProfile, JsonNode.class);

JsonPatch patchItem = JsonDiff.asJsonPatch(source, target);

this.customObjectApi.getApiClient().setDebugging(true);
this.customObjectApi.getApiClient().selectHeaderContentType(MEDIA_TYPE_APPLICATION_JSON_PATCH);
this.customObjectApi.getApiClient().patchNamespacedCustomObject(group, version, namespace, plural, name, patchItem);

Note1 : Validated all other params such as group, version, namespace, plural, name and all are correct as expected.,
Note2 : I also tried to convert the patch doc into Json String using this "CommonUtils.getJsonString(patchItem)" as a last param

Is there anything I am doing wrong in the approach? Please guide me to the right approach if not., Thanks in advance.,

Regards,
Balaji.K.R

**Comment by brendandburns** [comment]
Please see the patch example here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java

**Comment by balajikrb** [comment]
Thanks @brendanburns : With V1Patch it is working as expected., This issue can be closed now., Much appreciate .,
