### ISSUE TITLE
unmarshalerDecoder: Object 'Kind' is missing in

### ISSUE THREAD

**Issue by matty111** [kubernetes-client/java#867]
I wrote this code:

Call call = client.buildCall(url, "POST", localVarQueryParams, localVarCollectionQueryParams,
				json, localVarHeaderParams, localVarFormParams, localVarAuthNames, null);

Response resp = call.execute();

Header is setted application/json e with GET method api works good.
When I use Post and the body is an Object json (i convert a file yaml in json) the api dosen't work.

My goal is make the same of kubectl apply -f file.yaml

**Comment by brendandburns** [comment]
This is basically the same as #835 

tl; dr; this isn't currently very easy to do with this client.

`Yaml.loadAll(...)` (https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Yaml.java#L251) will help a little bit with this, but only the loading part, not the POST part, you will need to write the code to do that yourself.

We'd gladly take a PR for this if you get it together.

**Comment by matty111** [comment]
Thanks,

but i can use Yaml.load() for object istio? Virtualservice, authoritazionpolicy etc.... 

If I must use loadAll() maybe the object doesn't known and the problem to the method post isn't solved

**Comment by brendandburns** [comment]
`Yaml.load/loadAll` only works for build in Kubernetes types. It won't work for any custom resources.

**Comment by brendandburns** [comment]
Just to be clear, you don't _have_ to use the `Yaml` class, it just might be easier.

You can optionally register additional classes with the `Yaml` class for loading (take a look at the static methods in the `Yaml` class for more details.

**Comment by matty111** [comment]
I have understand. Then do you know other library that can do that i told?
Because kubectl apply -f virtualservice.yaml works in my service mesh, but with this library no.
With kubectl -v=8 apply -f virtualserice.yaml,  i see url ReST and it works. When i use java library no, but i think that some method exists.
Thanks.

**Comment by brendandburns** [comment]
You can use the `ApiClient.buildRequest(...)` function to build raw requests:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L1021

It would be pretty manual, but that's the only way to do it with this client.

This library is generated from Swagger/OpenAPI specifications, and thus it doesn't contain any types for external APIs like Istio.

**Comment by brendandburns** [comment]
(also, fwiw, Apply is a client side command until Kubernetes 1.16.x, so you can't really do `apply` but you can do `create`)

**Comment by matty111** [comment]
I don't understand.
My question of this issue was because I have this error when I run this method:

Call call = client.buildCall (url, "POST", localVarQueryParams, localVarCollectionQueryParams,
json, localVarHeaderParams, localVarFormParams, localVarAuthNames, null);

buildCall method uses apiClient.buildRequest(...).  

Then I think that this doesn't solve my problem

**Comment by ysx** [comment]
java library has CustomObjectsApi class,I don't know if it can solve your problem.

**Comment by brendandburns** [comment]
If you're getting this error with buildCall, it's because the body that you are sending as JSON isn't formatted correctly. Specifically, it's missing the 'Kind' property.

**Comment by brendandburns** [comment]
Closing this issue since I believe it is answered, please use `/reopen` if further assistance is required.
