### ISSUE TITLE
Client certificate authentication for private key with passphrase

### ISSUE THREAD

**Issue by avmohan** [kubernetes-client/java#868]
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/credentials/ClientCertificateAuthentication.java does not support when private key is encrypted with a passphrase.

**Comment by brendandburns** [comment]
It's generally expected that this client library is used for headless non-interactive code. How would we prompt for the password in that context?

I'm certainly open to taking a PR to add this support, but we have no immediate plans to implement it ourselves.
