### ISSUE TITLE
How to create pod with  my own image?

### ISSUE THREAD

**Issue by yuanxiaomama** [kubernetes-client/java#869]
V1Pod pod =
                    new V1PodBuilder()
                            .withNewMetadata()
                            .withName("cpod")
                            .endMetadata()
                            .withNewSpec()
                            .addNewContainer()
                            .withName("www")
                            .withImage("myImage")
                            .endContainer()
                            .endSpec()
                            .build();
            api.createNamespacedPod(NAMESPACE, pod, null, null, null);

The result is : ImagePullBackOff/InvalidImageName
How to create pod with my registry

**Comment by brendandburns** [comment]
You need to specify the full image name for the image (e.g. `acr.io/my-repo/my-image`)

Right now `myImage` points to an image in the default Docker namespace.

**Comment by frezbo** [comment]
@yuanxiaomama you also need to specify the `imagePullSecret` if using a private docker registry.

```java
Map<String, String> metadata = new HashMap<String, String>();
        metadata.put("name", "pod");
        Map<String, String> annotations = new HashMap<String, String>();
        annotations.put("container.apparmor.security.beta.kubernetes.io/rootless", "unconfined");

        V1ObjectMeta meta = new V1ObjectMeta();
        meta.namespace("frezbo").name("pod").labels(metadata).annotations(annotations);

        V1PodSpec podSpec = new V1PodSpec();
        V1LocalObjectReference obj = new V1LocalObjectReference();
        obj.name("docker-registry");
        podSpec.addImagePullSecretsItem(obj);
        V1Container container = new V1Container().name("pod").image("docker.io/frezbo/pod:0.1.3")
                .imagePullPolicy("Always").command(Arrays.asList("sleep", "infinity"));
        podSpec.addContainersItem(container);

        V1Pod pod = new V1PodBuilder().withMetadata(meta).withSpec(podSpec).build();
```

something like this

**Comment by brendandburns** [comment]
Closing this issue since I believe it is answered, please use `/reopen` if further assistance is required.
