### ISSUE TITLE
how to use RuntimeRawExtension?

### ISSUE THREAD

**Issue by sumool** [kubernetes-client/java#872]
![image](https://user-images.githubusercontent.com/39091480/75520080-a40d5c80-5a3f-11ea-8325-b22234652981.png)
V1ControllerRevision object include RuntimeRawExtension filed,How to use to serialize the data of this field

**Comment by brendandburns** [comment]
The class is here:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/RuntimeRawExtension.java#L32

**Comment by brendandburns** [comment]
Closing this issue since I think the question is answered. Please use `/reopen` if further assistance is required.
