### ISSUE TITLE
Java client for k8s version 1.16

### ISSUE THREAD

**Issue by zhirin** [kubernetes-client/java#874]
Hi There,

I’m working on the project where we use java k8s client. And we are upgrading t the k8s version 1.16.7.
According to the documentation, the latest version of java client (7.0.0) supports k8s v1.15.
So the question is: is it safe to use java client 7.0.0 with k8s 1.16 and when should we expect new version of java-client with support of k8s v1.16?

Thanks,
Roman.

**Comment by brendandburns** [comment]
It is generally safe, though there are some [incompatabilities](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) with some older beta objects.

I have pushed a version `8.0.0-alpha1` which has full 1.16 support, despite the `alpha1` label it should be pretty stable

Assuming no major bugs in that alpha release, I would expect an official 8.0.0 release in a few weeks.

**Comment by rjeberhard** [comment]
Just a heads-up that when I tested the `8.0.0-alpha1`against Kubernetes 1.16, I was using a pre-release JDK.  @brendandburns, I didn't realize I was doing this when I pinged you earlier saying that all of my tests were successful.  Unfortunately, released versions of the JDK don't properly handle TLS 1.3 used 1.16's REST interface.  Here is the bug: https://bugs.openjdk.java.net/browse/JDK-8236039.  The fix will be in the upcoming 11.0.8 release currently scheduled for April 15th.

**Comment by brendandburns** [comment]
@rjeberhard thanks for the info. It seems like we should probably add client SDK testing to the main Kubernetes release pipeline.

**Comment by yue9944882** [comment]
@brendandburns there's a bunch of new APIs introduced or progressed to beta/GA in 1.16. how do you think about cutting a `8.0.0` release?

**Comment by brendandburns** [comment]
Sure, we can do that. Do you want to get your Spring PR in first?

**Comment by djain13** [comment]
@brendandburns Will that be possible to release a new build for **io.kubernetes » client-java-util**. maven repo(https://mvnrepository.com/artifact/io.kubernetes/client-java-util) has a 2-year-old build which doesn't contain oidc authenticator.

**Comment by yue9944882** [comment]
> Sure, we can do that. Do you want to get your Spring PR in first?

thanks, we can suspend it to the next release. i'd like a month-ish time buffer to verify that pull in our internal environment.

**Comment by yue9944882** [comment]
> maven repo(https://mvnrepository.com/artifact/io.kubernetes/client-java-util) has a 2-year-old

@djain13 i believe it's renamed to https://mvnrepository.com/artifact/io.kubernetes/client-java

**Comment by djain13** [comment]
@yue9944882 
Look like client-java (https://mvnrepository.com/artifact/io.kubernetes/client-java) jar is missing the `OpenIDConnectAuthenticator` class. Hence I am getting forbidden error when I use the jar. But when I import the code in my workspace things work. 
Will that be possible to rebuild the jar.

**Comment by brendandburns** [comment]
I cut an `8.0.0` release. We can generate a `9.0.0-SNAPSHOT` release now with the code for `1.17.0`

**Comment by brendandburns** [comment]
Closing this issue. @djain13 will you re-open a new/different issue for the problems that you are seeing?

Thanks!
