### ISSUE TITLE
Leader Election + Readiness Check

### ISSUE THREAD

**Issue by darren-bell-nanthealth** [kubernetes-client/java#875]
Hi
I am trying to implement a controller that leverages code similar to [Leader Election](https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java) However, I am struggling to create a readiness check that will inform me when a leader has successfully been created. I don't see events/hooks/callbacks that will inform me of the status of the leader election process. 
Is there an approach that I can/should use?

Thanks

**Comment by brendandburns** [comment]
The hook is the function passed in as in the example here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java#L33

Or perhaps I don't understand the question?

**Comment by darren-bell-nanthealth** [comment]
Thanks for the reply. You are right that would be the place. I wasn't clear that I am using the LeaderElectionController and there is no hook here https://github.com/kubernetes-client/java/blob/7f72a20cb2b5d4488135642c4540fe1f0c7e461a/extended/src/main/java/io/kubernetes/client/extended/controller/LeaderElectingController.java#L28. 
I guess I can simply extend the class and my hook where you suggested
