### ISSUE TITLE
Forbidden error while running from eclipse

### ISSUE THREAD

**Issue by vishalbiradar** [kubernetes-client/java#876]
I am having my pods running on AWS and want to get the details using java program.
While running the application from eclipse, I am getting the forbidden error.

I have tried with exporting AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN in the eclipse as below:
Eclipse --> My Java App ---> Run Configurations ---> Environment

But if I run it from the command line, by exporting the above AWS access variables, then it is working fine.
Even I have tried with the kube.config file from the java prog, but still got the same error.

**So how can we run it from the eclipse?**

Java Version: 1.8

```
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java</artifactId>
    <version>7.0.0</version>
    <scope>compile</scope>
</dependency>
```

My Java Code:

```
ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);
CoreV1Api api = new CoreV1Api();
CoreV1Api api = getK8sCoreApi();
V1ConfigMap v1ConfigMap = api.readNamespacedConfigMap("aws-pod-sf-configmap","default", null, null, null);
```

But still getting the below error:

```
Caused by: io.kubernetes.client.openapi.ApiException: Forbidden
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:979)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
	at io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedConfigMapWithHttpInfo(CoreV1Api.java:24545)
	at io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedConfigMap(CoreV1Api.java:24521)
	at com.sfdc.app.v1.jobActionImpl.TargetConfiguration.getSdbDetails(TargetConfiguration.java:54)
	at com.sfdc.app.v1.jobActionImpl.TargetConfiguration.postTopologyConfiguration(TargetConfiguration.java:47)
	at com.sfdc.app.v1.jobActionImpl.TargetConfiguration.execute(TargetConfiguration.java:81)
```

**Comment by brendandburns** [comment]
The default client uses `$HOME/.kube/config` as the config file. I don't know what eclipse uses as `$HOME`

You can set the `$KUBECONFIG` environment variable to a hard-coded path to be guaranteed of the kubeconfig file that is loaded.  That way you can test if `kubectl` works with that file, and the Java client doesn't then there's definitely something wrong.

It's possible that there's some part of the AWS authentication we don't support. If you continue to have problems after you point the client directly at a specific kubeconfig file, please add that kubeconfig file to this issue (after removing  any secrets obviously) and we can investigate what the bugs might be.

**Comment by vishalbiradar** [comment]
@brendandburns 
EVen I have tried with

```
String kubeConfigPath = "/Users/vbiradar/.kube/config";
ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();
Configuration.setDefaultApiClient(client);
Configuration.setDefaultApiClient(client);
CoreV1Api api = new CoreV1Api();

```

**Comment by brendandburns** [comment]
Can you send the contents of your config file (with the secrets removed) my guess is that it is unsupported somehow. I bet that this is independent of Eclipse.

**Comment by vishalbiradar** [comment]
The important thing is, the clusters are deployed o aws.
In order to access them, we need to get and export the token and the token will expire every one hour.

So if I want to get the pod details,
How can I get the pod details from the java application?
