### ISSUE TITLE
Client-java jar is missing the OpenIDConnectAuthenticator class

### ISSUE THREAD

**Issue by djain13** [kubernetes-client/java#883]
Latest client-java (https://mvnrepository.com/artifact/io.kubernetes/client-java) jar is missing the `OpenIDConnectAuthenticator` class. This results in a forbidden error while using `Kube-conf`  with `oidc`  as auth-provide. 

When I take the code from master forbidden error goes away and I could make Kube API calls.

**Comment by djain13** [comment]
cc @brendandburns @yue9944882

**Comment by brendandburns** [comment]
I downloaded the `8.0.0` release jar from here:

https://repo1.maven.org/maven2/io/kubernetes/client-java/8.0.0/client-java-8.0.0.jar

And when I run

`jar tf client-java-8.0.0.jar`

I see:
```
...
io/kubernetes/client/util/authenticators/OpenIDConnectAuthenticator.class
...
```

So I think it is already packaged. Are you sure you are using the 8.0.0 release?
