### ISSUE TITLE
kubernetes-client-java How to set up QPS and Burst

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#886]
For example kubernetes-client-java How to set up QPS and Burst。
This can be set in go language

```
func KubeConfig() (conf *rest.Config, err error) {
	kubeConfig, err := clientcmd.BuildConfigFromFlags(config.KubeMaster, config.KubeConfig)
	if err != nil {
		return nil, err
	}
	kubeConfig.QPS = config.KubeQPS
	kubeConfig.Burst = config.KubeBurst
	kubeConfig.ContentType = config.KubeContentType

	return kubeConfig, err
}

```

But I didn't find a way to set this parameter in the Java client

**Comment by ZP-AlwaysWin** [comment]
cc @brendandburns @yue9944882

**Comment by brendandburns** [comment]
Apologies, but there's no similar thing rate limiting implemented in this client.

I'll leave this open as a feature request, but I think it's unlikely to be added anytime soon.

**Comment by brendandburns** [comment]
(oops, didn't mean to close)

**Comment by ZP-AlwaysWin** [comment]
> (oops, didn't mean to close)

OK, thank you very much for your reply and look forward to this feature
