### ISSUE TITLE
how to get metrics by  client api ?

### ISSUE THREAD

**Issue by damozhiying** [kubernetes-client/java#892]
```
sudo kubectl top node
185.xx.yy.110     878m         2%     18481Mi         29%         
185.xx.yy.111     2571m        8%     18440Mi         29%         
185.xx.yy.112     921m         2%     12111Mi         19%         
```

how to get metrics by  client api ?

**Comment by damozhiying** [comment]
how to get node cpu and memory usage percentage,i want to get node metrics then custom loadbalance by node cpu,mem usage

**Comment by brendandburns** [comment]
The metrics APIs are not currently part of this client library because they are not included in the main Kubernetes OpenAPI schema.

**Comment by persunde** [comment]
@damozhiying If you want to get Node and/or Pod CPU/Memory metrics check out this K8S client library instead:
https://github.com/fabric8io/kubernetes-client

It has extended functionality that is not part of the Kubernetes OpenAPI, such as fetching metrics data similar to
```
kubectl top node
kubectl top pod
```

Just use the code like this:
```
KubernetesClient client = new DefaultKubernetesClient();
PodMetricsList podMetricsList = client.top().pods().metrics(namespace);
```

See here for more information:
https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#fetching-metrics

**Comment by mattsanta** [comment]
Will the metrics APIs be a part of this client library soon?

**Comment by brendandburns** [comment]
The metrics APIs are now part of this, see `KubectlTop.java` (https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTop.java)
