### ISSUE TITLE
Unable to use Exec 

### ISSUE THREAD

**Issue by habibali95** [kubernetes-client/java#894]
Greetings, 

I'm trying to run sh commands using Exec, the script works fine with kubectl exec but not with the java client API, for a simple "echo" I get this error :

OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"echo 'schema db created'\": executable file not found in $PATH": unknown.

Im using minikube to run kubernetes, the pod contains an image of postgres, the version of kubernetes-client is 6.0.1 and the system is windows 10.

Any help would be appreciated.

**Comment by brendandburns** [comment]
I think you are sending the command as a single string `"echo 'schema db created'` when you should be sending it as an array `new String[] { "echo", "schema db created" }`

See the example here:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java#L54

**Comment by habibali95** [comment]
Greetings, 
Thanks, I'm getting the same problem with this, can you help me correct it if there's something wrong?
String [] commands = {"su postgres" , 
    		"psql -c", "SELECT schema_name FROM information_schema.schesmata"} ;

OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"su postgres\": executable file not found in $PATH": unknown
