### ISSUE TITLE
Informer the network is disconnected, how to report an error

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes-client/java#896]
When I use the java-client Informer function, even if the network is disconnected, the client has no way to detect it. Is there any way to make the network disconnected and notify the client in time?

The code example is as follows

```
public class InformerStatefulSets7 {
    public static void main(String[] args)  {
        /**/
        ApiClient apiClient = null;
        try {
            ClassPathResource resource = new ClassPathResource("kubectl.conf");
            InputStream inputStream = resource.getInputStream();
            Reader input = new InputStreamReader(inputStream);

            KubeConfig kubeConfig = KubeConfig.loadKubeConfig(input);
            apiClient = ClientBuilder.kubeconfig(kubeConfig).build();
           apiClient.getHttpClient().newBuilder().pingInterval(100, TimeUnit.MILLISECONDS);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        SharedInformerFactory factory = new SharedInformerFactory();

        AppsV1Api appsV1Api = new AppsV1Api(apiClient);

        // StatefulSet informer
        SharedIndexInformer<V1StatefulSet> statefulSetInformer =
                factory.sharedIndexInformerFor(
                        (CallGeneratorParams params) -> {
                            try {
                                return appsV1Api.listNamespacedStatefulSetCall(
                                        "default",
                                        null,
                                        null,
                                        null,
                                        null,
                                        null,
                                        null,
                                        params.resourceVersion,
                                        params.timeoutSeconds,
                                        params.watch,
                                        null);
                            } catch (ApiException e) {
                                e.printStackTrace();
                                return null;
                            }

                        },
                        V1StatefulSet.class,
                        V1StatefulSetList.class);

        statefulSetInformer.addEventHandlerWithResyncPeriod(
                new ResourceEventHandler<V1StatefulSet>() {
                    @Override
                    public void onAdd(V1StatefulSet statefulSet) {
                        System.out.printf("%s StatefulSet added!\n", statefulSet.getMetadata().getName());
                    }

                    @Override
                    public void onUpdate(V1StatefulSet oldStatefulSet, V1StatefulSet newStatefulSet) {
                        System.out.printf("%s StatefulSet update!\n", newStatefulSet.getMetadata().getName());
                        System.out.println(newStatefulSet);
                    }

                    @Override
                    public void onDelete(V1StatefulSet statefulSet, boolean deletedFinalStateUnknown) {
                        System.out.printf("%s StatefulSet delete!\n", statefulSet.getMetadata().getName());
                        System.out.println(statefulSet);
                    }
                },1000);

        statefulSetInformer.run();
        
    }
}
```

**Comment by ZP-AlwaysWin** [comment]
Excuse me, I need help
@brendandburns

**Comment by yue9944882** [comment]
the informer doesn't alert/panic on network failures, instead it's supposed to be re-connecting every 1s until it's online again.

**Comment by ZP-AlwaysWin** [comment]
> the informer doesn't alert/panic on network failures, instead it's supposed to be re-connecting every 1s until it's online again.

hi @yue9944882 
Thank you for your reply. Do you need to configure this automatic retry? In the process of using it in a production environment, the above code often does not work. Unless I restart the service, the Informer will not work again.

**Comment by yue9944882** [comment]
by "does not work", do you mean that the informer doesnt seem to be receiving any events from watches? or it is failing to connecting the kubernetes cluster?

**Comment by ZP-AlwaysWin** [comment]
> by "does not work", do you mean that the informer doesnt seem to be receiving any events from watches? or it is failing to connecting the kubernetes cluster?
The Informer can connect to the kubernetes cluster normally and can receive events when it is just started. After running for a period of time, the informer does not receive any events from the watch.

**Comment by ZP-AlwaysWin** [comment]
> by "does not work", do you mean that the informer doesnt seem to be receiving any events from watches? or it is failing to connecting the kubernetes cluster?

The Informer can connect to the kubernetes cluster normally and can receive events when it is just started. After running for a period of time, the informer does not receive any events from the watch.

**Comment by yue9944882** [comment]
it can be caused by various reason.. what's your version? upgrading to the latest can bring couples of fixes

**Comment by ZP-AlwaysWin** [comment]
> it can be caused by various reason.. what's your version? upgrading to the latest can bring couples of fixes

I used 5.0.0, 6.0.1, 7.0.0 versions in production environment, all have this problem. It just started to run normally, it will fail after some time, and the reason is not clear. Restarting the service will return to normal and then start again and again.

**Comment by yue9944882** [comment]
did you override the read timeout for the client? https://github.com/kubernetes-client/java/blob/28cfba91724facab07efce62337d9c228a263012/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java#L26-L27

**Comment by ZP-AlwaysWin** [comment]
> did you override the read timeout for the client?
> 
> https://github.com/kubernetes-client/java/blob/28cfba91724facab07efce62337d9c228a263012/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java#L26-L27

**Comment by ZP-AlwaysWin** [comment]
Yes, I have overwritten this readtimeout.
![image](https://user-images.githubusercontent.com/23489782/77742348-55101280-7051-11ea-83da-99e0513d2568.png)

**Comment by yue9944882** [comment]
can you show us the thread dump where the informer got hanging? the informer's thread are particularly named for dump analysis.

**Comment by ZP-AlwaysWin** [comment]
> can you show us the thread dump where the informer got hanging? the informer's thread are particularly named for dump analysis.

In the process of using it, I did not find that the process running Informer hangs, it just fails and does not work. But its threads exist.

Even if Informer is not working, this thread is still false（`es.isTerminated() `）, this is my test code demo. I have tried the new version, but all have this problem. Now I can only reconstruct java code into go

```
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import org.springframework.core.io.ClassPathResource;

import io.kubernetes.client.ApiClient;
import io.kubernetes.client.ApiException;
import io.kubernetes.client.apis.AppsV1Api;
import io.kubernetes.client.informer.ResourceEventHandler;
import io.kubernetes.client.informer.SharedIndexInformer;
import io.kubernetes.client.informer.SharedInformerFactory;
import io.kubernetes.client.models.V1StatefulSet;
import io.kubernetes.client.models.V1StatefulSetList;
import io.kubernetes.client.util.CallGeneratorParams;
import io.kubernetes.client.util.ClientBuilder;
import io.kubernetes.client.util.KubeConfig;

public class InformerStatefulSets {
    public static void main(String[] args)  {
        /**/
        ApiClient apiClient = null;
        try {
            ClassPathResource resource = new ClassPathResource("kubectl_fuck.conf");
            InputStream inputStream = resource.getInputStream();
            Reader input = new InputStreamReader(inputStream);

            KubeConfig kubeConfig = KubeConfig.loadKubeConfig(input);
            apiClient = ClientBuilder.kubeconfig(kubeConfig).build();
            apiClient.getHttpClient().setReadTimeout(0, TimeUnit.SECONDS); // infinite timeout
            apiClient.getHttpClient().setRetryOnConnectionFailure(true);
            apiClient.getHttpClient().setConnectTimeout(1, TimeUnit.SECONDS);
            io.kubernetes.client.Configuration.setDefaultApiClient(apiClient);

        } catch (Exception e) {
            e.printStackTrace();
        }

        ExecutorService es = Executors.newFixedThreadPool(1);
        SharedInformerFactory factory = new SharedInformerFactory(es);

        AppsV1Api appsV1Api = new AppsV1Api(apiClient);

        // StatefulSet informer
        SharedIndexInformer<V1StatefulSet> statefulSetInformer =
                factory.sharedIndexInformerFor(
                        (CallGeneratorParams params) -> {
                            try {
                                return appsV1Api.listNamespacedStatefulSetCall(
                                        "default",
                                        null,
                                        null,
                                        null,
                                        null,
                                        null,
                                        null,
                                        params.resourceVersion,
                                        params.timeoutSeconds,
                                        params.watch,
                                        null,
                                        null);
                            } catch (ApiException e) {
                                e.printStackTrace();
                                return null;
                            }

                        },
                        V1StatefulSet.class,
                        V1StatefulSetList.class);

        statefulSetInformer.addEventHandlerWithResyncPeriod(
                new ResourceEventHandler<V1StatefulSet>() {
                    @Override
                    public void onAdd(V1StatefulSet statefulSet) {
                        System.out.printf("%s StatefulSet added!\n", statefulSet.getMetadata().getName());
                    }

                    @Override
                    public void onUpdate(V1StatefulSet oldStatefulSet, V1StatefulSet newStatefulSet) {
                        System.out.printf("%s StatefulSet update!\n", newStatefulSet.getMetadata().getName());
                        System.out.println(newStatefulSet);
                    }

                    @Override
                    public void onDelete(V1StatefulSet statefulSet, boolean deletedFinalStateUnknown) {
                        System.out.printf("%s StatefulSet delete!\n", statefulSet.getMetadata().getName());
                        System.out.println(statefulSet);
                    }
                },1000);

        statefulSetInformer.run();

        while (true) {
            try {
                Thread.sleep(9000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            System.out.println(es.isTerminated());

            System.out.println("=====================");

            System.out.println(statefulSetInformer.hasSynced());

        }

    }
}
```

**Comment by yue9944882** [comment]
can you confirm that the thread spawned from `ReflectorRunnable` is in running state?

**Comment by ZP-AlwaysWin** [comment]
> can you confirm that the thread spawned from `ReflectorRunnable` is in running state?

I don't know what you mean, but I can be sure that in order to solve this problem, I run this program on the server for three days without any error log output, but informer just doesn't work

**Comment by ZP-AlwaysWin** [comment]
https://github.com/kubernetes/kubernetes/pull/89652

**Comment by cizezsy** [comment]
@ZP-AlwaysWin I have met the same problem before. If the client didn't receive events from the server for a period of time, the TCP connection between your client and server might be stopped by some network middlewares because of no data transmitted in this connection. You can add a timer task in your server to update the resource you want to watch periodically to keep the connection alive.

**Comment by tg123** [comment]
tcp_keepalive for a workaround?

**Comment by ZP-AlwaysWin** [comment]
> tcp_keepalive for a workaround?
hi @tg123
Do you have any sample code? I still haven't solved this problem

**Comment by ZP-AlwaysWin** [comment]
> @ZP-AlwaysWin I have met the same problem before. If the client didn't receive events from the server for a period of time, the TCP connection between your client and server might be stopped by some network middlewares because of no data transmitted in this connection. You can add a timer task in your server to update the resource you want to watch periodically to keep the connection alive.

Do you have any sample code? I still haven't solved this problem

**Comment by weihai4099** [comment]
me too. can't get informer status .so can't auto restart informer by code

**Comment by ichekrygin** [comment]
This issue is impacting us as well. Can this be reopened?

**Comment by yzxz1996** [comment]
> This issue is impacting us as well. Can this be reopened?

I agree.The same problems plague us.
