### ISSUE TITLE
'CustomObjectsApi' Object parameters value cannot support int 

### ISSUE THREAD

**Issue by shanleyHe** [kubernetes-client/java#899]
run   Message:      invalid spec: cannot convert int64 to string
Argo yaml transform jsonObject, put jsonObject into CustomObjectsApi.createNamespacedCustomObject():
there is Argo yaml:
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
  namespace: default
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: 0

  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [echo, "{{inputs.parameters.message}}"]

**Comment by brendandburns** [comment]
Can you provide sample code for what you are trying to do? That will help us debug.

**Comment by shanleyHe** [comment]
`CustomObjectsApi apiInstance = new CustomObjectsApi(client);
        String group = "argoproj.io"; // String | The custom resource's group name
        String version = "v1alpha1"; // String | The custom resource's version
        String namespace = "default"; // String | The custom resource's namespace
        String plural = "workflows"; // String | The custom resource's plural name. For TPRs this would be lowercase plural kind.
        Object body = map; // Object | The JSON schema of the Resource to create.
        String pretty = "true"; // String | If 'true', then the output is pretty printed.
        try {
            Object result = apiInstance.createNamespacedCustomObject(group, version, namespace, plural, body, pretty);
            System.out.println(result);
        }catch (ApiException e) {
            System.err.println("Exception when calling CustomObjectsApi#createNamespacedCustomObject");
            System.err.println("Status code: " + e.getCode());
            System.err.println("Reason: " + e.getResponseBody());
            System.err.println("Response headers: " + e.getResponseHeaders());
            e.printStackTr`

**Comment by shanleyHe** [comment]
> Can you provide sample code for what you are trying to do? That will help us debug.

sorry，I think it's kubernetes cannot create spec. arguments. parameters.value type is Integer
