### ISSUE TITLE
Consider integrating VCR-style testing for HTTP calls...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#90]
There is a Java library here:

https://github.com/betamaxteam/betamax

Similar to VCR for Ruby and VCR.py for Python. 

It supports recording and playback of HTTP requests. We should consider using it to write a bunch of functional tests for this library.

**Comment by rpalcolea** [comment]
Hi @brendanburns ,

Are there any examples out there on how to tests applications that use this library? is people only mocking responses?

**Comment by brendandburns** [comment]
@rpalcolea 

Here are examples of using it in python:

https://vcrpy.readthedocs.io/en/latest/usage.html

Sadly, it looks like the equivalent Java library (Betamax) has been abandoned.

We could just use Mockito to mock out the relevant HTTP calls.

But basically, the problem I'm trying to solve for is that our unit testing doesn't really cover most of our usage, and thus we have introduced bugs that are only found when users use the code.

**Comment by rpalcolea** [comment]
I wonder if flashback could be helpful to you -> https://github.com/linkedin/flashback

**Comment by brendanburns** [comment]
cool, I'll give it a try.  Thanks!

**Comment by brendandburns** [comment]
This is now done. For the record, I used WireMock
