### ISSUE TITLE
java-model-gen generates partial list of classes off of an '/opeapi/v2' input

### ISSUE THREAD

**Issue by zzur** [kubernetes-client/java#904]
Followed _**https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md**_ in order to generate java client source code for _istio_ CRDS, I am getting only the **_*List_** resources and the rest of the classes are missing, e.g: here would expected the _Gateway_ class so that I can create namespaced Gateway etc. ...

```
[mzur@mzur-dt2 ~/tmp/k8s-java-client] (colossus_dev *)$ tar tfv openapi.tgz | grep -i Gateway
-rw-r--r-- root/root      5898 2020-03-27 22:40 java/src/main/java/io/kubernetes/client/models/IoIstioNetworkingV1alpha3GatewayList.java
-rw-r--r-- root/root      5891 2020-03-27 22:40 java/src/main/java/io/kubernetes/client/models/IoIstioNetworkingV1beta1GatewayList.java
```
Attaching the _openapi_ swagger file retrieved from the _api server_ and the output from _java-model-gen_ ... 
[openapi.txt](https://github.com/kubernetes-client/java/files/4397415/openapi.txt)
[out.txt](https://github.com/kubernetes-client/java/files/4397417/out.txt)

**Comment by brendandburns** [comment]
There's a lot of errors in the output like:

```sh
-attribute paths.'/apis/config.istio.io/v1alpha2/namespaces/{namespace}/handlers/{name}/status'. Declared path parameter name needs to be defined as a path parameter in path or operation level
        -attribute paths.'/apis/security.istio.io/v1beta1/namespaces/{namespace}/peerauthentications/{name}/status'. Declared path parameter namespace needs to be defined as a path parameter in path or operation level
        -attribute paths.'/apis/networking.istio.io/v1beta1/namespaces/{namespace}/sidecars/{name}'. Declared path parameter name needs to be defined as a path parameter in path or operation level
        -attribute paths.'/apis/apps/v1beta2/namespaces/{namespace}/controllerrevisions/{name}'(put).operationId is repeated
        -attribute paths.'/apis/security.istio.io/v1beta1/namespaces/{namespace}/requestauthentications/{name}'. Declared path parameter name needs to be defined as a path parameter in path or operation level
```

I suspect that the istio openapi is not well formed. I think with aggregate API servers, the openapi is served by the aggregate API server itself, so you'd need to follow up with the Istio folks to get them to fix their OpenAPI definitions.

**Comment by brendandburns** [comment]
In the meantime, you can probably just use the CustomObjectsAPI if you want with hand-rolled objects.

I'm going to close this, since I don't think there's anything actionable for us here.

Please reopen with `/reopen` if you need any more assistance.

**Comment by zzur** [comment]
Okay, makes sense, many thanks.

**Comment by ashirvadgupta** [comment]
For CustomResourceDefinitions created in apiextensions.k8s.io/v1, structural OpenAPI v3 validation schemas are required and pruning is enabled and cannot be disabled (note that CRDs converted from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1 might lack structural schemas, and spec.preserveUnknownFields might be true).


For CustomResourceDefinitions created in apiextensions.k8s.io/v1beta1, if a structural OpenAPI v3 validation schema is defined (either in the global spec.validation.openAPIV3Schema in apiextensions.k8s.io/v1beta1 or for each version) in a CustomResourceDefinition, pruning can be enabled by setting spec.preserveUnknownFields to false.

After enabling this setting, your models will be generated properly

**Comment by zzur** [comment]
this worked fine. Many many thanks, aslo for posting on the channel: https://kubernetes.slack.com/archives/C76GB48RK/p1585367426022600
