### ISSUE TITLE
ApiClient is infinite timeout，But an exception appears that read timeout 10 minutes later 

### ISSUE THREAD

**Issue by Fly0905** [kubernetes-client/java#906]
`ApiClient client = Config.defaultClient();
client.setDebugging(true);
client.getHttpClient().setReadTimeout(0, TimeUnit.SECONDS); // infinite timeout
Configuration.setDefaultApiClient(client);`

**Comment by brendandburns** [comment]
Can you send the exception stack trace? That will help us debug.

It's possible that the timeout is on the server side (or somewhere in-between)

**Comment by yue9944882** [comment]
kubernetes has a server-side timeout, which is 10-min for shortly-running verbs (get/create/update..) and 1 hr-ish for watches.

**Comment by Fly0905** [comment]
> Can you send the exception stack trace? That will help us debug.
> 
> It's possible that the timeout is on the server side (or somewhere in-between)

Complete code ：

 `ApiClient client = Config.defaultClient();
            client.getHttpClient().setReadTimeout(0, TimeUnit.SECONDS); // infinite timeout 
            Configuration.setDefaultApiClient(client);

            CoreV1Api api = new CoreV1Api();

            Watch<V1Namespace> watch = Watch.createWatch(
                    client,
                    api.listNamespaceCall(null, null, null,
                            null, null, null, 5,
                            Boolean.TRUE,null,  null),
                    new TypeToken<Watch.Response<V1Namespace>>(){}.getType());

            for (Watch.Response<V1Namespace> item : watch) {
                System.out.printf("%s : %s%n", item.type, item.object.getMetadata().getName());
            }
`
an exception appears that read timeout 10 minutes later

java.lang.RuntimeException: Io Exception during hasNext method
    at io.kubernetes.client.uitl.Watch.hasNext(Watch.java:183)
    ...
Caused by:java.net.SocketTimeoutException:Read timed out

**Comment by Fly0905** [comment]
> kubernetes has a server-side timeout, which is 10-min for shortly-running verbs (get/create/update..) and 1 hr-ish for watches.

how to check kubernetes cofing about a server-side timeout

**Comment by brendandburns** [comment]
You have to look at the flags that are set on the Kubernetes master.

But chances are, unless you are running the cluster yourself, you can't reconfigure those.

But in general, you shouldn't expect Watches to last forever. You should wrap them up in a List/Watch loop (or just use the Informer utilities in this library which do that for you)

**Comment by Fly0905** [comment]
The cofing of Kubernetes master is default . Can you give an example about use the Informer
