### ISSUE TITLE
Kubernetes Client for Kubernetes v1.18

### ISSUE THREAD

**Issue by brindasanth** [kubernetes-client/java#907]
I am trying Kubernetes-client for Java based operator framework, Kubernetes java client is working perfectly for v1.5x, When I try to test with v1.17 or v1.18, It is not working as expected. Would please let me know, if it supports next version of v1.5x ?, If not, please let me know, Is there any plan to support and their timelines.

**Comment by bhardwahnitish19** [comment]
Please go through this issue: https://github.com/kubernetes-client/java/issues/893

Java version 11.0.5 is not compatible with k8s v1.16+. Please wait for an update for java or use java 15 preview.

**Comment by brindasanth** [comment]
Thanks for your response.
