### ISSUE TITLE
Patch deployment

### ISSUE THREAD

**Issue by arnouthoebreckx** [kubernetes-client/java#919]
Is it possible to patch both the limits and requests in one command?

Currently I do this
```
V1Patch patchUpgRequest = new V1Patch("[{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/resources/requests/cpu\",\"value\":\""+ upgRequests + "m\"}]");

V1Patch patchUpgLimits = new V1Patch("[{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/resources/limits/cpu\",\"value\":\""+ upgLimits + "m\"}]");

api.patchNamespacedDeployment(upgDeploymentName, "default", patchUpgLimits, null, null, null, null);

api.patchNamespacedDeployment(upgDeploymentName, "default", patchUpgRequest, null, null, null, null);
```
But it will try to create the pods twice because of the double api.patchNamespacedDeployment call.

Is it possible to do this in one call? I was thinking if you can get the Deployment data in JSON, than edit this and send this as patch could work but no idea how to do it.

**Comment by brendandburns** [comment]
Sure, you'll notice that the JSON object in that string is an Array, just place two JSON objects in that array and make one patch call.

**Comment by arnouthoebreckx** [comment]
@brendanburns Wow, no idea how I overlooked that but it works now!

Thank you very much!

**Comment by brendandburns** [comment]
Closing as I believe this is answered. Please use the `/reopen` command (or open a new issue) if you need any more assistance.
