### ISSUE TITLE
java-model-gen generates CRD that imports non-exist class

### ISSUE THREAD

**Issue by codeyq** [kubernetes-client/java#921]
I followed https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md to generate Java client for CRD. However, the generated file imports the following class which doesn't exist in generated file nor library
```java
import io.kubernetes.client.models.IoK8sApimachineryPkgApisMetaV1ObjectMeta;
```
Actually, should I just replace it with the following?
```java
import io.kubernetes.client.openapi.models.V1ObjectMeta;
```
By the way, any plan to productionize `yue9944882/java-model-gen` docker image in this repo?

**Comment by brendandburns** [comment]
Yeah, probably. There is a pre-processor here:

https://github.com/kubernetes-client/gen/blob/master/openapi/preprocess_spec.py

That massages the swagger spec to do things like this.

We're open to productionizing that script/image but I'm not sure anyone has the cycles to do it right now.

**Comment by codeyq** [comment]
@brendandburns Thanks. Replacing to `V1ObjectMeta` works. However, I found there is another issue with `yue9944882/java-model-gen`. Let's say we got the following files from the code gen
```
V1Crd.java
V1CrdList.java
V1CrdListMetadata.java
V1CrdSpec.java
```
When I try to run the controller, i got the following error message. 
```
java.lang.ClassCastException: io.kubernetes.client.models.V1CrdListMetadata cannot be cast to io.kubernetes.client.openapi.models.V1ListMeta
	at io.kubernetes.client.util.ListAccessor.listMetadata(ListAccessor.java:18)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
```
Apparently `V1CrdListMetadata` cannot be cast to `V1ListMeta`. Replacing `V1CrdListMetadata`s in `V1CrdList.java` to `V1ListMeta` resolved the issue. Is this expected in `yue9944882/java-model-gen`?

**Comment by brendandburns** [comment]
cc @yue9944882 

Not sure what the plans to productionize it are, but if you wanted to improve it and submit a PR to this repo that would be awesome.

**Comment by yue9944882** [comment]
> import io.kubernetes.client.models.IoK8sApimachineryPkgApisMetaV1ObjectMeta;
> Actually, should I just replace it with the following?
> import io.kubernetes.client.openapi.models.V1ObjectMeta;

Exactly. There're a few manual changes have to be done after the code-generation, at least you're not only required to replace `V1ObjectMeta` but also `V1ListMeta`.

> By the way, I would be more than happy to help productionizing the script/image if there is anything that I can do.

There was plan to enhance the java model generator. @brendandburns I was thinking about introducing java models for other commonly-used repos e.g. [kubefed](https://github.com/kubernetes-sigs/kubefed), istio, helm. etc (probably in a separated module named `client-java-model-contrib`) and manage/upgrade them automatically w/ the help of that generator . That will require the java model generator to be working smoothly (w/o manual follow-ups)..

**Comment by codeyq** [comment]
@yue9944882 Yeah two fields need to be fixed manually, `V1ObjectMeta` and `V1ListMeta`
- `V1ObjectMeta` 
This is easy to fix because `V1Crd` has a ref in metadata that points to `"$ref": "#/definitions/v1.ObjectMeta"`
- `V1ListMeta`
This seems not straightforward cuz it doesn't have any reference to the `V1ListMeta`. As a result, a CRD specific `V1CrdListMetadata` was derived from a customized metadata field.

Do you know why a new metadata field was generated for `V1CrdList` but not using the existing `V1ListMeta`?

**Comment by aespinosa** [comment]
> Any updates on this issue? It seems like `V1ObjectMeta` is fixed, but `V1ListMeta` is still not applied to the metadata field of the generated CRD List type.
> 
> We would like to help fixing this, at is it currently blocking our progress. But it will require some guidance to where/how to apply a fix.

@erikgb  Can you try https://github.com/kubernetes-client/gen/pull/161 ? It contains a fix in pre-processing for V1ObjectMeta and V1ListMeta

**Comment by erikgb** [comment]
> @erikgb Can you try [kubernetes-client/gen#161](https://github.com/kubernetes-client/gen/pull/161) ? It contains a fix in pre-processing for V1ObjectMeta and V1ListMeta

@aespinosa Sorry for the delay. It seems like the pull request is already merged! I have been using the image create from https://github.com/yue9944882/java-model-gen, so to test your pull request would require some additional work/time that I did not have until now.

@yue9944882 Any chance for you to update your excellent java-model-gen image with the changes submitted by @aespinosa?

**Comment by yue9944882** [comment]
@erikgb i opened https://github.com/kubernetes-client/java/pull/981 to switch the model-generation guides to the scripts by @aespinosa , any comments are welcome. thanks

**Comment by erikgb** [comment]
> @erikgb i opened #981 to switch the model-generation guides to the scripts by @aespinosa , any comments are welcome. thanks

@yue9944882 It seems like a good idea to drop the container image approach for generating code for custom resources. I will try to "test" your proposed update to the docs and report back any findings.

**Comment by erikgb** [comment]
@yue9944882 I have reviewed https://github.com/kubernetes-client/java/pull/981, and added a couple of minor comments.

Sadly I was unable to verify the new approach with my current setup: I want to run this class generation as part of a GitLab CI/CD pipeline configured with Docker runners. Since the invoked scripts are invoking `docker`, I need to review my Docker-IN-Docker setup. We also have to go through a corporate Docker Registry proxy, to pull the container images, which tends to cause some pain - because we have to rewrite the Docker image URLs. I will have a closer look over the weekend....

**Comment by aespinosa** [comment]
i think @yue9944882 's workflow is meant have code generated and checked-in by hand.  

For integrating with CI pipelines, you might want to tap directly to `generate-sources` phase. just copy off the `openapi-generator-maven-plugin`'s settings in https://github.com/kubernetes-client/gen/blob/master/openapi/java.xml in your own `pom.xml`

**Comment by yue9944882** [comment]
UPDATE: the CRD models now can also be written manually by properly implementing some interfaces: https://github.com/kubernetes-client/java/pull/1020
