### ISSUE TITLE
io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by toufunao** [kubernetes-client/java#923]
I write a test demo as 

ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new 
      FileReader(kubeConfigPath))).build();

Configuration.setDefaultApiClient(client);

CoreV1Api api = new CoreV1Api();

V1PodList list = api.listPodForAllNamespaces(null,null,null,null,null,null,null,
                null,null);

  for (V1Pod item : list.getItems()) {
            System.out.println(item);
        }

but it reports as 
kubernetes.client.openapi.ApiException: javax.net.ssl.SSLPeerUnverifiedException: Hostname xxxxxx not verified:
    certificate: sha256/zKZhFXdH1atBs2AKx0zjYPXIaBDGxZVtooe4YADWO5I=
    DN: CN=kube-apiserver
    subjectAltNames:

**Comment by brendandburns** [comment]
There's some sort of problem with your certificate. It looks to me like the common name (`kube-apiserver`) doesn't match the hostname, but I'm not positive.

Does `kubectl get nodes` work correctly?

**Comment by guyrotem** [comment]
@toufunao is your cluster by any chance a local "kind" cluster? (the redacted Hostname and subjectAltNames could have been helpful here)
for testing purposes, setting cluster.insecure-skip-tls-verify to true might solve it (keeping in mind it is potentially insecure for production usage)

**Comment by lkxsoul** [comment]
Hello, I met the same problem as you, have you solved it

**Comment by liyuntian** [comment]
> Hello, I met the same problem as you, have you solved it

I met the same problem as you, have you solved it？？
