### ISSUE TITLE
Rollout Status

### ISSUE THREAD

**Issue by leimort** [kubernetes-client/java#924]
What is the equivalent command for **kubectl rollout status**?

After doing a rollout restart on a pod, I wanted to wait for all the pod instances to restart by using kubectl rollout status. Is there a command for this?

**Comment by brendandburns** [comment]
`kubectl rollout status` is a complex command not a single API call.

The golang code for it is here:
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/rollout/rollout_status.go#L162

You will need to translate that code into calls to the API via the java client.

If you end up implementing it, we'll gladly take a PR with the implementation.

**Comment by brendandburns** [comment]
If you need further info, please use the `/reopen` command to reopen the issue.
