### ISSUE TITLE
How to create istio VirtualService use this client?

### ISSUE THREAD

**Issue by CodingSinger** [kubernetes-client/java#929]
How can I access custom resources like that of istio's service entry, destination rules, virtual services from kubernetes java client?

**Comment by yue9944882** [comment]
you are free to use `CustomObjectsApi` or `KubernetesGenericApi` to access the custom resources.

**Comment by brendandburns** [comment]
Closing this issue because the question is answered. Please use `/reopen` if you need further assistance.
