### ISSUE TITLE
Adding API calls with missing optional parameters

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/java#93]
TODO: Better title.

There are many optional parameters in API calls, setting them to null would make a very ugly call like:

```java
V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
```

Also adding an optional parameter to an API call (in a newer version of kubernetes) is not backward compatible as it will add another parameter to API call in java and all code need to be updated for that.

I suggest we generate every possible variation of API call with regard to optional parameters, e.g.:

```java

// Optional _continue parameter
public V1PodList listPodForAllNamespaces(String fieldSelector, Boolean includeUninitialized, String labelSelector, Integer limit, String pretty, String resourceVersion, Integer timeoutSeconds, Boolean watch) throws ApiException {
  return this.listPodForAllNamespaces(null, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch)
}

...

// original call
public V1PodList listPodForAllNamespaces(String _continue, String fieldSelector, Boolean includeUninitialized, String labelSelector, Integer limit, String pretty, String resourceVersion, Integer timeoutSeconds, Boolean watch) throws ApiException {
...
}
```

cc @brendandburns @lwander any thoughts?

**Comment by lwander** [comment]
The client library is already quite huge, generating every possible variant for each call might make it unwieldy. Maybe a builder pattern for the calls would be better? And then use some reflection magic to apply the parameters? Or auto-generate the builders & their application E.g.

```java

ListPodsParams listParams = new ListPodsParams.builder()
  .namespace("default")
  .labelSelector("app=frontend")
  .build() // all unset fields default to `null` or something sensible

v1Client.listPods(listParams)
```

**Comment by brendandburns** [comment]
We hates the builder pattern precious, hates it! :)

I think a better approach would be a "Options" object that contains all of the potential parameters as well as sane defaults.

--brendan

Microsoft Give is happening in October!
Participate at https://aka.ms/give

________________________________

**Comment by lwander** [comment]
Heh - alright alright - what do you see the Options object being used like? I mainly just like the builder for making the `param-name -> param-value` explicit.

**Comment by brendandburns** [comment]
Note, I'm not 100% opposed, if other people want to use Builder, I can go along with that, there's certainly lots of other Java code that does...

I was thinking something like:

```java
// Sets a bunch of sane defaults for all parameters
GetPodOptions options = new GetPodOptions();
// Override some defaults
options.namespace = "some-namespace"

Make the call:
client.GetNamespacedPods(options);
```

**Comment by lwander** [comment]
SGTM - I think for the sake of consistency w/ the rest of java we should probably rely on getters & setters. We don't have to manually write those - I've been using [lombok](https://projectlombok.org/) to generate those & other useful utility functions at compile time with much success.

**Comment by mbohlool** [comment]
How do you guys see we implement this? In swagger-codegen? Is the suggestion is to keep the function with all parameters and this will be a new function (probably will be called by the function with all parameters)? If we keep the function with all parameters, that would be easier for people to use at first but their code would not be forward compatible.

I have no strong feeling about Option vs Builder approach (yet :) ).

**Comment by lwander** [comment]
It might be hard to get this into swagger-codegen - do the other clients have similar problems with the really long parameter list? Or do they (with optional parameters or something) make them easier to use?

Keeping the long parameter list public might have us repeatedly breaking clients each time that list changes.

BTW the option & builder approaches aren't exclusive, would could always just add a static nested builder class to each option class ;) Again, really easy to [do w/ lombok](https://projectlombok.org/features/Builder), there would be no need to write (or in our case generate) special code beyond the field names:

```java
@Data
@Builder
public class GetPodOptions {
  private String namespace;
  private String labelSelector;
  // ...
}
```

^ gives us both what @brendandburns & I suggested

**Comment by mbohlool** [comment]
We need to generate new classes for every call with this model. That is possible but changes the way we call APIs and also will not fix the problem for people that call into the other functions with all parameters.

I still don't want to dismiss previous idea about generating calls with default values. 

What if we:
- only generating changes from previous releases to keep compatibility. e.g. if a new optional field added, we can only add one function with that optional field missing so previous version of the client works. 
- Marking the compatibility functions `@Deprecated` and remove them in next version. The point here is to make sure people can upgrade to the new client and get access to the new features while they change their code to remove call to deprecated functions.

**Comment by brendandburns** [comment]
To be clear, I'm ok with the "generate calls with default values" approach to.

But, I actually think that we may be able to use compiler annotations to do what we need here...  I've been looking at Lombok, it's _fascinating_

--brendan


________________________________

**Comment by lwander** [comment]
Lombok is really neat

Having used the client a little, my biggest concern with generating more calls is how large each API class becomes. The `CoreV1Api.java` is 35K lines and takes a few seconds for intellij to load. Each parameter we make optional doubles that, and right now, the easiest way to get documentation on the parameters/models your passing requires you to open one the `*Api.java` classes in your editor. I think this might set us down a bad path. We could also break out each of the `*Api.java` classes by the resources they operate on to keep them smaller.

**Comment by mbohlool** [comment]
Yes, Annotation based code generators are really nice in java. I wonder if there is one for "generate calls with default values" approach. That would fix the problem of source code size.

**Comment by lwander** [comment]
That's a good point too - I don't know of one off the top of my head

**Comment by mbohlool** [comment]
https://github.com/rzwitserloot/lombok/issues/1009

and somebody did it: https://gist.github.com/dsteiner93/c717ee4aac092fe3ba98

I am sure if we dig more, we can find a better/cleaner solution. We can even dig into the solution of the second link and add it to our util package with our twists.

**Comment by mbohlool** [comment]
And more in swagger-codegen: https://github.com/swagger-api/swagger-codegen/issues/4776

**Comment by lwander** [comment]
Oh neat finds - my only concern with the dsteiner example is that the interface you end with up has a `Map<String, Object>` parameter which makes the code harder to understand.

**Comment by brendandburns** [comment]
Yeah, I'd really prefer an Options object to a Map<String, Object> map...



________________________________

**Comment by mbohlool** [comment]
Yeah, I don't like Map approach too. I was hoping we get something out of it though. but "generate calls with default values" approach is not generic enough as it cannot be done for all optional parameters when we have optional parameters of the same type adjacent to each other.

**Comment by mbohlool** [comment]
look like it is done in swagger-codegen https://github.com/swagger-api/swagger-codegen/issues/5142

I would like to see if that works for us and then if we can expand that to other strongly typed languages. Will do more research.

**Comment by mbohlool** [comment]
I marked this as release blocker as we cannot release a client that we cannot upgrade without breaking backward compatibility.

**Comment by brendandburns** [comment]
We have added an (optional) builder pattern for people to use in #323 so I'm going to close this. I think it satisfies the original request.
