### ISSUE TITLE
the dryRun alpha feature is disabled

### ISSUE THREAD

**Issue by sumool** [kubernetes-client/java#932]
The dryRun option can be used through kubectl, but the dryRun alpha feature is disabled exception will be thrown through the client api call. I am using version 1.12.5. Is this required to be set on the client?

**Comment by brendandburns** [comment]
You are using Kubernetes `1.12.5`? I'm pretty sure that server-side dry run isn't implemented in Kubernetes `1.12.5` so I wouldn't expect this to work.

`kubectl` does dry run on the client side, so that works with `1.12.5` but this client only knows how to talk to the server API.

**Comment by brendandburns** [comment]
Closing this due to lack of feedback. Please use the `/reopen` command if more help is needed.
