### ISSUE TITLE
client-java-spring-integration maven artifacts

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [kubernetes-client/java#934]
I don't seem to be able to locate the maven artifacts for Spring Integration. Is this an oversight, or is it that its not yet supported?

**Comment by brendandburns** [comment]
They should be in the `8.0.0` release. They weren't in any previous releases.

Are you using `8.0.0`?

**Comment by tony-clarke-amdocs** [comment]
I tried all versions. I don't see it released under any version. See https://mvnrepository.com/artifact/io.kubernetes

**Comment by brendandburns** [comment]
I finally took a look at this. I'm not a maven expert, but I think it _might_ be because the `pom.xml` is missing a `<packaging>bundle</packaging>` directive. I will try adding that and see what happens.
