### ISSUE TITLE
How many connections will cost when watching several resources?

### ISSUE THREAD

**Issue by fredalxin** [kubernetes-client/java#935]
It seems like kubernetes-client use websocket for watch/informer. When i watch several resources,i will cost several connections.Is it right?
client-go use http2 ,so is it always cost single connection?

**Comment by brendandburns** [comment]
Yes, kubernetes uses one connection per watch. Watch actually doesn't happen over web sockets, it is a pure hanging GET.

**Comment by brendandburns** [comment]
Closing as the question is answered. Please use the `/reopen` command if you need to reopen this issue for any reason.
