### ISSUE TITLE
Alternative for rollback mechanism of a deployment using client-java

### ISSUE THREAD

**Issue by naveen27232** [kubernetes-client/java#938]
Background- 
Cluster nodes are with master version - 1.15.9-gke.24
Our application supports upgrade of deployment in GCP wherein we patch the yaml with required version and in case of failure we rollback to previous version. 
For this rollback operation we were successfully using the method : 
               ExtensionsV1beta1Api.createNamespacedDeploymentRollback(String name, String namespace, ExtensionsV1beta1DeploymentRollback body, String dryRun, Boolean includeUninitialized, String pretty). 

But now we are upgrading our clusters to support gke version 1.16. In order to move to Kubernetes version to 1.16 on our cluster we are using client-java: version 8.0.0 , and we need to migrate the above apis to apps/v1.
Referring the blog- blog- 'https://urldefense.proofpoint.com/v2/url?u=https-3A__kubernetes.io_blog_2019_07_18_api-2Ddeprecations-2Din-2D1-2D16_&d=DwICaQ&c=y9ER7-XqJ9hjToafeR_J2A&r=xqezmUkGUOGf4WN9aYZZP1ZqP6vETLZ9fspb9rX2rxI&m=7IB5rNV6qdBigkieJ2j2D759BEi9lUGQN_Uf60K2zaQ&s=6V3CTkN14mH6ofcBo5aUEUk74FlW4HQ9a-cIZWVffEk&e= '

However the parameter 'ExtensionsV1beta1DeploymentRollback' & 'ExtensionsV1beta1RollbackConfig' have been deprecated.
So we could not find the alternative for this function or its parameters. Please suggest what can be used as an alternative in this scenario if we migrate to apps/v1 from ExtensionsV1beta1Api.

**Comment by HiremathPanchaxari** [comment]
I am also looking for the alternative rollback api in client library 8.0.0. please suggest which one to use

**Comment by brendandburns** [comment]
Deployments moved from `extensions` to `apps` so what you're looking for is here:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/AppsV1beta1RollbackConfig.java

**Comment by HiremathPanchaxari** [comment]
> Deployments moved from `extensions` to `apps` so what you're looking for is here:
> 
> https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/AppsV1beta1RollbackConfig.java

Why these are marked as Deprecated ? When will there will a replacement for these api ?

**Comment by naveen27232** [comment]
hi @brendandburns : As stated by HiremathPanchaxari , these are the still deprecated and we cannot use them so we need some alternative in apps/v1 in 8.0.0 which is not deprecated
see
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Regards
Naveen

**Comment by HiremathPanchaxari** [comment]
hi @brendandburns, 

Are you suggesting, that we use the deprecated AppsV1beta1RollbackConfig for rollback until a new version client java library ?

**Comment by dengyongfu** [comment]
> 部署从迁移到`extensions`，`apps`因此您需要的是这里：
> 
> https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/AppsV1beta1RollbackConfig.java

404  了

**Comment by HiremathPanchaxari** [comment]
hi @brendandburns 
AppsV1beta1RollbackConfig.java are not available in https://github.com/kubernetes-client/java/tree/client-java-parent-10.0.1 ? it was available client-java-parent-9.X. Can you suggest on this ?
