### ISSUE TITLE
Is there an api equal to `kubectl get deployment,configmap,secret -l labelKey=labelValue`

### ISSUE THREAD

**Issue by liuming-dev** [kubernetes-client/java#939]
kubectl provides the following function:

```bash
~/.kube » kubectl get deployment,pod -l paas.sogou.com/app=spring-boot-sample -n bizdev
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/spring-boot-sample   1/1     1            1           7d22h

NAME                                      READY   STATUS    RESTARTS   AGE
pod/spring-boot-sample-568c87c6f5-k7td4   1/1     Running   0          13h
```

And I want to know if there is an function-equal api in kubernetes java client? Thanks.

**Comment by rjeberhard** [comment]
It looks like kubectl just does one search and then the other.

**Comment by brendandburns** [comment]
There's no bulk action for multiple gets. You need to do a get for each resource type (`deployment`, `pod`).

You can specify the label query when you do the get to do the label-based filtering.

**Comment by brendandburns** [comment]
Closing this issue since the question is answered. Please use `/reopen` if you need to get more information for any reason.
