### ISSUE TITLE
Multiple leaders arising from leader election example code?

### ISSUE THREAD

**Issue by pnathan** [kubernetes-client/java#940]
Hi,
I worked through the example code and my system is running well, except for the fact that the pods all seem to elect themselves as leader. While mildly politically amusing, it doesn't really solve the engineering requirement of having only 1 node execute.

Using this leader election code as a base - 
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java#L113-L123

Working backwards looking at where I've modified the code (some refactoring into methods from lambdas occurred): 
```
        Controller controller =
                ControllerBuilder.defaultBuilder(informerFactory)
                        .watch(this::watcherOfQueue)
```

watcherOfQueue is:
```
        return ControllerBuilder.controllerWatchBuilder(MyCRD.class, workQueue)
                .withWorkQueueKeyFunc(this::onEvent)
                .withOnUpdateFilter(this::onUpdate)
                .build();
```

And my _expectation_ here is that onUpdate and onEvent will only be called for the leader node.
Please advise if my expectation is wrong.

**Comment by erikgb** [comment]
@pnathan Remember to set the last parameter in https://github.com/kubernetes-client/java/blob/4cd1cbdd4aed0ba50ebb7f07bfe884764193c6f1/extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java#L34 to something distinct for each Pod. If not the leader election will not work. I have used the Pod hostname as `identity`, but you can use any value unique for the Pod. My EndpointLock:
```java
String identity = InetAddress.getLocalHost().getHostName();
EndpointsLock lock = new EndpointsLock(namespace, name, identity);
````

**Comment by yue9944882** [comment]
the leader election example is updated for clarification #1013

**Comment by pnathan** [comment]
Thanks, @erikgb . Didn't pick that up in my studies of the code, I had held it constant. I'll give that a test, but I expect it to be the problem.

& thanks, @yue9944882 for the updated docs.
