### ISSUE TITLE
Patch StatefulSet with Json array does not work

### ISSUE THREAD

**Issue by vladut2403** [kubernetes-client/java#942]
Hi,

I am trying to patch a statefulset, the nodeAffinity part. This is how it looks like:

      affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: kubernetes.io/hostname
             operator: NotIn
             values: 
             - testNode

I am trying to patch and replace the matchExpression , this is the body in patchNamespacedStatefulSet() my java code:

`[
   {
      "op":"replace",  "path":"/spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/",
      "value":"{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":\"In\",\"values\":[\"patchNodeTest\"]}]}]}"
   }
]`

It seems that the response is **ok**, but the internal structure of V1StatefulSet is unchanged:

            spec: class V1PodSpec {
                activeDeadlineSeconds: null
                affinity: class V1Affinity {
                    nodeAffinity: class V1NodeAffinity {
                        preferredDuringSchedulingIgnoredDuringExecution: null
                        requiredDuringSchedulingIgnoredDuringExecution: class V1NodeSelector {
                            nodeSelectorTerms: [class V1NodeSelectorTerm {
                                matchExpressions: [class V1NodeSelectorRequirement {
                                    key: kubernetes.io/hostname
                                    operator: NotIn
                                    values: [testNode]
                                }]
                                matchFields: null
                            }]
                        }
                    }

I tried directly from console and it worked:

`kubectl patch statefulset my_stateful_set --patch '{"spec":{"template":{"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"NotIn","values":["testNode1"]},{"key":"kubernetes.io/hostname","operator":"NotIn","values":["testNode2"]}]}]}}}}}}}'`

I can't find any relevant examples on how to patch a with a value that is a whole json array.
I've also tried with operator 'add' and same result.

**I am using kubernetes-client 5.0**

Any ideas? Thank you!

**UPDATE**

It seems that with the **add** operator it adds the same matchExpression twice and it does not put my requested values from the json:

                            "matchExpressions": [
                                {
                                    "key": "kubernetes.io/hostname",
                                    "operator": "NotIn",
                                    "values": [
                                        "testNode"
                                    ]
                                },
                                {
                                    "key": "kubernetes.io/hostname",
                                    "operator": "NotIn",
                                    "values": [
                                        "testNode"
                                    ]
                                }
                            ]

**Comment by brendandburns** [comment]
I _think_ it might be the trailing `/` on your `path` but I'm not certain.

What `content-type` are you sending for your patch?

Since the patch is being accepted with an `HTTP 200 OK` I think that this is more about the syntax of the patch than anything this client is doing. I would validate the contents of the patch that kubectl sends using `kubectl --v=10 patch ...` and looking at the raw JSON that it sends across the wire.

**Comment by vladut2403** [comment]
> using kubectl --v=10 patch ...

Request Body: {"spec":{"template":{"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"NotIn","values":["testNode"]},{"key":"kubernetes.io/hostname","operator":"NotIn","values":["testNode"]}]}]}}}}}}}

I0504 19:16:18.976804   11135 round_trippers.go:419] curl -k -v -XPATCH  -H "User-Agent: kubectl/v1.13.3 (linux/amd64) kubernetes/721bfa7" -H "Accept: application/json" **-H "Content-Type: application/strategic-merge-patch+json"**

**Comment by vladut2403** [comment]
@brendandburns 

This is what I've tried and now the response is 500 Internal Error:

`[{"op":"add","path":"/spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms","value":"[{\"matchExpressions\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":\"NotIn\",\"values\":[\"testNode\"]}]}]"}]`

It seems that the problem is not with the value (because I had it empty and the same error appeared), but with the path.
This is the path in the JsonObject:

`path="/spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms"`

And this is the response body:

[ERROR] `{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"v1.StatefulSet.Spec: v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Affinity: v1.Affinity.NodeAffinity: v1.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution: v1.NodeSelector.NodeSelectorTerms: []v1.NodeSelectorTerm: decode slice: expect [ or n, but found \", error found in #10 byte of ...|orTerms\":\"[{\\\"matchE|..., bigger context ...|lingIgnoredDuringExecution\":{\"nodeSelectorTerms\":\"[{\\\"matchExpressions\\\":[{\\\"key\\\":\\\"kubernetes.io/h|...","code":500}`

What causes this error ?

The actual deserialized json by ApiClient should be like this:

`{"nodeSelectorTerms": [{"matchExpressions": [{"key": "kubernetes.io/hostname","operator": "NotIn","values": ["kmaster"]}]}]`

**Comment by vladut2403** [comment]
Finally got it. I was putting the json value by hand(hardcoded) which was wrong. So I created 2 POJOs which solved the problem:

```
public class NodeAffinityMatchExpression
{
    @SerializedName("key")
    private String key;

    @SerializedName("operator")
    private String operator;
    
    @SerializedName("values")
    private Object values;
```

```
public class NodeSelectorTerms
{
   @SerializedName("matchExpressions")
   private List<NodeAffinityMatchExpression> matchExpressions;
```
