### ISSUE TITLE
how to update deployment

### ISSUE THREAD

**Issue by githubyangxd** [kubernetes-client/java#946]
Hello master:
I want to change k8s deployment configration，my key code:
**(1)AppsV1Api config:**
@Configuration
public class K8sConfig {
    @Autowired
    private K8sProperties k8sProperties;
    @Bean
    public AppsV1Api appsV1Api() throws IOException {
        ClassPathResource resource = new ClassPathResource(k8sProperties.getK8sConfigPath());
        ApiClient client = Config.fromConfig(resource.getInputStream());
        return new AppsV1Api(client);
    }
}
**(2)service:**
@Service
public class TestService {
    @Autowired
    CoreV1Api coreV1Api;

    @Autowired
    AppsV1Api appsV1Api;

    public void test01() {
        System.out.println("00");
    }

    public void test02() {
        //deployment name 
        String name = "operate-demo";
        String nameSpace = "extdev";

        V1Patch v1Patch = new V1Patch("[{\"op\": \"replace\", \"path\": \"spec/replicas\", \"value\":2}]");
        String pretty = "true";
        String dryRun = null;
        Boolean force = null;
        try {
            V1Deployment v1Deployment = appsV1Api.patchNamespacedDeployment(name, nameSpace, v1Patch, pretty, dryRun, null, force);
            System.err.println("#######" + v1Deployment);
        } catch (ApiException e) {
            e.printStackTrace();
        }
    }

**(3)k8s config:**
kind: Deployment
apiVersion: apps/v1
metadata:
  name: operate-demo
  namespace: extdev
  selfLink: /apis/apps/v1/namespaces/extdev/deployments/operate-demo
  uid: a85a2aa1-9ac6-4b30-bc65-03d2a6054fc1
  resourceVersion: '29332392'
  generation: 2
  creationTimestamp: '2020-04-29T11:48:07Z'
  labels:
    app: operate-demo
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  ......

**The phenomenon of description:**
I want to change replicas = 2 ,but don't take effect, still =1,

Ask the master for guidance

**Comment by brendandburns** [comment]
Patch is complicated to use, I would recommend starting with replace rather than patch.

Also using `kubectl --v=10 ...` will print a bunch of JSON and HTTP information that will help you learn what is going on.

**Comment by brendandburns** [comment]
Closing as I believe the question is answered and no further requests. Please use `/reopen` if you need anything further.
