### ISSUE TITLE
please describe method parameters in detail

### ISSUE THREAD

**Issue by githubyangxd** [kubernetes-client/java#947]
I find lots of methods haven't detail describe，let user don't know how to use  kubernetes-client .
Can you explain each method in detail , make the api more learner. Thank you

**Comment by brendandburns** [comment]
There's extensive documentation here:
https://github.com/kubernetes-client/java/tree/master/kubernetes/docs

And lots of JavaDoc (e.g. https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/apis/ApiextensionsV1Api.java#L65)

What additional documentation are you looking for?

**Comment by brendandburns** [comment]
Closing due to lack of response. Please use `/reopen` if you need further assistance.
