### ISSUE TITLE
Publish/release the java client version 8.0.2 to maven central

### ISSUE THREAD

**Issue by zzur** [kubernetes-client/java#951]
Follow-up to #945 which got closed, yet not fixed.

The fix for #945 ended up pushing a snapshot version (8.0.1-SNAPSHOT) to sonatype. This is to track the work as commented there, for publishing a 8.0.2 instead.

**Comment by zzur** [comment]
Just FYI, main reason for asking for this release is to get fix for a bug in 8.0.0 where watches don't work in the generic (extended) API (there might be other goodness in there, donno ...)

**Comment by zzur** [comment]
Any update on this would be appreciated. Specifically interested to know if this would be interested to have a window of time for this getting addressed so we can make a decision if to wait - we very much interested to use the statically typed generic api with watches, or just to work around by using the type unsafe crd api till there is a new release...

**Comment by brendandburns** [comment]
Sorry for the delay, I pushed this to Sonatype today, expected in Maven Central in ~1 day (replication delay from observation)

**Comment by zzur** [comment]
Many many thanks
