### ISSUE TITLE
Improvement for uncaught exception in Reconciler

### ISSUE THREAD

**Issue by hinyinlam-pivotal** [kubernetes-client/java#961]
This is a question about running reconciler as worker threads and its potential improvement.

The current way of running Reconciler started in [`DefaultController`](https://github.com/kubernetes-client/java/blob/client-java-parent-8.0.2/extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java#L105) by [`ScheduledThreadPoolExecutor.scheduleWithFixedDelay`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#scheduleWithFixedDelay-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-)

The [`ScheduledThreadPoolExecutor.scheduleWithFixedDelay` Java doc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#scheduleWithFixedDelay-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-) stated that  `If any execution of the task encounters an exception, subsequent executions are suppressed`

Therefore, if the `Reconciler.reconcile` method have uncaught exception, the thread running in ThreadPool will be suppressed (ie won't start another thread -- lost).

Even with multiple worker threads, a tricky bug that causing uncaught exception in reconcile will gradually causing all worker threads to lost.

A demo of thread dead and no further execution of `ScheduledThradPoolExecutor` is available [here](https://gist.github.com/hinyinlam-pivotal/15bae62658097c70b65732a27e557eca)
Please note there is some comment in the demo to test out the behavior of `Reconciler.reconcile` with uncaught exception.

As of latest version 8.0.1 of K8S Java Client SDK, there is no capture of uncaught exception and is no method for detection/resurrect of abnormal exit threads, so I believe there is room for future improvement.

What design choices we can go for K8S Java SDK Client?
1. Should the controller developer uses `Try-Catch-All` in `Reconciler.reconcile` code to avoid uncaught exception escaping entirely? (ie keep how the current client behaviour)
2. Is there any way we can use alternative executor or implement resurrector/restart pattern for a failed worker thread and replace with a new thread?

Or what other design pattern we can target to improve self-healing and high availability within a single controller?

**Comment by yue9944882** [comment]
> What design choices we can go for K8S Java SDK Client?

thank you for reporting this @hinyinlam-pivotal, the reconciler implementation is originally ported another golang library [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)  in which any worker thread/routines aborted the entire golang process to expected to crash and exit. while this behavior can be inappropriate for java applications. i'm slightlly leaning on the 1st idea on fixing this as a prompt fix.
