### ISSUE TITLE
Error:java: io.sundr.SundrException: No getter found for property: instance on class: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImpl

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#964]
Hi,

I am trying to run examples under Master Branch in IntelliJ Idea and I am getting below error along with warnings.
Error:java: io.sundr.SundrException: No getter found for property: instance on class: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImpl
Warning:java: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.BuildableProcessor, returning RELEASE_6.
Warning:java: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.BuildableProcessor' less than -source '1.7'
Warning:java: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.ExternalBuildableProcessor, returning RELEASE_6.
Warning:java: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.ExternalBuildableProcessor' less than -source '1.7'

Thanks

**Comment by brendandburns** [comment]
What version of the JDK are you using?

**Comment by saparaj** [comment]
Java 1.8.0

**Comment by bjrara** [comment]
For anyone who meets the same issue, try `mvn clean` first.

In my case, after removing all the generated files, intellij threw me error: `internal java compiler error`. I solved the second issue by increasing the build heap size.
