### ISSUE TITLE
Load multiple resources via Single YAML file

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#965]
Hi, I am trying to load YAML file which consists of resources like Deployment, Service and Ingress separated by '---'. I am using method yaml.loadAll(new FileReader(fileName)) to get list of objects. Is there anywhere we have API class mapping to Resource class so that I can call respective API create methods?
example: 
for V1Deployment --> AppsV1Api  --> createNamespacedDeployment
V1Service -->  CoreV1Api api --> createNamespacedService
ExtensionsV1beta1Ingress --> ExtensionsV1beta1Api --> createNamespacedIngress

Thanks

**Comment by brendandburns** [comment]
There's no such mapping currently. It could be dynamically loaded from the API discovery info on the Kubernetes server and then you could use the GenericAPI Client:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java

But that work hasn't been done. We'd welcome a PR doing it though.

**Comment by saparaj** [comment]
Thanks I will look the example provided. For now I have implemented something like below:

public class KubeDLCExample {
  private interface Handler {
    void handle(Object o) throws ApiException;
  }
  // Make a map that translates a Class object to a Handler
  private static final Map<Class, Handler> apiCallByClass = new HashMap<Class, Handler>();

  // public static init map
  static {
    apiCallByClass.put(
        V1Deployment.class,
        new Handler() {
          public void handle(Object o) throws ApiException {
            createDeployment((V1Deployment) o);
          }
        });
    apiCallByClass.put(
        ExtensionsV1beta1Ingress.class,
        new Handler() {
          public void handle(Object o) throws ApiException {
            createIngress((ExtensionsV1beta1Ingress) o);
          }
        });

    apiCallByClass.put(
        V1Service.class,
        new Handler() {
          public void handle(Object o) throws ApiException {
            createService((V1Service) o);
          }
        });
  }
public static void main(String[] args) throws IOException, ApiException {

public static void loadAllResources(String content) throws IOException, ApiException {
    Yaml yaml = new Yaml();
    List<Object> listObj = yaml.loadAll(content);
    for (Object obj : listObj) {
      Handler h = apiCallByClass.get(obj.getClass());
      if (h != null) h.handle(obj);
    }
  }
}

**Comment by sarveshkaushal** [comment]
> There's no such mapping currently. It could be dynamically loaded from the API discovery info on the Kubernetes server and then you could use the GenericAPI Client:
> 
> https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java
> 
> But that work hasn't been done. We'd welcome a PR doing it though.

I would like to give it a try. But it will help if you could provide more information on the implementation to be done.
