### ISSUE TITLE
Is there any tunnel option for KubeApi

### ISSUE THREAD

**Issue by tutaidalal** [kubernetes-client/java#977]
My cluster master IP is private to a network and I access the master using a jump server using SSH. Is there any way to access API from my PC via jump server ?

**Comment by brendandburns** [comment]
You have to set up the network tunnel yourself (e.g. SSH tunnel for example or some other VPN) this library just uses whatever network you have setup.

**Comment by tutaidalal** [comment]
Yes, solved it by using sshj tunnel . Thanks for the support
