### ISSUE TITLE
how to get kubernetes version by client api 

### ISSUE THREAD

**Issue by zyq1994** [kubernetes-client/java#984]
just like kubectl version

**Comment by brendandburns** [comment]
The URL is:

```
https://<master-ip>:443/version?timeout=32s
```

But as far as I know this client doesn't have code to access it currently. It wouldn't be hard to add, but I don't think it's in the swagger/openapi document that Kubernetes currently publishes.

I'll keep this issue open so that someone can implement it.

**Comment by rjeberhard** [comment]
io.kubernetes.client.openapi.apis.VersionApi

**Comment by zyq1994** [comment]
![image](https://user-images.githubusercontent.com/23446769/86590324-f3513400-bfc1-11ea-9801-1c4d3b695042.png)
thank you

**Comment by brendandburns** [comment]
Closing this since apparently it's possible (and `KubectlVersion` was also added)
