### ISSUE TITLE
pom.xml do not get the necessary to run the example.java

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [kubernetes-client/java#99]
Hi! I set the pom with the specified maven dependency, but the is no **Config class** to import.
![config](https://user-images.githubusercontent.com/4364432/31695842-4a2b97dc-b383-11e7-8b7e-e3d73c995ecc.png)

What is wrong?

check the pom.xml
![xml](https://user-images.githubusercontent.com/4364432/31695902-996ebea0-b383-11e7-91e0-bc441534dd70.png)

**Comment by lwander** [comment]
Can you import 

`import io.kubernetes.client.util.Config

or is the editor just not suggesting it?

**Comment by ViniciusDeAndrade** [comment]
It is a little strange because the package explore do not show anything "inside" the Config.class tree item.
I am sending a screenshot to show the idea of the bug.

![class](https://user-images.githubusercontent.com/4364432/31719444-df6b5d44-b3e9-11e7-87c1-66a8470f51d7.png)

See in the package explore that there is a KubeConfig.class file, and it can be expanded, showing the KubeConfig class. It cannot be made with the Config.class file. So, the example given by this kubernetes-client java cannot work properly.

**Comment by lwander** [comment]
Are you able to build your code when you import the config class? If so, maybe something needs to be reconfigured in your editor.

**Comment by lwander** [comment]
As an example, we're using this client at the 1.0.0-beta1 release just fine here: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java#L152

**Comment by lwander** [comment]
And here is an example of an editor opening the dependency: 
![editor](https://user-images.githubusercontent.com/4874941/31721473-7dd3ee36-b3e7-11e7-87e3-02e3a5af6a21.png)

**Comment by ViniciusDeAndrade** [comment]
I will try to use another IDE so. In fact, when I try to use "alt + F5" to check the "force update of snapshots/releases", the editor do not save what I just did. I know that because I open it again and see it unchecked.

Maybe it is really a eclipse problem. I have tryed to use it on windows, besides ubuntu. I guess it is time to try .... Netbeans.

Thanks for your help

**Comment by ViniciusDeAndrade** [comment]
I finally fixed it!
There was an error on maven cache

Thank you!

**Comment by lwander** [comment]
Glad it works!
